### ISSUE TITLE
.hh files (HHVM) incorrectly recognized as C++

### ISSUE THREAD

**Issue by fredemmott** [github/linguist#1000]
While some of these are C++ headers, some are Hack, a language supported by HHVM. It's very similar to PHP.

Files recognized by HHVM will start with <?hh

Example: https://github.com/fredemmott/hh_extension_toolset/blob/master/src_classmap/Foo/Bar/Baz.hh

**Comment by staabm** [comment]
Created a pygments issue, https://bitbucket.org/birkenfeld/pygments-main/issue/1071/add-support-for-hack-files

**Comment by arfon** [comment]
Hey @staabm - this isn't a pygments thing: https://github.com/github/linguist/pull/1669#issuecomment-68524699

**Comment by staabm** [comment]
Hey! Thx for the info. It wont hurt in case they add support for it ;).
