### ISSUE TITLE
HTML?

### ISSUE THREAD

**Issue by danieldiekmeier** [github/linguist#1019]
Hey,

I'm not sure if this has been answered a thousand times before, but I was wondering why HTML isn't picked up in any repo's language reporter, but CSS and JavaScript are.

One could debate if HTML really is a programming language, but I think that's beyond the point here. If I visit a repo that consists of HTML files and one CSS-file, I want that reflected in the colored bar at the top.

Regards,
Daniel

**Comment by eReGeBe** [comment]
This issue still shows up on a google search of "html linguist", so for those looking you can mark languages not marked as "programming" as detectable -> https://github.com/github/linguist#detectable

**Comment by pchaigno** [comment]
@eReGeBe HTML is a `markup` language for Linguist. `markup` languages are already "detectable". What might happen however is that some of your files are marked documentation and not counted in statistics. You can change that with:
```
$ cat .gitattributes
path-to-html-files/* linguist-documentation=false
```
