### ISSUE TITLE
SQL is marked as data type

### ISSUE THREAD

**Issue by TheFrozenFire** [github/linguist#1044]
SQL is currently specified as [type: data](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L1566) in languages.yml. This is causing [my repository](https://github.com/TheFrozenFire/StoredProcedureWeb), which is overwhelmingly SQL, to be shown as completely PHP and Shell.

SQL should be marked as `type: programming`, as it's clearly a procedural programming language, and is defined in its [Wikipedia entry](http://en.wikipedia.org/wiki/SQL) as "a special-purpose programming language".

**Comment by yangsoosong** [comment]
@Shoelace You can now [override](https://github.com/github/linguist/blob/master/README.md#detectable) language definitions and file paths. You just need to make sql detectable for linguist library.
Adding `*.sql linguist-detectable=true` in `.gitattributes` solved this issue for me!
