### ISSUE TITLE
.tst files identified as SciLab - not scilab

### ISSUE THREAD

**Issue by ryancoleman** [github/linguist#1066]
For instance: https://github.com/ryancoleman/traveldistance/search?l=scilab

These files are not scilab files. I looked at https://github.com/github/linguist/blob/master/lib/linguist/languages.yml and can't see why they are marked as such, as the entry for scilab doesn't contain anything like .tst

It would be great as these .tst files are data files for some scientific code that is now 10 years old, and erroneously making some of my projects identify as the wrong language. Again, I can't figure out why they are marked like this or I'd fix it myself. Thanks.

**Comment by arfon** [comment]
@ryancoleman - if you would like to manually override these erroneous detections that you can do so using the Linguist Overrides: https://github.com/github/linguist#overrides

Given your statement about this being an old codebase and these being data files it might just be worth setting `linguist-vendored=true` for these files
