### ISSUE TITLE
QML not detected at all

### ISSUE THREAD

**Issue by strahlex** [github/linguist#1152]
My repository: https://github.com/strahlex/QtQuickVcp is marked as mainly C++, however, it is mainly QML. QML files seem to be ignored at all. Would be easy to identify them by the file extension .qml.

**Comment by arfon** [comment]
> This problem already occurred with SQL when it was set to programming.
Maybe we could set QML to programming and see if anyone comes here to complain.
@arfon Any thoughts about this?

@pchaigno - I have no serious objections to this. @bkeepers - what do you think ?

**Comment by arfon** [comment]
:flags: flagging this as stale.

**Comment by roschern** [comment]
I was under the impression this would be marked as a code from now on. Did that not happen?

**Comment by pchaigno** [comment]
@arfon I think @roschern is right :). Should I open a PR?

**Comment by arfon** [comment]
> @arfon I think @roschern is right :). Should I open a PR?

Yeah, let's try it out.

**Comment by pchaigno** [comment]
Done.
