### ISSUE TITLE
Bash shell script repository incorrectly marked as PHP

### ISSUE THREAD

**Issue by stefaniuk** [github/linguist#1185]
One of my repositories [mintleaf-shell](https://github.com/codeworksio/mintleaf-shell) contains only shell script code but is incorrectly marked as PHP.

**Comment by pchaigno** [comment]
@stefaniuk The issue with [your repository](https://github.com/codeworksio/mintleaf-shell) seems fixed?

**Comment by stefaniuk** [comment]
Yes, it is fixed. Now, I can see it as a `Shell` repo. Perfect, thanks.

**Comment by pchaigno** [comment]
Great! You're welcome. Thanks for reporting the issue :-)
