### ISSUE TITLE
Detect DB2's Procedure language (SQL-PL)

### ISSUE THREAD

**Issue by angoca** [github/linguist#1204]
I have developed a couple of projects in IBM's SQL-PL, which is a Procedure language. However, the language analyse in GitHub says this is SQL, and I know it is based on linguist.

The language documentation is here: http://pic.dhe.ibm.com/infocenter/db2luw/v10r5/topic/com.ibm.db2.luw.apdv.sqlpl.doc/doc/c0011916.html

My projects use many elements of this language:
* https://github.com/angoca/log4db2
* https://github.com/angoca/db2unit

**Comment by arfon** [comment]
This should be fixed in https://github.com/github/linguist/pull/2175 . These changes should be live on GitHub in the next week or so.
