### ISSUE TITLE
TSV data file classified as SQL

### ISSUE THREAD

**Issue by vdemario** [github/linguist#1218]
There is a file called birch_unigenes_annotation.tab in [GOParGenPy](http://ekhidna.biocenter.helsinki.fi/users/ajay/private/GOParGenPy.htm) which is a tab-separated data file, around 21k lines and 18M in size, that file gets erroneously classified as SQL.

ps: sorry, can't point to a repository, the only one I've seen containing that file is private. I could create a brand new repository and add the file if it helps

**Comment by arfon** [comment]
Hi @vdemario - please take a look at using the [Linguist overrides](https://github.com/github/linguist#overrides) to fix this. If it's a general issue then we could look at doing some additional work on Linguist to address this.
