### ISSUE TITLE
netCDF data files (extension .nc) identified as nesC

### ISSUE THREAD

**Issue by hereidk** [github/linguist#1345]
I have some Python code that extracts data from a netCDF file, a data storage file type commonly used in climate science datasets.  This repository is incorrectly classified as nesC, presumably because of the .nc file extension.  Thanks.

[Drought](https://github.com/hereidk/Drought)

Edit: And I just saw that others have had this issue as well: [#958](https://github.com/github/linguist/issues/958)

**Comment by arfon** [comment]
This seems to be fixed now.

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
This is still not fixed
