### ISSUE TITLE
Allow specifying an ignore file for language statistics

### ISSUE THREAD

**Issue by davidfowl** [github/linguist#137]
Some repositories (like [SignalR](https://github.com/SignalR/SignalR)), have samples that include common javascript libraries like jQuery etc. and github ends up classifying the project as javascript instead of C# (in this particular case). Nothing is wrong with this at a high level since jQuery **is** javascript, but for project maintainers that want more control over statistics need a way to opt out of this behavior. 

I see 2 options:
- **Short term hack:** Exclude commonly used js files. This will handle some scenarios but you'll have to exclude multiple versions of the library (unless you had wildcard support).
- **Longer term solution:** Allow a repository to have a .lignore or equivalent (I suck a naming) that uses glob syntax to exclude files to be processed for language statistics.

**Comment by arcanis** [comment]
Will this file (`.gitattributes`) also be used for github stats? It's always a bit disappointing to see all stat charts destroyed when commiting vendors to the tree. On one repo I have about 935,827 ++ / 849,501 --. I'm not that much productive :smile:

**Comment by David-OConnor** [comment]
See this repo: https://github.com/David-OConnor/fplot

It's showing as 98.5% Jupyter Notebook, because I included an example notebook as part of the documentation.

**Comment by pchaigno** [comment]
@arcanis It's a good idea I think. It's not something that can be implemented in Linguist however; you should suggest it to GitHub support. Might be a bit more difficult to implement for them though.

**Comment by ravicious** [comment]
To anybody still finding the issue through Google like me, [Linguist now treats code under certain paths as vendored by default](https://github.com/github/linguist#vendored-code) and doesn't include them in the stats.

**Comment by trevorhackman** [comment]
Do lines in Linguist vendored files still count towards line additions/deletions?

**Comment by lildude** [comment]
> Do lines in Linguist vendored files still count towards line additions/deletions?

You can easily test this 😉

**Comment by Kroc** [comment]
I include binaries in a '/bin' directory for out-of-the-box build functionality. It seems too obvious that excluding a 'bin' directory has not already been discussed / rejected! Should I file an issue, or is this a won't-fix?

**Comment by Alhadis** [comment]
@Kroc It's a won't-fix. Linguist only scans textual formats and doesn't even acknowledge binary files. Moreover, this would severely affect repositories with executable scripts in `/bin` directories (which *should* count towards language statistics).

**Comment by Kroc** [comment]
My bin folder contains the documentation for those binaries! It's weighting the statistics entirely toward HTML, a format I don't use at all in the actual project: https://github.com/Kroc/pling (it's all assembly). Could you ignore sub-folders of /bin, or is this cutting off other use-cases?

**Comment by Alhadis** [comment]
@Kroc This is all explained in our readme. Please read [the section on overrides](https://github.com/github/linguist#overrides) for the solution to your problem.

**Comment by jmrico01** [comment]
Updated link to overrides doc: https://github.com/github/linguist/blob/master/docs/overrides.md
