### ISSUE TITLE
Drop requirement for shell scripts to be executable

### ISSUE THREAD

**Issue by mcandre** [github/linguist#1453]
Please consider dropping the requirement for shell scripts to have executable permissions in order to be syntax highlighted, or at least offer a customization variable for this.

As an academic, I often post the same command line script in a variety of forms for illustration. I would *still* like my shell scripts to be highlighted according to their shebangs, regardless of a lack of file extension and executable permissions.

**Comment by arfon** [comment]
Pretty sure this is fixed now that we detect by shebang early in the classification process. https://github.com/transcode-open/apt-cyg/blob/41e1d91/apt-cyg for example is correctly classified as `Shell` even though it's not executable.

LMK if I'm wrong about this but closing this out unless corrected.

**Comment by svnpenn** [comment]
@arfon yeah, it looks to be fixed now
