### ISSUE TITLE
Exclude vendor folders when calculating additions and deletions

### ISSUE THREAD

**Issue by milani** [github/linguist#1469]
In a project, our team uses cocoapods. We added `Pods` folder to the repo because cocoapods does not guarantee exact copies of generated files in different systems.

Now the problem is that `Pods` is not considered as a vendor folder also it is defined in Linguist's  vendor.yml so I now see Ruby as a language in the repo and big numbers for additions and deletions in graphs page.

**Comment by rcedwards** [comment]
This seems like a valid issue.

Is there a reason why:

> We can't do anything for the numbers in additions/deletions...

@pchaigno

**Comment by lildude** [comment]
> Is there a reason why:
> 
>> We can't do anything for the numbers in additions/deletions...

Yup, because it’s not a function of Linguist but rather the GitHub.com code. The “we” is referring to Linguist, not GitHub, hence the follow up suggestion of contacting GitHub’s support team.
