### ISSUE TITLE
Add Windows Batch Language

### ISSUE THREAD

**Issue by Kwimbee** [github/linguist#1483]
Please add the windows "Batch" Language.

It's still used by some people and tagged as Shell by Github.

Thanks

**Comment by arfon** [comment]
:flags: - flagging this as stale.

**Comment by arfon** [comment]
> @bkeepers In light of #1548, should we just remove Batch from the Shell group?

Crazy slow response here but @pchaigno I think this is the correct way to proceed.

**Comment by bkeepers** [comment]
doh, sorry for dropping the ball.
