### ISSUE TITLE
TorqueScript files falsely recognized as C#

### ISSUE THREAD

**Issue by Wuzzy2** [github/linguist#1512]
TorqueScript is a scripting language used by Torque3D, a game engine.
https://github.com/GarageGames/Torque3D

Linguist falsely attributes TorqueScript source files as C#.

Here is a project where 8.5% are falsely attributed to C#, where the source code is actually in TorqueScript:
https://github.com/fr1tz/terminal-overload

Sadly, it’s syntax of TorqueScript looks similar to C# and also the preferred file suffix is “.cs” (like for C#), so it is probably not easy to distinguish both languages.

TorqueScript documentation:
http://docs.garagegames.com/tgea/official/content/documentation/Scripting%20Reference/Introduction/TorqueScript.html

**Comment by arfon** [comment]
@eightyeight - is the any news on this possible switch? I wonder if there are any heuristics we could use here to disambiguate C# abd Torque 3D

**Comment by eightyeight** [comment]
@arfon no news yet. We're waiting till a major version to make the switch, as it'll affect our users significantly. But even after the official repo makes the switch, a lot of legacy `.cs` extensions will remain in other repos, I imagine. As for heuristics, presence of the `function` and `datablock` keywords would be the easiest, I think. IIRC neither of those exist in C#. What other sorts of heuristics are there? `$=` operator could be one.

**Comment by arfon** [comment]
OK thanks for the update @eightyeight. You can see how we've resolved a previous clash on `.cs` with Smalltalk [here](https://github.com/github/linguist/pull/2003) and https://github.com/github/linguist/blob/master/lib/linguist/heuristics.rb#L72-L78.

`$=` and `datablock` seem pretty good candidates. @bkeepers @pchaigno what do you think?

**Comment by eightyeight** [comment]
I'd be willing to work up a PR if you'd like :).

**Comment by pchaigno** [comment]
:+1: 

@eightyeight You'll have to be a little more specific when making the heuristic with `function` for Torque Script; [it's quite frequent to have this word in comments](https://github.com/search?o=asc&q=extension%3Acs+function+OR+datablock&ref=searchresults&s=indexed&type=Code&utf8=%E2%9C%93) ([the same applies to `datablock` but less often](https://github.com/search?utf8=%E2%9C%93&q=extension%3Acs+datablock&type=Code&ref=searchresults)).
Also, for the pull request you "just" have to extend the block for C# and Smalltalk with your heuristic rule(s) for TorqueScript (and add some tests [here](https://github.com/github/linguist/blob/master/test/test_heuristics.rb#L143-L148)).

**Comment by eightyeight** [comment]
Good point, I forgot about comments. So here's what I'm thinking currently:

 * look for `datablock`
    * _not_ preceded by `class`
    * followed by `something(`, where `something` is an identifier
 * look for `function`
    * _not_ preceded by anything but whitespace on the same line
    * followed by `something (`, where `something` is an identifier that may contain `::`
 * look for ` $= ` and ` !$= ` (there are spaces around those)
    * Does Smalltalk allow custom operators?

Another thing I've forgotten during all this is that Torque also creates TorqueScript files with `.mis` and `.gui` extensions, when they're used as data files.

**Comment by pchaigno** [comment]
@eightyeight I think you should implement what you proposed (and open a pull request) and then we'll be able to see, with @arfon's help, if it's accurate on a big sample of files.

**Comment by eightyeight** [comment]
I'm getting to it - just pretty busy these days :).

**Comment by pchaigno** [comment]
@eightyeight No worries.

**Comment by arfon** [comment]
:flags: flagging this as stale :flags:

**Comment by Wuzzy2** [comment]
Does this mean this is now officially a WONTFIX?
o_O

**Comment by larsbrinkhoff** [comment]
My interpretation is that we're still waiting to hear from @eightyeight.  If he (or someone else!) posts a pull request, I'm sure progress could be made.
