### ISSUE TITLE
Many *.g and *.gd files are mis-recognized as GAP, how to handle it?

### ISSUE THREAD

**Issue by fingolfin** [github/linguist#1528]
I just had a look at https://github.com/trending?l=gap and noticed that the top projects there are not using GAP at all, but rather are misdetected. They all seem to be using something called "G-code", see http://reprap.org/wiki/G-code -- format for RepRap 3D printers (it seems to essen

Some concrete examples (randomly picked):
- https://github.com/dmcc/bllip-parser/blob/master/first-stage/DATA/EN/ru.g
- https://github.com/reprappro/RepRapFirmware/blob/master/SD-image-Ormerod-1/gcodes/duettest.g
- https://github.com/reprappro/RepRapFirmware/blob/master/SD-image-Ormerod-1/gcodes/square.g
- https://github.com/MakerGear/M2/blob/master/Sample%20Prints/Gcode/bracelet.g

The official extension for such files seem to be ".gco", but clearly many people use ".g"

This is a bit annoying. What can be done to fix this? One solution would be to add RepRap G-code to the list of "languages" detected by linguist. Note that this is not a general programming language, but rather a set of commands controlling the RepRap "3D printer". Still, it is some kind of machine code.

Should one add a language entry for this, then? What would be the name of the "language", "G-code"? Or is there another way to deal with such misdetections?

**Comment by arfon** [comment]
:flags: flagging this as stale.

**Comment by fingolfin** [comment]
First off, as I just learned, those files in BLLIP are not G-Code at all. That in turn means that the files `lm.g` and `rm.g` should be removed from the G-code sample set (let me know if you need me to file a pull request for that).

But of course even with that changes, those files in BLLIP (and any other .g files that is neither GAP nor G-Code) will be misdetected. I still think this is a design flaw in linguist (see issue #1571)...

Anyway, I'll have a look to see if I can figure out how these "heuristics" work and whether I can get them to help... (I guess they are yet another attempt to workaround that fundamental issue I mentioned... *sigh*)

**Comment by fingolfin** [comment]
So... actually... how does one add a disambiguate heuristics rule for two language which generates the results "neither of these languages match" ?

**Comment by pchaigno** [comment]
> let me know if you need me to file a pull request for that

They can probably be removed in #1027.
<br/>

> I guess they are yet another attempt to workaround that fundamental issue I mentioned...

No, they would still be here even if we had a "no a code" option ;)
<br/>

> So... actually... how does one add a disambiguate heuristics rule for two language which generates the results "neither of these languages match" ?

Just return nothing in the case where none of the language match. For instance:
```ruby
disambiguate "Hack", "PHP" do |data|
  if data.include?("<?hh")
    Language["Hack"]
  elsif /<?[^h]/.match(data)
    Language["PHP"]
  end
end
```

**Comment by bojidar-bg** [comment]
:+1: This is (mostly) misidentified as GAP, though it is GDScript.... https://github.com/KOBUGE-Games/ringed

**Comment by brice-morin** [comment]
Also, I suspect projects that rely on ANTRL also have `*.g` files identified as GAP... whereas those files are used to define the grammar of a language.

**Comment by pchaigno** [comment]
@fingolfin Are you still working on a heuristic rule?

**Comment by fingolfin** [comment]
No, I haven't looked a linguist since my last comment. There are multiple reasons for that:

* While I know GAP, I don't know any of the other languages, so in order to develop a meaningful heuristic, I'd have to dig into them. And even then, the best I can hope for is a crude hack.
* If instead linguist use text classifiers that allow for classifying text as "unknown", this problem would not exist, or at least would be much less severe. Working on manual disambiguation hacks for linguist seems to be an endless whack-a-mole game, for which I don't have the nerve.
* As I explained above, several of these misdetection issues are (or at least: used to be... haven't verified that recently) already fixed by the addition of G-Code as a language. But since github does not rerun the detection for repositories that are not changed, e.g. https://github.com/reprappro/Mendel is still reported as GAP code, even thought linguist at one point correctly handled it. Clearly, no effort I'd ever spend on linguist would fix that problem.

**Comment by williamd1k0** [comment]
Hi, I'm working on a heuristic rule for GDScript.
I've tested with some GDScript and GAP repos. I think it's ok with the rules.

I don't know GAP and G-code to write a rule for GAP :/

Also, I added a color to GDScript but travis-ci is failing the color threholds...

**Comment by smola** [comment]
This affects a lot of ANTLR code: https://github.com/search?l=GAP&q=extension%3Ag+antlr&type=Code

**Comment by fingolfin** [comment]
It is still relevant because the issues described  here are issues. However, I have not checked whether the underlying design flaw (of not allowing negative detection) is still present in linguist.

**Comment by fingolfin** [comment]
See above. Do we now have to tick this "keep alive" check box every month? What is the idea behind this "stale bot"? Are old bugs somehow fermenting into features perhaps? ;-)

**Comment by lildude** [comment]
> See above. Do we now have to tick this "keep alive" check box every month?

Until someone provides a solution, yes. Lots of peeps have said they're looking into heuristic improvements - even you at [one point](https://github.com/github/linguist/issues/1528#issuecomment-77202548) 😉  - yet the PRs aren't coming. This is something that really needs to be addressed by people that know the languages involved.

> What is the idea behind this "stale bot"?

To nudge people to double-check that the issues they've raised are still valid and contribute to fixing them if they are (it's almost working on this issue too 😉). An issue sitting looking pretty isn't going to get resolved unless it gets attention 😄

**Comment by fingolfin** [comment]
> > See above. Do we now have to tick this "keep alive" check box every month?
> 
> Until someone provides a solution, yes. Lots of peeps have said they're looking into heuristic improvements - even you at [one point](https://github.com/github/linguist/issues/1528#issuecomment-77202548) 😉 - yet the PRs aren't coming. This is something that really needs to be addressed by people that know the languages involved.

But to do that, we'd need the ability to classify content as "spam" -- i.e., to say "this is definitely *not* the right language". This is something that really needs to be addressed by people that know linguist in and out.

> 
> > What is the idea behind this "stale bot"?
> 
> To nudge people to double-check that the issues they've raised are still valid and contribute to fixing them if they are (it's almost working on this issue too 😉). An issue sitting looking pretty isn't going to get resolved unless it gets attention 😄

I don't see how it is working on this issue. It is annoying, sure, but I've been waiting to be able to work on this issue for years, but AFAIK (but I might be wrong, I didn't check recently) the fundamental flaws in the architecture of linguist remain, so I can't really work on it.

Anyway, I guess then we are better off closing it.

**Comment by Alhadis** [comment]
> Lots of peeps have said they're looking into heuristic improvements

Wait a second, why should heuristics be involved? This should be addressable from a configuration level:

* [ ] Maximum times @stale can flag a thread as stale after somebody's responded
* [ ] Whether or not those with write-access can influence the above setting
* [ ] Prevent bot from flagging issues labelled as **ongoing** or something

**Comment by fingolfin** [comment]
I think @lildude referred to language recognition heuristics, not the settings for the stale bot.

Anyway, to me, the stale bot is an unfriendly passive-aggressive way of saying "we are not interested in issue reports, at least for non-trivial issues, only for PRs". I'd find it more honest if the issues were simply closed with such a comment, instead of badgering people who tried to contribute by taking time to careful document and describe an issue. I am not interested in contributing to a project that works this way. No config tuning will help with that.

**Comment by lildude** [comment]
> But to do that, we'd need the ability to classify content as "spam" -- i.e., to say "this is definitely _not_ the right language".

That is the complete opposite of the purpose of Linguist... Linguist is designed to tell you what it thinks the language is based on the information it has. In order for Linguist to get this right, it needs more data, whether that's heuristics or more samples for the classifier. Only the repo owner can tell Linguist what it is _not_, on a repo-by-repo basis, by telling it what it is using an override. Linguist, however, doesn't learn from this, and really shouldn't either as one person's preference is not necessarily correct for all, and that's why we need PRs for Linguist itself.

> Wait a second, why should heuristics be involved? This should be addressable from a configuration level:

None of those actually address _this_ issue, just the stalebot behaviour 😉. Adding one of [these labels](https://github.com/github/linguist/blob/3ff6a9bfbb206a80504492f4d28a17e5e900041b/.github/stale.yml#L21-L25) would certainly stop stalebot.

We could certainly add the "Help wanted" label and keep this open until someone offers the necessary updates, but I fear this won't happen given it's been over four years already.

@fingolfin I hear you and understand your sentiments. I implemented stalebot to keep the development of Linguist active and "fresh" and encourage ongoing help from those knowledgable and affected. We rely heavily on the community as it's impractical for us to know each and every supported language in enough depth to resolve all the issues raised, especially as most of these are around language identification/matching, as is this issue, and often they're resolved over time thanks to other PRs. I'd love to dig in myself, but I know absolutely diddly about any of the languages involved here.

**Comment by Alhadis** [comment]
Yeah, I agree. Bots are annoying, but they give routine contributors fewer headaches from running around poking old issues with a stick to see which ones care, and which don't. This sort of thing becomes easier to manage when responsive users are ones who reply, and the ones who clearly aren't motivated enough to keep an issue open will let it grow stale. =)

Either way, thank you for your patience, and apologise for any frustration caused.

**Comment by DO-Ui** [comment]
Hi, I wanted to add onto this issue with some language written in GDscript also being identified as GAP, GDscript has the .gd extension and its used in the Godot engine. It appears GDScript support already exists as some code in my repository is properly identified but the rest is mis-identified as GAP.

My repo:
![image](https://user-images.githubusercontent.com/68296986/196322401-f3c01bbf-406d-4bf4-8ac5-f57b07a5821e.png)
In my repository i am 100% certain there is 0 GAP code and it is all GDScript

My repository is private although some other examples I could find with [this search](https://github.com/search?q=language%3AGAP+godot&type=Repositories):
https://github.com/khairul169/3d-simplewater
https://github.com/mistertaftcreates/Godot_2048
https://github.com/brett-taylor/Godot-Achievement-System

**Comment by dc42** [comment]
> The official extension for such files seem to be ".gco", but clearly many people use ".g"
Extension .gco is used by old 3D printer firmware that only supports 8.3 file names. Extension .gcode is more prevalent these days. Macro files (as opposed to model files to be printed) often use .g.
