### ISSUE TITLE
`.in` extension does not imply CMake syntax

### ISSUE THREAD

**Issue by roman-neuhauser** [github/linguist#1568]
it seems that https://github.com/github/linguist/commit/c8bc0a5c792b39b378a6bc743ad45949ea18f13b causes any file with a name ending in `.in` to be treated as CMake input.

`$whatever.in` is a traditional naming pattern for files meant to be preprocessed in some way.  half of my repos in github have files ending in `.spec.in`, *among others*.  i'd expect there to be a lot of `Makefile.in` files in github.  etc, etc.

some of my repositories with `.in` files:

* https://github.com/roman-neuhauser/bs-update
* https://github.com/roman-neuhauser/pastish
* https://github.com/roman-neuhauser/printscreen

**Comment by arfon** [comment]
@pchaigno - do you know if this is this still an issue?

**Comment by pchaigno** [comment]
Yes and no. We now support segmented file extensions and have a couple defined for `.in` (`.rs.in` and `.cmake.in`). We also improved the recognition of files based on their filename solely. However, we still don't recognize the `.spec.in` file extension.

> files ending in `.spec.in`, among others.

@roman-neuhauser What are these files? What other extensions are you thinking of?

**Comment by pchaigno** [comment]
Flagging this as stale :flags:

**Comment by tripleee** [comment]
Sorry for being late to reply. I don't know exactly what Roman was alluding to, but using `*.in` as a template for generating a build artefact is fairly universal practice, and this extension by itself should not be taken as more than possibly a weak hint for the file's language, type, or purpose. `Makefile.in` from Autotools is of course ubiquitous; quick googling also brought up the following;

* https://gist.github.com/telent/4118983 apparently builds an RPM `.spec` file from a template where the version etc is a hard-coded static token to be replaced dynamically at build time
* https://github.com/liip/mahararpmpkg/blob/master/Makefile does something fairly similar

**Comment by roman-neuhauser** [comment]
exactly what @tripleee said.  *filename.in* is a ubiquitous pattern used to signal that the file is a main *in*put to generate *filename*, regardless of the actual syntax of the input, output, or the extent of processing.

you'll notice that `configure.in` (processed by `autoconf`), `Makefile.in` (processed by `configure`) have vastly different syntaxes, what they do have in common is that they're the main inputs used to produce `configure` and `Makefile` respectively.

@pchaigno wrote

> > files ending in `.spec.in`, among others.
>
> What are these files?

if you're asking about `*.spec.in` files, i use them as templates for `*.spec` files, these are used to create software packages for an array of GNU/Linux distros (see http://rpm.org/).

> What other extensions are you thinking of?

this is a wrong line of thinking.  there's no closed set of extensions to think of.  you cannot say "we'll whitelist `{foo,bar,baz}.in`" and expect to land anywhere close to correct.  people tack `.in` on anything, different people on different things.  sometimes the input syntax *mostly* conforms to the syntax of the output (cf. Makefile.in), othertimes it's anything but (cf. configure.in).

the FreeBSD ports collection contains over 5800 files ending in `.in`.  ~1670 of these are either patches for upstream Makefile.in files (`patch-.*Makefile\.in$`) or wholesale replacements, the rest is a hodgepodge.  case in point: the x11/printscreen port comes with a `printscreen.in` file which is a normal /bin/sh script.

what other filetypes i use the `.in` suffix with, besides makefiles and specfiles?  any that (may) need some build step.  this includes source files in any text-based language without a standardized preprocessor or where the preprocessor does not fit the bill, like when i need to embed system-specific paths in manpages.

but i really need to stress what @tripleee said: [`.in`] by itself should not be taken as more than possibly a weak hint for the file's language, type, or purpose.

**Comment by pchaigno** [comment]
Do you still have issues with this? `.in` isn't associated to any language anymore.
