### ISSUE TITLE
`.t` extension does not imply Perl syntax

### ISSUE THREAD

**Issue by roman-neuhauser** [github/linguist#1569]
`.t` is also used for [cram][0]-based tests, eg. in [git-mantle][1].

[0]: https://pypi.python.org/pypi/cram
[1]: https://github.com/roman-neuhauser/git-mantle/blob/master/tests/0400.t

**Comment by arfon** [comment]
>  So, if only one language (e.g. perl) lists a given extension (e.g. ".t") then all files with that extensions are treated as perl code... 

Closing as stale. Linguist could definitely be improved here but there are no current plans to address this issue.

**Comment by roman-neuhauser** [comment]
github clobbers attempts to search for what little it does have (` (glob)` and ` (re)`) as it "helpfully" strips the parentheses.  the only remaining keyword is ` (no-eol)` which gets a small fraction of use compared to the other two, most results are related to mercurial or ceph.

**Comment by roman-neuhauser** [comment]
to make myself clearer: the difficulty in searching stems from the fact that "glob" and "re" are too common and desired results are swamped by unrelated chaff. "no-eol" is fairly unambiguous but also fairly useless in determining the language's prevalence because very rare (in my experience).

**Comment by pchaigno** [comment]
The BigQuery platform might be a better fit for such search queries ;)
