### ISSUE TITLE
Add "not a code file at all" to possible detection results

### ISSUE THREAD

**Issue by fingolfin** [github/linguist#1571]
I think linguist has a big flaw in its design in the following sense: Once an extension is associated to at least one "language" in linguist, it will always associate files with that extensions with a language known to it. The option "I do not know what this file is" simply vanishes.

This is akin to a spam filter only knowing how to classify emails as "spam", but not as "ham" -- suddenly, all emails become spam.

So, if exactly one language known to linguist is listed with a certain extension (e.g. ".tst" for Scilab, see PRs #1523 and #1541; or ".t" for Perl, see issue #1569), then linguist automatically considers all files with that extension as being written in that language.

The only way to "fix" that then is to add support to linguist for the language that this is written in. Except of course that it will only fix it for *that* language, not all the others. And there is no way at all to fix it for pure data files. 

Making it worse for the person adding the second language for a given extension is that of course such a fix will cause regressions: Since previously, all files with that extension were automatically associated with language 1, there were 0 false negatives, and only tons of false positives. With the second language, there will almost always be new false negatives. There is virtually no way to avoid this. (This seems to be the reason why my PRs #1523 and #1541 are not yet accepted).

I think this is a bad situation. The normal "fix" for this in a document classifier system would be to only accept the result of the classifier if they exceed a certain confidence threshold. So, even if only one language is listed with that extension, the result of the bayesian classifier should be consulted (this is currently not the case, it seems).

And please don't tell me about "gitattributes" or other manual overrides -- yes, in some cases, one may  have to resort to a manual override, just like I will always have to double check on my spam filter (with some false positives and false negatives). But before looking at fixes for exceptional cases, I think it's important to get the baseline right.

**Comment by arfon** [comment]
We're planning on working on this extensively over the coming months https://github.com/github/gsoc#linguist so closing this out. Thanks for your thoughts @fingolfin - one of the outcomes of this work should be for Linguist to not return _any_ classification if the confidence is too low.

**Comment by victorlin** [comment]
Was this ever implemented? I am running into this in [nextstrain/augur](https://github.com/nextstrain/augur) where Cram's `.t` files are being detected as Perl (#1569).

**Comment by lildude** [comment]
Nope, and there still isn't support for cram but you can use an override to remove the syntax highlighting and language classification and have it excluded from the stats by forcing the language to text:

```gitattributes
*.t linguist-language=text
```

GitHub's new search is a lot more powerful now and can use regex so it's probably possible to come up with a search for cram files that can be used to confirm usage and also used for the heuristic that would be needed when adding support for cram and the `.t` extension.
