### ISSUE TITLE
gnu linker script

### ISSUE THREAD

**Issue by zchrissirhcz** [github/linguist#1576]
Hello, I think gnu's linker file, whose file name ends with .ld, should be supported though it is not commonly used. Could any one supply a color YAML file?

**Comment by pchaigno** [comment]
@zchrissirhcz Do you know a TextMate or Atom bundle or a Sublime Text package for GNU Linker files?

**Comment by arfon** [comment]
:flags: flagging this as stale

**Comment by arfon** [comment]
Please feel free to open another issue if this is still something you're interested in working on.

**Comment by larsbrinkhoff** [comment]
Implemented in #2330.
