### ISSUE TITLE
My dotfile `.aliases` with execute permission and Sha-Bang doesn't have syntax highlighting. 

### ISSUE THREAD

**Issue by vamdt** [github/linguist#1603]
Hi,

I have a file named `.aliases`, I have add execute permission and Shang-Bang, but it doesn't recognised as a bash script.
https://github.com/vamdt/dotfiles/blob/master/link/.aliases

Thanks.

**Comment by pchaigno** [comment]
@vamdt Is this issue solved?

**Comment by vamdt** [comment]
@pchaigno yes, Thank you, guys.
