### ISSUE TITLE
Linguist overrides for sub-directories

### ISSUE THREAD

**Issue by pchaigno** [github/linguist#1606]
I started playing around a bit with the new Linguist override feature.
My first goal is to ignore the `Report/` directories of this repository:
https://github.com/pchaigno/TP-Compilation

I tried to add this line to the `.gitattributes` files without success: `Report/* linguist-vendored=true`
I also tried: `Report/ linguist-vendored=true`
It works if I ignore the TP1 directory for example with: `TP1/* linguist-vendored=true`

Also, while I'm at it, why do we need to add an asterisk after a folder path? It's not required for `.gitignore` files...

**Comment by capnslipp** [comment]
Tip for anyone else who's still having issues even after modifying `.gitattributes`: You need to commit `.gitattributes` in order for github-linguist to use it.  So commit it locally, adjust and tweak and then amend the commit with `git commit --amend -C HEAD` until you're happy with it, and push to remote when it's good to go.

I was tearing my hair out not understanding why going full-metal and putting this in my `.gitattributes` was having no effect.  `git check-attr --all «some filename»` was happily reporting the attributes, but github-linguist continued to show only 2 files in the repo (a couple of root-level package definition files).
```
Demo/** linguist-detectable linguist-documentation=false linguist-generated=false linguist-vendored=false
```

**Comment by lildude** [comment]
@capnslipp this is [documented, and in bold](https://github.com/github-linguist/linguist/blob/master/docs/overrides.md) 😉
