### ISSUE TITLE
Linguist identifies .asc files as "AGS Script", but github.com renders them as AsciiDoc

### ISSUE THREAD

**Issue by aroben** [github/linguist#1638]
https://github.com/progit/progit2 is full of `.asc` AsciiDoc files. But the language statistics for that repo say that it is 97% AGS Script. Seems like github.com and Linguist should agree here.

/cc @arfon

**Comment by arfon** [comment]
@aroben there's an old PR here that I've just picked up https://github.com/github/linguist/pull/1511

**Comment by arfon** [comment]
@aroben - #2120 should fix this (although Ascii doc won't be included in the repository stats as it's [`prose`](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L182))
