### ISSUE TITLE
Language is null in some forked repos

### ISSUE THREAD

**Issue by ahmdrefat** [github/linguist#1642]
The language of some forked repos are `null` until I push the first commit! 
Is this normal?
Here's an example [https://api.github.com/repos/ahmdrefat/Design-Patterns-in-Javascript](https://api.github.com/repos/ahmdrefat/Design-Patterns-in-Javascript)

**Comment by Varulv1997** [comment]
> The language of some forked repos are `null` until I push the first commit!
> Is this normal?
> Here's an example https://api.github.com/repos/ahmdrefat/Design-Patterns-in-Javascript

Because the repository is empty, what did you expect.
