### ISSUE TITLE
Disambiguate Matlab, Objective-C, Mathematica, M, and Mercury

### ISSUE THREAD

**Issue by bkeepers** [github/linguist#1649]
Matlab, Objective-C, Mathematica, M, and Mercury are often misidentified due to their common use of the `.m` extension. This is a common issue so I'm creating a meta-issue that we can point all the reports to.

**Comment by arfon** [comment]
Closing this as https://github.com/github/linguist/pull/1652 is nearly ready to land. I would love people's feedback over there please.
