### ISSUE TITLE
Perl 6 lexer not being used for .pm6 files

### ISSUE THREAD

**Issue by hoelzro** [github/linguist#1680]
`.pm6` files in repositories have no syntax highlighting applied (example: https://github.com/retupmoca/p6-Email-Simple/blob/master/lib/Email/Simple.pm6).  `.pm6` files in Gists, however, do!

**Comment by hoelzro** [comment]
So it seems that Perl 6 files are sometimes classified as Prolog: https://github.com/rakudo/rakudo/search?l=prolog

**Comment by hoelzro** [comment]
Ha, found the problem! https://github.com/rakudo/rakudo/blob/nom/src/core/List.pm#L452

**Comment by arfon** [comment]
Can this be closed now that https://github.com/github/linguist/pull/900 has landed?

**Comment by hoelzro** [comment]
@arfon I'm not sure; as far as I see it, there are two issues remaining:
  * Perl 6 files are sometimes not detected as such (ex. List.pm in rakudo is identified as Prolog)
  * There is no highlighting for Perl 6 files, due to the lack of a Textmate bundle to do so.

The issue makes it sound like .pm6 files are not properly detected as Perl 6, which they are.  I don't remember if linguist improperly detected them back in November, or if I was misrepresenting the issue that there was no Perl 6 highlighting for them.  Would you like me to close this and break out the two problems mentioned above into separate issues?

**Comment by pchaigno** [comment]
> Perl 6 files are sometimes not detected as such (ex. List.pm in rakudo is identified as Prolog)

This is happening because of #2042.
<br/>

> There is no highlighting for Perl 6 files, due to the lack of a Textmate bundle to do so.

@ashgti doesn't seem to be responding anymore (see ashgti/perl-tmbundle#1). Maybe we could fork the repository, update the conflicting scope name and use it as is?

**Comment by ashgti** [comment]
@pchaigno Hi, I have updated my perl.tmbundle with an updated syntax based off the vim.perl perl6 syntax. Its not complete yet, but I created a pull request here https://github.com/atom/language-perl/pull/9 and https://github.com/textmate/perl.tmbundle/pull/13 for the basic support.

I am still working on a more complete grammar for TextMate (and Atom).

**Comment by pchaigno** [comment]
@ashgti Good! Could you post here when one of the PR is merged?

**Comment by ashgti** [comment]
@pchaigno sure, I'll let you know when its merged

**Comment by arfon** [comment]
Since `v4.5.1` this is fixed.
