### ISSUE TITLE
Github API Markdown Changes?

### ISSUE THREAD

**Issue by infomaniac50** [github/linguist#1718]
I'm not sure if there have been changes lately but markdown rendered though the API is not highlighting syntax correctly anymore. The CSS used by API client now longer works. I noticed that the API renders with different css classes than github does. 
Github gives

``` html
<div class="highlight highlight-ruby">
    <pre>
        <span class="nb">require</span>
        <span class="s1">'redcarpet'</span>
        <span class="n">markdown</span>
        <span class="o">=</span>
        <span class="no">Redcarpet</span>
        <span class="o">.</span>
        <span class="n">new</span>
        <span class="p">(</span>
        <span class="s2">"Hello World!"</span>
        <span class="p">)</span>
        <span class="nb">puts</span>
        <span class="n">markdown</span>
        <span class="o">.</span>
        <span class="n">to_html</span>
    </pre>
</div>

```

but the api gives

``` html
<div class="highlight highlight-ruby">
    <pre>
        <span class="pl-mr">
            <span class="pl-kos">require</span>
            <span class="pl-s1">
                <span class="pl-pds">'</span>redcarpet
                <span class="pl-pds">'</span>
            </span>
        </span>
        markdown
        <span class="pl-ko">=</span>
        <span class="pl-sc">Redcarpet</span>.
        <span class="pl-kos">new</span>(
        <span class="pl-s1">
            <span class="pl-pds">"</span>Hello World!
            <span class="pl-pds">"</span>
        </span>) puts markdown.to_html</pre>
</div>
```

This is breaking code editors that use the API to render markdown. Here is a full copy of the stuff I'm seeing 
https://gist.github.com/infomaniac50/5f2886df9308d3fb4009

I'm using SublimeText 3 with the Markdown Preview plugin to render the html but I'm also having issues with markdownpad 2

**Comment by kachkaev** [comment]
@bkeepers if I've noticed a bug in how markdown preview works on GitHub, where is it best to report it?

In particular, GithHub seems to fail in highlighting some fenced code blocks inside markdown listings. Precisely, those that have additional attributes.

When a code block is not inside a markdown listing, highlighting works OK:

````
```js
const x = 42;
```
````
↓
```js
const x = 42;
```

---

````
```js {something=something}
const x = 42;
```
````
↓
```js {something=something}
const x = 42;
```

However, when a code block listing is inside a markdown listing, presence of `{something=something}` breaks highlighting:

`````
````markdown
# fenced code block without arguments
```js
const x = 42;
```

# fenced code block with arguments
```js {something=something}
const x = 42;
```
````
`````
↓
````markdown
# fenced code block without arguments
```js
const x = 42;
```

# fenced code block with arguments
```js {something=something}
const x = 42;
```
````

What library is responsible for syntax highlighting here? How can I help with fixing this and propagating the changes back to GitHub?

---

Code block attributes can instruct some preview tools to apply additional styling to the block or make it _live_. For instance, attributes [are used in `markdown-preview-enhanced`](https://shd101wyy.github.io/markdown-preview-enhanced/#/code-chunk).

I've been recently working on a project called [litvis](https://github.com/gicentre/litvis), which also uses code block attributes. Although this syntax is not standard, there are currently no issues with it in editors like Atom or VSCode as well as tools like Prettier. It'd be great if GitHub could nicely highlight things too, e.g. [in this README](https://github.com/gicentre/litvis/blob/2ba014df51700010cc52f5626f85ac78842cfc7f/documents/README.md).

**Comment by kachkaev** [comment]
Many thanks for reaching out @pchaigno! Indeed, the issue has already been reported as https://github.com/atom/language-gfm/issues/199.
