### ISSUE TITLE
Gemfile.lock is not Ruby

### ISSUE THREAD

**Issue by bkeepers** [github/linguist#1740]
`Gemfile.lock` is classified as Ruby, which means it gets syntax highlighted as Ruby.  #1733 removed the generated designation, which means we'll probably see a lot more complains about the syntax highlighting as soon as that gets deployed.

If we remove `Gemfile.lock` from the list of ruby filenames, it will likely [get detected as JSON](https://github.com/github/linguist/blob/df105c0c33dca43533d7724ed7b724d0b80557c3/lib/linguist/languages.yml#L1187). We really want something like what is described in https://github.com/github/linguist/issues/1571, where we can explicitly describe a file as not code.

One option would be to just add a catch-all entry in languages.yml and set the type to `data` (or something that is ignored) where we could define extensions, filenames, and put samples.

Thoughts?

/cc @arfon @pchaigno @vmg @aroben

**Comment by arfon** [comment]
Closing this as stale. (Still think it's a good idea)
