### ISSUE TITLE
Go highlighting has regressed

### ISSUE THREAD

**Issue by titanous** [github/linguist#1761]
A bunch of things are now highlighted orange (the string highlight color) that should not be:

- Type names (sometimes)
- Struct field names (only in definitions)
- Function/method parameter names

Overall it's much more inconsistent than the pygments highlighter.

Here is an example file that demonstrates most of these issues: https://github.com/flynn/flynn/blob/master/test/runner/runner.go

**Comment by arfon** [comment]
@aroben [this repo](https://github.com/DisposaBoy/GoSublime) looks to have a more up to date bundle. This is a Lightshow test of [https://github.com/flynn/flynn/blob/master/test/runner/runner.go](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2FDisposaBoy%2FGoSublime%2Fmaster%2FGoSublime.tmLanguage.json&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fflynn%2Fflynn%2Fmaster%2Ftest%2Frunner%2Frunner.go&code=) - it looks pretty good to me?

**Comment by titanous** [comment]
@arfon Unless I'm missing something, the linked highlighter has the exact same problems listed in my original description.

**Comment by arfon** [comment]
> @arfon Unless I'm missing something, the linked highlighter has the exact same problems listed in my original description.

Very possibly. I'm afraid I don't know Go at all and so wanted to bring this option to your attention incase it was better. Sounds like it isn't :-\

**Comment by pchaigno** [comment]
@titanous You should probably report issues to https://github.com/AlanQuatermain/go-tmbundle since there doesn't seem to be a better alternative.

@lazywei Do you know a better grammar (Sublime Text package or TextMate bundle)?

**Comment by titanous** [comment]
@pchaigno I consider this to be a regression in GitHub's Go language highlighter. If the GitHub folks feel like this is an upstream issue, they can work on solving it upstream.

**Comment by pchaigno** [comment]
@titanous Okay, I'll report it upstream (even if I'm not from GitHub :p). I just thought it would be better if it was you since I'm not familiar with Go.

**Comment by pchaigno** [comment]
Actually, I found a few other mistakes, but I think what you describe isn't one:

> A bunch of things are now highlighted orange (the string highlight color) that should not be:

[Strings are now highlighted in blue](https://github.com/flynn/flynn/blob/master/test/runner/runner.go#L4) and orange is for variables. It looks like [the grammar](https://github.com/AlanQuatermain/go-tmbundle/blob/master/Syntaxes/Go.tmLanguage) is respecting TextMate naming conventions and [only misses a few variables](https://github.com/flynn/flynn/blob/master/test/runner/runner.go#L80). Please excuse me if I misinterpreted something.

**Comment by titanous** [comment]
Here's an example of orange being used randomly: https://github.com/flynn/flynn/blob/b2743b65a540b9a1bc878f9cfb2f8b30290a0377/test/runner/runner.go#L119

`error` and `Runner` are type names, `r` is a variable/receiver name.

**Comment by titanous** [comment]
And more here: https://github.com/flynn/flynn/blob/b2743b65a540b9a1bc878f9cfb2f8b30290a0377/test/runner/runner.go#L383

**Comment by arfon** [comment]
Closing as this isn't an issue that can be fixed in Linguist.
