### ISSUE TITLE
Gradle files no longer highlighted

### ISSUE THREAD

**Issue by aroben** [github/linguist#1766]
Before the fix for https://github.com/github/linguist/issues/1365, Gradle files were getting highlighted as Groovy. Now they aren't highlighted at all. Apparently the Groovy highlighting was working well enough, because we're now getting reports from users saying that their Gradle code is no longer highlighted (but they don't mention anything about the highlighting being poor previously).

So should we add a new language for Gradle and use the Groovy highlighter for it? I don't know much about these languages so I can't say myself.

**Comment by pchaigno** [comment]
Should be fixed with #1790.

**Comment by arfon** [comment]
> Should be fixed with #1790.

Indeed it is.

**Comment by matthoffman** [comment]
Just a note for others finding this much later: this arrangement does mean that you need `language-groovy` installed in addition to `language-gradle` to see syntax highlighting. If you just install `language-gradle`, you'll get no errors, but no highlighting.
