### ISSUE TITLE
Fix syntax hilighting of clojure code 

### ISSUE THREAD

**Issue by hiredman** [github/linguist#1769]
after https://github.com/clojure/tools.reader/blob/b62ce9964a9770578b5f2179a2166cbfc956dfe8/src/main/clojure/clojure/tools/reader.clj#L36 the highlighter seems to thing it is in a string literal for a large chunk of the rest of the file (everything is orange)

**Comment by arfon** [comment]
Hi @hiredman, thanks for reporting this - the issue is being tracked over here: https://github.com/atom/language-clojure/issues/11
