### ISSUE TITLE
highlight for Coq with comments broken

### ISSUE THREAD

**Issue by shouya** [github/linguist#1804]
It seems that comment is not handled correctly. When there is a keyword `Qed` within a comment block, this keyword will still be highlighted.

See: https://github.com/shouya/thinking-dumps/blob/master/imp/Chap7.v#131

Actually the highlight support for Coq was not very complete yet, it looks the content within 'Proof...Qed' is not highlighted at all.

**Comment by arfon** [comment]
Closing as this is an issue on https://github.com/mkolosick/Sublime-Coq/

Please open an issue here once the bug is fixed upstream.
