### ISSUE TITLE
#; s-exp is not highlighted correctly in Racket

### ISSUE THREAD

**Issue by soegaard** [github/linguist#1822]
Racket (and a lot of Scheme implementations as well) support #; which comments out an s-sexp.

The following is one big comment:

#;( if  (= x 1)
         2 
         3)

Github colors the last parenthesis red. The naive syntax highliger Sees the ; and thinks
that it is a line comment.  That is it sees ; (if (= x 1)  as the comment.
It then sees 2 and 3 as legal expressions. And then it sees ) which it
thinks is an unmatched parenthesis.

**Comment by arfon** [comment]
Should be fixed by https://github.com/github/linguist/pull/1982
