### ISSUE TITLE
Incorrectly identifies GPG/PGP .asc files as AGS files

### ISSUE THREAD

**Issue by ryanmjacobs** [github/linguist#1843]
I uploaded a gpg public key to my web project, and then this happened!
![asc-files](https://cloud.githubusercontent.com/assets/4251257/5330040/ff3461ba-7d88-11e4-8f6c-b6c5a0be9aa6.png)

Is there a way linguist could check for the "PGP header" before determining that it's an AGS file?

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2

blah blah blah...
key stuff...

-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by pchaigno** [comment]
@ryanmjacobs It should be fixed now :-)

**Comment by ryanmjacobs** [comment]
Sweet! Now it's correctly identified. Thanks @pchaigno!
