### ISSUE TITLE
Unicode, indentation -- pick just one.

### ISSUE THREAD

**Issue by greghendershott** [github/linguist#1858]
Example: https://gist.github.com/mattmight/cfdd27bb971eb3a79f53

1. If you copy/paste code from the main page, you lose indentation.

2. If you click `Raw`, you lose text encoding. `λ` and `β` end up as `Î»` and `Î²`.

In other words, it's not possible to copy/paste code intact.

Although I might be mistaken, I believe the first item is a result of the recent Great Pygments Purge. So that's why I'm filing the issue here. Would be happy to file under another repo instead, if you tell me where.

**Comment by greghendershott** [comment]
> If you copy/paste code from the main page, you lose indentation.

This half is fixed now (maybe it was fixed long ago).

> If you click Raw, you lose text encoding. λ and β end up as Î» and Î².

This is still the case.

Because at least the first method now works, and because the second likely has nothing to do with linguist, I'm closing this.

**Comment by pchaigno** [comment]
@greghendershott Forgot to close? ;)

**Comment by greghendershott** [comment]
@pchaigno Yes. Thanks. :)
