### ISSUE TITLE
HTTP highlighting broken on github.com

### ISSUE THREAD

**Issue by abalmos** [github/linguist#1862]
It appears that HTTP highlighting is broken on github.com. Rather then creating an issue github support sent me here to report the bug.

For example:

**Request**
```http
GET /a/b/c HTTP/1.1
Host: cloud.com
Accept: application/json
```

**Response**
```http
HTTP/1.1 200 OK
Content-Type: application/json

{
  "a": "A",
  "b": {
    "c": "C"
  }
}
```

More examples of the issue can be found here: https://github.com/OADA/oada-docs/blob/master/rest-specs/REST-API-Examples.md. That page, and the others in that repo, used to be colorful.

languages.yml (https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L1194) seem to indicate HTTP highlighting is still supported.

**Comment by pchaigno** [comment]
@abalmos It looks good in Lightshow so I opened a pull request (#1952) to use this grammar.

**Comment by arfon** [comment]
This will be addressed in https://github.com/github/linguist/pull/2011 which should go live very soon.
