### ISSUE TITLE
Bug in JavaScript Syntax Hightlighting

### ISSUE THREAD

**Issue by sstur** [github/linguist#1870]
The following JavaScript is incorrectly parsed. I think it has to do with the function keywords appearing inside strings.

```javascript
var f = function(y) {
  if (a) {
    a.push('x' + y + ':function()');
  } else {
    this.part.is.not.correctly.syntax.highlighted();
  }
};
```

**Comment by arfon** [comment]
Closing this as it's being tracked over in https://github.com/atom/language-javascript/issues/76
