### ISSUE TITLE
Diffs for Sql files are shown as "binary"

### ISSUE THREAD

**Issue by JoePlant** [github/linguist#1873]
I noticed recently that my diffs for two checkins were not showing the changes for two sql files.

They can be seen here: https://github.com/JoePlant/Ampla-Sql-Scripts/commit/ec7110b54ddd75b47d54898357188f9f70026221
and here: https://github.com/JoePlant/Ampla-Sql-Scripts/commit/33ae110d15612b2789a4bf1fe474f3e5e8bc8ae1

Screenshot 
![image](https://cloud.githubusercontent.com/assets/4065727/5422865/a39acaac-82e6-11e4-8044-fb1738a8fdc3.png)

I reported it to github staff and received the following reply:

```
It is listed as a binary diff even though the file is a text file.

Just a quick followup - the team does believe this is an issue in Linguist. 
The best way to get this resolved would be to open an issue directly 
in the project issue tracker:

https://github.com/github/linguist/issues

Then if the problem is resolved there, we should get the fix as well 
when we bump the version of Linguist that we're running.
```

**Comment by vossad01** [comment]
@JoePlant Our experience has been that this usually happens with .sql files saved from Microsoft's SQL Management Studio, which uses a 16-bit (UTF-16 or UCS-2, not sure) encoding by default.  As @brianmario mentions git then is likely to treat them as binary files, which causes issues not only here but if you want to do things with that file in git, such as merging or viewing diffs.

Choosing a different encoding in the save dialog (or changing the encoding after saving) solves the issue.

**Comment by marnen** [comment]
This should probably be reopened. I'm having the same issue with SQL files generated by Rails on Mac OS X.

**Comment by bkeepers** [comment]
@marnen See https://github.com/github/linguist/issues/1849#issuecomment-67402191. Unfortunately, it's not a problem that can be solved by a change to linguist.

**Comment by marnen** [comment]
@bkeepers Wow, that sucks. So this is a Git bug?

**Comment by brianmario** [comment]
@marnen I wouldn't say it's a "bug" as much as an intention design decision. git's binary detection looks at the first few kb of a file to see if it contains any null bytes. If it does, it's considered binary and it skips performing a diff on that file for performance reasons.

I believe the reason for this design choice is it gives the best intersection of performance and accuracy. Otherwise encoding detection would have to be done, which can be considerably more expensive to do. And even then, it's not always accurate.

I have some ideas we've been playing with to see if we can make that more accurate, but we haven't come up with anything that has been performant enough yet. For now it's best to make sure all of your files are saved as UTF-8.

Hope that helps!

**Comment by marnen** [comment]
@brianmario Unfortunately, that sort of makes sense. But I wonder why Rails would be generating files like this in the first place. (However, this particular one *may* have been manually edited; haven't confirmed yet. If so, maybe it's an editor bug.)

**Comment by larsbrinkhoff** [comment]
I'm able to override git's binary detection by adding a `diff` attribute in `.gitattributes`.  So I don't see that git is at fault.

However, GitHub doesn't seem to honour the `diff` attribute.

**Comment by SH2015** [comment]
any update about this issue ? , I have same problem with sql files

**Comment by arj03** [comment]
Same problem here.

**Comment by pchaigno** [comment]
@larsbrinkhoff Did you send an issue with your findings (on the `diff` attribute) to GitHub support?

**Comment by larsbrinkhoff** [comment]
I don't think so!  I'll check it again.

**Comment by larsbrinkhoff** [comment]
@pchaigno Have a look at this: http://github.com/larsbrinkhoff/diff-test

In the first revision `foo` is a plain text file.  In the next revision, I inserted a NUL, which makes git think it's a binary file.  But adding the `diff` attribute makes git show the diff anyway.

GitHub, however, does not show a diff.

**Comment by panayot-p** [comment]
since git itself works fine with those files and it is github that has issues this should be reopened.

**Comment by brianmario** [comment]
@panayot-p which example are you referring to? The file from the commit referenced in the OP (https://github.com/JoePlant/Ampla-Sql-Scripts/commit/ec7110b54ddd75b47d54898357188f9f70026221) is in fact UTF-16, which git treats as binary.

**Comment by deseven** [comment]
I started to work on [a localization for some game](https://github.com/deseven/infra-ru) based on a Source engine. All localization files are in UTF16 with BOM and it's a requirement, there is no option to switch to UTF8. I have a correct `.gitattributes` file and it fixes the issue on my side, but github still refuses to treat those files as text.
Please reopen or tell me where to report it.

**Comment by lildude** [comment]
As mentioned many times in this issue and referenced off this issue, this is not something Linguist can address. If you wish to report this anywhere, you need to [contact GitHub Support](https://github.com/contact).

I'm going to lock this issue as it is clearly being missed that this is not something Linguist can solve.
