### ISSUE TITLE
Multiline comments broken in C/C++, Java, HTML, PHP, and, JavaScript

### ISSUE THREAD

**Issue by soegaard** [github/linguist#1887]
While writing a grammar for Github for syntax highlighting programs written in the Racket language, I have stumbled upon a general problem. The TextMate grammar framework has severe problems when it comes to multiline constructs. 

In Racket `#|` starts a multiline comment and `|#` ends it.

The problem is that multiline comments can be nested:

      #| a comment  #| still a comment |# even 
                                          more comment |#

Here is my non-working attempt:

    repository:
      multilinecomment: 
        begin:         \#\|
        end:           \|\#
        name:          comment
        contentName:   comment
        patterns:
        - include:     "#multilinecomment"
          name:        comment
        - match:       ([^\|]|\|(?=[^#]))*
          name:        comment

The intent of the match patterns are:

1. `"#multilinecomment"`
     A multiline comment can contain another multiline comment.
2. `([^\|]|\|(?=[^#]))*`
    The meaning of the subexpressions:

         [^\|]        any characters not an `|`
         \|(?=[^#])   an `|` followed by a non-`#`

The entire expression thus matches a string not containg |#

A Stackoverflow answer suggests that is a general problem due to the poor handling of multinline constructs in the TextMate grammar framework. Multiline comments are broken in C/C++, Java, HTML, PHP, and, JavaScript. 

I haven't tested Pascal but (* *) nested comments are probably also affected.

**Comment by pchaigno** [comment]
Good catch! Do you know if Atom and Sublime Text have the same issue?

**Comment by soegaard** [comment]
I still haven't found a way to support nested multiline comments.

However it turns out that some of the languages on the list has multiline comments - but that they are *not* allowed to be nested. That means JavaScript, Java og PHP can be stricken from the list.
I got the list of languages from a StackOverflow answer - but should have of course have fact checked - sorry.

Some variants of Pascal do allow nested comments (e.g. the fpc compiler) however.
Haskell is another language that allows nested multiline comments.

I have only tested the old Racket mode in Sublime Text. The MattDMo tested in Sublime - but he tested languages were nesting weren't allowed. See

http://stackoverflow.com/questions/27460207/matching-nested-constructs-in-textmate-sublime-text-atom-language-grammars

**Comment by pchaigno** [comment]
Have you tried contacting Textmate support? They probably are the best able to help you.

**Comment by soegaard** [comment]
I have now posted a question on the TextMate mailing list.

**Comment by pchaigno** [comment]
Is this issue solved? (I followed [your post](http://lists.macromates.com/textmate/2015-January/038267.html) on the Racket mailing list.)

**Comment by soegaard** [comment]
Yes.


2015-01-10 11:17 GMT+01:00 Paul Chaignon <notifications@github.com>:

> Is this issue solved? (I followed your post
> <http://lists.macromates.com/textmate/2015-January/038267.html> on the
> Racket mailing list.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/github/linguist/issues/1887#issuecomment-69450922>.
>



-- 
-- 
Jens Axel Søgaard

**Comment by arfon** [comment]
Can this be closed now @soegaard ?

**Comment by soegaard** [comment]
Yes.

2015-01-10 16:20 GMT+01:00 Arfon Smith <notifications@github.com>:

> Can this be closed now @soegaard <https://github.com/soegaard> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/github/linguist/issues/1887#issuecomment-69459204>.
>



-- 
-- 
Jens Axel Søgaard
