### ISSUE TITLE
AutoHotkey syntax highlighting stopped functioning?

### ISSUE THREAD

**Issue by lintalist** [github/linguist#1898]
It sees syntax highlighting on .ahk files in repositories and fenced code blocks in markdown files is no longer working.

```autohotkey
MsgBox This is a test ; MsgBox should be highlighted but isn't
```

**Comment by G33kDude** [comment]
Of all the available .tmLanguage files I could find for AutoHotkey, @robertcollier4 seems to have the best. It highlights my complex AutoHotkey scripts with the greatest accuracy.

**Comment by robertcollier4** [comment]
https://packagecontrol.io/packages/AutoHotkey
https://github.com/robertcollier4/AutoHotkey - it is a community package and the result of many contributors.
Would recommend using it as central AutoHotKey SublimeText .tmLanguage file - and submit improvements as Pull Requests to the Repo.

**Comment by pchaigno** [comment]
Pull request opened at #1951 :zap: 
Thanks @lintalist @G33kDude @robertcollier4!

**Comment by pchaigno** [comment]
@robertcollier4 Any chance you could pick a license at http://choosealicense.com and add it to your repository?

**Comment by robertcollier4** [comment]
I have added UNLICENSE.txt to the root of the AutoHotKey github repo.
https://github.com/robertcollier4/AutoHotkey/commit/a2207359782c564a9a3bfe5142d7b5a250d9b18b

**Comment by arfon** [comment]
This will be fixed when https://github.com/github/linguist/pull/1951 goes live in `v4.3.0` (:soon:)

**Comment by robertcollier4** [comment]
FYI the AutoHotKey package has been transferred to the ahkscript Github organization so that more people can participate. The new URL is:
https://github.com/ahkscript/AutoHotkey

**Comment by pchaigno** [comment]
@robertcollier4 I opened a pull requets to update the URL at #2058.
