### ISSUE TITLE
Detected as Abl but must be as python

### ISSUE THREAD

**Issue by Alexey-T** [github/linguist#1901]
these repos detected badly:
https://github.com/nodebox/nodebox-opengl
https://github.com/siddharth950/Neural-Tensor-Network

**Comment by Ferada** [comment]
We have a similar issue (in a private repository); the files (and the ones mentioned above as well?) are Python pickle files, but frankly, detecting file type by extension is not very useful; is it possible to force the OpenEdge ABL plugin to actually look at the content of files?
