### ISSUE TITLE
Syntax Highlighting not working anymore for Liquid

### ISSUE THREAD

**Issue by spplante** [github/linguist#1903]
Hi there,

My github has a project with Liquid syntax that was working well, until you guys migrated to TextMate. If I am not mistaken, Liquid has been created by the company "Shopify", they are pretty big here in Montreal. 

By looking at their GitHub, I found pretty much what you guys need in order to support Liquid syntax highlighting just like before :

https://github.com/Shopify/liquid-tmbundle

This is their TextMate bundle for liquid. If you guys could add this to GitHub's TextMate library it would be super cool and my "read me" file would start working back :)

Thanks!

**Comment by pchaigno** [comment]
Hi @spplante!
I opened an issue on the repository to add a license: Shopify/liquid-tmbundle#3.
Once this is done, I'll open a pull request to add it as a grammar for Liquid.
(I tested it in [Lightshow](https://lightshow.githubapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2FShopify%2Fliquid-tmbundle%2Fmaster%2FSyntaxes%2FHTML%2520Liquid.plist&grammar_text=&code_source=from-text&code_url=&code=%3C!DOCTYPE+html+PUBLIC+%22-%2F%2FW3C%2F%2FDTD+XHTML+1.0+Transitional%2F%2FEN%22%0D%0A++%22http%3A%2F%2Fwww.w3.org%2FTR%2Fxhtml1%2FDTD%2Fxhtml1-transitional.dtd%22%3E%0D%0A%0D%0A%3Chtml+xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F1999%2Fxhtml%22+xml%3Alang%3D%22en%22+lang%3D%22en%22%3E%0D%0A%3Chead%3E%0D%0A++%3Cmeta+http-equiv%3D%22Content-Type%22+content%3D%22text%2Fhtml%3B+charset%3Dutf-8%22%2F%3E%0D%0A++%3Ctitle%3E{{shop.name}}+-+{{page_title}}%3C%2Ftitle%3E%0D%0A%0D%0A++{{+%27textile.css%27++|+global_asset_url+|+stylesheet_tag+}}%0D%0A++{{+%27lightbox%2Fv204%2Flightbox.css%27+|+global_asset_url+|+stylesheet_tag+}}%0D%0A%0D%0A++{{+%27prototype%2F1.6%2Fprototype.js%27+|+global_asset_url++|+script_tag+}}%0D%0A++{{+%27scriptaculous%2F1.8.2%2Fscriptaculous.js%27+|+global_asset_url++|+script_tag+}}%0D%0A++{{+%27lightbox%2Fv204%2Flightbox.js%27++|+global_asset_url++|+script_tag+}}%0D%0A++{{+%27option_selection.js%27++++++++|+shopify_asset_url+|+script_tag+}}%0D%0A%0D%0A++{{+%27layout.css%27+++|+asset_url+|+stylesheet_tag+}}%0D%0A++{{+%27shop.js%27++++++|+asset_url+|+script_tag+}}%0D%0A%0D%0A++{{+content_for_header+}}%0D%0A%3C%2Fhead%3E%0D%0A%0D%0A%3Cbody+id%3D%22page-{{template}}%22%3E%0D%0A%0D%0A++%3Cp+class%3D%22hide%22%3E%3Ca+href%3D%22%23rightsiders%22%3ESkip+to+navigation.%3C%2Fa%3E%3C%2Fp%3E%0D%0A++++%3C!--+mini+cart+--%3E%0D%0A++++++++{%25+if+cart.item_count+%3E+0+%25}%0D%0A++++++%3Cdiv+id%3D%22minicart%22+style%3D%22display%3Anone%3B%22%3E%3Cdiv+id%3D%22minicart-inner%22%3E%0D%0A++++++%3Cdiv+id%3D%22minicart-items%22%3E%0D%0A++++++%3Ch2%3EThere+{{+cart.item_count+|+pluralize%3A+%27is%27%2C+%27are%27+}}+{{+cart.item_count+}}+{{+cart.item_count+|+pluralize%3A+%27item%27%2C+%27items%27+}}+in+%3Ca+href%3D%22%2Fcart%22+title%3D%22View+your+cart%22%3Eyour+cart%3C%2Fa%3E!%3C%2Fh2%3E%3Ch4+style%3D%22font-size%3A+16px%3B+margin%3A+0+0+10px+0%3B+padding%3A+0%3B%22%3EYour+subtotal+is+{{+cart.total_price+|+money+}}.%3C%2Fh4%3E%0D%0A++++++++{%25+for+item+in+cart.items+%25}%0D%0A++++++++%3Cdiv+class%3D%22thumb%22%3E%0D%0A++++++++++%3Cdiv+class%3D%22prodimage%22%3E%3Ca+href%3D%22{{item.product.url}}%22+onMouseover%3D%22tooltip%28%27{{+item.quantity+}}+x+{{+item.title+}}+%28{{+item.variant.title+}}%29%27%2C+200%29%22%3B+onMouseout%3D%22hidetooltip%28%29%22%3E%3Cimg+src%3D%22{{+item.product.featured_image+|+product_img_url%3A+%27thumb%27+}}%22+%2F%3E%3C%2Fa%3E%3C%2Fdiv%3E%0D%0A++++++++%3C%2Fdiv%3E%0D%0A++++++++{%25+endfor+%25}%0D%0A++++++++%3C%2Fdiv%3E%0D%0A+++++++%3Cbr+style%3D%22clear%3Aboth%3B%22+%2F%3E%0D%0A++++++%3C%2Fdiv%3E%3C%2Fdiv%3E%0D%0A++++++++{%25+endif+%25}%0D%0A%0D%0A++%3Cdiv+id%3D%22container%22%3E%0D%0A++++%3Cdiv+id%3D%22header%22%3E%0D%0A++++++%3C!--+Begin+Header+--%3E%0D%0A++++++++%3Ch1+id%3D%22logo%22%3E%3Ca+href%3D%22%2F%22+title%3D%22Go+Home%22%3E{{shop.name}}%3C%2Fa%3E%3C%2Fh1%3E%0D%0A++++++%3Cdiv+id%3D%22cartlinks%22%3E%0D%0A++++++++{%25+if+cart.item_count+%3E+0+%25}%0D%0A++++++++++%3Ch2+id%3D%22cartcount%22%3E%3Ca+href%3D%22%2Fcart%22+onMouseover%3D%22tooltip%28%27There+{{+cart.item_count+|+pluralize%3A+%27is%27%2C+%27are%27+}}+{{+cart.item_count+}}+{{+cart.item_count+|+pluralize%3A+%27item%27%2C+%27items%27+}}+in+your+cart!%27%2C+200%29%22%3B+onMouseout%3D%22hidetooltip%28%29%22%3E{{+cart.item_count+}}+{{+cart.item_count+|+pluralize%3A+%27thing%27%2C+%27things%27+}}!%3C%2Fa%3E%3C%2Fh2%3E%0D%0A++++++%3Ca+href%3D%22%2Fcart%22+id%3D%22minicartswitch%22+onclick%3D%22superSwitch%28this%2C+%27minicart%27%2C+%27Close+Mini+Cart%27%29%3B+return+false%3B%22+id%3D%22cartswitch%22%3EView+Mini+Cart+%28{{+cart.total_price+|+money+}}%29%3C%2Fa%3E%0D%0A++++++++{%25+endif+%25}%0D%0A++++++%3C%2Fdiv%3E%0D%0A++++++%3C!--+End+Header+--%3E%0D%0A%0D%0A++++%3C%2Fdiv%3E%0D%0A++%3Chr+%2F%3E%0D%0A%3Cdiv+id%3D%22main%22%3E%0D%0A%0D%0A++++%3Cdiv+id%3D%22content%22%3E%0D%0A++++%3Cdiv+id%3D%22innercontent%22%3E%0D%0A++++++{{+content_for_layout+}}%0D%0A++++++%3C%2Fdiv%3E%0D%0A++++%3C%2Fdiv%3E%0D%0A%0D%0A++%3Chr+%2F%3E%0D%0A++++%3Cdiv+id%3D%22rightsiders%22%3E%0D%0A%0D%0A++++++%3Cul+class%3D%22rightlinks%22%3E%0D%0A++++++++{%25+for+link+in+linklists.main-menu.links+%25}%0D%0A+++++++++++%3Cli%3E{{+link.title+|+link_to%3A+link.url+}}%3C%2Fli%3E%0D%0A++++++++{%25+endfor+%25}%0D%0A++++++%3C%2Ful%3E%0D%0A%0D%0A++++++++{%25+if+tags+%25}%0D%0A++++++++%3Cul+class%3D%22rightlinks%22%3E%0D%0A++++++++++{%25+for+tag+in+collection.tags+%25}%0D%0A++++++++++++%3Cli%3E%3Cspan+class%3D%22add-link%22%3E{{+%27%2B%27+|+link_to_add_tag%3A+tag+}}%3C%2Fspan%3E{{+tag+|+highlight_active_tag+|+link_to_tag%3A+tag+}}%3C%2Fli%3E%0D%0A++++++++++{%25+endfor+%25}%0D%0A++++++++%3C%2Ful%3E%0D%0A++++++++{%25+endif+%25}%0D%0A%0D%0A++++++%3Cul+class%3D%22rightlinks%22%3E%0D%0A++++++++{%25+for+link+in+linklists.footer.links+%25}%0D%0A+++++++++++%3Cli%3E{{+link.title+|+link_to%3A+link.url+}}%3C%2Fli%3E%0D%0A++++++++{%25+endfor+%25}%0D%0A++++++%3C%2Ful%3E%0D%0A%0D%0A++++%3C%2Fdiv%3E%0D%0A%0D%0A++%3Chr+%2F%3E%3Cbr+style%3D%22clear%3Aboth%3B%22+%2F%3E%0D%0A%0D%0A++++%3Cdiv+id%3D%22footer%22%3E%0D%0A++++++%3Cdiv+class%3D%22footerinner%22%3E%0D%0A++++++All+prices+are+in+{{+shop.currency+}}.%0D%0A++++++Powered+by+%3Ca+href%3D%22http%3A%2F%2Fwww.shopify.com%22+title%3D%22Shopify%2C+Hosted+E-Commerce%22%3EShopify%3C%2Fa%3E.%0D%0A++++%3C%2Fdiv%3E%0D%0A++++%3C%2Fdiv%3E%0D%0A%0D%0A++%3C%2Fdiv%3E%0D%0A%3C%2Fdiv%3E%0D%0A%0D%0A%3Cdiv+id%3D%22tooltip%22%3E%3C%2Fdiv%3E%0D%0A%3Cimg+id%3D%22pointer%22+src%3D%22{{+%27arrow2.gif%27+|+asset_url+}}%22+%2F%3E%0D%0A%0D%0A%3C%2Fbody%3E%0D%0A%3C%2Fhtml%3E%0D%0A) and it looks good)

**Comment by spplante** [comment]
Great thank you!

**Comment by arfon** [comment]
Closing this as we're tracking the fix over on https://github.com/Shopify/liquid-tmbundle/issues/3
