### ISSUE TITLE
C# code is recognized as SmallTalk

### ISSUE THREAD

**Issue by DerKnerd** [github/linguist#1907]
For an example check https://github.com/nant/nant

**Comment by JoshKeegan** [comment]
Having the same problem on [this project](https://github.com/JoshKeegan/PiSearch)

**Comment by JoshKeegan** [comment]
And also on [this project](https://github.com/JoshKeegan/hpop)

**Comment by pchaigno** [comment]
@arfon I'm trying to write an heuristic for this issue. Could you send me corpus of files for the following searches?
- https://github.com/search?o=asc&q=extension%3Acs+public&ref=searchresults&s=indexed&type=Code&utf8=%E2%9C%93 - should be mostly C# files
- https://github.com/search?o=desc&q=extension%3Acs+self+iftrue&ref=searchresults&s=indexed&type=Code&utf8=%E2%9C%93 - should be mostly Smalltalk files

Thanks :-)

**Comment by arfon** [comment]
@pchaigno - I've just sent you some samples for those searches.

**Comment by franklinchou** [comment]
You will also notice that for (many) of these projects, if you click on the colorized bar that displays the ratio of the project's various languages, clicking on "Smalltalk" will actually point nowhere on the page. This is a phenomenon that I find occurs when Linguist incorrectly recognizes the language.

**Comment by larsbrinkhoff** [comment]
Right, the language statistics bar can be inconsistent with search results from the repository.  Why is that?

**Comment by pchaigno** [comment]
I opened a pull request at #2003 with heuristic rules to solve these issues.

@arfon The samples from the second search were all from one unique repository so I tested the PR against the repository instead of the sample files you send me (the repository contains more than 43,000 Smalltalk files).

**Comment by arfon** [comment]
Thanks @pchaigno. https://github.com/github/linguist/pull/2003 is now merged but it will be another week or so before the changes are live on GitHub.

**Comment by ChayimFriedman2** [comment]
I've this problem too: see https://github.com/ChayimFriedman2/SimpleNETting/.

**Comment by rmunn** [comment]
@ChayimFriedman2 Looks like the [only file being detected as Smalltalk](https://github.com/ChayimFriedman2/SimpleNETting/search?l=Smalltalk) in your repo is `Lexing/TokenType.cs`, which has no `using` statements at the top of the file since it's only declaring a couple of enums. A simple workaround [that has worked for other people](https://github.com/github/linguist/pull/2003#issuecomment-201557389) is to add a `using` statement even if it's not actually needed in your code, like `using System;` on the top line. That should make the heuristic detect the file as C#.

**Comment by ChayimFriedman2** [comment]
I've guessed that reason, but anyway it's a bug.

‫בתאריך יום ד׳, 16 באוק׳ 2019 ב-17:09 מאת ‪Robin Munn‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by pchaigno** [comment]
You can use Linguist overrides to fix such errors. No need to change the source file. Please see the README.

**Comment by LeMorrow** [comment]
**For the lazy**
Add the following line to the `.gitattributes` file on your default branch:
```
*.cs linguist-language=C#
```
Wait between 5-20 minutes. If the problem still hasn't disappeared, make another change to the repository, clear cache and refresh.
