### ISSUE TITLE
Issue with bash syntax highlight

### ISSUE THREAD

**Issue by martincmelik** [github/linguist#1918]
Hi,

it seems that linguist (in fact grammars.yml) have issue with recognition of where start and where ends variable definition in format:
```bash
VAR1="${VAR1:-"default-${VAR2}-data"}"
```
As you can see, starting from line https://github.com/martincmelik/Securix-Linux/blob/master/securix-install/install.sh#L58 code is wrongly colorized.
Unfortunately I'm not using TextMate so I will not be the best person for pull request.

More info: https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html

Thank you for looking into this!

**Comment by arfon** [comment]
@martincmelik - I tried out a different Textmate grammar with your snippet and this [looks better to me](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Ftextmate%2Fshellscript.tmbundle%2Fmaster%2FSyntaxes%2FShell-Unix-Bash.tmLanguage&grammar_text=&code_source=from-text&code_url=&code=VAR1%3D%22%24%7BVAR1%3A-%22default-%24%7BVAR2%7D-data%22%7D%22) - can you confirm and perhaps test with some other files?

**Comment by arfon** [comment]
:flags: flagging this as stale :flags:
