### ISSUE TITLE
Regression: Add support for highlighting "pycon" (Python console/doctest)

### ISSUE THREAD

**Issue by msabramo** [github/linguist#1939]
Please add back support for using the "pycon" syntax highlighting that worked for years when GitHub was using Pygments. Linguist apparently lacks support for this. It's probably just a variation of the highlighter for Python or for Python tracebacks, if that is supported (hmmm, is it?)

MIME type:  `text/x-python-doctest`

Note that the following snippet using "pycon" is not highlighted. It used to be highlighted nicely when GitHub used Pygments:

``` pycon
>>>  try:
...     from io import StringIO
... except ImportError:
...     from StringIO import StringIO
```

The "python" highlighter does a reasonable job. It would be nicer if it ">>>" and "..." were colored differently but this is not bad. 

``` python
>>>  try:
...     from io import StringIO
... except ImportError:
...     from StringIO import StringIO
```

Experiment using "pytb":

``` pytb
>>>  try:
...     from io import StringIO
... except ImportError:
...     from StringIO import StringIO
```

"pycon" lexer is documented at http://pygments.org/docs/lexers/#lexers-for-python-and-related-languages

Demo of it using Pygments: http://pygments.org/demo/1061247/?style=default

**Comment by arfon** [comment]
Thanks for reporting this @msabramo - could you please link me to a file that _should_ be highlighted correctly (but no-longer is?)

**Comment by msabramo** [comment]
- https://github.com/naiquevin/lookupy/blob/master/README.rst
- https://github.com/pythonsd/presentations/blob/21dc794ee5e965ee5087663063e0847fb63c8fea/list_comprehensions/README.rst
- https://github.com/rbarrois/python-semanticversion/blob/master/README.rst
- https://github.com/jrydberg/etcd-py/blob/5112d01d4d3ff18db2a2c2a4f6c5251c037eb311/README.rst
- https://github.com/pmuller/versions/blob/951bc3fd99b6a675190f11ee0752af1d7ff5b440/README.rst
- https://github.com/rhyselsmore/log-metrics/blob/ecd843cb300524d1d5039abdbcf75c8de1b88ef4/README.rst
- https://github.com/joaopinto461/CampusTV-Proxy/blob/8f0163c14ada8123cd936117ad7e1c72aa755af6/videosPython/README.rst
- https://github.com/mkolodny/3taps/blob/f7764337381d55badb6f551de5fae0925fb2cc61/README.rst
- https://github.com/czterybity/python_doc/blob/b12118436feb34c1ee742b3f03c9b05a74914b5b/sphinx/adv/2vs3.rst
- https://github.com/djfroofy/beatlounge/blob/6ab173e2e1e3a8a357063e020f0392fa71330382/docs/music/notes_notes.rst
- https://github.com/glenfant/robotframework-consoledialogs/blob/e7ac387f57ab4b75c6c7800c5cca4ca5d4559849/tests/test_narrative.rst

I could also find a bunch with this search: https://github.com/search?q=code-block%3A%3A+pycon&type=Code&utf8=✓

**Comment by arfon** [comment]
Thanks @msabramo. I think this might actually be an issue for https://github.com/github/markup / cc @bkeepers

**Comment by msabramo** [comment]
github/markup links to this other repo which uses Linguist:

https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/syntax_highlight_filter.rb

**Comment by bkeepers** [comment]
This used to work because the [syntax highlight filter](https://github.com/jch/html-pipeline/blob/5feb0c185fb1e5037e3ad6d6bd533fb4af3685d8/lib/html/pipeline/syntax_highlight_filter.rb#L39) falls back to looking up lexers in pygments (`Pygments::Lexer[lang]`), which defines the [pycon lexer](http://pygments.org/docs/lexers#pygments.lexers.python.PythonConsoleLexer). We will need to add support for pycon, which means we will need a grammar for it. I didn't find one in my quick googling. The [pygments version](https://bitbucket.org/birkenfeld/pygments-main/src/c479af13420f8b1232c382bb1ad1d2e6d06212bf/pygments/lexers/python.py?at=default#cl-305) just extends the python lexer and strips out the prompt and console output.

/cc @aroben

**Comment by aroben** [comment]
This should be pretty easy to write a TextMate-style grammar for. See https://github.com/atom/language-shellscript/blob/master/grammars/shell-session.cson and https://github.com/atom/language-python/blob/master/grammars/python-traceback.cson for examples of grammars that are just wrappers around another programming language.

**Comment by msabramo** [comment]
Thanks, @aroben! I'll take a stab at it 

1. How do I test? Use the Atom editor I guess?
2. One of the samples you linked to was Python Traceback (`pytb`) but I used \```pytb above in this issue and it didn't highlight? Why?

**Comment by msabramo** [comment]
Hmmm maybe the answer to 2 is that I didn't use an actual tracebacks so it's no matching the patterns.

**Comment by msabramo** [comment]
Let's see if I'm right about pytb...

```pytb
Traceback (most recent call last):
  File "tb.py", line 10, in <module>
    a()
  File "tb.py", line 2, in a
    b()
  File "tb.py", line 5, in b
    c()
  File "tb.py", line 8, in c
    error()
NameError: global name 'error' is not defined
```

**Comment by msabramo** [comment]
So in theory if I create a grammar and you folks merge it in, then the following will render in beautiful color:

```pycon
>>>  try:
...     from io import StringIO
...     print("Imported StringIO from io")
... except ImportError:
...     from StringIO import StringIO
...     print("Imported StringIO from StringIO")
... print("StringIO = %s" % StringIO)
...
```

**Comment by msabramo** [comment]
@aroben: Have a look at https://github.com/atom/language-python/pull/48 when you get a chance.

**Comment by aroben** [comment]
> How do I test? Use the Atom editor I guess?

Testing in Atom is good, but you should also test using https://lightshow.githubapp.com in case there are any discrepancies between Atom's highlighter and github.com's highlighter. (If you find any, please tell us!)

> One of the samples you linked to was Python Traceback (`pytb`) but I used ```pytb above in this issue and it didn't highlight? Why?

You need to specify `text.python.traceback` as the language. `pytb` isn't a string that Linguist knows about.

**Comment by msabramo** [comment]
https://github.com/atom/language-python/pull/48 was merged. Can we schedule pushing that out to github.com?

**Comment by aroben** [comment]
I pulled in the fix in #1953. It should make its way over to github.com within a couple of weeks.

**Comment by aroben** [comment]
> > One of the samples you linked to was Python Traceback (`pytb`) but I used ```pytb above in this issue and it didn't highlight? Why?

> You need to specify `text.python.traceback` as the language. `pytb` isn't a string that Linguist knows about.

I was wrong about this. `pytb` works because `.pytb` is the filename extension for Python Traceback files. And you can see that your example is now highlighted correctly.

**Comment by msabramo** [comment]
Any update on when this might go live?

**Comment by aroben** [comment]
@msabramo Whoops, we had some discussion about this internally and I forgot to update the issue. Sorry about that.

The pycon grammar is live on github.com, but there's currently no way to invoke it. Code blocks in Markdown on github.com can use any language name or language alias known to Linguist, but there's no language that corresponds to "Python console" in Linguist currently.

Are there any standard filenames or filename extensions that are associated with "Python console" files? If there are, then adding a new language is pretty easy as [documented in `CONTRIBUTING.md`](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). In addition to making `pycon` work in code blocks in Markdown, this will also help those files get detected correctly in repositories.

If there is no such thing as a "Python console file", then we could still add a "Python console" language to Linguist purely for the purpose of exposing the `pycon` grammar for code blocks. We'll need to make sure that Linguist behaves OK when there's a language with no filenames or filenames extensions listed. It will probably work just fine, but @arfon and @bkeepers might know of some pitfalls.

**Comment by msabramo** [comment]
I've never seen python console stuff in a file by itself. I suppose if it made your job easier, we could invent a .pycon file type.

**Comment by aroben** [comment]
In that case I think we should explore adding a language with no filenames/filename extensions. I suspect we'll want this in the future for other syntaxes that have no associated file type.

**Comment by pchaigno** [comment]
> In that case I think we should explore adding a language with no filenames/filename extensions. I suspect we'll want this in the future for other syntaxes that have no associated file type.

@aroben #1837 is adding two languages with no filenames/extensions. You might want to take a look ;)

**Comment by homeworkprod** [comment]
I'd like to see "pycon" syntax highlighting working again, too.

Wasted some time on research why this isn't working *anymore* until I found this issue. :(

**Comment by alexpirine** [comment]
I'm interested in this feature as well.

**Comment by homeworkprod** [comment]
Since `pycon` highlighting *did* work for a long time but currently isn't, I think this issue should be labeled as a bug.

**Comment by Alhadis** [comment]
This is probably because the [site's Markdown grammar](https://github.com/atom/language-gfm/blob/master/grammars/gfm.cson#L550-L565) doesn't define a pattern-match for `pycon`.

To embed a TextMate grammar inside another, it needs to be either declared explicitly in the grammar file (with `include: text.python.console`) or using a TextMate feature called an `injection` (where patterns are injected into foreign scopes, irrespective of whether the target's grammar actually expects it).

So, the fix should be reasonably simple. I'll look into it.

**Comment by Alhadis** [comment]
Right. I'm not 100% sure if this *will* fix the issue, but it's a start.

**Comment by Alhadis** [comment]
@pchaigno Isn't this less an issue with `languages.yml` and more a case of syntax highlighting?

**Comment by pchaigno** [comment]
Fixed with #3092.

**Comment by pradyunsg** [comment]
Hi hi -- is this still working?

https://github.com/pypa/packaging/issues/216#issuecomment-538252420

**Comment by Alhadis** [comment]
> I don't see the required highlighting

It's working fine. Your code just happens to contain only strings, which GitHub doesn't highlight very well:

<img src="https://user-images.githubusercontent.com/2346707/66252680-a07fed00-e7a1-11e9-82e2-868deea3ccbc.png" alt="Figure 1" />

Because `#032f62` is close to the default colour `#24292e`, you aren't noticing the difference. Might want to bring this up with GitHub support and ask their designers to fix their godawful colour scheme. 😉

**Comment by pradyunsg** [comment]
Thanks for taking a look @Alhadis and for the helpful explanation!

I think I'll... just let it be. Too tired to follow up on this in this week.
