### ISSUE TITLE
Markdown Highlighting Strangely in Pull Requests

### ISSUE THREAD

**Issue by parkr** [github/linguist#1943]
The new diff syntax highlighting is excellent, but I noticed one problem: markdown files seem to have the wrong lexer applied. Here's one of @benbalter's pull requests I was just reading:

![screen shot 2015-01-02 at 1 34 12 pm](https://cloud.githubusercontent.com/assets/237985/5599885/3799b50e-9284-11e4-9e3e-8aa182cff3a2.png)

Is this a linguist problem?

**Comment by arfon** [comment]
Hrm, not sure. Assuming that post is public you post a link to that view so I can take a closer look?

**Comment by parkr** [comment]
(Mobile version... Still causing problems for me heh) 

Here's the link https://github.com/benbalter/benbalter.github.com/pull/197/files

**Comment by arfon** [comment]
I don't think this is a Linguist thing. I'm pretty sure it's to do with our new syntax highlighter. / cc @aroben

**Comment by aroben** [comment]
Yep, this is a problem with the highlighter itself. It's misinterpreting the regex that identifies the YAML front matter. We're looking into it. Thanks @parkr and sorry for the trouble.

**Comment by parkr** [comment]
Not at all! Thanks for checking it out. :)

**Comment by vmg** [comment]
Fixed!

**Comment by parkr** [comment]
Thanks, @vmg!
