### ISSUE TITLE
New Grammar for Racket

### ISSUE THREAD

**Issue by soegaard** [github/linguist#1946]
I have written a new grammar for Racket that improves the current syntax highlighting.
The grammar and a link to light show was posted to the Racket mailing list, in order for people to try it out. 

The new grammar is here:
    https://github.com/soegaard/racket-highlight-for-github/blob/master/racket.tmLanguage

**Comment by pchaigno** [comment]
Did you get any feedback from the Racket mailing list?
Do you have an example of what it improves in [Lightshow](http://lightshow.githubapp.com/)?

**Comment by soegaard** [comment]
No feedback from the mailing list, but lots of a positive feedback from the #racket IRC channel,
including from the author of the previous Pygments lexer for Racket.

Improvements:
  - no incorrect error highlighting 
  - correct highlighting of numbers (including binary, octal, hexadecimal, inexact and exact numbers)
  - comprehensive list of keywords
  - correct nested multiline comments
  - no incorrect interpretation of s-expression comments  
      (that begins with #; and uncomments the following line)

An example file, line 62 is the first number example.
Original:
     https://github.com/dscorbett/pygments/blob/master/tests/examplefiles/example.rkt#L62
Improved:
     https://lightshow.githubapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fsoegaard%2Fracket-highlight-for-github%2Fmaster%2Fracket.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fdscorbett%2Fpygments%2F78f24f4def553698979b785739461fc7602f777b%2Ftests%2Fexamplefiles%2Fexample.rkt&code=

**Comment by pchaigno** [comment]
Looks good! Do you want to open a pull request to use this grammar or should I do it?

**Comment by soegaard** [comment]
It would be great if you do it, thanks.

/Jens Axel



2015-01-10 11:44 GMT+01:00 Paul Chaignon <notifications@github.com>:

> Looks good! Do you want to open a pull request to use this grammar or
> should I do it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/github/linguist/issues/1946#issuecomment-69451621>.
>



-- 
-- 
Jens Axel Søgaard

**Comment by pchaigno** [comment]
@soegaard Could you add a license to your repository? Any of those should be fine: http://choosealicense.com/

**Comment by soegaard** [comment]
I have added an MIT License.

 /Jens Axel


2015-01-10 13:15 GMT+01:00 Paul Chaignon <notifications@github.com>:

> @soegaard <https://github.com/soegaard> Could you add a license to your
> repository? Any of those should be fine: http://choosealicense.com/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/github/linguist/issues/1946#issuecomment-69453842>.
>



-- 
-- 
Jens Axel Søgaard

**Comment by arfon** [comment]
Thanks @soegaard - this is now merged in https://github.com/github/linguist/pull/1982
