### ISSUE TITLE
Syntax highlighting for diff files wrong

### ISSUE THREAD

**Issue by MarkusH** [github/linguist#1947]
I wanted to comment on a PR and attach a diff of changes for the user to apply. The rendered output looked completely broken. I broke the diff down to a few lines to show the problem:

![diff1](https://cloud.githubusercontent.com/assets/475613/5607134/a14e86f8-944d-11e4-8bc1-0be4f343d06f.png)
![diff2](https://cloud.githubusercontent.com/assets/475613/5607133/a146bf7c-944d-11e4-842e-9deedc0e5d25.png)

**Comment by aroben** [comment]
I think this is rendering as expected, but @jonrohan would know for sure.

Maybe I'm missing the problem; can you describe what looks wrong to you?

**Comment by MarkusH** [comment]
I'd expect:

1. the line with `~~~` to show up as the second line of the before-context (the blank line to be line 3)
2. the line "One of the ..." be highlighted in red
3. the lind the one "or not to ..." to be highlighted in green
4. everything from "particular database." on up to before the code end marker to be diff after-context.

**Comment by pchaigno** [comment]
@MarkusH Do you mean that [this gist](https://gist.github.com/pchaigno/828292fed285ad48ee97) has the correct rendering? 

It looks like an issue with the Markdown renderer to me. As if the `~~~~~~~~~~` line was interpreted as the end of ```?

**Comment by MarkusH** [comment]
@pchaigno yes, this gist is rendered correctly.

**Comment by bkeepers** [comment]
Thanks for the bug report, I am able to [duplicate the issue](https://gist.github.com/bkeepers/f4dadc82a6bda9910567). I've reported it to our team that maintains our markdown parser. Since the issue can't be fixed by a change to linguist, I'm going to close this issue.

**Comment by MarkusH** [comment]
Thanks, @bkeepers

**Comment by aroben** [comment]
@MarkusH Thanks for the detailed explanation. It seems so obvious now, but I just couldn't see it before. :sparkling_heart:
