### ISSUE TITLE
.gitattributes and syntax highlighting

### ISSUE THREAD

**Issue by rubys** [github/linguist#1957]
I added a .gitattributes file, but I don't get the desired syntax highlighting.  What am I doing wrong?

I started here:

https://help.github.com/articles/my-repository-is-marked-as-the-wrong-language/

I made this change:

https://github.com/rubys/wicker/commit/5712b32d9ee82198fd32bba44d930b9841c78c20

Still no syntax highlighting for my DSL:

https://github.com/rubys/wicker/blob/master/views/entry._html

**Comment by aroben** [comment]
Hi @rubys. Sorry you're having trouble.

The `linguist-language` attribute currently only affects your repository's language stats:

![screen shot 2015-01-08 at 10 58 09 am](https://cloud.githubusercontent.com/assets/917945/5665269/414efe4c-9725-11e4-9481-4a8f60e8d7f9.png)

We don't take it into account when syntax highlighting for performance reasons. To fix the highlighting we'd have to teach Linguist to correctly detect the language as Ruby without `.gitattributes`. https://github.com/github/linguist/blob/master/CONTRIBUTING.md#my-code-is-detected-as-the-wrong-language has suggestions for doing this. In this case, we'd need to teach it about the `._html` extension. In general we try to be fairly conservative and only add extensions once they're in wide use. It [looks like](https://github.com/search?utf8=✓&q=do+extension%3A_html&type=Code&ref=searchresults) this DSL is not in wide use yet, so adding that extension to Linguist is probably not appropriate at this time.

We are definitely thinking about how to make `.gitattributes` affect syntax highlighting, but haven't come up with a solution yet. Thanks for giving us another use-case for it. I'm sorry there isn't much else we can do right now!

**Comment by ernstki** [comment]
For those from the future (hello future people!) who find themselves here after doing a web search, I believe this is documented [here](https://github.com/github/linguist/blob/master/docs/overrides.md) now, and I believe can confirm this is working in the year 2021.
