### ISSUE TITLE
Particular CMakeLists.txt file not detected as CMake

### ISSUE THREAD

**Issue by aroben** [github/linguist#1961]
https://github.com/serge-v/ctests/blob/fbce433d9fa09465a2b883a1e320a5e2c242ba97/departures/CMakeLists.txt is getting detected as `Text`, rather than `CMake`:

```console
$ bundle exec linguist CMakeLists.txt 
CMakeLists.txt: 29 lines (20 sloc)
  type:      Text
  mime type: text/plain
  language:  Text
```

/cc @serge-v

**Comment by aroben** [comment]
The problem starts here:

```
> Linguist::Language.find_by_filename("CMakeLists.txt")
=> [#<Linguist::Language name=CMake>, #<Linguist::Language name=Text>]
```

It feels to me like a file called `CMakeLists.txt` should always be classified as CMake. Sure, it has a `.txt` extension, but it seems very unlikely for someone to create a file called `CMakeLists.txt` that is *not* CMake.

/cc @bkeepers because you've worked on this disambiguation stuff before.

**Comment by bkeepers** [comment]
Interesting. So I'm guessing that the classifier is choosing `Text` over  `CMake`. Here's the sample we have for `CMakeList.txt`: https://github.com/github/linguist/blob/master/samples/CMake/filenames/CMakeLists.txt

I know we talked at one point about having the file names be authoritative, but that has its own set of issues (.e.g someone has a file named `build.xml` that is not actually an Ant file).

I think my suggestion would be to start by adding more samples (or a bigger sample) for CMake.

**Comment by larsbrinkhoff** [comment]
Another suggestion would be to add a `disambiguate "Cmake", "Text"` heuristic.  I'm willing to take a stab at this.

**Comment by bkeepers** [comment]
I think we should only use heuristics if absolutely necessary. It feels like this one should be resolvable with better samples.

**Comment by arfon** [comment]
> I think we should only use heuristics if absolutely necessary. It feels like this one should be resolvable with better samples. /cc @arfon

Agreed. Do you think you could grab some more samples @larsbrinkhoff?

**Comment by larsbrinkhoff** [comment]
@arfon Ok.  What's the policy for selecting samples from random repos?  Which licenses are compatible with Linguist?

**Comment by arfon** [comment]
> @arfon Ok. What's the policy for copying sample files from random repos? Which licenses are compatible with Linguist?

Well [these ones](https://github.com/github/linguist/blob/master/test/test_grammars.rb#L110-L133) are compatible as grammars so I'd expect them to be OK for us too?

**Comment by aroben** [comment]
Anything on choosealicense.com (other than "no license") should be fine.

**Comment by larsbrinkhoff** [comment]
Ok, #1978 now has a sanitised version of @serge-v's CMakeLists.txt, plus five more samples, plus one from @pchaigno.
