### ISSUE TITLE
Symta

### ISSUE THREAD

**Issue by maxwell5** [github/linguist#1966]
Github confuses Symta for Assembly.
Please, fix this. It's urgent!

Example:
https://github.com/saniv/symta-iso
https://github.com/saniv/symcraft

**Comment by arfon** [comment]
Hi @maxwell5 - it doesn't look like we know about Symta as a language - you can see the supported languages [here](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml)

If you'd like us to support Symta then please take a look at our [contributor guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#i-want-to-add-support-for-the-x-programming-language)

**Comment by missionarycrm** [comment]
HELP ME NOW TO CORRECT ITNOW

On 1/8/15, Arfon Smith <notifications@github.com> wrote:
> Closed #1966.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/github/linguist/issues/1966#event-215706158


-- 
DR HAPURUCHI  INNO(UZOMA) RICHARD
