### ISSUE TITLE
projects marked wrong language

### ISSUE THREAD

**Issue by wewoor** [github/linguist#1967]
The project is ZBLOG,  main coded by Java. thank you .

**Comment by arfon** [comment]
Could you please include a URL to the project page?

**Comment by wewoor** [comment]
This is URL: https://github.com/wewoor/ZBLOG. it's marked Css..

**Comment by arfon** [comment]
Ah ok, that's because you've got some large CSS files here: https://github.com/wewoor/ZBLOG/search?l=css

You can learn how to remove them from your language statistics here: https://github.com/github/linguist#overrides
