### ISSUE TITLE
Add support for highlighting "http"

### ISSUE THREAD

**Issue by msabramo** [github/linguist#1968]
I like having syntax highlighting when looking at HTTP requests and responses, mostly for the headers, which is simple to develop a grammar for.

Here's a [grammar that I created in Lightshow](https://lightshow.githubapp.com/?utf8=%E2%9C%93&scope=from-text&grammar_url=&grammar_text=%7B%0D%0A++%22scopeName%22%3A+%22text.http%22%2C%0D%0A++%22name%22%3A+%22HTTP%22%2C%0D%0A++%22fileTypes%22%3A+%5B%0D%0A++++%22http%22%0D%0A++%5D%2C%0D%0A++%22patterns%22%3A+%5B%0D%0A++++%7B%0D%0A++++++%22match%22%3A+%22%5E%28%5BA-Z%5D%2B%29+%28%2Fapps%29+%28HTTP%2F1.1%29%24%22%2C%0D%0A++++++%22comment%22%3A+%22E.g.%3A+GET+%2Fpath%2Fto%2Fpage+HTTP%2F1.1%22%2C%0D%0A++++++%22captures%22%3A+%7B%0D%0A++++++++%221%22%3A+%7B%0D%0A++++++++++%22name%22%3A+%22keyword.method.http%22%0D%0A++++++++%7D%2C%0D%0A++++++++%222%22%3A+%7B%0D%0A++++++++++%22name%22%3A+%22constant.numeric.integer.decimal.http%22%0D%0A++++++++%7D%2C%0D%0A++++++++%223%22%3A+%7B%0D%0A++++++++++%22name%22%3A+%22constant.proto.http%22%0D%0A++++++++%7D%0D%0A++++++%7D%0D%0A++++%7D%2C%0D%0A++++%7B%0D%0A++++++%22match%22%3A+%22%5E%28HTTP%2F%5B%5C%5Cd%5C%5C.%5D%2B%29+%28%5C%5Cd%2B%29+%28.%2B%29%24%22%2C%0D%0A++++++%22comment%22%3A+%22E.g.%3A+HTTP%2F1.1+400+Bad+Request%22%2C%0D%0A++++++%22captures%22%3A+%7B%0D%0A++++++++%221%22%3A+%7B%0D%0A++++++++++%22name%22%3A+%22constant.proto.http%22%0D%0A++++++++%7D%2C%0D%0A++++++++%222%22%3A+%7B%0D%0A++++++++++%22name%22%3A+%22constant.numeric.integer.decimal.http%22%0D%0A++++++++%7D%2C%0D%0A++++++++%223%22%3A+%7B%0D%0A++++++++++%22name%22%3A+%22support.message.http%22%0D%0A++++++++%7D%0D%0A++++++%7D%0D%0A++++%7D%2C%0D%0A++++%7B%0D%0A++++++%22match%22%3A+%22%5E%28%5C%5CS%2B%29%28%3A%29+%28.%2B%29%24%22%2C%0D%0A++++++%22captures%22%3A+%7B%0D%0A++++++++%221%22%3A+%7B%0D%0A++++++++++%22name%22%3A+%22entity.name.tag.http%22%0D%0A++++++++%7D%2C%0D%0A++++++++%222%22%3A+%7B%0D%0A++++++++++%22name%22%3A+%22punctuation.separator.key-value.http%22%0D%0A++++++++%7D%2C%0D%0A++++++++%223%22%3A+%7B%0D%0A++++++++++%22name%22%3A+%22string.unquoted.http%22%0D%0A++++++++%7D%0D%0A++++++%7D%0D%0A++++%7D%0D%0A++%5D%0D%0A%7D%0D%0A&code_source=from-text&code_url=&code=%24+http+-v+HEAD+http%3A%2F%2Fmy-cool-app.127.0.0.1.xip.io%3A8080%2Fapps%0D%0AGET+%2Fapps+HTTP%2F1.1%0D%0AAccept%3A+*%2F*%0D%0AAccept-Encoding%3A+gzip%2C+deflate%0D%0AConnection%3A+keep-alive%0D%0AHost%3A+my-cool-app.127.0.0.1.xip.io%3A8080%0D%0AUser-Agent%3A+HTTPie%2F0.8.0%0D%0A%0D%0A%0D%0A%0D%0AHTTP%2F1.1+404+Page+not+found%0D%0AConnection%3A+keep-alive%0D%0ADate%3A+Wed%2C+07+Jan+2015+22%3A46%3A44+GMT%0D%0ACache-Control%3A+no-cache%0D%0AContent-Type%3A+text%2Fhtml%0D%0AExpires%3A+-1%0D%0APragma%3A+no-cache%0D%0A).

![screen shot 2015-01-07 at 10 06 32 pm](https://cloud.githubusercontent.com/assets/305268/5658625/d030ad16-96b9-11e4-9980-b08649210f70.png)

**Comment by msabramo** [comment]
Here's a gist with the `http.json` grammar: https://gist.github.com/msabramo/bd6459bc7f8d04b64404

**Comment by arfon** [comment]
Hi @msabramo - thanks for this contribution! We've actually got a pull request that's nearly complete over here: https://github.com/github/linguist/pull/1975
