### ISSUE TITLE
Grammar for Elisp mistakes ?\"  as beginning of string

### ISSUE THREAD

**Issue by soegaard** [github/linguist#1971]
The Elisp syntax for " as a character literal is ?\"
The highlighter doesn't recognize it, and highlights everything that follows as a string.

Example:
https://github.com/emacsmirror/paredit/blob/master/paredit.el#L790

**Comment by nikolas** [comment]
I just ran into this bug as well. Here's another example: https://github.com/syohex/emacs-editutil/blob/master/editutil.el#L131

**Comment by arfon** [comment]
I'm afraid this is a bug with the Elisp grammar. Please could you report this issue here: https://github.com/textmate/lisp.tmbundle

**Comment by nikolas** [comment]
Oh right.. looks like there's already an issue for this here: https://github.com/textmate/lisp.tmbundle/issues/1

**Comment by arfon** [comment]
Looks like that project is a little stale (no updates for a couple of years). It might be worth looking for alternative grammars? You can test them here: https://lightshow.githubapp.com/
