### ISSUE TITLE
Option to disable syntax highlighting

### ISSUE THREAD

**Issue by greghendershott** [github/linguist#1972]
As a paying GitHub customer, I'm frustrated to still see incorrect code highlighting. I continue to encounter new bugs, like [75% of a file being highlighted as a string](https://github.com/emacsmirror/paredit/blob/master/paredit.el#L790) because [`?"` isn't recognized as a char literal in Lisp](https://github.com/github/linguist/issues/1971). It's really distracting.

Therefore: **I would like an option to disable highlighting completely**.  For all repos, as viewed when I'm logged in, would suffice.

That would make me happier, at least while you continue to beta-test and fix the bugs over the coming weeks or months.

And for you, every user like me who disables highlighting, will improve your performance, which [you've stated is your top priority](https://github.com/github/linguist/issues/1717#issuecomment-63681177).  Doing no highlighting at all will be even faster, and is guaranteed not to be buggy.

So it would seem to be win-win.

To be clear, although yeah I'm feeling a little prickly about this, no this isn't a rhetorical request. If you provided such an option, I would actually use it, immediately.

Thank you in advance for considering this request.

**Comment by bucaran** [comment]
:Y
An option to _enable_ or rather, [_force_](http://webapps.stackexchange.com/questions/31654/force-github-syntax-highlighting-language-on-source-files) a particular syntax would be desirable too. I don't mind github telling me my [fish](https://fishshell.com) projects are shell, but it would be nice if there was a way to color code force files without an extension.

**Comment by arfon** [comment]
Hey @greghendershott - thanks for this feedback. I understand that this is frustrating.

I'd love your thoughts on [this PR](https://github.com/github/linguist/pull/2041) that has just merged which brings support for Vim and Emacs modelines to override the language detection. Would this help at all?

I realize that the bug you're talking about may be in the syntax-highlighting grammar (and so https://github.com/github/linguist/pull/2041 may not be a solution to your issue) but I'd be interested in your feedback nonetheless.

Thanks for keeping us on our toes :smile:

**Comment by greghendershott** [comment]
@arfon Thank you for following up.

#2041 sounds like a good idea for language identification.

However my frustration is with the syntax highlighting, as discussed in #1717.

**Comment by greghendershott** [comment]
Meanwhile I'm using [this](https://gist.github.com/greghendershott/671dd311b77569ba2eaf) with Stylish to disable seeing the highlighting. But still you're burning cycles to create it. Which is unfortunate and ironic since performance was the stated motivation for degrading the highlighting. So the status quo is meh/lose (customers/you). My proposal would make it meh/win.

**Comment by bkeepers** [comment]
@greghendershott I understand your frustration. Syntax highlighting bugs are really annoying. We are definitely open to considering adding a feature to disable syntax highlighting if there are other use cases, but I think hiding bugs in syntax highlighting is a compelling reason.

I think the best path forward is to fix the grammar or find one that is better maintained, as @arfon mentions in https://github.com/github/linguist/issues/1971.

**Comment by greghendershott** [comment]
@bkeepers I'm curious, did you look at using Rouge [https://github.com/jneen/rouge]?  AFAICT its goal is to be a port of Pygments to Ruby.

Although it may not have as many or as up-to-date lexers as Pygments, now, with a little love from you it could catch up.  Probably quickly: Although I don't believe that all Pygments lexers could be mechanically ported to Rouge, even doing so manually seems to be a significantly simpler effort than the status quo?

**Comment by aroben** [comment]
> did you look at using Rouge?

I believe we did and found it not to be fast enough. As I mentioned over in https://github.com/github/linguist/issues/1717#issuecomment-63681177, performance was the main motivation for switching away from Pygments. Maybe Rouge has gotten faster since we last checked though?
