### ISSUE TITLE
Heavily commented shell script detected as groff

### ISSUE THREAD

**Issue by oldlaptop** [github/linguist#1991]
This (comment-heavy, but also explicitly shebanged as #! /bin/sh) shell script in one of my repos seems to be detected as groff: https://github.com/oldlaptop/uqm-crossbuilder/blob/master/config/includes.chroot/usr/lib/crossbuild/crossbuild_liblua5.1

This doesn't seem to be specific to Linguist, my editor (kate) also misidentifies it, as "Troff Mandoc".

**Comment by arfon** [comment]
Perhaps I'm missing something but I can't seen any reference to Groff in the repo statistics here: https://github.com/oldlaptop/uqm-crossbuilder

![screen shot 2015-01-13 at 4 11 48 pm](https://cloud.githubusercontent.com/assets/4483/5730328/cab07428-9b3e-11e4-9171-9b3924a4aed2.png)

**Comment by oldlaptop** [comment]
It's one 60-line shell script out of about a thousand lines and 25 or so scripts, that's apparently below the status bar's noise level. The file is listed as groff in the "detailed" search view (https://github.com/oldlaptop/uqm-crossbuilder/search?l=groff) and obviously is highlighted as groff.

**Comment by arfon** [comment]
> It's one 60-line shell script out of about a thousand lines and 25 or so scripts, that's apparently below the stat bar's noise level. The file is listed as groff in the "detailed" search view (https://github.com/oldlaptop/uqm-crossbuilder/search?l=groff) and obviously is highlighted as groff.

Sorry I missed that. We currently support [overrides](https://github.com/github/linguist#overrides) for language reporting but these aren't used for [syntax highlighting](https://github.com/github/linguist/issues/1792) or search results yet I'm afraid.

**Comment by pchaigno** [comment]
Has there ever been a case where the shebang strategy failed? This issue makes me think that maybe [the shebang strategy should be the first one to try](https://github.com/github/linguist/blob/master/lib/linguist/language.rb#L96-L100). It would require a bit of work since currently the first strategy is also generating the list of candidates but it could surely help solve this type of issue.

/cc @bkeepers

**Comment by arfon** [comment]
Looks like this was fixed in https://github.com/github/linguist/issues/2085
