### ISSUE TITLE
C files detected as C++

### ISSUE THREAD

**Issue by franklinchou** [github/linguist#1993]
This is a commonly encountered error where Linguist incorrectly types C files as C++. 

Consider [this forked repository](https://github.com/franklinchou/c-linked-list) and [the master branch] (https://github.com/skorks/c-linked-list). 

Strangely, even though both are written in C and (if memory serves linguist uses a statistical method to analyze language differentiation to "guess" the best fit) only about 30% of the code itself was changed, the forked repository reports that 9.8% of the repo is written in C++. Based on a quick analysis of the files, it appears as though Linguist believes the header file (.h) is a C++ file. 

Also the dynamic links that direct, for example, C to all the files that are written in C, does not correctly update. Clicking on C points to nothing. 

* As an interesting side note, Linguist recognizes a Makefile in the fork but not in the master. 

* Update: I made a new commit using `d2u` to force line-endings to UNIX format. Problem persists.

**Comment by arfon** [comment]
Hi @franklinchou - thanks for reporting this. We've been tracking this (long-running) issue over here: https://github.com/github/linguist/issues/1626
