### ISSUE TITLE
Polymer component repo labeled incorrectly

### ISSUE THREAD

**Issue by scottnath** [github/linguist#1994]
This repository:
https://github.com/scottnath/polymer-picasa-album
is being language-labeled as 'CSS' when only one file is css and certainly not the point of that repository. It should probably be HTML instead. Is there something I can do differently to make these Polymer repositories labeled as HTML?

thanks,
Scott

**Comment by arfon** [comment]
Hi Scott, I'm afraid HTML is considered [markup](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L1167) by Linguist and so isn't included in the repository statistics.
