### ISSUE TITLE
C# project incorrectly labelled as SmallTalk

### ISSUE THREAD

**Issue by brtubb** [github/linguist#1997]
Looks like our repo is labelled as SmallTalk while it is C#!
https://github.com/Parature -> see the ParatureSDK libary
![image](https://cloud.githubusercontent.com/assets/10502971/5763909/46423878-9cbc-11e4-9bf5-52d1451f32dc.png)

Any help appreciated!

**Comment by arfon** [comment]
Duplicate of https://github.com/github/linguist/issues/1907
