### ISSUE TITLE
Invalid Smalltalk detection

### ISSUE THREAD

**Issue by MarioZ** [github/linguist#2010]
See the following repo:
https://github.com/MarioZ/MadMilkman.Ini
Linguist detects Smalltalk in C# [.cs] file (actually it also detects Objective-C in a header [.h] files).

**Comment by arfon** [comment]
Hi @MarioZ - thanks for reporting this. The C# / Smalltalk issue should be addressed as soon as this change is live (https://github.com/github/linguist/pull/2003). 

The Objective-C / C issue is also being tracked here: https://github.com/github/linguist/issues/1626 but it a much harder ongoing challenge!
