### ISSUE TITLE
c is marked as obj-c

### ISSUE THREAD

**Issue by y5a9f2y** [github/linguist#2013]
one file of my repo has been incorrectly marked as obj-c , but the primary language is c.

https://github.com/y5a9f2y/zeus

**Comment by arfon** [comment]
Hi @y5a9f2y, thanks for reporting this. We're already tracking this issue here: https://github.com/github/linguist/issues/1626

**Comment by y5a9f2y** [comment]
Hi Arfon,

I have checked the issue , and I checked the keywords , but I can not find
a solution.

Can you give me some advise on how to correct this?

y5a9f2y

2015-01-20 22:21 GMT+08:00 Arfon Smith <notifications@github.com>:

**Comment by y5a9f2y** [comment]
Hi Arfon,

I find the solution , maybe the comment causes the incorrectly recognition.

You can check the repo for this part.

Thank U all the same

y5a9f2y


2015-01-21 14:33 GMT+08:00 赵耀东 <ydzhao1992@gmail.com>:
