### ISSUE TITLE
Vim help format

### ISSUE THREAD

**Issue by maxnordlund** [github/linguist#2016]
There are a lot of vim plugins on Github, but reading there documentation isn't as nice as it could be. This is mostly because there is no syntax highlighting for vim help. I don't know if there is one in textmate format, but it isn't that complicated if you ignore link generation.

Does anyone know if there is a syntax highlighter for vim help? If not, what about the syntax for vim help?

**Comment by pchaigno** [comment]
@maxnordlund Do you have an example of Vim help file? I'll try to see if anything can be done to improve that.

**Comment by maxnordlund** [comment]
No problem, here are a few big ones:

* [VimProc](https://github.com/Shougo/vimproc.vim/blob/master/doc/vimproc.txt)
* [Unite](https://github.com/Shougo/unite.vim/blob/master/doc/unite.txt)
* [Vundle](https://github.com/gmarik/Vundle.vim/blob/master/doc/vundle.txt)

**Comment by pchaigno** [comment]
I can't find a TextMate bundle or Sublime Text package for Vim help files... Is there an other name for it?

**Comment by arfon** [comment]
:flags: flagging as stale.

**Comment by arfon** [comment]
Please feel free to open another issue if this is still something you're interested in working on.
