### ISSUE TITLE
Wrong lisp is selected in lightshow tester

### ISSUE THREAD

**Issue by nikolas** [github/linguist#2018]
In https://lightshow.githubapp.com, when I select "Emacs Lisp (source.lisp)" and submit the form, it always switches to "NetLogo (source.lisp)".

**Comment by arfon** [comment]
I can confirm this behaviour although I think this is because they both use the same grammar. See the NetLogo entry: https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L1878

So while this is a bug in the UI I'm pretty sure it's testing against the correct grammar.

**Comment by aroben** [comment]
Yeah this is just a bug in the presentation of that form. As @arfon says the right grammar is being used. Thanks for letting me know; I'll try to get a fix in place.

**Comment by aroben** [comment]
I'm tracking this elsewhere. I'll leave a note here when the bug is fixed. Thanks!
