### ISSUE TITLE
Update PHP grammar

### ISSUE THREAD

**Issue by MorrisJobke** [github/linguist#2019]
I reported the issue upstream and was advised by the GitHub support to open an issue here once it is fixed upstream, which is the case now:

https://github.com/textmate/php.tmbundle/issues/56

**Comment by arfon** [comment]
OK thanks for the update @MorrisJobke. We update the grammars each time we cut a new gem. We last did this just a [couple of days ago](https://github.com/github/linguist/releases/tag/v4.2.7) and so this update won't likely be live on GitHub for another couple of weeks.
