### ISSUE TITLE
Volatile not being considered a Java keyword

### ISSUE THREAD

**Issue by MazenMC** [github/linguist#2020]
As seen [here](https://github.com/TridentSDK/Trident/blob/bleeding-edge/src/main/java/net/tridentsdk/server/entity/TridentEntity.java#L89-L121), the "volatile" keyword is not being considered a java keyword.

**Comment by arfon** [comment]
Hi @MazenMC - this is an issue with the grammar we're using to highlight the files. Please file this bug report upstream here: https://github.com/textmate/java.tmbundle
