### ISSUE TITLE
indicate that a file is a generated file

### ISSUE THREAD

**Issue by davidchambers** [github/linguist#2021]
Is there a way to indicate that a file is a generated file? Ramda has about 200 separate JavaScript source files which are combined into a single JavaScript file with each commit. This works well but adds a lot of noise to diffs: see ramda/ramda#741, for example. We *could* add `// Generated by CoffeeScript 1.8.0` to the header, but that's misleading and likely to cause confusion.

**Comment by arfon** [comment]
Hi @davidchambers - right now this is how files are marked as generated: https://github.com/github/linguist/blob/master/lib/linguist/generated.rb#L53-L68

If this is a common issue then we could add a check for files like this and look inside the file [like this](https://github.com/github/linguist/blob/master/lib/linguist/generated.rb#L213).

There's currently no way to set at a per-repository level though that a file is generated sorry.

**Comment by davidchambers** [comment]
It would be nice to provide a way for developers to indicate to Linguist that a file is generated, regardless of file extension. Perhaps we could look for `Generated by .* DO NOT EDIT!` in the first line of the file? Then __dist/ramda.js__ could begin:

```javascript
// Generated by Ramda's build tool. DO NOT EDIT!
```
