### ISSUE TITLE
Main source-code in a Mathematica project is recognized as MATLAB

### ISSUE THREAD

**Issue by halirutan** [github/linguist#2022]
When you look at the language statistics in this repo on GitHub

- [halirutan/HeyexImport](https://github.com/halirutan/HeyexImport)

you find that two of the three Mathematica `*.m` files are correctly identified. The largest of the three files,  [HeyexImport.m](https://github.com/halirutan/HeyexImport/blob/200c0480dce53de9f6c3dafa33b58b7018363402/HeyexImport/HeyexImport.m) which contains the complete implementation is recognized as MATLAB code.

I have already pushed a new commit to GitHub since I heard that it restarts the recognition-algorithm, but no luck. Any help?

**Comment by arfon** [comment]
Hi @halirutan - I'm sorry for the bad results from Linguist here. We're actually already tracking this issue over here: https://github.com/github/linguist/pull/1652
