### ISSUE TITLE
Language#colorize method doesn't seem to work

### ISSUE THREAD

**Issue by dcecile** [github/linguist#2023]
I'm trying to set up a Linguist development environment to test a Scheme syntax highlighting change, but I can't find any documentation for this task. My first attempt was to use the `Language` class to generate some HTML. 

I think that the [`Language#colorize`](http://www.rubydoc.info/gems/github-linguist/4.2.7/Linguist/Language#colorize-instance_method) method previously used a Pygments lexer, but now that Pygments is gone, what is the method supposed to do?

Also, there's only one language left in `languages.yaml` which has a lexer: [the RAML language](https://github.com/github/linguist/blob/b319731a2d2b1e3341a17e3f805468bf0c7c9e21/lib/linguist/languages.yml#L2429). Is this intended?

**Comment by pchaigno** [comment]
You're correct. Linguist was previously using Pygments, now it is using different grammars (TextMate or Atom bundles or Sublime Text packages). You can see [the list of grammars in `grammars.yml`](https://github.com/github/linguist/blob/master/grammars.yml#L390) and most of them are in [the `vendor/grammars/` directory](https://github.com/github/linguist/tree/master/vendor/grammars).

If you only want to test some syntax highlighting changes, maybe [the Lightshow app](https://lightshow.githubapp.com/) will be sufficient?

(The last mentions of `lexer`, which was indicating the lexer to use in Pygments, will be remove with #1986.)

**Comment by dcecile** [comment]
Okay, #1986 would have prevented a bit of my confusion. So would it be fair to say that Linguist no longer does syntax highlighting? Does the ["Syntax Highlighting" section](https://github.com/pchaigno/linguist#syntax-highlighting) of `README.md` need to be changed to just "YAJL Parsing"?

The Lightshow app might be what I need, but when I try to paste in the original XML source of [my syntax file](https://github.com/textmate/scheme.tmbundle/blob/master/Syntaxes/Scheme.plist), the web request fails with this `414 (Request-URI Too Long)`. I [found how](http://stackoverflow.com/a/18835385/207321) to get a link to the raw master of a Gist, so I think I can work with that for now.

**Comment by pchaigno** [comment]
> Okay, #1986 would have prevented a bit of my confusion. So would it be fair to say that Linguist no longer does syntax highlighting? Does the "Syntax Highlighting" section of README.md need to be changed to just "YAJL Parsing"?

Linguist has never been doing syntax highlighting by itself, it was always using a third party highlighter (Pygments before, TextMate grammars now). Maybe the README should state this explicitly.

> The Lightshow app might be what I need, but when I try to paste in the original XML source of my syntax file, the web request fails with this 414 (Request-URI Too Long). I found how to get a link to the raw master of a Gist, so I think I can work with that for now.

Great! :zap: Don't hesitate to open an issue if you have any issue with Lightshow.

**Comment by dcecile** [comment]
> TextMate grammars now

The TextMate grammars only

**Comment by pchaigno** [comment]
> The TextMate grammars only act as a schema for YAJL parsing, right? Is the actual generation of HTML included in a different GitHub project?

I guess but I don't think this part is open-sourced yet. @bkeepers probably knows more about that.
<br/>

> Is this the right place for Lightshow issues? Is the code public so that I can use it with a local copy of Linguist? Also, does the URL-too-long error need a bug report?

I don't know if the code for Lightshow is public. Issues with it are usually reported here. Also, I'm not sure the situation with too long URLs can be improved. @aroben will know for sure.

**Comment by aroben** [comment]
> I guess but I don't think this part is open-sourced yet.

That's right. We're still looking into that.

> I don't know if the code for Lightshow is public.

It isn't public, because it includes the syntax highlighter which is also not public.

> Also, I'm not sure the situation with too long URLs can be improved.

We should change the `<form>` from a GET to a POST when the input gets large. I think that would fix this problem.

**Comment by pchaigno** [comment]
> We should change the <form> from a GET to a POST when the input gets large. I think that would fix this problem.

:+1: but you may have to warn the user that the url can't be used anymore to make a direct link when it changes from a GET to a POST form.

**Comment by AnthonyDGreen** [comment]
@aroben 

Without having the code for the syntax highlighter is it possible to change the theme used on either a per language or per repository basis? (e.g. VS colors on Roslyn repository/C#/VB)

**-ADG**

**Comment by aroben** [comment]
@AnthonyDGreen You might be able to do something with a browser extension that lets you apply a custom user stylesheet based on the current URL. We don't have any per-repo theming support built into github.com itself.

**Comment by dcecile** [comment]
:smiley_cat: I think it's fair to say that there are a bunch of different threads rolled into this issue. I'll try to list them off:

##### (1) Language#colorize method doesn't seem to work

It doesn't work, and it will be removed with #1986.

##### (2) The Linguist README says some stuff about syntax highlighting

This is confusing because Linguist now only has syntax definition files and (I think?) a parser. The highlighting part isn't open source right now. I can create a separate issue for this.

##### (3) The Linguist README doesn't say how to test syntax definition files

Testing out how changes to syntax definition files affect GitHub requires using [Lightshow](https://lightshow.githubapp.com/). I don't think it's worth updating the README to talk about running parsers (because the output data would be too detailed), but I think something in the README about Lightshow would be helpful. Again I can create a separate issue (maybe the same issue as above).

##### (4) Lightshow doesn't work with normal-size inline syntax definitions

Because Lightshow creates a shareable URL out of its form parameters, pasting in the text of a standard syntax definition file causes a `414 (Request-URI Too Long)` error. @aroben and @pchaigno  to take care of this?

##### (5) github.com doesn't have per-repo theming for syntax highlighting colours

Linguist doesn't do syntax highlighting any more, and per-repo theming would be a GitHub feature request I guess. What's the best way for @AnthonyDGreen to follow up for this?

**Comment by dcecile** [comment]
Oh, for **(2)** and **(3)**, the README has already been updated (I can't find the diff), and [CONTRIBUTING](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#fixing-syntax-highlighting) already talks about Lightshow.

The only change I'd suggest is here in the README, to also mention the relationship between Linguist and syntax parsing/highlighting:

> This library is used on GitHub.com to detect blob languages, ignore binary or vendored files, suppress generated files in diffs, and generate language breakdown graphs.

**Comment by aroben** [comment]
> Lightshow doesn't work with normal-size inline syntax definitions

I have an issue tracking this internally. I'll try to get it fixed soon.

> What's the best way for @AnthonyDGreen to follow up for this?

Emailing support@github.com is the best way to request a feature.

**Comment by bkeepers** [comment]
Closing this as I think we're all sorted out here, but let me know if I'm wrong.
