### ISSUE TITLE
Objective-C highlighting broken for multiline string

### ISSUE THREAD

**Issue by meatcoder** [github/linguist#2028]
The following snippet is highlighted such that the `%` in the second segment of the NSString constant is shown as a syntax error. Note that this is valid Objective-C code.

```Objective-C
id a = @"hello there"
          "bye %@";
```

Adding a `@`  to the second segment produces the correct highlighting:

```Objective-C
id a = @"hello there"
          @"bye %@";
```

This `%` in both snippets should be highlighted in the same way.

**Comment by arfon** [comment]
Hi @meatcoder - thanks for reporting this. Unfortunately this isn't something we can fix in Linguist, it's an issue with the grammar we're using: https://github.com/textmate/objective-c.tmbundle

Would you mind reporting this bug here? Once it gets fixed we can merge in the upstream fixes.

**Comment by pchaigno** [comment]
@meatcoder This issue was solved in textmate/objective-c.tmbundle#7. The fix will be live within a couple of weeks.
