### ISSUE TITLE
Wrong language in Git Hub repo

### ISSUE THREAD

**Issue by johnt447** [github/linguist#2029]
Hi

The repo named PyVAFM at https://github.com/SINGROUP is incorrectly labelled mathematica when it should be Python. How do I fix this?

**Comment by arfon** [comment]
Hi @johnt447 - it looks like you've got a large Mathematica file here: https://github.com/SINGROUP/PyVAFM/blob/21c7ec38bb1fcdc0791c54fb71c59ebd098b2b06/examples/filtercheck.nb

You can manually force Linguist to ignore these using our custom overrides: https://github.com/github/linguist#overrides
