### ISSUE TITLE
Wrong language

### ISSUE THREAD

**Issue by Josenzo** [github/linguist#2032]
Hello, this project is market with wrong language:
https://github.com/Josenzo/spserver

Is in PHP, i know it has too many .as files, it because the client for test is writen in ActionScript.

Thank you.

**Comment by arfon** [comment]
Hi @Josenzo - you can exclude files from the language statistics using the overrides described here: https://github.com/github/linguist#overrides

**Comment by pchaigno** [comment]
Hello @Josenzo - You can tell Linguist to ignore your `.as` files with [README#Overrides](https://github.com/github/linguist#overrides).
