### ISSUE TITLE
matlab files listed as objective-c

### ISSUE THREAD

**Issue by akshaybabloo** [github/linguist#2033]
Hi,

Matlab files (.m) are being showed as objective-c files.

please see the attached screen shot.

thank you.

![screen shot 2015-01-24 at 5 51 34 pm](https://cloud.githubusercontent.com/assets/7360286/5889082/79c9bc5e-a47b-11e4-97ec-e348ca09c210.png)

**Comment by arfon** [comment]
Hi @akshaybabloo - thanks for reporting this. We're tracking this issue [here](https://github.com/github/linguist/pull/1652) and should have this fixed up soon.
