### ISSUE TITLE
Licensed grammar for Rebol 

### ISSUE THREAD

**Issue by pchaigno** [github/linguist#2036]
[The current grammar](https://github.com/Oldes/Sublime-REBOL) for Rebol doesn't have a license and [it doesn't seem to be maintained anymore.](https://github.com/Oldes/Sublime-REBOL/issues/2)
Should we use [@rgchris'](https://github.com/rgchris/rebol-tmbundle) instead?

The syntax highlighting seems less complete ([currently](https://github.com/github/linguist/blob/master/samples/Rebol/booters.r) and [after](https://lightshow.githubapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Frgchris%2Frebol-tmbundle%2Fmaster%2FSyntaxes%2FRebol.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fgithub%2Flinguist%2Fmaster%2Fsamples%2FRebol%2Fbooters.r&code=)) but at least we'll be able to remove it from [the list of exceptions](https://github.com/github/linguist/blob/master/test/test_grammars.rb#L10)...

/cc @aroben @bkeepers @arfon

**Comment by arfon** [comment]
This seems like a good idea. @aroben?

**Comment by aroben** [comment]
> The syntax highlighting seems less complete

I think the problem is that the grammar is using nonstandard scope names like `native.rebol.parse`. http://manual.macromates.com/en/language_grammars#naming_conventions describes the normal conventions. If the scope names were fixed then the highlighting would probably improve quite a bit. Want to take a stab at that?

**Comment by pchaigno** [comment]
@aroben Okay, I've read the documentation on conventions. I'm not familiar with Rebol but I'll try to fix the grammar and ask for help if there is a construction I don't understand.

**Comment by arfon** [comment]
Is this still active @pchaigno?

**Comment by pchaigno** [comment]
Yes, I just can't find the time to do it :/
I'll open an issue on the grammar's repository to see if someone can fix it. If I find someone, I'll close this issue.

**Comment by arfon** [comment]
I think I'm correct in saying that this can be closed now.
