### ISSUE TITLE
https://github.com/studerw/activiti-example - Wrong language. Should be Java, not JS.

### ISSUE THREAD

**Issue by studerw** [github/linguist#2038]
This is a java web app. Obviously it contains numerous front-end JS libraries. However, the project should not be tagged as 'javascript'.

**Comment by arfon** [comment]
Hi @studerw - you can manually exclude [these files](https://github.com/studerw/activiti-example/search?l=javascript) using the [overrides](https://github.com/github/linguist#overrides).
