### ISSUE TITLE
Literate CoffeeScript not highlighting properly in Github, working in Atom

### ISSUE THREAD

**Issue by jasonm23** [github/linguist#2040]
![screen shot 2015-01-24 at 1 03 35 pm](https://cloud.githubusercontent.com/assets/71587/5906514/2efd7af4-a5d3-11e4-8f34-958d0aa983cb.png)
![screen shot 2015-01-24 at 1 02 26 pm](https://cloud.githubusercontent.com/assets/71587/5906515/2f4024b2-a5d3-11e4-97b0-cfde2c3d00e7.png)

e.g. https://github.com/jasonm23/Phoenix-config/blob/master/.phoenix.litcoffee

**Comment by pchaigno** [comment]
That's actually an issue with [github/markup](https://github/markup).
[`.litcoffee` files are rendered as simple Markdown.](https://github.com/github/markup/blob/4c23636e2b475ba58397189d06aa0e9a1265c980/lib/github/markup/markdown.rb#L28)

/cc @bkeepers

**Comment by bkeepers** [comment]
Looks to be a bug with with the filename starting with a `.`:

`test.litcoffee` [works](https://github.com/bkeepers/test/blob/a07be81c9c7f9c8fa9fd0a503037f7f8559143e7/test.litcoffee).
`.test.litcoffee` [does not](https://github.com/bkeepers/test/blob/125f2ad390a67027cd13c3ef5146b62fadb0940f/.test.litcoffee).

Linguist seems to properly detect this, so might be a bug in GitHub. I'll report it to our team and see what I find out.

**Comment by jasonm23** [comment]
Nice catch, thanks

**Comment by jasonm23** [comment]
Adding this link for my own testing reference.

https://github.com/jasonm23/Phoenix-config/blob/77f0455fc11ab87bd067a8148a34836e50204374/.phoenix.litcoffee

**Comment by pchaigno** [comment]
Closing as this is not something that can be fixed in Linguist.
