### ISSUE TITLE
Errors when searching for the correct heuristic rule to use

### ISSUE THREAD

**Issue by pchaigno** [github/linguist#2042]
I found an issue with the heuristics and the way it looks for the right heuristic to use.
In the [Heuristic strategy](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.rb#L54-L57), these lines checks if a certain heuristic matches the candidate languages:
```ruby
# Internal: Check if this heuristic matches the candidate languages.
def matches?(candidates)
  candidates.any? && candidates.all? { |l| @languages.include?(l.name) }
end
```
It basically says that all candidate languages must be in the list of language this heuristic is trying to distinguish.

0. So if one of the candidate languages is not in the list, the heuristic will not be used.
0. It also means that, if the heuristic was written to distinguish more languages than we have candidates, it will still be used.

At the time we write the heuristic we generally make sure that the first case doesn't happen. For example when we wrote the heuristic for AsciiDoc and AGS Script (`.asc files`) they were the only two languages using the `.asc` extension. But since, Public Key has been added with the `.asc` extension. Thus the heuristic for AsciiDoc and AGS Script is not used anymore when trying to distinguish `.asc` files. This is why the issue #1638 is still opened.
We also wrote a heuristic rule for Prolog and IDL on `.pro` files. But now this file extension is also defined for [QMake](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L2417), explaining why [so many `.pro` files are still not correctly detected](https://github.com/search?l=idl&q=extension%3Apro+is&ref=searchresults&type=Code&utf8=%E2%9C%93).

The second point explains the issue with [these Perl files](https://github.com/rakudo/rakudo/search?l=prolog) (reported by @hoelzro in #1680). The `.pm` extension causes a conflict between Perl 5 and 6. Then Linguist uses the heuristic for Perl, Perl6 and Prolog because it includes all the candidate languages it's trying to distinguish. Unfortunately, ([because our heuristic doesn't check for comments](https://github.com/rakudo/rakudo/blob/421176c14605dcca7d339aec2d61aaee329b9f6d/src/core/io_operators.pm#L162)) Prolog is chosen as the correct language. Even if it wasn't a candidate for `.pm` files...

I'm not really sure on how this should be fixed. I also don't think I have enough experience with Ruby to write a test that detects these cases happening (I tried quickly but hit some specificities to Ruby's OOP).

/cc @bkeepers @arfon

**Comment by arfon** [comment]
> 1. So if one of the candidate languages is not in the list, the heuristic will not be used.
> 2. It also means that, if the heuristic was written to distinguish more languages than we have candidates, it will still be used.

Yeah I've been vaguely aware that this was the case for a while. I agree this is an issue.

```ruby
# Internal: Check if this heuristic matches the candidate languages.
def matches?(candidates)
  candidates.any? && candidates.all? { |l| @languages.include?(l.name) }
end
```

Regarding this :point_up: - I wonder if we should just relax the conditional so that the heuristic is invoked if two or more languages are matched. i.e. for [this one](https://github.com/github/linguist/blob/168ff4c050e29361ec9f9b40536f953347d6f4d4/lib/linguist/heuristics.rb#L80) we'd use the heuristic if `C` and `C++` were `candidates`.

> I'm not really sure on how this should be fixed. I also don't think I have enough experience with Ruby to write a test that detects these cases happening (I tried quickly but hit some specificities to Ruby's OOP).

I think I might have an idea how we can do this.

**Comment by pchaigno** [comment]
> Regarding this :point_up: - I wonder if we should just relax the conditional so that the heuristic is invoked if two or more languages are matched. i.e. for this one we'd use the heuristic if C and C++ were candidates.

Did you mean if C, C++, Objective-C **and** an other language were candidates?
I tried this and wrote [a new code to select the best heuristic matching 2 or more languages](https://github.com/pchaigno/linguist/blob/match-heuristics/lib/linguist/heuristics.rb). But the issue `2.` remains...

**Comment by arfon** [comment]
> Did you mean if C, C++, Objective-C **and** an other language were candidates?

I didn't (but my statement could mean that too). Let me explain:  I'm thinking that in all the following scenarios we'd invoke [this heuristic](https://github.com/github/linguist/blob/168ff4c050e29361ec9f9b40536f953347d6f4d4/lib/linguist/heuristics.rb#L80-L87)

```ruby
disambiguate "Objective-C", "C++", "C" do |data|
  if (/^[ \t]*@(interface|class|protocol|property|end|synchronised|selector|implementation)\b/.match(data))
    Language["Objective-C"]
  elsif (/^\s*#\s*include <(cstdint|string|vector|map|list|array|bitset|queue|stack|forward_list|unordered_map|unordered_set|(i|o|io)stream)>/.match(data) ||
    /^\s*template\s*</.match(data) || /^[ \t]*try/.match(data) || /^[ \t]*catch\s*\(/.match(data) || /^[ \t]*(class|(using[ \t]+)?namespace)\s+\w+/.match(data) || /^[ \t]*(private|public|protected):$/.match(data) || /std::\w+/.match(data))
    Language["C++"]
  end
end
```

```
1. candidates = [C, Objective-C, C++]
# Exact match, call the heuristic

2. candidates = [C, Objective-C]
# Partial match (more than 1 language matching), call the heuristic

3. candidates = [C, Perl] (not sure how this would happen - perhaps we accidentally include a `.h` sample for Perl)
# Only 1 matching language, don't call the heuristic WARN IN TESTS

4. candidates = [C, Objective-C, C++, Perl]
# Partial match (more than 1 language matching), call the heuristic WARN IN TESTS

```
Basically I think we should use the heuristics where they may be able to provide information. Also, for scenarios 3 & 4 I think we should detect these in our test suite. I started working on this (pushed it early for feedback in this conversation) [here](https://github.com/github/linguist/commit/b227816e917ae7c3156925a109183b5939c381b0).

Finally, if we go in this direction we have to make sure we are extra careful of writing heuristics in the pattern `if ... else ... end` as the final `else` would presumably be more prone to returning bad results if we were using the heuristic with varying candidate languages.

**Comment by pchaigno** [comment]
Okay, I think case `2.` would be a good thing.

For case `3.` I don't think we can throw a warning because, if we do, there will be warnings all the time...

Case `4.` means we could end up adding new candidates with the Heuristic strategy. Currently they only return a definitive answer or nothing. But if we latter make a heuristic rule capable of simply eliminating a candidate without a definitive answer then it could also possibly end up adding new candidates out of nowhere :/
Case `4.` is already [causing issues](https://github.com/rakudo/rakudo/search?l=prolog) as @hoelzro reported in [#1680 (comment)](https://github.com/github/linguist/issues/1680#issuecomment-69956905). Perl files are recognized as Prolog when they are not even using a Prolog extension.

**Comment by larsbrinkhoff** [comment]
Isn't it actually the case that we're looking at one particular file (with one particular file extension) and want the heruristics to return the most likely language for that file?  Wouldn't it then make more sense to select an heuristic based on the file extension, not the list of possible languages?

**Comment by pchaigno** [comment]
> Isn't it actually the case that we're looking at one particular file (with one particular file extension) and want the heruristics to return the most likely language for that file? Wouldn't it then make more sense to select a heuristic based on the file extension, not the list of possible languages? It seems to me that this would remove most of the problems mentioned in this issue.

:+1:

**Comment by pchaigno** [comment]
Closing in favor of #2441.
