### ISSUE TITLE
There is better PowerShell language bundle

### ISSUE THREAD

**Issue by vors** [github/linguist#2043]
Current [grammar](https://github.com/davidpeckham/powershell.tmbundle) for PowerShell language has few problems:
1) It's case sensitive sometimes (PS is case-insensitive).
2) It's outdated (i.e. [identify class keyword as an error](https://github.com/flavops/Lexec.Type#example-with-attributes-metaclassattribute). Classes are new in PS v5). It was written for PS v1.
3) It lacks a lot of scopes.
4) Project doesn't look alive (0 issues, last activity 10 months ago), so there is little chance for improvements in the near future.

There is [SublimeText bundle](https://github.com/SublimeText/PowerShell ) with better syntax highlighting.
**Compare** [current](https://github.com/pester/Pester/blob/master/Functions/Context.ps1) highlighting to [ST bundle](http://goo.gl/i7u4kg).
Also [samples](https://github.com/github/linguist/tree/master/samples/PowerShell) for PowerShell are pretty small. It affects auto-recognition algorithm. 

If everybody fine with switching vendor, I can prepare PR with bundle replacement and bigger samples.

**Comment by arfon** [comment]
Can this be closed now @vors (given that https://github.com/github/linguist/pull/2047 is merged)?

**Comment by vors** [comment]
Yes, thank you!
When new grammar will be used on github?

**Comment by arfon** [comment]
> When new grammar will be used on github?

Probably another couple of days. I'm planning/hoping to cut a new gem tomorrow.

**Comment by vors** [comment]
Cool, thank you!
