### ISSUE TITLE
PowerShell Grammar in Sublime/PowerShell

### ISSUE THREAD

**Issue by Jaykul** [github/linguist#2049]
The [tmLanguage grammar in the Sublime/PowerShell](https://github.com/SublimeText/PowerShell/blob/master/Support/PowershellSyntax.tmLanguage) repository has been worked on and improved by several people over the last few years, it's noticeably better (and more up to date) than the one in use on github now.

https://lightshow.githubapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2FSublimeText%2FPowerShell%2Fraw%2Fmaster%2FSupport%2FPowershellSyntax.tmLanguage&grammar_text=&code_source=from-url&code_url=http%3A%2F%2Fposhcode.org%2Fget%2F5702&code=

**Comment by vors** [comment]
It's already done :) #2043

**Comment by Jaykul** [comment]
Well, yay
