### ISSUE TITLE
Incorrect Language for Repository "FileUploadDownload"

### ISSUE THREAD

**Issue by rahulbahal7** [github/linguist#2050]
The repository is marked as CSS but it should be JAVA

![image](https://cloud.githubusercontent.com/assets/8658590/5953204/a86c1612-a753-11e4-8178-6bb270a4ef3f.png)

**Comment by pchaigno** [comment]
Hi @rahulbahal7 - Your repository is detected as CSS because of [these files](https://github.com/rahulbahal7/FileUploadDownload/search?l=css). See [README#Overrides](https://github.com/github/linguist#overrides) to ignore them.

**Comment by rahulbahal7** [comment]
Hi

Can you please tell me the process so that I can manually change the language to JAVA instead?

----- Original Message -----

**Comment by pchaigno** [comment]
You could for instance choose to ignore all CSS files. In order to do so, you have to add in `.gitattributes` the line `*.css linguist-language=Java`.
