### ISSUE TITLE
Repository language issues

### ISSUE THREAD

**Issue by Distjubo** [github/linguist#2052]
I have a repository on github ( https://github.com/Distjubo/MinecraftLauncher/ ), it contains a lot of .java files, and only 2 .css files. I would appreciate it if you could somehow detect the quantity of a certain file type :)

**Comment by arfon** [comment]
Hi @Distjubo - the language statistics are by overall volume of contents in each language and the CSS file is ~130kb.

You can manually ignore CSS files using our overrides as described here: https://github.com/github/linguist#overrides
