### ISSUE TITLE
Tell apart text and binary *.mo files

### ISSUE THREAD

**Issue by thorade** [github/linguist#2053]
`*.mo` files can be [Modelica](http://en.wikipedia.org/wiki/Modelica) source code or binary [GNU gettext](http://en.wikipedia.org/wiki/GNU_Gettext) files.
Some time ago I did a Pull Request to add Modelica detection (see #107) 
but that broke things for people using GNU gettext (see #119).

Is there by now a way to tell apart binary and text `*.mo` files?
The [`CONTRIBUTE.md`](https://github.com/github/linguist/blob/master/CONTRIBUTING.md) and [`README.md`](https://github.com/github/linguist/blob/master/README.md) seem to be only covering the case that two *languages* share an extension, but what should be done if the same extension is used by binary and text files?

I tried to override detection using the `.gitattributes`:
https://github.com/thorade/HelmholtzMedia/blob/master/.gitattributes
but I guess that only works if the language is already in the [linguist language list](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml) !?

Once the language is detected correctly, 
syntax highlight could be done using one of these two packages:
https://github.com/BorisChumichev/modelicaSublimeTextPackage
https://github.com/raphaelchenouard/atom-language-modelica

**Comment by pchaigno** [comment]
> I tried to override detection using the .gitattributes:
https://github.com/thorade/HelmholtzMedia/blob/master/.gitattributes
but I guess that only works if the language is already in the linguist language list !?

Yep, you can only override with languages defined in Linguist.

There was a big update on the binary detection in the meantime I believe. I can try to add support for Modelica and see if it works better than before.

I also tested the two grammars in Lightshow:
[Does this look right? (Sublime Text package highlighting)](https://lightshow.githubapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2FBorisChumichev%2FmodelicaSublimeTextPackage%2Fmaster%2FModelica.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fgithub%2Flinguist%2Fce5402dd55c274ac22743f293b35aefd543997da%2Ftest%2Ffixtures%2Fmodelica.mo&code=)
[The last dev version of the Atom grammar doesn't seem to be working](https://lightshow.githubapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fraphaelchenouard%2Fatom-language-modelica%2Fmaster%2Fgrammars%2Fmodelica.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fgithub%2Flinguist%2Fce5402dd55c274ac22743f293b35aefd543997da%2Ftest%2Ffixtures%2Fmodelica.mo&code=within+Modelica.Electrical.Analog%3B%0D%0Apackage+Sensors+%22Potential%2C+voltage%2C+current%2C+and+power+sensors%22%0D%0A%0D%0A++extends+Modelica.Icons.SensorsPackage%3B%0D%0A%0D%0A++model+PotentialSensor+%22Sensor+to+measure+the+potential%22%0D%0A++++extends+Modelica.Icons.RotationalSensor%3B%0D%0A%0D%0A++++Interfaces.PositivePin+p+%22pin+to+be+measured%22+annotation+%28Placement%28%0D%0A++++++++++transformation%28extent%3D{{-110%2C-10}%2C{-90%2C10}}%2C+rotation%3D0%29%29%29%3B%0D%0A++++Modelica.Blocks.Interfaces.RealOutput+phi%0D%0A++++++%22Absolute+voltage+potential+as+output+signal%22%0D%0A++++++++annotation+%28Placement%28transformation%28extent%3D{{100%2C-10}%2C{120%2C10}}%2C%0D%0A++++++++++++rotation%3D0%29%29%29%3B).

**Comment by thorade** [comment]
If you could try to add Modelica support that would be great. Please tell me how I can help. 
When I tested both packages few days ago, both were working. Strange.
As the Sublime package works better, that should be used as starting point of course.

Here is another Modelica source code example file:
https://github.com/modelica/Modelica/blob/release/Modelica%203.2.1/Mechanics/Translational.mo

Testing that file with Lightshow:
[Lightshow with Sublime Package](https://lightshow.githubapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2FBorisChumichev%2FmodelicaSublimeTextPackage%2Fblob%2Fmaster%2FModelica.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fmodelica%2FModelica%2Fblob%2Frelease%2FModelica%25203.2.1%2FMechanics%2FTranslational.mo&code=)
[Lightshow with Atom Package](https://lightshow.githubapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fraphaelchenouard%2Fatom-language-modelica%2Fblob%2Fmaster%2Fgrammars%2Fmodelica.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fmodelica%2FModelica%2Fblob%2Frelease%2FModelica%25203.2.1%2FMechanics%2FTranslational.mo&code=within+Modelica.Electrical.Analog%3B%0D%0Apackage+Sensors+%22Potential%2C+voltage%2C+current%2C+and+power+sensors%22%0D%0A%0D%0A++extends+Modelica.Icons.SensorsPackage%3B%0D%0A%0D%0A++model+PotentialSensor+%22Sensor+to+measure+the+potential%22%0D%0A++++extends+Modelica.Icons.RotationalSensor%3B%0D%0A%0D%0A++++Interfaces.PositivePin+p+%22pin+to+be+measured%22+annotation+%28Placement%28%0D%0A++++++++++transformation%28extent%3D{{-110%2C-10}%2C{-90%2C10}}%2C+rotation%3D0%29%29%29%3B%0D%0A++++Modelica.Blocks.Interfaces.RealOutput+phi%0D%0A++++++%22Absolute+voltage+potential+as+output+signal%22%0D%0A++++++++annotation+%28Placement%28transformation%28extent%3D{{100%2C-10}%2C{120%2C10}}%2C%0D%0A++++++++++++rotation%3D0%29%29%29%3B)

**Comment by pchaigno** [comment]
So I looked into the detection process and it appears that almost everything have changed since you made the first pull request. Linguist now drops the detection process if the file is a binary. So adding Modelica shouldn't be a problem anymore :-)

I opened a pull request at #2059

**Comment by thorade** [comment]
Awesome, thanks a lot. Excited to see what will happen.

**Comment by arfon** [comment]
This should be fixed now in https://github.com/github/linguist/pull/2059. These changes will go live in the next week or so when we cut a new gem.
