### ISSUE TITLE
New language detection

### ISSUE THREAD

**Issue by benzen** [github/linguist#2054]
Here is a file that language is not detected
https://github.com/muut/riotjs/blob/master/demo/todo.tag

According to the guys who work on this, the syntaxe coloration could be copied from JSX

**Comment by arfon** [comment]
Hi @benzen - this looks like it is some kind of view template associated with a JavaScript library. You can see the file extensions that we support for JavaScript here: https://github.com/github/linguist/blob/1a3960e95dc86f271d983bcc624d1a127fb86d0c/lib/linguist/languages.yml#L1449-L1492

It's not clear that adding `.tag` to this definition though is the correct solution as most of the file contents is HTML which is considered markup in Linguist and not a 'language'.

If you would like to force the highlighting of this file you could add a Vim or Emacs-style modeline to the top of the file (e.g. `-*- JavaScript -*-``).
