### ISSUE TITLE
Common Lisp files ending in .l not being recognised

### ISSUE THREAD

**Issue by hscells** [github/linguist#2060]
Please see https://github.com/hscells/CSC466 for example.

Thank you.

**Comment by larsbrinkhoff** [comment]
This seems tricky.  There are more than 300k `.l` files.  Traditionally, this extension is used for Lex input.  These files usually contain lots of code from the target language, so the Bayesian classifier would have a hard time doing the right thing.  I guess heuristics could latch onto the `%{` and `%}` keywords used by Lex.

I found more than 5000 `.l` files which seems to be Lisp.

**Comment by pchaigno** [comment]
I agree with @larsbrinkhoff (but I'm not part of GitHub staff either). This is going to be a lot of work but it's feasible. We'll first need to identify all languages using this extension.

- [3,600 of them seem to be C#](https://github.com/search?utf8=%E2%9C%93&q=extension%3Al+namespace)
- [a good number seems to be C++/C](https://github.com/search?utf8=%E2%9C%93&q=extension%3Al+include&type=Code&ref=searchresults)

**Comment by larsbrinkhoff** [comment]
@pchaigno Many of those two searches include files which are Lex files.

E.g. the first C# result: https://github.com/jk983294/Store/blob/e1e052231917815dc3f02768a69f70a2f5cfb164/CompileExp/SeuYacc/%E7%94%A8%E4%BE%8B/example1-%E7%AE%80%E5%8D%95%E8%BF%90%E7%AE%97/lex.l

Note the precense of `%{`.

**Comment by larsbrinkhoff** [comment]
Which language or testing framework use `.l` and `.p`?  See for example this directory:
https://github.com/doespresso/leroy/tree/eecbeee944ebc09fde4c353a442de3a7ed892bf7/node_modules/grunt-csso/node_modules/csso/test/data/test_simpleselector

**Comment by pchaigno** [comment]
> @pchaigno Those two searches include many files which are Lex files.
E.g. the first C# result. Note the precense of %{.

Arf! Good to know.

**Comment by hscells** [comment]
What extension should I use if I wanted linguist to pick them up?

**Comment by larsbrinkhoff** [comment]
@hscells `.lisp`is by far the most common.  `.lsp` and `.cl` are also supported by GitHub if you need something shorter.

**Comment by hscells** [comment]
> larsbrinkhoff

Thank you :)

**Comment by larsbrinkhoff** [comment]
May the sexp be with you!
