### ISSUE TITLE
wrong language detected

### ISSUE THREAD

**Issue by alxcancado** [github/linguist#2061]
Hi!

I have an Unity3D project that should be marked as C# language but it's showing as ASP.

https://github.com/alxcancado/Eskiv

How can I fix it?

Thank's

Alex.

**Comment by pchaigno** [comment]
Hi @alxcancado - Your project is recognized as ASP because of [these two big ASP files](https://github.com/alxcancado/Eskiv/search?l=aspx-vb). You can override the detection in statistics with [Linguist#Overrides](https://github.com/github/linguist#overrides).

**Comment by arfon** [comment]
Thanks @pchaigno

**Comment by alxcancado** [comment]
Thanks @pchaigno @arfon
