### ISSUE TITLE
Wrong language 

### ISSUE THREAD

**Issue by scstauf** [github/linguist#2065]
I searched github for my project scstauf/noctis and it was listed as a C project but it's C++.  I realize they're similar, but if you look in the subdirectory /include/, you'll see that several of the header files contain class definitions. I'm not sure how linguist works, but it could also look for C++ specific keywords just in case what it thinks is C might actually be C++.

**Comment by arfon** [comment]
Hi @scstauf, thanks for reporting this. We're already tracking this issue over here: https://github.com/github/linguist/issues/1626

I'd love you input in that discussion if you have ideas.
