### ISSUE TITLE
syntax highlighting doesn't work properly (readme with AS3 code snippets)

### ISSUE THREAD

**Issue by honzabrecka** [github/linguist#2067]
Hi,

I have a [readme file](https://github.com/honzabrecka/Screenshot/blob/master/README.md) that contains some code snippets in AS3 (each snippet has `as3` language identifier) but properly highlighted is only [the last one](https://github.com/honzabrecka/Screenshot/blob/master/README.md#custom-assertion).

Can someone take a look please?

**Comment by egonSchiele** [comment]
My docs (generated with gh-pages) have ruby code that isn't getting highlighted either. Related issue?

Link: http://egonschiele.github.io/contracts.ruby/

**Comment by pchaigno** [comment]
@honzabrecka The incorrect highlighting comes from [the grammar GitHub is using to highlight ActionScript](https://github.com/simongregory/actionscript3-tmbundle). I was able to reproduce the issue in [Lightshow](https://lightshow.githubapp.com/?utf8=%E2%9C%93&scope=source.actionscript.3&grammar_url=&grammar_text=&code_source=from-text&code_url=&code=%5BTest%28async%2C+ui%29%5D%0D%0Apublic+function+defaultColor%28%29%3Avoid%0D%0A{%0D%0A%09var+component%3ASquare+%3D+new+Square%28%29%3B%0D%0A%09Async.proceedOnEvent%28this%2C+component%2C+Event.ADDED%29%3B%0D%0A++++UIImpersonator.addChild%28component%29%3B%0D%0A%09%0D%0A%09%2F%2F+this+is+the+line!%0D%0A%09assertTrue%28Screenshot.compare%28%22SquareTest.defaultColor%22%2C+component%29%29%3B%0D%0A}).

I'm not familiar with ActionScript but it looks like this grammar is expecting a complete/syntactically correct ActionScript program. See for instance [the same example as before but with a `namespace` statement](https://lightshow.githubapp.com/?utf8=%E2%9C%93&scope=source.actionscript.3&grammar_url=&grammar_text=&code_source=from-text&code_url=&code=package+test.test+{%0D%0A++++%5BTest%28async%2C+ui%29%5Dpublic+function+defaultColor%28%29%3Avoid+{%0D%0A++++++++var+component%3ASquare+%3D+new+Square%28%29%3B%0D%0A++++++++Async.proceedOnEvent%28this%2C+component%2C+Event.ADDED%29%3B%0D%0A++++++++UIImpersonator.addChild%28component%29%3B%0D%0A%0D%0A++++++++%2F%2F+this+is+the+line!%0D%0A++++++++assertTrue%28Screenshot.compare%28%22SquareTest.defaultColor%22%2C+component%29%29%3B%0D%0A++++}%0D%0A}). Of course this behavior is incompatible with snippets of code.

You should probably open an issue on the repository of the grammar to see if the author is okay with making his grammar more flexible (and compatible with an usage in Markdown documents). It's also possible to change the grammar if you know a better one (TextMate bundle or Sublime Text package)?

@egonSchiele Your issue doesn't seem related to @honzabrecka's but are you sure gh-pages are using Linguist?? Anyway, I think you should open a new issue.

**Comment by arfon** [comment]
Thanks @pchaigno. @honzabrecka - please go ahead and open an issue on the grammar repository.

**Comment by honzabrecka** [comment]
@pchaigno @Aaron1011 I've made [changes myself](https://github.com/honzabrecka/as3grammar/commit/7c11e091d0e6ef40bfe1a6b30c1b35f5e57cebbf) at https://github.com/honzabrecka/as3grammar. It makes grammar finally suitable for code snippets.

How can I propose my changes in grammar to GitHub, please?

**Comment by pchaigno** [comment]
@honzabrecka You will have to fork the grammar repository, make your changes in the fork and open a pull request on the original repository. See https://guides.github.com/activities/contributing-to-open-source/#contributing for help. You can also open an issue on the repository of the grammar if you need help.

**Comment by honzabrecka** [comment]
@pchaigno I know..., but the latest update made in repository was 4 years ago with many PRs open, so I don't hope to merge.  It's also a plugin for text editor, therefore it makes sense to be strict in grammar. Whereas grammar for code snippets shouldn't be so strict.

> It's also possible to change the grammar if you know a better one.

I was asking because of this sentence. :)

Never mind, it's no such big issue.

**Comment by pchaigno** [comment]
> I know..., but the latest update made in repository was 4 years ago with many PRs open, so I don't hope to merge

@honzabrecka I understand, however I still think you should make a fork (even if you don't open a PR after). It would make it clear for people where your grammar comes from. It would also allow people eventually to move their pull requests from the original repository to your fork. It's all win imo!
