### ISSUE TITLE
(TextMate grammar included) eC syntax highlighting lost when switching from Pygments to TextMate 

### ISSUE THREAD

**Issue by jerstlouis** [github/linguist#2068]
We've lost eC highlighting.

You can find an eC grammar for TextMate in this repository:

http://github.com/ecere/ec.tmbundle

Thank you.

Jerome

**Comment by arfon** [comment]
Thanks for reporting this @jerstlouis. We'll need the grammar to be licensed before we can consider including it in Linguist. I've opened an issue here: https://github.com/ecere/ec.tmbundle/issues/1

**Comment by pchaigno** [comment]
@arfon I'm making a second round for grammars (a lot of people responded to my issues for licenses quicker than I expected), I'll include this one.

**Comment by arfon** [comment]
:+1: awesome. Thanks @pchaigno

**Comment by pchaigno** [comment]
Never mind, there's still an issue:
[convert-grammars](https://github.com/github/linguist/blob/master/script/convert-grammars) doesn't recognize the [`.tmGrammar` extension](https://github.com/ecere/ec.tmbundle/blob/master/Syntaxes/eC.tmGrammar). I've never seen it before so I don't know if we should add it to convert-grammar or not?

/cc @aroben

**Comment by aroben** [comment]
Does `.tmGrammar` work in TextMate? If so, let's change `convert-grammars`. If not, let's change `ec.tmbundle` to use a standard extension.

**Comment by jerstlouis** [comment]
I was told by Allan Odgaard that .plist was the old extension and now they
use .tmGrammar

[10:31] <allan> also, name it eC.tmGrammar
[10:31] <allan> the plist extension is deprecated

**Comment by pchaigno** [comment]
> Does .tmGrammar work in TextMate? If so, let's change convert-grammars. If not, let's change ec.tmbundle to use a standard extension.

:+1: I don't have TextMate though

**Comment by aroben** [comment]
Weird, most bundles I've seen use `.tmLanguage`. I've never seen `.tmGrammar`, and there doesn't seem to be any code on GitHub using that extension either: https://github.com/search?utf8=✓&q=plist+extension%3AtmGrammar&ref=simplesearch

**Comment by jerstlouis** [comment]
Maybe he had a long day and meant .tmLanguage then? I don't mind either way
:)

**Comment by jerstlouis** [comment]
Got the confirmation it should be .tmLanguage and fixed and pushed to

https://github.com/ecere/ec.tmbundle

**Comment by pchaigno** [comment]
I added it to #2071.

**Comment by arfon** [comment]
:+1: - this should now be fixed in the latest release.
