### ISSUE TITLE
MonkeyC support

### ISSUE THREAD

**Issue by tradespoke** [github/linguist#2084]
Please add MonkeyC to supported languages (and make it possible to search for repositories written in MonkeyC in Advanced Search)

http://developer.garmin.com/connect-iq/monkey-c/

**Comment by pchaigno** [comment]
Hi @tradespoke - Which extension(s) is it using? Is it widely used on GitHub?

**Comment by arfon** [comment]
Hi @tradespoke, please take a look at our [contributing guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) which gives some guidance on the sorts of information we need before we can consider adding a new language.

**Comment by nickbroon** [comment]
Just to gather information in one place, here is link to in the wild use of the Garmin MonkeyC language:
https://github.com/search?p=8&q=extension%3Amc+%22using+toybox%22&ref=searchresults&type=Code&utf8=%E2%9C%93

It's extension is `.mc`
I'd guess the most appropriate `ace_mode` for the language would be `c_cpp` or `java`

What is needed to is build a grammar file for the language.

Sample of the language could almost certainly be lifted from the Garmin SDK examples at http://developer.garmin.com/connect-iq/monkey-c/
