### ISSUE TITLE
VC++ resource script (*.rc) files are treated as binary files when viewing commits.

### ISSUE THREAD

**Issue by flarn2006** [github/linguist#2088]
Example: https://github.com/flarn2006/WinParticles/commit/68c683840cea01537d042e7d690eaacdf374b4c8

The changed file at the bottom is a .rc file, which is a text file, but it doesn't show the changes because for some reason it thinks it's a binary file.

**Comment by pchaigno** [comment]
Same issue as in #1873. It is actually an issue with git itself.
Because your file is encoded in UTF-16, git detects `NULL` bytes at the beginning and thinks it's a binary file :/

**Comment by arfon** [comment]
@flarn2006 I'm afraid there nothing that can be done in the near future to solve this. See @brianmario's comment in #1849.
