### ISSUE TITLE
Java Syntax Higlighting broken

### ISSUE THREAD

**Issue by itshorty** [github/linguist#2090]
Hi,

the Java highlighter has a problem formating block-comments containing '<' 

For an example see here: https://github.com/itshorty/libsybos/blob/master/src/main/java/at/ffesternberg/sybos/SybosClient.java#L220

greetings Florian

**Comment by bkeepers** [comment]
Hi @itshorty. Thanks for reporting the issue! We use Textmate's [Java bundle](https://github.com/textmate/java.tmbundle) to perform the syntax highlighting.  Would you mind reporting the bug there?

There is more information in our [docs on fixing syntax highlighting issues](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#fixing-syntax-highlighting).

**Comment by hagbard** [comment]
Personally I think it would be wise to consider Textmate's [Java bundle](https://github.com/textmate/java.tmbundle) as an abandoned project and perhaps look for alternatives. There are many open issue affecting modern Java syntax which have remained unaddressed for many years.

https://github.com/textmate/java.tmbundle/issues

As Java syntax evolves, and people start using matcher syntax, string templates, virtual threads etc. this issue will only get worse and the output from Linguist will start becoming effectively unusable for many situations.

**Comment by lildude** [comment]
GitHub doesn't use the TextMate grammar. It uses the [tree-sitter grammar](https://github.com/tree-sitter/tree-sitter-java) (see [here](https://github.com/github-linguist/linguist/tree/master/vendor)) which is actively maintained. If you are seeing problems on GitHub, report them to the grammar maintainers and it'll eventually be pulled into GitHub. Linguist continues to ship the TextMate grammar so other grammars that may rely on it don't break.
