### ISSUE TITLE
A syntax to allow a user to highlight arbitrary structured text

### ISSUE THREAD

**Issue by JoshCheek** [github/linguist#2095]
I find I often want to highlight some text that isn't a particular language. For example, I'm a teacher, so I might teach a lesson on file permissions. Some structure would help them understand the grouping, so I might want the output of `ls -l` to look like this:

![screenshot 2015-02-09 22 02 04](https://cloud.githubusercontent.com/assets/77495/6121830/66e4c3c6-b0a7-11e4-86a8-dd6bfcb45014.png)

How would I do that in Markdown? IDK, maybe something like this.

![screenshot 2015-02-09 23 22 16](https://cloud.githubusercontent.com/assets/77495/6122657/1c5b0eca-b0b4-11e4-993b-f05e545fcf4e.png)

So, instead of embedding knowledge of the structure into the parser, which is arbitrary and will change for every instance of this grammar, you embed knowledge of the structure language. Then you can use the structure language to apply syntax highlighting to any arbitrary text. The structure language is omitted from the final output.

This would be nice for me in my use case, I can syntax highlight data to help my students see the associations between the pieces. Someone else could show a hypothetical example of a language or a feature, and have highlighting for that. Some artistic individual would apply it to their ascii art generated from an image. My point is just that it can handle any highlighting oriented use case and opens up a lot of creative potential.

Is this (1) already done in one of those many many languages? (2) possible (3) something others would be interested in?

**Comment by arfon** [comment]
Sorry for the very slow response to this @JoshCheek. I agree this would be cool but I'm afraid I just don't have an answer for (1) & (2) and to be honest my response to (3) is 'kinda'. I think it's an interesting idea for sure but I don't see us working on anything like this anytime soon sorry.
