### ISSUE TITLE
Repository reanalysis not working?

### ISSUE THREAD

**Issue by larsbrinkhoff** [github/linguist#2096]
I asked support@github to reanalyse language statistics for a number of repos, e.g. https://github.com/jamesbowman/j1.  However, the repository language is still listed as "F#".  I tested it myself with Linguist v4.3.1 (live version I believe), v4.3.0, and v4.2.7.  They all return "Forth" as the primar language.

I reported this to support, but they are sure they did reanalyse the repositories.  Is there a problem with Linguist?

**Comment by whitten** [comment]
It's also possible that the data that the bayesian matcher uses that is supposed to match Forth isn't as strong as the data that supports F#

**Comment by arfon** [comment]
@larsbrinkhoff - strange - I just tried re-analysing and things are looking much better. Any chance you could loop me in on the discussion with support (arfon@github.com)

**Comment by larsbrinkhoff** [comment]
@whitten That may be the case, but I really checked all repositories with Linguist before submitting the request.  And also, in the case of Forth vs F#, the heuristics will probably find the correct language before the bayesian matcher has a chance to run.

**Comment by larsbrinkhoff** [comment]
@arfon Thanks!  That's what I thought.  I suspect there may be a problem in how support schedules the language analysis jobs.  Will send you copies of the messages.

**Comment by arfon** [comment]
> @arfon Thanks! That's what I thought. I suspect there may be a problem in how support schedules the language analysis jobs. Will send you copies of the messages.

:+1: thanks.

**Comment by larsbrinkhoff** [comment]
@arfon There are three more repos that should go F# -> Forth, and 19 FORTRAN -> Forth.  If you need test cases.
