### ISSUE TITLE
HTML Not Detected

### ISSUE THREAD

**Issue by MrabEzreb** [github/linguist#2099]
HTML files aren't detected at all, they don't show up as HTML or Other.

**Comment by pchaigno** [comment]
HTML files are actually detected (see for instance in [bootstrap](https://github.com/twbs/bootstrap/search?l=html)) but [Linguist considers HTML as a markup language](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L1172) and thus these files are not part of the statistics.

**Comment by MrabEzreb** [comment]
ohhhh, okee :P but wouldnt CSS also be markup?

**Comment by arfon** [comment]
/ cc @aroben - very topical!

**Comment by pchaigno** [comment]
@arfon Just saw the PR ^_^

@MrabEzreb See #2097 for more about this.

**Comment by arfon** [comment]
@MrabEzreb this is fixed in https://github.com/github/linguist/pull/2097 . Please note you need to push a change to your repository before the language statistics will update.

**Comment by MrabEzreb** [comment]
YAY! Thanks so much!!
