### ISSUE TITLE
Update language-clojure to 0.12.0

### ISSUE THREAD

**Issue by manicolosi** [github/linguist#2103]
[language-clojure](https://github.com/atom/language-clojure) was updated to 0.12.0 which included a fix to how Clojure syntax highlighting highlights double quote character literals `\"` ([#11](https://github.com/atom/language-clojure/issues/11)).

**Comment by pchaigno** [comment]
@manicolosi Submodules (i.e. grammars) are updated with each new release ;) It's usually every couple weeks.

**Comment by arfon** [comment]
Yep, this will be updated in the next release.
