### ISSUE TITLE
README doesn't mention parsing

### ISSUE THREAD

**Issue by dcecile** [github/linguist#2104]
Neither the [README](https://github.com/github/linguist/blob/master/README.md)'s introductory sentence not its troubleshooting indicates that Linguist is responsible for parsing language syntax. Any problems with GitHub code colours probably originate in this repository's submodules.

Current introductory sentence:

> This library is used on GitHub.com to detect blob languages, ignore binary or vendored files, suppress generated files in diffs, and generate language breakdown graphs.

Sample (wordy) revised introductory sentence:

> This library is used on GitHub.com to detect blob languages, ignore binary or vendored files, suppress generated files in diffs, generate language breakdown graphs, and create parse trees of code for syntax highlighting.

As for the other sections of the README (troubleshooting / overrides / usage), I'm really not sure how or if they should be adapted.

**Comment by pchaigno** [comment]
@dcecile Sorry for the late reply.

Actually, Linguist doesn't parse the code for syntax highlighting. It only selects the proper syntax definition that is then used by a closed source piece of code for syntax highlighting.

I'm closing this issue in favor of #2331, which addresses the broader issue of how Linguist relates to github.com.

**Comment by dcecile** [comment]
No problem; thanks for the update :+1:
