### ISSUE TITLE
Numerous files are incorrectly detected as C instead of C++

### ISSUE THREAD

**Issue by vitaut** [github/linguist#2105]
Most files that contain `namespace` or `typename` are C++ files, but are detected as C, for example:

https://github.com/search?utf8=%E2%9C%93&q=language%3Ac+namespace&type=Code&ref=searchresults

**Comment by arfon** [comment]
Hi @vitaut. Thanks for reporting this. Would you mind adding this comment over here: https://github.com/github/linguist/issues/1626 where we're already tracking this issue?

**Comment by vitaut** [comment]
Sure, sorry for the duplicate.
