### ISSUE TITLE
CMakeLists.txt is not detected as CMake code

### ISSUE THREAD

**Issue by vitaut** [github/linguist#2106]
Here's a file that is reported as text although it is clear form the file name that it is a CMake code:

https://github.com/cppformat/cppformat/blob/757a523195325d73eb87469875990dd6ac8f82ff/test/CMakeLists.txt

**Comment by pchaigno** [comment]
The last released version of Linguist detects this file as CMake so your statistics are probably just not up-to-date. It looks like the highlighting is though. It should update with the next commit or if you contact GitHub support.

This kind of incorrect detections (when the detection is made based on the filename) should be fixed with #2006.

**Comment by vitaut** [comment]
Thanks for the information. Do you mean it should update with the next commit to this specific file? Doesn't GitHub update language statistics periodically?

**Comment by arfon** [comment]
> Doesn't GitHub update language statistics periodically?

Hi @vitaut - I'm afraid language statistics are only updated after a [update is pushed to your repo](https://help.github.com/articles/my-repository-is-marked-as-the-wrong-language/)

**Comment by vitaut** [comment]
@arfon Well, I've just pushed to the `master` branch of the repo containing the file, but it's still misclassified.

**Comment by arfon** [comment]
@vitaut - can you tell me what URL you are using to determine that it's being classified as text? As @pchaigno mentioned, the highlighting suggests that we think it's `CMake`

**Comment by pchaigno** [comment]
@arfon I think @vitaut saw that it was classified as text through [this page](https://github.com/cppformat/cppformat/search?l=text). Maybe I didn't have the last released version when I tested...

**Comment by arfon** [comment]
Ah ok. The search indexes are sometimes a few minutes behind these updates. https://github.com/cppformat/cppformat/search?l=text doesn't show any results now.

**Comment by vitaut** [comment]
Actually, it does classify it correctly now. Probably needed more time after the push. Thanks!

**Comment by vitaut** [comment]
FWIW I was checking the classification here: https://github.com/cppformat/cppformat/search?l=text

**Comment by arfon** [comment]
:+1: - glad things are looking better for you now @vitaut
