### ISSUE TITLE
.nl files are incorrectly reported as NewLisp

### ISSUE THREAD

**Issue by vitaut** [github/linguist#2113]
[.nl files](http://en.wikipedia.org/wiki/Nl_%28format%29) are incorrectly reported as NewLisp in the description of [AMPL/MP](https://github.com/ampl/mp) project (and probably in other places):

![screenshot from 2015-02-13 12 58 06](https://cloud.githubusercontent.com/assets/576385/6195165/59271ac8-b380-11e4-8410-b32c2857f333.png)

Here's an example of such file: https://github.com/ampl/mp/blob/master/test/data/assign0.nl

NL files are very easy to detect: they all start with letter `b` or `g` immediately followed by a number.

**Comment by arfon** [comment]
@vitaut - what language should these be detected as?

**Comment by pchaigno** [comment]
@arfon [As the NL file format apparently](http://en.wikipedia.org/wiki/Nl_%28format%29). I found [more than 1,200 NL files on GitHub](https://github.com/search?o=desc&p=100&q=extension%3Anl+g0&ref=searchresults&s=indexed&type=Code&utf8=%E2%9C%93).

@vitaut Do you know a Sublime Text package or TextMate bundle to highlight these files?

**Comment by vitaut** [comment]
Yes they should be ideally reported as something like "NL Format". This is a low-level format designed for machine rather than human input so I don't think there is a grammar for it.

**Comment by pchaigno** [comment]
@vitaut Does that mean that they are generated from a higher language?

**Comment by vitaut** [comment]
@pchaigno Yes, they are usually generated from [AMPL](https://en.wikipedia.org/wiki/AMPL) or other mathematical programming system (such as [Pyomo](https://software.sandia.gov/trac/pyomo) or [OpenSolver](http://opensolver.org/)). So it's not really a language, more like a serialization format for optimization problems. It just doesn't seem right that it is detected as NewLisp.

**Comment by arfon** [comment]
So it sound like these should probably be added (name TBD) and then set as `data`?

**Comment by pchaigno** [comment]
Would NL be okay for the name?

**Comment by arfon** [comment]
> Would NL be okay for the name?

Yeah, I think so. http://en.wikipedia.org/wiki/Nl_%28format%29 . Looks like there's `SOL` too: http://en.wikipedia.org/wiki/Sol_(format)

**Comment by vitaut** [comment]
"NL" is perfectly fine.

**Comment by pchaigno** [comment]
@arfon Do we need to add SOL too??

**Comment by arfon** [comment]
> @arfon Do we need to add SOL too??

No, I just saw they were related and thought it might be worth adding them both?

**Comment by pchaigno** [comment]
But as two distinct languages then?

**Comment by arfon** [comment]
Yeah. I thought it might be worth looking into but there's no rush as it's not directly related to this issue.
