### ISSUE TITLE
MIT license detected as Erlang

### ISSUE THREAD

**Issue by christianbundy** [github/linguist#2115]
Same issue as #769. [Example](https://github.com/neale/relations/blob/master/LICENSE).

**Comment by pchaigno** [comment]
That's because you license file is executable. Thus, Linguist thinks it's a script file and tries to identify the script language :/
If you remove the executable flag it should be fine.

**Comment by arfon** [comment]
:+1: yep, if you remove the executable flag you should be good.

**Comment by christianbundy** [comment]
Thanks guys, that's hilarious. I'll go bother @neale about it.
