### ISSUE TITLE
Says KiCad Project file is Prolog

### ISSUE THREAD

**Issue by HSchmale16** [github/linguist#2116]
Your language recognition software says that a kicad project file is a prolog file, yet it's closer to MS-INI. This should be fixed as a lot of software development tools use MS-INI format to describe projects.

**Comment by pchaigno** [comment]
Hi @HSchmale16 - Do you have a link to the repository where this issue is occurring? What extension are KiCad project files using?

**Comment by WyldeOscar** [comment]
hey





Wylde Oscar Enterprises
Oscars Adult Toys & Lingerie <http://oscarsadulttoys.com>
Edmonton,AB
Canada

**Comment by HSchmale16** [comment]
https://github.com/HSchmale16/CustomComputerChair
The extension is `.pro`, There's a string right at the begining of the file that can be used to id kicad project files.

**Comment by pchaigno** [comment]
I think the solution here will be to add `.pro` as a INI extension. Then, KiCad project files will be recognized and highlighted as INI. Anything against that?

**Comment by HSchmale16** [comment]
Wouldn't that affect prolog detection too.

**Comment by pchaigno** [comment]
We already have a [heuristic rule for the `.pro` extension](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.rb#L110-L116). I will extend it to classify KiCad files based on the line that you mentioned, at the beginning of the file.

**Comment by HSchmale16** [comment]
Yeah, that would work. I was just reading the project file, and you're going to want to search for `[eeschema]` or `pcbnew` in a set of angle brackets.

**Comment by pchaigno** [comment]
#2154 should fix this.

**Comment by arfon** [comment]
Hi @HSchmale16 - https://github.com/github/linguist/pull/2154 has just been merged and a new version of Linguist should be live on GitHub in the next week or so.
