### ISSUE TITLE
XAML classified as XML

### ISSUE THREAD

**Issue by rikkit** [github/linguist#2124]
See: https://github.com/inflatablefriends/lastfm

[XAML](http://en.wikipedia.org/wiki/Extensible_Application_Markup_Language) *is* XML but I think it's misleading to show it comprising 83% of the codebase. There hasn't been a commit for a month until today - previously the stats showed 98% C#.

What would cause the XAML to be overrepresented like this? And can it be represented as XAML, not XML?

**Comment by aroben** [comment]
We only just started including XML in repository language statistics (see #2097). That repository has 1.5MB of XML and only 263KB of C#. I'm working on excluding project files (like `.csproj`) from the statistics, and might end up excluding all XML files again until we can come up with a better classification.

**Comment by aroben** [comment]
This is now fixed on github.com.

**Comment by rikkit** [comment]
@aroben C# is a lot more compact than XAML so filesize will always be misleading... linecount would be a better metric imo.

**Comment by rikkit** [comment]
@aroben I think XAML should be a separate filetype; it's based on XML but it's more akin to HTML. Wasn't clear on this when I raised the issue: XML is a data format, XAML is a markup language.
