### ISSUE TITLE
Adding a Contributor License Agreement

### ISSUE THREAD

**Issue by bkeepers** [github/linguist#2126]
I just wanted to give a heads up that new pull requests will now have a status for the "GitHub CLA". Think of a CLA like an open source software license from the contributor to the project, letting us and other users know that we have permission to use the contributed code.

For first pull request that someone makes to this repo, contributors will have to click through the failure link to the CLA and accept the agreement. Any future pull pull requests will immediately go green.

This is a new process that we are just experimenting with. We want to find the right balance of protecting the projects we maintain without adding too much friction for contributors. I welcome any and all feedback.

/cc @arfon @pchaigno @larsbrinkhoff

**Comment by arfon** [comment]
:zap:

**Comment by larsbrinkhoff** [comment]
I fully understand that GitHub would need something like this.  As a GNU contributor, I find your suggestion rather light-weight.  The only complication would be when adding sample files.  Do we need to get an explicit permission for those?

**Comment by larsbrinkhoff** [comment]
Is the license agreement text available online for empoyers to review?  I mean, other than me copy-pasting it and emailing my boss.

**Comment by pchaigno** [comment]
:+1: I always found it weird that no CLA was required.

Will this be required for all GitHub projects from now on or only Linguist?
Shouldn't contributors who made their contribution before today be required to "sign" it?

**Comment by larsbrinkhoff** [comment]
I had this thought...

To encourage contributions, once a PR is accepted, the contributor could be invited to some kind of "GitHub contributor" organization.  This would add a bit of flair to the user profile.

**Comment by bkeepers** [comment]
> As a GNU contributor, I find your suggestion rather light-weight.

What do you mean?

> Is the license agreement text available online for empoyers to review? I mean, other than me copy-pasting it and emailing my boss.

https://cla.github.com/

It currently requires being signed in and authorizing the app, but I'll get rid of that.

> Will this be required for all GitHub projects from now on or only Linguist?

We will be adding it to all GitHub projects soon.

> Shouldn't contributors who made their contribution before today be required to "sign" it?

Ideally, yes, but it will be very tedious and to chase them all down. Right now we are focusing on getting CLAs for future work. We may revisit for previous contributions later.

> To encourage contributions, once a PR is accepted, the contributor could be invited to some kind of "GitHub contributor" organization. This would add a bit of flair to the user profile.

That's a cool idea. I'll see if I can get some traction for that.

**Comment by larsbrinkhoff** [comment]
> > As a GNU contributor, I find your suggestion rather light-weight.
> What do you mean?

A GNU contributor is required to sign an actual dead-tree paper and send it by snail mail.  In light of that, the GitHub CLA process is quite smooth.

**Comment by bkeepers** [comment]
:+1: That's our goal.
