### ISSUE TITLE
Tcl and TCC-interpreted C misclassified as JavaScript

### ISSUE THREAD

**Issue by pjanouch** [github/linguist#2127]
linguist seems to be a bit too happy to mark code as JavaScript.

This is a normal C file, only without an extension. The first line states ```/usr/bin/tcc -run``` as the interpreter, which is a very unmistakable identifier for regular C code. I suggest adding this "interpreter" to languages.yml for C.
https://github.com/pjanouch/ZyklonB/blob/master/plugins/script

~~Similarly, while this Tcl file doesn't have an extension either, the interpreter line of ```/usr/bin/env tclsh``` should make it pretty clear that this is supposed to be Tcl code. ```tclsh``` seems to be already present in languages.yml, so I'm not sure if this is a problem of JavaScript overriding this, or of not being able to detect interpreters correctly after ```/usr/bin/env```.~~
https://github.com/pjanouch/ZyklonB/blob/master/plugins/coin

**Comment by pchaigno** [comment]
> I suggest adding this "interpreter" to languages.yml for C.

Sounds like a good idea to me (but I'm not from GitHub though); I think you should open a pull request for that.

> tclsh seems to be already present in languages.yml, so I'm not sure if this is a problem of JavaScript overriding this, or of not being able to detect interpreters correctly after /usr/bin/env.

Interpreters are not a requirement for files to be detected properly. Meaning that if a file doesn't have a `tclsh` shebang, it can still be a Tcl files. Thus, Linguist keeps it as a potential candidate and, in that case, the Bayesian classifier detected it as JavaScript :/

**Comment by pjanouch** [comment]
The Tcl issue seems to have been somehow fixed now.

**Comment by pchaigno** [comment]
@pjanouch Do you want to open a pull request for `tcc` or should I do it?

**Comment by pjanouch** [comment]
@pchaigno I would rather if someone more knowledged in the project made the change, even if it seems to be a one-liner (or two-liner). I would probably get to it eventually but if you feel like contributing, sure, take it.

**Comment by pchaigno** [comment]
I opened a pull request at #2147.

**Comment by arfon** [comment]
#2147 is now merged. It'll be another couple of weeks before this change is live on GitHub.com
