### ISSUE TITLE
vendored / language stats issue?

### ISSUE THREAD

**Issue by jerstlouis** [github/linguist#2132]
I've tried taking advantage of the new custom vendored paths to sort out files that shouldn't be considered in classification, but the stats still look wrong to me.

https://github.com/ecere/ecere-sdk

I would expect eC to rank much higher (> 90% instead of 47.9%) as we really have very few C source files. The search per language feature makes it somewhat difficult to understand what's going on, as it does not exclude the vendored files (an option to do so, enabled by default when you end up in the search from clicking a particular language from the graph bar would be very useful in my opinion). However even going through all 82 pages of what gets classified as 'C', I would expect almost all of them should be excluded by the vendored settings (except about 4 .c files: DualPipe.c, File.c, System.c and instance.c). All ecere/src/gfx/drivers/harfbuzz/, deps/ and compiler/bootstrap/ files should be excluded.

The .gitattributes contains:

ecere/src/gfx/drivers/harfbuzz/* linguist-vendored
compiler/bootstrap/* linguist-vendored
deps/* linguist-vendored
samples/* linguist-vendored=false

Any help figuring out what's going on would be much appreciated.

Thank you!

Jerome

**Comment by pchaigno** [comment]
I ran Linguist against your repository and these files are still counted as C:
```
compiler/libec/src/grammar.h
ecere/src/com/instance.c
ecere/src/gui/drivers/cocoa/CocoaEcereBridge.h
ecere/src/sys/DualPipe.c
ecere/src/sys/File.c
ecere/src/sys/System.c
eda/drivers/sqlite/shell.c
eda/drivers/sqlite/sqlite3.c
eda/drivers/sqliteCipher/sqlite3.c
extras/include/dpl.c
extras/include/dpl.h
```

Could that explain the statistics?

**Comment by jerstlouis** [comment]
Ah! Thank you! I probably missed the SQLite files lost in all those others
files.

**Comment by pchaigno** [comment]
You're welcome! Is this issue solved then?

> The search per language feature makes it somewhat difficult to understand what's going on, as it does not exclude the vendored files (an option to do so, enabled by default when you end up in the search from clicking a particular language from the graph bar would be very useful in my opinion).

I agree that it would be a really useful feature. You should submit it to support@github.com, they keep a list of suggestions.

**Comment by jerstlouis** [comment]
Yes it is solved ( was not an issue ), I had missed the SQLite files.

However as mentioned I think my suggestion would avoid this type of
confusion, so I will submit it to support@github.com as you suggest.

Thanks again for your help.

Jerome
