### ISSUE TITLE
Why is my repository suddenly consider nearly 50% XML?

### ISSUE THREAD

**Issue by Kazark** [github/linguist#2134]
I have a [repo](https://github.com/PolyglotSymposium/void) which was considered 75% F# and 25% C#. Now that make sense. I pushed up four commits in which I only added F# code, refreshed the page, and suddenly my project was considered nearly 50% XML. (Is this a coincidence that I just pushed then? Did Linguist just update between page loads?) The only XML I have in the project are NuGet configuration files and Visual Studio project and solution files. So true, there is XML under source control, but it's not a project done in XML... it feels weird to have it reporting nearly 50% XML.

**Comment by Kazark** [comment]
A [similar project](https://github.com/jaredpar/VsVim) is not showing any XML, which is evidence that this is a misidentification.

**Comment by SomethingSexy** [comment]
Same thing happened to be yesterday.  I have a predominately PHP project and now it is showing mostly as XML.

**Comment by larsbrinkhoff** [comment]
This is because of #2097.

**Comment by Kazark** [comment]
@larsbrinkhoff Interesting. I can see why they did that, but in the case of `.csproj`, `.nuspec`, `.fsproj`, `.sln` and other such files, XML is not so much a markup language that is part of the project as a configuration language that is part of its metadata.

**Comment by larsbrinkhoff** [comment]
In your own repositories, you can override file classification in the `.gitattributes` file.

**Comment by Kazark** [comment]
@larsbrinkhoff I added [this](https://github.com/PolyglotSymposium/void/blob/master/.gitattributes), and it doesn't seem to have fixed it. What did I do wrong?

**Comment by larsbrinkhoff** [comment]
I'm not sure `linguist-type` is implemented yet?  I believe `linguist-vendored` should work:
https://github.com/github/linguist#overrides

**Comment by pchaigno** [comment]
@Kazark The best solution for you here is to use `linguist-documentation` I think. Unlike `linguist-vendored` it will still show the files in diffs.

**Comment by Kazark** [comment]
This seems to have fixed it:
```
*.[cC]onfig linguist-documentation
*.sln linguist-documentation
*.fsproj linguist-documentation
*.csproj linguist-documentation
*.shproj linguist-documentation
*.projitems linguist-documentation
*.targets linguist-documentation
*.plist linguist-documentation
```
@aroben Should I leave this issue open?

**Comment by aroben** [comment]
Yes please. I'm working on changing Linguist to exclude these project files by default.

**Comment by Kazark** [comment]
Awesome. I was just telling my wife how much I love GitHub. This is just one more example.

**Comment by aroben** [comment]
This is now fixed on github.com.

**Comment by aroben** [comment]
This is now fixed on github.com.

**Comment by Kazark** [comment]
Super! That was quick.
