### ISSUE TITLE
Nynorsk and Bokmål identified as Mathamatica

### ISSUE THREAD

**Issue by Zachary-Holland** [github/linguist#2137]
See https://github.com/msysgit/msysgit/search?l=mathematica&q=vim&utf8=%E2%9C%93
(previous title said Norwegian, based on [Google Translate](https://translate.google.com/#auto/en/Vim%20er%20en%20meget%20kraftig%20editor%20med%20mange%20kommandoer%2C%20alt%20for%20mange%20til%20%C3%A5%0Akunne%20g%C3%A5%20gjennom%20alle%20i%20en%20innf%C3%B8ring%20som%20denne.%20Den%20er%20beregnet%20p%C3%A5%20%C3%A5%0Asette%20deg%20inn%20i%20bruken%20av%20nok%20kommandoer%20s%C3%A5%20du%20vil%20v%C3%A6re%20i%20stand%20til%20lett%0A%C3%A5%20kunne%20bruke%20Vim%20som%20en%20editor%20til%20alle%20form%C3%A5l.))
=)

**Comment by larsbrinkhoff** [comment]
Another case of people using language codes as file extensions.  `.no` is Nynorsk I believe, and `.nb` is Bokmål.

**Comment by pchaigno** [comment]
#2146 should fix this.

**Comment by arfon** [comment]
Planning on fixing this in #2146
