### ISSUE TITLE
Repos now reported as HTML

### ISSUE THREAD

**Issue by larsbrinkhoff** [github/linguist#2138]
These two (and forks) are now reported as HTML.  I believe the primary programming language is Forth.

https://github.com/keithcausey/GreenArrays (I checked this with the latest release of Linguist)
https://github.com/DRuffer/arrayForth

It could be that they were reported as HTML or some other markup before #2097.  I didn't check that.

Thanks!

**Comment by aroben** [comment]
Interesting. These repositories each contain ~1.5MB of HTML but only ~13KB of Forth. Do you know what the purpose of the HTML files is?

**Comment by m3hr** [comment]
https://github.com/servo/servo is also being reported as HTML. IMO HTML should take the least precedence in being reported, especially for projects whose languages are up-and-coming.

**Comment by aroben** [comment]
Thanks for pointing that out. https://github.com/WebKit/webkit is in the same boat. Lots of HTML test files are skewing the statistics.

**Comment by aroben** [comment]
@m3hr @larsbrinkhoff I'm working to improve the situation here. In the meantime, this is fixable on a per-repository basis using `.gitattributes`. See https://github.com/github/linguist#using-gitattributes.

**Comment by larsbrinkhoff** [comment]
I have my own forks which include more Forth files, resulting in 90% Forth:
https://github.com/larsbrinkhoff/GreenArrays
https://github.com/larsbrinkhoff/arrayForth

The HTML files seem to be source code dumps.  Because the colors have semantic meaning in colorForth, and this may be awkward to express in ASCII format.

**Comment by larsbrinkhoff** [comment]
My arrayForth pull request was accepted, so that repo now displays as Forth.

**Comment by larsbrinkhoff** [comment]
I have another one:
https://github.com/mnemnion/gforth-win

**Comment by larsbrinkhoff** [comment]
https://github.com/blackpit73/arrayForth
https://github.com/uho/arrayForth

**Comment by jennybc** [comment]
@aroben I followed the advice at <https://github.com/github/linguist#using-gitattributes> to declare in the `.gitattributes` file that everything below `vignettes/` is documentation in [my repo](https://github.com/jennybc/googlesheets) . But the repo is still being reported as mostly HTML, due to a single piece of documentation that is compiled to HTML, when it is most definitely an R package.  Does this take a while to refresh? Or can you see what I am doing wrong?

**Comment by pchaigno** [comment]
@jennybc Looks fixed now ;)

**Comment by jennybc** [comment]
@pchaigno Yes I got some unexpected help from @arfon. :+1:

**Comment by pchaigno** [comment]
@jennybc Great!

**Comment by larsbrinkhoff** [comment]
C++ project with ample documentation:
https://github.com/Carisius/pikascript

**Comment by arfon** [comment]
Closing this as we're not planning on making any changes here.
