### ISSUE TITLE
Specifying a language in .gitattributes doesn't affect syntax highlighting

### ISSUE THREAD

**Issue by deviantintegral** [github/linguist#2140]
Most of my Github projects are Drupal projects, so we have a ton of custom extensions containing PHP code. There's quite a few issues for adding support, but most of them are blocked on conflicts over the .inc extension.

According to the Linguist readme, we should be able to manually specify file masks to mark language types. While Linguist on my local properly picks up the .module and .inc extensions, Github is still not detecting the files as PHP code in search or in syntax highlighting.

* [An example repository](https://github.com/deviantintegral/linguist-module)
* [Linguist output](https://github.com/deviantintegral/linguist-module/blob/master/README.md)
* [Search results that are missing .inc and .module files](https://github.com/deviantintegral/linguist-module/search?l=php)
* [The .gitattributes file](https://github.com/deviantintegral/linguist-module/blob/master/.gitattributes)

Is this simply not supported as a feature, a bug, or am I not setting up the .gitattributes file correctly?

**Comment by geerlingguy** [comment]
If, in Drupal 8, all the PHP files are made to end in `.php`, this will be a non-issue. Still an issue for older Drupal codebases... and would be an issue if that Drupal issue _doesn't_ make it in time for Drupal 8's release, but so far it looks like that might just happen :)

**Comment by arfon** [comment]
Hi @deviantintegral - unfortunately this currently isn't supported (we're tracking the issue here https://github.com/github/linguist/issues/1792). This isn't quite the same fix but it's possible to override on a per-file basis using Vim or Emacs overrides: https://github.com/github/linguist#using-emacs-and-vim-modelines

**Comment by deviantintegral** [comment]
Thanks @arfon - I filed a docs update to clarify this. It doesn't really help for upstream code where we don't want to modify it, but it would certainly work for custom code for a specific project.
