### ISSUE TITLE
Some .pm categorised as Perl6, some as Perl

### ISSUE THREAD

**Issue by mintsoft** [github/linguist#2149]
Hey,

We have a collection of `.pm` files, all of which are Perl 5; however about 10% are being classed as Perl 6 incorrectly:

* https://github.com/duckduckgo/zeroclickinfo-goodies/search?l=perl6
* https://github.com/duckduckgo/zeroclickinfo-goodies/search?l=perl

I've had a quick look and I can't see what the particular reason is. A specific example is:
Erroneously Perl 6:
* https://github.com/duckduckgo/zeroclickinfo-goodies/blob/f352c6c9ae215c68607c38acaa9b89402fe736a3/lib/DDG/Goodie/DateMath.pm
* https://github.com/duckduckgo/zeroclickinfo-goodies/blob/f352c6c9ae215c68607c38acaa9b89402fe736a3/lib/DDG/Goodie/PrivateNetwork.pm

Correctly Perl 5:
* https://github.com/duckduckgo/zeroclickinfo-goodies/blob/f352c6c9ae215c68607c38acaa9b89402fe736a3/lib/DDG/Goodie/BashPrimaryExpressions.pm
* https://github.com/duckduckgo/zeroclickinfo-goodies/blob/f352c6c9ae215c68607c38acaa9b89402fe736a3/lib/DDG/Goodie/TimezoneConverter.pm

cc @jagtalon @mrchrisw

**Comment by mintsoft** [comment]
I've also just noticed it here: 
* https://github.com/duckduckgo/p5-app-duckpan/blob/master/lib/App/DuckPAN/Web.pm 
Which is also Perl 5

**Comment by pchaigno** [comment]
I'm afraid there is not much that can be done with Linguist here.
As you can guess, distinguishing Perl 5 and Perl 6 is tricky. The way Linguist does it is by first using [some heuristic](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.rb#L92-L100); if that doesn't work the Bayesian classifier tries to guess the language. But since the two languages are really close, it will often fail.

A few solutions to fix your case:
- explicitly say you're using Perl 5 with `use v5;` (`use strict;` will also work in your case)
- add `*.pm linguist-language=perl` in a `.gitattributes` file to override Linguist results (this will only affect the statistics)
- use [Vim modelines](https://github.com/github/linguist#using-emacs-and-vim-modelines)

**Comment by mintsoft** [comment]
@pchaigno I can certainly see how difficult this is. Just to clarify, if we use the `.gitattributes` then it wouldn't fix the highlighting in the cases when it's incorrectly classified as 6?

**Comment by pchaigno** [comment]
> Just to clarify, if we use the .gitattributes then it wouldn't fix the highlighting in the cases when it's incorrectly classified as 6?

That's correct. Unfortunately, the highlighting and the search results are currently not affected by the overrides :/

**Comment by mintsoft** [comment]
Dang, that's a real shame. Do you know if there's any plans to link the overrides in at some point?

**Comment by pchaigno** [comment]
I think it is considered. @arfon will know for sure.

**Comment by arfon** [comment]
> Do you know if there's any plans to link the overrides in at some point?

Yeah, there's an issue for this [here](https://github.com/github/linguist/issues/1792). We'd definitely like to add this functionality - it's just a bunch of work on our end (for GitHub/infrastructure reasons).

**Comment by arfon** [comment]
... for now, the EMacs and Vim overrides are probably your best bet: https://github.com/github/linguist#using-emacs-and-vim-modelines

**Comment by mintsoft** [comment]
Cool thanks @arfon We've actually opted for the `use strict;` for now.

**Comment by arfon** [comment]
:+1: ok thanks @mintsoft

**Comment by kraih** [comment]
If Linguist can't distinguish between Perl 5 and Perl 6, why does it default to Perl 6 here? The odds of it being Perl 5 are much much much higher. I think that's the real bug.

**Comment by arfon** [comment]
> If Linguist can't distinguish between Perl 5 and Perl 6, why does it default to Perl 6 here? The odds of it being Perl 5 are much much much higher. I think that's the real bug.

Because the 'likelihood' is determined by the bayesian classifier and not any other custom rules about languages which are more likely purely based on popularity.

As @pchaigno [discussed](https://github.com/github/linguist/issues/2149#issuecomment-75452121), getting Linguist to do the right thing here is hard so I'd encourage you to take a look at the [overrides](https://github.com/github/linguist/#overrides) to address this issue.

**Comment by jberger** [comment]
Based on the [linked code](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.rb#L92-L100), there seems to only be certain heuristics, but no way to provide a default 'else'.

```ruby
  ...
  else
    Language["Perl"]
  end
```

**Comment by arfon** [comment]
It is possible to provide a default 'else' but we try to avoid writing heuristics that way. Especially as we don't actually know the file extension we're working with when we're in the heuristic.

**Comment by zoffixznet** [comment]
What about adding popularity of a language, however vaguely it is defined, as part of the heuristics?

Regardless of Linguist's implementation, Perl5 has 150,717 modules (not all of them on GitHub though), while Perl6 has only 330. It's incredibly more likely that an ambiguous file is Perl5 code, not Perl6.

**Comment by arfon** [comment]
> What about adding popularity of a language, however vaguely it is defined, as part of the heuristics?

It's possible we could do something with popularity _somewhere_ in the [language classification](https://github.com/github/linguist/blob/master/lib/linguist/language.rb#L90-L96) but the heuristics isn't the right place.

**Comment by jberger** [comment]
I could even suggest that, in the interim, the lack of a `use v6` ought to be enough to disambiguate. I'm fairly sure that that is a Perl 6 best practice and will (or should) be for some time.

**Comment by smls** [comment]
Perl 6's design docs have some thought in the matter: see point 8 in [this bullet point list](http://design.perl6.org/S01.html#Random_Thoughts).

In practice, this means that it should be safe to assume a .pm file is Perl by default, and only treat it as Perl 6 if the first line which is not empty and not a comment starts with one of:

    use v6
    class
    module
    unit

**Comment by mintsoft** [comment]
> If Linguist can't distinguish between Perl 5 and Perl 6, why does it default to Perl 6 here? The odds of it being Perl 5 are much much much higher. I think that's the real bug.
I agree with this, it does seem odd that the weighting appears to be in favour of Perl6

> I could even suggest that, in the interim, the lack of a use v6 ought to be enough to disambiguate. I'm fairly sure that that is a Perl 6 best practice and will (or should) be for some time.
This seems sensible to me

**Comment by zoffixznet** [comment]
> I could even suggest that, in the interim, the lack of a use v6 ought to be enough to disambiguate. I'm fairly sure that that is a Perl 6 best practice and will (or should) be for some time.

Just asked about this on [#perl6 IRC channel](irc://irc.freenode.net/#perl6) and FROGGS said that it likely won't work in this case, because we're also [trying to decide whether the code is Prolog.](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.rb#L92-L100)

Also, to add to the discussion, nwc10 had this to suggest:
> <nwc10> alternative question - is it viable to help train the basien filter - ie would github be happy with a button for "you're wrong, it's this other language?"

**Comment by mintsoft** [comment]
> because we're also trying to decide whether the code is Prolog.

Surely that's relatively straight forward, if there are `$` in it, it's not Prolog?

**Comment by zoffixznet** [comment]
Would there be any possibility of re-opening this issue so someone with more intimate knowledge of Ruby/Linguist could perhaps see if any of the suggestions above are viable and could be implemented, to make Linguist's guesses more accurate?

**Comment by mintsoft** [comment]
@zoffixznet I've reopened it for now, I'll leave it open unless the github staff close it

**Comment by jberger** [comment]
excellent, thanks!

**Comment by Grinnz** [comment]
This is excellent, thank you, but just wondering, does this also help with .t files? I don't see it referenced in the commits, and these seem to be the most often marked as Perl6 mistakenly.

**Comment by arfon** [comment]
> This is excellent, thank you, but just wondering, does this also help with .t files? I don't see it referenced in the commits, and these seem to be the most often marked as Perl6 mistakenly.

Not currently. We could write a heuristic that is only for `.t` extensions which uses the same matchers for `.pm` [here](https://github.com/github/linguist/commit/be122ca1a536ba730e292facabdc4348ec459281). Note that `.t` isn't unique to `Perl`/`Perl 6` - `Turing` also uses it so we'd need to make sure to include that also.

What do you think @pchaigno?

**Comment by zoffixznet** [comment]
@arfon in my experience, it's mostly the Perl 5's `.t` files that Linguist mistakenly thinks is Perl 6, so it would be very helpful if those were part of the heuristic.

**Comment by polamjag** [comment]
FYI: I feel like that problems described here is pretty much resolved by https://github.com/github-linguist/linguist/pull/6264 (ref. https://github.com/github-linguist/linguist/discussions/6263
