### ISSUE TITLE
nginx syntax highlighting error

### ISSUE THREAD

**Issue by plentz** [github/linguist#2155]
There's a problem with nginx conf files where comments sometimes isn't proper highlighted. If ou look here https://gist.github.com/plentz/6737338#file-nginx-conf-L6-L9 some comments aren't displayed in grey. But looking at the same file inside sublime text using nginx syntax, it looks okey.

![nginx](https://cloud.githubusercontent.com/assets/4867/6321025/d4a1bc54-bacd-11e4-948a-10cc8ae32be0.png)

maybe related with #2125

**Comment by arfon** [comment]
Hi @plentz - we use [this grammar](https://github.com/brandonwamboldt/sublime-nginx) to highlight files on GitHub. Would you mind opening an issue over there? Once the bug is fixed in the grammar we can pull the changes in here.

**Comment by pchaigno** [comment]
@arfon Except this time, the grammar works fine in Sublime Text :/ (I checked with the last dev version). This issue is very close to #2125 so it's probably best to follow it there.

**Comment by plentz** [comment]
@pchaigno thanks :)

**Comment by brandonwamboldt** [comment]
Turns out I had an error in my regex and sublime is a bit more forgiving (see my fix: https://github.com/brandonwamboldt/sublime-nginx/commit/872afddd2d61acae85560fa009658257f4030244). I will submit a PR to update the submodule here :)

**Comment by arfon** [comment]
Ok thanks for the follow up. Does that mean this issue can be closed?

**Comment by brandonwamboldt** [comment]
@arfon Once my PR gets created and merged :)
