### ISSUE TITLE
Possible .gitattributes issue

### ISSUE THREAD

**Issue by permcody** [github/linguist#2156]
I need to have linguist ignore certain paths in our repository that contain tests and large chunks of documentation. I added a .gitattributes file as shown in the linguist documentation but I can't get anything I try to work. I tried to play around with the existing linguist .gitattributes file as well with no changes to the language stats. Am I doing something wrong or am I hitting a bug in the processing of this file?

Here is a direct link to my .gitattributes file:
https://github.com/idaholab/moose/blob/devel/.gitattributes

I would expect the "PostScript" category to go to zero if this was working properly. Any help would be appreciated.

**Comment by pchaigno** [comment]
I get this when running the last released version of Linguist on your repository:
```
67.70%  C++
11.88%  C
9.04%   Python
4.60%   Mathematica
3.07%   TeX
1.96%   CSS
0.97%   Makefile
0.64%   FORTRAN
0.08%   Shell
0.04%   Matlab
0.03%   JavaScript
0.00%   Eiffel
```

It happens sometimes that the statistics don't update currently, you should contact GitHub support about that. It may update if you push something but that's not guaranteed.

**Comment by permcody** [comment]
Thanks, I'm aware that the stats often don't update for a few days. I'm glad you are seeing the correct stats though. I still don't see why I'm not getting them. If it's working on your end, then it must be a problem on my system so feel free to close this issue.

**Comment by arfon** [comment]
Hi @permcody - I just tried adding a new custom rule for .eps files here which seems to address things? https://github.com/idaholab/moose/pull/4711
