### ISSUE TITLE
CSS like languages like MapCSS

### ISSUE THREAD

**Issue by Skippern** [github/linguist#2159]
MapCSS is an experimental language with a CSS like syntax, with the same purpose as CartoCSS, but a slightly different syntax. Information on the standard can be found at [OpenStreetMap wikipage](https://wiki.openstreetmap.org/wiki/MapCSS/0.2). I don't know if it is similar enough to detect similar as Carto, or if it needs to be different. Normally file extensions are `.mapcss`. I know of a few projects working with MapCSS, mostly as interpreters for map rendering. I also have an experimental [MapCSS syntax highlighter for Xcode6](https://github.com/Skippern/mapcss-xcode-coloring)

**Comment by arfon** [comment]
Thanks for raising this @Skippern. Right now I don't think there are [sufficiently large numbers](https://github.com/search?utf8=%E2%9C%93&q=meta+extension%3Amapcss&type=Code&ref=searchresults) of `.mapcss` files on GitHub to warrant adding support for this (see [contributing.md](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language)).

Please feel free to open a new issue in the future when there are more people using this.
