### ISSUE TITLE
Inconsistent XML detection

### ISSUE THREAD

**Issue by CodingAnarchy** [github/linguist#2166]
My [repository](https://github.com/CodingAnarchy/Amon) has a GUI partially driven by a GLADE XML file.  Sometimes this is detected as XML, but just as often it seems the file is ignored and only the Python code is detected by linguist.

**Comment by pchaigno** [comment]
> Sometimes this is detected as XML, but just as often it seems the file is ignored and only the Python code is detected by linguist.

Since very recently, Linguist counts markup languages like XML in the statistics. Could the inconsistencies happen because some repositories haven't been updated recently? (Language statistics update when you push to the repository.)

**Comment by CodingAnarchy** [comment]
The repository in question was last pushed five days ago. Also, it had been reporting the XML in the statistics, but it ceased to do so with the latest push.

**Comment by pchaigno** [comment]
It's probably normal. There were some big changes recently on the way Linguist handles XML in language statistics. See #2097 ([v4.0.0](https://github.com/github/linguist/pull/2114)) and #2139 ([v4.4.2](https://github.com/github/linguist/pull/2141)) for more information.

**Comment by bkeepers** [comment]
As @pchaigno mentions, #2139 intentionally classified XML as data, which means it won't show up in the language stats bar any more. We appreciate any feedback if this is not ideal.
