### ISSUE TITLE
.dat file extension

### ISSUE THREAD

**Issue by pchaigno** [github/linguist#2169]
There is [more than 3 millions `.dat` files on GitHub](https://github.com/search?utf8=%E2%9C%93&q=extension%3Adat+NOT+dkfgjdkdjkfkqlf&type=Code&ref=searchresults). It is used by many languages. Thus, to add that extension, we need to identify all languages using it (with at least hundreds of examples).

I will update this post with the list of languages as we go. I might eventually turn this issue into a pull request to add support of the extension.

This extension was requested for AMPL in #2073.

**Comment by pchaigno** [comment]
Looks like this extension is mostly used for data files. See for instance [`parser.dat`](https://github.com/procblock/gemrage/blob/ed108dae6af2e248d09cb8db53b5662f197e36e1/gem/vendor/ruby/1.8/gems/json_pure-1.4.6/benchmarks/data-p4-3GHz-ruby18/ParserBenchmarkRails%23parser.dat), [`build-state~.dat`](https://github.com/patproct/Apress-Book/blob/13d950833ec8eb589e3a4dc8fee39926d8638c77/View%20Switcher/build/View%20Switcher.build/Debug-iphonesimulator/View%20Switcher.build/build-state~.dat) or [`funshion.isp.dat`](https://github.com/dongs/IP/blob/5bd78b761cbd41f1c669ed499523ec1c6a30346a/funshion.isp.dat). We don't have a good way currently of detecting these files. So I don't think we can add this extension to any language :/

@vitaut Is this extension really common for AMPL files?

**Comment by vitaut** [comment]
Yes, `.dat` is very common for AMPL files. I think even more common than `.mod` because one model file in AMPL often has multiple data files.

Is it possible to identify files in Linguist based on content? AMPL data files are pretty easy to detect as almost all of them have statements of the form:

```
param <name> := ...
```
or
```
param <name> : ...
```
Detection can be made even more specific than that using more syntax details.

Or, maybe it is possible to define a catch-all "language" like "Data File" for all unidentified `.dat` files? Then real languages that use this extension can still be identified.

**Comment by pchaigno** [comment]
> Is it possible to identify files in Linguist based on content? AMPL data files are pretty easy to detect as almost all of them have statements of the form:

It's possibly to distinguish them from other languages based on content. See [`heuristics.rb`](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.rb) for examples. But in order to do that we would have to have another language to attribute them to.
<br/>

> Or, maybe it is possible to define a catch-all "language" like "Data File" for all unidentified .dat files? 

That's the core of the problem here, imo. We don't have such an option currently but it has been discussed before. The issue #1571 was opened for this.

**Comment by pchaigno** [comment]
I'm going to close this until we get a fallback option (e.g., `data` language) when selecting the language for a file. Without that, recognizing `.dat` files would add to much misclassifications.

**Comment by Alhadis** [comment]
I've fought the urge to post this for days, I can't take it anymore:

<img src="https://cloud.githubusercontent.com/assets/2346707/20976285/280d334c-bcf6-11e6-8635-260513b7120c.jpg" width="400" alt="Three days is pretty good, right?" />
