### ISSUE TITLE
Cython-generated C/C++ files shouldn't make repo C/C++

### ISSUE THREAD

**Issue by kmike** [github/linguist#2172]
Many Python repos are incorrectly marked as C/C++ because of C/C++ extensions generated using Cython.

Some examples:

* https://github.com/scikit-learn/scikit-learn
* https://github.com/piskvorky/gensim
* https://github.com/kmike/psd-tools
* https://github.com/bwhite/hadoopy

Why was https://github.com/github/linguist/pull/354 fix reverted?

**Comment by bkeepers** [comment]
I'm not sure why it was reverted in da515105975f2df3d1fc2c5897e6da85771d5f13.

@tnm do you remember?

**Comment by tnm** [comment]
I don't, but it seems alright to bring back in some form. I'd add in a check on `lines` length as well.

**Comment by arfon** [comment]
#2232 addressed this.
