### ISSUE TITLE
PostScript not recognized?

### ISSUE THREAD

**Issue by hdon** [github/linguist#2182]
Here's a project with PostScript files:

https://github.com/hdon/lua2ps/tree/master

But they are apparently not detected by the "language statistics" feature of GitHub.

Just thought I'd mention it.

**Comment by arfon** [comment]
Looks like this just needed an update to the language statistics. I manually did this for you (this usually happens post-push).

![Uploading Screen Shot 2015-03-01 at 7.23.48 PM.png . . .]()

**Comment by hdon** [comment]
Oh, closed bug report. Okay.

Well, what language statistics were displayed on my project in particular wasn't of very much interest to me.

Maybe, though, there's some reason why the post-push hook for language statistics didn't fire? A bug, perhaps?

**Comment by arfon** [comment]
Closed because it's fixed - sorry if that's not what you expected. 

Also, we've only just started including `markup` in the repo statistics so this would only have started showing in the last few weeks - I only remembered this after closing the issue. Sorry for not adding this info.

**Comment by hdon** [comment]
It's no problem. I just misunderstood. If the bug is fixed, then this should definitely be closed!
