### ISSUE TITLE
Add Web IDL language

### ISSUE THREAD

**Issue by m93a** [github/linguist#2185]
Web IDL is a language invented by W3C, "that can be used to describe interfaces that are intended to be implemented in web browsers" [[ref]](http://www.w3.org/TR/WebIDL/). Its extensions are usually `.webidl` (Mozilla) or `.idl` (Google). Syntax highlighting of Web IDE would be useful for writing web specs on GitHub.

Could you please add it? Thanks :)

**Comment by pchaigno** [comment]
WebIDL is [already recognized by Linguist](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L3228-L3233) with the extension `.webidl`.

> Its extensions are usually .webide (Mozilla).

Did you mean `.webidl`? I can't find any [`.webide` files on GitHub](https://github.com/search?utf8=%E2%9C%93&q=extension%3Awebide+NOT+dckdjfkcxhnwikdsnf&type=Code&ref=searchresults).

>  or .ide (Google).

I found around [12,700 `.ide` files on GitHub](https://github.com/search?p=5&q=extension%3Aide+NOT+dckdjfkcxhnwikdsnf&ref=searchresults&type=Code&utf8=%E2%9C%93) but they don't look like [the WebIDL files we already have](https://github.com/github/linguist/blob/master/samples/WebIDL/Fetch.webidl)...

**Comment by m93a** [comment]
Ah, sorry. It was a typo. I've corrected it now.  
It exists but is not highlighted because there's no ace mode for it. Maybe I should open a new issue in ace's repo and close this one?

**Comment by arfon** [comment]
> It exists but there's no ace mode for it so no code highlighting is available. 

@m93a - this Web IDL file is already syntax-highlighted: https://github.com/github/linguist/blob/master/samples/WebIDL/Fetch.webidl

Are you looking for some other behaviour?

**Comment by m93a** [comment]
Wow, it really works. I must had missed something.
Thanks for your patience, we're closing :)

**Comment by arfon** [comment]
:+1: you're welcome!
