### ISSUE TITLE
*.pro extension is also used for KiCad project files

### ISSUE THREAD

**Issue by Miceuz** [github/linguist#2186]
Now *.pro is recognised as prolog source code.

**Comment by Miceuz** [comment]
Repos in question: 
https://github.com/Miceuz/ultimate-temperature-controller
https://github.com/Miceuz/soil-moisture-sensor-analog

**Comment by thorade** [comment]
QT Creator also uses `*.pro` as extension for its project files.
QT Creator files are easily identified by the first 5 lines of the file (especially line 3):
```
#-------------------------------------------------
#
# Project created by QtCreator 2012-06-06T19:03:23
#
#-------------------------------------------------
```
https://github.com/search?q=%23+Project+created+by+QtCreator&type=Code&utf8=%E2%9C%93

**Comment by pchaigno** [comment]
@Miceuz #2154 fixes this. It was recently merged and should be in the next release.
