### ISSUE TITLE
Google Summer of Code

### ISSUE THREAD

**Issue by bkeepers** [github/linguist#2190]
GitHub has been accepted as a mentoring organization into the [Google Summer of Code](http://www.google-melange.com/gsoc/homepage/google/gsoc2015) program. We will be accepting applications from students to work on features for linguist.

If you are interested, check out the [idea list](https://github.com/github/gsoc#linguist). Student applications can be submitted on March 16-27. Check out the [GSoC 2015](http://www.google-melange.com/gsoc/homepage/google/gsoc2015) website for more information.

**Comment by arfon** [comment]
Closing as the deadline for submission has now passed
