### ISSUE TITLE
jQuery in Sub Folders and .gitattributes does not work

### ISSUE THREAD

**Issue by neurospeech** [github/linguist#2191]
I have a library, it is marked for JavaScript, but all of them are third party libraries, it should ignore jQuery however, https://github.com/neurospeech/iis-ci/search?l=javascript shows that jQuery is still counted in statistics.

Also I have written following .gitattributes
*.js linguist-vendored=false
*.css linguist-vendored=false
*.cshtml linguist-vendored=false

but there is no change, still JavaScript and CSS are indexed, I want to remove all *.js

**Comment by pchaigno** [comment]
> https://github.com/neurospeech/iis-ci/search?l=javascript shows that jQuery is still counted in statistics.

Files appear in the search results even if they are not counted in statistics.
<br/>

> Also I have written following .gitattributes
*.js linguist-vendored=false
*.css linguist-vendored=false
*.cshtml linguist-vendored=false

You should use `linguist-vendored=true` or `linguist-vendored` to mark files as vendored.

**Comment by arfon** [comment]
> but there is no change, still JavaScript and CSS are indexed, I want to remove all *.js

As @pchaigno mentioned, they're still indexed even with `linguist-vendored` but don't show up in the repository statistics.

BTW, you still have one file being counted as `CSS`: `IISCI.Web/Content/Site.less`
