### ISSUE TITLE
.jbuilder extensions are ruby

### ISSUE THREAD

**Issue by wyaeld** [github/linguist#2194]
Rails includes rails/jbuilder by default, and views with name.json.jbuilder extensions are becoming more common.

This is still just ruby though, much like erb.  https://github.com/facelessuser/ApplySyntax just delegates to the ruby bundle under sublime

**Comment by pchaigno** [comment]
Hi @wyaeld!

Is the extension always `.json.jbuilder` or can it be just `.jbuilder`?

**Comment by wyaeld** [comment]
usage is just convention I think.  Rails convention seems to be
.json.jbuilder, but the actual handler registration with sprockets is based
only on .jbuilder, so thats probably more reliable.  I've seen gists from
sinatra projects where they only have .jbuilder on the template

**Comment by pchaigno** [comment]
#2202 should fix this ;)

**Comment by wyaeld** [comment]
excellent, thankyou
