### ISSUE TITLE
Repository code search doesn't match language bar

### ISSUE THREAD

**Issue by larsbrinkhoff** [github/linguist#2199]
This may be the wrong place to report this problem, but it seems related to Linguist.

I created this repository about 24 hours ago:
https://github.com/larsbrinkhoff/color-test

The language bar statistics was updated immediately, but code search only displays C:
https://github.com/larsbrinkhoff/color-test/search?l=c
https://github.com/larsbrinkhoff/color-test/search?l=python

**Comment by pawandeep2155** [comment]
Hello larsbrinkhoff
Linguist has prioritised Languages(see popular.yml in lib/linguist folder of Linguist code ).
I think it searches only the top language and neglects the bottom languages in the search.
And C is at second place after ActionScript so your code would be searched in C Language.
Thank You

**Comment by arfon** [comment]
@larsbrinkhoff - this should be fixed now. Basically you found an edge-case in our search infrastructure where we assume that files with identical contents are, well, identical :smile:. In this case though there were lots of files that had different extensions even though they had identical file contents.

Anyway, as my colleague mentioned in email, this should be fixed now!

**Comment by larsbrinkhoff** [comment]
Thanks!
