### ISSUE TITLE
nginx vhost recognition with sublime-nginx module

### ISSUE THREAD

**Issue by david-rahrer** [github/linguist#2201]
The highlighting is already there, you just haven't extended it to the vhost files. IOW, the nginx.conf file is hightlighted fine. The vhost files are simply separated for convenience but are actually part of nginx.conf - they are added in by an include at the bottom of nginx.conf. So the only thing missing that I can see is that vhost files aren't being highlighted for some reason. Can *.vhost be added to the files associated with this highlighting?

https://github.com/david-rahrer/nginx-wordpress/blob/master/nginx/nginx.conf
https://github.com/david-rahrer/nginx-wordpress/blob/master/nginx/sites-available/example.com.vhost

**Comment by pchaigno** [comment]
Added in #2203.

**Comment by david-rahrer** [comment]
Great, thanks.

**Comment by arfon** [comment]
This was fixed in #2203
