### ISSUE TITLE
Conf/routes file misread as PHP

### ISSUE THREAD

**Issue by hktaylan** [github/linguist#2214]
The routes configuration file for the Play 2 Framework based application is being misread as PHP.

**Comment by bkeepers** [comment]
Hi @hktaylan, can you link to an example in a public repository?

**Comment by hktaylan** [comment]
I made my private project public for this but it's actually showing a lot of languages which aren't related to the project. https://github.com/hktaylan/Vresh/search?l=apacheconf

**Comment by arfon** [comment]
Hi @hktaylan - it looks like this file is being detected incorrectly as it's marked as executable.

Also, if you're looking to ignore/override language detections on your repository then please take a look at the [overrides](https://github.com/github/linguist#overrides) we support.
