### ISSUE TITLE
Multiline Haskell string with empty last line not terminated 

### ISSUE THREAD

**Issue by eallik** [github/linguist#2216]
The below captured snippet compiles perfectly well by GHC but fails to properly syntax highlight.

The syntax highlighter fails to terminate the multiline string literal at `\"`, even though it's perfectly valid in Haskell to end a multiline string with `\"` as the only thing on the last line.

![screen shot 2015-03-09 at 11 04 54](https://cloud.githubusercontent.com/assets/17533/6552224/4ae32f90-c64c-11e4-9126-ac5ef4502cf4.png)

I discovered the bug while reporting [the same bug in Emacs's `haskell-mode`](https://github.com/haskell/haskell-mode/issues/497); I then reported a bug for github/markup and was then redirected to github/linguist; see https://github.com/github/markup/issues/467.

**Comment by pchaigno** [comment]
Same as in github/markup#467, you should report this at [textmate/haskell.tmbundle](https://github.com/textmate/haskell.tmbundle).

**Comment by arfon** [comment]
> you should report this at textmate/haskell.tmbundle (Sorry if I wasn't clear before).

Yeah please report this on https://github.com/textmate/haskell.tmbundle
