### ISSUE TITLE
Add support for syntax: Line Delimited JSON

### ISSUE THREAD

**Issue by stevemao** [github/linguist#2217]
http://jsonlines.org/
http://en.wikipedia.org/wiki/Line_Delimited_JSON

Similar to JSON so it should be easy.

**Comment by pchaigno** [comment]
We will need a few information if we want to add support for those files.
What file extension are they using? Would a JSON grammar be able to highlight them? Shouldn't they just be recognized as JSON?

**Comment by stevemao** [comment]
Sorry I just came across Line Delimited JSON today in my project. From my research it could be `.jsonl`, `.ldjson`, `.ldj` or `.ndjson`. I can't find any standard on this.

I think it's more than enough to use existing JSON grammar. Only difference is one line is one json object and objects are separated by a newline.

They are just JSON. They are used in stream protocols such as TCP.

**Comment by pchaigno** [comment]
So, to add these extensions, we will need to:

0. Find out how many files there are on GitHub for each of these extensions (with a GitHub search).
0. Check that the [current grammar for JSON](https://github.com/textmate/json.tmbundle) can handle those files (it might not like the fact that there is one JSON object per line).

**Comment by stevemao** [comment]
I think you are right.

**Comment by pchaigno** [comment]
- `.ldjson`: [18 files](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aldjson+NOT+ddhfdhfkdhfd)
- `.ldj`: [20 files](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aldj+NOT+ddhfdhfkdhfd&type=Code&ref=searchresults)
- `.jsonl`: [60 files](https://github.com/search?utf8=%E2%9C%93&q=extension%3Ajsonl+NOT+ddhfdhfkdhfd&type=Code&ref=searchresults)
- `.ndjson`: [13 files](https://github.com/search?utf8=%E2%9C%93&q=extension%3Andjson+NOT+ddhfdhfkdhfd&type=Code&ref=searchresults)

As per the [contribution guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language), I'm afraid that none of these file extensions is sufficiently used on GitHub.

**Comment by stevemao** [comment]
In fact, I just want these to be recognised as JSON. Does it count as a new language?

**Comment by pchaigno** [comment]
Yes, this requirement is on the extensions. I agree that the doc is not really clear about that :/

**Comment by arfon** [comment]
> As per the contribution guidelines, I'm afraid that none of these file extensions is sufficiently used on GitHub.

Let's revisit this as adoption increases of these extensions.

**Comment by benatkin** [comment]
This got to the front page of HN today. Mostly positive feedback. https://news.ycombinator.com/item?id=10280483

**Comment by rtsao** [comment]
> * `.ldjson`: [18 files](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aldjson+NOT+ddhfdhfkdhfd)
> * `.ldj`: [20 files](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aldj+NOT+ddhfdhfkdhfd&type=Code&ref=searchresults)
> * `.jsonl`: [60 files](https://github.com/search?utf8=%E2%9C%93&q=extension%3Ajsonl+NOT+ddhfdhfkdhfd&type=Code&ref=searchresults)
> * `.ndjson`: [13 files](https://github.com/search?utf8=%E2%9C%93&q=extension%3Andjson+NOT+ddhfdhfkdhfd&type=Code&ref=searchresults)
> 
> As per the [contribution guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language), I'm afraid that none of these file extensions is sufficiently used on GitHub.

It appears there are now 293K results for `.ndjson`. Is that sufficient usage now?

**Comment by Alhadis** [comment]
`.jsonl` is now a [supported JSON extension](https://github.com/github/linguist/blob/a7854f452bce874e600cac8b24ec948e1d8af6e3/lib/linguist/languages.yml#L2324), and the JSON grammar appears to have no difficulties highlighting them.

Adding an entirely new language for this would, IMHO, be overkill. We added `JSON with comments` as a separate entry only so we could highlight it with a grammar that doesn't mark comments as errors:

~~~json
{
	// This is a comment in a .json file
	"key": "value"
}
~~~

~~~jsonc
{
	// This is a comment in a .jsonc file
	"key": "value"
}
~~~

@rtsao Feel free to submit a pull-request adding `.ndjson` as a new JSON extension. 😉

**Comment by benatkin** [comment]
```jsonl
["is", "this", "supported"]
```

Now would be a good time to either implement it or lock the issue. ;)
