### ISSUE TITLE
Good Approach to contribute in Linguist

### ISSUE THREAD

**Issue by pawandeep2155** [github/linguist#2219]
I want to contribute to Linguist in GSOC 2015 but I don't know how to approach to Linguist.
I have 2 confusions:-

1. Should I read the existing code of Linguist to get familiar with the code or should I improve my existing Ruby language understanding through different sources ?
2. Should I start working on how to implement the ideas in the idea list or should I now work on removing the existing issues in Linguist mentioned in Github?

**Comment by pchaigno** [comment]
> Should I read the existing code of Linguist to get familiar with the code or should I improve my existing Ruby language understanding through different sources ?

I'd say you should go through the Linguist code (it's pretty simple to understand even if you've never written any Ruby code) but that mostly depends on you.

> Should I start working on how to implement the ideas in the idea list or should I now work on removing the existing issues in Linguist mentioned in Github?

The two are often related. The ideas in the list will be needed to truly solve several of the issues currently opened. I think that going through the issues would certainly help you understand the ideas and it's always a good approach to an open source project to solve a few minor issues (it will get you familiar with the code).
