### ISSUE TITLE
Python Django project being misclassified as HTML

### ISSUE THREAD

**Issue by bensnyde** [github/linguist#2220]
https://github.com/bensnyde/django-csa

**Comment by arfon** [comment]
Hey @bensnyde. This is because there are a bunch of [HTML files](https://github.com/bensnyde/django-csa/search?l=html&q=l%3Dhtml&utf8=%E2%9C%93).

You can stop these files being included in the repository statistics by using the [Linguist Overrides](https://github.com/github/linguist#overrides).
