### ISSUE TITLE
Why Language Statistics show Ruby and Shell only?

### ISSUE THREAD

**Issue by pawandeep2155** [github/linguist#2226]
Language Statistics of Linguist shows it is written in 99% in Ruby and 1% in Shell but the sample folder contain code for 267 languages so why it does not show those languages in Language statistics.

**Comment by arfon** [comment]
Hi @pawandeep2155 - Linguist ignores any file paths defined in [this file](https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml)

In this case the `samples` folder is ignored because of this line:
https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml#L210-L211
