### ISSUE TITLE
Syntax Highlight for URL descriptions

### ISSUE THREAD

**Issue by felipenmoura** [github/linguist#2228]
We have to, many times, describe a URL in documentation/wiki/readme/issues, etc.
It's used sometimes to describe services, other times to run scripts in directories or even on how to customise params, etc.
It could be interesting if we could have this kind of highlighting

```
    ```url
        http://server.domain.com/service/task?config.opt1=val&config.opt2=val#top
    ```
```

And this could result in something with different colours for the protocol, characters like "/", ".", "=", "?", "&" and "#". Also colours for "queryVariables", path and hash.

I think the implementation might not be so hard, and could be really useful.

**Comment by pchaigno** [comment]
We could implement that with the hack (add an `URL` language with no extension and define a grammar for it which highlights URLs). I'm not sure it wouldn't break anything and there might be a better solution. An implementation in CommonMark (standard for Markdown) might be a better idea...

@arfon @bkeepers What do you think?

**Comment by arfon** [comment]
I'm sympathetic to this but I really don't think we should be using Linguist in this way sorry.

**Comment by j4hangir** [comment]
But why not? URLs do have a syntax of their own.

I second the idea.
