### ISSUE TITLE
Elisp highlight: escaped quotes are not detected properly

### ISSUE THREAD

**Issue by BasicWolf** [github/linguist#2234]
There is a bug in processing escaped code in Elisp. Consider the following code:

```elisp
    (setq electric-pair-pairs '(
                                (?\{ . ?\})
                                (?\" . ?\")
                                (?\[ . ?\])))
```

As you can see the escaped quote is detected as a beginning of the string, which is wrong in this case. The rest of the highlight gets broken because of this effect.

**Comment by pchaigno** [comment]
@BasicWolf Linguist only selects the grammar to use for highlighting. [textmate/lisp.tmbundle](https://github.com/textmate/lisp.tmbundle) is used to highlight Elisp code on GitHub. You should open an issue there ;)

**Comment by BasicWolf** [comment]
Thanks @pchaigno, I'll open an issue there.
