### ISSUE TITLE
GSoC: Improving language deduction by file-extension

### ISSUE THREAD

**Issue by torpedro** [github/linguist#2235]
Hi everyone!
While looking into some of the issues (especially #2123, but also #2214) I thought about how to improve the language detection based on the file-extension. There are two options that I'd like to get your opinion on (also in the context of GSoC).
First I'd like to be able to give a confidence score to the file-type deduction. By using the probability prediction of a NB-classifier we should get a decent confidence score. Also since the training data is fairly simple (extension -> language) I suspect we should be able to get large amounts of training data to fit the classifier with reasonable complexity.
A second idea I am interested in investigating is using the file-extensions of other files in the folder (or repository) to deduce the language of a file. For #2123 for example I can already see, that the likelihood that a .for file is a data file increases when there are R-scripts or .csv files in the same directory.
What do you think of these approaches? Do you think they make sense to pursue for me as part of the GSoC? (@arfon, @bkeepers)

**Comment by pchaigno** [comment]
> First I'd like to be able to give a confidence score to the file-type deduction. By using the probability prediction of a NB-classifier we should get a decent confidence score.

Linguist is using [several strategies](https://github.com/github/linguist/blob/master/lib/linguist/language.rb#L91-L95) to detect the language of a file. To give an overall confidence score we'll need to be able to give a confidence score per strategy. For the classifier it's relatively easy but for other, such as the `Heuristics` strategy it's more complex.
<br/>

 > Also since the training data is fairly simple (extension -> language) I suspect we should be able to get large amounts of training data to fit the classifier with reasonable complexity.

Could you extend on this? I'm not sure I understand exactly how you propose to do this.
Files that reach the Classifier strategy are files whose extensions match several languages. So for these languages, it's not always possible to find an extension such that `extension -> 1 language`.

Thanks for sharing your opinion and ideas!

**Comment by torpedro** [comment]
Thanks for your reply!
I was thinking about using a separate classifier to correlate file extensions and languages. As far as I know right now linguist first checks what programming languages a file extension is used for and simply returns a list of candidates. My idea focusses on those cases where the file extension might refer to multiple languages. I was thinking about training a classifier on the ```extension -> language``` relationship, so that we can not only return a list of possible languages for an extension but also assign probabilities to the candidates. The result for ```.for``` files might look something like this:  ```[40% FORTRAN, 40% Forth, 20% Text]```.
I am thinking that assigning probablities to the file-extension strategy will be very helpful when trying to integrate multiple strategies into a unified score as suggested in #2195. Later I'd also want to incorporate the other file-extensions within the directory/repository to generate a better extension classifier.

What do you think?

Thanks! Pedro

**Comment by pchaigno** [comment]
> I was thinking about training a classifier on the extension -> language relationship, so that we can not only return a list of possible languages for an extension but also assign probabilities to the candidates.

The [Bayesian classifier](https://github.com/github/linguist/blob/master/lib/linguist/classifier.rb) is doing that. It currently only returns the languages sorted by score without the probabilities. You might want to take a look to that class ;)

**Comment by torpedro** [comment]
Thanks! Maybe I have been looking in the wrong places.
From what I've read in the code the [classifier](https://github.com/github/linguist/blob/master/lib/linguist/classifier.rb#L25-L61) doesn't use the file-extension as an input. What I intended to improve was the [filename strategy](https://github.com/github/linguist/blob/master/lib/linguist/strategy/filename.rb#L16). Where, if I am reading the code correctly, a [list of languages is returned](https://github.com/github/linguist/blob/master/lib/linguist/language.rb#L170-L189) without probabilities. I want to add probabilities to that strategy, so that we can use the results of this strategy more precisely when combining them (#2195).

Thanks! I really appreciate your feedback!

**Comment by pchaigno** [comment]
Oh! I think I understand. But then, how do you propose to compute these probabilities?

**Comment by torpedro** [comment]
This is where I want to build another classifier. This classifier would learn the correlation between file-extension and programming language. From that classifier we would be able to get a probability estimation for the language candidates.

**Comment by pchaigno** [comment]
> This classifier would learn the correlation between file-extension and programming language.

What data would you use to train it?
<br/>

> From that classifier we would be able to get a probability estimation for the language candidates.

I'm not sure we need a confidence score for the `Filename` strategy. If there is only one language returned, we can return an overall confidence score of 1. If there are several languages returned, we will try the following strategies and thus, use one of their confidence score.

**Comment by torpedro** [comment]
> What data would you use to train it?

This is also a big issue that I see. The [samples](https://github.com/github/linguist/tree/master/samples) currently used for classification are probably not sufficient to train a filetype classifier. What I'd want is a real-world sample of repositories. I probably can limit the number of repositories to those that contain file-extensions that are associated with multiple languages. This would involve some manual work on my part.

> If there are several languages returned, we will try the following strategies and thus, use one of their confidence score.

The benefit I see is in combining this strategie's confidence scores with the confidences of the others. I see it as part of the goal for the weighted scoring described in #2195. When combining strategies I think it is beneficial if we know the confidence of each strategy.

**Comment by pchaigno** [comment]
If you want to train your classifier on the content of the training files, I don't see the difference with the Bayesian classifier we already have... :/

**Comment by torpedro** [comment]
Hmm... Alright I'll take a deeper look into the existing classifier. I'll work on defining more clearly where this differs and where see the distinct benefits.

Thanks for discussing this with me! I really appreciate it
