### ISSUE TITLE
Add .odd extension

### ISSUE THREAD

**Issue by joewiz** [github/linguist#2238]
There are [nearly 500 ODD files](https://github.com/search?q=extension%3Aodd+NOT+djfhdirijdskqdhd&type=Code&utf8=%E2%9C%93) in GitHub.  [ODD](http://en.wikipedia.org/wiki/Text_Encoding_Initiative#ODD) is an XML-based vocabulary for defining schemas for Text Encoding Initiative (TEI) projects, used widely in the humanities.  ODD should be rendered using XML syntax but is currently displayed as plain text (see [this example](https://github.com/wolfgangmm/tei-simple-pm/blob/master/odd/teisimple.odd)).  

I would be happy to submit a pull request, but I'm not sure about whether to define .odd as an entry within the [existing XML languages](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L3263) or whether I should submit this as a new language, along the lines of the entry for [XProc](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L3345).  I'm inclined toward the former, but I'd appreciate guidance before I submit the wrong type of pull request.

Thanks in advance.

**Comment by Phase** [comment]
I think you could add it to XML language if they're the same thing.

**Comment by pchaigno** [comment]
You could define it as a new language in Linguist if you wanted it to be counted as a different language (from XML) in the statistics or if you wanted to use a different grammar for highlighting.
XML isn't counted in the statistics anyway, so, in your case, I think you should define it as a new extension.

Though 500 files might not be enough to add it to linguist (@arfon ?).

**Comment by arfon** [comment]
> You could define it as a new language in Linguist if you wanted it to be counted as a different language (from XML) in the statistics or if you wanted to use a different grammar for highlighting. XML isn't counted in the statistics anyway, so, in your case, I think you should define it as a new extension.

Yes, I think we should add this as a new extension to `XML`. @phase - would you mind doing this? You can read our [contributing guidelines here](https://github.com/github/linguist/blob/master/CONTRIBUTING.md)

**Comment by joewiz** [comment]
Sure, will do.  Thanks for your guidance, everyone!
