### ISSUE TITLE
Python docstrings don't get highlighted properly

### ISSUE THREAD

**Issue by erbridge** [github/linguist#2240]
See e.g. https://github.com/cobrateam/splinter/blob/master/splinter/browser.py#L46. Everything between the `"""`s should be quoted.

**Comment by pchaigno** [comment]
@erbridge Linguist only selects the grammar to use for highlighting. [atom/language-python](https://github.com/atom/language-python) is used to highlight Python code on GitHub. You should open an issue there ;)

**Comment by erbridge** [comment]
Got it. Sorry about that.
