### ISSUE TITLE
Detect .svg files

### ISSUE THREAD

**Issue by polybuildr** [github/linguist#2244]
Currently, .svg files are detected as XML (example: https://github.com/zhukov/webogram/search?l=xml) Should they not be treated separately as SVGs?

**Comment by arfon** [comment]
Looks like the search index was outdated here. I now see this [here](https://github.com/zhukov/webogram/search?l=svg&q=l%3Dsvg&utf8=%E2%9C%93):

![screen shot 2015-03-19 at 3 14 35 pm](https://cloud.githubusercontent.com/assets/4483/6739991/b565cbc4-ce4a-11e4-84d1-5fae47e8bab9.png)

Please note though, `SVG` is considered `data` by Linguist and so won't contribute to language statistics for the repository.
