### ISSUE TITLE
RPGLE Syntax Highlighting

### ISSUE THREAD

**Issue by WorksOfBarry** [github/linguist#2245]
It's not really in-demand, but I feel that it will eventually make it's appearance in the open-source community.

Is there any way we could possibly get some syntax highlighting for this language?

You can find a spec/reference for the language [here](http://publib.boulder.ibm.com/iseries/v5r1/ic2924/books/c0925083.pdf), which may be a good starting point.

Regards,
Liam

**Comment by arfon** [comment]
Hi @WorksOfBarry. I'm not very familiar with RPGLE but you can see read our policy [here](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) on adding new languages to Linguist (and therefore GitHub.com).

We'd first need to establish that people are working in RPGLE by searching for files on GitHub. Can you tell me what common file extensions are?

For syntax highlighting we'd then need to find a Textmate bundle or Sublime grammar for RPGLE.

**Comment by WorksOfBarry** [comment]
Common extensions can be either .RPGLE or .SQLRPGLE - but both share the exact same syntax.

**Comment by arfon** [comment]
So I can find some of these files - there look to be ~900 or so:

https://github.com/search?utf8=%E2%9C%93&q=define+OR+eval+OR+include+OR+if+extension%3Arpgle+&type=Code&ref=searchresults

> For syntax highlighting we'd then need to find a Textmate bundle or Sublime grammar for RPGLE.

@WorksOfBarry - next steps here would be to find a suitable grammar for highlighting. You can read how to do that here: https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language

**Comment by arfon** [comment]
Please consider opening a Pull Request to add support for RPGLE.
