### ISSUE TITLE
Require 'linguist' throwing error

### ISSUE THREAD

**Issue by pawandeep2155** [github/linguist#2248]
I read on the page https://github.com/github/linguist
about how to use classifier after installing gem , $ gem install github-linguist
But when I use it as :

![screen shot 2015-03-20 at 6 28 13 pm](https://cloud.githubusercontent.com/assets/7972666/6751840/d7f76cc6-cf2e-11e4-8887-15677a471c89.png)

It shows me the following error:

![screen shot 2015-03-20 at 6 28 50 pm](https://cloud.githubusercontent.com/assets/7972666/6751836/d149bf46-cf2e-11e4-80c1-d6bc5d48f164.png)

**Comment by arfon** [comment]
@pawandeep2155 -  it looks like Linguist isn't installed. Can you tell me what you see when you type:

`gem list`

**Comment by pawandeep2155** [comment]
I did gem list and its showing :- github-linguist (4.5.2)
Now when I am using linguist in my file as:-

![screen shot 2015-03-23 at 11 47 13 am](https://cloud.githubusercontent.com/assets/7972666/6775114/582192c6-d152-11e4-9442-4e93c16423ce.png)

It is showing this error:-

![screen shot 2015-03-23 at 11 46 52 am](https://cloud.githubusercontent.com/assets/7972666/6775121/70b451ca-d152-11e4-873e-a33630b641aa.png)

**Comment by arfon** [comment]
Hi @pawandeep2155 - looks like you've got an issue with Rugged here. Have you tried searching online with this error?

**Comment by pawandeep2155** [comment]
Sorry for late reply,
I am using Mac and I even tried running Linguist on my friend computer running Ubuntu, it is also showing the same error. 
I searched it but could not find any answer . 
This is what I am doing :-
1. Getting Linguist gem 
    $ gem install github-linguist
2. Created a ruby file 
3. Wrote the code shown in above image
4. Throwing the error shown in above image
What am I doing wrong here??

**Comment by arfon** [comment]
Hi @pawandeep2155 - this looks like an issue with Rugged. I'd recommend filing an issue over there: https://github.com/libgit2/rugged
