### ISSUE TITLE
Can't run tests locally

### ISSUE THREAD

**Issue by larsbrinkhoff** [github/linguist#2249]
I get a failure runnnig `bundle exec rake test`

I'm guessing my copy of `npm` may be too old or something, but my node-foo is weak.

    npm ERR! Couldn't read dependencies.
    npm ERR! Error: No 'name' field found in package.json
    npm ERR!     at /usr/share/npm/lib/utils/read-json.js:253:13
    npm ERR!     at /usr/share/npm/lib/utils/read-json.js:166:33
    npm ERR!     at P (/usr/share/npm/lib/utils/read-json.js:142:41)
    npm ERR!     at /usr/share/npm/lib/utils/read-json.js:108:7
    npm ERR!     at [object Object].<anonymous> (fs.js:115:5)
    npm ERR!     at [object Object].emit (events.js:64:17)
    npm ERR!     at afterRead (fs.js:1117:12)
    npm ERR!     at Object.wrapper [as oncomplete] (fs.js:254:17)
    npm ERR! You may report this log at:
    npm ERR!     <http://bugs.debian.org/npm>
    npm ERR! or use
    npm ERR!     reportbug --attach /home/lars/src/linguist/npm-debug.log npm
    npm ERR!
    npm ERR! System Linux 3.2.0-70-generic
    npm ERR! command "node" "/usr/bin/npm" "install"
    npm ERR! cwd /home/lars/src/linguist
    npm ERR! node -v v0.6.12
    npm ERR! npm -v 1.1.4
    npm ERR! message No 'name' field found in package.json
    npm ERR!
    npm ERR! Additional logging details can be found in:
    npm ERR!     /home/lars/src/linguist/npm-debug.log
    npm not ok

Contents of `npm-debug.log`:

    info it worked if it ends with ok
    verbose cli [ 'node', '/usr/bin/npm', 'install' ]
    info using npm@1.1.4
    info using node@v0.6.12
    verbose config file /home/lars/.npmrc
    verbose config file /usr/etc/npmrc
    verbose config file /usr/share/npm/npmrc
    ERR! Couldn't read dependencies.
    ERR! Error: No 'name' field found in package.json
    ERR!     at /usr/share/npm/lib/utils/read-json.js:253:13
    ERR!     at /usr/share/npm/lib/utils/read-json.js:166:33
    ERR!     at P (/usr/share/npm/lib/utils/read-json.js:142:41)
    ERR!     at /usr/share/npm/lib/utils/read-json.js:108:7
    ERR!     at [object Object].<anonymous> (fs.js:115:5)
    ERR!     at [object Object].emit (events.js:64:17)
    ERR!     at afterRead (fs.js:1117:12)
    ERR!     at Object.wrapper [as oncomplete] (fs.js:254:17)
    ERR! You may report this log at:
    ERR!     <http://bugs.debian.org/npm>
    ERR! or use
    ERR!     reportbug --attach /home/lars/src/linguist/npm-debug.log npm
    ERR!
    ERR! System Linux 3.2.0-70-generic
    ERR! command "node" "/usr/bin/npm" "install"
    ERR! cwd /home/lars/src/linguist
    ERR! node -v v0.6.12
    ERR! npm -v 1.1.4
    ERR! message No 'name' field found in package.json
    verbose exit [ 1, true ]

**Comment by larsbrinkhoff** [comment]
cc @aroben

**Comment by aroben** [comment]
I just did a fresh clone, bootstrap, and test run, and it all worked fine, so there probably is some difference in our environments causing the problem.

Does the problem go away if you add a `name` field to `package.json`?

**Comment by pchaigno** [comment]
I had the same issue some time ago on a fresh clone. I'll try to reproduce.

> Does the problem go away if you add a name field to package.json?

From what I remember, there was a new error after adding a `name` field.

**Comment by larsbrinkhoff** [comment]
Right, I added `name`.  Then `version` was requected, so I added that too.  (These two seem required, by the way.)

Now I get 
    npm http GET https://registry.npmjs.org/season
    npm ERR! Error: failed to fetch from registry: season

This is in the log file:
    silly cache add: name, spec, args [ undefined, 'season@~>5.0', [ 'season@~>5.0'\
, null ] ]
    verbose parsed url { pathname: 'season@~', path: 'season@~', href: 'season@~' }
    silly cache add: name, spec, args [ 'season', '~>5.0', [ 'season', '~>5.0' ] ]
    verbose parsed url { pathname: '~', path: '~', href: '~' }

**Comment by aroben** [comment]
My guess is that your npm is too old to handle the `~>5.0` version specifier we're using. Interestingly, that syntax isn't mentioned on https://docs.npmjs.com/files/package.json#dependencies so maybe we should change it to something like `>=5.0 <6.0`.

**Comment by pchaigno** [comment]
> My guess is that your npm is too old to handle the ~>5.0 version specifier we're using.

That's probably the reason: the issue is happening for me with npm 1.1.4... I'll try to update.

**Comment by larsbrinkhoff** [comment]
Fresh clone + npm 2.5.1:

     # Running:

     ..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................E.EEE...E..........This method will be deprecated in a future 5.x release. Every language now has an `ace_mode` set.
     This method will be deprecated in a future 5.x release. Every language now has an `ace_mode` set.
     ..................................................................................

     Finished in 38.632538s, 21.3033 runs/s, 258.9527 assertions/s.

       1) Error:
     TestRepository#test_linguist_override_documentation?:
     Rugged::OdbError: Object not found - failed to find pack entry (d4c8fb8a28e91f97a7e53428a365c0abbac36d3d)
         /home/lars/src/linguist/lib/linguist/repository.rb:125:in `lookup'
         /home/lars/src/linguist/lib/linguist/repository.rb:125:in `current_tree'
         /home/lars/src/linguist/lib/linguist/repository.rb:120:in `read_index'
         /home/lars/src/linguist/test/test_repository.rb:105:in `test_linguist_override_documentation?'


       2) Error:
     TestRepository#test_repo_git_attributes:
     Rugged::OdbError: Object not found - failed to find pack entry (351c1cc8fd57340839bdb400d7812332af80e9bd)

       3) Error:
     TestRepository#test_linguist_override_vendored?:
     Rugged::OdbError: Object not found - failed to find pack entry (351c1cc8fd57340839bdb400d7812332af80e9bd)

       4) Error:
     TestRepository#test_linguist_override_unvendored?:
     Rugged::OdbError: Object not found - failed to find pack entry (351c1cc8fd57340839bdb400d7812332af80e9bd)

       5) Error:
     TestRepository#test_commit_with_git_attributes_data:
     Rugged::OdbError: Object not found - failed to find pack entry (7ee006cbcb2d7261f9e648510a684ee9ac64126b)

**Comment by pchaigno** [comment]
@larsbrinkhoff I had this issue a few times - If I remember correctly, you need to install rugged (`gem install rugged`).

**Comment by larsbrinkhoff** [comment]
Thanks!  I tried that; still same errors.

**Comment by larsbrinkhoff** [comment]
Old clone + node v0.12.0 + npm 2.5.1: success!

Apparently something in my old Linguist clone worked better than the new clone.  So my immediate problem seems to be solved.  But it's still a bit of a mystery what I would need to do to get this working again.

**Comment by pchaigno** [comment]
I managed to reproduce the last error on a new clone.
It disappeared when I did:
```
$ git remote add upstream https://github.com/github/linguist
$ git fetch upstream
```

**Comment by larsbrinkhoff** [comment]
Confirmed!  That fixes the errors.  Thanks!

**Comment by larsbrinkhoff** [comment]
Though I wonder why.

**Comment by pchaigno** [comment]
@larsbrinkhoff It's because [the commits used in `test_repository.rb`](https://github.com/github/linguist/blob/master/test/test_repository.rb#L104) are on the [test/attributes branch](https://github.com/github/linguist/commit/d4c8fb8a28e91f97a7e53428a365c0abbac36d3d).

**Comment by arfon** [comment]
> @larsbrinkhoff It's because the commits used in test_repository.rb are on the test/attributes branch.

Oh yeah. Sorry about that weirdness...

**Comment by larsbrinkhoff** [comment]
Ok, cool!
