### ISSUE TITLE
What is the use of Sample folder in Linguist

### ISSUE THREAD

**Issue by pawandeep2155** [github/linguist#2252]
I think sample folder has nothing to do with the Linguist code. It is just for basic understanding of that language for the developer. Is it like this or does it have any role to play in Linguist.

**Comment by pchaigno** [comment]
It's used for tests and to train the Bayesian classifier: https://github.com/github/linguist/search?p=2&q=samples+-path%3Asamples&type=Code&utf8=%E2%9C%93
