### ISSUE TITLE
text8 corpus misclassified as Perl

### ISSUE THREAD

**Issue by Shashwat986** [github/linguist#2258]
Hi, so in my repository: https://github.com/Shashwat986/WTM-IITKanpur
I have had to manually classify text8 as linguist-documentation to get the repo detected as Python. It seems that linguist detects the text8 corpus as perl for some reason.

Considering that text8 is an english language text corpus, I thought I should report this as a possible bug.

Cheers,
Shashwat.

**Comment by pchaigno** [comment]
This is happening because the text8 file in your repository is executable.
