### ISSUE TITLE
Elixir mix.lock file misidentified as JSON

### ISSUE THREAD

**Issue by lpil** [github/linguist#2260]
https://github.com/lpil/elixre/blob/ddabcb13a3242f855781e0b8d920f3a8b985f10f/mix.lock

It does look rather JSON-y, but it's just an Elixir file with a map literal in it. [link](http://elixir-lang.org/getting-started/maps-and-dicts.html#maps)

**Comment by pchaigno** [comment]
@lpil Is `.lock` a standard file extension for Elixir?

**Comment by lpil** [comment]
No, this file is specifically generated by the standard build tool, mix. It's like ruby's `Gemfile.lock`- it's programatically generated, is always called `mix.lock`, and resides in the same directory as `mix.exs`. :)

**Comment by larsbrinkhoff** [comment]
Shouldn't built files generally be `.gitignore`d?

**Comment by pchaigno** [comment]
@lpil Do you want to add it as a filename for Elixir (see [`Gemfile.lock` in `languages.yml`](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L2728) for an example)?

**Comment by lpil** [comment]
AH, so that's how you do it. Thanks @pchaigno , I'll make a pull request.
