### ISSUE TITLE
What if any strategy out of 3 detects different language than the other

### ISSUE THREAD

**Issue by pawandeep2155** [github/linguist#2271]
I know this could be a stupid question but I have this confusion 
As https://github.com/github/gsoc says:
" Linguist currently uses multiple strategies to detect the language of a file, including matching on file name, heuristics, and bayesian classification. "
What if one strategy detects any file as of one language and other strategy detects it as another language.

**Comment by pchaigno** [comment]
You should take a look at [this method in `language.rb`](https://github.com/github/linguist/blob/master/lib/linguist/language.rb#L104-L133). Each strategy is tried in a fixed order and it stops when one of them returns only one matching language.

**Comment by arfon** [comment]
> Each strategy is tried in a fixed order and it stops when one of them returns only one matching language.

:+1:
