### ISSUE TITLE
CSS , Javascript, PHP in HTML file detected as HTML only 

### ISSUE THREAD

**Issue by pawandeep2155** [github/linguist#2273]
I created a sample Repository 
https://github.com/pawandeep2155/SampleHTMLJavascript

How linguist detects a language in another language because I can make html file with css, javascript, php etc in it. Linguist is only detecting html only due to its html file extension.

**Comment by arfon** [comment]
This is because Linguist works on a per-file basis. We don't try and calculate language statistics _within_ a file.
