### ISSUE TITLE
Add list of valid (or relevant) language identifier keywords for GFM syntax highlighting

### ISSUE THREAD

**Issue by jmm** [github/linguist#2278]
I created this [list of language keywords](https://github.com/jmm/gfm-lang-ids/wiki/GitHub-Flavored-Markdown-%28GFM%29-language-IDs) for enabling syntax highlighting and asked GitHub support to consider linking to it from the [GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/) page. People who post issues without even marking up code are not going to be able to figure out the YAML file it currently refers them to. And for that matter, I don't know how anyone is supposed to understand it since there's no explanation of what values from it are relevant.

@gjtorikian advised me to submit a request to integrate that content into this repo.

I wrote a [node program](https://github.com/jmm/gfm-lang-ids) (it's pretty quick and dirty) to automatically generate the document from the `languages.yml` file. I made the document a wiki so that there would be a fallback in case it needed updating and I was unavailable. With the content in this repo it might make more sense to just check it in, to encourage updating it by running a script.

I looked around for a while and then gave up on figuring out where the logic is that defines the valid values. My theory is that it works like this (at least in part):

Any of the following (case-insensitive, with or without a `.` prepended) can be used as the keyword:
- top level key, with spaces replaced by hyphens
- `aliases` values that don't contain spaces
- `extensions` values

That's how I believe it works so that's how I wrote my script, but frankly I think the document it creates is massive overkill. Take JavaScript for example. My script generates the following list of keywords to enable JS highlighting:
- `_js`
- `bones`
- `es6`
- `frag`
- `gs`
- `jake`
- `javascript`
- `js`
- `jsb`
- `jsfl`
- `jsm`
- `jss`
- `jsx`
- `njs`
- `node`
- `pac`
- `sjs`
- `ssjs`
- `sublime-build`
- `sublime-commands`
- `sublime-completions`
- `sublime-keymap`
- `sublime-macro`
- `sublime-menu`
- `sublime-mousemap`
- `sublime-project`
- `sublime-settings`
- `sublime-theme`
- `sublime-workspace`
- `sublime_metrics`
- `sublime_session`
- `xsjs`
- `xsjslib`

For the purposes of enabling syntax highlighting in GFM I think there should just be `js` (_maybe_ also `javascript`). It's probably too late to not support the others, but I think only 1 or 2 are relevant to include in a general reference list. The only value I can imagine in including the others is to leave the door open to provide more specific highlighting for them in the future.

**Comment by jmm** [comment]
Another thing worth keeping in mind is that npm renders GFM fenced code blocks with syntax highlighting in `readme` files. I got sick of trying to trace the logic for where that gets the language keywords from, but I got far enough to form the opinion that it's probably not working from the same list as on GitHub. I used [one of my `readme`'s](https://www.npmjs.com/package/pathmodify) as a guinea pig and I can observe the following:

Enables syntax highlighting:
* `js`

  ```js
  var x = "X";
  ```

  
* `javascript`
  ```javascript
  var x = "X";
  ```

Does not:
* `es6`

  ```es6
  var x = "X";
  ```

* `JS`
  ```JS
  var x = "X";
  ```

* `JAVAscript`

  ```JAVAscript
  var x = "X";
  ```

* `Js`

  ```Js
  var x = "X";
  ```

* `jS`
  ```jS
  var x = "X";
  ```

As you can see, they all enable highlighting here.

**Comment by gjtorikian** [comment]
I don't think I'm exactly giving trade secrets away, but the way we do highlighting is a simple:

``` ruby
Linguist::Language[lang_name] || Linguist::Language.find_by_extension(lang_name).first
```

I'm assigning this to myself as part of a documentation effort for this project.

**Comment by arfon** [comment]
@gjtorikian - what do you think is the best way to proceed here? I closed #2353 as it seemed that no-one was working on this but I'm definitely sympathetic to @jmm's goals here.

@jmm - It's not clear to me that this repo/project is the correct place for this documentation.

**Comment by gjtorikian** [comment]
I think we should probably list _somewhere_—maybe the README?—the key quote in #2353:

>  Generally speaking, the slugified version of a language name, as well as any of its extensions, defined the language code.

If we could automate the generation of the language codes, that'd be cool. We could also just link to @jmm's list: https://github.com/jmm/gfm-lang-ids/wiki/GitHub-Flavored-Markdown-(GFM)-language-IDs

**Comment by pchaigno** [comment]
Although it doesn't include the complete list of keywords, this will be covered by the new FAQ at #4271.

**Comment by waldyrious** [comment]
> Although it doesn't include the complete list of keywords

@pchaigno IMO having a **complete** list in a human-readable format would be important to consider this issue resolved.

**Comment by pchaigno** [comment]
@waldyrious With the FAQ, you'll have [the rules to determine the list of keywords for a given language](https://github.com/github/linguist/blob/22cd80721eb3984c740225dcafea5440a6405c82/FAQ.md#what-keywords-can-i-use-to-highlight-a-code-snippet-in-markdown). When is that not sufficient?

**Comment by waldyrious** [comment]
Even without the FAQ, the data in the yaml file (including the comments at the top), not to mention the code itself, already allowed people to figure out the exhaustive list of valid identifiers, with more or less work. The FAQ improves the situation, but only to an extent.

Especially in the context of the [help page](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting), I'd say it would make more sense to provide a plain list that people could use to look up valid keys, search for a specific identifier, etc., than offer a machine-readable file plus rules to interpret it. That's certainly sufficient, but it seems fair to say that most people would not find it very convenient.

**Comment by pchaigno** [comment]
@lildude If we write a script to generate the list of identifiers for each language, would it be possible to include it (or link to it) in [the help page](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting)?

**Comment by lildude** [comment]
> If we write a script to generate the list of identifiers for each language, would it be possible to include it (or link to it) in [the help page](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting)?

Link? Probably, yes, though I'd need to pass it through our docs team first. Include? Probably not as the churn rate would be too high for our docs team to keep on top of it and I certainly don't want to be manually updating docs each time I make a release 😁 .
