### ISSUE TITLE
My server is not worning due to postgres changes

### ISSUE THREAD

**Issue by SanjayYadav90** [github/linguist#2281]
I have Rails 4.1 along with ruby 2.1.1 DB = Postgres Server = Digital Ocean

Last hour I had made changes in 
/etc/postgresql/9.3/main/postgresql.conf

then i open config file by using sudo nano postgresql.conf so that i can make change in it
 I make change as
#listen_addresses = 'localhost' 
to
listen_addresses = '*'  

  GNU nano 2.2.6                                  File: postgresql.conf                                                                           

# The default values of these variables are driven from the -D command-line
# option or PGDATA environment variable, represented here as ConfigDir.

data_directory = '/var/lib/postgresql/9.3/main'         # use data in another directory
                                        # (change requires restart)
hba_file = '/etc/postgresql/9.3/main/pg_hba.conf'       # host-based authentication file
                                        # (change requires restart)
ident_file = '/etc/postgresql/9.3/main/pg_ident.conf'   # ident configuration file
                                        # (change requires restart)

# If external_pid_file is not explicitly set, no extra PID file is written.
external_pid_file = '/var/run/postgresql/9.3-main.pid'                  # write an extra PID file
                                        # (change requires restart)

#------------------------------------------------------------------------------
# CONNECTIONS AND AUTHENTICATION
#------------------------------------------------------------------------------

# - Connection Settings -

#listen_addresses = 'localhost'         # what IP address(es) to listen on;
                                        # comma-separated list of addresses;
                                        # defaults to 'localhost'; use '*' for all
                                        # (change requires restart)
port = 5432                             # (change requires restart)
max_connections = 100                   # (change requires restart)

(so that i can access my DB on local)
then i restart Postgres by

invoke-rc.d postgresql restart

as soon as I restart My server get dead.
Can anyone suggest me idea!!?????

Although I have Revert back my changes and again restart the postgres but still issue is remain same.

**Comment by arfon** [comment]
Wrong repo sorry.
