### ISSUE TITLE
Perl "cpanfile" wrongly identified as JavaScript

### ISSUE THREAD

**Issue by mjemmeson** [github/linguist#2282]
A "cpanfile" is a fairly recent but increasingly common format for specifying Perl dependencies, the file itself is valid Perl and parsed as such. The files are always named "cpanfile" and placed in the root of a Perl repo.

I think it should be able to match on filename, since "cpan" is short for "Comprehensive Perl Archive Network", and unlikely to be used elsewhere?

Pull request to follow, once criteria in Contributing doc have been met.

thanks,
Michael

**Comment by pchaigno** [comment]
> Pull request to follow, once criteria in Contributing doc have been met.

What are you missing? Do you need help?

**Comment by mjemmeson** [comment]
> What are you missing?

Time! Created issue to have a record of it because otherwise I'd probably forget. Will aim to do PR next week and look for any other Perl related files misclassified at the same time.

thanks,
Michael

**Comment by pchaigno** [comment]
Okay, great ;)

**Comment by arfon** [comment]
:flags: flagging this as stale :flags:
