### ISSUE TITLE
Javascript: Anonymous functions are not 

### ISSUE THREAD

**Issue by caiotoon** [github/linguist#2284]
Anonymous functions are not tokenized properly, as you can see by the following image:

![screen shot 2015-03-29 at 11 47 32 am](https://cloud.githubusercontent.com/assets/350165/6886382/ad367d24-d609-11e4-8a80-797c61b18f96.png)

**Comment by pchaigno** [comment]
@caiotoon Linguist only selects the grammar to use for highlighting. atom/language-javascript is used to highlight JavaScript code on GitHub. You should open an issue there ;)

**Comment by caiotoon** [comment]
Hi @pchaigno. I already submitted a PR for them and opened a issue here to let you guys know once it gets approved as instructed by email.

**Comment by pchaigno** [comment]
> I already submitted a PR for them

:+1: I missed that.

> opened a issue here to let you guys know once it gets approved as instructed by email.

Submodules are now all updated with each new release of Linguist. Looks like the documentation on this (last line of [Fixing syntax highlighting](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#fixing-syntax-highlighting)) is outdated :/
@arfon @bkeepers Should I open a pull request to update the [contribution guidelines]()?

**Comment by arfon** [comment]
> @arfon @bkeepers Should I open a pull request to update the contribution guidelines?

Yes please (and sorry about that)
