### ISSUE TITLE
Shell highlighting single quotes is wrong.

### ISSUE THREAD

**Issue by phase** [github/linguist#2285]
When highlighting shell code with `'` in it, the highlighter goes bananas. [As seen here.](https://github.com/lukkit/Lukkit/blob/master/lukkit#L12-25)

```shell
lukkit_help(){
    echo Lukkit
    echo Available Commands:
    command -v column >/dev/null 2>&1 && cmd="column -t -s -" || cmd=cat
    $cmd <<<'
    lukkit init        | Initialize Lukkit
    lukkit patch apply | Apply patches to build/
    lukkit patch build | Build patches from build/'
}

lukkit_init(){
    git submodule update --init
    cp -a indirect/Bukkit build/Bukkit
    cp -a indirect/CraftBukkit build/CraftBukkit
    lukkit_patch_apply
}

lukkit_patch(){
    echo "Use: 'lukkit patch [apply|build]
    exit 1
}
```

**Comment by pchaigno** [comment]
@phase Linguist only selects the grammar to use for highlighting. [atom/language-shellscript](https://github.com/atom/language-shellscript) is used to highlight Shell code on GitHub. You should open an issue there ;)

**Comment by phase** [comment]
@pchaigno Ah! The more you know!
