### ISSUE TITLE
100% Newlisp file without extension being incorrectly recognized as Perl script

### ISSUE THREAD

**Issue by fernandocanizo** [github/linguist#2287]
Sample file:
https://github.com/fernandocanizo/newlisp-webscraps/search?l=perl

It doesn't has extension but has shebang line:

```
#!/usr/bin/env newlisp
```

**Comment by larsbrinkhoff** [comment]
I'm not part of GitHub staff, but I took a look at this.

When I run the current version of Linuguist against your repository it report 100% `NewLisp`.  

Language statistics are only updated after a push to the repo, which was almost two years ago.  So if you update any file, the statistics should get refreshed.

**Comment by arfon** [comment]
:+1: @larsbrinkhoff 

I just manually re-indexed the project and it's now showing as 100% `NewLisp`
