### ISSUE TITLE
Classification for BASIC source code

### ISSUE THREAD

**Issue by DTJF** [github/linguist#2288]
Linguist obviously clasifies all source files with suffix .bas as viasul basic. This is an old dialect. Currently there's no way to differentiate modern stuff from that deprecated class. 

I'd like to have at least a general class BASIC (not related to any compiler manufacturer), or preferably several classes for the different BASIC dialects (PureBASIC, SmallBASIC, FreeBASIC, ...).

**Comment by pchaigno** [comment]
So, all these languages (VisualBasic, PureBasic, SmallBasic and FreeBasic) use the same extension (`.bas`) but have different syntaxes?

**Comment by arfon** [comment]
Also, @DTJF - is this a syntax-highlighting issue (i.e. are some files being poorly handled) or you'd just rather see the language statistics bar reporting the different dialects?

**Comment by DTJF** [comment]
Yes, all dialects use (.bas) extension (as far as I know).

It's not only a question of syntax highlighting. My main concerns are about searching a project. A user who is looking for modern stuff gets lots of irrelevant links listed. Or a user who excludes this proprietary dialect in his search won't find my projects.

**Comment by pchaigno** [comment]
Thanks for the clarification @DTJF!

We could define each dialect as a separated language in Linguist. But, in order to do that, we'll have to find a way to distinguish them. Can you think of keywords (or construction) that can be found in one dialect and not the others? Also, do you have examples (a repository for instance) of these dialects on GitHub?

**Comment by larsbrinkhoff** [comment]
`languages.yml` already identifies these dialecs: BlitzBasic, PureBasic, REALbasic, and Visual Basic, along with assorted file extensions.

I guess one issue is that `.bas` is currently taken by Visual Basic, but actually it's used for any generic BASIC code.

**Comment by DTJF** [comment]
Sorry, I don't know all those dialects. And I thinks it's not the best idea to distunguish between them by searching for keywords in the source code, since the relevant keywords may not be used.

What about

- classifying all projects with .bas extension as BASIC, and
- searching the ReadMe.md file for keywords like FreeBASIC, PureBasic, ... for further subclassification?

**Comment by arfon** [comment]
OK so it sounds like we should look at adding `SmallBASIC` if we can find a search that can demonstrate significant usage on GitHub.

> - searching the ReadMe.md file for keywords like FreeBASIC, PureBasic, ... for further subclassification?

Unfortunately Linguist works on a per-file basis and so it's not possible to construct classification strategies like this.

@DTJF - is there somewhere we can read up on the syntaxes for the different flavours?

**Comment by DTJF** [comment]
*Linguist works on a per-file basis and so it's not possible to construct classification strategies like this.*
OK. But how gets the complete project specified?

I see no chance to distinguish the flavours by syntax. Ie. FreeBASIC itself has [several dialects](http://www.freebasic.net/wiki/wikka.php?wakka=KeyPgPplang). There's no difference in a source code in dialect `#LANG "QB"` to a quick basic source code. The preprocessor `#LANG "..."` may be an indicator for FreeBASIC code, but it's optional.

What about searching the source for a special comment, ie. like

`GitHubClass=FreeBASIC`

**Comment by arfon** [comment]
> OK. But how gets the complete project specified?

> What about searching the source for a special comment, ie. like

We have overrides that you can use to set the language manually but the language needs to be defined in `languages.yml` for these to work. https://github.com/github/linguist#overrides

**Comment by DTJF** [comment]
Overrides look good. So
~~~
$ cat .gitattributes
*.bas linguist-language=FreeBASIC
~~~
would do the job for the source files (after you added FreeBASIC to `languages.yml`)?

What about the project classification?

**Comment by arfon** [comment]
> would do the job for the source files (after you added FreeBASIC to languages.yml)?

Correct. 

> What about the project classification?

I'm not sure I understand your question sorry. Could you clarify what you mean here?

**Comment by DTJF** [comment]
So please add FreeBASIC to `languages.yml`. The extensions are `*.bas` and `*.bi`. Does that need two lines in `.gitattributes` or can I list more than one extension like
~~~
*.bas;*.bi linguist-language=FreeBASIC
~~~~

*Could you clarify what you mean here?*
In [this overview](https://github.com/DTJF?tab=repositories) each project is classified. In case of FBeauty and fb_prussdrv the classification should be FreeBASIC.

**Comment by arfon** [comment]
> Does that need two lines in .gitattributes or can I list more than one extension like

Two lines will be need for this.

> So please add FreeBASIC to languages.yml.

@DTJF we can definitely add `.bi` as this doesn't clash with any other languages but before we can add `.bas` we'll need to work out how to disabiguate it from `Visual Basic` which defines it [here](https://github.com/github/linguist/blob/a0fb54fe705c3433f790f2a8da476d39aaf57f66/lib/linguist/languages.yml#L3269).

> In this overview each project is classified. In case of FBeauty and fb_prussdrv the classification should be FreeBASIC.

Ah OK. Yes, once we've added support for for FreeBASIC then provided you have the override then this will show the correct language.

**Comment by DTJF** [comment]
>  but before we can add .bas we'll need to work out how to disabiguate it from Visual Basic which defines it here.

Sorry, now I need clarification. When the extension `*.bas` gets overriden by `.gitattributes`, why do you need disambiguation?

What about using only `*.bi` in `languages.yml` for auto detection? And extension '*.bas' gets handled by the overrides?

**Comment by arfon** [comment]
> Sorry, now I need clarification. When the extension *.bas gets overriden by .gitattributes, why do you need disambiguation?

If we add `.bas` to `FreeBASIC` then this will mean that some things that are `Visual Basic` will start getting classified as `FreeBASIC`.

Linguist has a number of [strategies it uses](https://github.com/github/linguist/blob/a0fb54fe705c3433f790f2a8da476d39aaf57f66/lib/linguist/language.rb#L90-L96) to try and determine the language of a file and so if the file extension isn't unique then it will fall back to the other methods (such as heuristics, Bayesian classifier etc).

 > What about using only *.bi in languages.yml for auto detection? And extension '*.bas' gets handled by the overrides?

That would work but it's far from ideal as now people will _have to_ us the overrides for their `.bas` files to be identified as `FreeBASIC`. It would be much better for the `FreeBASIC` community if we could find some heuristics to automatically classify the different types of `BASIC`.

**Comment by DTJF** [comment]
> That would work but it's far from ideal as now people will have to us the overrides for their .bas files to be identified as FreeBASIC. It would be much better for the FreeBASIC community if we could find some heuristics to automatically classify the different types of BASIC.

Currently the FreeBASIC community has no classification at all. So a must-override would be a great step forward :-)

Anyway, I try to find a strategy.

**Comment by DTJF** [comment]
I checked some VB source code and found keywords only in camel case. FreeBASIC keywords (more than 400) are non-case-sensitve, capital letters could be used as disambiguation. A strategy might be searching for common keywords like

- IF
- END
- AS
- FOR
- DO
- SUB
- ENUM
- ...

and when they're in upper case, it's FreeBASIC. What do you think?

**Comment by larsbrinkhoff** [comment]
> we can definitely add `.bi` as this doesn't clash with any other languages

@arfon Not in `languages.yml` no, but I estimate only around half of the 12000 `.bi` files at GitHub are BASIC.

**Comment by arfon** [comment]
@larsbrinkhoff - then it seems like there's some work to be done here to get this right :-\

**Comment by larsbrinkhoff** [comment]
@arfon Is there a way to find out how many `.DLL.bi` files there are?  Searching for `filename:DLL.bi` didn't do the trick.

**Comment by arfon** [comment]
@larsbrinkhoff - can you link me to some of these `.DLL.bi` files?

**Comment by larsbrinkhoff** [comment]
@arfon Sure:
https://github.com/search?q=filename%3Adll.bi&type=Code

**Comment by DTJF** [comment]
>then it seems like there's some work to be done here to get this right :-\

No more progress here?

What about adding the new language in `languages.yml` without any file extension in a first step (to be used by overrides), and doing the fine-tuning later in a second (when internals are clear)?

**Comment by arfon** [comment]
> What about adding the new language in languages.yml without any file extension in a first step (to be used by overrides), and doing the fine-tuning later in a second (when internals are clear)?

@DTJF apologies for the glacially-slow reply. I would be happy to consider a Pull Request implementing this change if the usage of other BASIC dialects can be demonstrated.

**Comment by jeffythedragonslayer** [comment]
Dark Basic Pro is another dialect easily identified by .dba file extensions.
