### ISSUE TITLE
Customizeable colors on GitHub

### ISSUE THREAD

**Issue by Oldes** [github/linguist#2297]
Hello... would it be possible to change colors per language one day on GitHub? Or at least the basic one, like color for string.

And is it possible to see somewhere without browsing minified css, which color (styles) are used for each [name](https://manual.macromates.com/en/language_grammars#naming_conventions.html)?

**Comment by bkeepers** [comment]
Hi @oldes, you are asking about syntax highlighting colors, right? That is not customizable, and I don't think we publish an unminified version at the moment. Sorry, that's not the best news. I'll look into what our options are for publishing it and let you know if I get any good news.
