### ISSUE TITLE
Forked A Repository showing different language statistics

### ISSUE THREAD

**Issue by pawandeep2155** [github/linguist#2303]
This Repository at " https://github.com/danro/LESS-sublime " shows language statistics as Css, Python.
When I forked this repo at " https://github.com/pawandeep2155/LESS-sublime " shows language statistics as Css, Javascript, Python, Makefile
I don't know what is happening here?

**Comment by pchaigno** [comment]
This happened because the repository you forked wasn't up-to-date.
I get this when I run the last released version of Linguist against it:
```
$ linguist
38.94%  CSS
33.84%  JavaScript
25.84%  Python
1.38%   Makefile
```

**Comment by arfon** [comment]
Yep, the languages are only updated once a repository is pushed to. https://github.com/pawandeep2155/LESS-sublime is a new repository to Linguist and so it will get the latest stats.
