### ISSUE TITLE
Prolog files classified as IDL

### ISSUE THREAD

**Issue by ksallberg** [github/linguist#2305]
Example:

https://github.com/ksallberg/ID2213/blob/bc42ae73552c400e19dc0266be61659e6c1fba6c/src/shooting_engine.pro

This file, with file ending .pro gets classified as IDL. Two files in the project (https://github.com/ksallberg/ID2213) are classified as prolog, but I can not figure out what separates them from the IDL classified prolog files.

**Comment by ksallberg** [comment]
(I added a .gitattributes file to fix this for my project, but the error is still in here somewhere..)

**Comment by arfon** [comment]
@ksallberg - this is actually fixed now - see my fork of your repository without the `.gitattributes` file: https://github.com/arfon/ID2213/tree/master

The reason your repository was showing `IDL` was that we fixed the `.pro` mis-identification a while ago but your repository hadn't been updated recently and so hadn't picked up the changes to Linguist.

**Comment by ksallberg** [comment]
Alright that's great :) Thanks for the fix and info!
