### ISSUE TITLE
SaltStack files identified as data.

### ISSUE THREAD

**Issue by DavidJFelix** [github/linguist#2307]
Per discussion in https://github.com/github/linguist/issues/960#issuecomment-89772128 I'm opening this issue.

Salt is more than just yaml data. A `sls` file is technically a jinja2 template of yaml that's parsed and compiled before it becomes data. Consider the following: https://github.com/saltstack-formulas/apache-formula/blob/master/apache/modules.sls

There is no switch to tell salt to analyze this with jinja rather than directly import it - all salt files are parsed with jinja2 a templating engine. What is the qualification for markup over data? I mean, surely yaml rides that line already?

**Comment by pchaigno** [comment]
@arfon @bkeepers This seems to be the same type of code as in Smarty, [which is classified as programming in Linguist](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L3010-L3014).

**Comment by DavidJFelix** [comment]
I'd propose the pull request myself, but I think a color needs to be set.

**Comment by DavidJFelix** [comment]
Closed by merging #2335

**Comment by DavidJFelix** [comment]
Reopening for clarification. I should see saltstack in the language bar right? I've made a number of changes to a repo: https://github.com/hatchery/genepool and still see no saltstack in the bar.

**Comment by arfon** [comment]
@DavidJFelix - I'm afraid this is because the stats only update once a repo has been pushed too. The [new gem](https://github.com/github/linguist/pull/2401) didn't go live until early this week which is after the last push to that repo.

I've manually updated the language stats and things are looking better now.

![screen shot 2015-05-22 at 10 03 23 am](https://cloud.githubusercontent.com/assets/4483/7773418/f7245084-0069-11e5-932f-5251378c0b2b.png)

**Comment by DavidJFelix** [comment]
I know pushing adds you to a queue so I tried doing that a bit and wasn't able to trigger it, but it's cool now. Thanks again @arfon

**Comment by arfon** [comment]
> I know pushing adds you to a queue so I tried doing that a bit and wasn't able to trigger it, but it's cool now. Thanks again @arfon

:+1: ok thanks @DavidJFelix. Sorry for again for the delay getting this live.
