### ISSUE TITLE
Mischaracterized as Smalltalk

### ISSUE THREAD

**Issue by MattWhilden** [github/linguist#2310]
If you look at the bar here: http://github.com/dotnet/corefx you'll notice it thinks 25% of the repo is smalltalk. There isn't any smalltalk in this repo. Clicking through that the next analysis pane has everything correctly identified in the sidebar: https://github.com/dotnet/corefx/search?l=smalltalk

Any tips for chasing this down?

**Comment by pchaigno** [comment]
The [search page](https://github.com/dotnet/corefx/search?l=smalltalk) isn't up-to-date. I get this when I run the last version of Linguist against your repository:
```
$ linguist
71.93%  C#
27.10%  Smalltalk
0.95%   Visual Basic
0.02%   C++
0.01%   Shell
```

I think this is happening because some of your files (the one detected as Smalltalk) are UTF-16 encoded (was it intentional?). For instance:
```
$ file ctest*
ctestbase.cs:      Little-endian UTF-16 Unicode text, with CRLF, CR line terminators
ctestcase.cs:      Little-endian UTF-16 Unicode text, with CRLF, CR line terminators
ctestexception.cs: Little-endian UTF-16 Unicode text, with CRLF, CR line terminators
ctestmodule.cs:    Little-endian UTF-16 Unicode text, with CRLF, CR line terminators
```

Linguist doesn't seem to understand that very well:
```
$ bundle exec linguist ../corefx/src/Common/tests/SystemXml/ModuleCore/ctestbase.cs 
/home/paul/linguist/lib/linguist/blob_helper.rb:281:in `split': invalid byte sequence in UTF-8 (ArgumentError)
```

**Comment by MattWhilden** [comment]
It's not clear whether it's "intentional" but should it be allowed?

**Comment by MattWhilden** [comment]
What I mean is, this is a completely valid C# file and I'd expect linguist to recognize it as such. :-)

**Comment by pchaigno** [comment]
> It's not clear whether it's "intentional" but should it be allowed?

It should be. I think it's the same issue as #353.

**Comment by jasonwilliams200OK** [comment]
Windows uses UTF-16 encoding. It should be allowed and certainly not mischaracterized C# as Smalltalk.

**Comment by arfon** [comment]
This appears to be fixed now.

**Comment by MattWhilden** [comment]
A-mazing. Thank you!
