### ISSUE TITLE
Broken JavaScript syntax highlighting

### ISSUE THREAD

**Issue by mariusschulz** [github/linguist#2315]
Take a look at [this line](https://github.com/mishoo/UglifyJS2/blob/3c846e6f7bdc1e0de536ada9b4f221a6223775e4/lib/parse.js#L1340) in a commit to the UglifyJS project. The current JavaScript syntax highlighting is broken and renders almost all following lines entirely in blue.

I've reported this bug to the [atom/language-javascript](https://github.com/atom/language-javascript) project, and the team [have fixed this issue](https://github.com/atom/language-javascript/issues/131#event-274679824) by now. Time to upgrade your grammar. ;)

**Comment by mariusschulz** [comment]
Ah, I just saw that Linguist uses TextMate grammars. I'll open an issue over at their project.

**Comment by aroben** [comment]
No, you were actually right the first time. We do use the atom/language-javascript grammar for highlighting JavaScript on github.com. You can see that we pull it in as a submodule in https://github.com/github/linguist/tree/master/vendor/grammars.

We pull in grammar updates every time we make a release of Linguist, which usually happens every couple of weeks. This will get fixed on github.com at that time.

**Comment by mariusschulz** [comment]
Right, that's where I looked first. I got confused because two guys from the support team told me to open an issue over at [textmate/javascript.tmbundle](https://github.com/textmate/javascript.tmbundle).

Anyway, the issue is closed now. Looking forward to an updated grammar!

**Comment by aroben** [comment]
Sorry for the confusion!

**Comment by mariusschulz** [comment]
No worries!
