### ISSUE TITLE
Update README to clarify suppress diff behaviour

### ISSUE THREAD

**Issue by nunorafaelrocha** [github/linguist#2317]
REAME file contains information that leads to the assumption that this library allows changing the suppress diff behaviour.

Something that needs to be removed is the mention that this library allows ignore binary files by suppressing diff.

This was also reported in #2206.

**Comment by arfon** [comment]
Thanks for reporting this @nunorafaelrocha. We updated the language in https://github.com/github/linguist/pull/2304/files
