### ISSUE TITLE
Puppet incorrectly classified as Pascal

### ISSUE THREAD

**Issue by 3flex** [github/linguist#2318]
This file is Puppet code, not Pascal: https://github.com/jfryman/puppet-nginx/blob/master/manifests/init.pp

It might help if a new sample is added which contains class parameters, none of the samples include this:

```puppet
    # A class with parameters
    class apache ($version = 'latest') {
      package {'httpd':
        ensure => $version, # Using the class parameter from above
        before => File['/etc/httpd.conf'],
      }
      file {'/etc/httpd.conf':
        ensure  => file,
        owner   => 'httpd',
        content => template('apache/httpd.conf.erb'), # Template from a module
      }
      service {'httpd':
        ensure    => running,
        enable    => true,
        subscribe => File['/etc/httpd.conf'],
      }
    }
```

Example is from https://docs.puppetlabs.com/puppet/latest/reference/lang_classes.html#syntax

Also missing is an example of inheritance which the problem file also uses.

```puppet
class example (
  $my_param = $example::params::myparam
) inherits example::params {

  notice('This is a test notice')
}
```

Modified from https://docs.puppetlabs.com/puppet/latest/reference/lang_classes.html#aside-when-to-inherit

**Comment by pchaigno** [comment]
New samples are always welcome!
Do you want to open a pull request? I'm not from GitHub so I won't be able to merge your PR (though it should be merged quickly) but if there's any issue I can help you.

**Comment by 3flex** [comment]
So I just drop these into /samples/Puppet, then they'll do their magic?

It would probably be best to have a disambiguation in heuristics.rb but I don't know Pascal nor am I any good with regular expressions.

**Comment by 3flex** [comment]
Now I think about it, if someone could help come up with something that detects the first keyword in the file is either `class`, `define` or `node` (ignoring any comments in the preceding lines [i.e. lines that start with `#`]) then we can say that's Puppet. It would be good enough for most cases.

**Comment by pchaigno** [comment]
We usually prefer to add heuristic rules if the issue can't be solved only with the Bayesian classifier. We could first try to add new samples and if that doesn't solve it (we'll need incorrectly classified repositories to test it), we can build a new heuristic.

**Comment by arfon** [comment]
> We usually prefer to add heuristic rules if the issue can't be solved only with the Bayesian classifier. 

Yes, please add some samples to `/samples/Puppet`. If this doesn't fix the issue then let's look at adding a heuristic.

**Comment by 3flex** [comment]
I'm happy to open a PR, can you leave this issue open though? It's not fixed, I'm not sure why it was closed.

**Comment by arfon** [comment]
Yep, sorry.

**Comment by arfon** [comment]
This now looks to be fixed. Please feel free to comment/re-open if you're still having problems.
