### ISSUE TITLE
Coffeescript is way to close to CSS

### ISSUE THREAD

**Issue by phase** [github/linguist#2320]
The colors are way to close! I can't even tell what [DevDocs](https://github.com/Thibaut/devdocs) is!

**Comment by gjtorikian** [comment]
Is it? One is blue, the other is purple. They seem pretty different to me.

N.B. This has nothing to do with https://github.com/github/linguist/pull/2298: the colors for these two languages went unchanged.

**Comment by phase** [comment]
It might just be me, but they look pretty close.

**Comment by pchaigno** [comment]
@phase They look ok to me too :/

**Comment by phase** [comment]
Weird, they look similar to me...
