### ISSUE TITLE
CoffeeScript syntax highlighting not working with backticks

### ISSUE THREAD

**Issue by amk221** [github/linguist#2321]
Backticks are being used in CoffeeScript to escape import/exports [more info](https://github.com/kimroen/ember-cli-coffeescript#coffeescript-and-ember-cli).

When used, the syntax highlighting doesn't work:
![screen shot 2015-04-10 at 09 09 34](https://cloud.githubusercontent.com/assets/382061/7084099/6544e238-df61-11e4-8ac5-8e35e882f789.png)

**Comment by pchaigno** [comment]
@amk221 Linguist only selects the grammar to use for highlighting. [atom/language-coffee-script](https://github.com/atom/language-coffee-script) is used to highlight CoffeeScript code on GitHub. You should open an issue there ;)

**Comment by amk221** [comment]
Ah, appologies

**Comment by pchaigno** [comment]
No worries ;)
