### ISSUE TITLE
Write 'how Linguist integrates into GitHub' docs

### ISSUE THREAD

**Issue by arfon** [github/linguist#2331]
> In github/markup#431 I added a section in the README on how the library is integrated into GitHub.com. I wonder if it would make sense to add something similar here.

Basically we need a much better version of this: https://github.com/github/linguist/pull/2093

**Comment by arfon** [comment]
Also / cc https://github.com/github/linguist/issues/2104

**Comment by larsbrinkhoff** [comment]
Plus one; thumbs up.  Suggested items to cover:

* How a repository is assigned a primary language, which is used for "Trending" lists, repository searches etc.
* How the repository language statistics are calculated and displayed in a bar.
* How individual files are indexed with respect to language.

**Comment by gjtorikian** [comment]
Also /cc https://github.com/github/linguist/issues/2278. Unsure if you're thinking of a new docs folder or what but I can commit to doing that issue above.

**Comment by jimmyye** [comment]
When  a new version of Linguist released, how long will it take GitHub to adapt those changes (new languages, languages renamed)?

How about a /languages or /linguist API to list all languages that GitHub is using? Something like https://github.com/github/linguist/blob/master/lib/linguist/languages.yml but in json.

**Comment by gjtorikian** [comment]
> How about a /languages or /linguist API to list all languages that GitHub is using? 

That's not a bad idea. It's pretty inline with our existing [Emoji API](https://developer.github.com/v3/emojis/).

What do you think, @brandonblack? Maybe we could make a `Meta` object in GraphQL for stuff like this.
