### ISSUE TITLE
Emacs modeline regurarly conflicts with file contents and extension

### ISSUE THREAD

**Issue by larsbrinkhoff** [github/linguist#2336]
Apparently, programmers like to declare an Emacs modeline that confilcts with the file contents and file extension.

Not sure what to do about that.  Whack them with the Emacs Lisp Reference Manual?

**Comment by larsbrinkhoff** [comment]
[https://github.com/tudelft/winning_group/blob/4e394ee9a7469f39ac324c8429e52ba3d0c9d36c/sw/airborne/arch/stm32/lisa-l.ld](linker script)

**Comment by pchaigno** [comment]
Sounds like the `Modeline` strategy isn't as sure as we though. Maybe it should be [after the `Shebang` strategy](https://github.com/github/linguist/blob/master/lib/linguist/language.rb#L91-L92)?

**Comment by larsbrinkhoff** [comment]
Admittedly, these are only a handful of examples so far.  I don't know if they are statistical flukes or a real problem.

**Comment by pchaigno** [comment]
I don't think there is a real problem either but I can't remember a single time when the `Shebang` strategy was wrong. Shebangs and modelines are both fairly sure labels but one only impacts the syntax highlighting when the other impacts the interpretation itself. I don't think any user would use a shebang different from the language's shebang.

**Comment by arfon** [comment]
> Sounds like the Modeline strategy isn't as sure as we though. Maybe it should be after the Shebang strategy?

Possibly but that's not been causing issues as far as I know so far right? I agree it would be very peculiar to have a Shebang defined that couldn't actually execute a piece of code.

> Not sure what to do about that. Whack them with the Emacs Lisp Reference Manual?

@larsbrinkhoff - to your original question. I agree this is tripping some people up but IMO if you use a modeline that isn't correct and that makes your GitHub experience a little weird then there's not much we can do :shrug:

**Comment by larsbrinkhoff** [comment]
@arfon I'm hoping a future multiple-strategy scoring would be a solution.

And implementing @pchaigno's suggestion wouldn't hurt.

**Comment by arfon** [comment]
> @arfon I mostly wanted to shine a light on the fact that Emacs mode lines are a somewhat irreliable source of information. I'm hoping a future multiple-strategy scoring would be a solution.

:+1: yup I appreciate this. Thanks for keeping us honest :smile:

> And implementing @pchaigno's suggestion wouldn't hurt.

Agreed. I'll take a stab at that when I get a chance.
