### ISSUE TITLE
Update Ceylon

### ISSUE THREAD

**Issue by lucaswerkmeister** [github/linguist#2338]
[ceylon-sublimetext](https://github.com/jeancharles-roger/ceylon-sublimetext) was updated (jeancharles-roger/ceylon-sublimetext#7), please update your tree in `vendor/grammars`.

**Comment by pchaigno** [comment]
It will be updated in the next release ;) (see [contribution guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#fixing-syntax-highlighting))

**Comment by lucaswerkmeister** [comment]
Alright, support told me to submit an issue, sorry if it’s superfluous :)

**Comment by pchaigno** [comment]
No problem, it changed recently.
