### ISSUE TITLE
Put language on bar that usually isn't?

### ISSUE THREAD

**Issue by phase** [github/linguist#2347]
I'd like to put a language on the "bar" of my project that usually isn't there. Is there any way I can manually set it?

**Comment by pchaigno** [comment]
If it's a `programming` or `markup` language you can [override](https://github.com/github/linguist#using-gitattributes) the detection for some arbitrary files (to have them detected as that language).

**Comment by phase** [comment]
I want to do it for all languages of that language (Markdown).

**Comment by pchaigno** [comment]
You mean `RMarkdown` and `Markdown` (Linguist only support these two).

**Comment by phase** [comment]
So would I do something like this:
```
$ cat .gitattributes
*.rb linguist-language=Markdown
```

**Comment by pchaigno** [comment]
That wouldn't change anything since `.md` is already associated to Markdown.
I'm not sure I understand what you want to do exactly. Do you have an example?

**Comment by phase** [comment]
I'm making a website in Markdown pages, and I'd like the Markdown to show up on the bar.

**Comment by pchaigno** [comment]
It should already show up in the language bar. Do you have a link to the repository?

**Comment by phase** [comment]
My original repo is private, so I [made a test one](https://github.com/phase/mdjs).

**Comment by pchaigno** [comment]
My bad, [Markdown is actually a `prose` language](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L1858) so it won't be shown in the statistics, you're right. There isn't currently

**Comment by arfon** [comment]
Yeah I'm afraid we don't show `prose` stats in the language bar. @phase it looks like you've figured out how to override the other language detections with `.gitattributes` data already :smile:

**Comment by phase** [comment]
@arfon Is there any way to manually show it?

**Comment by arfon** [comment]
> @arfon Is there any way to manually show it?

Unfortunately not sorry.
