### ISSUE TITLE
Detect .pbxproj as generated (Xcode)

### ISSUE THREAD

**Issue by mdio** [github/linguist#2349]
The Git book even uses .pbxproj files as [an example for treating files as binary](http://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes).
> Although it’s technically a text file (because it’s all UTF-8), you don’t want to treat it as such because it’s really a lightweight database – you can’t merge the contents if two people change it, and diffs generally aren’t helpful.

Please have a look at an example: https://github.com/fullstackio/FlappySwift/blob/master/FlappyBird.xcodeproj/project.pbxproj

It really adds unnecessary clutter to our pull requests.

**Comment by jspahrsummers** [comment]
Although it's certainly not the best format—or the most friendly for merging—`project.pbxproj` _is_ diffable and partly readable.

For example, the following changes will result in an (IMO) understandable diff in the project file:

 1. Changes to build settings
 1. Files being added/removed in targets
 1. Run Script build phases being edited
 1. Build configurations being added/removed

You'd lose all of this information if the contents didn't appear.

**Comment by robrix** [comment]
It’s also pretty important for _correct_ build settings when adding frameworks, as it’s too easy to otherwise end up with `FRAMEWORK_SEARCH_PATHS` pointing at a specific user’s built products dir.

**Comment by mdio** [comment]
As far as I understand, marking files as generated only leads to "Diff suppressed. Click to show." messages. So it's still possible to review them.

**Comment by pchaigno** [comment]
@arfon opened a PR at #2351 to fix this.

**Comment by arfon** [comment]
OK it seems like there's some difference of opinion here as to what the value of seeing diffs for these files is.

I think we should stick with the current behaviour and push ahead on making it possible to override these behaviours on a per-repo basis with the `.gitattributes` data. Currently it's not possible to do this but we're tracking the issue here: https://github.com/github/linguist/issues/2206
