### ISSUE TITLE
Differentiate Assembly Languages  

### ISSUE THREAD

**Issue by phase** [github/linguist#2350]
Is there any way we could separate Assembly languages? Such as [6502](https://github.com/search?utf8=%E2%9C%93&q=6502) & x86?

**Comment by pchaigno** [comment]
Do they use different file extensions?

**Comment by phase** [comment]
No, but they have very different syntax.

**Comment by pchaigno** [comment]
Do you want to do this for the language statistics or to fix a highlighting issue somewhere?

**Comment by phase** [comment]
Language statistics, such as the "bar" (is there a name for that?).

**Comment by pchaigno** [comment]
We sometimes call it the language bar.

But if we create two languages for 6502 and x86, how would we classify the other assembly dialects?

**Comment by phase** [comment]
Can we put them all in an "Assembly" group? Like Perl6?

**Comment by phase** [comment]
List of Assembly languages I could find:
* x86
* x64
* 6502

**Comment by larsbrinkhoff** [comment]
- [MIPS](https://github.com/search?q=jal+lw&type=Code)
   - [PowerPC](https://github.com/search?q=br+stw&type=Code)
   - [](https://github.com/search?q=jal+lw&type=Code)
   - [](https://github.com/search?q=jal+lw&type=Code)
   - [](https://github.com/search?q=jal+lw&type=Code)
   - [](https://github.com/search?q=jal+lw&type=Code)
   - [](https://github.com/search?q=jal+lw&type=Code)
   - [](https://github.com/search?q=jal+lw&type=Code)

**Comment by larsbrinkhoff** [comment]
Also, "GAS" is a bit of a misnomer for `.s`.  But language names can never ever be changed, right?

**Comment by pchaigno** [comment]
> Can we put them all in an "Assembly" group? Like Perl6?

All languages of a group will be counted in the statistics as the parent language. So the different Assembly dialects would be counted as Assembly :/
Perl6 isn't in a Perl group because it's very different from Perl 5.

I don't think it would be a good idea to create a new language per Assembly dialect. Maybe there is a better approach...?

**Comment by larsbrinkhoff** [comment]
By the way, I have some other improvements for the `Assembly` language:
https://github.com/github/linguist/compare/master...larsbrinkhoff:asm

**Comment by pchaigno** [comment]
@larsbrinkhoff You forgot a `k` in your link ;)

**Comment by larsbrinkhoff** [comment]
Thanks; fixed.

**Comment by pchaigno** [comment]
@larsbrinkhoff I think you should open one pull request per commit (they look unrelated). Do we really need to use heuristics to distinguish Assembly from Unix Archive and Assembly from GAS? (it would probably be best to discuss that in a new thread though)

**Comment by larsbrinkhoff** [comment]
It's a work in progress.  Will post a new PR when more polished.

**Comment by phase** [comment]
Is there a way we could separate them, but still keep them together? Like, if I had a project with x86 & 6502, we could have them be the same color on the bar (or not), but have the names show up as different.

**Comment by pchaigno** [comment]
> Is there a way we could separate them, but still keep them together? Like, if I had a project with x86 & 6502, we could have them be the same color on the bar (or not), but have the names show up as different.

To have different names we need to be able to differentiate the languages. In order to do that we need to create new languages :/

**Comment by arfon** [comment]
Closing this as stale. We'd welcome Pull Requests adding support for new Assembly languages.
