### ISSUE TITLE
My small Python repository is detected as Groff language

### ISSUE THREAD

**Issue by clsacramento** [github/linguist#2352]
-On the language bar I get: 
Groff 99.5%

-But when I click:

We couldn't find any code matching ''

You could try an advanced search.

-And on the left bar:

Languages

9 Python
1 Text
1 Markdown

-repository link:
https://github.com/clsacramento/LeBonCoinAlert

**Comment by arfon** [comment]
Running Linguist on your repository locally it looks like these files are being detected as Groff:
```
web_monitor/data/apscheduler/executors.default.log.1
web_monitor/data/apscheduler/scheduler.log.1
web_monitor/data/web_monitor/main.log.1
```

You might want to ignore these with something like this in your `.gitattributes` file: 

`web_monitor/data/* linguist-vendored=true`

**Comment by clsacramento** [comment]
Super! This works perfectly. Thanks a lot!

**Comment by arfon** [comment]
:+1: great!
