### ISSUE TITLE
Drools .drl extension.

### ISSUE THREAD

**Issue by viridian1138** [github/linguist#2355]
Add syntax highlights for .drl rules files for the Drools rule engine.

http://drools.org

**Comment by pchaigno** [comment]
Hi @viridian1138 - Do you have an example of `.drl` file? Also, please see [the requirements for adding support for a new language](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) to Linguist.

**Comment by arfon** [comment]
Closing as stale.
