### ISSUE TITLE
Ruby counted as Java(!), but search shows 0 Java files

### ISSUE THREAD

**Issue by eins78** [github/linguist#2356]
Repo https://github.com/Madek/madek-webapp: says: 54% Java
https://github.com/Madek/madek-webapp/search?l=java show: 0 Java files

I am getting the same results if using `linguist` locally. 
What's worse, setting `.gitattributes` has no effect at all. I added the following (which shouldn't even be necessary):

```
$ cat .gitattributes
*.rb linguist-language=Ruby
*.js linguist-language=JavaScript
*.haml linguist-language=HAML
*.sass linguist-language=SASS
```

That all makes me think there is some internall bug which I can't even begin to grasp…

**Comment by pchaigno** [comment]
> I am getting the same results if using `linguist` locally. 

By *same results* you mean 54% Java right?
Try to use the `--breakdown` option to see which files are detected as Java.

**Comment by eins78** [comment]
Yeah, sorry, I wrote that way too short.
Same results means:
- same percentage of Java Code
- `--breakdown` does show Java files*

* apart from a few vendored files which is just removed, but those are not anywhere close to 50%

**Comment by pchaigno** [comment]
These files are detected as Java because of the modeline (`-*- Mode: Java;`):
```
public/mozilla-pdf/core/pdf.js
public/mozilla-pdf/core/pdf.worker.js
public/mozilla-pdf/web/compatibility.js
public/mozilla-pdf/web/debugger.js
public/mozilla-pdf/web/viewer.js
```

A `.gitattributes` fixes it but you need to make a new commit before checking again ;)

**Comment by eins78** [comment]
Ah, thanks! :)

Committing "fixed" it, but not because of the `.gitattributes` (don't need those anymore) but because I had not committed the deletion of those files. Now it works as expected.
