### ISSUE TITLE
Incorrect syntax hilighting of Ada character literals

### ISSUE THREAD

**Issue by faelys** [github/linguist#2357]
Hello,

there is a problem with the syntax hilighting of Ada source. I haven't really understood how linguist works, it seems language-specific hilighting is "vender provided", but for Ada it points to aroben/ada.tmbundle, which has no issue tracker, so I'm reporting it here. Please point me to the right direction if this is not the correct place to report it.

I have no idea what TextMate is or how a "bundle" works, so I can't offer a patch or a pull request, but I will do my best to describe what is wrong here.

To put it simply, it seems character literals in Ada are not recognized at all.

In Ada, much like in C, strings are arrays of characters, and string literals are written between double-quotes (`"`), while character literals are written between single-quotes (`'`). Escaping is a bit different than in C though: a double-quote character is inserted in a string literal using two consecutive double-quote character (e.g. `"This: "" is a single-double quote"`) while the character literal for the simple quote is three consecutive single-quotes (i.e. `'''`). To put it a regex way, character literals match `'.'` and the single-quote character literal is no exception.

As far as I can tell, there is currently no syntax hilighting at all for character literals. Here is an example:

```ada
declare
   Two_SL : String (1 .. 3) := "two";
   Two_CL : String (1 .. 3) := ('t', 'w', 'o');
begin
   Text_IO.Put_Line (Two_SL);
   Test_IO.Put_Line (Two_CL);
end;
```

As of this writing, `1` and `3` are colored specially, `"two"` has another color, `declare`, `begin` and `end` have keyword color, but `'t'` is in plain style like `Two_SL`.

Now in itself, it's a small problem, since character literals are small anyway. However it really hurts readability when using the double-quote character literal:

```ada
procedure Print_String_Value (Value : in String) is
begin
   Text_IO.Put_Line ("The value is: """ & Value & '"');
end Print_String_Value
```

For the reference, here `&` is the concatenation operators, and it is overloaded so that a string can be built by concatenating strings or by concatenating a string and a single character.

This causes the double-quote character literal to be considered as the beginning of a string literal, and the string coloring spans the rest of the code.

There are several real-world examples of this, [here is one of mine](https://github.com/faelys/markup-ada/blob/trunk/tools/markdown.adb#L120)

I wouldn't mind having character literals without special hilighting, if at least it wouldn't incorrectly color large sections of code.

Thanks for your time,
Natasha

**Comment by arfon** [comment]
/ cc @aroben

**Comment by aroben** [comment]
Hi @faelys. Thanks for the detailed bug report.

aroben/ada.tmbundle is actually a fork of textmate/ada.tmbundle, as you can see here:

![screen shot 2015-04-23 at 3 14 49 pm](https://cloud.githubusercontent.com/assets/917945/7305392/81f6c9b8-e9cb-11e4-8ca4-d0642ade2600.png)

So the best place to file an issue is at https://github.com/textmate/ada.tmbundle/issues/new. Sorry for the confusion! I think if you copy this issue over into that repository the people there should be able to help you.

**Comment by faelys** [comment]
Hello,

I'm not sure it's worth re-opening the issue here for that: I have opened the issue against TextMate/ada.tmbundle, and they committed a fix, but as far as I understand, that's not enough to make it to linguist, @aroben 's branch has to be updated somehow.

Thanks for your help,
Natasha

**Comment by pchaigno** [comment]
@aroben textmate/ada.tmbundle#2 was fixed, maybe we could now use [textmate/ada.tmbundle](https://github.com/textmate/ada.tmbundle) directly instead of your fork?

**Comment by aroben** [comment]
Yeah we should get off my fork now.
