### ISSUE TITLE
Update JavaScript grammar git submodule

### ISSUE THREAD

**Issue by cvrebert** [github/linguist#2361]
See https://github.com/atom/language-javascript/issues/142#issuecomment-96462283

**Comment by pchaigno** [comment]
Grammars are updated with each new release ;)

**Comment by cvrebert** [comment]
Well, the Supportocat who responded to my bug report said to file a Linguist issue if a grammar submodule update was necessary.

**Comment by pchaigno** [comment]
No worries. It changed recently.

@arfon Any way we could prevent support that this has changed?

**Comment by jhosman** [comment]
> @arfon Any way we could prevent support that this has changed?

@pchaigno Thanks! I'll pass this info along to the other Supportocats :+1:
