### ISSUE TITLE
Not adding Algol

### ISSUE THREAD

**Issue by larsbrinkhoff** [github/linguist#2362]
I intestigated the use of Algol at GitHub.  The result was:

| x | Algol files | Total files | Comment
| --- | --- | --- | ---
| `.al` | 81 | 84182 | Mostly Perl autoload files
| `.alg` | 757 | 51813 | Mostly Nyquist files
| `.algol` | 15 | 15 |
| `.alw` | 3 | 8 |
| `.a60` | 794 | 794 |
| `.a68` | 20 | 42 |

Conclusion: Probably not popular enough to add.

**Comment by pchaigno** [comment]
Thanks for posting the result @larsbrinkhoff!
Would it be worth adding `.al` for Perl?

**Comment by larsbrinkhoff** [comment]
There are probably enough repositories for adding Perl's `.al`.  I also saw other kinds of `.al` files, but didn't take notes.
