### ISSUE TITLE
Highlight DNS zone files

### ISSUE THREAD

**Issue by mcandre** [github/linguist#2364]
Could we add support for DNS zone files, e.g. https://github.com/mcandre/docker-bind/blob/master/sneaky.net.zone ?

**Comment by pchaigno** [comment]
@mcandre Do you want to open a pull request? There seem to be [enough DNS zone files on GitHub](https://github.com/search?utf8=%E2%9C%93&q=extension%3Azone+NOT+ksfjdjgbfkvbfjgbf&type=Code&ref=searchresults). Please see the [contribution guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language).

**Comment by mcandre** [comment]
I'm new to DNS, hence how I noticed this while practicing submitting zone files on GitHub.

I know dns-mode.el does a decent job, but I don't know of a JavaScript lib for this.

**Comment by pchaigno** [comment]
We'll need a Sublime Text package or a TextMate/Atom bundle. I found:
- https://github.com/sixty4k/st2-zonefile
- https://github.com/norm/Bind.tmbundle

You can use [Lightshow](https://github-lightshow.herokuapp.com/) if you want to test them.

**Comment by mcandre** [comment]
The TextMate bundle, https://github.com/norm/Bind.tmbundle , works for me.

**Comment by pchaigno** [comment]
Great!

Do you want to open a pull request to add support for DNS zone files? I can help you if you have any issue.
