### ISSUE TITLE
files (.bf) misclassified as brainfuck

### ISSUE THREAD

**Issue by mbdoud** [github/linguist#2365]
In my [repository] (https://github.com/mbdoud/Compare-NP-Preferences), I have files with an extension ``.bf`` which are misclassified as 'brainfuck'.

The misclassified files:
phylo_output/codonmodel_optimized_trees/Tree-GY94_Allhosts_Model-GY94_CF3x4_omega-global-gamma4_rates-gamma4/hyphy_cmds.bf
phylo_output/codonmodel_optimized_trees/Tree-GY94_Avian_Model-GY94_CF3x4_omega-global-gamma4_rates-gamma4/hyphy_cmds.bf
phylo_output/codonmodel_optimized_trees/Tree-GY94_Equine_Model-GY94_CF3x4_omega-global-gamma4_rates-gamma4/hyphy_cmds.bf
phylo_output/codonmodel_optimized_trees/Tree-GY94_Human_Model-GY94_CF3x4_omega-global-gamma4_rates-gamma4/hyphy_cmds.bf
phylo_output/codonmodel_optimized_trees/Tree-GY94_Swine_Model-GY94_CF3x4_omega-global-gamma4_rates-gamma4/hyphy_cmds.bf

**Comment by mbdoud** [comment]
I fixed this in my own repository by overriding the classification with a ``.gitattributes`` file, but I believe this is still a general classification issue, as the program [HyPhy] (https://github.com/veg/hyphy) uses ``.bf`` as an extension for [its batch files] (http://hyphy.org/w/index.php/Template_Batch_Files).

**Comment by larsbrinkhoff** [comment]
Can you provide a search which estmiates the number of HyPy batch files?

**Comment by pchaigno** [comment]
Hi @mbdoud - To fix this issue we'll have to recognize HyPhy as a language in Linguist. As @larsbrinkhoff asked, we'll need to show that there are hundreds of examples of HyPhy files on GitHub (see the requirements in the [contribution guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language)).

**Comment by mbdoud** [comment]
I guess my issue here was not that HyPhy batch files are not recognized by linguist, but that my repository was labeled "brainfuck". This misclassification looks pretty unprofessional when sharing my work with others in my research field, and luckily I noticed it and fixed it quickly. 

Although it looks like there are only [a few dozen] (https://github.com/search?utf8=%E2%9C%93&q=HyPhy) repositories on GitHub using HyPhy, it is a widely-used program, [cited over 1000 times] (http://scholar.google.com/scholar?cluster=17874163875017617061&hl=en&as_sdt=0,5&sciodt=0,5) in peer-reviewed publications. Perhaps HyPhy doesn't meet linguist's requirements, but I'm guessing there may be others in the future who, like myself, will be inconvenienced with a potentially embarrassing misclassification to what appears to be a highly impractical and esoteric language built (and apparently named) solely for amusement.

**Comment by pchaigno** [comment]
@mbdoud It's quite difficult to search for repositories so we usually search for code and roughly estimate the number of repositories from that.

Could you quickly check that code snippets from [this search](https://github.com/search?utf8=%E2%9C%93&q=extension%3Abf+fprintf&type=Code&ref=searchresults) are all HyPhy (checking one page at the beginning, one at the end and one in the middle should be enough)? If that's the case, it'll probably be sufficient to add it as a new language in Linguist :-)

**Comment by mbdoud** [comment]
I took a quick look at a bunch of those search results, and they are indeed all HyPhy batch files.

**Comment by pchaigno** [comment]
Great! Do you want to open a pull request to [add HyPhy as a language in Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language)?

**Comment by mbdoud** [comment]
Sure, I've [forked] (https://github.com/mbdoud/linguist) and added an entry for HyPhy in ``languages.yml``and added sample files in an appropriate directory. I do not, however, know how to add a grammar for it. Perhaps a HyPhy developer (@spond?) might be able to assist.  And maybe @arfon or @bkeepers can help test the classifier to distinguish between brainfuck and HyPhy?

**Comment by pchaigno** [comment]
> I do not, however, know how to add a grammar for it. Perhaps a HyPhy developer (@spond?) might be able to assist.

I couldn't find one either. If there is one, you'll have to add `tm_scope: none` until one is developed.
<br/>

> And maybe @arfon or @bkeepers can help test the classifier to distinguish between brainfuck and HyPhy?

@arfon Could you send me samples file from https://github.com/search?utf8=%E2%9C%93&q=extension%3Abf+fprintf&type=Code&ref=searchresults and https://github.com/search?p=1&q=extension%3Abf+brain&ref=searchresults&type=Code&utf8=%E2%9C%93 to test @mbdoud's changes? Thanks :sparkles:

**Comment by arfon** [comment]
> @arfon Could you send me samples file from

:+1: in your inbox.

**Comment by pchaigno** [comment]
Thanks :sparkles:

**Comment by arfon** [comment]
This will be fixed in the next release of Linguist: https://github.com/github/linguist/pull/2375

**Comment by mbdoud** [comment]
Thanks :smile:
