### ISSUE TITLE
GML Geography Markup Language showing as Game Maker Language

### ISSUE THREAD

**Issue by vog** [github/linguist#2366]
The .gml files in my repository are classified as Game Maker Language, but these are [OGC Geography Markup Language](https://en.wikipedia.org/wiki/Geography_Markup_Language) files.

There seem to be many [users of the OGC Geography Markup Language](https://github.com/search?utf8=%E2%9C%93&q=extension%3Agml+opengis&type=Code&ref=searchresults). Please add support for them.

**Comment by pchaigno** [comment]
I think we could add it as a new XML extension. Do you want to take a stab at it?

**Comment by vog** [comment]
I quickly added an entry to languages.yml as well as some example files for GML 3.1 and GML 3.2, the rest should be done be somebody else. Even after skimming through CONTRIBUTING.md I have no idea what else is needed, if anything.

**Comment by pchaigno** [comment]
Nothing else is needed ;)

**Comment by arfon** [comment]
I re-ran the language calculation on [this repo](https://github.com/diegomigliavacca/deegree-3.3.11-gpkg) and it looks like this fix has worked.

**Comment by vog** [comment]
Could you also re-run the language calculation on this repo?

https://github.com/deegree/deegree3

**Comment by arfon** [comment]
> Could you also re-run the language calculation on this repo?

Done.

**Comment by vog** [comment]
I'm afraid something went wrong there.  The second largest part was GML.  Now it is HTML. It seems that "Geography Markup Language" has been recognized as HTML instead of XML.

**Comment by arfon** [comment]
HTML looks to be third after XML and Java - is this not correct?

https://github.com/deegree/deegree3/search?l=xml

![screen shot 2015-05-31 at 11 07 32 pm](https://cloud.githubusercontent.com/assets/4483/7903876/da76d330-07e9-11e5-93cc-27fd51f065d2.png)

**Comment by vog** [comment]
That one looks correct, but the summary at the top shows a different picture that confuses me:

![screenshot](https://cloud.githubusercontent.com/assets/412749/7911185/6a65faae-085b-11e5-8dfc-5cc23c285d38.png)

**Comment by arfon** [comment]
Ah OK. The language stats bar excludes languages that are defined as [`data`](https://github.com/github/linguist/blob/f380aa2e5ef1dbad4157f205e4f93a2055f1c7d7/lib/linguist/languages.yml#L3451) which means `XML` doesn't show up here (but it does show up in the search results). I'm sorry for this confusion :-\

**Comment by vog** [comment]
Okay. Thanks for the clarification!
