### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by davidbarratt** [github/linguist#2367]
Is this the library that is being used for syntax highlighting on github.com or should I be looking somewhere else?

I tried to add `.module` and `.install` (drupal files) files as PHP
```
*.module linguist-language=PHP
*.install linguist-language=PHP
```
in `.gitattributes` but this didn't seem to have any effect. :/

**Comment by arfon** [comment]
Hi @davidbarratt. Unfortunately it's not possible to use the `.gitattributes` overrides to manually set the highlighting yet - they're only used when calculating the repository language statistics.

One possible alternative is to use Vim/Emacs modelines in these files which _will_ override the syntax highlighting: https://github.com/github/linguist#using-emacs-and-vim-modelines

Sorry for any confusion caused here.

**Comment by davidbarratt** [comment]
@arfon,

Interesting, yeah I don't want to modify all of the files (most of them are third-party), but the lack of syntax highlighting is annoying. :(

Should I submit a PR to support Drupal file extensions? (which are PHP)

Thanks!

**Comment by arfon** [comment]
> Should I submit a PR to support Drupal file extensions? (which are PHP)

We had a go at this a while ago but concluded it wasn't possible right now sorry: https://github.com/github/linguist/pull/1343#issuecomment-91732365

The long-term focus for Linguist is currently to improve the performance of our classifier (with a Google Summer of Code project). I'm also planning on spending some time fixing the issue you originally flagged - that `.gitattributes` data can't be used for overriding syntax highlighting.

**Comment by davidbarratt** [comment]
@arfon,

ah, I see. ok, yeah if `.gitattributes` could be used to override syntax highlighting globally, that would be incredible, I can just set it for the Drupal projects. :)

**Comment by josephjoaquinmartin** [comment]
Has anything happened on this topic @arfon ?

**Comment by arfon** [comment]
Excellent timing @josephjoaquinmartin - I was actually chatting with some engineers last week at GitHub and we're planning on doing some work on this in the coming weeks. No promises but it's rapidly reaching the top of my todo list.

**Comment by josephjoaquinmartin** [comment]
attababe @arfon I look forward to it. How people program without syntax highlighting, I'll never know. Thanks.

**Comment by horst-n** [comment]
@arfon,
is it possible now to define f. e. php syntax highlighting for *.module files? If yes, can you point me to a HowTo, please?

**Comment by arfon** [comment]
> is it possible now to define f. e. php syntax highlighting for *.module files? If yes, can you point me to a HowTo, please?

I'm afraid overrides like this still aren't possible 😞

**Comment by Niklan** [comment]
Still not supported. So annoying. Srsly, maybe better use Bitbucket way? Let user to select main language for repository for syntax highlight files where your code can't detect language?

I still remember time when .module is correctly highlighted on GitHub, why it isn't possible for now?

**Comment by travis-bradbury** [comment]
Looks like this is [fixed](https://github.com/github/linguist/issues/1792#issuecomment-286379822) now. I had to change a file to see my `.gitattributes` setting take effect on it. It seems that [Klausi](https://github.com/github/linguist/issues/1792#issuecomment-286419227) had the same experience.
