### ISSUE TITLE
Dominant language in repository being misidentified

### ISSUE THREAD

**Issue by javathunderman** [github/linguist#2385]
Hey there, 

We have a repository at http://github.com/Emposoft/Edlightened-Web, and the files being shown in the marker on top and the "filter files by language" (https://github.com/Emposoft/Edlightened-Web/search?l=php) search feature are showing two different languages as having the most files. It is changing between PHP (on the quick look marker), and JS (in the search function). 

I'm not exactly sure why this is happening, but taking a quick look at the files, about 90 or so are JS, versus 10 that are PHP. On the marker, it's showing 50% of the files in the repository as PHP, and about 14% JS. However, I'm not able to find any files that are explicitly being identified as the wrong language. 

Again, not sure exactly why this is, but I wanted to bring this to your attention. Really appreciate the work you guys are doing!

cc @AJDev77

**Comment by pchaigno** [comment]
The percentages in the language bar are the correct one. I ran Linguist against your repository:
```
$ linguist
51.84%  PHP
29.12%  HTML
13.67%  JavaScript
5.25%   CSS
0.13%   Ruby
```

The percentages don't represent the number of files but the total size of the files ;)
So for instance, your PHP files represent 51.84% of the total size of your source codes.

**Comment by javathunderman** [comment]
Ah, my mistake. Thanks for the help!
