### ISSUE TITLE
vim modeline does not work?

### ISSUE THREAD

**Issue by wkentaro** [github/linguist#2389]
In my repo, vim modeline does not work to highlight files.

bashrc with vim modeline:
https://github.com/wkentaro/dotfiles/blob/vim-modeline/_bashrc

bashrc with emacs modeline:
https://github.com/wkentaro/dotfiles/blob/emacs-modeline/_bashrc

**Comment by arfon** [comment]
Looks like when we require a matching pair of in the [Vim regex](https://github.com/github/linguist/blob/master/lib/linguist/strategy/modeline.rb#L5) although I'm not sure why.

This basically means that this doesn't match:

```
# vim: set ft=sh:
```

...whereas this does:

```
/* vim: set ft=sh: */
```

As the author of the modeline functionality I'm :hand: to fix this. @bkeepers @pchaigno @larsbrinkhoff I'm planning to just remove the  `/* .... */` part of the regex here. Sound good?

**Comment by larsbrinkhoff** [comment]
I defer to the Vim experts.

**Comment by pchaigno** [comment]
> As the author of the modeline functionality I'm :hand: to fix this. @bkeepers @pchaigno @larsbrinkhoff I'm planning to just remove the `/* .... */` part of the regex here. Sound good?

:+1:

**Comment by wkentaro** [comment]
Thanks.

2015年5月13日水曜日、Arfon Smith<notifications@github.com>さんは書きました:

> Closed #2389 <https://github.com/github/linguist/issues/2389> via #2394
> <https://github.com/github/linguist/pull/2394>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/github/linguist/issues/2389#event-303892825>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>
