### ISSUE TITLE
Misclassified project

### ISSUE THREAD

**Issue by w00fz** [github/linguist#2396]
Hello,
I'm trying to fix a repository so that the dominant language is not JS but PHP. I believe the issue is that most of the PHP logic is happening in TWIG files so what i did was to follow the troubleshooting and created a `.gitattributes` and treat all `.html.twig` files as PHP lang ([reference](https://github.com/gantry/gantry5/blob/develop/.gitattributes)).

```
# Linguist Normalizer
*.html.twig linguistic-language=PHP
```

I tried to play with the `.gitattributes` on a [forked version of the repository](https://github.com/w00fz/gantry5) by un-vendoring all the JS files, just to understand if I was in the right direction. I also tried to install the `github-linguist` gem on my local to perform the tests but unfortunately [there is currently a bug with `rugged` on Mac OS X](https://github.com/libgit2/rugged/issues/475).

I'm sorry if I missed the proper documentation regarding this but it doesn't seem like adding the `.gitattributes` changed anything, is the linguist run periodically on repositories and it just didn't refresh it yet or am I missing something?

Thank you.

**Comment by arfon** [comment]
Hi @w00fz - I think you just need to set `linguist-vendored=true` here. I've opened a Pull Request with the fix here: https://github.com/w00fz/gantry5/pull/1

**Comment by w00fz** [comment]
Doh!
That is awesome, so the changes happen immediately as soon as `.gitattributes` gets pushed?
Can you tell if making the `.html.twig` files resolve to PHP will mark the project as PHP rather than JS? I would still like to show the % of JS used but it's definitely not the dominant language of the project.

Thank you for the fast response!

**Comment by arfon** [comment]
> That is awesome, so the changes happen immediately as soon as .gitattributes gets pushed?

Yes, stats are recalculated immediately after new `.gitattributes` data is committed.

> Can you tell if making the .html.twig files resolve to PHP will mark the project as PHP rather than JS?

I think the issue you're facing here is that Linguist reports lines of code (LOC) stats rather than the number of files in a particular language.

The line you have in for `.html.twig` files is setting them as PHP in the statistics but I think including the JS files means that your repo is dominated by JS by the sheer number lines of code in big files like [this](https://github.com/w00fz/gantry5/blob/develop/assets/common/js/main.js)

**Comment by w00fz** [comment]
Thank you so much, that was very helpful.
I fixed it by vendoring the compiled JS

```
# Linguist Normalizer
*.twig linguistic-language=PHP
platforms/common/js/main.js linguist-vendored=true
assets/common/js/main.js linguist-vendored=true
```
And now it looks properly classified.

Thank you again!

**Comment by arfon** [comment]
Great! Glad I could be of help.
