### ISSUE TITLE
Perl module (.pm) mis-classified as Prolog

### ISSUE THREAD

**Issue by pwr22** [github/linguist#2397]
[This](https://github.com/pwr22/Net-DNS-CloudFlare-DDNS/blob/e8cc533f62fce310cc264d89ea5687fb10763d79/lib/Net/DNS/CloudFlare/DDNS.pm) is the file

**Comment by pchaigno** [comment]
This is a consequence of #2042 :/

**Comment by arfon** [comment]
This is now fixed.
