### ISSUE TITLE
C# issue with "HTTP/1.1" term

### ISSUE THREAD

**Issue by metadings** [github/linguist#2399]
Please have a look to [Microsoft.AspNet.Server.Kestrel](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Http/Frame.cs).

**Comment by pchaigno** [comment]
You're referring to [this line](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Http/Frame.cs#L292)?

Linguist only selects the grammar to use for highlighting. [atom/language-csharp](https://github.com/atom/language-csharp) is used to highlight C# code on GitHub. You should open an issue there (check that there isn't already one opened ;)

**Comment by metadings** [comment]
okay ;)
