### ISSUE TITLE
Haxe repository miscategorized as Javascript

### ISSUE THREAD

**Issue by mlms13** [github/linguist#2400]
My [april-game](https://github.com/mlms13/april-game) repository is being labeled as 99% JS (and no mention of Haxe) despite the fact that there are 14 Haxe files while the only JS file is a `gulpfile.js`

![screen shot 2015-05-15 at 9 21 08 am](https://cloud.githubusercontent.com/assets/1105543/7655936/682e9928-fae4-11e4-8fa5-5cac6526a024.png)

![screen shot 2015-05-15 at 9 20 48 am](https://cloud.githubusercontent.com/assets/1105543/7655943/73448f34-fae4-11e4-9dad-f142c793a149.png)

I've had other Haxe repos where a generated JS file in `bin/` tips the scale in favor of Javascript instead of Haxe, and I've fixed those with `.gitattributes`, but I don't think this repository falls into that category. For some reason the language statistics bar doesn't seem to be aware of Haxe at all here.

**Comment by pchaigno** [comment]
Looks like it's because of [this file](https://github.com/mlms13/april-game/blob/master/web/lib/pixi.3.0.0-rc4.js):
```
linguist --breakdown
99.00%  JavaScript
0.97%   Haxe
0.03%   HTML

JavaScript:
gulpfile.js
web/lib/pixi.3.0.0-rc4.js
```

You can ignore it in statistics using [Linguist overrides](https://github.com/github/linguist#overrides).

**Comment by mlms13** [comment]
Ah, thanks. Now that Pixi.js is on npm, it'll end up in my `node_modules` folder which should take care of this issue.

But why is the [language search for my repo](https://github.com/mlms13/april-game/search?l=javascript) still not finding Pixi (when it's clearly part of the language stats)?

**Comment by pchaigno** [comment]
> But why is the language search for my repo still not finding Pixi (when it's clearly part of the language stats)?

That's probably a cache update issue, we have these sometimes. You can contact support@github.com to fix that.

**Comment by arfon** [comment]
This looks to be fixed now. Can you confirm @mlms13?

![screen shot 2015-05-28 at 11 28 49 am](https://cloud.githubusercontent.com/assets/4483/7865220/c1786cbe-052c-11e5-822e-62f05922fe14.png)

**Comment by mlms13** [comment]
The pixi script is now in my `node_modules` folder where it gets ignored for stats, so in that sense it's fixed. :) I'm fine with closing this.
