### ISSUE TITLE
Typescript repositories misclassified as Javascript

### ISSUE THREAD

**Issue by ChimeraCoder** [github/linguist#2403]
While linguist classifies Typescript files correctly, it also counts the Typescript-generated Javascript output towards the language breakdown, which leads to misleading reports.

This is particularly problematic because, by definition, Typescript outputs ES3, so it is almost *always* less verbose (by line count) than the equivalent transpiled Javascript. So Javascript will always appear to be the more frequently-used language in the project.

As an example, the [Electrovim](https://github.com/ChimeraCoder/electrovim) extension was written entirely in Typescript. The Javascript is included in the repository so that others can build the extension from source even if they don't have the Typescript compiler installed, as long as they have the Firefox build toolchain (which does not even depend on Javascript).

Linguist correctly identifies the Typescript files, but classifies the project as Javascript due to the auto-generated Javascript files:

Language |  Percentage
------------ | -------------
Javascript | 51.0%
Typescript | 46.8%
Makefile | 1.3%

One easy heuristic is to check for `.ts` files whose name matches a corresponding a `.js` file, and ignore the latter if the former exists. That would yield the correct result in this particular case, as well as many similar repositories. 

To be more robust, it could be possible to analyze the files themselves to see if they match. (At first glance, this may sound difficult, but since Typescript's output is intentionally a transparent mapping, even a `git diff` may be sufficient). This second approach may be overkill, but it's also worth keeping in mind.

**Comment by pchaigno** [comment]
LInguist investigates files one by one and currently isn't aware of other files.
However, [it is possible to detect generated files](https://github.com/github/linguist/blob/master/lib/linguist/generated.rb) if they contain some kind of header.

It doesn't look like it's the case for Typescript-generated JavaScript files. Alternatively, you could use [Linguist overrides](https://github.com/github/linguist#overrides).

**Comment by ChimeraCoder** [comment]
I could use `linguist-vendored`, though that seems like a slight misuse of the flag, since these files aren't vendored (just auto-generated).

As for the detection of generated files using a header, I see that source maps are excluded. Typescript can also output a source map (though that hasn't been checked into this repository). However, it seems that that would only apply to the source map file itself.

It would be great to figure out some way for linguist to classify these repositories correctly without manual intervention from the repository owner, since this is a very common problem for Typescript projects.

**Comment by pchaigno** [comment]
> I could use linguist-vendored, though that seems like a slight misuse of the flag, since these files aren't vendored (just auto-generated).

I think you can use `linguist-generated`.
<br>

> It would be great to figure out some way for linguist to classify these repositories correctly without manual intervention from the repository owner, since this is a very common problem for Typescript projects.

I agree but if these files don't have anything distinguishing them from normal JS files it's going to be difficult :/

**Comment by ChimeraCoder** [comment]
Hm, I don't doubt that, though it's not in the README, and the only reference I can find for the identifier `linguist-generated` is in a comment.

> I agree but if these files don't have anything distinguishing them from normal JS files it's going to be difficult :/

Maybe that means it's time for Linguist to start considering repository structure when determining language breakdowns at the repository level? Javascript-as-a-compilation-target has become far more common than it was in previous years, and all signs point to that increasing. (As of right now, the most recent open issue (#2400) also involves compiled JS output, though for a different issue) 

Per-file analysis works well for per-file classification, but determining the primary language of a repository by per-file line count systematically overestimates compilation targets. `.gitattributes` makes sense on a per-repository basis, but not all developers use it, and it definitely skews aggregate statistics of languages.

**Comment by mlms13** [comment]
I've also been running into this with JS files generated by the Haxe compiler. Is it true from [this](https://github.com/github/linguist/blob/master/lib/linguist/generated.rb#L128-L130) that any *.js file will be considered generated if its first line starts with `// Generated by `? I'd be happy to see if the Haxe maintainers would be willing to add that when compiling JS files.

And it's likely that this has already been discussed somewhere, but a `bin/` folder in the root of the project probably contains generated files, no? I know `dist/` is also a pretty common convention in the JS world.

**Comment by pchaigno** [comment]
>  Is it true from this that any *.js file will be considered generated if its first line starts with // Generated by?

Yes :-)
<br>

> I'd be happy to see if the Haxe maintainers would be willing to add that when compiling JS files.

Yep, that would help :+1: 
<br>

> And it's likely that this has already been discussed somewhere, but a bin/ folder in the root of the project probably contains generated files, no? I know dist/ is also a pretty common convention in the JS world.

Sure, but we can't consider all files in `bin/` or `dist/` as generated...

**Comment by arfon** [comment]
@ChimeraCoder - `linguist-generated` [is a real thing](https://github.com/github/linguist/blob/master/lib/linguist/lazy_blob.rb#L46-L52) but I agree this isn't a complete fix here as people will need to know they can set it.

> Is it true from this that any *.js file will be considered generated if its first line starts with // Generated by?

This is probably the only realistic large-scale solution right now as we don't have any plans to move away from per-file classification of languages.

**Comment by ewanh26** [comment]
What I'd do personally, to show that it was made with typescript only, is use `*.js linguist-detectable=false`, then keep the typescript files, then only typescript will be shown in the language summary, but your application can still use the javascript, since they are still there, just not being shown.
