### ISSUE TITLE
Incorrect code %s

### ISSUE THREAD

**Issue by srsudar** [github/linguist#2404]
Just for fun I'm making a [repo](https://github.com/srsudar/github-spectrum) with a large number of languages to see a pretty github color spectrum.

It starts lumping languages into "Other" at >6 languages, unfortunately, but I'm soldiering on.

It looks like the language graphs are generated by character count. This worked perfectly for the first 10 or so, and then I batched them up to 20 languages. When I pushed, the percentages are broken. See the picture below.

ABAP is incorrectly listed as 4.8%, when it has the same number of characters as action script.

I might go back and see at exactly how many languages the math starts going wonky, but for now at least, something seems to be awry.

![20_languages](https://cloud.githubusercontent.com/assets/6362625/7696602/9e363e50-fdb3-11e4-8145-cedf36363956.png)

**Comment by larsbrinkhoff** [comment]
For bonus points, try to arrange the languages to make a rainbow! :wink:

**Comment by srsudar** [comment]
It looks as if it's actually only 18 languages, as the Ant and ApacheConf files aren't recognized, likely because they're classified as "data" and "markup" in the [yaml](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml).

The command line interface for linguist appears to be detecting and calculating percentages correctly.

![screen shot 2015-05-19 at 9 38 12 am](https://cloud.githubusercontent.com/assets/6362625/7708550/47c8434e-fe0b-11e4-8ba8-41e7c05705d1.png)

**Comment by arfon** [comment]
Hi @srsudar - not sure what's going on here. My guess is that this is some kind of rounding error in the UI on GitHub giving us weird results. As this repo is being made 'for fun' and as you point out it looks like Linguist reports the correct stats here, I'm going to close this out,

**Comment by pchaigno** [comment]
Should we report it to support@github.com though?

**Comment by srsudar** [comment]
Yeah I probably will. Almost feel bad submitting bug reports for this kind of pet project thing, but it is a bug either way. At least this way they'll know about it.

I just updated the README to have snapshots at every level up through 18 languages. (I said 20 but that actually wasn't counting ant or apache conf.)

**Comment by srsudar** [comment]
Sent them a note.

**Comment by pchaigno** [comment]
> Sent them a note.

Great :+1:

**Comment by srsudar** [comment]
Heard back this very polite and reasonable response:

>Thanks for your feedback! Although we want to fix every little detail in order to improve the quality of our service, we have to prioritize work based on how likely it is to run into such troubles. In any case, I have added your feedback to our list for our team to consider. Thanks again for taking the time to send it to us! :)

Makes sense to me.
