### ISSUE TITLE
100% pure java project is classified as C++ because it has .mm files in plain on text format

### ISSUE THREAD

**Issue by ge0ffrey** [github/linguist#2411]
OptaPlanner is 100% pure java project
  https://github.com/droolsjbpm/optaplanner
yet GitHub says it's contains 59% C++ code, which it does not:
  https://github.com/droolsjbpm/optaplanner/search?l=objective-c%2B%2B

Those .mm files are just text files in a format defined by 3th party researchers. They contain data, not C++ code.

**Comment by arfon** [comment]
> Those .mm files are just text files in a format defined by 3th party researchers. 

Hi @ge0ffrey. You can use the [Linguist Overrides](https://github.com/github/linguist#overrides) to ignore these files.
