### ISSUE TITLE
syntax highlighting for jruby as an executable

### ISSUE THREAD

**Issue by KCErb** [github/linguist#2412]
Hi all,

I see that JRuby is listed as an alias for Ruby

https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L2802

but [this](https://github.com/shoes/shoes4/blob/master/shoes-swt/bin/shoes-swt) executable isn't getting syntax highlighted as ruby (like [this one](https://github.com/shoes/shoes4/blob/master/shoes-core/bin/shoes-picker) does). Not sure if this is a bug or something else but just thought I'd report.

If it's a small fix (like adding jruby to a list somewhere that it's not) I'd be happy to submit a PR.

**Comment by yegortimoschenko** [comment]
I suppose it will be fixed if you add a `#!/usr/bin/env jruby` example to `samples/Ruby` folder, [like this one](https://github.com/github/linguist/blob/b92b3af6021326c2c7b3de9b870a9723730a2243/samples/Ruby/ruby).

**Comment by pchaigno** [comment]
@KCErb - @yegortimoschenko Is right. #2413 should fix this ;)

**Comment by KCErb** [comment]
Looks great, thanks guys!
