### ISSUE TITLE
Syntax highlighting in pom (maven) files are off

### ISSUE THREAD

**Issue by SimenB** [github/linguist#2414]
I of course could not find any (public) pom file with the problem, so I'm attaching a screenshot from a private repo of mine.

![image](https://cloud.githubusercontent.com/assets/1404810/7757219/0652f3ee-0001-11e5-98bd-2593324929d9.png)

The `.version` part is a part of the tag, and should be colored as well.

Also attaching a screenshot from Atom, as from what I understand from `CONTRIBUTING.md` the problem should have been there as well.

![image](https://cloud.githubusercontent.com/assets/1404810/7757239/2abb8476-0001-11e5-90e3-17af83d905fc.png)

EDIT: Lightshow has the same error: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=text.xml.pom&grammar_url=&grammar_text=&code_source=from-text&code_url=&code=++++++++%3Cjavaee-api.version%3E7.0%3C%2Fjavaee-api.version%3E%0D%0A++++++++%3Cjunit.version%3E4.12%3C%2Fjunit.version%3E

**Comment by yegortimoschenko** [comment]
It is a bug in https://github.com/atom/language-xml or (less probability) https://github.com/textmate/xml.tmbundle.

**Comment by SimenB** [comment]
It's correct in Atom

**Comment by pchaigno** [comment]
Linguist only identifies the languages. GitHub use [textmate/maven.tmbundle](https://github.com/textmate/maven.tmbundle) to highlight Maven POM code. You should open an issue there ;)

**Comment by SimenB** [comment]
@pchaigno it's correct in the TextMate app.

![image](https://cloud.githubusercontent.com/assets/1404810/7776118/d41b86a8-00b8-11e5-86c8-274cca726e16.png)

**Comment by pchaigno** [comment]
@SimenB Did you test with the last development version of the TextMate bundle? I'm able to reproduce the issue with [Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Ftextmate%2Fmaven.tmbundle%2Fmaster%2FSyntaxes%2FMaven%2520POM.tmLanguage&grammar_text=&code_source=from-text&code_url=&code=%3Cjavaee-api.version%3E%3C%2Fjavaee-api.version%3E).

**Comment by SimenB** [comment]
@pchaigno, yeah, I included a link to lightshow in the OP.

The maven bundle was last updated 11 months ago. `brew cask install textmate` 15 minutes ago probably installed a newer version than that? The maven bundle I downloaded after starting up textmate, I think that means it's the newest? I've never used textmate, and the version installed by cask is `TextMate version 2.0-beta.7.1`

**Comment by arfon** [comment]
Closing this as the fix is required upstream and we'll automatically pick up the fix when it's made.
