### ISSUE TITLE
Ruby incorrectly reported as Groff

### ISSUE THREAD

**Issue by yegortimoschenko** [github/linguist#2415]
https://github.com/CocoaPods/Specs/search?l=groff

**Comment by pchaigno** [comment]
That's happening because the file has `.2` as extension (it's a Groff extension). If you add a proper Ruby extension or make it executable and add a shebang, Linguist will recognize it correctly.
Otherwise, you can also use [Linguist overrides](https://github.com/github/linguist#overrides).

**Comment by yegortimoschenko** [comment]
#2416 is
