### ISSUE TITLE
Some weird stuff incorrectly reported as Groff

### ISSUE THREAD

**Issue by yegortimoschenko** [github/linguist#2416]
https://github.com/matiasinsaurralde/facebook-tunnel/search?l=groff 
https://github.com/matiasinsaurralde/facebook-tunnel/blob/b82adf540c9b8c8563f7caecde135ceb9b7a9592/gumbo/autom4te.cache/traces.1

**Comment by yegortimoschenko** [comment]
Also:

 https://github.com/danielmiessler/SecLists/search?l=groff
https://github.com/danielmiessler/SecLists/blob/6babb9ec9ad6f6b594380797b78b734500c1c453/URLs/urls_joomla_3.0.3
https://github.com/danielmiessler/SecLists/blob/6babb9ec9ad6f6b594380797b78b734500c1c453/URLs/urls_wordpress_3.3.1

**Comment by pchaigno** [comment]
Same as #2415.
