### ISSUE TITLE
VBA vs. Visual Basic

### ISSUE THREAD

**Issue by peterennis** [github/linguist#2418]
VBA != vb
I can only search for Visual Basic. It returns mostly .net code and that is just noise.
VBA should be separate.

**Comment by pchaigno** [comment]
Do they use different sets of file extensions?

**Comment by peterennis** [comment]
VBA is embedded in ms office apps.

If files are exported then default is .bas

Sometimes .mod for modules or

You can make up your own.


Distribution is often inside an office app

So extensions could be

Xls, xlsx, mdb, accdb, doc, docx etc. Ad nauseum...


Someone searching for VBA is typically

Not interested in .net


Thanks


Peter


E.g.

https://www.bing.com/search?q=peterennis+github&PC=U316&FORM=CHROMN


These are VBA repos, not visual basic, so the default github

Description is false


Sent from Yahoo Mail on Android

**Comment by pchaigno** [comment]
[Linguist currently associates the following extensions with Visual Basic](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L3390-L3406):
- `.vb`
- `.bas`
- `.cls`
- `.frm`
- `.frx`
- `.vba`
- `.vbhtml`
- `.vbs`

Which of these are VBA? Visual Basic?

**Comment by peterennis** [comment]
Not .vb

Not .frx

Not .vbhtml

Not .vbs


However, I could create all them if I wanted :)


Removing those would at least reduce the search spam.


In the spirit of cross platform development, ms 

Honest embracement of os(?), and github expansion,

Perhaps you could have "Microsoft Office VBA"

As the 'language' selection?


Thanks,


Peter




Sent from Yahoo Mail on Android

**Comment by NattyNarwhal** [comment]
VBA is actually just embedded classic VB. Modern VB.NET uses .vb, but classic VB will use the older extensions like .bas and .frm.

.vbs is VBScript, which is its own language altogether.

**Comment by peterennis** [comment]
Yes. The issue us that search for VBA returns too much github spam as it brings back all results for VB. Ironically I find better results using google while searching the universe in comparison to the "targeted" subset of github.

**Comment by chadebeauche** [comment]
I confirm :+1: 
.vb => VB.NET
.bas, .cls, .frm => VBA (or to be more precise, it's originally VB6 extensions)
.frx => binary file associated with .frm
.vbs => VB Script, sort of sub-langage based on VB6
.vba and .vbhtml => no idea

If we could search for VBA code only, it will be **very** helpfull for VBA coders, have mercy for them ;)

**Comment by LukaszDev** [comment]
I agree with **chadebeauche** - also `.vbs` means VB Script what it's scripting language - it's came form VB family but is different from VB.NET and VBA.

We can consider VBS as an old, but still is in use, and should be counted as separated language.

BTW similar extension `.svb` it's also VB Script file but it's used internally in TestComplete for creating automatic test scripts - I'm not sure but probably should by considered as separate category. Typically `.svb` file contains 70-90% of VBS and 10-30% of TestComplete specific features.

**Comment by GustavBrock** [comment]
This issue persists. Some VBA repos are even being labeled as TeX. Go figure.

**Comment by GustavBrock** [comment]
I have passed this issue/proposal to the Office documentation team - asking them to take over.

**Comment by NattyNarwhal** [comment]
The situation hasn't changed to my knowledge.

**Comment by GustavBrock** [comment]
I have renewed my request to the "doc people" of Office at Microsoft to take care of this.

**Comment by NattyNarwhal** [comment]
AFAIK, this is still an issue.

**Comment by GustavBrock** [comment]
It is, but priority at MS seems low.

**Comment by smola** [comment]
Could this be reopened? As far as I can tell, this is still unresolved and it applies to latest linguist version.

**Comment by GustavBrock** [comment]
My MS contact must have gone cold; no response yet.
Could someone else perhaps pick this up? Like @linda-editor ?

**Comment by Linda-Editor** [comment]
@GustavBrock I'll see what I can do about finding the right person to address this.

**Comment by dmahugh** [comment]
I agree this VBA-vs-VB-vs-VB.net confusion is a problem, for Linguist as well as search engines in general, but it's not clear what is being requested here. As covered in the readme, Linguist ignores blobs, and XLSX/XLSM files (where most VBA code resides) are zipped blobs. Is there a specific change to Linguist that people are looking to Microsoft submit a PR for?

**Comment by GustavBrock** [comment]
@dmahugh : Browse the thread from the start. And VBA does not reside in xlsx files. However, most code has been exported to .bas or .cls text files for the benefit of the GitHub parser and for easy perusing by the visitors. If .frm files exist in a repository, it is VB6, not VBA.

**Comment by cbeauchesne** [comment]
Actually, you can have .frm files in a VBA project, if you have a "form" (basiclly, a GUI). BTW, it's by far the less common use-case.

+1 for the answer : the point here is to make a distinction between : 

* .vb => .NET world
* .cls/.bas/.frm => VB6/VBA world

**Comment by Linda-Editor** [comment]
To all of you on this thread, if you have an actionable suggestion, please submit a PR. If you're looking for documentation on VBA, please see https://docs.microsoft.com/en-us/office/vba/api/overview/.

**Comment by GustavBrock** [comment]
I see a similar pattern:

- .vb => VB.NET
- .vbs => VBScript
- (.bas and/or .cls) but no .frm => VBA
- (.bas and/or .cls) and .frm => VB6 or VBA (Word, Excel)

**Comment by zspitz** [comment]
I've tried to write a PR, but have run into [some issues](https://github.com/github/linguist/pull/4725#issuecomment-558404155). Any help would be greatly appreciated.

**Comment by peterennis** [comment]
@zspitz I have no Ruby or linguist experience. Thanks for taking this on :+1:

**Comment by zspitz** [comment]
@peterennis That makes two of us 😊.

**Comment by GustavBrock** [comment]
@zspitz That makes three of us. Sorry.

**Comment by zspitz** [comment]
ping @Linda-Editor

**Comment by zspitz** [comment]
Question: should the language name be VBA or Visual Basic for Applications?

**Comment by GustavBrock** [comment]
The name is **Visual Basic for Applications**, and **VBA** is the abbreviation for this.

**Comment by zspitz** [comment]
@GustavBrock The name of SQL is Structured Query Language, and yet the name in `languages.yml` is listed as `SQL`. Same for `eXtensible Markup Language`, `HyperText Markup Language`,  `ANother Tool for Language Recognition`, `Comma-Separated Values` and `Cascading Style Sheets`.

IMO, as long as the acronym has wide acceptance, I think makes more sense to use the acronym instead of the alternative mouthful.

**Comment by GustavBrock** [comment]
Well, you only asked for the name, not what to use in `languages.yml` - where **VBA** will be fine in my opinion.

**Comment by Gagniuc** [comment]
How to make a distinction between VB6 and VBA and VB.NET? **The .vbp and .vbw extensions are unique to the VB6 language.** Thus, if any VBA files are accompanied by files with .vbp and .vbw extensions, than all repository is Visual Basic 6.0. Just look on any of [my repositories on VB6](https://github.com/Gagniuc?tab=repositories&q=VB6&type=&language=&sort=).

In short:

VB6 - if (**.bas** and/or **.cls** and/or **.frm** and/or **.frx**) and **.vbp** and **.vbw** exist.
VBA - if (**.bas** and/or **.cls** and/or **.frm** and/or **.frx**) but **no** **.vbp** and **.vbw** exist.

VB.NET - if **.vb** exists.
VBScript - **.vbs** 

Note also that any **.xlsm** file it implies the presence of VBA. Also note that VB6 is the only programming language among these (it is fully compiled).
