### ISSUE TITLE
Github is displaying incorrect language project

### ISSUE THREAD

**Issue by roadev** [github/linguist#2421]
After merge two branches, my project changed the name of the programming language Ruby to Javascript...
Why?
As you can see, there are more files/code wrote in Ruby rather than Javascript.
https://github.com/roadev/GearApuestas2/search?l=ruby

**Comment by arfon** [comment]
Hi @roadev - these large JavaScript files are skewing the stats for your project.

![screen shot 2015-05-28 at 11 30 52 am](https://cloud.githubusercontent.com/assets/4483/7865290/1510f74c-052d-11e5-8588-3ddfb85f2c2e.png)

You can learn how to ignore these files using the Linguist overrides [here](https://github.com/github/linguist#overrides)
