### ISSUE TITLE
.ss files are not always scheme

### ISSUE THREAD

**Issue by codemac** [github/linguist#2423]
In many cases, they're related to the http://www.silverstripe.com/ project.

- https://github.com/silverstripe-australia/silverstripe-grouped-cms-menu
- https://github.com/ryanwachtl/silverstripe-foundation-theme
- https://github.com/sunnysideup/silverstripe-googleanalyticsbasics
- https://github.com/jeffwhitfield/silverstripe-bootstrap-theme
- https://github.com/ntd/silverstrap-cerulean
- https://github.com/ntd/silverstripe-gallery
- https://github.com/i-lateral/silverstripe-gallery
- https://github.com/chtombleson/mobi2go-silverstripe
- https://github.com/sunnysideup/silverstripe-typography

**Comment by larsbrinkhoff** [comment]
I also found some SaltStack files when I investigated this some time ago.

**Comment by larsbrinkhoff** [comment]
| Language | Search | Files |
| --- | --- | --- |
| SilverStripe | ["end_if" OR "end_loop" OR include](https://github.com/search?q=extension%3Ass+%22end_if%22+OR+%22end_loop%22+OR+include) | 36,232 |
| Scheme | [define OR module](https://github.com/search?q=extension%3Ass+define+OR+module) | 27,207 |
| Certificate | [certificate](https://github.com/search?q=extension%3Ass+certificate) | 4,485 |
| NCR SCSI script | [arch jump move](https://github.com/search?q=extension%3Ass+arch+jump+move) | 269 |

**Comment by pchaigno** [comment]
@arfon @bkeepers Would it be okay to add the `.ss` crypto files (Certificate Requests) in the [Public Key language](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L2567-L2573)?

**Comment by larsbrinkhoff** [comment]
@pchaigno According to [this](http://stackoverflow.com/questions/5355046/where-is-the-pem-file-format-specified), perhaps `PEM` or `Privacy Enhanced Mail` would be a better name, and then make `Public Key` group under that.

**Comment by pchaigno** [comment]
If I'm not mistaken, child languages only allow us to define a grammar different from the parent's one. It would not allow us to display it under a different name or anything.
Maybe we should find a better name for `Public Key` instead, something more generic?

**Comment by larsbrinkhoff** [comment]
I believe `PEM` is that generic (though inofficial) name for the `-----BEGIN...` format.

**Comment by arfon** [comment]
Closing this as stale. We'd welcome a Pull Request implementing any additional support for disambiguating `.ss` files.
