### ISSUE TITLE
Rust misclassified as RenderScript

### ISSUE THREAD

**Issue by thelink2012** [github/linguist#2424]
[File in question](https://github.com/dcampbell24/iup-rust/blob/eb5724fcfd51353caec22ca4711a86257f65ea63/iup-sys/src/lib.rs).

**Comment by larsbrinkhoff** [comment]
Sorry, my mistake.  Fixed in #2425.

**Comment by thelink2012** [comment]
Off curiosity how much time it takes for those changes to take effect?

**Comment by arfon** [comment]
@thelink2012 - we need there to be a new version of Linguist deployed first (which will probably be in the next couple of weeks). Also, reclassification of files only happens once updates have happened to the repository and so you'll need to push some changes to your repo once Linguist has been updated.
