### ISSUE TITLE
Some problem with installing

### ISSUE THREAD

**Issue by hnwfs** [github/linguist#2430]
install date: 2015-04-30 and report from stdout:
.....
ERROR:  Error installing github-linguist:
	escape_utils requires Ruby version >= 1.9.3.
[[ vatay@lineo : ~ ]]$ ruby --version
ruby 1.9.3p0 (2011-10-30 revision 33570) [i686-linux]

What can I making?

**Comment by pchaigno** [comment]
Works for me with 1.9.3p551. Though, this version of Ruby is not maintained anymore, you should update it ;)
