### ISSUE TITLE
DIGITAL command language showing up in private repo.

### ISSUE THREAD

**Issue by swang** [github/linguist#2433]
A private repo our company owns shows DIGITAL command language as being 34% of our codebase, which is not right. Clicking on the link shows zero results in our codebase.

Another example I found through the trending links: https://github.com/trending?l=digital-command-language shows this repo: https://github.com/michaelliao/learngit that also contain 0 results when searching for DIGITAL command language.

**Comment by larsbrinkhoff** [comment]
Do you have any files ending in `.com`?  Those are classified as "DIGITAL command language".

**Comment by swang** [comment]
Ah yes. seems odd to not look into the contents of the file though...

**Comment by larsbrinkhoff** [comment]
Maybe it's time to start doing that.  What's the contents of your `.com` files?

**Comment by swang** [comment]
They are just JSON files in our repo that don't have a .json extension and are named after randomized email addresses (thus .com).
