### ISSUE TITLE
Identifies main language as COBOL but no files identified as written in COBOL

### ISSUE THREAD

**Issue by gkobilansky** [github/linguist#2434]
Repo shows as 38.8% written in COBOL - https://github.com/wealthbot-io/wealthbot
Click on COBOL, shows 'We couldn't find any code matching ''' - https://github.com/wealthbot-io/wealthbot/search?l=cobol

**Comment by pchaigno** [comment]
The statistics aren't always in sync with the search page (it's a cache update issue). Looks like the issue is fixed now :zap:
