### ISSUE TITLE
bash syntax highlighting incorrect

### ISSUE THREAD

**Issue by bahamas10** [github/linguist#2437]
not sure if this is the right place, but the bash syntax highlighter breaks if command substitution is done inside parameter expansion

``` bash
foo=${foo:-$(date | awk '{print $0}')}

# now everything is messed up
for f in ./*.js; do
  echo "$f"
done
```

The curly braces inside the awk command throw off the outside curly braces used around the variable it seems

**Comment by pchaigno** [comment]
Linguist only selects the grammar to highlight the language based on the detection results. [atom/language-shellscript](https://github.com/atom/language-shellscript) is used to highlight Bash code. You should open an issue there ;)

**Comment by arfon** [comment]
I believe this is now fixed. Please re-open if not!
