### ISSUE TITLE
`linguist-type` flag

### ISSUE THREAD

**Issue by graymalkin** [github/linguist#2444]
It would be nice if `linguist-type` could be set on in the `.gitattributes` file in the same way `linguist-language` may be.

Specifically as a way to override things like SQL files being marked as data files, rather than programming.

**Comment by billybonks** [comment]
👍

**Comment by lildude** [comment]
This is now possible with the [`linguist-detectable` attribute](https://github.com/github/linguist#detectable). Instead of specifying a type, you specify that you'd like the files to be counted in the stats, regardless of the type.

This will go live on GitHub.com by the end of January 2018.
