### ISSUE TITLE
syntax highlighting for EDK2 configs

### ISSUE THREAD

**Issue by M1cha** [github/linguist#2450]
Tianocore EDK2 uses init files with different file extensions: https://github.com/tianocore/edk2

It would be great if you could add the file extensions inf, fdf, dec and dsc as aliases for the ini-syntax highlighter.

**Comment by pchaigno** [comment]
@M1cha Please see [the requirements and steps](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) to add support for a new language in Linguist ;)

**Comment by arfon** [comment]
:point_up: what @pchaigno said :smile:
