### ISSUE TITLE
JavaScript highlighting handles single-line comments incorrectly

### ISSUE THREAD

**Issue by Narthur** [github/linguist#2451]
Highlights everything following a single-line comment as if it is part of the comment.

Example:
https://github.com/OuachitaHillsMinistries/ohc-handbook-md2id/blob/master/markdownID.jsx

**Comment by pchaigno** [comment]
Linguist only selects the grammar. [atom/language-javascript](https://github.com/atom/language-javascript) is used to highlight JavaScript code. You should open an issue there ;)

**Comment by Narthur** [comment]
Got it. My bad. =)
