### ISSUE TITLE
Binary Files Marked as "BrainFuck"

### ISSUE THREAD

**Issue by dagrooms52** [github/linguist#2452]
Title says it all. https://github.com/AndroDevcd/Scorpion/search?l=brainfuck

**Comment by pchaigno** [comment]
Thanks for the report.
These looks like ASCII text files to me. What makes you think they are binary files? Do you know what they are? Do they correspond to some particular format/language we should recognize?

**Comment by dagrooms52** [comment]
I would contact the owner of the original repo for more details. I just saw that there was no BF code in the repo.

**Comment by AndroDevcd** [comment]
I have been creating a powerful new computer language lateley and I have developed over 100+ programs in the language. I am not yet ready for syntax coloring as the language is still in its baby stages. However If it would be ok, I could provide some basic syntax coloring for the language. 

The language is called Scorpion, and its a low level bare metal programming language that allows you to closely program the physical hardware on a device, or at least "emulate" that affect. The languages has 2 types of important files:

1. Scorpion Source: or ".ss" files will hold the somewhat high level source code written in Scorpion.
2. Scorpion Executable: or ".b" a binary file that contains only 1's 0's and white-space. 

I would like to request for you to notice all my scorpion source files ".ss" as well as my executable files ".b" in my repo.

**Comment by pchaigno** [comment]
@AndroDevcd Please see [the steps to add support for a language to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). In particular, please note the requirement on in-the-wild usage (hundreds of repositories using it on github.com).
