### ISSUE TITLE
perl is classified as Lisp

### ISSUE THREAD

**Issue by chorny** [github/linguist#2458]
https://github.com/TheOpenRepository/Text-FindIndent/search?l=common-lisp

File is https://github.com/TheOpenRepository/Text-FindIndent/blob/b6cd9d3101d2b8cbff63ec0ecd2098915f228176/lib/Text/FindIndent.pm

**Comment by arfon** [comment]
I'm afraid this is because the [Linguist Overrides](https://github.com/github/linguist#using-emacs-or-vim-modelines) are being triggered by this line:

https://github.com/TheOpenRepository/Text-FindIndent/blob/b6cd9d3101d2b8cbff63ec0ecd2098915f228176/lib/Text/FindIndent.pm#L431
