### ISSUE TITLE
LSLForge scripts not properly detected as lsl language

### ISSUE THREAD

**Issue by kyrahabattoir** [github/linguist#2461]
lslForge ( https://code.google.com/p/lslforge/ ) is a well known lsl pre processor that extends the language with the ability to write modules and include them, very much like the #include command on C preprocessors.

It stores scripts as .lslp and modules as .lslm

Once lslm/lslp scripts have been optimized and merged it generates a .lsl file that is compliant with the lsl language.

So the syntax is identical to regular lsl, with the exception of two key words: $module and $import.

**Comment by pchaigno** [comment]
We'd welcome a pull request if it is widely used on GitHub. Please see the [requirements to add a language](https://github.com/github/linguist/blob/master/CONTRIBUTING.md) ;)

**Comment by kyrahabattoir** [comment]
I would make a PR if i knew how to get it to work, personally i'd just add .lslm .lslp as valid extensions for lsl scripts. But i get the feeling that it wouldn't be acceptable?

**Comment by pchaigno** [comment]
If you follow the guidelines I linked above it should be fine. If it fails the tests, open a pull request and I'll help you.

If you don't have the time or don't want to install the environment for Ruby, could you link to a search result on GitHub showing as many examples of LSLForge script as possible?

**Comment by kyrahabattoir** [comment]
here you go:

https://github.com/search?utf8=%E2%9C%93&q=default+extension%3Alslm+extension%3Alslp&type=Code&ref=advsearch&l=

**Comment by pchaigno** [comment]
That's only 32 repositories. I don't think it'll be enough to recognize it in Linguist :/
Please consider opening a new issue or PR in the future if adoption of these extensions increases.

**Comment by kyrahabattoir** [comment]
Well all i really hoped for was the file extension to be supported but fine.
