### ISSUE TITLE
Python files wrongly identified as PLpgSQL for the Gramps-project

### ISSUE THREAD

**Issue by sam-m888** [github/linguist#2462]
Any idea why Github identifies 52.5% of the Python files are PLpgSQL files?

Definitely no PLpgSQL in the Gramps project as far as I can identify.
https://github.com/gramps-project/gramps

![gramps-project_gramps github_detects plpgsql as majority](https://cloud.githubusercontent.com/assets/8924713/8270781/243072bc-1837-11e5-93bc-ccb49d0690cd.png)
--------------
Probably unrelated but does mention PLpgSQL #2384

**Comment by pchaigno** [comment]
This is happening because of these two huge files:
- https://github.com/gramps-project/gramps/blob/master/gramps/webapp/empty.sql
- https://github.com/gramps-project/gramps/blob/master/gramps/webapp/example.sql

See [Linguist overrides](https://github.com/github/linguist#overrides) to ignore them.

**Comment by sam-m888** [comment]
Ok, I did spot those two and didn't believe them to have that much influence over the result.

Thank you
