### ISSUE TITLE
GolfScript Language

### ISSUE THREAD

**Issue by phase** [github/linguist#2464]
The GolfScript language is used a ton on [codegolf](http://codegolf.stackoverflow.com/) & on [github](https://github.com/search?utf8=%E2%9C%93&q=golfscript&type=Code&ref=searchresults).

**Comment by pchaigno** [comment]
@phase Please [the requirements and steps](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) to add support for a new language in Linguist ;)

**Comment by arfon** [comment]
Looks like there's ~200 GolfScript files on GitHub which doesn't reach [our guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) for usage/adoption. Please feel free to reopen an issue in the future if the popularity significantly increases.
