### ISSUE TITLE
Syntax hightlight slim templates

### ISSUE THREAD

**Issue by brauliobo** [github/linguist#2467]
Support slim templates (https://github.com/slim-template/slim) syntax highlighting.

One example here: https://github.com/CIRANDAS/noosfero-ecosol/blob/master/plugins/delivery/views/delivery_plugin/admin_method/_edit.html.slim

**Comment by pchaigno** [comment]
@brauliobo [Linguist already supports Slim templates](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L3148-L3154). It selects https://github.com/slim-template/ruby-slim.tmbundle for their syntax highlighting. You should open an issue there. If you know a better grammar (Sublime Text package or TextMate bundle) we can change it ;)

**Comment by brauliobo** [comment]
thanks @arfon, just opened the issue there

**Comment by arfon** [comment]
@brauliobo - this should be fixed in the next release of Linguist. The issue here I think is that the correct `tm_scope` wasn't being set. Take a look at https://github.com/github/linguist/issues/2536 for details.
