### ISSUE TITLE
Restore older version of NimLime for Nim syntax highlighting

### ISSUE THREAD

**Issue by dom96** [github/linguist#2468]
It seems that recently the syntax highlighting for Nim has been broken. Likely with [this](https://github.com/github/linguist/commit/37222d5622184be34f704c5f26f76ca4f51c8a55) change.

Could we roll that back to https://github.com/Varriount/NimLime/commit/663b417558e47ad4c9f8744cd15860652051e05d (or whatever the last commit version that was deployed to github was)?

**Comment by pchaigno** [comment]
@arfon @bkeepers Could we push a new release with grammar updates? The bug was just fixed in https://github.com/Varriount/NimLime/ (Varriount/NimLime#36).

**Comment by arfon** [comment]
This will be fixed in the next release of Linguist (later this week)

**Comment by dom96** [comment]
Thank you.
