### ISSUE TITLE
My SCSS files are shown as CSS files

### ISSUE THREAD

**Issue by leo** [github/linguist#2469]
I already contacted the Support Team about this and they told me to open an issue here. The problem is that my repository contains several SCSS (Sass) files and not a single CSS file. Nevertheless the top bar shows that 46.7% of my files are CSS files.

And now the best thing about that: If I click on the "CSS 46.7%" badge, there are simply [no files][1] listed. The reason for this is of course that I don't have a single CSS file in there, only SCSS files (and the sidebar even shows that).

I think the right fix would be if the top bar would also show those files as SCSS files (like the sidebar does it) and not as CSS files.

![thing](https://cloud.githubusercontent.com/assets/6170607/8341030/ad093eba-1ac2-11e5-89ae-b28820e522d8.png)
![thing2](https://cloud.githubusercontent.com/assets/6170607/8341031/ad09b7aa-1ac2-11e5-8031-e17ad33b6cbf.png)

[1]: https://github.com/leo/leo.github.io/search?l=css

**Comment by leo** [comment]
And while we're on it, could you please change the color of the "Liquid" templating language? It's currently merging with the border color (therefore the bar looks slightly thicker and therefore not good, in my opinion).

I thought about opening a pull request by myself for that, but I don't know which colors are already in use.

**Comment by arfon** [comment]
Hi @leo - sorry for the slow reply (and any confusion caused here). The reason the language bar is reporting `CSS` is because `SCSS` is [included in the CSS group here](https://github.com/github/linguist/blob/9d61487403c7bac7fe35ab1ffe447239f3ad82ea/lib/linguist/languages.yml#L2917). Basically, anything in the `CSS` group will be grouped into `CSS` in the language stats bar.

**Comment by leo** [comment]
No problem :blush:

I was just a little confused because the sidebar showed me something different. Now I know that this behaviour is intended.

Thanks!

**Comment by pchaigno** [comment]
> And now the best thing about that: If I click on the "CSS 46.7%" badge, there are simply no files listed. 

@arfon Shouldn't it display the SCSS files since they are in the CSS group? This behaviour seems a little off to me...

**Comment by leo** [comment]
Oh, that's definitely true! Forgot about that.
