### ISSUE TITLE
Syntax highlighting and top bar color — Liquid

### ISSUE THREAD

**Issue by leo** [github/linguist#2470]
Could you please change the color of the "Liquid" language? It's currently merging with the border color (therefore the bar looks slightly thicker and therefore not good, in my opinion). I thought about opening a pull request by myself for that, but I don't know which colors are already in use.

![screen](https://cloud.githubusercontent.com/assets/6170607/8341438/2e173654-1ac5-11e5-9fc1-58c7f25efe8b.png)

--

It also doesn't look like there's a special syntax highlighting mode for this language, it just looks like simple text strings next to HTML:

```liquid
<ul id="products">
  {% for product in products %}
    <li>
      <h2>{{ product.name }}</h2>
      Only {{ product.price | price }}

      {{ product.description | prettyprint | paragraph }}
    </li>
  {% endfor %}
</ul>
```

**Comment by pchaigno** [comment]
If you can install the development environment, you can add a color and there's a test to check that it doesn't collide with other colors.

 I can also test colors for you but that'll be a slower process.
Does Liquid have a logo we could use for a first idea of color?

For the syntax highlighting issue, it's probably not something we can fix here. Linguist only selects the grammar. In the case of LIquid, it uses [bastilian/validcode-textmate-bundles](https://github.com/bastilian/validcode-textmate-bundles). Alternatively, if you know a better grammar (TextMate bundle or Sublime Text package) we can change it ;)

**Comment by leo** [comment]
No, Liquid currently doesn't have an official logo. But since the word "liquid" can be associated with water, many themes for Sublime Text (as an example) and some websites simply use a raindrop for that. Therefore I guess using a light-blue color would be the best.

Maybe something like `#7ed4f8` would be fitting? I also checked the `languages.yml` file and there's no other language associated to this color.

--

P.S.: I don't know who to ask for this, but I definitely think the `border` attribute of the language bar should be set to `0` (maybe this issue is the right place). It's just unnecessary and makes the design look bad as soon as some light colors come into play:

**Before:**
![before](https://cloud.githubusercontent.com/assets/6170607/8396498/83d224f6-1da8-11e5-8b22-d03f16f6b62e.png)

**After:**
![after](https://cloud.githubusercontent.com/assets/6170607/8396499/90239442-1da8-11e5-9a91-37ba63145c2d.png)

(Please take a look at the big version of those, then you'll notice the difference)

I also think that arguing with "no, let's just avoid light colors" won't be really useful - there are just too many languages on GitHub and each one needs a color (and even if it doesn't have one, the default grey color also merges with the border).

Just to be clear, I'm talking of the element `.repository-lang-stats-graph`.

**Comment by pchaigno** [comment]
> Maybe something like #7ed4f8 would be fitting? I also checked the languages.yml file and there's no other language associated to this color.

`#7ed4f8` is colliding with RAML's `#77d9fb` (see http://github.github.io/linguist/).
<br>

> I don't know who to ask for this, but I definitely think the border attribute of the language bar should be set to 0 (maybe this issue is the right place).

We can't fix this here. You should report it at support@github.com ;)

**Comment by leo** [comment]
Okay. If `#7ed4f8` is colliding with another language, how can I test new colors by myself?

Didn't find any information about this within the README or CONTRIBUTING file.

**Comment by pchaigno** [comment]
You'll need to fork the repository, add a color for Liquid (see `languages.yml`) and test.
See [CONTRIBUTING.md](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#testing) for tests.

**Comment by leo** [comment]
I've followed the instructions within the "Testing" section and cloned the repo and moved into the directory using `cd`. Then I've tried executing `script/bootstrap` but the only thing that I got back was the following:

```command
script/bootstrap: line 7: bundle: command not found
```

After this response, I even tried running a test using `bundle exec rake test` but this command doesn't seem to exist. What did I do wrong?

--

I know there's also the option to let Travis CI do the testing, but that means I would have to open a new pull request for each color to test, wouldn't I? Therefore not really useful.

**Comment by pchaigno** [comment]
You'll need a Ruby dev environment. [RVM](https://rvm.io/rvm/install) is, imo, the easiest option to install it: `\curl -sSL https://get.rvm.io | bash -s stable --ruby`.

Alternatively, if you connect to Travis CI you can enable builds for your fork of Linguist. Then, you'll only have to make your changes in your fork and Travis CI will tell you if it worked ;)

**Comment by leo** [comment]
I've installed the dev environment but I'm still not able to get this thing working. I also tried forking the project and then letting Travis CI do the rest, but [it doesn't seem to work][1].

Maybe you could set up a simple light-blue color for Liquid? It doesn't need to be a specific HEX.

[1]: http://snippi.com/s/59kbw29

**Comment by pchaigno** [comment]
> I've installed the dev environment but I'm still not able to get this thing working.

What's the error you're getting?

> I also tried forking the project and then letting Travis CI do the rest, but it doesn't seem to work.

Would you by any chance have a student pack account on Travis CI? [That may explain it](http://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure).

> Maybe you could set up a simple light-blue color for Liquid? It doesn't need to be a specific HEX.

I'll try that when I get home.

**Comment by leo** [comment]
> What's the error you're getting?

[This][1] happens, when I try to call the `script/bootstrap` script. After that, I also tried it as root user, but all I got was [this][2].

> Would you by any chance have a student pack account on Travis CI?

I'm not sure - the "Account" page on Travis CI doesn't seem to include this information. But I'm definitely sure that I have one on GitHub (no idea how this is related).

> I'll try that when I get home.

:ok_hand:

[1]: http://snippi.com/s/ekdkw3g
[2]: http://snippi.com/s/jgrkxr4

**Comment by leo** [comment]
Haha, just found out that "Travis CI Pro" is something like a standalone version of the original "Travis CI" (really confusing). But just to clarify it: I'm only signed up for "Travis CI" (travis-ci.org), I never used the other one.
