### ISSUE TITLE
SQL not working?

### ISSUE THREAD

**Issue by jjb** [github/linguist#2472]
See section "Now you can start setting up the Foreign Data Wrapper" here https://github.com/jjb/holycorn/tree/patch-1

And I'll try it right here as well...

```sql
DROP EXTENSION holycorn CASCADE;
CREATE EXTENSION holycorn;
CREATE SERVER holycorn_server FOREIGN DATA WRAPPER holycorn;
CREATE FOREIGN TABLE holytable (some_date timestampz) \
  SERVER holycorn_server
  OPTIONS (wrapper_path '/tmp/source.rb');
```

**Comment by pchaigno** [comment]
It looks like this is because of the `EXTENSION` keyword.
However, Linguist only selects the appropriate grammar. It uses [textmate/sql.tmbundle](https://github.com/textmate/sql.tmbundle) for SQL code. You should open an issue there ;)

**Comment by arfon** [comment]
> You should open an issue there ;)

:+1:
