### ISSUE TITLE
Java enums and annotations

### ISSUE THREAD

**Issue by ming13** [github/linguist#2473]
It seems like the highlighting of Java `enum` types with annotations set is a little bit off. [Example](https://github.com/hawkular/hawkular-android-client/blob/d0df3e2b225b21437649b3d6c2067c6ffb6c8613/src/main/java/org/hawkular/client/android/backend/model/AlertType.java#L25-L27).

**Comment by pchaigno** [comment]
Linguist only selects the appropriate grammar for highlighting. In the case of java, it uses [this TextMate bundle](https://github.com/textmate/java.tmbundle). You should open an issue there ;)

**Comment by ming13** [comment]
Thank you for the redirect, just posted the issue there as you can see.

**Comment by arfon** [comment]
Closing as we'll pick up the fix when we update the grammars.

**Comment by ming13** [comment]
It was fixed via textmate/java.tmbundle#38. Is it possible to fetch and deploy the latest `java.tmbundle`?

**Comment by pchaigno** [comment]
> Is it possible to fetch and deploy the latest java.tmbundle?

Grammars are updated with each new release ;)

**Comment by ming13** [comment]
Thanks! Any ETA on this? Haven’t found any timeline or similar :confused:

**Comment by pchaigno** [comment]
It's usually every couple weeks (last one was a week ago).

**Comment by ming13** [comment]
All right, thanks again!
