### ISSUE TITLE
Incorrect comment syntax highlighting in Scala code diff

### ISSUE THREAD

**Issue by danvk** [github/linguist#2475]
On [this diff][1], I see comments being added on the right. The corresponding section on the left also shows up as being commented, even though it is not:

![pasted_image_at_2015_06_29_05_00_pm_1024](https://cloud.githubusercontent.com/assets/98301/8418714/fc6c733c-1e82-11e5-9d8f-bc19da85b68a.png)

This is quite misleading!

[1]: https://github.com/hammerlab/guacamole/pull/311/files#diff-5164f4a138a75d7f3a67b96253106845

**Comment by pchaigno** [comment]
I think this is happening because the highlighting is based on the unified view only. Anyway, it's not something that can be fixed here. You should report it at support@github.com ;)

**Comment by arfon** [comment]
Yep this is a GitHub bug I think (rather than a Linguist one). If you haven't already please report this to support@github.com
