### ISSUE TITLE
wrong language: Modelica

### ISSUE THREAD

**Issue by thorade** [github/linguist#2486]
From the list of trending repositories mainly written in Modelica language:
https://github.com/trending?l=modelica
almost all are correct, but the following repos are wrongly detected as Modelica:
https://github.com/twitter/effectivescala
https://github.com/asamardzic/tempo

Some typical characteristics of Modelica files:
- First line of the file starts with the word `within`.
- Last line of the file starts with the word `end`.
- Frequent keywords are `package`, `model`, `function`, `extends`, `parameter`, `input`, `output`, `protected`, `equation`, `algorithm`, `connect`, `annotation`, `Modelica.SIunits`.

Examples of correct Modelica files are here:
https://github.com/modelica/Modelica
https://github.com/iea-annex60/modelica-annex60
https://github.com/xogeny/ModelicaBook/tree/master/ModelicaByExample

As suggested by the guidelines for contributing, I'll add some more sample files.

**Comment by pchaigno** [comment]
Since Modelica is the only language with a registered `.mo` extension, all `.mo` files will be recognized as Modelica. Do you know what [those files](https://github.com/twitter/effectivescala/search?l=modelica) are?

**Comment by thorade** [comment]
I think they are PEG markdown files, because the Readme mentions it.
I can also try and file an issue with them and ask to change the extension.

And after all, two repositories marked in the wrong language is also not a big problem...

**Comment by pchaigno** [comment]
> I can also try and file an issue with them and ask to change the extension.

I think that would be best. They can also use [Linguist overrides](https://github.com/github/linguist#overrides) to fix the issue.

**Comment by thorade** [comment]
Closing this issue, as it is more easily fixed elsewhere.
