### ISSUE TITLE
Language stats bar does not work in Firefox for Android

### ISSUE THREAD

**Issue by erikano** [github/linguist#2490]
Hi, so, this might not be the right repository to report this issue in(?) but anyway, here's the thing.

In Firefox on Android, I can't click the language stats bar in any repository. No matter where I touch the screen close to the language stats bar, surrounding elements such as *commits*, *branches*, *releases*, *contributors* are selected instead.

Please make the language breakdown easily accessible on mobile.

**Comment by pchaigno** [comment]
> this might not be the right repository to report this issue in(?)

You're right, it's not :smile: 
You should report this to support@github.com ;)

**Comment by erikano** [comment]
@pchaigno thanks, I will -- or, rather, I'll use the form at https://github.com/contact.
