### ISSUE TITLE
AGS-Script rendered as Markdown

### ISSUE THREAD

**Issue by ManiacTwister** [github/linguist#2492]
AGS-Script Files (.asc) are rendered as markdown while they should be rendered as c/c++

See here for a example: https://github.com/github/linguist/blob/master/samples/AGS%20Script/GlobalScript.asc

According to https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L36 AGS-script is supported so i don't really know how to fix this.

**Comment by arfon** [comment]
I'm pretty sure this is because it's been interpreted as AsciiDoc: https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L209

@bkeepers @gjtorikian is there anything we can do to stop this from happening?

**Comment by pchaigno** [comment]
I think this is happening because [github/markup](https://github.com/github/markup) relies on the file extension to determine if it should be rendered (as Markdown, AsciiDoc, etc.). Maybe it should rely on Linguist detection results instead?

**Comment by pchaigno** [comment]
Actually, this has been discussed before at github/markup#468 ;)

**Comment by arfon** [comment]
Ok closing as this is already being tracked elsewhere and isn't a Linguist issue.
