### ISSUE TITLE
Samples have not been updated for the 4.5.8 gem release

### ISSUE THREAD

**Issue by brainwater** [github/linguist#2495]
The samples.json file appears to be out of date in the gem release of 4.5.8. Since it does not contain the samples for the 'Linux Kernel Module' language, it has an error at https://github.com/github/linguist/blob/v4.5.8/lib/linguist/classifier.rb#L131 due to that language not being in the tokens. It fails while running against apache cassandra, specifically it fails against the file https://raw.githubusercontent.com/apache/cassandra/418c7936fb61ca3e385326bddb55ee4a81e97d53/test/conf/cassandra-rackdc.properties

**Comment by pchaigno** [comment]
@arfon That seems quite problematic. Should we make a new release?

**Comment by arfon** [comment]
This is weird, the gem building step [generates the samples automatically](https://github.com/github/linguist/blob/master/Rakefile#L42-L47). @brainwater - are you running the gem locally?

**Comment by arfon** [comment]
OK, I can reproduce the bug. Not exactly sure what's happened here but I'll make a 4.5.9 release ASAP.

**Comment by arfon** [comment]
@brainwater - I've released a new gem here: https://rubygems.org/gems/github-linguist/versions/4.5.9 - this will be live on GitHub soon but this should fix the error you're experiencing.

**Comment by brainwater** [comment]
@arfon Great, thanks! I checked it and it works now.
