### ISSUE TITLE
Incorrect Code Highlighting Over Macros in C++

### ISSUE THREAD

**Issue by burz** [github/linguist#2503]
When a quote within a macro is split over two lines using a backslash, the syntax highlighting counts the close quote character as a begin quote character, thereby highlighting the rest of the code incorrectly.

Here's an example:

https://github.com/bloomberg/bde/blob/master/groups/bsl/bslstl/bslstl_deque.h#L157

**Comment by pchaigno** [comment]
Linguist only selects the appropriate grammar for highlighting. In the case of C++, it uses [this TextMate bundle](https://github.com/textmate/c.tmbundle). You should open an issue there ;)

**Comment by arfon** [comment]
> You should open an issue there ;)

Yes, please report the issue in https://github.com/textmate/c.tmbundle - as bug fixes are made upstream we pull changes in.

**Comment by burz** [comment]
Thanks guys, I added to https://github.com/textmate/c.tmbundle/issues/5

It's somewhat disappointing that this has been a problem for three years.
