### ISSUE TITLE
xBase: add extension .prw

### ISSUE THREAD

**Issue by imsys** [github/linguist#2504]
As @vszakats said in #2498, xBase is an umbrella term for all languages in this family, and that includes AdvPL that mainly uses the .prw extension

Usage in GitHub:
https://github.com/search?p=7&q=extension%3Aprw+function&ref=searchresults&type=Code&utf8=%E2%9C%93

**Comment by pchaigno** [comment]
> Usage in GitHub:
https://github.com/search?p=7&q=extension%3Aprw+function&ref=searchresults&type=Code&utf8=%E2%9C%93

Looks good to me :+1: (only binary files and AdvPL files)

Could you open a pull request to add that extension to [the xBase entry](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L3790-L3797)? (Please see the [guidelines for that](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language).)

**Comment by vszakats** [comment]
Strange, if this looks good, while a primary xBase extension like `.ch` doesn't.

**Comment by arfon** [comment]
> Strange, if this looks good, while a primary xBase (Clipper) extension like `.ch` doesn't.

This is mostly about getting the `.ch` usages properly identifier. As @pchaigno said in [this comment](https://github.com/github/linguist/pull/2498#issuecomment-120868894):

> Okay, so we should identify those files. With the pull request as-is, they will all be detected as xBase :/

Before #2498 can be merged we need to be confident we're not going to mis-classify [these ~7000 files](https://github.com/search?p=1&q=extension%3Ach+NOT+define+NOT+command&ref=searchresults&type=Code&utf8=%E2%9C%93) `.ch` files that _aren't_ `XBase`

**Comment by vszakats** [comment]
Of these ~7000, it will be fairly complicated to do that for the thousands of duplicates of the `lzo1*.ch` files, which use similar format as `.ch` with some extra C code. `.ch` files (which stands for *C*lipper *H*eader) use similar PP directive syntax as `.h` headers for C do. I think LZO misuses `.ch` extension for their `.c` files and I'm not sure it's the best choice to design around the exception.

Apart from this peculiar case, it's quite easy to identify `.ch` files using this [regexp](https://www.debuggex.com/r/dMIeOfYAk1y0Nbd-): 
```
^\s*#\s*(if|ifdef|ifndef|endif|define|command|xcommand|translate|xtranslate|include|elif|else|pragma|error|warning|stdout|line|undef)\b
```

**Comment by arfon** [comment]
@imsys - would you mind opening a pull request to add this extension to `xBase`? You can read how to do that [here](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language)

**Comment by imsys** [comment]
@arfon, I'm just not sure if I have to add a sample file. It's basicaly the same as a .prg.

It's probably a good thing to add. I will do it tomorrow.

**Comment by arfon** [comment]
> It's probably a good thing to add. I will do it tomorrow.

OK thanks. Yes, just adding an extension and a sample file should do it :+1:

**Comment by arfon** [comment]
Ping @imsys - are you still interested in adding this?

**Comment by imsys** [comment]
Sorry for the delay: #2537

**Comment by arfon** [comment]
Thanks @imsys
