### ISSUE TITLE
language-xbase: grammar fixes upstream

### ISSUE THREAD

**Issue by vszakats** [github/linguist#2509]
There have been fixes committed upstream for xBase grammar rules:
https://github.com/hernad/atom-language-harbour/commit/3f77776e98054b5ae53f13b14b4da1656497ce41

What is the procedure to update this submodule to the latest HEAD revision?

Here's my diff attempt (sadly I'm unable to make a clean PR about it ATM):
```diff
diff --git a/vendor/grammars/language-xbase b/vendor/grammars/language-xbase
index 86f0c6c..3f77776 160000
--- a/vendor/grammars/language-xbase
+++ b/vendor/grammars/language-xbase
@@ -1 +1 @@
-Subproject commit 86f0c6c370c56c95d1b1ac9f3dbdca3b31d482bb
+Subproject commit 3f77776e98054b5ae53f13b14b4da1656497ce41
```

**Comment by pchaigno** [comment]
All grammars are updated with each new release of Linguist ;)

**Comment by vszakats** [comment]
Oh great. [I was wondering because the initial rules just kicked in on GitHub (nice!) and they are still pointing to the original upstream commit.] Awaiting to see the updated on a new release. Thanks!
