### ISSUE TITLE
Failing tests: TestGrammers #test_submodules_have_licenses, #test_local_scopes_are_in_sync

### ISSUE THREAD

**Issue by joelparkerhenderson** [github/linguist#2511]
When I clone, then `rake`, there are two failing tests -- is there a quick/easy way to address these? Thanks!

  1) Failure:
TestGrammars#test_submodules_have_licenses [/Users/joel/git/joelparkerhenderson/linguist/test/test_grammars.rb:106]:
The following grammar submodules don't seem to have a license. All grammars must have a license that permits redistribution.

  2) Failure:
TestGrammars#test_local_scopes_are_in_sync [/Users/joel/git/joelparkerhenderson/linguist/test/test_grammars.rb:54]:
script/convert-grammars failed

**Comment by pchaigno** [comment]
> The following grammar submodules don't seem to have a license. All grammars must have a license that permits redistribution.

You need to initialize all submodules with `git submodule update --init --recursive` or `git clone --recursive` ;)
