### ISSUE TITLE
Smalltalk files are getting tagged as html

### ISSUE THREAD

**Issue by fawind** [github/linguist#2517]
When a smalltalk (.st) file contains a raw byte array it gets tagged as html.

Example: [settingsIcon.st](https://github.com/HPI-SWA-Teaching/SWT15-Project-12/blob/ef390fa274f313fb39fc1821f49e2b835c183e82/packages/Algernon.package/ALGIconFactory.class/class/settingsIcon.st)
```
icons
settingsIcon

	^  '(Form
	extent: 48@48
	depth: 32
	fromArray: #( 0 0 0 0 0 0 0 0 0 0  [...] )
	offset: 0@0)'
```

Edit: There seems to be a general problem with smalltalk marked as html: [wrong tags](https://github.com/HPI-SWA-Teaching/SWT15-Project-12/search?l=html)

**Comment by arfon** [comment]
Thanks for reporting this @fawind. We added `.st` as an extension for HTML back in https://github.com/github/linguist/pull/1120 for StringTemplate files.

In the short term you can fix the repository stats for your repository by using [Linguist Overrides](https://github.com/github/linguist#using-gitattributes) to set the language. 

In the longer term I think we might need to add a new heuristic to help disambiguate these two languages.
