### ISSUE TITLE
Allow .gitattributes to set syntax highlighting for files with custom extensions.

### ISSUE THREAD

**Issue by josephjoaquinmartin** [github/linguist#2518]
currently you can set file extensions to point to different languages for your project from the .gitattributes file. Unfortunately these changes do not change the syntax highlighting for those files (you still have to use magic comments in the files)

This is a ticket to extend the behaviour here so the language detection also adds in the syntax highlighting.

(as per https://github.com/github/linguist/issues/2367#issuecomment-123261091)

**Comment by eugeneia** [comment]
I would be very happy for that feature to exist!

**Comment by incertia** [comment]
wouldn't this be an editor feature and not a linguist feature? unless you mean syntax highlighting on the github page...

**Comment by eugeneia** [comment]
@incertia I have the problem that linguist fails to recognize lots of my files which leads to broken syntax highlighting. I need a feature that lets me "turn off" syntax highlighting selectively.

**Comment by arfon** [comment]
Agreed this would be a useful feature. Closing this issue as it's a dup of https://github.com/github/linguist/issues/1792
