### ISSUE TITLE
.sublime-settings detected as JavaScript

### ISSUE THREAD

**Issue by HoBi** [github/linguist#2519]
Why is .sublime-settings detected as JavaScript file?

[There](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml) is everything for Sublime Text marked as JavaScript files, but a lot of them are JSON, aren't they?

**Comment by pchaigno** [comment]
Those extensions were moved in #1888 to JavaScript for syntax highlighting reasons apparently (they allow comments so technically, they are JavaScript files).
