### ISSUE TITLE
Default to C# instead of SmallTalk for .cs files (important for gist.github.com)

### ISSUE THREAD

**Issue by nelsonlaquet** [github/linguist#2520]
Because Linguist seems to default to SmallTalk instead of C# when all it sees is the filename, gist will configure its editor for SmallTalk instead of C# after you specify a file extension. However, once you submit the gist, Linguist properly does identify the code as C#.

So while the final gist is properly colored, the editor isn't. This makes the fancy text editor kinda useless to me considering most of my gists are of C#.

I would vote for it to default (at first glance) to the vastly more popular language (C#), over a language that is rarely used.

**Comment by arfon** [comment]
Thanks for this feedback @nelsonlaquet. This is actually an issue with Gist and not Linguist. Would you mind reporting this to support@github.com ?
