### ISSUE TITLE
Some NDK generated files marked as D language files

### ISSUE THREAD

**Issue by sbuberl** [github/linguist#2521]
Some text files that I guess are built as part of Android NDK process also have a D extension, and they're being up as D the language.

Here's an example: https://github.com/lightbox/PhotoProcessing/tree/master/PhotoProcessing/obj/local/armeabi/objs/imageprocessing

Ideally, these files shouldn't be checked in.  But searching "ndk language:D" reveal 57 results that marked as like 50% D which have no real D code.

**Comment by pchaigno** [comment]
@sbuberl Thanks for the report!

These files can be ignored using [Linguist overrides](https://github.com/github/linguist#overrides) ;)

**Comment by sbuberl** [comment]
Well I wasn't asking for my projects so much as cleaning up non-D projects when I'm doing a search by the language
