### ISSUE TITLE
Identify MPEG DASH manifests (.mpd) as XML files

### ISSUE THREAD

**Issue by GeneticGenesis** [github/linguist#2523]
.mpd is the extension for MPEG DASH manifest files, see a few examples [here](https://github.com/mozilla/gecko-dev/blob/b6ea902b969546b6ae6c2d43e68b193bfb48716e/dom/media/mediasource/test/bipbop/bipbop_dash.mpd), [here](https://github.com/sfvideo/sash/blob/master/0.1/dash-live.mpd) and [here](https://github.com/zencoder/go-dash/blob/master/examples/live.mpd).

Unfortunately, ".mpd" seems to be used for lots of other things. I anticipate a large growth in repositories using this for manifests.

In general, how is it handled when an extension catches several pre existing usages?

Otherwise, I'm happy to make a PR for this change.

**Comment by GeneticGenesis** [comment]
In the same light, identifying .m3u8/.m3u files would be pretty cool too - it doesn't look like they're identified as playlist files. Looks like there's over a thousand examples in public github too.

**Comment by pchaigno** [comment]
We could add `.mpd` to the XML extensions. Then, these files would be highlighted correctly. However, they still won't be part of the repository statistics, as they are data files ;)
