### ISSUE TITLE
Single quote character problematic in CoffeeScript

### ISSUE THREAD

**Issue by mdouglasbrett** [github/linguist#2529]
Hi guys, 

Hope you're ok, I came across this when I was looking through a README (https://github.com/zooniverse/Panoptes-Front-End):

```coffee
<ChangeListener target={auth}>{=>
  <PromiseRenderer promise={auth.checkCurrent()}>{(user) =>
    if user?
      <p>User is {user.display_name}</p>
    else
      <p>Nobody's signed in.</p>
  }</PromiseRenderer>
}</ChangeListener>
```
The single quote starts a string that doesn't end. I had a go at escaping it and I'm not sure that you can:

```coffee
<ChangeListener target={auth}>{=>
  <PromiseRenderer promise={auth.checkCurrent()}>{(user) =>
    if user?
      <p>User is {user.display_name}</p>
    else
      <p>Nobody\'s signed in.</p>
  }</PromiseRenderer>
}</ChangeListener>

```

Is this a bug, or am I missing something incredibly obvious?

All the best,

Mike

**Comment by pchaigno** [comment]
@mdouglasbrett Linguist only selects the appropriate grammar for highlighting. In the case of JavaScript, it uses [this Atom grammar](https://github.com/atom/language-coffee-script). You should open an issue there ;)

**Comment by mdouglasbrett** [comment]
Cool. Done :)
