### ISSUE TITLE
JavaScript is broken

### ISSUE THREAD

**Issue by bucaran** [github/linguist#2530]
Hi. JavaScript the syntax highlighting is broken and this is affecting me in both Atom and GitHub code viewer. Please see the attached images.

![untitled 2](https://cloud.githubusercontent.com/assets/8317250/9020487/9b1bffa4-3849-11e5-99f0-1d51ba9ecdf1.png)
![untitled](https://cloud.githubusercontent.com/assets/8317250/9020488/9c83db8c-3849-11e5-8512-05e7754326a0.png)

**Comment by bucaran** [comment]
The problem goes away if I change the constructor signature:

```js
constructor ({ host, root = "", plugins = [] }) {
```

**Comment by pchaigno** [comment]
@bucaran Linguist only selects the appropriate grammar for highlighting. In the case of JavaScript, it uses [this Atom grammar](https://github.com/atom/language-javascript). You should open an issue there ;)

**Comment by bucaran** [comment]
@pchaigno Thanks!

**Comment by 50Wliu** [comment]
@pchaigno this should now be fixed.  Linguist just needs to update to atom/language-javascript@2766ff3052615016e53298ee715e221cd740b5a3 (v0.87.1).  Upgrading should also fix a regression with consts introduced in the last grammar update.

**Comment by pchaigno** [comment]
@50Wliu Nice! Grammars are updated with each new release of Linguist ;)

**Comment by arfon** [comment]
As of `v4.5.11` today this should be fixed.

**Comment by bucaran** [comment]
Good job folks. You make my job easier.
