### ISSUE TITLE
R / Rebol Disambiguation

### ISSUE THREAD

**Issue by jimhester** [github/linguist#2531]
Rebol repositories currently miss-classified as R repositories.

- https://github.com/Oldes/REBOL-scripts
- https://github.com/angerangel/rebolide/tree/master/local
- https://github.com/angerangel/rebolforum
- https://github.com/bitbegin/RebolSCard
- https://github.com/jankom/RebToStatic/blob/master/primo.r
- Search with more https://github.com/search?q=language%3Ar+rebol&type=Repositories&utf8=%E2%9C%93

R repositories miss-classified as Rebol repositories.
- https://github.com/hadley/memoise
- https://github.com/hadley/classifly
- https://github.com/opower/rbundler
- https://github.com/asheshwor/np-quake
- https://github.com/BrunildaBalliu/TrioEpi
- Search with more https://github.com/search?utf8=%E2%9C%93&q=language%3Arebol+user%3Acran&type=Repositories&ref=searchresults

In particular one very user visible place where this comes up is when creating a gist, files with `.R` extensions are labeled as `Will render as Rebol.`.  The actual highlighting done with the gist seems correct however, so perhaps the highlighting is being done differently than the language display.

The heuristics from (https://github.com/draegtun/linguist/commit/bb2afbb03dbce9b39989edd876cdb41fe482690b) or ([pchaigno/linguist/lib/linguist/heuristics.rb#L81-L84](https://github.com/pchaigno/linguist/blob/282c15d78daf3f85b842601fcc077ddf5cdee494/lib/linguist/heuristics.rb#L81-L84)) seem like they would work well as Rebol files seem to require a `REBOL []` line to begin them, so this should disambiguate basically everything.  However those changes do not currently exist in the current master (https://github.com/github/linguist/blob/master/lib/linguist/heuristics.rb).  Another heuristic that could be used is the vast majority of R files use an uppercase `.R` for the extension.  Rebol files almost always use a lower case `.r`.

I can make a pull request with the proposed heuristic if you would like.

**Comment by yoavram** [comment]
This is an [R gist](https://gist.github.com/yoavram/198493cebbf0b323a9d8) that is identified as Rebol.
I even added a `.gitattributes` with `* linguist-language=R` as suggested to me [on twitter](https://twitter.com/thosjleeper/status/628170084641583104) but it didn't help.

**Comment by pchaigno** [comment]
> In particular one very user visible place where this comes up is when creating a gist, files with .R extensions are labeled as Will render as Rebol.. The actual highlighting done with the gist seems correct however, so perhaps the highlighting is being done differently than the language display.

GitHub support is aware of that issue and a fix is coming (see #2520 and [#1797 (comment)](https://github.com/github/linguist/pull/1797#issuecomment-126925995)).

> I even added a .gitattributes with * linguist-language=R as suggested to me on twitter but it didn't help.

This override only works for repositories :/

> The heuristics from (draegtun@bb2afbb) or (pchaigno/linguist/lib/linguist/heuristics.rb#L81-L84) seem like they would work well as Rebol files seem to require a REBOL [] line to begin them, so this should disambiguate basically everything. However those changes do not currently exist in the current master (https://github.com/github/linguist/blob/master/lib/linguist/heuristics.rb).

Hm, those are very old. I'm not sure why or when they were removed :/

> I can make a pull request with the proposed heuristic if you would like.

:+1: 

> Another heuristic that could be used is the vast majority of R files use an uppercase .R for the extension. Rebol files almost always use a lower case .r.

The detection by extension is case-insensitive since #2087 ;)

**Comment by arfon** [comment]
@pchaigno looks like the `R/Rebol` heuristics were removed in https://github.com/github/linguist/commit/7b41346db8f1f1b5a45297b6fdb9ed6c13a43a48#diff-e56a8d50b1a75fc4212ffb3504faa007

**Comment by arfon** [comment]
OK this should be fixed now @jimhester. I went through and manually re-calculated the language statistics for the repositories that you listed. The others will automatically update when changes are pushed to the repos.

**Comment by yoavram** [comment]
My gist  is still recognized as Rebol.
https://gist.github.com/yoavram/198493cebbf0b323a9d8

**Comment by arfon** [comment]
> My gist is still recognized as Rebol. https://gist.github.com/yoavram/198493cebbf0b323a9d8

No, we're correctly detecting it as `R` - see this screenshot:

![screen_shot_2015-08-06_at_7_41_38_am](https://cloud.githubusercontent.com/assets/4483/9105364/cc4be47c-3c0e-11e5-9e03-a9c39a3eb4b7.png)

**Comment by pchaigno** [comment]
> My gist is still recognized as Rebol.
https://gist.github.com/yoavram/198493cebbf0b323a9d8

@yoavram The bug I was mentioning before is that it says `Will render as Rebol.` when it's actually rendered correctly ;)

**Comment by yoavram** [comment]
OK, I don't see the "will render as Rebol", but why is the " in" in `in.fname` highlighted?

**Comment by pchaigno** [comment]
That's an issue with [the grammar GitHub uses to highlight R code](https://github.com/textmate/r.tmbundle). I can reproduce [the bug in Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Ftextmate%2Fr.tmbundle%2Fmaster%2FSyntaxes%2FR.plist&grammar_text=&code_source=from-text&code_url=&code=%23+install%0D%0Asource%28%22http%3A%2F%2Fbioconductor.org%2FbiocLite.R%22%29%0D%0AbiocLite%28%22flowCore%22%29%0D%0A%0D%0A%23+convert%0D%0Alibrary%28flowCore%29%0D%0Ain.fname+%3C-+%27flow123.LMD%27%0D%0Afolder+%3C-+%27C%3A\\users\\user\\flow\\%27%0D%0Ax+%3C-+read.FCS%28paste0%28folder%2C+in.fname%29%29%0D%0Asummary%28Xx%29%0D%0Aout.fname+%3C-+paste0%28file_path_sans_ext%28in.fname%29%2C+%27.fcs%27%29%0D%0Awrite.FCS%28x%2C+paste0%28folder%2C+out.fname%29%29%0D%0A%0D%0A). You should open an issue on the grammar repository ;)

**Comment by ppernot** [comment]
Hi, 

[these](https://github.com/ppernot/Reproducible-Research/search?l=rebol) R files in my projects are incorrectly identified as Rebol.

**Comment by larsbrinkhoff** [comment]
Hey @Alhadis, here's a defective grammar!

**Comment by Alhadis** [comment]
Eh? Which grammar is being defective? It looks fine to me...

<img src="https://cloud.githubusercontent.com/assets/2346707/18263300/5abd952c-744c-11e6-88dd-2967fe8f5052.png" width="457" alt="Figure 1" />

Note that after clicking @pchaigno's [link](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Ftextmate%2Fr.tmbundle%2Fmaster%2FSyntaxes%2FR.plist&grammar_text=&code_source=from-text&code_url=&code=%23+install%0D%0Asource%28%22http%3A%2F%2Fbioconductor.org%2FbiocLite.R%22%29%0D%0AbiocLite%28%22flowCore%22%29%0D%0A%0D%0A%23+convert%0D%0Alibrary%28flowCore%29%0D%0Ain.fname+%3C-+%27flow123.LMD%27%0D%0Afolder+%3C-+%27C%3A%5Cusers%5Cuser%5Cflow%5C%27%0D%0Ax+%3C-+read.FCS%28paste0%28folder%2C+in.fname%29%29%0D%0Asummary%28Xx%29%0D%0Aout.fname+%3C-+paste0%28file_path_sans_ext%28in.fname%29%2C+%27.fcs%27%29%0D%0Awrite.FCS%28x%2C+paste0%28folder%2C+out.fname%29%29%0D%0A%0D%0A), I had to reinsert some backslashes that Lightshow swallowed up:

```
folder <- 'C:\users\user\flow\'
```

The trailing `\'` is obviously supposed to be `\\'`, and you can imagine how that's gonna affect highlighting.

**Comment by larsbrinkhoff** [comment]
@Alhadis Right!  Sorry, no work for you then.

**Comment by Alhadis** [comment]
\> no work for you
\> is unemployed

Oooh, ouch.
<img src="http://cdn.bleacherreport.net/images_root/slides/photos/002/199/454/lebron-sad-face-thumb-500xauto-94_display_image.jpg?1336163150" />
