### ISSUE TITLE
bad regex for const

### ISSUE THREAD

**Issue by bucaran** [github/linguist#2544]
```js
const index = 0
const offset = 0
```

**Comment by pchaigno** [comment]
@bucaran Linguist only selects the appropriate grammar for highlighting. You should open an issue on the grammar repository. See [`grammars.yml`](https://github.com/github/linguist/tree/master/grammars.yml) and [`vendor/grammars`](https://github.com/github/linguist/tree/master/vendor/grammars) to know which grammar GitHub uses here.

**Comment by arfon** [comment]
:+1: yes please report the issue on the grammar repository and we'll pick up the changes here automatically.

**Comment by bucaran** [comment]
@pchaigno Thanks, no ill intention, I always forget where I should post this.

**Comment by pchaigno** [comment]
@bucaran No problem ;)
