### ISSUE TITLE
Linguist labels c headers with keyword private as c++

### ISSUE THREAD

**Issue by 2trill2spill** [github/linguist#2553]
The c headers in my project https://github.com/Secure-Labs/nextgen with the compiler attribute `private` are being mislabeled as c++. Here is how I am defining `private`.

`#define private __attribute__((visibility("hidden")))`

The headers without `private` are being correctly labeled as c headers.

**Comment by arfon** [comment]
Hi @2trill2spill. You might like to take a look at the Linguist Overrides to fix this: https://github.com/github/linguist#overrides

Getting 100% accuracy for C/C++ files is nigh on impossible.
