### ISSUE TITLE
Add support for Nunjucks?

### ISSUE THREAD

**Issue by slavafomin** [github/linguist#2558]
Hello!

Could you please add support for [Nunjucks](https://mozilla.github.io/nunjucks/) by Mozilla?

It's a templating language like Django Templates, Jinja2/Twig.

**Comment by arfon** [comment]
Hi @slavafomin - please take a look out [contributing guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) for adding a new language. If Nunjucks is sufficiently popular we should be able to add it.

**Comment by SimenB** [comment]
#3341
