### ISSUE TITLE
Primarily C++ project misidentified as LLVM

### ISSUE THREAD

**Issue by neilsteiner** [github/linguist#2562]
My https://github.com/torc-isi/torc project consists primarily of C++ code, plus a bunch of custom .db files.

For some unknown reason, linguist classifies the project as LLVM.  I checked lib/linguist/languages.yml, and I see that .ll extensions are recognized as LLVM.  However I have only 7 .ll files in the project, and nearly 2,000 other files, as you can see from https://github.com/torc-isi/torc/search?l=llvm.

I noticed your https://github.com/github/linguist#overrides section, but that seems relevant to cases where a file is misclassified.  This instead seems to be an accounting error.  Any suggestions would be much appreciated.

**Comment by pchaigno** [comment]
The statistics do not depend on the number of files but on their total size. These `.ll` files are really big and seem to be generated files so you probably want to ignore them using Linguist overrides ;)

**Comment by arfon** [comment]
> These `.ll` files are really big and seem to be generated files so you probably want to ignore them using Linguist overrides ;)

:+1: - yep, I think this is your best fix here.

**Comment by neilsteiner** [comment]
Thanks for the response.  But how do I tell linguist to completely ignore certain files?  https://github.com/github/linguist#overrides tells me how to override a file type based on its extension, but what do I put in .gitattributes to tell linguist to ignore a file completely?

**Comment by neilsteiner** [comment]
I added a .gitattributes to the top of my repository with the following contents:
`src/torc/bitstream/assembler/libraries/memory/*.ll linguist-vendored`
That solved my problem.  Thank you.  I didn't realize that "linguist-vendored" was equivalent to saying "ignore this pattern."

**Comment by arfon** [comment]
Glad you got this sorted @neilsteiner!
