### ISSUE TITLE
Incorrectly indented lines on Safari

### ISSUE THREAD

**Issue by leo** [github/linguist#2564]
It seems like the indention in GitHub's file view doesn't work that great on Safari (I'm on 9.0, but I think it also doesn't work in 8.0). Just open [this][1] link in Safari.

Noticed that all closing brackets on sub-roles are indented the wrong way? Take line 11, 34, 67 or 71 as an example — they're not on the same line:

![screen](https://cloud.githubusercontent.com/assets/6170607/9330811/e07ecd68-45bb-11e5-8a05-baadd2c7e5ea.png)

The funny thing is that if you click on the beginning of those lines, the indention suddenly gets corrected. What the hell? :smile:

And that's not only with SCSS code, it's the exact same thing with every other language. But on Chrome everything works fine.

I always thought that this is a problem that was caused by myself and I therefore tried deleting and re-adding the indentation in my files, but that didn't solve the problem. Now I now that it's not my fault, but a simple bug in the syntax highlighter.

[1]: https://github.com/leo/leo.github.io/blob/master/_sass/_main.scss

**Comment by pchaigno** [comment]
I'm afraid there's nothing that can be done in Linguist to fix this. You should report it to support@github.com.

**Comment by leo** [comment]
:heavy_check_mark:
