### ISSUE TITLE
[Typescript] - Syntax highlighting is outdated

### ISSUE THREAD

**Issue by bluong** [github/linguist#2569]
Specifically, the `let`, `const`, and probably the new Typescript keywords are not being highlighted.  I have looked at #2221 but it seems that https://github.com/lavrton/sublime-better-typescript has been deprecated.

**Comment by pchaigno** [comment]
@bluong Looks like [this is the new package](https://github.com/Microsoft/TypeScript-Sublime-Plugin). Do you have an example of file incorrectly highlighted? We could test this grammar and replace the old one in Linguist if it works better.

**Comment by bluong** [comment]
Yup, here's a link to a file in a pull request, and note that all of the `let` usage is not highlighted

https://github.com/palantir/plottable/pull/2620/files#diff-de6d2d24d77b0ff5a88bf14334277007R235

**Comment by bluong** [comment]
Here's a picture for a quick visual

![screen shot 2015-08-19 at 11 36 42 am](https://cloud.githubusercontent.com/assets/1448299/9365499/bfd46400-4666-11e5-9a08-5d46ad5432f0.png)

**Comment by pchaigno** [comment]
It looks better with the new package: [Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2FMicrosoft%2FTypeScript-Sublime-Plugin%2Fmaster%2FTypeScript.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fpalantir%2Fplottable%2FaxisAnnotations%2Fsrc%2Faxes%2Faxis.ts&code=), right?
I'll open a pull request to change the grammar.

**Comment by bluong** [comment]
This looks a lot better at first glance.  It even highlights newly made variables!  How long do you expect this to take to merge in?

**Comment by pchaigno** [comment]
It will probably be in the next release, so in a couple weeks ;)

**Comment by arfon** [comment]
\

**Comment by bluong** [comment]
Thanks a ton for the quick response!
