### ISSUE TITLE
Mozilla Public License recognized as GPL

### ISSUE THREAD

**Issue by pchaigno** [github/linguist#2575]
Mozilla Public Licenses are currently recognized as GPL because it is mentioned in the [official text](https://www.mozilla.org/MPL/2.0/).
I'm opening this issue to remember to fix this if we don't go ahead with #2568 (using Licensee).

A fix could be to move [this section of code](https://github.com/github/linguist/blob/b3b75e5ef836f3ae442597c0ac52ee3e90aad548/test/test_grammars.rb#L135-L140) before the section for GPL.

**Comment by arfon** [comment]
Is this fixed now @pchaigno?

**Comment by pchaigno** [comment]
Not entirely. Since we're still using your custom script for licenses in READMEs, MPL licenses in READMEs will be recognized as GPL licenses.
I'll open a pull request to fix this.

**Comment by pchaigno** [comment]
I added code in #2557 to recognize the MPL license but it isn't in master and I can't find when it was removed in the [history](https://github.com/github/linguist/commits/master/test/test_grammars.rb). @arfon Am I missing something here?

**Comment by arfon** [comment]
Weird. I don't see these lines of code being removed either. @benbalter was the last people to touch these files - Ben do you have any ideas?

**Comment by benbalter** [comment]
Do you have an example of a repo/project that it's miscategorizing?
