### ISSUE TITLE
Unrecognised R language in Gists

### ISSUE THREAD

**Issue by klmr** [github/linguist#2576]
Syntax highlighting for gists — which is inferred from the file itself and can no longer be explicitly specified — seems to no longer recognise some R files (the type is incorrectly inferred as Rebol):

:link: https://gist.github.com/klmr/faf1b150d6b7f8c7b0f8

As long as the file type could be explicitly specified, inferring a wrong language wasn’t that bad. But now it’s bothersome.

The only heuristic disambiguation rule at the moment [seems to be](https://github.com/github/linguist/blob/b3b75e5ef836f3ae442597c0ac52ee3e90aad548/lib/linguist/heuristics.rb#L354-L360): “if the code includes `<-`, it’s R”. However, this insufficient since many people do not use `<-` in their code at all.

As far as I can see, *every* Rebol file needs to start with (or at the very least contain) the string “`Rebol`” so this appears to be a far more consistent heuristic. Apparently this rule was (in my case) overridden by the ML classifiers, which shouldn’t have happened.

**Comment by pchaigno** [comment]
See #2533 for more background on this issue.

Is there any other keyword/construct we could use for R (in addition to `->`)?

**Comment by arfon** [comment]
Thanks for reporting this. 

> As long as the file type could be explicitly specified, inferring a wrong language wasn’t that bad. But now it’s bothersome.

We removed the dropdown because even though you were specifying the language this preference was never stored so we still resorted to using the Linguist classifier :-\

> As far as I can see, every Rebol file needs to start with (or at the very least contain) the string `Rebol` so this appears to be a far more consistent heuristic. 

Could you link to any docs that state this? If this is the case then we could consider changing [this line](https://github.com/github/linguist/blob/b3b75e5ef836f3ae442597c0ac52ee3e90aad548/lib/linguist/heuristics.rb#L357) to just be an `else`: i.e.:

```ruby
disambiguate ".r" do |data|
  if /\bRebol\b/i.match(data)
    Language["Rebol"]
  else
    Language["R"]
  end
end
```

although to be honest we try to avoid writing heuristics that way. The other options are: 

1. To expand the current `R` heuristic beyond the existing check
2. To improve the samples that the classifier trains on for both languages

**Comment by arfon** [comment]
Also, note that you can 'fix' this in the short term by including Vim or Emacs overrides in your files: https://github.com/github/linguist#using-emacs-or-vim-modelines

**Comment by klmr** [comment]
The modeline support is great.

Here’s the relevant Rebol doc: [5.2: Scripts/Headers](http://www.rebol.com/docs/core23/rebolcore-5.html#section-2):

> Directly preceding the script body, every script must have a header that identifies its purpose and other script attributes. […] The general form of a script header is:
>
> ```rebol
> REBOL [block]
> ```
>
> For the interpreter to recognize the header, the block must immediately follow the word `REBOL`. Only white space (spaces, tabs, and lines) is permitted between the word `REBOL` and the block 

But note also:

> Script text does not need to begin with a header. Scripts can begin with any text …

@pchaigno Unfortunately R has few keywords or other recurring language features that set it apart syntactically. However, another distinguishing feature is comments:

* R comment lines start with `#`
* REBOL comment lines start with `;`.

So here’s another potential heuristic (although the second test is strictly redundant since all full REBOL scripts will already succeed the first test — only script fragments might fail it):

```ruby
disambiguate ".r" do |data|
  if /\bRebol\s*\[\b/i.match(data) || /\s*;/.match(data)
    Language["Rebol"]
  else
    Language["R"]
  end
end
```

**Comment by arfon** [comment]
Thanks for this additional context @klmr. If you have the bandwidth, we'd welcome a Pull Request with an improved heuristic.
