### ISSUE TITLE
Python docstrings not ended

### ISSUE THREAD

**Issue by flying-sheep** [github/linguist#2577]
[this line](https://github.com/biopython/biopython/blob/2d2488c3a5184d220df268e7e804e31d6f41abfe/Bio/SeqIO/QualityIO.py#L1188) demonstrates that the end of the the docstring started [here](https://github.com/biopython/biopython/blob/2d2488c3a5184d220df268e7e804e31d6f41abfe/Bio/SeqIO/QualityIO.py#L1056) is not detected.

as result, the rest of the file is highlighted as docstring…

**Comment by pchaigno** [comment]
@flying-sheep Linguist only selects the appropriate grammar for highlighting. In the case of Python, it uses [this Atom bundle]https://github.com/atom/language-python). You should open an issue there ;)

**Comment by arfon** [comment]
> You should open an issue there ;)

Yep, please report this issue upstream. We will automatically pick up the fix when it's made.

**Comment by flying-sheep** [comment]
will do, thanks, and sorry for raising it here :relaxed:
