### ISSUE TITLE
Many repos in our organisation ar identified as Javascript despite being Groovy projects

### ISSUE THREAD

**Issue by aruizca** [github/linguist#2579]
Organisation url: https://github.com/AtlasOfLivingAustralia

Most of our projects are Grails projects using the Groovy language, but they are identified as Jacascript projects due to the amount of third party web static libraries that we use as dependencies and that, for now, we have to check in with our source code.

Cheers,
Angel.

**Comment by pchaigno** [comment]
[Here are the details of which files participate to the statistics count](https://gist.github.com/pchaigno/7804f67d397011638a44) for 4 of your (detected-as-)JavaScript repositories.

I found a few directories we could ignore (ie. add to [`vendor.yml`](https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml)). For instance, `leaflet-plugins`, `bootstrap-datepicker`, `fancybox`, `fileupload`, etc. I'll open a pull request for those.
To ignore the other libraries you can use [Linguist overrides](https://github.com/github/linguist#overrides).
