### ISSUE TITLE
F# bad highlighting

### ISSUE THREAD

**Issue by dezelin** [github/linguist#2581]
This file is not highlighted properly:

https://github.com/dezelin/BitcoinZ/blob/feature_tracker/Bitcoin/TestMessageSerialization.fs

**Comment by pchaigno** [comment]
@dezelin Linguist only selects the appropriate grammar for highlighting. In the case of F#, it uses [this Atom bundle](https://github.com/fsprojects/atom-fsharp). You should open an issue there ;)

**Comment by arfon** [comment]
> You should open an issue there ;)

:+1:
