### ISSUE TITLE
Sublime Project and Workspace shouldn't be counted as JavaScript

### ISSUE THREAD

**Issue by porglezomp** [github/linguist#2587]
For an example see https://github.com/porglezomp/LD33, when I had the workspace included it though that I had ~50% JavaScript, which was slightly annoying.

It would probably work fine to just exclude `.sublime-project` and `.sublime-workspace`.

**Comment by arfon** [comment]
I would use the Linguist overrides to fix this. Specifically, you need to mark these files as `linguist-vendored`: https://github.com/github/linguist#using-gitattributes
