### ISSUE TITLE
Language bar doesn't match search results

### ISSUE THREAD

**Issue by larsbrinkhoff** [github/linguist#2588]
The language breakdown presented in the language bar sometimes does not match search results.

E.g. the language bar for https://github.com/jjmaldonis/md currently says "Forth 99.9% Other 0.1%".  But clicking "Forth" goes to https://github.com/jjmaldonis/md/search?l=forth which doesn't have any results for Forth files.

As far as I can see, there are no language overrides here.

**Comment by larsbrinkhoff** [comment]
Indeed, [the file classified as Forth](https://github.com/jjmaldonis/md/blob/master/potentials/Al90Sm10_MendelevM_2014.eam.fs) doesn't seem to appear in any search results at all:
https://github.com/jjmaldonis/md/search?q=unpublished

Might this be because the file is considered too large to be indexed?

**Comment by arfon** [comment]
> Might this be because the file is considered too large to be indexed?

Yeah, at > 2Mb I think it might be too big :-(

**Comment by larsbrinkhoff** [comment]
Ok.  I see these mismatches from time to time, but then I understand this particular issue.
