### ISSUE TITLE
Improve recognition of embedded SQL in python files?

### ISSUE THREAD

**Issue by foresmac** [github/linguist#2595]
Noticed that the syntax highlighting will correctly highlight SQL inside a `cursor.execute()` call, but only if it's a single line. Would it be possible to improve this buy checking for multi-line SQL, perhaps wrapped in triple quotes?

Only certain lines recognized here:
<img width="518" alt="screen shot 2015-08-26 at 2 41 59 pm" src="https://cloud.githubusercontent.com/assets/3628189/9504222/02004cf0-4c01-11e5-9d2d-df82931fb85c.png">

None recognized here (in a comment marked as `python`):
<img width="462" alt="screen shot 2015-08-26 at 2 42 28 pm" src="https://cloud.githubusercontent.com/assets/3628189/9504241/1c0d267c-4c01-11e5-83da-15a01fbe7f1a.png">

**Comment by auscompgeek** [comment]
Firstly, you should file an issue on the project for the *Python grammar*, not here.

Secondly, it works fine? :stuck_out_tongue_winking_eye:

```python
'''SELECT *
FROM users
WHERE 1 = 1 AND 1 <> 2
'''
```

**Comment by pchaigno** [comment]
@foresmac - @auscompgeek is right, Linguist only selects the grammars to use. For Python, GitHub uses [atom/language-python](https://github.com/atom/language-python). You should open an issue there.

Also, it looks like it works if the SQL immediately follows the triple quotes. You might want to point that out in your issue ;)
```python
example1 = '''
SELECT *
FROM users
WHERE 1 = 1 AND 1 <> 2
'''

example2 = '''SELECT *
FROM users
WHERE 1 = 1 AND 1 <> 2
'''
```

**Comment by bkeepers** [comment]
@foresmac thanks for reporting the issue. I opened an issue on https://github.com/atom/language-python/issues/102.

**Comment by foresmac** [comment]
Just a test:
``` python
def some_func(count):
    cursor.execute('''
        WITH users_with_occurances AS (
        SELECT      users_user.id
                    COUNT(users_user.id) AS occurances
        FROM        users_user
        INNER JOIN  photo_photo
        ON          users_user.id = photos_photo.owner_id
        GROUP BY    users_user.id
        )

        SELECT      COUNT(*)
        FROM        users_with_occurances
        WHERE       occurances >= %s
    ''', [count])
```
