### ISSUE TITLE
Add support for C strftime and strptime format specifiers.

### ISSUE THREAD

**Issue by serge-v** [github/linguist#2596]
C language strftime format specifiers are not highlighting properly.
Example: https://github.com/serge-v/ctests/blob/master/weather/parse-dwml.c#L464

**Comment by pchaigno** [comment]
@serge-v Linguist only selects the appropriate grammar for highlighting. In the case of C, it uses [this TextMate bundle](https://github.com/textmate/c.tmbundle). You should open an issue there ;)

**Comment by arfon** [comment]
> You should open an issue there ;)

:+1:
