### ISSUE TITLE
This repo is mainly PHP and no java

### ISSUE THREAD

**Issue by geshan** [github/linguist#2609]
https://github.com/NRGI/resourcecontracts.org

**Comment by larsbrinkhoff** [comment]
It's classified as JavaScript because there are 1951 Kbytes of `.js` files.  Two are classified as Java, because they contain `-*- Mode: Java`, and those are 1473 Kbytes.

The PHP files total 635 Kbytes.

See https://github.com/github/linguist/blob/master/README.md#overrides.
