### ISSUE TITLE
Colors for languages.

### ISSUE THREAD

**Issue by ghost** [github/linguist#2611]
I researched the contributing guidelines, issues and PRs but couldn't find anything about that. What is the guidelines to assign a color to a language? Why do not some languages have colors? Is it possible to be changed a color value of a language afterwards?

I think it would be better to have some guidelines for color assignment to languages in the contributing guidelines. I want to add it but I couldn't realize what it should be.

**Comment by jonas-l** [comment]
You don't have to specify a color (see [Ant Build System definition][ant-definition]). In that case it will be grey. However, I don't know whether it is allowed to change it afterwords.

[ant-definition]: https://github.com/github/linguist/blob/074f17ed98a73b424f4b98c67a4a1517b6d9e8e2/lib/linguist/languages.yml#L150

**Comment by pchaigno** [comment]
[This comment](https://github.com/github/linguist/pull/2298#issuecomment-90150424) explains how the colors were first selected. We could probably add an entry in `CONTRIBUTING.md` based on that.
