### ISSUE TITLE
Deep Learning approach to Automatic Source Code Classification

### ISSUE THREAD

**Issue by nemesiscodex** [github/linguist#2618]
#### Hello there!

I am investigating about a single deep learning approach for this problem, like the **LSTM-RNN**, instead of **Naive Bayes** or **SVM**. 

I am planning to make an implementation and make comparations to other approaches.

It is worth doing? Any advice would be appreciated!

My starting points:

- [What's the Code? Automatic Classification of Source Code Archives](https://clgiles.ist.psu.edu/papers/KDD-2002-whatsthecode.pdf)
- [Jürgen Schmidhuber's page on Recurrent Neural Networks](http://people.idsia.ch/~juergen/rnn.html)
- [University of Oxford: Deep Learning Lectures  by Nando de Freitas](https://www.youtube.com/watch?v=PlhFWT7vAEw)

**Comment by larsbrinkhoff** [comment]
Sounds interesting!

**Comment by pchaigno** [comment]
You should probably discuss that with @lazywei. He was working on Linguist's classifier during his Google Summer of Code. See also #2505.

**Comment by lazywei** [comment]
Thanks @pchaigno for mentioning.

Here are some of my points:
- As mentioned, I'm working on re-write the classifier part in the project [mockingbird](https://github.com/lazywei/mockingbird). So if you do want to implement deep learning related algorithm, it would be more than welcome you make it to mockingbird as well.
- RNN indeed has its superiority in "text processing". Yet, we will then encounter the problem of
  - lack of enough training data for supporting the high learning complexity introduced by RNN (which might lead to overfitting)
  - the computational cost of training will be higher (comparing NNets to linear methods)
  - predicting stage and model saving will be complicated (we will need to go through the whole nets each time we want to make a prediction, which means we need to save the whole weights of the neural nets)

Just my 2 cents. How do you think?

**Comment by nemesiscodex** [comment]
> As mentioned, I'm working on re-write the classifier part in the project mockingbird. So if you do want to implement deep learning related algorithm, it would be more than welcome you make it to mockingbird as well.

I will, actually mockingbird will be perfect for comparing, thanks for your hard work! :+1: 

> lack of enough training data for supporting the high learning complexity introduced by RNN (which might lead to overfitting)

I think LSTM will get the most of the available training data, otherwise we can always get more in this case

> the computational cost of training will be higher (comparing NNets to linear methods)

The phrase "Pay once, play forever" comes to my mind :sweat_smile: 

> predicting stage and model saving will be complicated (we will need to go through the whole nets each time we want to make a prediction, which means we need to save the whole weights of the neural nets)

It may not be that big, I'm not sure yet, I will have to try

**Comment by lazywei** [comment]
By mentioning mockingbird, I was in fact hoping you could implement the RNN or other deep learning strategies in mockingbird, instead of comparing to mockingbird. :wink: (maybe you can open an PR/issue regarding this feature in [mockingbird](https://github.com/lazywei/mockingbird)?)

Ya, I agree with you that LSTM can somehow solve the problem of training data size.

Anyway, I think it is worth a try, and I think it is generally good for us to exploring more diversity. We can always adjust our algorithm/storage method/caching etc. after first implementation.

Thanks :+1:

**Comment by nemesiscodex** [comment]
> By mentioning mockingbird, I was in fact hoping you could implement the RNN or other deep learning strategies in mockingbird, instead of comparing to mockingbird

By comparing I just meant to compare strategies, and I like that mockingbird is written in go, that's convenient. And yes I will make that PR, but I think it will take me a few months to get that done

**Comment by lazywei** [comment]
Please keep me informed with your progress and please let me know if I can help with your implementation - I know the theory of RNN but I haven't implemented it yet by myself.
Thanks.

**Comment by nemesiscodex** [comment]
Sure, what I am doing now, is getting familiar with lua and [torch](http://torch.ch/), so I can make a quick implementation of the model, before I go (bad joke).

**Comment by nemesiscodex** [comment]
**Status update:** After some time inactive due to a big [incident in my university](http://www.argentinaindependent.com/currentaffairs/newsfromlatinamerica/paraguay-students-take-over-university-during-protest/) and more than a month full of protests, classes are going back to normal. And **this project is continuing.**

The topics I am researching right now are related to the feature representation (Word Vectors), LSTM variations, and how to achieve classification. I am feeling more confident as I go and I hope it is worth it

**Comment by nemesiscodex** [comment]
**Status update:** 
1. There is a new boom in machine learning [TensorFlow](http://tensorflow.org/) and I am considering to replace torch with it, to speed things up
2. I am reading a lot of papers, news, and blogs on the subject (lstm, rnn in general). I will make my bibliography available as soon as I have a little time. In the mean time feel free to email me and I will share what I have.

**Comment by arfon** [comment]
Closing as stale.
