### ISSUE TITLE
Language bar shows 99.5% C++ on C# project

### ISSUE THREAD

**Issue by mattolenik** [github/linguist#2626]
If you take a look at the language bar on [this project](https://github.com/mattolenik/winston) you see it shows 99.5% C++. But if you use the language search feature, you only see [8 for C++](https://github.com/mattolenik/winston/search?l=cpp) and [45 for C#](https://github.com/mattolenik/winston/search?l=csharp). This doesn't seem to add up either for number of files or SLOC.

**Comment by pchaigno** [comment]
This is happening because of [this file](https://github.com/mattolenik/winston/blob/master/winston_install/winston_tar.cpp) ;)

**Comment by mattolenik** [comment]
Ahah, that would indeed be it! That is not supposed to be checked in, my mistake. Thanks!
