### ISSUE TITLE
Wrong repository language 

### ISSUE THREAD

**Issue by xLs51** [github/linguist#2635]
Hi,
My repository (https://github.com/xLs51/Twemoji-Picker) is supposed to be tagged as JavaScript but it looks like my js/ folder is ignored.
Thanks.

**Comment by pchaigno** [comment]
Your JavaScript file is detected as generated, probably because of the very long lines.
It's probably better though, since it looks more like a data file ;)

**Comment by xLs51** [comment]
As a jQuery plugin it's a bit weird to get tagged as CSS but yeah I should've put the data in a separated file.
Thanks :)
