### ISSUE TITLE
Add GraphQL syntax highlighting to GFM code fences

### ISSUE THREAD

**Issue by steveluscher** [github/linguist#2637]
Opening this issue to track the addition of GraphQL syntax highlighting to GFM.

    ```graphql
    query FooQuery {
      field(call:$value) @directive(awesome:true, number:42, strings:"yes") {
        subfield as alias
      }
    }
    ```

Use the syntax highlighter from https://github.com/rmosolgo/language-graphql

Click here for an [example of highlighted source](http://graphql-swapi.parseapp.com/graphiql/?query=%23%20Copyright%20(c)%202015%2C%20Facebook%2C%20Inc.%0A%23%20All%20rights%20reserved.%0A%23%0A%23%20This%20source%20code%20is%20licensed%20under%20the%20BSD-style%20license%20found%20in%20the%0A%23%20LICENSE%20file%20in%20the%20root%20directory%20of%20this%20source%20tree.%20An%20additional%20grant%0A%23%20of%20patent%20rights%20can%20be%20found%20in%20the%20PATENTS%20file%20in%20the%20same%20directory.%0A%0Aquery%20queryName(%24foo%3A%20ComplexType%2C%20%24site%3A%20Site%20%3D%20MOBILE)%20%7B%0A%20%20whoever123is%3A%20node(id%3A%20%5B123%2C%20456%5D)%20%7B%0A%20%20%20%20id%20%2C%0A%20%20%20%20...%20on%20User%20%40defer%20%7B%0A%20%20%20%20%20%20field2%20%7B%0A%20%20%20%20%20%20%20%20id%20%2C%0A%20%20%20%20%20%20%20%20alias%3A%20field1(first%3A10%2C%20after%3A%24foo%2C)%20%40include(if%3A%20%24foo)%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%2C%0A%20%20%20%20%20%20%20%20%20%20...frag%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0Amutation%20likeStory%20%7B%0A%20%20like(story%3A%20123)%20%40defer%20%7B%0A%20%20%20%20story%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0Afragment%20frag%20on%20Friend%20%7B%0A%20%20foo(size%3A%20%24size%2C%20bar%3A%20%24b%2C%20obj%3A%20%7Bkey%3A%20%22value%22%7D)%0A%7D%0A%0A%7B%0A%20%20unnamed(truthy%3A%20true%2C%20falsey%3A%20false)%2C%0A%20%20query%0A%7D).

**Comment by steveluscher** [comment]
cc @leebyron @dschafer @schrockn

**Comment by pchaigno** [comment]
Is the file extension for GraphQL `.js`? Is there a way to differentiate GraphQL files from JavaScript files?

**Comment by leebyron** [comment]
File extension is recommended to be `.graphql`

**Comment by pchaigno** [comment]
> File extension is recommended to be `.graphql` - `.js` should never be treated as GraphQL.

Oh, great! (I had this impression because [facebook/graphql](https://github.com/facebook/graphql#type-system) is using `.js` for its [example files](https://github.com/graphql/graphql-js/tree/master/src/__tests__)).

I can open a pull request to add detection for GraphQL. Do you have a sample file I could use though?

**Comment by leebyron** [comment]
https://github.com/graphql/graphql-js/blob/master/src/language/__tests__/kitchen-sink.graphql and https://github.com/graphql/graphql-js/blob/master/src/language/__tests__/schema-kitchen-sink.graphql are pretty good places to start! :)

**Comment by pchaigno** [comment]
Is there a color from an official logo I could use for the language bar?

**Comment by leebyron** [comment]
#E535AB

**Comment by pchaigno** [comment]
Hum, I'm getting ahead of myself. I don't think there are enough [`.graphql` files on GitHub](https://github.com/search?utf8=%E2%9C%93&q=extension%3Agraphql+NOT+djfhdjfnf&type=Code&ref=searchresults) to add support for it in Linguist (see the [guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language)).

@arfon Could we only add support for GraphQL without a file extension (only for code snippets as it was the original request)?

**Comment by steveluscher** [comment]
I'm most concerned at this point with syntax highlighting than I am with showing the percentage of `.graphql` files in any given repo.

We have many examples in the Relay universe that could benefit from this treatment.

See “Proposed API” of this issue: https://github.com/facebook/relay/issues/114

Another issue altogether is how to syntax highlight fragments of GraphQL found inside JS `Relay.QL` templates. See “getFatQuery()” here: https://github.com/facebook/relay/issues/126#issuecomment-133107693

**Comment by leebyron** [comment]
Even with wide proliferation of GraphQL the use of .graphql files will probably not be all that common. However GraphQL code blocks in markdown files will be.

**Comment by pchaigno** [comment]
> Could we only add support for GraphQL without a file extension (only for code snippets as it was the original request)?

@arfon @bkeepers :point_up:

**Comment by arfon** [comment]
> Could we only add support for GraphQL without a file extension (only for code snippets as it was the original request)?

I've just closed a pull request [asking for the same thing](https://github.com/github/linguist/pull/2590#issuecomment-148076094) so I really don't want to make an exception here unless we can demonstrate more wide-scale usage of the syntax. 

@leebyron/@pchaigno  - do you have any suggestions for finding more files that might contain `GraphQL` snippets?

**Comment by steveluscher** [comment]
<3
