### ISSUE TITLE
Add Support for PL/SQL

### ISSUE THREAD

**Issue by jaredpetersen** [github/linguist#2645]
It would be nice if PL/SQL was supported, though I'm not sure if it is used enough to warrant it. Thoughts?

**Comment by arfon** [comment]
Pretty sure we already do: https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L2452-L2463

**Comment by jaredpetersen** [comment]
Huh, interesting. I've always save my PL/SQL code as a .pck, which is a valid file extension, but it's not listed there.

**Comment by arfon** [comment]
Looks like there are a [fair few of these](https://github.com/search?l=&q=create+extension%3Apck&ref=advsearch&type=Code&utf8=%E2%9C%93) files on GitHub. Feel free to open a new Pull Request adding this extension (take a look at our [contributing guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language) together with a sample or I'll likely get to this in the coming weeks.

**Comment by jaredpetersen** [comment]
Okay, that sounds good! I'll try to look into that further tonight. Thanks for your help!

**Comment by jaredpetersen** [comment]
@arfon Would you mind taking a look at my pull request? :grinning:

**Comment by arfon** [comment]
> @arfon Would you mind taking a look at my pull request?

:+1:  Done
