### ISSUE TITLE
Repo marked as wrong language

### ISSUE THREAD

**Issue by BerkeleyTrue** [github/linguist#2646]
Our repo github.com/freecodecamp/freecodecamp is marked as HTML (should be JavaScript) and has not updated since we removed most of the vendor HTML that was causing this issue.

We also have `.gitattributes` file that is not being honored by linguist.

**Comment by pchaigno** [comment]
See the full list of files contributing to the language statistics here: https://gist.github.com/pchaigno/2347e3e6f3a0b6420fc3 (HTML at the end).

A few things worth noting:
- Most CodeMirror files are [already considered as vendored](https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml#L156) by Linguist.
- [Jade is in the HTML group](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L1589) which means that all `.jade` files count as HTML in the statistics.

**Comment by BerkeleyTrue** [comment]
OIC. A former Ruby dev and I tried to run Linguist locally against the project to verify and failed miserably. Maybe there is a quick tutorial out there for non Ruby devs?

Thanks for you help.

**Comment by pchaigno** [comment]
> A former Ruby dev and I tried to run Linguist locally against the project to verify and failed miserably. Maybe there is a quick tutorial out there for non Ruby devs?

Nop, not yet. I'm working on making this project more approachable to new contributors.
In the meantime, if you still want to figure out what went wrong, you can take a look at [this Dockerfile](https://github.com/pchaigno/linguist/blob/dockerfile/Dockerfile) for detailed installation steps.
If you don't need a development environment, you can just use `gem install github-linguist` (you'll need [RVM](https://rvm.io/rvm/install)).
