### ISSUE TITLE
Add information about file extension order to the contribution guidelines

### ISSUE THREAD

**Issue by jaredpetersen** [github/linguist#2649]
I was trying to add a new file extension to an existing language and ran into an issue where the TravisCI build failed because the file extensions in [languages.yaml](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml) file need to be alphabetically sorted ([see build logs](https://travis-ci.org/github/linguist/jobs/81897206)). However, this is not mentioned in the contributing guidelines.

This information should be included in the contributing guidelines.

**Comment by pchaigno** [comment]
@arfon Is this requirement still needed? (now that Gist interface has changed)
