### ISSUE TITLE
SCSS, SASS, LESS, Stylus, etc. = CSS?

### ISSUE THREAD

**Issue by jamen** [github/linguist#2650]
When doing searches on projects or viewing what the project contains, it's misleading.

Say for instance you only want to find SCSS projects.  When doing a search that can be hard to perform since all CSS, SASS, LESS, Stylus, etc. are all categorized as "CSS" along with the SCSS project you're trying to find.

We should separate them out into separate languages.

**Comment by auscompgeek** [comment]
What's wrong with searching for `extension:scss` or similar? IMO, this is a feature, not a bug.

**Comment by davidzchen** [comment]
IMO it would be better to separate these into separate languages if they meet the requirements.

SASS, LESS, Stylus, etc. _are_ different languages and code cannot be freely shared between them interchangeably.

**Comment by jamen** [comment]
I figured out that GitHub does separate them in searches, however it just doesn't distinguish them in the repository "language bar". 

This is kinda pointless, I was only really concerned about searches.  I don't think the language bar matters too much, but it would be nice if it were distinguishable on the repo's page.

**Comment by julmot** [comment]
:+1:
