### ISSUE TITLE
[Feature Request] Differentiate between JS and node.js

### ISSUE THREAD

**Issue by gappleto97** [github/linguist#2652]
This would be a useful thing to do, even if only by flagging manually in the .gitattributes file.

**Comment by pchaigno** [comment]
Do you want this to use different syntax highlighting grammars or just for the statistics?
Is there an easy way to differentiate a JS file from a Node.js one?

**Comment by gappleto97** [comment]
I only particularly care about the statistics. I don't think there's any major differentiation between normal javascript and node.js scripts.
