### ISSUE TITLE
Please update standard-ml.tmbundle

### ISSUE THREAD

**Issue by commonlisp** [github/linguist#2658]
Please update the vendored standard-ml.tmbundle from the github repo.

**Comment by pchaigno** [comment]
This will be done automatically with the next release (see the [contribution guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#fixing-syntax-highlighting)).

**Comment by arfon** [comment]
:+1: this happened in the [last release](https://github.com/github/linguist/compare/v4.6.3...d06860df37a9528c531c146c684419fa30a6d078#diff-29afa9023872fac5aa6ba571d59f1199R1)
