### ISSUE TITLE
Demo projects in my repo are no longer counted in language statistics

### ISSUE THREAD

**Issue by armadsen** [github/linguist#2659]
The code in the demo projects in [my repo](https://www.github.com/armadsen/ORSSerialPort/) are no longer included in the language statistics for the repo. Near as I can tell, that's because of the change in commit fd570d906 . Is there any way to override this (short of renaming the folder so it's not 'Examples')? Some of the examples are in a different language (Swift) than the library itself, and I'd prefer that the Swift get included in the statistics, if possible.

**Comment by pchaigno** [comment]
> Is there any way to override this (short of renaming the folder so it's not 'Examples')?

Yes, using [Linguist overrides](https://github.com/github/linguist#using-gitattributes). In a `.gitattributes` file:
```
Examples/* linguist-documentation=false
```

**Comment by armadsen** [comment]
Perfect, thanks!
