### ISSUE TITLE
Python 3 Annotations break highlighting

### ISSUE THREAD

**Issue by pradyunsg** [github/linguist#2660]
Currently, if the Python code contains function-annotations (new in Python 3), the highlighting goes hay-wire (as can be seen [here](https://github.com/JukkaL/mypy/blob/f4be501a2183a009496532f3557a56ad06beb64f/mypy/parse.py#L70)).

Please fix. (← there's definitely a better way to say this, but I'm sleepy :| )

**Comment by berdario** [comment]
Yeah, github is pretty nasty in this respect

I was affected by the same issue recently

linguist uses this stuff for syntax highlight:
https://github.com/github/linguist/tree/master/vendor/grammars

So this needs to be reported as a bug to `language-python`, which [has already been done](https://github.com/atom/language-python/issues/68)

I also [tried to fix it with a PR](https://github.com/atom/language-python/pull/95), but the test that I added is not working... 

The original author of language-python is  @kevinsawicki  but I'm afraid that nowadays it's not actively maintained anymore

**Comment by pchaigno** [comment]
Thanks @berdario for your answer!

To add on this, there is a fix on the way at atom/language-python#88. I just need to find the time to finish it :/
<br>

> The original author was @kevinsawicki but I'm afraid that language-python nowadays is not actively maintained anymore

It can take some time but the grammar is still maintained. Look at the merged/closed PRs ;)

**Comment by berdario** [comment]
You're right... today I was a bit pessimistic upon seeing that the last merged PR is from 1 month ago.

**Comment by pchaigno** [comment]
September is a busy month :smile:

**Comment by bkeepers** [comment]
Closing this since it's being tracked in https://github.com/atom/language-python/issues/68
