### ISSUE TITLE
C# thinks most of my file is a string literal

### ISSUE THREAD

**Issue by Tanjoodo** [github/linguist#2661]
I don't know how that happens or why but here is the file in question https://github.com/Tanjoodo/autoproxy/blob/master/AutoProxy/Poller.cs

**Comment by pchaigno** [comment]
Linguist only selects the grammar to use for highlighting. In the case of C#, GitHub uses [atom/language-csharp](https://github.com/atom/language-csharp). You should open an issue there.
It would greatly help if you can join a minimum reproduction example in your issue there (it's probably due to the `@"` ;).

**Comment by Tanjoodo** [comment]
Thanks for the tip, I'll tinker around with things. 

Does the minimum reproduction example have to be valid C#? As in, does it have to compile?

**Comment by pchaigno** [comment]
> Does the minimum reproduction example have to be valid C#? As in, does it have to compile?

Nop, just has to show that the syntax highlighting breaks ;)

> Edit: The bug has already been reported there, it seems. Thanks for the help.

Oh, I though I checked. Must have missed it. Which issue do you think it corresponds to?

**Comment by Tanjoodo** [comment]
This one here. https://github.com/atom/language-csharp/issues/22

**Comment by pchaigno** [comment]
Looks like there actually are two issues here.
- Strings as arguments are not highlighted:
```cs
class Poller {
  A a = b("c");
}
```
- If a string argument contains a space, it also breaks syntax highlighting of following code lines:
```cs
class Test {
  A a = b("Path\\WithoutASpace");
  A a = b("Path\\WithA Space");
}
```

I'll open issues for these on the grammar repo.
Thanks for reporting this!

**Comment by Tanjoodo** [comment]
No problem! Thanks for being friendly and helpful :)
