### ISSUE TITLE
sublime-* files with JSON like content detected as JavaScript

### ISSUE THREAD

**Issue by aviaryan** [github/linguist#2662]
`.sublime-build` , `.sublime-completions` and `.sublime-settings` are detected as JavaScript

All of those 3 files have JSON content.

https://github.com/aviaryan/AutoHotkey/search?l=javascript

**Comment by deathbeam** [comment]
They does not have valid JSON content. In JSON you cannot use comments.

**Comment by arfon** [comment]
So we can close this now?

**Comment by aviaryan** [comment]
Never thought linguist looks beyond file extensions. If that's the case, then it's all right.

**Comment by keplersj** [comment]
JSON5 supports comments, perhaps that is a better fit for these files?

**Comment by Alhadis** [comment]
@keplersj Does Sublime permit you to run arbitrary functions in those files?

If so, it's JavaScript.

JSON5 is a different beast altogether, though... it supports a lot more than just comments (primitives, unquoted keys, etc)

**Comment by keplersj** [comment]
@Alhadis I don't think Sublime allows abstract functions in these, I believe they are just JSON files with comments.

**Comment by Alhadis** [comment]
I think it's probably safe to leave them classified as JSON. It'd surprise me if Sublime were the only program out there which permits comments in JSON data.

**Comment by keplersj** [comment]
They're currently classified as JavaScript because of these comments though

**Comment by Alhadis** [comment]
Whoops, yeah, sorry... I got them switched in my head.

I've only ever used Sublime a handful of times, so I've no idea how its config files are used. But from a cursory glance, it'd seem this issue should be revisited.

Given Sublime's mass popularity, it wouldn't strike me as unusual if the stats for JavaScript for this year's [GitHub Octoverse](http://www.i-programmer.info/news/136-open-source/10126-github-octoverse-reveals-the-state-of-open-source.html) were unfairly inflated:

<img src="http://www.i-programmer.info/images/stories/News/2016/Sept/B/octovers2.JPG" />

I think this should be reopened, honestly.

**Comment by keplersj** [comment]
I agree, it seems unfair to count these configuration files as JavaScript.

**Comment by keplersj** [comment]
SublimeText docs have more information on the files, and they are not JavaScript.

Format: JSON (with comments)
- [.sublime-build](http://docs.sublimetext.info/en/latest/reference/build_systems/basics.html#file-format-of-sublime-build-files)
- [.sublime-commands](http://docs.sublimetext.info/en/latest/reference/command_palette.html#file-format-of-sublime-commands-files)
- [.sublime-menu](http://docs.sublimetext.info/en/latest/customization/menus.html#file-format)

Format: JSON (comments not specified)
- [.sublime-completions](http://docs.sublimetext.info/en/latest/reference/completions.html#file-format)
- [.sublime-keymap](http://docs.sublimetext.info/en/latest/customization/key_bindings.html#file-format)
- [.sublime-macro](http://docs.sublimetext.info/en/latest/extensibility/macros.html#macros)
- [.sublime-project](https://www.sublimetext.com/docs/3/projects.html)
- [.sublime-workspace](https://www.sublimetext.com/docs/3/projects.html)

Seemingly No Documentation Available
- .sublime-mousemap
- .sublime-theme
- .sublime-metrics
- .sublime-session

Documentation and Examples Available but Format not Specified
- [.sublime-settings](https://www.sublimetext.com/docs/3/settings.html)

**Comment by Alhadis** [comment]
HAHA, I'm in the middle of compiling links too. I'm up to `.sublime-mousemap` and I noticed there's nothing available on them documentation-wise. But [they look to be plain JSON files too](https://github.com/search?q=extension%3A.sublime-mousemap+NOT+nothack&type=Code). Perhaps a deprecated file extension used in earlier versions? Dunno.

I'll submit a new PR to fix this. Thanks @keplersj for bringing this up. =)
