### ISSUE TITLE
Ignore a bower_components folder

### ISSUE THREAD

**Issue by tchoulihan** [github/linguist#2669]
My project language is incorrectly identified as javascript(it should be java), because I'm using a lot of bower dependencies in my project, with a ton of javascript files.

I just want linguist to ignore all the files in these folders and their subfolders

I've tried two lines in my `.gitattributes` file, all of which failed, and the false one actually inflated the number of javascript files recognized.
`src/main/resources/web/bower_components/* linguist-vendored=false `
`src/main/resources/web/bower_components/* linguist-vendored`

**Comment by pchaigno** [comment]
Is it a public repository? Could you link to it? :-)

**Comment by tchoulihan** [comment]
https://github.com/tchoulihan/torrenttunes-client

**Comment by pchaigno** [comment]
I ran Linguist against your repository: https://gist.github.com/pchaigno/7c1130a3a57ca48a2fa2.
I looks like you still have some big JavaScript files which aren't in `.gitattribute` ;)

**Comment by tchoulihan** [comment]
What should my line be to ignore this folder?
`src/main/resources/web/bower_components/`

**Comment by pchaigno** [comment]
Maybe `src/main/resources/web/js/`? Have you looked at the file I linked? It's the details of the language statistics in your repo.

**Comment by tchoulihan** [comment]
Oops thanks for linking.

What would the line be if I wanted to exclude/ignore a certain file?

**Comment by pchaigno** [comment]
The full path to the file with `linguist-vendored`.

**Comment by tchoulihan** [comment]
Okay thanks! I'll reopen this then if I have problems.
