### ISSUE TITLE
Repo detect as perl respect to js or php

### ISSUE THREAD

**Issue by Mte90** [github/linguist#2674]
I've this old repo detect that contain perl but the file extension are php or js so i don't understand the problem https://github.com/Mte90/Webary

**Comment by pchaigno** [comment]
I think you repo statistics are just not up-to-date. Here is what I get when I run the last release of Linguist against your repo:
```
$ linguist
42.76%  JavaScript
28.28%  CSS
26.64%  HTML
2.32%   PHP
```
It should update with the next push or you can contact support@github.com to ask for a manual update.

**Comment by Mte90** [comment]
confirmed with a push the repo is updated correctly
