### ISSUE TITLE
YAML repository miscategorized as PHP

### ISSUE THREAD

**Issue by davidfischer-ch** [github/linguist#2677]
Hi,

I am the owner of the project https://github.com/davidfischer-ch/ansible-roles, obviously containing many Ansible roles that are small YAML configuration files. My issue is that this project is reported as a PHP project, but in fact, YAML should be considered the main language:

     ~/github/davidfischer-ch/ansible-roles$ find . -name "*.yml" -exec cat {} \; | wc
         2442    5885   56447
     ~/github/davidfischer-ch/ansible-roles$ find . -name "*.php" -exec cat {} \; | wc
         982    4516   28750

Is it possible to give a look to my repository and understand why the ".yml" files aren't summed up as YAML in the languages breakdown? Rachel Berry (from github staff) confirmed that linguist should consider YAML as a language.

Thanks for your time.

Regards,

David

**Comment by arfon** [comment]
`YAML` is recognised by Linguist but it's also [considered data](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L3759) and so doesn't contribute to repository language statistics sorry.
