### ISSUE TITLE
Feature request: support for the Metal language

### ISSUE THREAD

**Issue by aledalgrande** [github/linguist#2679]
Hi, I noticed that in code stats or search or highlighting there is no support for Metal (Apple). Is there any hope it will be supported?

**Comment by pchaigno** [comment]
That will depend on its level of adoption on GitHub (see the requirements in [how to add a new language](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language)).
What extension are Metal files using?

**Comment by aledalgrande** [comment]
The extension is `.metal`. The language is still in its infancy, but I bet more and more people will use it, it makes GPGPU on mobile much simpler.

**Comment by pchaigno** [comment]
There are [around 1,000 Metal files on GitHub](https://github.com/search?utf8=%E2%9C%93&q=extension%3Ametal+fragment+OR+vertex&type=Code&ref=searchresults), spread across 400 users. That should be enough.

Do you have a few files from a real application (under an open source license) that could be used as samples? Also, do you know a grammar (Sublime Text package or TextMate/Atom bundle) for highlighting?
Do you want to open a pull request to add this language (I can assist if there's any issue)?

**Comment by aledalgrande** [comment]
You can see an example from a [public app I have](https://github.com/aledalgrande/warpExample/blob/master/warpExample/Warp.metal). Also, [this open source app](https://github.com/victorprad/InfiniTAM/tree/master/InfiniTAM/ITMLib/Engine/DeviceSpecific/Metal) uses it.

I do not know of any grammars for Metal, but as [it is very similar to C++](https://developer.apple.com/library/ios/documentation/Metal/Reference/MetalShadingLanguageGuide/cplusplus/cplusplus.html), I think you can use that template as a start.

Unfortunately I don't have bandwidth to make a PR, but I will try to be available if there are any issues that need clarification.

**Comment by pchaigno** [comment]
Pull request is almost ready, it's just missing a color.
Does Metal have a logo from which I could extract a color?

**Comment by aledalgrande** [comment]
Yes, the official logo is this one: http://blogs.unity3d.com/wp-content/uploads/2014/06/metal-logo.png

**Comment by aledalgrande** [comment]
I would say the dark purple is the one taken as a reference, see [the icon in the bottom left corner](https://developer.apple.com/library/watchos/documentation/DeveloperTools/Conceptual/InstrumentsUserGuide/Art/instruments_profilingtemplateselection_dialog_2x.png).

**Comment by pchaigno** [comment]
@adelcambre Pull request opened in #2686 :tada:

**Comment by aledalgrande** [comment]
Thanks Paul!

**Comment by arfon** [comment]
This will be live in the next release of Linguist.
