### ISSUE TITLE
Repository language is being misclassified

### ISSUE THREAD

**Issue by ktemo** [github/linguist#2682]
Hi, I have this new repository and is build in meteorjs (Javascript) but appears as CSS.
https://github.com/ktemo/MeteorHackathon2015

Could someone help me with this, please? Do I need to do something extra?

Regards

**Comment by arfon** [comment]
This file https://github.com/ktemo/MeteorHackathon2015/blob/master/ifeel/client/stylesheets/main.css is skewing your language statistics.

You can tell Linguist to ignore it by using the overrides: https://github.com/github/linguist#overrides
