### ISSUE TITLE
Support the Mustache language

### ISSUE THREAD

**Issue by dasilvacontin** [github/linguist#2685]
Most used extensions are `.mu` and `.mustache`, I believe. Would you accept a PR for this?

**Comment by pchaigno** [comment]
`.mustache` files are [currently recognized as HTML+Django](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L1318). Is Mustache related to Django?

**Comment by dasilvacontin** [comment]
Nope, not at all. Maybe they use it, but it's unrelated. Mustache is a template system with implementations in over 30 programming languages. I've never used it alongside Django, nor I use Django. http://mustache.github.io/

**Comment by dasilvacontin** [comment]
Handlebars is Mustache-compliant. Handlebars adds logic statements (among other sugar) to Mustache's logic-less templates.

**Comment by pchaigno** [comment]
Do you hae an example of Mustache file and is there a way to identify them (to distinguish them from Django files)?

**Comment by sonalkr132** [comment]
I think Mustache should be language of its own just like `haml`.
[Django comes with its DTL](https://docs.djangoproject.com/en/1.8/topics/templates/#s-module-django.template) and doesn't really have anything to do with Mustache.
Using `.mustache` file extension exclusively for Mustache should be enough. Here is an excerpt from [template section](https://github.com/mustache/mustache#templates) of Mustache's readme:
> By default, a view will try to find its template on disk by searching for an HTML file in the current directory that follows the classic Ruby naming convention.
`TemplatePartial => ./template_partial.mustache`

**Comment by pchaigno** [comment]
Flagging this as stale :flags:
