### ISSUE TITLE
Ruby error when running convert-grammars

### ISSUE THREAD

**Issue by edendramis** [github/linguist#2688]
Hey all, I am finishing up adding a new language and when I run this:

```
script/convert-grammars --add vendor/grammars/FreeMarker.tmbundle
```

I get this error:

```
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- plist (LoadError)
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from script/convert-grammars:6:in `<main>'
```

I'm running OS X Yosemite with ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

I've been trying to debug it lately and any help would be appreciated.

**Comment by arfon** [comment]
Do you have the `plist` gem installed? https://github.com/github/linguist/blob/master/github-linguist-grammars.gemspec#L13

**Comment by edendramis** [comment]
@arfon Thank you–that fixed it. 

As a side question for my general knowledge: Is there some kind of initialization step that Ruby uses? For example, node projects you generally run `npm install`.  I haven't contributed to any Ruby projects before and I had to install several packages manually before I could successfully run `bundle install` (I think they were pkg-config, cmake, charlock_holmes and icu4c)  Is that normal for a first time set up?

**Comment by Alhadis** [comment]
Just ran into this issue too (I'm new to both Ruby *and* adding languages to Linguist), and the dependency wasn't terribly obvious to me.

Perhaps mention the `plist
