### ISSUE TITLE
C# interpreted as Javascript

### ISSUE THREAD

**Issue by webgio** [github/linguist#269]
The repository https://github.com/webgio/Rotativa is in C# language but is interpreted as Javascript. 

I'm not sure why, I guess it's because it contains an execuable and some dll files. 

Should the vendor.yml file execlude exe and dll files?

**Comment by touhidulfahim** [comment]
Same Issue in my all repo

**Comment by lildude** [comment]
@touhidulfahim please open a new issue referencing the repo where you're seeing this. There's probably a explanation for this and it's best suited in it's own issue, rather than tacked onto the end of a closed issue that is over 5 years old.

**Comment by ronaldris21** [comment]
I'm working with Xamarin and C#, I use some Backend with MVC using .NET, but I get the JavaScript instead off C# language

**Comment by lildude** [comment]
@ronaldris21 if you're referring to your certification repo, have clicked the JavaScript word? Those all look like JavaScript to me 😉

**Comment by zdravkoggeorgiev** [comment]
I have c# .net core project with MVC backend with .csproj, .cs file, and ONE .js file. But it's still detected as JS project. link to repo:
https://github.com/zdravkoggeorgiev/roomschat

**Comment by lildude** [comment]
@zdravkoggeorgiev that's because the total number of bytes of Javascript far outweighs all the other languages combined:

JavaScript 7.97 KB
CSS 3.36 KB
C# 2.26 KB
HTML 814 Bytes

**Comment by dush-a** [comment]
Even if you are using a C# web project, you might have references to JavaScript files such as jQuery. This can be fixed by adding a `.gitattributes` file to the root of the project and adding the following line at the end of the file.

`*.js linguist-detectable=false`
