### ISSUE TITLE
Support for multi-line statements

### ISSUE THREAD

**Issue by elifoster** [github/linguist#2692]
I have only noticed this with Ruby, because that's really the only language that I've taken the care to actually follow a set style, but when a statement, particularly method definition, takes up more than one line, styling does not appear as it should. I'm probably really bad at explaining this, so [here's an example.](https://github.com/elifoster/weatheruby/blob/master/lib/weatheruby.rb#L17)

**Comment by pchaigno** [comment]
Each language has its own grammar for syntax highlighting. In general, a bug in the highlighting of one language shouldn't have consequences for other languages.
Also, Linguist only selects the correct grammar. For Ruby, GitHub uses [textmate/ruby.tmbundle](https://github.com/textmate/ruby.tmbundle). You should open an issue there. 

I can't see how it's broken though. The equal sign and true keyword appear to be highlighted correctly on the second line. Is there something else that should be highlighted?

**Comment by elifoster** [comment]
Sorry, should have been a tiny bit more specific, and checked without GitHub Dark installed. You can see the difference if you install a Stylish theme, like GitHub Dark, or inspect the blob-code element of that line.

"verbose_errors" is not the span class "pl-smi", though it should be. This is only noticeable when using a stylish theme or something similar, because the default GitHub css shows pl-smi as the same color as default text.

**Comment by pchaigno** [comment]
The CSS classes are generated based on the output of the language grammar. So, even if the TextMate bundle didn't generate the `pl-smi` classes itself, I still think it's the source of the bug.

I don't have TextMate but, if you report the issue at [textmate/ruby.tmbundle](https://github.com/textmate/ruby.tmbundle), someone might be able to check that it can be reproduced with the actual editor ;)

**Comment by arfon** [comment]
Closing as this isn't a Linguist issue :-)
