### ISSUE TITLE
Can linguist be used with redcarpet?

### ISSUE THREAD

**Issue by dchambers** [github/linguist#2704]
Sorry for potentially asking a dumb question, but is linguist designed to be used with redcarpet?

My understanding was that Github use redcarpet as their markdown processor, but that they've switched from pygments to linguist for syntax highlighting, but I'm unable to find any guidance on how to confgure redcarpet to use linuguist. Any help clearing this up would be much appreciated.

**Comment by sonalkr132** [comment]
Redcarpet is Markdown to (X)HTML parser and linguist is used to find language related statistic of a repository.
Github didn't switch from pygments for linguist, both of the libraries serve completely different purpose. If you want to perform syntax highlighting, may be you will find this railscast useful [#272 Markdown with Redcarpet](http://railscasts.com/episodes/272-markdown-with-redcarpet?view=asciicast)
HTH

**Comment by dchambers** [comment]
Thanks so much for providing clarification on this point.

**Comment by bkeepers** [comment]
@dchambers let us know if you need any further clarification or help.
