### ISSUE TITLE
Vendored files are hidden on diff but still count to max diff.

### ISSUE THREAD

**Issue by santagada** [github/linguist#2705]
The Readme for linguist states that: "Vendored files are also hidden by default in diffs on github.com." 
They are hidden but the diffs are counted so you end up with "Sorry, we could not display the entire diff because it was too big.". I really think it shouldn't count those lines if it is not showing them anyway.

**Comment by arfon** [comment]
That's a fair point. Would you mind emailing support@github.com about this as it's a GitHub (and not Linguist) issue.
