### ISSUE TITLE
Makefile syntax highlighting bug

### ISSUE THREAD

**Issue by philtay** [github/linguist#2710]
Have a look at this gist:

https://gist.github.com/philtay/5a647f5a573d1052e7f7

Repro:

```Makefile
define foobar
$(and $(filter-out undefined,$(origin 1)),$(1))
endef

define test
command
endef
```

**Comment by pchaigno** [comment]
Linguist only selects the grammar to use for highlighting. In the case of Makefile, GitHub uses [textmate/make.tmbundle](https://github.com/textmate/make.tmbundle). You should open an issue there.

**Comment by kepler0** [comment]
@philtay You may also try filing an issue on the [Atom version](https://github.com/atom/language-make), the tmbundle Linguist is using seems a little abandoned.

I just checked and this issue still exists with the Atom version: [Lightroom sample](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fatom%2Flanguage-make%2Fmaster%2Fgrammars%2Fmakefile.cson&grammar_text=&code_source=from-text&code_url=&code=define+foobar%0D%0A%24%28and+%24%28filter-out+undefined%2C%24%28origin+1%29%29%2C%24%281%29%29%0D%0Aendef%0D%0A%0D%0Adefine+test%0D%0Acommand%0D%0Aendef)

**Comment by arfon** [comment]
As this looks to now be fixed in the upstream grammar this will be fixed in the next release of Linguist.
