### ISSUE TITLE
Linguist thinks that this is 46.6% Java

### ISSUE THREAD

**Issue by wil93** [github/linguist#2711]
This repository: https://github.com/veluca93/oii-web is seen as being mostly written in Java:

    Java 46.6%	 Python 34.7%	 JavaScript 7.5%	 HTML 5.9%	 CSS 2.6%	 C++ 2.4%	 Other 0.3%

However, it's clearly a Python project, and if you click on Java you can see that it's used very little (just a few snippets to do unit testing): https://github.com/veluca93/oii-web/search?l=java this page says that HTML, JS, C, and even INI are more used than Java.

EDIT: oh, now I get it, this huge third-party file has "Mode: Java" at the beginning: https://github.com/veluca93/oii-web/blob/c7864993080c575826e3b1ca233dcb06ad7edae4/cms/web/assets/pdfjs/build/pdf.js however it's clearly a Javascript file, not Java.

**Comment by arfon** [comment]
> Mode: Java

I'm afraid the only way to fix this is to remove the offending line in the file. Alternatively you can tell Linguist to [ignore](https://github.com/github/linguist#overrides) that file.
