### ISSUE TITLE
Colorize fish-shell files with a shebang

### ISSUE THREAD

**Issue by bucaran** [github/linguist#2713]
I would like to finish what I started [here](https://github.com/github/linguist/pull/1785) (SWVII pun intended).

GitHub correctly colorizes `myfile.fish`, but fails for files without an extension using a shellbang `#!/usr/bin/env fish`.

This is probably similar to what's happening [here](https://github.com/atom/language-shellscript/blob/master/grammars/shell-unix-bash.cson#L23), but I am not sure. Perhaps @50Wliu can help out?

**Comment by 50Wliu** [comment]
Unfortunately I don't know enough about how Linguist detects grammars to help out that much, but it seems like it only detects Vim/Emacs modelines currently: https://github.com/github/linguist/blob/master/lib/linguist/strategy/modeline.rb

Passing the torch to @pchaigno since he probably knows more :).

**Comment by bucaran** [comment]
@50Wliu Thanks!

**Comment by pchaigno** [comment]
Shebang should also be recognized: [`shebang.rb`](https://github.com/github/linguist/blob/master/lib/linguist/shebang.rb).

@bucaran Do you have an example of file incorrectly highlighted that has a `fish` shebang?

**Comment by bucaran** [comment]
For example: https://github.com/bucaran/flipper/blob/master/flipper

**Comment by pchaigno** [comment]
The shebang detection strategy is only run on executable files. This file isn't detected as `fish` because it's not executable.

**Comment by bucaran** [comment]
Oh, in that case this problem is solved :smile: 

Thanks @pchaigno .

**Comment by onodera-punpun** [comment]
Reopening this issue, the vast majority if scripts in this repo are fish scripts, however it only shows "shell" in the bar: https://github.com/onodera-punpun/bin

All of them are executable
