### ISSUE TITLE
Can we somehow help other peoples repositories detect the language correctly?

### ISSUE THREAD

**Issue by logicmoo** [github/linguist#2721]
I see we can do something when our repositories are marked incorrectly by Linguist.  But what about other peoples repositories ?

Here are at least 40 incorrect search results:

https://github.com/search?l=perl6&p=4&q=put_attr&type=Code&utf8=%E2%9C%93

Here are at least 150 incorrect search results:

at https://github.com/search?l=openedge-abl&q=put_attr&type=Code&utf8=%E2%9C%93

**Comment by logicmoo** [comment]
Both those queries detect 90%+ of what should be Prolog

**Comment by arfon** [comment]
Opening an issue here is a good start :smile: (I think you're already doing the right thing here)

**Comment by arfon** [comment]
@logicmoo - is this the same issue? https://github.com/github/linguist/issues/435#issuecomment-155205823

**Comment by arfon** [comment]
Closing as stale.
