### ISSUE TITLE
Detect generated files of any language

### ISSUE THREAD

**Issue by cespare** [github/linguist#2724]
Hi,

I propose to add a new generated file check by extending the [generated go check](https://github.com/github/linguist/blob/master/lib/linguist/generated.rb#L238-L243) to apply to all languages. (This check looks for the text `"Code generated by"` in the first line of the file.)

This is useful for us because we're generating protobuf code for non-standard languages and we'd like to have diff suppression. Having the `generated_go?` check has been handy for our generated Go code and it'd be great to have this option in other languages as well.

If this sounds okay, I'll send along a PR. Thanks for your consideration!

**Comment by cespare** [comment]
Friendly ping :)

**Comment by deathbeam** [comment]
+1

**Comment by arfon** [comment]
@cespare - this sounds like a useful addition. Please feel free to open a Pull Request implementing this support and continue the discussion there :+1:

**Comment by cespare** [comment]
Thanks. Let's continue discussion over on #2734.

**Comment by cespare** [comment]
Reopening as my PR was closed, yet the problem remains.

**Comment by arfon** [comment]
Copying in my comment from #2734:

> Ultimately I believe that a solution using .gitattributes data would be a good solution here but as outlined in #1792 and #2206 we don't get have support for reading in .gitattributes data on our application servers.

**Comment by lildude** [comment]
I think we can close this now as you can now mark files as generated in your `.gitattributes` file. Whilst a generic method would be nice, it's too error prone whilst we don't have an industry-wide, cross-language format or method of declaring a file is generated. When one appears, we can always look into it then.

Until then, `*.whatever linguist-generated` in your `.gitattributes` file is your friend.

**Comment by arfon** [comment]
🎉👏🏻

**Comment by mimoo** [comment]
is this possible to have this in any languages? I have OCaml files that start with a similar pattern (except that comments start with `(*` instead of `//`)

**Comment by lildude** [comment]
@mimoo It's certainly possible, but very likely to lead to incorrect classification if someone happens to have added a comment that matches the regex we use. As such, we implement per-language checks to reduce the chances of this. See https://github.com/github/linguist/blob/master/lib/linguist/generated.rb for all those implemented so far.
