### ISSUE TITLE
Go code being marked as groovy

### ISSUE THREAD

**Issue by thewhitetulip** [github/linguist#2726]
https://github.com/thewhitetulip/Tasks, in this repo and https://github.com/thewhitetulip/picsort both are go based webapplications which are tagged under 21% groovy which is wrong because i do not know what Groovy was until linguist marked them as groovy

**Comment by pchaigno** [comment]
This is because of [the `.gtpl` files](https://github.com/thewhitetulip/Tasks/search?l=groovy). What are they?

**Comment by thewhitetulip** [comment]
They are the template files which are used to render the html page, by the way the syntax of gtpl files is more near to perl than groovy and shouldn't .gtpl be considered as HTML since majority is in HTML format?

**Comment by pchaigno** [comment]
[`.gtpl` files are currently associated to Groovy.](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L1283)
There seems to be approximately the same number of [HTML](https://github.com/search?utf8=%E2%9C%93&q=extension%3Agtpl+html) and [Groovy](https://github.com/search?utf8=%E2%9C%93&q=extension%3Agtpl+NOT+html) `.gtpl` files. We could probably add `.gtpl` to HTML. I'll take a look into it.

**Comment by thewhitetulip** [comment]
Well you can add `.gptl` to Go templates or html whichever you think best represents them

**Comment by lildude** [comment]
If you’ve got the bandwidth, we’d happily accept a PR implementing this.

**Comment by veera83372** [comment]
Hey @lildude, 
I can take up this.

**Comment by smola** [comment]
These should probably be classified as HTML if they are HTML-like, rather than Go. Since it's just a text template language supported by a [Go library](https://golang.org/pkg/text/template/), not Go itself.

Also, keep in mind that `.gtpl` is not really a standard extension, and there's a lot of Go templates using extensions like `.tpl`, `.go.tpl`, `.go.html`, `.tgo`, `.gotpl`, etc.
