### ISSUE TITLE
Python highlighting problem

### ISSUE THREAD

**Issue by d33tah** [github/linguist#2727]
18.11.2015 12:44, James Dennes (GitHub Staff):
> Hi there,
> 
> We use open source TextMate-style language grammars for syntax highlighting, which are available here:
> 
> https://github.com/github/linguist/blob/master/grammars.yml
> 
> The fastest way to get this fixed would be to find the issue tracker for the specific grammar and open an issue or contribute a fix there.
> 
> Linguist pulls in grammar updates with each new release, which usually happens every couple of weeks. This should get fixed on GitHub.com shortly after that happens.
> 
>> Hello,
>>
>> I think that I might have found a bug in your syntax highlighting. Here it is:
>>
>> https://github.com/d33tah/pypgexplain/blob/c4693a14f7e411e8239195269474edcd0c6628dd/json_parse.py
>>
>> As you can see, the color-coding here isn't really readable - all text is marked as a string.
>>
>> Cheers,
>> d33tah

**Comment by pchaigno** [comment]
> The fastest way to get this fixed would be to find the issue tracker for the specific grammar and open an issue or contribute a fix there.

The grammar for Python is at https://github.com/atom/language-python ;)

**Comment by d33tah** [comment]
Sorry about that. Reposted it here: https://github.com/atom/language-python/issues/117

**Comment by pchaigno** [comment]
No problem. Finding the grammar GitHub uses is not very straightforward currently :/

**Comment by arfon** [comment]
Closing as this is being tracked [elsewhere](https://github.com/atom/language-python/issues/117).
