### ISSUE TITLE
Gdb command files

### ISSUE THREAD

**Issue by eush77** [github/linguist#2730]
[Gdb command files](https://sourceware.org/gdb/onlinedocs/gdb/Command-Files.html) are script files that are loaded and executed by gdb debugger either at startup (in which case they are typically named `.gdbinit`) or at runtime with `source` command (in which case I don't know of any common naming conventions).

Some of these files can be [quite huge](https://github.com/gdbinit/Gdbinit/blob/master/gdbinit).

I know lldb has also some equivalent of these.

**Comment by pchaigno** [comment]
Can you confirm that [these files](https://github.com/search?p=4&q=extension%3Agdbinit+NOT+djfhdkghfjf&type=Code&utf8=%E2%9C%93) are Gdb command files? If they are, then [it meets the requirements for adding a language](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) and you should open a pull request ;)

**Comment by larsbrinkhoff** [comment]
Yes @pchaigno, those are overwhelmingly gdb.

Also, [possibly 17000](https://github.com/search?q=extension%3Agdb+define+OR+set+OR+end+OR+thread) out of [24000](https://github.com/search?q=extension%3Agdb+NOT+slartibartfast) `.gdb` files seem to be gdb scripts.

**Comment by pchaigno** [comment]
Support for GDB was added in #3090.
