### ISSUE TITLE
Wrong syntax highlighting for bash script blocks in markdown

### ISSUE THREAD

**Issue by mindaugasrukas** [github/linguist#2743]
Word `enable` is highlighted but it shouldn't:

```bash
./some_script some-command
```
vs
```bash
./some_script enable-some-action
```

**Comment by pchaigno** [comment]
Linguist only selects the grammar to use for highlighting. In the case of Bash scripts, GitHub uses [atom/language-shellscript](https://github.com/atom/language-shellscript). You should open an issue there.

**Comment by 50Wliu** [comment]
This has already been fixed in the latest shellscript version.
