### ISSUE TITLE
Misidentification of files with .do extension

### ISSUE THREAD

**Issue by wbuchanan** [github/linguist#2747]
[This file](https://github.com/txthinking/google-hosts/blob/c9fce873b44b50e326ca2197b1c70459f4fca302/scripts/hosts.do) is causing the repository at [https://github.com/txthinking/google-hosts](https://github.com/txthinking/google-hosts) to be misclassified as Stata.  The Stata language doesn't support method/function chaining and periods are not legal characters in variable names, so it might be possible to use a regex expression for this type of case where there is code that doesn't conform to that standard:

```
r1---sn-a5m7znee.c.android.clients.google.com
```

Is the first line which would never be a valid language construct in Stata.

**Comment by arfon** [comment]
Thanks for reporting this @wbuchanan. As this seems like an edge-case I've suggested a fix in https://github.com/txthinking/google-hosts/issues/91using the Linguist overrides.

**Comment by wbuchanan** [comment]
I'm unable to view the issue you linked to.  It becomes a problematic for the trending lists since there aren't a ton of Stata users/programmers using GitHub currently.  Is it possible for user's to override all of the language defaults?  For example, https://github.com/wbuchanan/StataJSON gets tagged as a Java repository (which the majority of the code is written in Java), but the code itself is a Java plugin for the Stata language and it would probably be more useful for users searching by language if this would show up in a Stata language search vs a Java language search.
