### ISSUE TITLE
issue in Batch syntax coloring, but upstream ericzou/ebundles is unmaintained

### ISSUE THREAD

**Issue by astroxe** [github/linguist#2748]
Per blob/master/grammars.yml (line 244), source.dosbatch is associated to "vendor/grammars/ebundles/Bundles/MSDOS batch file.tmbundle", which points to:
https://github.com/ericzou/ebundles "TextMate bundles ported to e-texteditor"

However,
  - ericzou/ebundles has had no commits in the last 7 years
  - http://e-texteditor.com/ (which ericzou/ebundles mentions as homepage) currently appears to have been overtaken by someone else
  - ericzou's GitHub homepage reports no contributions later than last year's October
  - http://www.ericzou.com (which is mentioned in https://github.com/ericzou/ ) is empty and provides no contact information

Last Oct 23, I reported an issue on ericzou/ebundles, about wrong unclosed string handling (an unterminated string is rendered on github.com as if it were multi-line and including the subsequent lines, breaking the syntax coloring). In a month, this issue has not received any attention.

**Comment by arfon** [comment]
@astroxe if you're comfortable making the change then please fork the upstream repository and make the fix. We can then switch out the grammar repository for Batch to your fork.

If you decide to go this route then please be sure to provide links to Lightshow demonstrating the fix: https://github-lightshow.herokuapp.com/

**Comment by waynenilsen** [comment]
I'm not sure why this issue is closed. It seems to me that this is not resolved. There is another issue with batch files that comments do not function as they should either. I have been communicating with Jess Hosman at github support about this possibly related issue. 

```bat
@echo off
rem this text should be green
echo hello world
```
