### ISSUE TITLE
The Vim help calls it "Vim script"

### ISSUE THREAD

**Issue by igrep** [github/linguist#2752]
```vim
:help usr_41
```

says

```
			      Write a Vim script


The Vim script language is used for the startup vimrc file, syntax files, and
many other things.  This chapter explains the items that can be used in a Vim
script.  There are a lot of them, thus this is a long chapter.
```

So, "**Vim script**" seems to be the most official name of the language,
**neither VimL, Vimscript, nor VimScript**.

Then, I want you to tell your thoughts on whether to change the name displayed on the language statistics.
In addition, if change, what's best way to edit this repository?

Ref: http://stackoverflow.com/questions/4398312/vimscript-or-viml

**Comment by arfon** [comment]
Thanks for raising this issue @igrep. Unfortunately it's currently not possible to rename languages on GitHub (see my [comment](https://github.com/github/linguist/pull/1936#issuecomment-91733362) and these issues for background: https://github.com/github/linguist/issues?q=label%3A%22Language+rename%22+is%3Aclosed).

In the future we hope to be able to rename languages on GitHub but for now I'm afraid we're stuck with `VimL`

**Comment by igrep** [comment]
Oh my... :sob: Got it. :+1:
