### ISSUE TITLE
.Rmd not being recognised

### ISSUE THREAD

**Issue by kungfujam** [github/linguist#2756]
Just a quick note that files with extension .Rmd is not recognised as RMarkdown. RMarkdown is in `languages.yml`. Is this problem just because the case is incorrect? `R Studio` defaults to creating files with this extension.

**Comment by arfon** [comment]
Could you link to an example of where you're seeing an issue @kungfujam? Linguist is case-insensitive these days for extensions and so this should work. See [this gist](https://gist.github.com/arfon/9be533e90e85e3c076eb) as an example.

**Comment by kungfujam** [comment]
I've added you as a contributor to a private repo of mine exhibiting the issue. See the code folder for the files.

**Comment by arfon** [comment]
Could you please email a link to the repository? arfon@github.com

**Comment by arfon** [comment]
@kungfujam actually, forget that. I just saw the email.

The file is being parsed as Markdown but I don't think we support all of the functionality that comes with RMarkdown (see this thread for background: https://github.com/github/markup/pull/343)

Can you tell me what you're expecting to see compared with what you are seeing?

**Comment by kungfujam** [comment]
I'm expecting to see the language details bar include R Markdown.

<img width="996" alt="screen shot 2015-12-03 at 13 50 08" src="https://cloud.githubusercontent.com/assets/3524723/11562272/e69ebc50-99c4-11e5-9207-354ae3956898.png">

**Comment by arfon** [comment]
Ahh OK. This is because RMarkdown is considered [`prose`](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L2884) and so isn't included in repository language statistics. Sorry for any confusion caused by this!

**Comment by kungfujam** [comment]
No problem. Thanks for letting me know, feel free to close this. As a side, this may be slightly unfair on github statistics with regards to the popularity of `R`. All my R code is written in files like this. Code chunks in RMarkdown have a language specifier so this could be leveraged in future.

Feel free to close this issue. Thanks again.

**Comment by kungfujam** [comment]
Also, I didn't know you could link to file lines like that...cool!

**Comment by arfon** [comment]
>  All my R code is written in files like this. 

Yeah this is a good point. Unfortunately we don't have a way to account for this kind of scenario right now.

**Comment by EarlGlynn** [comment]
Why hasn't GitHub fixed this glaring problem yet?  My Rmd files are NOT "Jekyll using Docker image" or "SLSA Generic generator".  If GitHub can't guess "right", why don't you let the author decide?  Your excuses since 2015 seem weak and causes misleading information about a repository.

**Comment by lildude** [comment]
@EarlGlynn 

> If GitHub can't guess "right", why don't you let the author decide? 

🤨 [we do](https://github.com/github-linguist/linguist/blob/master/docs/overrides.md), and have done so for a very very long time.

A lot has changed in 9 years so it's possibly something easily explained. If you want specific help, please  open a [new discussion](https://github.com/github-linguist/linguist/discussions/new?category=classification) with a link to an example repo and we can take a look. You might want to also take a look at some of the [other issues](https://github.com/github-linguist/linguist/issues?q=is%3Aissue%20state%3Aclosed%20rmd) around Rmd first, specifically https://github.com/github-linguist/linguist/issues/5208

Aggressive commenting on a 9 year old issue is also uncalled for.
