### ISSUE TITLE
Interpreter is higher precedence than filename

### ISSUE THREAD

**Issue by blakeembrey** [github/linguist#2760]
I quickly looked into the code, but the interpreters is a hash map so it's not possible to fix this there. Basically, if you look at a repo like https://github.com/typings/typings/search?l=javascript you'll see a bunch of TypeScript files (notice that link is for JavaScript files). This is because of the shebang which says `node`. I imagine any other compile-to-JS which supports shebangs has the same issue.

**Comment by pchaigno** [comment]
I'm not sure I understand the issue. These files are Typescript files but they have a Node.js shebang?

**Comment by blakeembrey** [comment]
Exactly, they are TypeScript, not JavaScript files.

**Comment by pchaigno** [comment]
But, why do they have a Node.js shebang?

**Comment by blakeembrey** [comment]
Because when they are transpiled they are executed in node?

**Comment by pchaigno** [comment]
But if I try to execute a Typescript file with a Node.js shebang it will fail right? (or will it transpile it before execution?) Shouldn't the shebang be added when transpiling?

**Comment by blakeembrey** [comment]
It will fail, yes (assuming you're using type syntax from TypeScript). I don't understand how that would factor into linguist at all though? You would transpile it before you execute, yes. And it'd be possible to do that, sure, but the TypeScript compile allows shebangs so why wouldn't linguist? That's probably an issue to make to the TypeScript team, but this is already a feature (and used).

**Comment by arfon** [comment]
Thanks for reporting this @blakeembrey. Unfortunately there's no easy fix here as for the vast majority of situations using the interpreter before the filename is the more reliable thing to do.

A couple of suggested solutions: 1) If you're simply looking to change the repository statistics for your project then you might like to look at our [manual overrides](https://github.com/github/linguist#overrides) 2) `Modeline` detection has [even higher precedence](https://github.com/github/linguist/blob/master/lib/linguist/language.rb#L90-L96) and so could potentially be used to fix this too.
