### ISSUE TITLE
tsx disambiguation

### ISSUE THREAD

**Issue by mking** [github/linguist#2761]
[Here is an example](https://gist.github.com/mking/37fd47580c4ad9272baf) where a TypeScript `.tsx` file is incorrectly recognized as tiled map format.

One way to solve this is to add a disambiguation heuristic for tsx (similar to the one used for ts).

```
    disambiguate ".tsx" do |data|
      if data.include?("<tile")
        Language["XML"]
      else
        Language["TypeScript"]
      end
    end
```

What do you think?

**Comment by pchaigno** [comment]
The heuristic for `.ts` files is a particular case because `.ts` XML files must always contain a `TS` tag.
That does not seem to always be the case for `.tsx` files. As such, I'm not sure there are enough mis-classifications of `.tsx` files to justify a new heuristic...

If you think this is a recurrent classification mistake, we could evaluate the number of files incorrectly classified for a sample?
Otherwise, you can use [Linguist overrides](https://github.com/github/linguist#overrides) to fix this issue on a per repository basis.

**Comment by mking** [comment]
Ah ok. So, I did some additional research into the `.tsx` XML format and into the number of misclassified files:

* Every `.tsx` file [has an outer `<tileset>` element](http://doc.mapeditor.org/reference/tmx-map-format). So I think if we use `<tileset ` we will catch every valid `.tsx` XML file and will only mistakenly classify React files if they have a `<tileset>` element. This should be rare since the React convention for non-builtin elements is to start with an uppercase letter.
* GitHub search brings up [322 misclassified .tsx TypeScript files](https://github.com/search?utf8=%E2%9C%93&q=React+language%3AXML+extension%3Atsx+&type=Code&ref=searchresults). (Every tsx file will have an `import React` at the top.)
* In total, I see [1893 tsx TypeScript files](https://github.com/search?utf8=%E2%9C%93&q=React+language%3ATypeScript+extension%3Atsx+&type=Code&ref=searchresults), so it seems like the number of misclassified files is not insignificant.

**Comment by arfon** [comment]
Thanks for documenting this @mking. We'd welcome a Pull Request implementing this heuristic. Alternatively the Linguist overrides (https://github.com/github/linguist#overrides) are probably the best solution for now.

**Comment by dsifford** [comment]
@arfon I've tried now using every glob combination I can think of to get `.tsx` to register as TypeScript, but it simply will not.

Am I missing something? https://github.com/dsifford/academic-bloggers-toolkit/blob/master/.gitattributes

**Comment by arfon** [comment]
@dsifford - can you tell me what you're *not* seeing? These are the language stats I see for your repository:

<img width="1002" alt="screen shot 2016-05-30 at 6 57 15 pm" src="https://cloud.githubusercontent.com/assets/4483/15660349/5ada798c-2698-11e6-8f38-795a4dd10471.png">

**Comment by dsifford** [comment]
@arfon Sorry, perhaps I had the wrong idea on how deeply linguist goes in github..

My concern was with this:

![image](https://cloud.githubusercontent.com/assets/5240018/15660978/38620b36-26b1-11e6-828f-77f545b4aec3.png)

Specifically, the `.tsx` files all are seemingly registered as XML files.

**Comment by arfon** [comment]
> @arfon I've tried now using every glob combination I can think of to get .tsx to register as TypeScript in .gitattributes, but it simply will not.

I'm afraid `.gitattributes` data only overrides the repository classification. They're currently not supported by the search infrastructure or the syntax-highlighting of files sorry.

**Comment by dsifford** [comment]
Ah, understood. No problem at all. Thanks for the clarification 👍
