### ISSUE TITLE
Python file with specific name not syntax highlighting

### ISSUE THREAD

**Issue by lathrop-navisite** [github/linguist#2764]
We have a file that is not receiving diff syntax highlighting in a pull request. 
This is a new file and the file's path is:
staticdhcpd/unit_tests/staticDHCPd/extensions/official/test_httpdb.py
(It's under a private repo)

It seems that any changes to the files name (a few tried are test_httpdb2.py, test_httpd.py, httpdb_test.py) make it get syntax highlighting on the diff. 
Syntax highlighting is correctly applied when just viewing the file (not as a diff).

Any ideas?

**Comment by pchaigno** [comment]
Any chance you could reproduce the bug on a public repository? I don't see any obvious reason why it wouldn't be highlighted so it's going to be difficult to debug if we can't reproduce :/

**Comment by arfon** [comment]
Closing as stale.
