### ISSUE TITLE
Colorize .travis.yml using sh/bash syntax highlighting

### ISSUE THREAD

**Issue by nicolas-grekas** [github/linguist#2767]
even if this is yml, highlighting this file as `sh` could be much more useful don't you think?

**Comment by nchammas** [comment]
Could you elaborate why you think that? If YAML files get dedicated syntax highlighting, I don't see why we should do anything else.

Peeking into the Travis config values to highlight them as shell commands does not seem practical without introducing Travis-specific logic to Linguist. I would wager that that is out of scope for the project.

**Comment by nicolas-grekas** [comment]
I noticed that when changing the highligh mode of my IDE from yaml to sh for the .travis.yml file, it's always way more helpful, that's why I made this proposal. I just wanted to share it in case you like it. Feel free to close of course.

**Comment by nchammas** [comment]
I'm just a regular user like you. :) I totally see your point, and perhaps a project maintainer will agree with you.

**Comment by arfon** [comment]
Given these are YAML files I'd rather keep the current behaviour. Thanks for the suggestion though :smile:
