### ISSUE TITLE
Add public API for single files

### ISSUE THREAD

**Issue by thedrow** [github/linguist#2769]
It be useful to be able to identify the language of single files instead of whole repositories.
Is there a public API to do that or do we need to add one?

**Comment by thedrow** [comment]
It seems like there is. See https://github.com/github/linguist/blob/master/bin/linguist#L40
Should we document that in the README file?

**Comment by arfon** [comment]
@thedrow - I would argue that's already documented in the binary here: https://github.com/github/linguist/blob/master/bin/linguist#L3-L4

If you don't think this is clear enough, feel free to suggest some modifications to the usage section of the README: https://github.com/github/linguist#usage
