### ISSUE TITLE
Reports C header as C++

### ISSUE THREAD

**Issue by Enerccio** [github/linguist#2770]
https://github.com/Enerccio/kclib

Reports headers as C++ instead of C (especially if there is #ifdef __cplusplus ).

**Comment by arfon** [comment]
Hi @Enerccio. Please take a look at our [overrides](https://github.com/github/linguist#overrides) to fix this in the short term. In the longer-term please take a look at this thread and see if there are any modifications you'd suggest for the current heuristics: https://github.com/github/linguist/issues/1626
