### ISSUE TITLE
Auto-detecting XML files based on the header

### ISSUE THREAD

**Issue by jamesqo** [github/linguist#2780]
There are just way too many XML files out there. Instead of the 50+ file extensions we have registered in [languages.yml](https://raw.githubusercontent.com/github/linguist/master/lib/linguist/languages.yml), why not just recognize it if the top of the file starts with `<?xml version="1.0" encoding="UTF-8"?>` and isn't one of the other known extensions? Similar with what we do for the shebang in Bash/Perl.

**Comment by pchaigno** [comment]
There are [approximately 150 millions XML files](https://github.com/search?p=1&q=xml+version&ref=searchresults&type=Code&utf8=%E2%9C%93) on GitHub. 
@arfon Do you think it is worth adding a new strategy for these files?

**Comment by pchaigno** [comment]
Revisiting this. @brandonblack @Alhadis @larsbrinkhoff What do you think?

**Comment by Alhadis** [comment]
Makes perfect sense to me. I'm even surprised this hasn't already been done.

**Comment by brandonblack** [comment]
👍 I'd be in favor of this approach as well.
