### ISSUE TITLE
JavaScript language dialect: OJ

### ISSUE THREAD

**Issue by IngwiePhoenix** [github/linguist#2785]
I'd like to suggest adding recognition for [OJ](https://github.com/musictheory/oj).

What is the best way to get this in, so that OJ sources can be reported on Github?

**Comment by pchaigno** [comment]
The [contribution guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) describe how to add a new language to Linguist.

That said, a minimum popularity on GitHub is required; hundreds of repositories using it are usually expected. I count only [4 repositories](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aoj+NOT+fdfkndkfd) so far. I think you'll have to wait for a higher adoption on GitHub ;)
