### ISSUE TITLE
.strings files are listed as binary files

### ISSUE THREAD

**Issue by nicatronTg** [github/linguist#2787]
I don't really have syntax, but these files are recognized in diffs as binary files, rather than text files:

https://github.com/overtake/telegram/blob/master/TGShare/en.lproj/Localizable.strings
https://github.com/overtake/telegram/blob/master/TelegramTest/en.lproj/localizations.strings

Example diff: https://github.com/overtake/telegram/pull/211/files

**Comment by pchaigno** [comment]
I can't seem to reproduce the issue locally with Linguist. Are you sure it's because of the `.strings` file extension?

**Comment by pchaigno** [comment]
Flagging as stale :flags:
