### ISSUE TITLE
vim modeline regex too restrictive.

### ISSUE THREAD

**Issue by kentfredric** [github/linguist#2789]
The current `vim` modeline regex only captures a narrow subset of legal modeline syntax.
```ruby
 VimModeline = /vim:\s*set.*\s(?:ft|filetype)=(\w+)\s?.*:/i
```
### 1: It requires the "set" token, while vim itself does not.

```text
vim: syntax=perl
vim: set syntax=perl:
```

These are both legal, and equivalent.

> There are two forms of modelines.  The first form:
>	[text]{white}{vi:|vim:|ex:}[white]{options}
...
> The second form (this is compatible with some versions of Vi):
>	[text]{white}{vi:|vim:|Vim:|ex:}[white]se[t] {options}:[text]

Its also worth pointing out the first of these forms does not require the trailing colon either, which your regex currently requires.

### 2: It anchors only on the `ft` and `filetype` settings, which IME are less common than the `syntax` setting. 

And there are copious examples of people using both of these features on github, eg:

```
# vim: syntax=Ruby
```

https://github.com/search?l=ruby&q=vim%3A+syntax%3D&ref=searchresults&type=Code&utf8=%E2%9C%93

**Comment by arfon** [comment]
Thanks for reporting this @kentfredric. We'd welcome a Pull Request to support the expanded syntax you've outlined here :smile:

**Comment by chrisarcand** [comment]
@arfon @kentfredric #2812 supports this nicely.
