### ISSUE TITLE
Unicode (UTF-8) CPP files are detected as binaries in pull reqest diff view

### ISSUE THREAD

**Issue by vputsenko** [github/linguist#2790]
Our project contains UTF-16 cpp files (because of unicode literals inside). Github shows them as binary. I tried to convert them to UTF-8 and committing changes, but existing pull request still shows them as binary. I also tried to set diif attribute for *.cpp files - didn't help. I though that github caches some data during pull request creation, So i just tried to use "compare" buttin to compare my branch with dev to check the issue separatelly - no results, files were still displayed as binary... Is this your old issue with handling of unicode files or after converting to UTF-8 it had to work and my issue relates to some diff results caching?  

BTW, when i set "*cpp diff" attribute GitHub desktop Win client (3.0.11.0) crashes when i click i the UTF-8 file to view the diff.

**Comment by vputsenko** [comment]
I checked my UTF-8 files, they don't have 0x00 byte anywhere in the body

**Comment by pchaigno** [comment]
Do you have an example of file detected as binary?

**Comment by vputsenko** [comment]
[test_generic_flow.zip](https://github.com/github/linguist/files/85622/test_generic_flow.zip)

Sure, i attached zipped cpp file. it is UTF-8 encoded.

**Comment by pchaigno** [comment]
Linguist does not seem to be the culprit here:
```
linguist test_generic_flow.cpp 
test_generic_flow.cpp: 1775 lines (1452 sloc)
  type:      Text
  mime type: text/plain
  language:  C++
```
(This would mention `binary` if Linguist detected it as binary.)

You will probably have to report it to contact@github.com. Do you have a link to the pull request diff view?

**Comment by pchaigno** [comment]
Flagging as stale :flags:
