### ISSUE TITLE
Switch to MagicPython?

### ISSUE THREAD

**Issue by kirbyfan64** [github/linguist#2791]
`language-python` is really out-of-date and breaks when given function annotations. For instance, see [this file](https://github.com/JukkaL/mypy/blob/master/mypy/build.py), where HUGE swaths of code are completely black.

[MagicPython](https://github.com/MagicStack/MagicPython) is MUCH more up-to-date; it supports much more than `language-python`. Would it be possible to switch to MagicPython? It'll make Python code on GitHub look a LOT better!

**Comment by pchaigno** [comment]
This appears to be a duplicate of #2703 ;)

**Comment by kirbyfan64** [comment]
Sorry about that!
