### ISSUE TITLE
Broken python syntax highlighting

### ISSUE THREAD

**Issue by foxx** [github/linguist#2793]
As you can see here, the syntax highlighting is broken (shows everything as a comment block).
https://github.com/bottlepy/bottle-sqlite/blob/master/bottle_sqlite.py

**Comment by pchaigno** [comment]
Linguist only selects the grammar to use for highlighting. For Python, GitHub uses [atom/language-python](https://github.com/atom/language-python). You should open an issue there if there isn't already one ;)

**Comment by arfon** [comment]
Closing as this is being tracked upstream
