### ISSUE TITLE
In CSS files, HTML element names are not highlighted consistently.

### ISSUE THREAD

**Issue by carlsmith** [github/linguist#2795]
If you look at [this file][1], you'll see that `body`, `section` and `span` are highlighted green, but `main` is highlighted black.

[1]: https://github.com/carlsmith/quran/blob/master/html/style.css

**Comment by pchaigno** [comment]
Linguist only selects the grammar to use for highlighting. For CSS, GitHub uses [textmate/css.tmbundle](https://github.com/textmate/css.tmbundle). You should open an issue there if there isn't already one ;)

**Comment by carlsmith** [comment]
Ah. Noted. Cheers.

**Comment by arfon** [comment]
Closing as this is an upstream issue.
