### ISSUE TITLE
GitHub gist renders comment in YAML at start of GFM document as headings in overview

### ISSUE THREAD

**Issue by en90** [github/linguist#2799]
I created a gist containing multiple files, the first of which is a GitHub Flavored Markdown document which begins with YAML Metadata in the manner described at https://github.com/blog/1647-viewing-yaml-metadata-in-your-documents.

Inside of said YAML Metadata block, I have a YAML comment. In the view of the gist itself, this is handled correctly, as shown below -- the comment is not shown in the rendered document.

![gist_gfm_yaml_correct](https://cloud.githubusercontent.com/assets/385688/12145993/9cc418e0-b491-11e5-8883-3a84583dab66.png)

However, when I go to my gist overview, the comments are incorrectly rendered as document headings as shown in below.

![gist_gfm_yaml_bad](https://cloud.githubusercontent.com/assets/385688/12146058/f7560962-b491-11e5-94dc-52de4c90670f.png)

URL of gist: https://gist.github.com/en90/3cae5db566f643437fa2

URL of my gist overview: https://gist.github.com/en90

I am using Firefox 42.0 on armv7l Ubuntu 14.04.3 LTS.

I hope github/linguist is the correct place to report this issue.

**Comment by en90** [comment]
Hello, it's been almost a month and I haven't heard anything back on this. Ping.

**Comment by arfon** [comment]
Hi @en90 - sorry I missed this earlier. This isn't the correct place to report this - please email support@github.com with this bug report.
