### ISSUE TITLE
guideline for adding new languages is sub-optimum

### ISSUE THREAD

**Issue by c-lipka** [github/linguist#2802]
The guideline for adding new languages should mention what pieces of software `script/convert-grammars` requires, and possibly also how to get them. Most notably, the message reported if a particular required ruby gem (such as `plist`) is missing is only remotely helpful for users who are unfamiliar with ruby, let alone ruby gems. Also the script surprised me with an unexpected complaint about some ominous missing or unaccessible file "npm", and I first had to figure out that I'd need to install the nodejs package for that one.

At the very least, the guideline should somehow hint at the fact that this is not a classic shell script relying on standard Unix tools, but a ruby script relying on standard web development tools.

Also, I suspect trying to get the script to run on a Windows machine might be a tad troublesome. Git tools for Windows typically do come with a Unix shell environment, but usually not with ruby or the like installed. Even the GitHub Desktop for Windows doesn't ship with ruby.

**Comment by arfon** [comment]
Thanks for the feedback @c-lipka. We'd welcome any suggested improvements in the form of a pull request :smile:
