### ISSUE TITLE
--breakdown does not respect vim modelines

### ISSUE THREAD

**Issue by chrisarcand** [github/linguist#2810]
I've discovered that if you add a vim modeline in a file the `--breakdown` option does not respect it and mark it as the language you set. The language is correctly reported as the one you set if you give it the file directly (`linguist <file>` vs `linguist --breakdown`)

**Edit:** Actually, upon further review I noticed that `Rugged::Repository` is used in the breakdown option. This means that you have to have whatever file you're looking at checked in to Git before it displays properly in the breakdown. I think it's rather confusing because you could fall into a case where it's reported differently as above; perhaps git can be leveraged for the filename option as well? (use the committed version for consistency)

**Comment by pchaigno** [comment]
Is this still an issue? We now use `Rugged::Repository` for both `linguist <file>` and `linguist --breakdown`.

**Comment by chrisarcand** [comment]
@pchaigno Yes I believe this issue has been resolved now! Thanks for following up.
