### ISSUE TITLE
haml - support more colors when highlighting

### ISSUE THREAD

**Issue by onebree** [github/linguist#2814]
There are issues when rendering multi-line comments with `-#` and Ruby string interpolation. But in Vim, none of these issues appear. I don't know if this is because Vim uses a different highlighting template (which is probably does). But either way, I think more colors (not necessarily the same as my theme) will help.

I have no issue writing in HAML in Vim with [railscast theme][1].

![screenshot from 2016-01-19 08-23-27](https://cloud.githubusercontent.com/assets/9038433/12419755/0dacbf8c-be86-11e5-9115-717cebf474ca.png)

However, the highlighting provided by linguist is not nearly as expressive. (See [screenshot][2] if this issue has been closed.)

```haml
-#
  multi-line comment
  must be indented further than: -#

= bootstrap_form_for @address, as: :address, url: url do |f|
  %h2 General Information
  .panel.panel-default
    .panel-body
       %ul
         %li= "Company name: #{f.object.company.name}"
         %li= "Address type: #{f.object.type}"

  %h2 Address Details
  .panel.panel-default
    .panel-body
      .row
        .col-xs-12
          = f.text_field :address1
          = f.text_field :address2
      .row
        .col-xs-5
          = f.text_field :city
        .col-xs-4
          = f.collection_select :state_id, State.all.to_a, :id, :name
        .col-xs-3
          = f.text_field :zip

  .text-center= f.submit 'Submit', class: 'btn btn-success'
```

[1]: http://www.vim.org/scripts/script.php?script_id=2175
[2]: https://cloud.githubusercontent.com/assets/9038433/12419794/3a5521be-be86-11e5-9cbb-801edda830d1.png

**Comment by pchaigno** [comment]
Linguist only selects the grammar to use for highlighting. For Haml, GitHub uses [textmate/ruby-haml.tmbundle](https://github.com/textmate/ruby-haml.tmbundle). You should open an issue there if there isn't already one ;)

**Comment by onebree** [comment]
@pchaigno thank you! I read that linguist is what Github uses for all syntax highlighting in its site. Thank you for pointing me to the right direction!
