### ISSUE TITLE
Add support for CLI (Command-line interface)

### ISSUE THREAD

**Issue by bpierre** [github/linguist#2815]
It would be nice to have a CLI “language”, to increase the quality of instructions in README files.

On [GitHub documentation pages](https://help.github.com/articles/generating-ssh-keys/#step-1-check-for-ssh-keys), the classic prompt character, `$`, is displayed but not selectable. I think this character is useful to indicate to the users that it is a command to type.

On GitHub README files, there is no possibility to make this character non selectable, and users have to take care of not pasting it in the terminal.

I am not sure it is possible with the current system. Could we make these characters non selectable?

The language would also provide useful coloration.

<img width=554 height=91 src=https://cloud.githubusercontent.com/assets/36158/12446798/1988af1c-bf64-11e5-95ef-56595c9e0e5f.png>

Selected:

<img width=554 height=91 src=https://cloud.githubusercontent.com/assets/36158/12446797/197246b4-bf64-11e5-93cf-c0b77fac70fd.png>

**Comment by bpierre** [comment]
There is already a `shell-session` variant in the `shellscript` grammar, extracting the prompt, the separator and the command: https://github.com/atom/language-shellscript/blob/master/grammars/shell-session.cson

**Comment by arfon** [comment]
Thanks for the suggestion @bpierre. We'd welcome a pull request implementing this change.

**Comment by pchaigno** [comment]
@arfon - @bpierre Wants to make the prompt and the separator non selectable. I'm not sure that's something that can be implemented in Linguist, is it? Maybe [github/markup](https://github.com/github/markup) would be a better place for this...?

**Comment by arfon** [comment]
> Wants to make the prompt and the separator non selectable.

Oops, my bad. Yes, I think this would probably be a [github/markup](https://github.com/github/markup) feature.
