### ISSUE TITLE
C code marked as PHP

### ISSUE THREAD

**Issue by fntlnz** [github/linguist#2817]
In the nodejs/node repository there's an autogenerated C header which name ends in `*.inc` and so doesn't follow the naming convention of C header files and is erroneously marked as PHP file.

In the `languages.yml` the files with `*.inc` extension are marked as PHP files. IMO `*.inc` files are just `*.inc` files and should not belong to PHP. 

https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L2520

You can verify that here:
https://github.com/nodejs/node/search?l=php

The file in question is:
https://github.com/nodejs/node/blob/6fff47ffacfe663efeb0d31ebd700a65bf5521ba/src/CNNICHashWhitelist.inc

**Comment by pchaigno** [comment]
You can fix this locally by using [Linguist overrides](https://github.com/github/linguist#overrides) ;)
