### ISSUE TITLE
Prolog misidentified as Perl6

### ISSUE THREAD

**Issue by triska** [github/linguist#2819]
Please see the repository:

https://github.com/triska/simsttab

It is currently misidentified as `Perl6`. The expected identification is `Prolog`.

**Comment by pchaigno** [comment]
I ran the last release of Linguist against your repository:
```
$ linguist --breakdown
100.00% Prolog

Prolog:
simsttab.pl
```
The statistics on your repository are probably just out-of-date. They should update next time you push to your repository. If not, you can contact support@github.com for an update of statistics.

**Comment by arfon** [comment]
> The statistics on your repository are probably just out-of-date.

Yep, I've manually re-calculated these and things are looking better now.

**Comment by triska** [comment]
Many thanks for correcting this!
