### ISSUE TITLE
Terra code marked as Perl

### ISSUE THREAD

**Issue by pyk** [github/linguist#2820]
This [hello.t](https://github.com/pyk/hello-terra/blob/master/hello.t) is written in [Terra](http://terralang.org/index.html) (Lua sintax-like) but marked as Perl.

**Comment by pchaigno** [comment]
Linguist does not support Terra files yet. See the [contribution guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) if you want to add it.

**Comment by pyk** [comment]
Thanks @pchaigno !
