### ISSUE TITLE
HTML not recognised?

### ISSUE THREAD

**Issue by FarbodSalamat-Zadeh** [github/linguist#2828]
I was looking at the [Spoon-Knife repo](https://github.com/octocat/Spoon-Knife), and the language bar shows 100% CSS.

However, apart from the `README.md` file, there is one HTML file (`index.html`) and one CSS file (`styles.css`), so I would expect it to show 50% HTML and 50% CSS.

Is there a reason for it showing 100% CSS, or is this an error?

**Comment by tjgerot** [comment]
I see what you are talking about. I created a similar repo with same file tree, same file names, same file content, same commit messages, and even in the same order as the Spoon-Knife repo. My language bar said "**HTML** 100%", however when I clicked on the statistic, it presented me with my files for each language, which recognized my repo had one HTML file, and 1 CSS file, exactly as Spoon-Knife does after clicking the percent. Then it got even more interesting. As I sit here typing this response, I returned to my repo to find it was changed (without me changing anything) to 58.1% HTML and 41,9% CSS, exactly as it should be. What was the cause for this change? I know not. I would conclusively state the error lies within GitHub's language detection algorithm which must have continued to check my repo, despite not making any changes, and corrected itself. Why Spoon-Knife does it; I know not.

**Comment by arfon** [comment]
Hi @FarbodSalamat-Zadeh - sorry for the confusion caused here but HTML did not used to be included in language statistics and this repository hasn't been updated in more than 2 years. As language statistics are only updated when a repository is pushed to the language statistics cache was stale.

I've gone ahead and force-updated the language statistics for the Spoon-Knife repository and this has fixed the issue.

**Comment by tjgerot** [comment]
@arfon Thanks! That explains the confusion and my results in replicating the repository. However, I assume this isn't the only repository before the change, is it possible someone could refresh these language statistics for all repos that haven't had this update? It might end this type of issue once and for all.

**Comment by FarbodSalamat-Zadeh** [comment]
@arfon Thank you for the fix. I agree with @tjgerot 's idea that it would be beneficial to update the language statistics for the repos that haven't been updated, if this is possible.

Thanks again for the update and fix.

**Comment by arfon** [comment]
> However, I assume this isn't the only repository before the change, is it possible someone could refresh these language statistics for all repos that haven't had this update?

Ideally I'd love to do that but it's currently not something we're able to do sorry.

**Comment by tjgerot** [comment]
No, that's fine! Just wondering. Thank you!
