### ISSUE TITLE
Consider switching to language-less

### ISSUE THREAD

**Issue by 50Wliu** [github/linguist#2829]
The current submodule linguist uses to highlight Less code hasn't received a real update to syntax highlighting in nearly 2 years (https://github.com/textmate/less.tmbundle/commits/master).  Atom's `language-less` is based off of `textmate/less.tmbundle` and has received a massive update in the past few months that *should* allow for better Less highlighting: https://github.com/atom/language-less/pull/42.

**Comment by arfon** [comment]
Hi @50Wliu. We'd definitely be willing to switch this out if there are some improvements. Do you think you could demonstrate some improvements to the highlighting using the lightshow app here? https://github-lightshow.herokuapp.com/

**Comment by 50Wliu** [comment]
This is with the current grammar: [textmate/less.tmbundle](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=source.css.less&grammar_url=&grammar_text=&code_source=from-text&code_url=&code=%40import+%28reference%29+%22theme%22%3B%0D%0Ahtml%0D%0A%7B%0D%0A++++font-family%3A+%22Source+Sans+pro%22%2C+courier%2C+serif%3B%0D%0A++++text-overflow%3A+ellipsis%3B%0D%0A++++background%3A+%230F0F0F+url%28%22%40%7Bvariable%7D%2Ftest.png%22%29%3B%0D%0A%7D%0D%0Acircle%0D%0A%7B%0D%0A++++fill%3A+white%3B%0D%0A++++stroke%3A+%40blue-light%3B%0D%0A++++background%3A+rgba%280%2C+0%2C+0%2C+1%29%3B%0D%0A++++border%3A+5px+solid+currentColor%3B%0D%0A%7D%0D%0Aspan%3Afirst-of-type%0D%0A%7B%0D%0A++++font-weight%3A+bold%3B%0D%0A%0D%0A++++custom-element%3Ahover+a%2C%0D%0A++++custom-element%3Ahover+~+a%3Afirst-child%2C%0D%0A++++span%3Afirst-of-type%0D%0A++++%7B%0D%0A++++++++font-weight%3A+bold%3B%0D%0A++++++++span%3Afirst-of-type%0D%0A++++++++%7B%0D%0A++++++++++++font-weight%3A+bold%3B%0D%0A++++++++%7D%0D%0A++++%7D%0D%0A++++h5%3Afirst-of-type%0D%0A++++%7B%0D%0A++++++++font-weight%3A+bold%3B%0D%0A++++%7D%0D%0A%7D)

language-less for comparison: [atom/language-less](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fatom%2Flanguage-less%2Fmaster%2Fgrammars%2Fless.cson&grammar_text=&code_source=from-text&code_url=&code=%40import+%28reference%29+%22theme%22%3B%0D%0Ahtml%0D%0A%7B%0D%0A++++font-family%3A+%22Source+Sans+pro%22%2C+courier%2C+serif%3B%0D%0A++++text-overflow%3A+ellipsis%3B%0D%0A++++background%3A+%230F0F0F+url%28%22%40%7Bvariable%7D%2Ftest.png%22%29%3B%0D%0A%7D%0D%0Acircle%0D%0A%7B%0D%0A++++fill%3A+white%3B%0D%0A++++stroke%3A+%40blue-light%3B%0D%0A++++background%3A+rgba%280%2C+0%2C+0%2C+1%29%3B%0D%0A++++border%3A+5px+solid+currentColor%3B%0D%0A%7D%0D%0Aspan%3Afirst-of-type%0D%0A%7B%0D%0A++++font-weight%3A+bold%3B%0D%0A%0D%0A++++custom-element%3Ahover+a%2C%0D%0A++++custom-element%3Ahover+~+a%3Afirst-child%2C%0D%0A++++span%3Afirst-of-type%0D%0A++++%7B%0D%0A++++++++font-weight%3A+bold%3B%0D%0A++++++++span%3Afirst-of-type%0D%0A++++++++%7B%0D%0A++++++++++++font-weight%3A+bold%3B%0D%0A++++++++%7D%0D%0A++++%7D%0D%0A++++h5%3Afirst-of-type%0D%0A++++%7B%0D%0A++++++++font-weight%3A+bold%3B%0D%0A++++%7D%0D%0A%7D)

(Note: Many of the examples were taken from atom/language-less#42 and linked issues)

**Comment by 50Wliu** [comment]
Added in #2833.
