### ISSUE TITLE
Neither linguist-language= nor vim modelines fix highlighting, perl6

### ISSUE THREAD

**Issue by sevvie** [github/linguist#2830]
I am doing some stuff with perl6, and noticed that when I use .t, I (rather expectedly) see it trying to parse the perl6 as perl5. So I did some googling, asked around, used github.com/support, and someone on IRC told me to make an issue about this after showing them:
https://github.com/sevvie/dreams-in-code/blob/master/.gitattributes
https://github.com/sevvie/dreams-in-code/blob/master/01st-expedition/t/shipwrecked-with-camelia.t
... and as you can see, the highlighting is still broken, despite having set `*.t linguist-language=perl6` and setting an appropriate vim modeline, as per the README.

**Comment by arfon** [comment]
Looking at the page structure, the file is definitely being detected as `perl6`:

<img width="433" alt="screen shot 2016-02-02 at 8 36 31 am" src="https://cloud.githubusercontent.com/assets/4483/12750929/272bbb22-c988-11e5-82df-fd181d512d52.png">

It seems like the issue may be with the grammar that we're using for highlighting. We can manually test this using the lightshow app like this: 

https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Ftextmate%2Fperl.tmbundle%2Fblob%2Fmaster%2FSyntaxes%2FPerl%25206.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fsevvie%2Fdreams-in-code%2Fblob%2Fmaster%2F01st-expedition%2Ft%2Fshipwrecked-with-camelia.t&code=

I'm assuming this highlighting doesn't look any better?

**Comment by sevvie** [comment]
This looks somewhat better; it is, however, still not acknowledging the condensed POD formatting, highlighting keywords in what should be rendering as comments.

**Comment by arfon** [comment]
OK well it sounds like we're going to need to try and find a better grammar to highlight with as Linguist is correctly identifying this as perl6, it's just the highlighting that's letting us down.

Do you know of any other Textmate bundles or Sublime grammars that could be used here?

**Comment by MadcapJake** [comment]
My [language-perl6fe](https://github.com/MadcapJake/language-perl6fe) for Atom does a great job at Perl 6 highlighting.

**Comment by arfon** [comment]
> My language-perl6fe for Atom does a great job at Perl 6 highlighting. Right now, there is no first line detection, but that could be easily rectified.

@sevvie - here's @MadcapJake's Perl6 grammar - does this look better?

https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2FMadcapJake%2Flanguage-perl6fe%2Fblob%2Fmaster%2Fgrammars%2Fperl6fe.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fsevvie%2Fdreams-in-code%2Fblob%2Fmaster%2F01st-expedition%2Ft%2Fshipwrecked-with-camelia.t&code=

**Comment by MadcapJake** [comment]
Didn't realize there was a para pod shortcut, will add right now.

**Comment by MadcapJake** [comment]
There we go, looks much better now.

**Comment by arfon** [comment]
Yeah, that looks good. Thanks @MadcapJake
