### ISSUE TITLE
Ponyfiles vs Pony language

### ISSUE THREAD

**Issue by maandree** [github/linguist#2835]
The .pony-files in https://github.com/erkin/ponysay are marked as written in the language Pony.

You will recognise a ponyfile (the image format) by its extensive use of ▄, █, ▀, regular spaces, and CSI m escape sequences, and a few (or none) $\$, $/$, $X$, $balloon`*`$, and often starting with $$$ line followed by some text — all lines until the first blank line starting with upper case ASCII followed by a colon and a space — and then another $$$ line.

**Comment by arfon** [comment]
Hi @maandree - could you please link to an example file that is being mis-classified?

**Comment by maandree** [comment]
They do not show up in https://github.com/erkin/ponysay/search?l=pony, but the project is marked as 96,3 % Pony, and from a quick look at linguist it looks like linguists assumes that all files whose name end with .pony are written in Pony. So I believe all files in https://github.com/erkin/ponysay/tree/master/ponies and https://github.com/erkin/ponysay/tree/master/ttyponies are marked as Pony files.

**Comment by arfon** [comment]
OK thanks for reporting this @maandree. Linguist currently has a very basic support for detecting images: https://github.com/github/linguist/blob/master/lib/linguist/blob_helper.rb#L163-L168

Unfortunately this won't work here as `.pony` is a legitimate extension for a programming language too.

A couple of suggestions for a fix in the short term: Please take a look at using our [overrides](https://github.com/github/linguist#overrides) for manually excluding these files from the repository statistics. Specifically you need to add something like:

```
ponies/*.pony linguist-vendored=true
ttyponies/*.pony linguist-vendored=true
```

In the longer term we may need to look at how we can detect these `.pony` image files if this is an issue that's affecting a lot of people. A quick search leads me to believe these are pretty uncommon files: https://github.com/search?p=1&q=APPEARANCE++extension%3Apony&ref=searchresults&type=Code&utf8=%E2%9C%93 - could you tell me more about them @maandree and perhaps point to any file specifications I could read up about?

**Comment by maandree** [comment]
The specifications can be found in https://github.com/erkin/ponysay/blob/master/ponysay.pdf section 12.1 and 12.2. However, I assume Pony source code do not start with a line containg `$$$` and nothing else, so that would be a good way to figure out whether it is an image or code.

**Comment by pchaigno** [comment]
We'd welcome a pull request to recognize Ponyfiles as a data language if there's enough in-the-wild usage as required in [the contribution guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). In the meantime, you can use Linguist overrides as documented in the README and mentioned by Arfon.
