### ISSUE TITLE
Regex messes up highlighting for most of the rest of the page

### ISSUE THREAD

**Issue by TWiStErRob** [github/linguist#2839]
This regex messes up highlighting for most of the rest of the page:

``` ruby
state :descriptors do
# a full-form tag
rule /!<[0-9A-Za-z;\/?:@&=+$,_.!~*'()\[\]%-]+>/, Keyword::Type
# a tag in the form '!', '!suffix' or '!handle!suffix'
rule %r(
  (?:![\w-]+)? # handle
  !(?:[\w;/?:@&=+$,.!~*\'()\[\]%-]*) # suffix
)x, Keyword::Type
# an anchor
rule /&[\w-]+/, Name::Label
# an alias
rule /\*[\w-]+/, Name::Variable
end
```

from https://github.com/jneen/rouge/blob/master/lib/rouge/lexers/yaml.rb#L152

That apostrophe which starts the single quoted string (blue colored from there on) is in a character class (delimited by `[]`), so it shouldn't have any special meaning. If I remove the apostrophe then the percent sign does the same. If I remove all special chars from the character class, it still breaks because of the `>/` which I can't explain.

I reported it to GitHub support, which lead me here:

> We use open source TextMate-style language grammars for syntax highlighting, which are available here:
> https://github.com/github/linguist/blob/master/grammars.yml
> Linguist pulls in grammar updates with each new release, which usually happens every couple of weeks.

So based on https://github.com/github/linguist/blob/master/grammars.yml#L480
The code is at https://github.com/aroben/ruby.tmbundle/tree/4636a3023153c3034eb6ffc613899ba9cf33b41f

The problem is that I see that it is a fork and is on a branch.
It's about 20 commits behind and 2 minor commits ahead of the official master which is so much improvement in the offical that GitHub can't even show the diff:
https://github.com/aroben/ruby.tmbundle/compare/pl...textmate:master

> Syntaxes/Ruby.plist
> 2,663 additions, 1,710 deletions not shown because the diff is too large.
> Please use a local Git client to view these changes.

It's possible that this issue was already fixed by those 20 commits, would it be possible to pull those 2 minor changes to the original repo and use that so the updates are received from other contributors?

/cc @aroben

**Comment by aroben** [comment]
Current highlighting: https://github-lightshow.herokuapp.com/?utf8=✓&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Faroben%2Fruby.tmbundle%2Fblob%2Fmaster%2FSyntaxes%2FRuby.plist&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fjneen%2Frouge%2Fblob%2Fmaster%2Flib%2Frouge%2Flexers%2Fyaml.rb&code=

If we use `textmate/ruby.tmbundle` instead, it looks like this: https://github-lightshow.herokuapp.com/?utf8=✓&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Ftextmate%2Fruby.tmbundle%2Fblob%2Fmaster%2FSyntaxes%2FRuby.plist&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fjneen%2Frouge%2Fblob%2Fmaster%2Flib%2Frouge%2Flexers%2Fyaml.rb&code=

As far as I can tell the rendering is the same regardless of which version of the grammar is used, so moving off of our fork probably wouldn't help. (I'd still like to move off the fork though!)

**Comment by TWiStErRob** [comment]
Wow, nice tool! Yeah, I didn't see any particular commit related to this, but the diff was so big I hoped for it. Can I help in any way here?

**Comment by aroben** [comment]
If you want to fix the regex bug you reported, feel free to work the grammar and try out changes using Lightshow. Moving off our fork is waiting on https://github.com/textmate/ruby.tmbundle/pull/73; perhaps a comment in that PR could help move things along.

**Comment by TWiStErRob** [comment]
I tried to test the editable grammar in Lightshow but I was getting `HTTP 414 Request-URI Too Long` from the server. I even tried if zipping the grammar source would be a viable option, but that's too long too:

```html
<input type="hidden" name="grammar_text">
<textarea id="grammar_text_raw" class="js-optional-field code form-control hidden">
...
<script language="text/javascript">
submitter.addEventListener("submit", function() {
	var zip = new JSZip();
	zip.file("source.txt", document.getElementById('grammar_text_raw').value);
	submitter.grammar_text.value = zip.generate({type:"base64", compression:"DEFLATE"});
});
```
I think the method should be changed to POST for long texts, it doesn't work now anyway so you wouldn't lose the linkabily, just allow a little more leeway for use cases.

Anyway, after this I just uploaded a file to somewhere I can edit, and also managed to make the example smaller and runnable, because Sublime Text has the same issue, here's the minimal code ([lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=http%3A%2F%2Ftemp.twisterrob.net%2Fruby.plist&grammar_text=&code_source=from-text&code_url=https%3A%2F%2Fgithub.com%2Fjneen%2Frouge%2Fblob%2Fmaster%2Flib%2Frouge%2Flexers%2Fyaml.rb&code=puts+%25r%28%5B0-9%27%5D%29+%23+regex+recognized%0D%0Aputs+%2F%5B0-9%27%5D%2F+%23+regex+not+recognized%0D%0Aputs+%22hello%22+%23+all+from+here+is+part+of+a+string+until+the+next+apostrophe%0D%0A%23+this+is+still+a+comment%2C+%27+but+highlighted+as+code%3A+def+x+%3D+1%2B2%0D%0Arule+%2F%21%3C%5B0-9A-Za-z%3B%5C%2F%3F%3A%40%26%3D%2B%24%2C_.%21~*%27%28%29%5C%5B%5C%5D%25-%5D%2B%3E%2F%2C+Keyword%3A%3AType%0D%0Arule+%25r%28%21%3C%5B0-9A-Za-z%3B%5C%2F%3F%3A%40%26%3D%2B%24%2C_.%21~*%27%28%29%5C%5B%5C%5D%25-%5D%2B%3E%29%2C+Keyword%3A%3AType)):
```ruby
puts %r([0-9'])
puts /[0-9']/
puts "hello" # all from here is part of a string until the next apostrophe
# this is still a comment, ' but highlighted as code: def x = 1+2
```

The fix I found was that `/.../` needs to be matched at the same time as the `%r×...×` (`string.regexp.mod-r.ruby`) versions. Sadly I don't know enough about ruby nor syntax grammars to know if this is the correct approach.

**Comment by pchaigno** [comment]
@TWiStErRob Thanks for working on this! Please report your findings to the grammar repository, as it is not something that can be fixed in Linguist.
