### ISSUE TITLE
Classify props file as XML

### ISSUE THREAD

**Issue by jasonwilliams200OK** [github/linguist#2852]
In VS land `.props` file are XML format, which contain the project properties and used by msbuild:
https://msdn.microsoft.com/en-us/library/669zx6zc.aspx

Example of such a file is https://github.com/dotnet/corefx/blob/67a17b3/dir.props

Please classify `.props` and `.xml`, so GitHub syntax highlighting can catch up.

cc @mellinoe, @rainersigwald

**Comment by arfon** [comment]
Hi @jasonwilliams200OK we'd welcome a Pull Request implementing this change :smile:. You can find our [contributing guidelines here](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language).

**Comment by larsbrinkhoff** [comment]
Note: [70000 `.props` files seem to be XML](https://github.com/search?q=extension%3Aprops+xml+version+encoding), and [90000 files seem to be something else](https://github.com/search?q=extension%3Aprops+NOT+xml+NOT+version+NOT+encoding).

**Comment by jasonwilliams200OK** [comment]
@larsbrinkhoff, more fair comparison would be

XML: https://github.com/search?utf8=%E2%9C%93&q=extension%3Aprops+xml+version+encoding+OR+project&type=Code&ref=searchresults (80k)

Non-XML: https://github.com/search?p=1&q=extension%3Aprops+NOT+xml+NOT+version+NOT+encoding+NOT+project&ref=searchresults&type=Code&utf8=%E2%9C%93 (88k)

Is there a way to resolve conflicting extensions scenarios, something like `those `.props` which contain markup should be classified as XML`?

**Comment by larsbrinkhoff** [comment]
Only if you also add a language for that "other syntax".  If you do that, you can add `.props` samples for that, and if necessary add [heuristics](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.rb).

I'm not saying this should be done now, mostly just adding some notes in case a future contributor wonder what happened.
