### ISSUE TITLE
Wrong percentage of languages. Ignores Golang

### ISSUE THREAD

**Issue by kriox26** [github/linguist#2854]
The repository: https://github.com/kriox26/rt-slackclone has 4 `.go` files which are not taken into account when showing the percentage of each language. The number of files are displayed correctly here:
![screen shot 2016-02-25 at 4 37 08 pm](https://cloud.githubusercontent.com/assets/8126891/13332037/df6319de-dbde-11e5-9194-5c24dcce647b.png)
And the colored bar is showing this:
![screen shot 2016-02-25 at 4 39 37 pm](https://cloud.githubusercontent.com/assets/8126891/13332055/f4cb624a-dbde-11e5-858c-726596180c62.png)

**Comment by arfon** [comment]
> The repository: https://github.com/kriox26/rt-slackclone has 4 .go files which are not taken into account when showing the percentage of each language. The number of files are displayed correctly here:

Hi @kriox26. They are being taken into account, the issue here is that you have 731KB of Javascript and  4.5 KB of Go. The repository stats are based on lines of code and so the Javascript files are dwarfing your repository statistics.

**Comment by kriox26** [comment]
I see, sorry for the confusion. Thanks! :+1:
