### ISSUE TITLE
Python highlighting real strange

### ISSUE THREAD

**Issue by amueller** [github/linguist#2860]
Since a couple of weeks, the python highlighting seems really odd:
![python_highlighting_messed_up](https://cloud.githubusercontent.com/assets/449558/13507930/f914ccfa-e152-11e5-8ba1-9eb9e18cc6e6.png)

what is the orange supposed to mean?
Random words seem to be highlighted in orange.

**Comment by pchaigno** [comment]
Linguist only selects the grammar to use for highlighting. For Python, GitHub uses [MagicStack/MagicPython](https://github.com/MagicStack/MagicPython). You should open an issue there if there isn't already one ;)

**Comment by amueller** [comment]
Thanks and sorry for the noise.

**Comment by pchaigno** [comment]
No worries ;)
