### ISSUE TITLE
Ability to set file extension -> syntax mapping at repo level.

### ISSUE THREAD

**Issue by jordwalke** [github/linguist#2864]
I believe that it would be fairly easy to set repo level overrides in the `.gitattributes` so that I could claim that all `.xyz` file extensions should be treated/highlighted as `OtherLanguage`. Why does it not currently work this way?

**Comment by arfon** [comment]
Hi @jordwalke. This is already works for the repository statistics (see https://github.com/github/linguist#using-gitattributes) but unfortunately this currently doesn't work for syntax highlighting (see https://github.com/github/linguist/issues/1792)
