### ISSUE TITLE
C#6 - string interpolation issue

### ISSUE THREAD

**Issue by jasonwilliams200OK** [github/linguist#2865]
The following two code blocks are syntactically different but semantically equivalent:

C# (rank 5)

```c#
string str = "--resource:" + resource.Replace("\"", "");
allArgs.AddRange(references.Select(r => "-r:" + r));
```

C# (rank 6)

```c#
string str = $"--resource:{resource.Replace("\"", "")}";
allArgs.AddRange(references.Select(r => $"-r:{r}"));
```

As evident, the GitHub editor syntax highlighting around quotes is mismanipulated in C# 6.

Feature release notes: https://github.com/dotnet/roslyn/wiki/New-Language-Features-in-C%23-6#string-interpolation

(perhaps the C# syntax per-processor can make use of Roslyn compiler, which works cross-platform?)

cc @jaredpar @akoeplinger for visibility

**Comment by pchaigno** [comment]
Linguist only selects the grammar to use for highlighting. For C#, GitHub uses [atom/language-csharp](https://github.com/atom/language-csharp/tree/f635e67edef4e2fe68c3526e1ad26ed66f01aa62). You should open an issue there if there isn't already one ;)

**Comment by jasonwilliams200OK** [comment]
Thanks @pchaigno! :)

I have found the resembling issue: https://github.com/atom/language-csharp/issues/43.

Closing this. :tada:
