### ISSUE TITLE
capnp: Closing parentheses in interface method declarations are highlighted as part of the type

### ISSUE THREAD

**Issue by jplatte** [github/linguist#2867]
Here's a simple example:

```capnp
interface Example {
  method @0 (arguments :List(Type)) -> (returnValue :OtherType);
}
```

**Comment by arfon** [comment]
Hi @jplatte, thanks for reporting this. Linguist only detects the language of the code, not how to highlight the code. You'll need to file a bug report upstream here: https://github.com/textmate/capnproto.tmbundle

**Comment by jplatte** [comment]
Okay, thanks for the quick reply!
