### ISSUE TITLE
Nested comments in Dart are not recognized

### ISSUE THREAD

**Issue by joseluis** [github/linguist#2872]
Dart has nested comments, but the GitHub syntax highlighter doesn't recognize them. For example:

```dart
/*
/*
 Comment
 
 /* nested comment */
​
*/ // <-- not highlighted
​
main() {}
```

Related: https://github.com/dart-lang/sdk/issues/25931

**Comment by arfon** [comment]
Hi @joseluis. Thanks for reporting this. Unfortunately this is an upstream issue in the grammar we use for highlighting: https://github.com/guillermooo/dart-sublime-bundle

If/when the issue is fixed there we'll pick up the changes automatically.
