### ISSUE TITLE
BCPL is not Brainfuck

### ISSUE THREAD

**Issue by rptb1** [github/linguist#2874]
Until I added .gitattributes, GitHub thought my BCPL project https://github.com/rptb1/clavicom was written in Brainfuck.  If it were, I wouldn't've passed my ‘A’-level exams, but I would perhaps have become a timelord.

I will try to find time to submit a pull, but it's unlikely any time soon.

**Comment by larsbrinkhoff** [comment]
Shouldn't `.b` be B? ;-)

I do enjoy classical languages very much, so I'm sad to say there may not be enough BCPL files at GitHub to warrant addition of that language.  See the [contribution guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language).

**Comment by Alhadis** [comment]
@rptb1 What file extensions does BCPL, other than `.b`? I notice there's a [file in your repo](https://github.com/rptb1/clavicom/blob/master/clavi1.sub) with the `.sub` extension that's written in (what I'm guessing) is BCPL.

**Comment by rptb1** [comment]
[Martin Richard's BCPL distribution](https://www.cl.cam.ac.uk/~mr10/BCPL.html) (*the* compiler) uses `.b` as does the [Arnor BCPL manual](https://www.cl.cam.ac.uk/~mr10/BCPL.html).  My use of `.sub` isn't canonical — more to do with me working in isolation, pre-Internet.

**Comment by rptb1** [comment]
By the way, if it has `$(` and `$)` then it's BCPL. BCPL was the first language with "section brackets" that later turned up as `{` and `}` — the "squiggle" and "squoggle"!

**Comment by rptb1** [comment]
Now I've seen one! https://github.com/eli-davis/BCPL/blob/master/data_structures/linked_list.bcpl
However, [this big pile of BCPL programs](https://github.com/8l/bcpl/tree/master/bcplprogs) uses `.b`.

**Comment by Alhadis** [comment]
Hrm, I see.

BCPL needs a language grammar before it can be parsed by Linguist. From cursory searches, there doesn't appear to be one.

I'd write one, but I'd need a comprehensive language reference first.

**Comment by rptb1** [comment]
That's very enterprising of you.  Full BNF grammar in the manual https://www.bell-labs.com/usr/dmr/www/bcpl.pdf thought some details changed later. There's more info here https://www.bell-labs.com/usr/dmr/www/bcpl.html and of course and I may be able to help out a bit later.

**Comment by Alhadis** [comment]
Now we're talking. ;)

Will look into doing so once I've finished working on [this](https://github.com/Alhadis/language-roff) (A language pack exists, but its support is limited to man-page macros only...)

**Comment by mahfoud14** [comment]
Slp
Le 29 mars 2016 18:28, "Richard Brooksby" <notifications@github.com> a
écrit :

**Comment by Alhadis** [comment]
No? I was under the impression Linguist used TextMate-compatible grammars to identify different parts of a language's anatomy (comments, keywords, standard library functions, etc) which influenced the results of its analysis...

**Comment by larsbrinkhoff** [comment]
@Alhadis No, that's not how it works. The grammars are used for syntax highlighting when viewing files.

Language classification analysis is done with filenames, shebangs, heuristics, editor modelines, etc.

**Comment by Alhadis** [comment]
![jjsdevl](https://cloud.githubusercontent.com/assets/2346707/14119299/403f619e-f639-11e5-8be4-b4843db90d47.jpg)

**Comment by pchaigno** [comment]
Flagging as stale.
