### ISSUE TITLE
PowerBASIC/thinBASIC identified as Assembly

### ISSUE THREAD

**Issue by petrSchreiber** [github/linguist#2878]
Dear authors,

first of all - thank you for all the work you put in your effort.

There is a minor issue I found out and cannot resolve it by myself. I am using two programming languages which are not (yet) supported by linguist, so I thought adjusting the .gitattributes file according to docs (https://github.com/github/linguist#troubleshooting) will do the job.

Sadly the trick did not work in any of the cases I tried. It affects the following repositories:
[thinBasic_iniFile](https://github.com/petrSchreiber/thinBasic_iniFile)
[thinBasic_enVar](https://github.com/petrSchreiber/thinBasic_enVar)
[thinBasic_stringBuilder](https://github.com/petrSchreiber/thinBasic_StringBuilder)

They all share the same .gitattributes, which look like this:
[.gitattributes](https://github.com/petrSchreiber/thinBasic_enVar/blob/master/.gitattributes)

Any help would be appreciated - I guess I am missing some obvious mistake in .gitattributes setup.
As a co-author of thinBasic I would appreciate solution of this, as I try to persuade our users to use gitHub more (because it is awesome).

**Comment by pchaigno** [comment]
I am not from GitHub but I might be able to shed some light on the problem. Linguist overrides only work with languages already recognized by Linguist, i.e. you cannot define your own language via `.gitattributes`.

A way to fix this would be to recognize the two languages. Please take a look at [the contribution guidelines to add support for a new language](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). In particular, notice the *in-the-wild adoption* requirement.

**Comment by petrSchreiber** [comment]
You are very kind, thank you for your reply.

I understand the in-the-wild adoption wants to avoid adding stuff which might fade away again, but as PowerBASIC is in business since 1989 and thinBasic since 2004, both actively used, would be nice to have allowance to create pull request for integration of these.

I will wait for reply of the local masters then. Thank you again!

**Comment by pchaigno** [comment]
An estimation of the number of PowerBASIC and thinBasic files via a GitHub search could help ;)

**Comment by petrSchreiber** [comment]
Give me few days, I asked the community to help me give you precise numbers.

**Comment by larsbrinkhoff** [comment]
Previous discussion about BASIC dialects: #2288

**Comment by pchaigno** [comment]
Flagging as stale :flags:

**Comment by petrSchreiber** [comment]
pchaigno, I did my research as promised, but from the reaction I got I realized that "we are not there yet".

We will try to drive our community to learn to adopt GitHub as code sharing platform and once we succeed, I'll be back ;)

Thanks for your time, and keep rockin' with linguist!

**Comment by pchaigno** [comment]
> We will try to drive our community to learn to adopt GitHub as code sharing platform and once we succeed, I'll be back ;)

Looking forward to it!
