### ISSUE TITLE
Standard C header files detected as C++

### ISSUE THREAD

**Issue by eyolfson** [github/linguist#2881]
Given what I've seen, these files should detect as C header files:

- https://github.com/eyolfson/nes-emulator/blob/f0d3de9a78ed764b71c0a11de28c12b1ad58273b/src/cpu.h
- https://github.com/eyolfson/nes-emulator/blob/f0d3de9a78ed764b71c0a11de28c12b1ad58273b/src/exit_code.h

However, even though they use the `__cpluscplus` test and use `<stdint.h>` instead of `<cstdint>` they still report as C++.

**Comment by Kuronogard** [comment]
This is also happening in one of my projects, All the headers in the following link are classified as C++ although i don't use any C++ feature.

https://github.com/Kuronogard/aavrlib/search?l=cpp

**Comment by eyolfson** [comment]
Yup, still happening.

- https://github.com/eyolfson/nes-emulator/blob/27698be97b6c0da2c86cd60cd7eedcd0ad36aadb/src/cartridge.h
- https://github.com/eyolfson/nes-emulator/blob/27698be97b6c0da2c86cd60cd7eedcd0ad36aadb/src/exit_code.h

**Comment by pchaigno** [comment]
This issue is discussed at #1626. In the meantime, you can use [Linguist overrides](https://github.com/github/linguist#overrides) to ensure all `.h` files are detected as C files.
