### ISSUE TITLE
Find grammars to replace those removed in #2884

### ISSUE THREAD

**Issue by arfon** [github/linguist#2885]
We've recently had to remove some language grammars (#2884). Ideally we need to find replacement grammars that are compatible with our [license whitelist](https://github.com/github/linguist/blob/master/test/test_grammars.rb#L14-L25) or encourage authors of the (currently removed) grammars to dual-license them.

- [x] https://github.com/Cykey/Sublime-Logos
- [ ] https://github.com/Red-Nova-Technologies/autoitv3-tmbundle
- [x] https://github.com/Shammah/boo-sublime
- [x] https://github.com/austinwagner/sublime-sourcepawn
- [x] https://github.com/cdwilson/nesC.tmbundle
- [x] https://github.com/gingerbeardman/monkey.tmbundle
- [x] https://github.com/idris-hackers/idris-sublime
- [x] https://github.com/lunixbochs/x86-assembly-textmate-bundle
- [x] https://github.com/nanoant/assembly.tmbundle
- [x] https://github.com/puppet-textmate-bundle/puppet-textmate-bundle
- [x] https://github.com/wmertens/sublime-nix
- [x] https://github.com/steinwaywhw/ats-mode-sublimetext
- [ ] https://github.com/psicomante/CLIPS-sublime
- [ ] https://github.com/Siddley/Creole
- [x] https://github.com/beefsack/GDScript-sublime
- [x] https://github.com/zmthy/grace-tmbundle
- [ ] https://github.com/idleberg/InnoSetup-Sublime-Text
- [ ] https://github.com/mulander/oracle.tmbundle.git (can't be relicensed)
- [x] https://github.com/goblindegook/sublime-text-pig-latin
- [ ] https://github.com/tbuser/openscad.tmbundle

**Comment by arfon** [comment]
Possible Assembly replacement: https://github.com/calculuswhiz/Assembly-Syntax-Definition

**Comment by pchaigno** [comment]
Why were https://github.com/nanoant/assembly.tmbundle and https://github.com/idleberg/InnoSetup-Sublime-Text removed? They seem to be under MIT license :/

**Comment by arfon** [comment]
> Why were https://github.com/nanoant/assembly.tmbundle and https://github.com/idleberg/InnoSetup-Sublime-Text removed? They seem to be under MIT license :/

Good catch. I'll add those back. Not sure why I removed those...

**Comment by vcunat** [comment]
What's wrong with grammars under non-permissive licenses? In README you state:
> The language grammars included in this gem are covered by their repositories' respective licenses.

I'm no lawyer, but it seems the worst thing that could happen when using linguist with (say) a GPL-licensed grammar is that together the license would be GPL. Why not keep that as an option, at least?

**Comment by arfon** [comment]
@vcunat - non-permissive licenses aren't compatible with the ways in which Linguist is distribute so we need all included grammars to have a permissive license I'm afraid.

**Comment by vcunat** [comment]
I see.

**Comment by copumpkin** [comment]
@arfon looks like @wmertens moved the nix highlighter to MIT. Can we get it reinstated on the live site? I use GitHub to browse Nix files a lot and it makes a big difference.

**Comment by arfon** [comment]
Yep. I will get to this early next week. We need to cut a new gem and deploy before this can be re-instated.

**Comment by copumpkin** [comment]
Thanks!

**Comment by arfon** [comment]
@copumpkin @wmertens #2914 is now live on GitHub.

**Comment by arfon** [comment]
> @arfon @wmertens awesome, thank you both for dealing with this so quickly! The Nix community thanks you :smile:

👍 my pleasure.

**Comment by arfon** [comment]
We've done pretty well here. Closing this out for now.
