### ISSUE TITLE
Need to add test for licenses

### ISSUE THREAD

**Issue by arfon** [github/linguist#2888]
`script/licensed --verify` needs to be run as a CI task.

**Comment by pchaigno** [comment]
There are already [some tests for grammar licenses](https://github.com/github/linguist/blob/master/test/test_grammars.rb#L73-L93). Are some additional tests required? Or do you want to run them in a standalone script?

**Comment by arfon** [comment]
Those tests are good but we're now writing out the licenses for each of the dependencies into `vendor/licenses` using `https://github.com/github/linguist/blob/master/script/licensed`.

Ultimately we need to test that these files are present and are listing a permitted license. This is a WIP thing on our side but part of a larger effort to be more explicit about documenting the licenses of all of our tools (and their dependencies).
