### ISSUE TITLE
[request] Syntax highlighting for IL assembly

### ISSUE THREAD

**Issue by jamesqo** [github/linguist#2890]
It'd be pretty nice to have a syntax highlighter for .NET intermediate language files. While they're not the exactly the most common, they're used in a bunch of libraries that call opcodes not expressible from C# ([example](https://github.com/DotNetCross/Memory.Unsafe/blob/master/il/DotNetCross.Memory.Unsafe.il)). Having syntax highlighting would make a huge difference in readability, and besides, we already have one for LLVM.

**Comment by arfon** [comment]
@jamesqo - do you know of any grammars (Sublime, Atom or Textmate bundles) that we could use to do this?

**Comment by jamesqo** [comment]
@arfon I found [this](https://github.com/mono/monodevelop/blob/bc908c9e791b0ee6f4951fb65495f82735bc95b7/main/src/core/Mono.Texteditor/SyntaxModes/ILSyntaxMode.xml) in the MonoDevelop repo - doesn't look like it should be too hard to convert to a `.plist` or JSON-based grammar, but I'm not too experienced with this stuff so I wouldn't know.

**Comment by pchaigno** [comment]
To highlight files, GitHub must first be able to recognize their language using Linguist. Please see the [guidelines to add support for a new language to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). If IL assembly meets the requirement on in-the-wild usage, don't hesitate to open a pull request.
