### ISSUE TITLE
The Language stats bar doesn't display JavaScript

### ISSUE THREAD

**Issue by burkovsky** [github/linguist#2904]
The repository - https://github.com/burkovsky/ab

https://api.github.com/repos/burkovsky/ab/languages API command doesn't detect any JavaScript bytes of code.

**Comment by arfon** [comment]
Hi @burkovsky - this is because Linguist excludes minified JavaScript (and CSS): https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml#L50-L51

The rationale behind this decision is that these are usually dependencies (e.g. jQuery) that haven't actually been authored by the repository creators.

**Comment by burkovsky** [comment]
Hi @arfon. Thank you for your response, but it's still weird that api doesnt find javascript code at all, even if it's my file without minified version. Also one more weirdness that before my todays large manipulations with solution ([commit](https://github.com/burkovsky/ab/commit/d08ee2b575e67d29b2c264056cb04e1065f427d8)) stats bar worked fine.

**Comment by arfon** [comment]
> Hi @arfon. Thank you for your response, but it's still weird that api doesn't find javascript code at all, even if it's my file without minified version. Also one more weirdness that before my todays large manipulations with solution (commit) stats bar worked fine.

Could you link to some example JavaScript files that you think *should* be included in the language statistics?

**Comment by burkovsky** [comment]
> Could you link to some example JavaScript files that you think should be included in the language statistics?

For example this [folder](https://github.com/burkovsky/ab/tree/master/AB.Web/Scripts/angular-app) contains JavaScript files only developed by me.

**Comment by arfon** [comment]
> For example this folder contains JavaScript files only developed by me.

Ah OK. I'm afraid this line in our vendor definition is also excluding these files: https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml#L170-L171

I think you'll need to use our [overrides](https://github.com/github/linguist#overrides) to fix this issue. you can see an example of how to do that here: https://github.com/burkovsky/ab/compare/master...arfon:master

**Comment by burkovsky** [comment]
Oh, I see. @arfon thank you for your help.
I'll explore the vendor's definition to make stats more accurate.

**Comment by arfon** [comment]
:+1: ok great.
