### ISSUE TITLE
Colorize fish-shell files with a shebang

### ISSUE THREAD

**Issue by onodera-punpun** [github/linguist#2913]
See: https://github.com/github/linguist/issues/2713

The vast majority if scripts in this repo are fish scripts, however it only shows "shell" in the bar: https://github.com/onodera-punpun/bin

Another example: https://github.com/onodera-punpun/neet
it only shows Makefile in the language bar, yet the fish script is much much bigger and doesn't get shown at all...

All of them are executable.

**Comment by arfon** [comment]
#2995 fixes this.

> The vast majority if scripts in this repo are fish scripts, however it only shows "shell" in the bar: https://github.com/onodera-punpun/bin

The language bar will still list `Shell` for the same reason outlined here: https://github.com/github/linguist/pull/2978#issuecomment-217525763 . The files _will_ be highlighted though after #2995 goes into production.
