### ISSUE TITLE
Lightshow unable to parse CSON grammars with unquoted keys

### ISSUE THREAD

**Issue by Alhadis** [github/linguist#2924]
Lightshow [complains](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-text&grammar_url=http%3A%2F%2Fpastebin.com%2Fraw%2FdXX2DyVh&grammar_text=name%3A+%22Quotes+Test%22%0D%0AscopeName%3A+%22source.quotes-test%22%0D%0AfileTypes%3A+%5B%22quotes-test%22%5D%0D%0Apatterns%3A+%5B%7B%0D%0A%09name%3A+%22comment.line.quotes-test%22%0D%0A%09begin%3A+%22COMMENT%3A+%22%0D%0A%09end%3A+%22%24%22%0D%0A%7D%5D&code_source=from-text&code_url=https%3A%2F%2Fraw.githubusercontent.com%2FAlhadis%2Flanguage-apl%2Fmaster%2Ftests%2Fgnu-web.apl&code=%23+Comment%0D%0A%0D%0ASecond+line.) if a CSON/JSON grammar uses unquoted property names... presumably because it's mistaken it as YAML source:

> Error parsing YAML grammar: (<unknown>): did not find expected ',' or '}' while parsing a flow mapping at line 4 column 12

If quote marks are added, [the problem goes away](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-text&grammar_url=http%3A%2F%2Fpastebin.com%2Fraw%2FdXX2DyVh&grammar_text=%22name%22%3A+%22Quotes+Test%22%0D%0A%22scopeName%22%3A+%22source.quotes-test%22%0D%0A%22fileTypes%22%3A+%5B%22quotes-test%22%5D%0D%0A%22patterns%22%3A+%5B%7B%0D%0A%09%22name%22%3A+%22comment.line.quotes-test%22%0D%0A%09%22begin%22%3A+%22%23%22%0D%0A%09%22end%22%3A+%22%24%22%0D%0A%7D%5D&code_source=from-text&code_url=https%3A%2F%2Fraw.githubusercontent.com%2FAlhadis%2Flanguage-apl%2Fmaster%2Ftests%2Fgnu-web.apl&code=%23+Comment%0D%0A%0D%0ASecond+line.).

(I understand the Lightshow app is [closed source](https://github.com/github/linguist/issues/2023#issuecomment-71478936), which is why I'm filing an issue instead of submitting a pull request...)

**Comment by arfon** [comment]
> (I understand the Lightshow app is closed source, which is why I'm filing an issue instead of submitting a pull request...)

I believe this may be a short-term issue.

/ cc @aroben

**Comment by pchaigno** [comment]
This issue was reported before in #2703 ;)

**Comment by Alhadis** [comment]
Strange, that didn't turn up in the search results. :S Sorry.

**Comment by pchaigno** [comment]
@Alhadis No problem :-)

**Comment by lildude** [comment]
> Lightshow complains if a CSON/JSON grammar uses unquoted property names... presumably because it's mistaken it as YAML source:
> 
>> Error parsing YAML grammar: (): did not find expected ',' or '}' while parsing a flow mapping at line 4 column 12

Not anymore 😄 and if it still gets it wrong from attempting to auto-detect the format, you can manually select the format of the grammar.
