### ISSUE TITLE
Python: highlight docstrings differently from strings literals

### ISSUE THREAD

**Issue by 1st1** [github/linguist#2925]
Sorry if this is the wrong project to request this feature.  GitHub is currently using [MagicPython](https://github.com/MagicStack/MagicPython) to highlight Python code. And MagicPython assigns distinct scopes to docstrings (there is a `.docstring.` extra scope):

```
string.quoted.docstring.multi.python
string.quoted.docstring.raw.multi.python
string.quoted.docstring.raw.single.python
string.quoted.docstring.single.python
```

It would be really cool if GitHub could color docstrings differently from regular string literals. Here's how it might look like:

![screen shot 2016-03-30 at 11 37 21 pm](https://cloud.githubusercontent.com/assets/239003/14164747/62aa42b6-f6d0-11e5-9ed5-42c6f7f0aa7d.png)

**Comment by pchaigno** [comment]
Shouldn't MagicPython assign the scope `comment.block.docstring.` to docstrings?
In any case, it's not something that can be changed in Linguist. You'll have better chances of being heard at MagicPython or by contacting support@github.com ;)

**Comment by 1st1** [comment]
Alright, I'll try contacting support. Sorry for the disturbance!
