### ISSUE TITLE
My C# file breaks the syntax highlighting

### ISSUE THREAD

**Issue by michaelpittino** [github/linguist#2926]
Hello! My (afaik valid) C# code breaks the syntax highlighting: https://github.com/michaelpittino/ReplayGG/blob/master/ReplayGG/Replays/Replay.cs

Would you mind looking into this?
Thanks!

**Comment by pchaigno** [comment]
Linguist only selects the grammar to use for highlighting. For C#, GitHub uses [atom/language-csharp](https://github.com/atom/language-csharp/tree/96ab79f45bfb6875c9aa2ac702934a385df35de3). You should open an issue there if there isn't already one ;)
