### ISSUE TITLE
C++ detected instead of Python in PyGeM repo

### ISSUE THREAD

**Issue by mtezzele** [github/linguist#2931]
This repo:

https://github.com/mathLab/PyGeM

shows 92.9% of C++ code and when I click on that it does not find any C++ file (because there are only .py files). I do not know why it marks the repo as a C++ repo. I never pushed C++ files, only python ones.

**Comment by arfon** [comment]
Files such as this one: https://github.com/mathLab/PyGeM/blob/master/tests/test_datasets/test_openFOAM are being detected as C++ and as they're so big they're dwarfing the language statistics for the repo.

You can fix this by creating a `.gitattributes` file and including the following:

tests/test_datasets/* linguist-vendored=true

**Comment by mtezzele** [comment]
@arfon Thank you very much!
