### ISSUE TITLE
Using language-c instead of c.tmbundle for C/C++ language support

### ISSUE THREAD

**Issue by jamesqo** [github/linguist#2932]
Atom has a good language support for C/C++ that's been updated in the last few days over [here.](https://github.com/atom/language-c) Meanwhile, TextMate's equivalent repo [here](https://github.com/textmate/c.tmbundle) hasn't been updated in the last 2 years and looks mostly dead to me. Why don't we switch over to Atom's version, then? (I'll make a pull request on my own if need be.)

**Comment by pchaigno** [comment]
A pull request would be welcome if you can show the improvement using [Lightshow](https://github-lightshow.herokuapp.com/) ;)

**Comment by arfon** [comment]
> Why don't we switch over to Atom's version, then? (I'll make a pull request on my own if need be.)

Sounds good to me.
