### ISSUE TITLE
Nervana sass files are wrongly identified as CSS

### ISSUE THREAD

**Issue by kriskhaira** [github/linguist#2933]
Nervana shader assembly files (*.sass) are being wrongly identified as CSS. Examples:

* https://github.com/baidu-research/nervanagpu
* https://github.com/NervanaSystems/maxas

**Comment by pchaigno** [comment]
To fix this, we'd have to recognize Nervana shader assembly files in Linguist and distinguish them from SASS. Is there a simple way to identify a Nervana shader assembly file?

**Comment by kriskhaira** [comment]
I'm not sure. I was just looking for Baidu's web-related open source projects and found this.

But looks like all sass files start with `Kernel: ` and contain `--:-:-:-:`.

**Comment by pchaigno** [comment]
Hm. Not always: https://github.com/woodun/swl_outputs/blob/12c46dd6fad73d9c92b471ecdaa2e1f8b213b6e1/gto/lonestar/sssp/_cuobjdump_1.sass but that may be another dialect :/

**Comment by pchaigno** [comment]
Closing in favor of #3093.
