### ISSUE TITLE
“.jsee” files are JavaScript and “.vbee” are VBScript files

### ISSUE THREAD

**Issue by jesus2099** [github/linguist#2943]
“.jsee” files are [EmEditor JavaScript macro files](http://emeditor.com/text-editor-features/extensibility/scriptable-macros/) (here are [some clumsy examples](//github.com/jesus2099/settings/tree/master/EmEditor/macros), just to illustrate how they don’t render yet as JavaScript).
Similarly, “.vbee” files are VBScript macro files.

**Comment by pchaigno** [comment]
Please see [the contribution guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) on how to add support for a new language in Linguist.

**Comment by jesus2099** [comment]
Thanks for the link, @pchaigno, I’ll make a PR when having some time to understand all that.
I am still wondering if I should add extensions to existing JavaScript section or create a new section for EmEditor…

**Comment by pchaigno** [comment]
Since `.jsee` files are JavaScript files, I think you should add it as an extension to JavaScript. Same for `.vbee`.

**Comment by jesus2099** [comment]
Thanks very much. :)
