### ISSUE TITLE
wrong colorization of var

### ISSUE THREAD

**Issue by OneOfOne** [github/linguist#2944]
https://github.com/Microsoft/vscode/commit/29fbb3e8455589641168edc97b6c97698d9f7fd0#diff-95f50894c440bb8a32933aaeba572732R53

**Comment by pchaigno** [comment]
Linguist only selects the grammar to use for highlighting. For TypeScript, GitHub uses [Microsoft/TypeScript-Sublime-Plugin](https://github.com/Microsoft/TypeScript-Sublime-Plugin/tree/2da61f59d231b5442e1a7136aedcb9705ad099e2). You should open an issue there if there isn't already one ;)

**Comment by OneOfOne** [comment]
thanks, I'll submit it there, thanks.
