### ISSUE TITLE
Jade has renamed itself to Pug

### ISSUE THREAD

**Issue by TimothyGu** [github/linguist#2956]
... and with the name change file extension detection should now be changed from `.jade` to `.pug`.

See pugjs/pug#2184.

**Comment by abdulhannanali** [comment]
`.jade` should also be highlighted meanwhile, because there's plenty of templates on github that are in .jade. so .pug should be added in the file detection. Suggestion

**Comment by arfon** [comment]
> .pug should be added in the file detection. 

We'd welcome a pull request with this change.

**Comment by Alhadis** [comment]
@arfon This issue can be closed now. =)

**Comment by abdulhannanali** [comment]
:smile:

**Comment by OutsourcedGuru** [comment]
I'm finding that after converting an Express-generated Node.js app from jade to pug, suddenly github is incorrectly shifting the project from being a JavaScript-type to an HTML.

As a workaround, I added a **.gitattributes** file to my project and it seems to correctly shift things back to JavaScript.

```
node_modules/* liguist-vendored
README.md linguist-documentation
views/*.pug linguist-documentation
LICENSE linguist-documtation
package.json linguist-documentation
```
