### ISSUE TITLE
S-Lang not recognized.

### ISSUE THREAD

**Issue by jedmodes** [github/linguist#2958]
Have a look, for lots of examples of **S-Lang** scripts, here: https://github.com/jedmodes/jedmodes .

**Comment by arfon** [comment]
Hi @jedmodes - we'd welcome a Pull Request to add support for S-Lang: https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language

**Comment by jedmodes** [comment]
`
--- a/languages.yml	2016-04-19 15:31:59.000000000 -0700
+++ b/languages.yml	2016-04-19 15:38:01.000000000 -0700
@@ -3173,6 +3173,18 @@
   - .rs.in
   ace_mode: rust
 
+S-Lang:
+  type: programming
+  ace_mode: text
+  color: "#0066cc"
+  extensions:
+  - .sl
+  interpreters:
+  - jed
+  - slang
+  - slrn
+  - slsh
+		    
 SAS:
   type: programming
   color: "#B34936"
`

**Comment by jedmodes** [comment]
--- a/languages.yml	2016-04-19 15:31:59.000000000 -0700
+++ b/languages.yml	2016-04-19 15:38:01.000000000 -0700
@@ -3173,6 +3173,18 @@
   - .rs.in
   ace_mode: rust
 
+S-Lang:
+  type: programming
+  ace_mode: text
+  color: "#0066cc"
+  extensions:
+  - .sl
+  interpreters:
+  - jed
+  - slang
+  - slrn
+  - slsh
+		    
 SAS:
   type: programming
   color: "#B34936"

**Comment by jedmodes** [comment]
Ok, I admit defeat. I did try.

**Comment by pchaigno** [comment]
@jedmodes Do you have the "[GitHub search result](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aboot+NOT+nothack&type=Code&ref=searchresults) showing in-the-wild usage"?

**Comment by arfon** [comment]
🎏 flagging as stale 🎏
