### ISSUE TITLE
Non-generated PostScript file diffs not shown

### ISSUE THREAD

**Issue by terryburton** [github/linguist#2962]
What are GitHub's current criteria for displaying a diff?

My project consists of mostly non-generated PostScript whose files can be displayed individually but do not appear in diffs which is annoying since it means fewer eyes-on.

See this commit for example: https://github.com/bwipp/postscriptbarcode/commit/3773466e8b47e8f628f8ce17ec79d0651e3ed680

It's not clear to me why a 7-bit clean file such as this isn't being diff'ed but will be displayed: https://github.com/bwipp/postscriptbarcode/blob/3773466e8b47e8f628f8ce17ec79d0651e3ed680/src/datamatrix.ps

linguist gives the following properties:

generated? => false
binary_mime_type? => true
likely_binary? => false
binary? => false

**Comment by arfon** [comment]
> What are GitHub's current criteria for displaying a diff?

GitHub relies upon Linguist for this.

> `binary_mime_type? => true`

I think this result is coming from the `mime-types` gem: https://github.com/github/linguist/blob/master/github-linguist.gemspec#L18 I'm not sure why it would be returning this result sorry. I'll try and dig into this when I have some time.

**Comment by terryburton** [comment]
On 22 April 2016 at 00:53, Arfon Smith <notifications@github.com> wrote:
> What are GitHub's current criteria for displaying a diff?
>
> GitHub relies upon Linguist for this.
>
> binary_mime_type? => true
>
> I think this result is coming from the mime-types gem: https://github.com/github/linguist/blob/master/github-linguist.gemspec#L18 I'm not sure why it would be returning this result sorry. I'll try and dig into this when I have some time.

Sure, and thanks for the offer to look.

Are you able to determine which properties of Linguist are currently
used in the commit view page's decision as to whether to render a
diff?

I note that Linguist's `likely_binary?` property takes the
`binary_mime_type?` result of the mime-types gem and combines it with
local information from Languages.yml and correctly decide that
non-generated PostScript is unlikely to be binary.

Perhaps the diff suppression is not using the best information available to it?

**Comment by luser-dr00g** [comment]
No info to add. But I'm having this problem, too. It is very irritating! Any other source code does fine, but not the ps: binary file not displayed. :(

**Comment by peterbillam** [comment]
Annoys me too.  Most of the files in my postscriptlib are *.ps PostScript files ...

**Comment by Alhadis** [comment]
Marginally related: I've noticed GitHub doesn't respect a `.gitattributes` file's `diff` properties. For instance, [this file](https://github.com/DanBrooker/file-icons/commit/1980febd445cf1fc5f80fb4fd0f0c5090b5a2343#diff-83059f5a665a73c8e09f88f71ad1a472R4) shows in diffs on the site, despite being [filtered](https://github.com/DanBrooker/file-icons/blob/master/.gitattributes). Currently, the attribute is only having an effect on `git diff`.

**Comment by MrB74** [comment]
Yes it would be useful to get this fixed for Scribus's users of github too

**Comment by sergey-s-betke** [comment]
up. I have the same problems: https://github.com/Metrolog/marks/commit/4c28a8e96eb249fe3ae00e2060c652f24c8ee214

**Comment by Alhadis** [comment]
@sergey-s-betke What encoding are you using? It doesn't appear to be UTF-8.

It could be that a regional character set is tricking GitHub into thinking the file is binary data, since it's failed to detect any UTF-8 sequences.

**Comment by terryburton** [comment]
On 6 Sep 2017 06:58, "John Gardner" <notifications@github.com> wrote:

@sergey-s-betke <https://github.com/sergey-s-betke> What encoding are you
using? It doesn't appear to be UTF-8.

It could be that a regional character set is tricking GitHub into thinking
the file is binary data, since it's failed to detect any UTF-8 sequences.

It happens in spite of the encoding. See the examples and analysis in the
earlier messages.

**Comment by sergey-s-betke** [comment]
@Alhadis , PostScript file **must be** in ISOLatin1 encoding. Or in any one-byte-per-char encoding. PostScript does not support Unicode! And UTF-8. I use CP1251 encoding (for Cyrillic data) and CP1253  encoding (for greek data).

**Comment by lildude** [comment]
I've looked into this and this isn't down to Linguist at all. GitHub.com explicitly marks PostScript and PDF files as binary (using a `.gitattributes` rule like `*.[Pp][Ss] -diff`) because even though they consist mostly of text, they are quite often filled with undiffable garbage (e.g., embedded images that have been encoded as alphabetic characters). This is not overrideable.

The ultimate solution would be for GitHub.com to allow users to overrule the `-diff` from their own repo's `.gitattributes` for the few situations where a user may be editing PostScript by hand and expecting to view diffs for those changes, and that change would need to take place within the main GitHub code and not Linguist.

As this is not due to Linguist's behaviour and nothing Linguist can directly influence, I'm going to close this issue. Please feel free to reach out to the GitHub support team for further assistance.

**Comment by terryburton** [comment]
> As this is not due to Linguist's behaviour and nothing Linguist can directly influence, I'm going to close this issue. Please feel free to reach out to the GitHub support team for further assistance.

@lildude Thanks for investigating. Raised with GitHub support.

**Comment by Xottab-DUTY** [comment]
> Thanks for investigating. Raised with GitHub support.

@terryburton, did you had any progress on this or some answer?

**Comment by terryburton** [comment]
> > Thanks for investigating. Raised with GitHub support.
> 
> @terryburton, did you had any progress on this or some answer?

I got a single placeholder reply from GitHub support several days after raising the support request, but nothing since:

> I can't say if/when the team can add this feature, but we really appreciate you reaching out with this request on how we can make GitHub work better for you!

I've not found a convenient way around the problem that wouldn't involve reworking the build system and tooling of my project.
