### ISSUE TITLE
Syntax highlighting bug

### ISSUE THREAD

**Issue by henrywright** [github/linguist#2965]
In one of my .scss files I have stored on GitHub, the @ symbol is being highlighted red, but I see no reason for it to be an error. See here for an example:

https://github.com/6ty8/6ty8.github.io/blob/master/_sass/_footer.scss

Is this a Linguist issue?

**Comment by pchaigno** [comment]
> Is this a Linguist issue?

No, it's not. Linguist only selects the grammar to use for highlighting. For SCSS, GitHub uses [MarioRicalde/SCSS.tmbundle](https://github.com/MarioRicalde/SCSS.tmbundle/tree/49a74571e7346b082016168fd702d41d1d319727). You should open an issue there if there isn't already one ;)

**Comment by henrywright** [comment]
Thanks @pchaigno, I've opened an issue upstream. See [#207](https://github.com/MarioRicalde/SCSS.tmbundle/issues/207).

**Comment by pchaigno** [comment]
Perfect! When the bug is fixed upstream, the dependency will be automatically updated with the next release of Linguist ;)

**Comment by arfon** [comment]
Closing as this is an upstream issue.

**Comment by aaronlademann-wf** [comment]
@arfon is there any concern that the upstream dependency being used... hasn't been updated in over 2 years?  What are the odds of the upstream dependency actually fixing it?

**Comment by pchaigno** [comment]
@aaronlademann-wf I just pinged the actual maintainer of the project (that sometimes works). If he doesn't answer in the next week, please open an issue and we'll try to find a replacement grammar.
