### ISSUE TITLE
Issue with Java source code

### ISSUE THREAD

**Issue by zg** [github/linguist#2970]
https://github.com/zg/pj2/blob/master/lib/edu/rit/util/DList.java

I don't know what's wrong here, but at line 148, the syntax highlighter breaks and everything gets painted blue past that line.

**Comment by pchaigno** [comment]
Linguist only selects the grammar to use for highlighting. For Java, GitHub uses [textmate/java.tmbundle](https://github.com/textmate/java.tmbundle/tree/64294ae0b62b64b1183c401e3803679eaddb4946). You should open an issue there if there isn't already one ;)

**Comment by zg** [comment]
Thank you.
