### ISSUE TITLE
Python is being marked as DIGITAL Command Language

### ISSUE THREAD

**Issue by EvanDarwin** [github/linguist#2974]
I think that's a bit of a stretch, this is the affected repo:

[removed]

**Comment by EvanDarwin** [comment]
I just realized that there were many extensions named ".com" in my directories, if you don't want these to be calculated, you can set:
```
*.com linguist-language=Text
```

in the `.gitattributes` file in the root of your project.

**Comment by grubern** [comment]
GitHub, in its sole discretion, has the right to suspend or terminate your account and refuse any and all current or future use of the Service, or any other GitHub service, for any reason at any time. Such termination of the Service will result in the deactivation or deletion of your Account or your access to your Account, and the forfeiture and relinquishment of all Content in your Account. GitHub reserves the right to refuse service to anyone for any reason at any time." ..............!
