### ISSUE TITLE
Terra Colour & Name

### ISSUE THREAD

**Issue by rokf** [github/linguist#2975]
Hi,

**Terra** `.t` files have the colour as **Lua** and are in some cases shown as they would be  Lua files, although Terra has its own colour in the `languages.yml` file.

The language next to the repository name is shown to be Lua for example, but in the list of languages used in a repository Terra is listed instead of Lua (correct).

How?

**Comment by pchaigno** [comment]
> The language next to the repository name is shown to be Lua for example, but in the list of languages used in a repository Terra is listed instead of Lua (correct).

The language statistics and the search results are sometimes out-of-sync.

Is it a public repository? What's the url?

**Comment by rokf** [comment]
The problem is not bound to a repository but to Terra detection in general.

Lets take the repository of Terra itself for example.

https://github.com/zdevito/terra

The coloured line (percentage of languages) is treating Terra files like Lua files.

If I go to https://github.com/zdevito/terra/search?l=terra then it is correct (Terra and Lua files separated). Also the repository view of the author for example (https://github.com/zdevito?tab=repositories), it says `Lua` next to the repository name, but actually those are mostly Terra files.

**Example number 2:**

Lets say I make an empty repository and only place one file inside. That file is a `.t` Terra file. The coloured percentage line is going to say **100% Lua** instead of **100% Terra**.

If I do the same like before and click on the **100% Lua** text, it shows that there are no Lua files and that the only file inside is of type Terra.

The language written next to the repository in the repository view is going to say Lua (wrong), should be Terra.

**Comment by pchaigno** [comment]
Okay, this is happening because [Lua is defined as the parent language of Terra](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L3603). Terra was added to Linguist in #2821 by @pyk. Although closely related, it doesn't look like Terra files should be counted as Lua. I'll open a pull request to change that ;)

**Comment by rokf** [comment]
@pchaigno Thanks a lot!

**Comment by arfon** [comment]
Fixed in #2976 - this will be live on GitHub next week sometime.
