### ISSUE TITLE
Jade is detected but listed as html anyway

### ISSUE THREAD

**Issue by zacps** [github/linguist#2977]
The github language bar shows the files as being HTML however if you click on them it will say that no files are found. Searching for jade then shows the files properly.
For example:
[Main page where language is reported as html](https://github.com/zacps/go-wiki)
[HTML search returning nothing](https://github.com/zacps/go-wiki/search?l=html )
[Jade search returning files properly.](https://github.com/zacps/go-wiki/search?l=jade )

**Comment by rokf** [comment]
That is because of `group: HTML` in the https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L1665 file. That line has to be removed for it to display correctly.

**Comment by grubern** [comment]
litcoffee,!
HTML however if you click on them it will say that no files are found. Searching for jade then shows the files properly.?

**Comment by arfon** [comment]
Closing this as we're discussing in #2978
