### ISSUE TITLE
Ability to linkify source.

### ISSUE THREAD

**Issue by jamestalmage** [github/linguist#2979]
It would be awesome to be able to linkify sources.

```js
getStream(
  stream: ReadableStream, 
  ?options: {
    maxBuffer: number = Infinity,
    encoding: string = 'utf8'
  }
);
```

Ideally, I would like `ReadableStream` to appear instead as [`ReadableStream`](https://nodejs.org/api/stream.html#stream_class_stream_readable) - with an inlined link to more information.

I think it might actually be pretty easy to do this, by allowing a special `Links` section at the bottom of any codeblock that takes standard Markdown links.

```
## Links
[ReadableStream](https://nodejs.org/api/stream.html#stream_class_stream_readable)
```

The link text (`ReadableStream`) would be the matcher used to select sections of the source to be linkified.

---

The total code block, with links would look like this:

```
```js
getStream(
  stream: ReadableStream, 
  ?options: {
    maxBuffer: number = Infinity,
    encoding: string = 'utf8'
  }
);

## Links
[ReadableStream](https://nodejs.org/api/stream.html#stream_class_stream_readable)
.```
```

I chose `## Links` as the separator because it is invalid JavaScript. There might be a better syntax for that. Maybe an additional block after the traditional closing block? 

```
```js
getStream(
  stream: ReadableStream, 
  ?options: {
    maxBuffer: number = Infinity,
    encoding: string = 'utf8'
  }
);
.```LINKS```
[ReadableStream](https://nodejs.org/api/stream.html#stream_class_stream_readable)
.```
```
---
Note that I am using a `.` character to get the closing tags to render above.

**Comment by arfon** [comment]
Hi @jamestalmage - this is an interesting suggestion for sure. I'm pretty sure this isn't a Linguist thing though. Would you mind posting this over in https://github.com/github/markup ?

**Comment by jamestalmage** [comment]
I reposted this as https://github.com/github/markup/issues/888.

I don't know enough of the internals to say which project it belongs too (I would have assumed work was required from both projects).

**Comment by arfon** [comment]
> I don't know enough of the internals to say which project it belongs too (I would have assumed work was required from both projects).

Thanks @jamestalmage. This is primarily a github/markup thing so going to close here.
