### ISSUE TITLE
Added .gitattributes, still wrong language

### ISSUE THREAD

**Issue by paradiselost79** [github/linguist#2989]
I added a .gitattributes file, still marking repository as HTML though it is Java
https://github.com/paradiselost79/Pokemonish

On .gitattributes I put:
$ cat .gitattributes
*.rb linguist-language=Java
*.rb linguist-vendored=Java

Is this correct?

**Comment by arfon** [comment]
@paradiselost79 - you're getting lots of HTML reported because of these files: https://github.com/paradiselost79/Pokemonish/search?l=html

You can remove these from your stats by putting the following in your `.gitattributes` file:

```
jc_ansiterm_0.1/* linguist-vendored=true
```

**Comment by paradiselost79** [comment]
Awesome, fixed it. Thanks (and I need to get rid of that library anyways)
