### ISSUE TITLE
No Language Identified for Java Repository

### ISSUE THREAD

**Issue by mattusifer** [github/linguist#3000]
This repository:
https://github.com/mattusifer/imdb-sentiment-classifier

The repo was very large before the last commit, containing over 100,000 text files, so I had assumed that linguist wasn't able to scan the entire repo to determine the language. 

Since I removed those text files yesterday afternoon it still hasn't picked up the language from the now relatively small repo.

**Comment by pchaigno** [comment]
I think it has not been updated yet, because if I run it against Linguist locally, I get:
```
97.16%  Java
2.84%   Shell
```

**Comment by mattusifer** [comment]
I see, thanks for the input. How long does it normally take to update?

**Comment by pchaigno** [comment]
It's usually gets updated when you push to the repository. Maybe @arfon could help?

**Comment by Alhadis** [comment]
[I recall this happening too](https://github.com/Alhadis/Linguist-Heuristics/commit/240d65951f90253af73f7bbb8c17e7a313819d09). Perhaps there's a filesize limit capping it?

**Comment by larsbrinkhoff** [comment]
Yes, there's a file size limit.

**Comment by Alhadis** [comment]
![I knew it.](https://cloud.githubusercontent.com/assets/2346707/15172793/8212c826-179b-11e6-8ab8-939e9f29fd1d.jpg)

**Comment by larsbrinkhoff** [comment]
E.g. https://github.com/larsbrinkhoff/test has two `.f` files.  
But https://github.com/larsbrinkhoff/test/search?l=forth only finds one.

**Comment by mattusifer** [comment]
The language is still detected in the in the https://github.com/larsbrinkhoff/test repository despite the file size being capped. Would this type of issue really prevent my repo from being fully scanned by linguist?

Besides, I don't think we have any huge files in that repo.

**Comment by larsbrinkhoff** [comment]
@mattusifer Right, but supposedly it wouldn't be detected if the smaller `foo.f` file weren't there.

I'm not sure if this is the exact same failure mode as for your repository.  Just adding another data point.

**Comment by pchaigno** [comment]
@arfon Could you trigger an update of statistics for this repository: https://github.com/mattusifer/imdb-sentiment-classifier?

**Comment by arfon** [comment]
> @arfon Could you trigger an update of statistics for this repository: https://github.com/mattusifer/imdb-sentiment-classifier?

This is actually a caching bug on GitHub. I've pinged the appropriate team internally for a fix.

**Comment by mattusifer** [comment]
Thanks @arfon !

**Comment by mattusifer** [comment]
This repository looks good - all set to close this out on my end. Thanks for everyone's help!

**Comment by georgy7** [comment]
The same issue.
https://github.com/georgy7/simpler-cache-api

Tiny repository, only 2 java-files. A few lines of code, many comments.

**Comment by lildude** [comment]
@georgy7 your issue is caused by the fact the path to your Java files includes `cache` and is thus being treated by Linguist as vendored code (see https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml#L12-L13) and thus ignored when determining the language stats of a repo.

You'll need to implement a manual override like detailed at https://github.com/github/linguist#vendored-code

**Comment by georgy7** [comment]
@lildude Thanks, this helped.
