### ISSUE TITLE
Javascript syntax highlighting bug

### ISSUE THREAD

**Issue by doughsay** [github/linguist#3003]
One of my js files is not highlighting correctly, even though Lightshow renders is correctly.

Lightshow url: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=source.js&grammar_url=&grammar_text=&code_source=from-text&code_url=&code=test%28%27deserialize+a+function%27%2C+t+%3D%3E+%7B%0D%0A++const+value+%3D+%7B+function%3A+true%2C+source%3A+%27function+foo%28%29+%7B+return+%22foo%22%3B+%7D%27+%7D%3B%0D%0A++const+fn+%3D+deserializer.deserialize%28value%29%3B%0D%0A++t.equal%28typeof+fn%2C+%27function%27%29%3B%0D%0A++t.equal%28fn.function%2C+true%29%3B%0D%0A++t.equal%28fn.source%2C+%27function+foo%28%29+%7B+return+%22foo%22%3B+%7D%27%29%3B%0D%0A++t.end%28%29%3B%0D%0A%7D%29%3B

Screenshot from github: 
<img width="651" alt="screen shot 2016-05-14 at 3 06 36 pm" src="https://cloud.githubusercontent.com/assets/221693/15270913/a632c250-19e5-11e6-8193-6d47203bfa3f.png">

And heres the link to the relevant lines: https://github.com/doughsay/room.js/blob/08467b23b6f03076242fcd1117d3eff833b06697/test/lib/deserialize-test.js#L140

**Comment by Alhadis** [comment]
This is an issue with the [grammar file being used for highlighting](https://github.com/atom/language-javascript): you should file an issue there.

The discrepancy is strange, but I believe Lightshow's current rendering engine isn't a perfect replica of GitHub's - some of its underlying dependencies may be outdated or using a different highlighting engine.

**Comment by doughsay** [comment]
I'll open an issue where you suggest, but the syntax highlighting IS working correctly in atom.  Also, I realized it's the incorrect highlighting of the key called "function" that's actually breaking things...
