### ISSUE TITLE
Grails 3 projects being identified as CSS

### ISSUE THREAD

**Issue by jackreyneke** [github/linguist#3006]
Hi guys,

We have a couple of Grails projects. All these projects are identified as CSS. They should be Groovy.

Cheers,
Jack

**Comment by pchaigno** [comment]
Are these private repositories or could you post links to them?

**Comment by jackreyneke** [comment]
Hi, unfortunately they are private repositories.


-------- Original message --------

**Comment by pchaigno** [comment]
Statistics depend on the size of files for each language. So you probably have many CSS files (or a few big ones) causing your repository to be identified as a CSS repository. See [Linguist overrides](https://github.com/github/linguist#overrides) to ignore CSS files in statistics.

**Comment by jackreyneke** [comment]
Thanks,

Out of interest, I did a quick search and it appears that Grails projects are commonly mistaken as CSS projects:
https://github.com/search?l=CSS&q=grails&ref=searchresults&type=Repositories&utf8=%E2%9C%93

Kind regards,
Jack

**Comment by Alhadis** [comment]
That'd probably be the [Bloatstrap CSS†](https://github.com/groovydev/twitter-bootstrap-grails-plugin/search?l=css) that's included with such projects.

@pchaigno Sound like an addition to [`linguist/vendor.yml`](https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml) to you?

<small>**†** - God, I love to hate Bootstrap...</small>

**Comment by pchaigno** [comment]
> @pchaigno Sound like an addition to linguist/vendor.yml to you?

Sure.

**Comment by Alhadis** [comment]
I'll take care of it. Anything to kick Bootstrap in the nuts.

**Comment by pchaigno** [comment]
:smile:

**Comment by jackreyneke** [comment]
Thanks for the quick response guys. Cheers

**Comment by Alhadis** [comment]
@jackreyneke When you first set up a Grails project, what's the directory structure? Are there auto-generated CSS files?

I'm noticing an abundance of `web-app/css/*.css` files named `errors.css`, `main.css` and `mobile.css`... most of it looks like boilerplate code, but I want to be certain before marking it as vendored.

**Comment by Alhadis** [comment]
@jackreyneke Just an FYI, I can't progress until you give me a definitive answer. ;)

**Comment by Alhadis** [comment]
@jackreyneke Paging you again as a reminder that I kinda need your help with this. I don't know anything about Grails.

@pchaigno Do you?

**Comment by Alhadis** [comment]
Okay, paging @jackreyneke hasn't worked and he isn't responding to e-mails. I'm officially declaring this issue a state of [i]"somebody else can take care of it if they want"[/i] because I'm not going to spend time learning Grails to answer my own question.

**Comment by jackreyneke** [comment]
@alhadis I do apologise, your Git notifications ended in a black hole somewhere.

To answer the question, yes the CSS files were all auto-generated on when creating the project. If you want I can create a blank project in a public repo when I'm back at my desk.

**Comment by Alhadis** [comment]
Please do.

If there are multiple project templates, each with varying sets of boilerplate files, then please create a copy of each one too. I'd like to be exhaustive in coverage.
