### ISSUE TITLE
Support for MQL4 & MQL5 syntax.

### ISSUE THREAD

**Issue by kenorb** [github/linguist#3012]
I'm requesting support for MQL4 & MQL5 programming language syntax.

These programming languages are different from C, so implementing #932 won't help.

The documentation can be found in here:

- https://docs.mql4.com/
- https://www.mql5.com/en/docs

I'm mainly interested in ability to filter files by their extensions while [searching files](https://github.com/search?p=3&q=MODE_FREEZELEVEL&type=Code&utf8=%E2%9C%93) on GitHub, but currently these languages doesn't appear in facets.

So I'm expecting to see MQL4 and MQL5 at the left side bar (_Languages_).

**Comment by pchaigno** [comment]
@kenorb Please see the [guidelines to add support for a new language to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). If MQL4 and MQL5 meet the requirement on in-the-wild usage, don't hesitate to open a pull request.

**Comment by kenorb** [comment]
Fixed in #3295
