### ISSUE TITLE
fastcgi++ being identified as C instead of C++

### ISSUE THREAD

**Issue by eddic** [github/linguist#3013]
I've recently started rewriting fastcgi++ and it has suddenly started being classified as C instead of C++. If ones searches for fastcgipp on GitHub one sees all the forks that are still listed as C++ but for some reason the new version is listed as C.

https://github.com/eddic/fastcgipp

**Comment by pchaigno** [comment]
This is happening because of [these few large files](https://github.com/eddic/fastcgipp/search?l=c). You can fix that using [Linguist overrides](https://github.com/github/linguist#overrides).

**Comment by eddic** [comment]
Bingo. Thanks.
