### ISSUE TITLE
Add language PowerBuilder

### ISSUE THREAD

**Issue by LucasKrahl23** [github/linguist#3014]
Hi guys,

We have a couple of PowerBuilder projects. And don't have that language in this project. We would like to contribute by providing this change.

Thanks, Lucas.

**Comment by pchaigno** [comment]
Hi @LucasKrahl23!
Please take a look at the [requirements (and steps involved) to add support for a language](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) to Linguist. If the language meets the requirements, a pull request would definitively be welcome!

**Comment by sahildua2305** [comment]
@arfon @pchaigno Is it confirmed that PowerBuilder can be added or do I need to check it that meets the requirements or not?

**Comment by arfon** [comment]
> @arfon @pchaigno Is it confirmed that PowerBuilder can be added or do I need to check if that meets the requirements or not?

It is not. Assessing whether PowerBuilder meets the requirements outlined [here](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) is probably the next step.

**Comment by sahildua2305** [comment]
@arfon I have found that PowerBuilder (PB) is an Object Oriented, Event Driven environment that used its own language, called PowerScript.
The possible file extensions can be PBL, PDB, PBW, PBT, SRD, SRW, SRM, SRU, SRS, SRP, SRF, SRQ, SRA and SRJ.

While searching for [`powerscript`](https://github.com/search?utf8=%E2%9C%93&q=powerscript&type=Code&ref=searchresults) gives a lot of results which contain files with these extensions, searching for these extensions separately doesn't generate any results.

**Comment by nixel2007** [comment]
@sahildua2305 
> searching for these extensions separately doesn't generate any results.

you need to search any key. common practice is search by `NOT nothack extension:your_extension` query

**Comment by sahildua2305** [comment]
Thanks @nixel2007 

@arfon I have found these results:
- PBL (Library files) [3,100 results](https://github.com/search?utf8=%E2%9C%93&q=NOT+nothack+extension%3Apbl&type=Code&ref=searchresults)
- PDB (Dynamic link library files) [2,359,000 results](https://github.com/search?utf8=%E2%9C%93&q=NOT+nothack+extension%3Apdb&type=Code&ref=searchresults)
- PBW (Workspace files) [1,400 results](https://github.com/search?utf8=%E2%9C%93&q=NOT+nothack+extension%3Apbw&type=Code&ref=searchresults)
- PBT (Target files) [576 results](https://github.com/search?utf8=%E2%9C%93&q=NOT+nothack+extension%3Apbt&type=Code&ref=searchresults)
- SRD (DataWindow source files) [4,000 results](https://github.com/search?utf8=%E2%9C%93&q=NOT+nothack+extension%3Asrd&type=Code&ref=searchresults)
- SRW (Window source files) [1,500 results](https://github.com/search?utf8=%E2%9C%93&q=NOT+nothack+extension%3Asrw&type=Code&ref=searchresults)
- SRM (Menu source files) [1,500 results](https://github.com/search?utf8=%E2%9C%93&q=NOT+nothack+extension%3Asrm&type=Code&ref=searchresults)
- SRU (Custom user object source files) [2,460 results](https://github.com/search?utf8=%E2%9C%93&q=NOT+nothack+extension%3Asru&type=Code&ref=searchresults)
- SRS (Structure source files) [1,000 results](https://github.com/search?utf8=%E2%9C%93&q=NOT+nothack+extension%3Asrs&type=Code&ref=searchresults)
- SRP (Data pipeline source files) [6,500 results](https://github.com/search?utf8=%E2%9C%93&q=NOT+nothack+extension%3Asrp&type=Code&ref=searchresults)
- SRF (Function source files) [4,000 results](https://github.com/search?utf8=%E2%9C%93&q=NOT+nothack+extension%3Asrf&type=Code&ref=searchresults)
- SRA (Application files) [663 results](https://github.com/search?utf8=%E2%9C%93&q=NOT+nothack+extension%3Asra&type=Code&ref=searchresults)
- SRJ (Project files) [1,200 results](https://github.com/search?utf8=%E2%9C%93&q=NOT+nothack+extension%3Asrj&type=Code&ref=searchresults)

Cumulative results for all these extensions - [2,387,000 results](https://github.com/search?utf8=%E2%9C%93&q=NOT+nothack+extension%3Apbl+extension%3Apdb+extension%3Apbw+extension%3Apbt+extension%3Asrd+extension%3Asrw+extension%3Asrm+extension%3Asru+extension%3Asrs+extension%3Asrp+extension%3Asrf+extension%3Asra+extension%3Asrj&type=Code&ref=searchresults)

**Comment by nixel2007** [comment]
Are all of this extensions text-based? dll (PDB) used to be binary

**Comment by sahildua2305** [comment]
@nixel2007 PBL, PBT, SRW, SRU, SRP, SRA and SRJ extensions are mostly text-based.

PBW, SRD, SRM, SRS and SRF are sometimes text-based. :confused:

**Comment by larsbrinkhoff** [comment]
Also, `.pdb` isn't exactly PowerBuilder, it is?

https://msdn.microsoft.com/en-us/library/yd4f8bd1%28vs.71%29.aspx

**Comment by sahildua2305** [comment]
@larsbrinkhoff No, it isn't. That was the exhaustive list of extensions in PowerBuilder projects.
It's a general DLL binary file extension. :)

**Comment by larsbrinkhoff** [comment]
Sorry, I edited my reply above.

**Comment by sahildua2305** [comment]
@larsbrinkhoff Check my edited comment.

**Comment by arfon** [comment]
OK thanks @sahildua2305.

> @nixel2007 PBL, PBT, SRW, SRU, SRP, SRA and SRJ extensions are mostly text-based.

I would suggest that we move this to a pull request at this stage implementing these extension. Many of the others I checked were binary which means we're [never going to try and detect the language](https://github.com/github/linguist/blob/master/lib/linguist.rb#L20) even if we define the extension.

**Comment by sahildua2305** [comment]
Awesome @arfon ! I will submit a PR today itself.

**Comment by sahildua2305** [comment]
@arfon Let's close this issue? :smile:

**Comment by sahildua2305** [comment]
@arfon @pchaigno Can you please assign me some "low" or "medium" effort task? I'd love to keep contributing.
