### ISSUE TITLE
Repo type classified as eagle, should be C

### ISSUE THREAD

**Issue by Wolfman-F16** [github/linguist#3016]
The filesize is given too much weight in determining the repo type. there are only 4 eagle files, but those have a bigger total file size than the 30 plus C files.
The repo is 
https://github.com/Wolfman-F16/uhf-radio

Thanks.

**Comment by pchaigno** [comment]
> The filesize is given too much weight in determining the repo type.

We discussed this issue in #2139. There isn't really one solution that stand out :/

> there are only 4 eagle files, but those have a bigger total file size than the 30 plus C files.

You can fix that locally with [Linguist overrides](https://github.com/github/linguist/blob/master/CONTRIBUTING.md).

**Comment by arfon** [comment]
> You can fix that locally with Linguist overrides.

👍
