### ISSUE TITLE
Scheme misclassified as E

### ISSUE THREAD

**Issue by Jonathan50** [github/linguist#3018]
After putting

``` scheme
;;; -*- geiser-scheme-implementation: guile -*-
```

at the top of my file it is now being detected as "E".
The repository is https://github.com/Jonathan50/scheme-hashtable

**Comment by pchaigno** [comment]
This is an issue with the [regular expression for Emacs modeline](https://github.com/github/linguist/blob/8b0b14c9a6d2128c3c7000aea7bb0709d1e1e6ea/lib/linguist/strategy/modeline.rb#L4).
@tesch1 introduced it in #2233. We could probably simplify it...

**Comment by tesch1** [comment]
Hm, I *think* the expression was matching an empty string.  I think the best solution is to separate out the two types of lines, the plain -*- MODE -*- and the -*- local-file-variables:val; mode:MODE; more-local-file-variables -*- like has been done for the different VI types of lines.  Potential fix in that branch above.. it's not passing travisci build though, I dont have any more time to figure out why at the moment, sorry!  will have a look again when I have a moment!

**Comment by pchaigno** [comment]
@tesch1 Did you get a chance to look into this since last time?

**Comment by Alhadis** [comment]
Heh. That reminds me, I rewrote the Emacs modeline-matching pattern too, because it was also matching stuff incorrectly:

```
-\*-
(?:
	(?:
		(?!mode\s*:)
		[^:;]+ :
		[^:;]+ ;
	)*
	
	\s* mode \s* :
)?
\s*
(MODE_NAME_HERE)
\s*
(?:
	; [^:;]+
	: [^:;]+?
)*
;?
\s*
-\*-
```

```js
/-\*-(?:(?:(?!mode\s*:)[^:;]+:[^:;]+;)*\s*mode\s*:)?\s*(MODE_NAME_HERE)\s*(?:;[^:;]+:[^:;]+?)*;?\s*-\*-/i.test(";;; -*- geiser-scheme-implementation: guile -*-")
// -> false
```

Should I, uh, submit a different pull request, or add to my existing one...?

**Comment by pchaigno** [comment]
I guess adding to the existing one is okay :+1: 
We'll also need tests and comments :stuck_out_tongue_closed_eyes:

**Comment by Alhadis** [comment]
Tests I can grab from my [Perl pull-request](https://github.com/atom/language-perl/pull/76) ("Perl Request"? LEL?). Comments will need to be added, but I'll need your <i>Parfait</i> of approval again. ;)

**Comment by tesch1** [comment]
@Alhadis your regex will incorrectly match something like: -*- perl; foo:bar-*-
pretty sure 0cfe7bb is ok, i just dont have time to dig further into why the test failed:
https://travis-ci.org/tesch1/linguist/jobs/133623442

**Comment by Alhadis** [comment]
:| Actually, I did that on purpose under the assumption that *was* legal syntax. Just tested `-*- perl; -*-` in Emacs now, and it's choking on the semicolon. The more you know.

Okay, definitely gonna fix. Glad you picked that up (I haven't been using Emacs for too long, I'm afraid)

**Comment by tesch1** [comment]
yeah, I went through the same pain of actually trying out all the edge-cases (well, as many as I reasonably could).  That's why I ended up with two expressions, it's just nasty to get it all in one.  Also, my lisp symbol recognition probably isnt totally right either (if the var names are even symbols, which looks to be not-quite the case) : https://www.gnu.org/software/emacs/manual/html_node/elisp/Symbol-Type.html#Symbol-Type

**Comment by Alhadis** [comment]
`(?![-+\d])([-+=*/\w~!@$%^&:<>{}?]+))`

That's the pattern I used when I [wrote this](https://github.com/Alhadis/language-emacs-lisp). Which, mind you, was authored *after* I penned the modeline expression, which... in hindsight, should've been revisited after learning Emacs Lisp. xD

Still, it never would've occurred to me that the short form was illegal when paired with anything else, given the long hairy crap I was using to test it with... :\

**Comment by tesch1** [comment]
ooh, nice :) I may have to try this newfangled atom thing.

it's the `:` that bugs me

**Comment by Alhadis** [comment]
> it's the `:` that bugs me

Well it's valid as a symbol character, and Emacs isn't complaining when I feed it this:

```
-*- var: na:me; mode: perl -*-
```

(Apart from the usual *"The local variables list contains values that may not be safe"* warning, I mean)

**Comment by Alhadis** [comment]
@pchaigno Don't wait for me to amend to my existing PR, I'll do so in another. I want to research Emacs modelines *properly*, to the same extent as Vim's.

**Comment by tesch1** [comment]
ah, interesting, this: `na:me:na:me;`
breaks down to this: `na` = `me:na:me`

**Comment by Alhadis** [comment]
WHOO, WE'RE ALL LEARNING SOMETHING TODAY

I FEEL SLIGHTLY LESS EMBARRASSED :D

(I shouldn't be allowed to use the Internet after a certain blood-caffeine level..)

**Comment by tesch1** [comment]
now i can die happy

**Comment by larsbrinkhoff** [comment]
An Emacs Lisp symbol can have any arbitrary string as its name.  See e.g. `make-symbol`.

But of course, you want to know which characters are allowed unquoted in the print syntax.  A cursory search didn't reveal the exact syntax, so I turned to the source code:

Supposedly, this little neat expression defines the legal characters:

    (c > 040
     && c != NO_BREAK_SPACE
     && (c >= 0200
         || strchr ("\"';()[]#`,", c) == NULL))

If I parse this correctly, this rules out control characters, space, "no break space" (probably a Unicode thing), and the set `"';()[]#`.  So `:` is perfectly fine.  Indeed symbols that begin with colon are common; they are treated as constants that evaluate to themselves.

**Comment by larsbrinkhoff** [comment]
Oh, found it:  
https://www.gnu.org/software/emacs/manual/html_node/elisp/Symbol-Type.html#Symbol-Type

**Comment by Alhadis** [comment]
Yup, @tesch1 already quoted it above, and I used the link when writing the [pattern-matching](https://github.com/Alhadis/language-emacs-lisp/blob/master/grammars/emacs-lisp.cson#L75) rules for the Emacs Lisp grammar. =)

**Comment by tesch1** [comment]
the issue here is that the regex/algorithm that emacs is using to pull out
the file-local variables is what we should approximate, and it's different
from the lisp interpreter's symbol recognition.  we seem to be pretty
close, the only better thing would be for someone to dig around in emacs
code for the function that loads file-local vars

**Comment by larsbrinkhoff** [comment]
The function that handles the mode line is called `set-auto-mode`:

https://github.com/emacs-mirror/emacs/blob/ec12c6705f91106c4f4c53e76447dafa21e12f9f/lisp/files.el#L2790-L3006

**Comment by Alhadis** [comment]
Interesting. Seems like [there're other](https://github.com/emacs-mirror/emacs/blob/ec12c6705f91106c4f4c53e76447dafa21e12f9f/lisp/files.el#L2529) config filenames for Emacs Lisp I didn't know about.

* [`.gnus`](https://github.com/search?q=filename%3A.gnus+NOT+nothack&type=Code) (23,212 results)
* [`.viper`](https://github.com/search?q=filename%3A.viper+NOT+nothack&type=Code) (92,058 results)
* [`Project.ede`](https://github.com/search?utf8=%E2%9C%93&q=filename%3AProject.ede+NOT+nothack&type=Code&ref=searchresults) (15,983 results)

Well... you know what this means...

**Comment by larsbrinkhoff** [comment]
Sure, I have a `.gnus` myself.  If you're making a new PR, can you check the `.eld` extension as well?

**Comment by Alhadis** [comment]
Will do. Never heard of the `.eld` extension, that's `gnus` to me...

(I got the pun when I noticed `.gnus` is a [newsreader](http://www.gnus.org/)...)

Stallman, you've done it again...

<img src="https://cloud.githubusercontent.com/assets/2346707/18505516/f6df1e12-7aaa-11e6-8364-806b36dbe5c7.jpg" width="500" />

**Comment by Alhadis** [comment]
Great... seems like even malformed modelines can trigger a language-change if the major mode's component is decipherable.

For example, this will set an opened file's mode to Ruby, AND display a warning about a malformed modeline:

```
# -*- foo-bar mode: ruby; -*-
```

Should we cater for this in our implementation? Gut feeling says "yes", since authors mightn't actually care if a modeline is malformed, as long as it's showing the right language.

**Comment by tesch1** [comment]
I'd do what emacs does
![stallman_pointing](https://cloud.githubusercontent.com/assets/322607/18590068/b7aa3ca2-7c2d-11e6-8fde-5c26ba263a04.jpeg)

**Comment by Alhadis** [comment]
... of course, the *end* of the modeline has to be well-formed if it's adjacent to the mode name, meaning this will be ignored altogether:

```
-*- mode: ruby--*-
```

Yet these are fine:
```
-*- mode: ruby;;;;;;;;;;;;;;;;-*-
-*- mode: ruby a-------*-
```
<img src="http://i1.kym-cdn.com/photos/images/original/001/100/634/ded.jpg" width="500" />

**Comment by Alhadis** [comment]
Right. Sorted. Hell, it's even shorter than the original expression.

```
-\*-
(?:
	\s*
	(?= [^:;\s]+ \s* -\*-)
	|
	(?:
		.*?[;\s]
		|
		(?<=-\*-)
	)
	mode\s*:\s*
)
([^:;\s]+)

(?=
	[\s;] | (?<![-*]) -\*-
)
.*?
-\*-
```

Time to annotate it and gift-wrap a pull request.

**Comment by tesch1** [comment]
nice work!  now you may bask.

![richard_stallman_01](https://cloud.githubusercontent.com/assets/322607/18607102/2cd5513e-7cc3-11e6-9eca-fd478038b859.jpg)

**Comment by Alhadis** [comment]
Oh man, I fell asleep this morning (~5-6am) trying to reinstall submodules, thinking I botched something when switching/merging branches (since tests were failing, when it was actually to do with a Licensee problem).

Sorry about that... I'm preparing a new PR now. :)

**Comment by tesch1** [comment]
apropos this whole issue ... http://regex.info/blog/2006-09-15/247  way to call it, jzw

**Comment by github3519305** [comment]
为什么没有中国人

**Comment by pchaigno** [comment]
@Alhadis Is this fixed with the new regular expression?

**Comment by Alhadis** [comment]
Good grief, no idea why this is still sitting open.

You bet it's been fixed.

**Comment by Jonathan50** [comment]
I still have this issue.

**Comment by lildude** [comment]
@Jonathan50 you will do as you've not touched the repo since the fix was released. Language statistics are only updated, via a background job, when a push is made. We don't go back and refresh all repos as this would be insanely resource intensive and would take a really long time. 

If you push a change to the repo you should find it'll update to the correct language.

**Comment by Jonathan50** [comment]
Oh. Thanks.
