### ISSUE TITLE
Repository type is classified as Javascript , where should be C#

### ISSUE THREAD

**Issue by hem-kant** [github/linguist#3023]
There is no JavaScript file in the repository but still it has been classified as Javascript , where should be C# [Link Repo](https://github.com/hem-kant/Mi4T/)

**Comment by Alhadis** [comment]
There are JavaScript files - [see here](https://github.com/hem-kant/Mi4T/search?l=javascript).

If these are vendored scripts (included or generated by another program), you can exclude them from your repository's language stats by marking the path/s as vendored in a `.gitattributes` file:
```
Mi4T/MongoDBIntegration4Tridion/MongoDBIndexService/scripts/* linguist-vendored
```
See [this](https://github.com/github/linguist#using-gitattributes) for more information.

**Comment by hem-kant** [comment]
I have updated the all the script path as linguist-vendored in  .gitattributes file but the repository is still showing  as Javascript

**Comment by Alhadis** [comment]
Ah! Erh, sorry, the `Mi4T/` wasn't supposed to be included in the pathnames. So it should just be this:

```
MongoDBIntegration4Tridion/MongoDBIndexService/scripts/* linguist-vendored
MongoDBIntegration4Tridion/MongoDBIndexService/obj/Release/Package/PackageTmp/scripts/* linguist-vendored
MongoDBIntegration4Tridion/packages/Microsoft.ApplicationInsights.JavaScript.0.15.0-build58334/content/scripts/* linguist-vendored
```

**Comment by hem-kant** [comment]
Thanks
