### ISSUE TITLE
Linguist not working as expected, Override not working at all

### ISSUE THREAD

**Issue by LukaszDev** [github/linguist#3025]
Hi,

**Can someone explain to me what I'm thinking or doing wrong and how to fix statistic for my repo, please ?**

Documentation from [Linguist Repo](https://github.com/github/linguist#linguist) is not clear for me.

As far I understand files (and paths)  included in [paths for vendored code](https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml) should be excluded from statistic, yes ? For example, bootstrap should be not counted in statistic by default ?

So - in my case - bootstrap is counted in language statistic...

I have tried fix it by [overrides](https://github.com/github/linguist#overrides) feature, but still doesn't work for me.

It's my `.gitattributes` [gitattributes.txt](https://github.com/github/linguist/files/289592/gitattributes.txt)
```
# Linguist
lib/* linguist-vendored
```

and printscreen form my repo:
![languages](https://cloud.githubusercontent.com/assets/17419186/15650477/bef3a286-2670-11e6-9002-c82324f966ac.png)

![linguist](https://cloud.githubusercontent.com/assets/17419186/15650384/138e30dc-2670-11e6-9ca7-78bcf8a49641.png)

Thanks in advance :)

BTW. It should be C# / HTML Repo, not JavaScript ;)

**Comment by Alhadis** [comment]
Vendored paths are still listed in search results, even though they don't affect the repository's language statistics.

Now, since your repository is private, I'm unable to give any meaningful insight as to what might be going on. Have you checked that the vendored paths are correct? They follow the same file-globbing format used by `.gitignore`.

**Comment by LukaszDev** [comment]
> Vendored paths are still listed in search results, even though they don't affect the repository's language statistics.

Ok, listing vendored path in search result it's ok - but still looks that my language statistic are affected by 3rd-part libs...
![languages](https://cloud.githubusercontent.com/assets/17419186/15650839/54f510f6-2673-11e6-87c5-81742bbb6754.png)

In my case JavaScript is not primary language and should be no more then 5-10% JS (excluding libs).
 
<br>
> Have you checked that the vendored paths are correct? They follow the same file-globbing format used by  .gitignore

I have tried both `lib/*` and `lib/` - the first came from [Linguist Docs](https://github.com/github/linguist#using-gitattributes), and the second working for me in `.gitignore`, but none of them works in `gitattributes`.

<br>
> Now, since your repository is private, I'm unable to give any meaningful insight as to what might be going on. 

If you would be so kind, I am willing to give you access to repo...

**Comment by Alhadis** [comment]
> If you would be so kind, I am willing to give you access to repo...

I'd be happy to have a look for you, if that's the easiest option. =)

**Comment by Alhadis** [comment]
Okay, here's your problem:
```
# Linguist
lib/ linguist-vendored
```

Paths are matched relative to the file's location, so `lib/` would only match a folder named `lib` that's sitting in the root directory. You'll want to change that to this:

```
Performance/wwwroot/lib/* linguist-vendored
```

**Comment by Alhadis** [comment]
@LukaszDev I see this has fixed your problem. =) Don't forget to remove me from your repo and mark this issue as solved. ;)

**Comment by LukaszDev** [comment]
You are a star - finally works as expected :) Thank you.

BTW. In my case line/path `lib/` in `.gitignore` works well - so this is reason why I expect that path will work in `.gitattributes`.
<br>
> Paths are matched relative to the `.gitattribute`

It's should be clearly mentioned in docs, because it's not obviously and is not the same rule like as for `.gitignore`!
