### ISSUE TITLE
Improve JSON syntax highlighting

### ISSUE THREAD

**Issue by P233** [github/linguist#3026]
Hi

Currently Github doesn't highlight JSON name and value separately which is not very convenient when we are looking for something through a large JSON file. So I create a simple JSON highlighting package to improve this.

Please see the following two examples: 

[Highlight JSON example](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2FP233%2Flinguist-JSON%2Fmaster%2FJSON.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2FP233%2Flinguist-JSON%2Fmaster%2Ftest.json&code=)

[Highlight the npm package.json](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2FP233%2Flinguist-JSON%2Fmaster%2FJSON.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fnpm%2Fnpm%2Fmaster%2Fpackage.json&code=)

The repo address is https://github.com/P233/linguist-JSON

Can you please consider to use this package or to improve the current one? Thanks!

**Comment by Alhadis** [comment]
What's stopping you from submitting a pull request to [the appropriate repository](https://github.com/textmate/json.tmbundle)?

**Comment by P233** [comment]
@Alhadis I highight the syntax in a different way and I don't want to change too many things in that package. And I am not a user of TextMate or Sublime Text anymore, this package is bulid for linguist only which makes it easy to maintain.

**Comment by Alhadis** [comment]
Personally, I feel the site should be displaying JSON data as an interactive tree, similar to the output of `console.dir` in Chrome's developer tools. An option to view the highlighted syntax could always be provided.

Anyway, regarding your proposed suggestion, I don't think it's going to get very far. The site's colour choices aren't set in stone, and the palette used for syntax highlighting may very well change in future. The change is also a very arbitrary and opinionated one - not every user finds reading the different colours difficult.

I'm not staff, so don't take my words as an official ruling.

**Comment by pchaigno** [comment]
> Currently Github doesn't highlight JSON name and value separately which is not very convenient when we are looking for something through a large JSON file.

@P233 Looks like this behavior was changed in the grammar upstream. If I'm mistaken, please open an issue at [textmate/json.tmbundle](https://github.com/textmate/json.tmbundle) to discuss it.
