### ISSUE TITLE
CSS Custom properties

### ISSUE THREAD

**Issue by kevinSuttle** [github/linguist#3042]
The syntax is nearly finalized, but in the meantime I'll document here:

<img width="661" alt="screen shot 2016-06-06 at 2 13 48 pm" src="https://cloud.githubusercontent.com/assets/95672/15832625/0565b774-2bf1-11e6-9e38-d7250185bebe.png">

Notice the `H` and the `C`.

```css
/* Theme.css */
:root {
  --HighlightColor: #3acfb6;
}
```

**Comment by Alhadis** [comment]
This is an issue with the [grammar being used](https://github.com/textmate/css.tmbundle) to provide syntax highlighting for CSS on GitHub. You should file an issue there.

**Comment by kevinSuttle** [comment]
Good to know. Thanks!
