### ISSUE TITLE
Unknown files classified as R and impossible to see why

### ISSUE THREAD

**Issue by dagwieers** [github/linguist#3043]
In the https://github.com/Fedict/eid-mw project 3.2% of our files are identified as R, however we don't have any R files. Now the real issue is that if you click on the "language bar" on the R-link, you don't get any files, so it is unclear why linguist is identifying R files and how to resolve the problem.

**Comment by pchaigno** [comment]
This is happening because of [the `sla.r` file](https://github.com/Fedict/eid-mw/tree/master/installers/quickinstaller/mac/DMG) which Linguist recognizes as R. Please see [Linguist overrides](https://github.com/github/linguist#overrides) to solve that issue.

**Comment by dagwieers** [comment]
The issue we are reporting is the fact that you get an error when clicking on the link to see what files are reported for R. Not the fact that they were incorrectly classified (ok, acoording to the title is was the combination ;-)).

**Comment by pchaigno** [comment]
@arfon might be able to manually fix that issue.

**Comment by arfon** [comment]
@dagwieers - yes it's definitely `installers/quickinstaller/mac/DMG/sla.r` that's beeing classified as `R`. As to why this isn't listed in the UI when you click the language name I'm not sure. Would you mind filing a bug with GitHub support about this as I think this is a GitHub bug? The email is `support@github.com`
