### ISSUE TITLE
Policy for lock files including npm-shrinkwrap.json

### ISSUE THREAD

**Issue by Limess** [github/linguist#3045]
Hello,

I was wondering what the perceived policy is for generated `npm-shrinkwrap.json` files. These files, although clearly useful, clog up diffs and github statistics.

The php composer lock file seems to be ignored in https://github.com/github/linguist/blob/baf56666d40fda769b2c1bfacdcc03208a4f72da/lib/linguist/generated.rb, however neither `npm-shrinkwrap.json` nor `Gemfile.lock` dependency locks are so it seems there isn't a set policy.

**Comment by arfon** [comment]
@Limess - looks like there are [lots of these files](https://github.com/search?utf8=%E2%9C%93&q=npm-shrinkwrap.json+in%3Apath&type=Code&ref=searchresults).

There isn't a strict policy here. If you think they are generally considered 'noise' in a Pull Request diff then we could certainly add them to `generated.rb` and see if anyone complains loudly.
