### ISSUE TITLE
.es file extension for javascript ES6 sources reported as Erlang

### ISSUE THREAD

**Issue by silkentrance** [github/linguist#3056]
See https://github.com/coldrye-es for a more comprehensive list of repositories for which Erlang instead of Javascript is being reported as the main language.

**Comment by Alhadis** [comment]
The Erlang/ECMAScript issue was addressed [in a pull request](https://github.com/github/linguist/pull/2920) earlier this year, which got merged on March 30th. Interestingly enough, the only Coldrye repositories which have files indexed as Erlang were last indexed on March 29th:

* [INXS Common](https://github.com/coldrye-es/inxs-common/search?l=erlang)
* [INXS](https://github.com/coldrye-es/inxs/search?l=erlang)

The rest are all indexed as ECMAScript: no Erlang files are indexed in these repositories, despite the repos being categorised as Erlang:
* [ypo-lexer-i18next](https://github.com/coldrye-es/ypo-lexer-i18next/search?l=erlang)
* [pingo-common](https://github.com/coldrye-es/pingo-common/search?l=erlang)
* [pingo](https://github.com/coldrye-es/pingo/search?l=erlang)

Repos that've been indexed more recently are correctly identified as JavaScript. Have any of the mislabelled "Erlang" repositories been updated recently with new files? I recall that changing the contents of a project's files forces Linguist to perform a full (or perhaps partial) reevaluation of each file's grammar. If nothing's changed, chances are it'll still be using its earlier (incorrect/pre-March 30th) evaluation.

@pchaigno, any thoughts?

**Comment by silkentrance** [comment]
@Alhadis so basically i need to push once more in order to get things reindexed? I think that we can close this then. Thanks for the quick reply!

**Comment by Alhadis** [comment]
I *think* so. If it doesn't reindex the whole repository, it'll probably be because Linguist's only performed a partial reevaluation of the codebase. I'm basing this off my own observations, though, so YMMV.

**Comment by pchaigno** [comment]
@silkentrance I ran Linguist against those repositories and they should all be detected as JavaScript. As @Alhadis guessed, language statistics are just not up to date. They should update if you push to those repositories. Otherwise, @arfon might be able to manually update them.

**Comment by silkentrance** [comment]
HI John, thanks for the advise and your kind help. Since these repos do not
gain that much attraction, I will try to update them when I find the time,
so there is no need for you to force a manual update.

Best Regards

Carsten

2016-06-18 15:46 GMT+02:00 Paul Chaignon <notifications@github.com>:
