### ISSUE TITLE
Wrong highlighting for minified css file

### ISSUE THREAD

**Issue by jcubic** [github/linguist#3058]
I have this [minified file](https://github.com/jcubic/jquery.terminal/blob/master/css/jquery.terminal.min.css) and the syntax highlighting is wrong, it display the whole thing as comment. I've tested the file in [atom](https://github.com/atom/atom) and it look correct.

**Comment by jcubic** [comment]
I've reported the issue here https://github.com/textmate/css.tmbundle/issues/26

**Comment by arfon** [comment]
> I've reported the issue here textmate/css.tmbundle#26

Thanks for reporting this upstream @jcubic. When this is fixed in https://github.com/textmate/css.tmbundle/issues/26 we'll automatically update here.

**Comment by jcubic** [comment]
they said

> There is nothing wrong with the grammar itself, the same code snippet parses in TextMate just fine. It appears that GitHub's parser has a time limit or length limit per-line before the parser cancels out and returns the line unparsed. So it's not actually matching as a comment it just never gets closed as that is on the line with the rest of the CSS.
