### ISSUE TITLE
PHP files being misidentified as PLSQL

### ISSUE THREAD

**Issue by carlbennett** [github/linguist#3063]
Hi,

I recently pushed up a restructure of the https://github.com/BNETDocs/bnetdocs-web repository.

However, I noticed that GitHub now believes it's a 70%+ PLSQL repository, which I had to look up what PLSQL even was after I found out. If I click on filter by PLSQL, nothing shows up.
![image](https://cloud.githubusercontent.com/assets/592196/16174372/cf0ad298-3584-11e6-9aa7-940e980e2b18.png)

https://github.com/BNETDocs/bnetdocs-web/search?l=plsql
![image](https://cloud.githubusercontent.com/assets/592196/16174371/b14f1728-3584-11e6-872c-fc7b77c19d57.png)

Is this a bug? What do I need to do to restore the correct language that is PHP? Also notice how in the above snapshot, GitHub's search shows the majority of the repository being PHP on the left-hand side.

**Comment by arfon** [comment]
@carlbennett - sorry for the confusion here. 

The `PLSQL` here is this one: https://github.com/BNETDocs/bnetdocs-web/blob/phoenix/etc/database.sample.sql - you can ask Linguist to ignore it by putting the following in a file called `.gitattributes`:

```
web/blob/phoenix/etc/*.sql linguist-vendored=true
```

My best guess about what's going on with the search view is that the search index is out of date. I'll see if I can manually update it.

**Comment by carlbennett** [comment]
>My best guess about what's going on with the search view is that the search index is out of date. I'll see if I can manually update it.

Well what's interesting is all of those files show up as last indexed yesterday, the same time when I last committed to this repository.

I'll see about adding the `.gitattributes` file, or perhaps moving this file to a new location. Oddly, it didn't show up as PLSQL at all when it was in the root of the repository.

**Comment by carlbennett** [comment]
I fixed it with this commit: https://github.com/BNETDocs/bnetdocs-web/commit/2254a283e7365d335259ee352fb7031507fd1529

It adds two `.gitattributes` files in both `bin/` and `etc/` that specify the entire directory as being `linguist-vendored=true`.

**Comment by carlbennett** [comment]
I'll leave this issue open for the repository maintainers to decide if this is really a bug or not. I'm content with the outcome of adding the `.gitattributes` file, but really I feel the `/etc/database.sample.sql` file in my repository shouldn't trigger a `PLSQL` format, if anything it should be `MySQL` or just plain `SQL`.

**Comment by pchaigno** [comment]
This was happening because there a piece of C++ code in your SQL file, itself containing the `pragma` keyword. Because of this keyword and [the PLSQL heuristic rule](https://github.com/github/linguist/blob/96bd08e391e1b4a828a27d9c4576f585d2ee92d3/lib/linguist/heuristics.rb#L385), the file was recognized as PLSQL. I guess that this is a corner case :smile: 

I still removed the keyword from the heuristic rule in #3066, which fixes your issue. It doesn't seem like `pragma` is specific to PLSQL anyway.
