### ISSUE TITLE
JavaScript detected as Java

### ISSUE THREAD

**Issue by wb9688** [github/linguist#3065]
In [Min's repository](https://github.com/minbrowser/min) some parts of the source code of [PDF.js](https://github.com/mozilla/pdf.js/) are [incorrectly detected as Java](https://github.com/minbrowser/min/search?l=java)…

**Comment by arfon** [comment]
I'm afraid there's not much we can do about this. The PDF.js developers [set the modeline as `Java` here](https://github.com/minbrowser/min/blob/master/pdfjs/build/pdf.js#L1) which means Linguist shortcuts its classification strategies to return `Java`.
