### ISSUE TITLE
Issue with some grammars

### ISSUE THREAD

**Issue by arfon** [github/linguist#3070]
There are a few grammars that I can't update because we fail to detect any scopes:

```
vendor/grammars/NSIS
vendor/grammars/sourcepawn
vendor/grammars/awk-sublime
```

To be honest I've not had a chance to figure out what's going on here but we get errors like this when running the tests (with the updated grammars):

```
3) Failure:
TestGrammars#test_local_scopes_are_in_sync [/Users/arfon/github/linguist/test/test_grammars.rb:70]:
The scopes listed for vendor/grammars/awk-sublime in grammars.yml don't match the scopes found in that repository.
Expected: ["source.awk"]
Actual: nil
```

This isn't a huge issue right now, except that we can't update grammars that throw errors like this. It's also a pain when trying to run `git submodule update --remote` as part of the release process for Linguist.

If anyone fancies trying to debug this then please be my guest. Otherwise I'll try and get to this at some point.

**Comment by Alhadis** [comment]
I'll have a look once I've finished posting a googolplex of orders at Discogs... (my streak this week is so empty, hahaha)

**Comment by arfon** [comment]
> I'll have a look once I've finished posting a googolplex of orders at Discogs... (my streak this week is so empty, hahaha)

Awesome. Thanks!

Steps to replicate:

- `git submodule update --remote`
- `bundle exec rake`
- ![giphy](https://cloud.githubusercontent.com/assets/4483/16235731/23e5b3c2-3793-11e6-971c-35d1b27207dd.gif)

**Comment by Alhadis** [comment]
My intended procedure:
* `git submodule update --remote`
* `bundle exec rake`
* STUFF HAPPENS
* ????? 
* Resolve issue 
* <img width="300" src="https://cloud.githubusercontent.com/assets/2346707/16236791/f44c5032-381c-11e6-96ca-d7c5c41936f8.jpg" />

I'll keep you posted, sir.

**Comment by pchaigno** [comment]
#3079 fixes the issue for both `vendor/grammars/NSIS` and `vendor/grammars/awk-sublime`.

The issue for [`vendor/grammars/sourcepawn`](https://github.com/austinwagner/sublime-sourcepawn) seems to be a bit different. The author removed the grammar file and there doesn't seem to be a direct replacement (maybe [the files in `snippets`](https://github.com/austinwagner/sublime-sourcepawn/tree/46063c73affc270010b59dd0359e74a63f9ddbed/snippet) but I can't find an entrypoint :/). I opened an issue at austinwagner/sublime-sourcepawn#10.

**Comment by Alhadis** [comment]
☝️ Damn this guy stealing my thunder before I had a chance to investigate. :(

Okay, yeah, it seems like the author only intended for that repo to provide SourcePawn *completions*, as opposed to everything else that usually comes with a language-support package.

**Comment by pchaigno** [comment]
> ☝️ Damn this guy stealing my thunder before I had a chance to investigate. :(

Sorry :bow: 
There's still work to be done if the author doesn't add the grammar back though :smiley: 
In that case we could add it back ourselves in another repository since it was under MIT license.
