### ISSUE TITLE
Unsupported language (EQ)

### ISSUE THREAD

**Issue by mkxcode** [github/linguist#3081]
In this repository:

https://github.com/eqela/jkop-eq

Most files are written in the EQ programming language (extension .eq), which is currently not supported or known by linguist. Tried to put .gitattributes:

*.eq linguist-language=EQ

But the language is now classified by Github as C++, not EQ.

**Comment by pchaigno** [comment]
@mkxcode I'm looking into adding support for EQ in Linguist. Do you know of a TextMate, Sublime Text, or Atom package I could use for syntax highlighting? If not, is there another language whose syntax is close enough?

**Comment by mkxcode** [comment]
I am not currently aware of any such syntax highlighting package for EQ. The syntax is very close to C# though (and C# highlighting is frequently used with EQ).

**Comment by pchaigno** [comment]
Okay, I've updated #3086 with C# highlighting.

**Comment by pchaigno** [comment]
@mkxcode Linguist will recognize EQ with its next release (usually, every couple of weeks).
When that happens, the statistics for the above repository should be:
```
$ bundle exec linguist ../jkop-eq/
66.57%  EQ
27.49%  C++
2.89%   C
2.17%   Java
0.38%   Objective-C
0.30%   C#
0.11%   HTML
0.10%   CSS
```
[Full results here](https://gist.github.com/pchaigno/8f3f20c91cfbd5d9917da9ee24f4f8e8)

**Comment by mkxcode** [comment]
Thank you.
