### ISSUE TITLE
.sass files are labeled as markup

### ISSUE THREAD

**Issue by controversial** [github/linguist#3084]
If I understand correctly, `.sass` files do not show in the top bar of a GitHub repo because [they're labeled as markup](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L3385). I don't think this is correct. The [tab-indented sass syntax](http://sass-lang.com/documentation/file.INDENTED_SYNTAX.html) is its own language, which compiles to CSS. It's not even CSS-like, it doesn't use curly brackets, etc.

I agree with the grouping of `scss` files as CSS, but I think `sass` files should be their own language. Could the sass language be marked as not a markup language, but its own language?

**Comment by pchaigno** [comment]
Closing in favor of #3093, which implements this change.
