### ISSUE TITLE
The Scheme highlighter currently colors square parentheses as errors 

### ISSUE THREAD

**Issue by davorb** [github/linguist#3089]
Here is an [example of the undesired behaviour](https://github.com/cisco/ChezScheme/blob/master/examples/power.ss). I'm pretty sure that we would all be better off if you switched to the Racket-highlighter.

**Comment by Alhadis** [comment]
Can you please explain this, then?

<img src="https://cloud.githubusercontent.com/assets/2346707/16424214/93a470e4-3da2-11e6-99ad-c8e6e4470a2d.png" width="558" alt="Figure 1" />

**Comment by larsbrinkhoff** [comment]
Apparently, *some* Scheme implementations permit using brackets instead of parentheses.  Found this in  a Scheme FAQ:

> R5RS states that square brackets are "reserved characters". However, the standard does not specify what an implementation is supposed to do when encountering reserved characters. Thus, Schemes using the above convention are standards-compliant, but code written for them may not be readable by other implementations.

**Comment by pchaigno** [comment]
This issue was already reported upstream (textmate/scheme.tmbundle#9). If they drop support for R6RS (which considers brackets as synonymous of parentheses), please reopen an issue (or this issue) and we'll discuss alternatives (and how to detect R6RS files in Linguist).

**Comment by soegaard** [comment]
@pchaigno Can we reopen this? Despite some effort  textmate/scheme.tmbundle#9  has never been pulled.

**Comment by pchaigno** [comment]
@soegaard Do you have an alternate grammar we could use for highlighting?

**Comment by soegaard** [comment]
Two options:

  1. I/We fork  textmate/scheme.tmbundle  and fix the square brackets
  2. I/We fork the grammar used for Racket grammar and make a Scheme grammar.

I prefer 2., but note that I am not impartial (I wrote the Racket grammar [1]).
In either case I would like to make a new repo for a Scheme grammar and
add some Schemers to the repo. Having people from the Scheme community
responsible for the repo, will make it much easier to fix bugs. 

The current grammar used for Racket is [1]:
    https://github.com/soegaard/racket-highlight-for-github
The list of current grammars in use:
    https://github.com/github/linguist/tree/master/vendor/grammars

PS: While looking up the Racket grammar, I see the problem originates from 2014 
(when Github switched the highlighter)  https://github.com/github/linguist/issues/1717 )
So using a grammar repo backed by Schemers would be welcome change.

**Comment by soegaard** [comment]
@pchaigno @sorawee

Hi. sorawee and I have made an alternate grammar.
We made a fork of the current Scheme grammar. 
Applied the pull request that fixes squares brackets:

Here is an example wherein you can see that square brackets are now colored normally.

https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fsicp-lang%2Fscheme.tmbundle%2Fblob%2Fmaster%2FSyntaxes%2FScheme.plist&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fnitinchandrol%2FBackgammon%2Fblob%2Fmaster%2Fproject%2Fproject.rkt&code=

/Jens Axel

**Comment by pchaigno** [comment]
@soegaard Great! Could you open a pull request to change the grammar? See [the appropriate contribution guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#changing-the-source-of-a-syntax-highlighting-grammar). I can help if needed.

**Comment by sorawee** [comment]
@pchaigno: @soegaard and I seem to have a trouble running `script/add-grammar`. Here's an output I got:

```
~/git/linguist ❯❯❯ ./script/add-grammar --replace scheme.tmbundle https://github.com/sicp-lang/scheme.tmbundle                                                                                 [3:42:26 AM]
Checking docker is installed and running
$ docker ps
Deregistering: vendor/grammars/scheme.tmbundle
$ git submodule deinit vendor/grammars/scheme.tmbundle
$ git rm -rf vendor/grammars/scheme.tmbundle
$ script/grammar-compiler update -f
Registering new submodule: vendor/grammars/scheme.tmbundle
$ git submodule add -f https://github.com/sicp-lang/scheme.tmbundle vendor/grammars/scheme.tmbundle
$ script/grammar-compiler add vendor/grammars/scheme.tmbundle
Confirming license
$ script/licensed
  > /Users/sorawee/gems/gems/bundler-1.17.1/lib/bundler/resolver.rb:287:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'rake-compiler (~> 0.9)' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)
  > 	from /Users/sorawee/gems/gems/bundler-1.17.1/lib/bundler/resolver.rb:255:in `each'
  > 	from /Users/sorawee/gems/gems/bundler-1.17.1/lib/bundler/resolver.rb:255:in `verify_gemfile_dependencies_are_found!'
  > 	from /Users/sorawee/gems/gems/bundler-1.17.1/lib/bundler/resolver.rb:49:in `start'
  > 	from /Users/sorawee/gems/gems/bundler-1.17.1/lib/bundler/resolver.rb:22:in `resolve'
  > 	from /Users/sorawee/gems/gems/bundler-1.17.1/lib/bundler/definition.rb:258:in `resolve'
  > 	from /Users/sorawee/gems/gems/bundler-1.17.1/lib/bundler/definition.rb:170:in `specs'
  > 	from /Users/sorawee/gems/gems/bundler-1.17.1/lib/bundler/definition.rb:237:in `specs_for'
  > 	from /Users/sorawee/gems/gems/bundler-1.17.1/lib/bundler/definition.rb:226:in `requested_specs'
  > 	from /Users/sorawee/gems/gems/bundler-1.17.1/lib/bundler/runtime.rb:108:in `block in definition_method'
  > 	from /Users/sorawee/gems/gems/bundler-1.17.1/lib/bundler/runtime.rb:20:in `setup'
  > 	from /Users/sorawee/gems/gems/bundler-1.17.1/lib/bundler.rb:107:in `setup'
  > 	from /Users/sorawee/gems/gems/bundler-1.17.1/lib/bundler/setup.rb:20:in `<top (required)>'
  > 	from /Users/sorawee/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
  > 	from /Users/sorawee/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
  > 	from /Users/sorawee/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
  > 	from script/licensed:3:in `<main>'
Command failed. Aborting.
```

Even after `gem install rake-compiler`, the error still persists.

Can you help us with this? And where should I report this error?

**Comment by sorawee** [comment]
@soegaard @pchaigno Here! #4437
