### ISSUE TITLE
Include support for JSP tag files

### ISSUE THREAD

**Issue by rn4n** [github/linguist#3094]
Hi,

I would like to suggest support for [files with the extension ".tag"](http://docs.oracle.com/javaee/1.4/tutorial/doc/JSPTags5.html). They have the same syntax used by JSP language, but it is not displayed with the same syntax highlighting:
- [JSP file example](https://github.com/caelum/mamute/blob/master/src/main/webapp/403.jsp).
- [Tag file example](https://github.com/caelum/mamute/blob/master/src/main/webapp/WEB-INF/tags/answerWith.tag).

:pray:

**Comment by pchaigno** [comment]
If we add the `.tag` file extension to JSP, we also need to add it to every other language that use it (otherwise all `.tag` files will be indentified as JSP). Thus, we first need to identify languages that use the `.jsp` file extension.
@reebr Are [those files](https://github.com/search?p=1&q=extension%3Atag+NOT+xml+NOT+tags+NOT+jsp+NOT+attribute+if&ref=searchresults&type=Code&utf8=%E2%9C%93) JSP tag files?

So far, I found:
- [10k XML files](https://github.com/search?p=1&q=extension%3Atag+xml+version&ref=searchresults&type=Code&utf8=%E2%9C%93)
- [at least 35k JSP tag files](https://github.com/search?p=1&q=extension%3Atag+if+tags+div+OR+section&ref=searchresults&type=Code&utf8=%E2%9C%93)

**Comment by reebr** [comment]
Woah, there're several languages that use this file format, I didn't know that.
Thanks for the search @pchaigno.

I'm not sure on [these files][1], but it seems they use the [Play framework template tags][2].
But [those files][3], they are definitely not related to Java / JSP.

Maybe it's a bad idea implement this for a specific language, there are a lot of ".tag" types. :disappointed: 

[1]:https://github.com/search?p=1&q=extension%3Atag+NOT+xml+NOT+tags+NOT+jsp+NOT+attribute+if&ref=searchresults&type=Code&utf8=%E2%9C%93
[2]:https://www.playframework.com/documentation/1.2/tags
[3]:https://github.com/search?p=1&q=extension%3Atag+xml+version&ref=searchresults&type=Code&utf8=%E2%9C%93

**Comment by pchaigno** [comment]
> I'm not sure about [these files](https://github.com/search?p=1&q=extension%3Atag+NOT+xml+NOT+tags+NOT+jsp+NOT+attribute+if&ref=searchresults&type=Code&utf8=%E2%9C%93), but it seems they use the [Play framework template tags](https://www.playframework.com/documentation/1.2/tags).

So... they are JSP files too?

> Maybe it's a bad idea implement this for a specific language, there are a lot of ".tag" types. :disappointed: 

I'm think we're fine so far. It's more of an issue when there are many different data files (because we don't have a good way to detect them).

**Comment by reebr** [comment]
> So... they are JSP files too?

I don't think so. To be honest, I didn't even know about this framework until you answered me, I researched about it after that. I believe it's more related to Java and Scala, although JSP is a Java technology those files look different.

It would be nice to have them recognized and syntax highlighted, but apparently It's hard to define where the file will be used, can be a java application, scala or even C ++ (as in the repositories you showed).

**Comment by pchaigno** [comment]
I counted 366 repositories by 315 different users from [this small search for Play framework template files](https://github.com/search?p=1&q=extension%3Atag+NOT+xml+NOT+tags+NOT+jsp+NOT+attribute+NOT+my+doBody&ref=searchresults&type=Code&utf8=%E2%9C%93). It should be enough to add this language/framework too. We'll have to make sure on the exact name though. I'll ask around.

**Comment by Nixinova** [comment]
Any reason for the 4 years of nothing in this issue?

Anyway, [searching 'extension:tag'](https://github.com/search?q=extension%3Atag) gives a few other languages, such as CSV, [XML](https://github.com/qbit-t/qbit/blob/6bd4063d4d5811d861336eda67b94a898b1017f3/boost/doc/accumulators.tag), [whatever this is](https://github.com/oturan-boga/MS-DOS_6.0/blob/fde8ea6c96afd46c58da17a4d1a4396b5887ce4a/dev/driver/driver.tag), [txt](https://github.com/uvalib/emma-production-deploy/blob/bdc0beefd0762a46fc9ae114d97c495908ad6c84/tags/emma.tag).
Is it fine to add `.tag` as "JSP tag" even though there will be these false positives? What is usual practice when theres a bunch of weird files attached to slightly-generic filenames?

**Comment by lildude** [comment]
@Nixinova since this is was opened we've implemented the ability to add generic extensions to the https://github.com/github/linguist/blob/master/lib/linguist/generic.yml file with a corresponding heuristic for each language.
