### ISSUE TITLE
QT translation file gets interpreted as a TypeScript file

### ISSUE THREAD

**Issue by avarun42** [github/linguist#3097]
Example: https://github.com/icefox/arora

The repo is marked as 14.2% TypeScript, when there's no TypeScript to speak of in the repo. Upon searching for the language, these files are shown: https://github.com/icefox/arora/search?l=typescript&type=Code

**Comment by pchaigno** [comment]
@avarun42 #3098 should improve our `.ts` heuristic rule and fix this ;)

**Comment by avarun42** [comment]
Thanks! By the way, it seems to me that the language percentages don't correspond to the actual breakdown of files in the repository. Are the percentages done strictly by extension? For example, 223 C++ files to 3 TypeScript files certainly does not correspond to 81.8% vs 14.2%

**Comment by pchaigno** [comment]
Percentages count the sum of file sizes for each language. It's not perfect but it's difficult to find a perfect way to measure the importance of each language.

After the next release, the new statistics for your repository should be:
```
95.41%  C++
1.58%   QMake
1.46%   Shell
0.44%   C
0.39%   HTML
0.29%   NSIS
0.14%   JavaScript
0.11%   Groff
0.09%   CSS
0.09%   Makefile
```
