### ISSUE TITLE
Incorrect highlighting of 'let' keyword in TypeScript highlighter

### ISSUE THREAD

**Issue by andydavies92** [github/linguist#3103]
As you can see from the highlighted TypeScript code below, the first three letters of the identifier `letter` on the second line are highlighted as if they were the keyword `let`, presumably due to a regex bug in the grammar that doesn't fully check for whitespace delimiting when looking for the aforementioned keyword:

```typescript
var letter: string;
letter = "foo";
```

However, the same code highlighted with the same grammar [appears fine on Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=source.ts&grammar_url=&grammar_text=&code_source=from-text&code_url=&code=var+letter%3A+string%3B%0D%0Aletter+%3D+%22foo%22%3B)... Is this just a matter of the grammar needing to be updated to the latest version in the next release of Linguist for the changes to start being reflected on rendered GitHub markdown?

**Comment by pchaigno** [comment]
Lightshow uses the last version of the grammar, which is not always the same as the version used on github.com. Linguist updates the version of the grammars used with every new release (usually every couple weeks). This issue will be fixed with the next release of Linguist.

**Comment by andydavies92** [comment]
Cool, thanks for letting me know.
