### ISSUE TITLE
.lsl misdetection

### ISSUE THREAD

**Issue by larsbrinkhoff** [github/linguist#3106]
The `.lsl` file extension is currently detected as [Linden Scripting Language](https://github.com/search?q=extension%3Alsl+integer+return&type=Code), but there are actually more hits for a [Linker Scripting Language](https://github.com/search?q=extension%3Alsl+memory+section).

**Comment by alexmayo** [comment]
This is most likely because there are more active users of the .lsl scripting language, namely over 1,500,000 active users, generating over $750,000,000 per year.

**Comment by pchaigno** [comment]
@alexmayo Well then, is it that [our search for Linden Scripting `.lsl` files is too restricted](https://github.com/search?q=extension%3Alsl+integer+return&type=Code) or is it that they're not investing enough of that money into open source? :smile_cat:

**Comment by alexmayo** [comment]
@pchaigno, there are a limited number of linden scripting language developers, probably no more than 10,000 (Me being one of them) - however there's upwards of a million users of LSL, who can simply copy any .LSL code found, and run it within the virtual environment where it is used.

So, to put it simply, LSL may not be more popular developer-wise, however the number of end-users who can copy and paste the code for usage is much more popular.

In a way, Linker  should be the default for .lsl from a developer's point of view, but anyone looking for a linden script who is not a developer will find it much more difficult.

**Comment by pchaigno** [comment]
In any case, I think the idea here was to try to recognize both, and not to drop support of one in favor of the other.

**Comment by Alhadis** [comment]
I think what @pchaigno means to say is  
<img src="https://cloud.githubusercontent.com/assets/2346707/17763139/0c4d7afc-655a-11e6-8cff-b4314983210b.png" width="597" alt="Pls" />

In all seriousness though, a simple heuristic should suffice. What's the most distinguishable trait about an Linda Scripting Language file that'd set it apart from a Linker Script?

**Comment by yegortimoshenko** [comment]
Something like this should do it:

```ruby
disambiguate ".lsl" do |data|
  if /^\s*(architecture|bus|core|memory)/.match(data)
    Language["Linker Scripting Language"]
  else
    Language["Linden Scripting Language"]
  end
end
```

**Comment by pchaigno** [comment]
Is Linker Scripting Language different from [Linker Script](https://github.com/github/linguist/tree/master/samples/Linker%20Script)?

**Comment by pchaigno** [comment]
Flagging as stale.
