### ISSUE TITLE
Stale branches

### ISSUE THREAD

**Issue by larsbrinkhoff** [github/linguist#3107]
There are a few stale branches: https://github.com/github/linguist/branches
Perhaps consider closing some of them?

**Comment by arfon** [comment]
Weirdly, some of these have a purpose:

- `test/attributes` is used as part of our test suite (I *think* this is still correct)
- `an-example-comparison-for-docs` is used in our GitHub help docs in the article about Pull Requests

I've tried to clear up the other branches that I believe can be safely deleted.

**Comment by larsbrinkhoff** [comment]
Great!  Just wanted to check.
