### ISSUE TITLE
Inconsistent Syntax Highlighting for CMakeLists.txt 

### ISSUE THREAD

**Issue by veesa** [github/linguist#3120]
The syntax highlighting for `CMakeLists.txt` does not display correctly if one of the following valid cmake lines are included in the file:

```
#--------------------------------------------------
###################################################
```
See examples:
 - working:
https://github.com/wilkpio/test/blob/master/good/CMakeLists.txt
 - not working:
https://github.com/wilkpio/test/blob/master/bad/CMakeLists.txt

Please see Zendesk ticket 34391 (link not included) for reference.

Thanks,
Veesa

**Comment by pchaigno** [comment]
Linguist only selects the grammar to use for highlighting. For CMake, GitHub uses [textmate/cmake.tmbundle](https://github.com/textmate/cmake.tmbundle/tree/1421c6ba47ba697742d615e92852cfe106e0879e). You should open an issue there if there isn't already one ;)
