### ISSUE TITLE
Support RPM spec files

### ISSUE THREAD

**Issue by veesa** [github/linguist#3121]
Please add support for RedHat Package Manager's `.spec` files as specified by http://www.rpm.org/max-rpm/s1-rpm-build-creating-spec-file.html

Thanks,
Veesa

**Comment by pchaigno** [comment]
Please see the [guidelines to add support for a new language to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). If RPM spec files meet the requirement on in-the-wild usage, don't hesitate to open a pull request.

**Comment by veesa** [comment]
This request had a pull request submitted in https://github.com/github/linguist/pull/442, can this issue be revisited please? A search for `".spec" rpm` reveals over 700 repos using this filetype.

**Comment by Alhadis** [comment]
[Sorted](https://github.com/github/linguist/pull/3160).

**Comment by larsbrinkhoff** [comment]
Closing in favour of @Alhadis' pull request #3160.
