### ISSUE TITLE
Not all languages are shown for project

### ISSUE THREAD

**Issue by Chalarangelo** [github/linguist#3129]
My [project](https://github.com/Chalarangelo/bootstrap-extend)'s landing page shows that all of its code is HTML. However when clicking on the *HTML 100%* at the top of the page, I can clearly [see](https://github.com/Chalarangelo/bootstrap-extend/search?l=html) that the language of the other files has been analysed properly, however it does not show in my project's main page. This has caused me some trouble with posting the project on reddit and such. Is there a way to manually troubleshoot this or anything that I can do to fix it?

**Comment by Alhadis** [comment]
Bootstrap is filtered from language analysis, because it's marked as a [vendored file](https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml). You can resolve this by using [`.gitattributes`](https://github.com/github/linguist#using-gitattributes):

```
bloatstrap.css linguist-vendored=false
```

**Comment by Chalarangelo** [comment]
I tried this, but the issue persists...

**Comment by Alhadis** [comment]
Ah right, you're using a suffix. Try this:

```
bootstrap-extend.* linguist-vendored=false
```

**Comment by Chalarangelo** [comment]
That seems to have fixed it partially, but the SCSS files are also not marked in my main repository page. Still, this is an improvement at least!

**Comment by Alhadis** [comment]
Okay, weird. Try targeting the SCSS files directly as well:

```
bootstrap-extend.* linguist-vendored=false
scss/*.scss linguist-vendored=false
```

If that doesn't work, you can always fall back to removing the `bootstrap-` part of the filenames.

**Comment by pchaigno** [comment]
I think the SCSS files are correctly counted in the language statistics. However, when you click on CSS on the language bar, it only shows the actual CSS files and not all files in the CSS group (CSS + SCSS + others). In short, for statistics, files are partitioned by language groups (a language group can contain several languages), while for searches, files are partitioned by languages.

We do know this is a bit strange and I think @arfon already reported the issue upstream.

**Comment by arfon** [comment]
> We do know this is a bit strange and I think @arfon already reported the issue upstream.

Yep, this is a known issue. I'm chatting with our search team about this to see if we can get this fixed.
