### ISSUE TITLE
Lightshow giving misleading results based on input method

### ISSUE THREAD

**Issue by Alhadis** [github/linguist#3130]
I ran into this when trying to demystify pernicious differences in grammar-parsing between Atom and Lightshow/GitHub...
## Steps to reproduce
1. [Open file by URL](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2FAlhadis%2FBreakshow%2Fblob%2Fmaster%2Fgrammars%2Fbreakshow.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2FAlhadis%2FBreakshow%2Fblob%2Fmaster%2Ftest-1.txt&code=)
2. Change input method to **Type or Paste Code**
3. [Copy+paste contents](https://raw.githubusercontent.com/Alhadis/Breakshow/master/test-1.txt) of the aforementioned file
4. Press **Highlight!**
5. <img src="https://cloud.githubusercontent.com/assets/2346707/17076449/59801ce0-50f5-11e6-8b80-3686496cca14.jpg" width="200" valign="top" />

**Comment by Alhadis** [comment]
Forget open-sourcing Lightshow, I'd burn it and start from scratch. The hell.

**Comment by pchaigno** [comment]
@Alhadis Nice catch!

/cc @aroben

**Comment by Alhadis** [comment]
Don't you point that 👎 at me, sir. I burnt at least three hours of my life this morning trying to figure out a problem in my code that wasn't even there. :<

I also didn't sleep last night (again). Coding has me sleeping every second day. =)

**Comment by pchaigno** [comment]
:stuck_out_tongue_winking_eye:

**Comment by Alhadis** [comment]
BTW, some other oddities I picked up while faffing around with Lightshow:

1. The `\A` anchor isn't matching correctly. I intended for the whole document to appear faded ([commented out](https://github.com/Alhadis/Breakshow/blob/master/grammars/breakshow.cson#L155)) so matched regions were more prominent in the feedback (yup, I was tired). Kicked up another bug instead, which occurs with either input method (typed input, or loaded remotely). [This is how it looks in Atom](https://cloud.githubusercontent.com/assets/2346707/17078362/afa2e5a0-5134-11e6-9ef9-a680c5bf4d25.png).

	This affects other grammars using the `\A` anchor too, usually to match hashbangs (this is probably a known issue). For instance, look how JavaScript's hashbang is rendered by [Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=source.js&grammar_url=&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2FAlhadis%2FBreakshow%2Fblob%2Fmaster%2Fjavascript.2016-06-01ESNextBabelEcmaTypeScriptWhatever.js&code=), and compare that to what [GitHub](https://github.com/Alhadis/Breakshow/blob/master/javascript.2016-06-01ESNextBabelEcmaTypeScriptWhatever.js) shows.

2. Another issue (which I'm now unable to reproduce...) was that matching `(?=\n)` in a `begin` context had the bizarre effect of injecting an extra newline beneath it. Not sure why it's not happening now... has somebody made modifications to Lightshow in the last 15 hours or so?

**Comment by pchaigno** [comment]
It looks like this is still a valid issue with the new Lightshow. @kivikakk Maybe something you might want to look into?

**Comment by Alhadis** [comment]
I'm still hoping #2988 will get resolved, as I'm dying to hear what the catalyst was...

**Comment by kivikakk** [comment]
It's an issue with the kind of linefeeds in use. If I modify the end of the grammar to:

```cson
{"name": "markup.bold", "captures": {"0": "name": "markup.inserted"}, "match": "match: \\$$"}
{"name": "markup.bold", "captures": {"0": "name": "markup.inserted"}, "match": "match: \\\\r\\\\n\\r\\n"}
{"name": "markup.bold", "captures": {"0": "name": "markup.inserted"}, "match": "match: \\(\\?=\\$\\)(?=$)"}
{"name": "markup.bold", "captures": {"0": "name": "markup.inserted"}, "match": "match: \\(\\?=\\\\r\\\\n\\)(?=\\r\\n)"}
```

And the input to:

```
=================================
match: $
-----------------
match: \r\n
-----------------
match: (?=$)
-----------------
match: (?=\r\n)
=================================
```

We then see:

![image](https://user-images.githubusercontent.com/1915/44315134-67cd6900-a464-11e8-972a-8f5cbf3946e2.png)


This doesn't happen when you use a URL because your test text file does indeed use only LF (0x0A, `\n`) characters to terminate lines. When you paste that into a text field in a web browser and submit it, the browser helpfully sends all newlines as CRLF (0x0D 0x0A, `\r\n`):

![image](https://user-images.githubusercontent.com/1915/44315150-a82ce700-a464-11e8-9427-4f2f4786c433.png)

See [this SO answer](https://stackoverflow.com/a/33961472/499609) for a spec reference.

Your grammar will likely want to be agnostic to whether newlines are `\r\n` or just `\n`. (Just `\r` is rare today.)

**Comment by kivikakk** [comment]
Closing as not an issue with Lightshow -- let me know if I'm mistaken here.

**Comment by Alhadis** [comment]
Ah sorry, forgot to offer a comment.

You're right, the handling of CRLF is what differs here. I believe Atom's implementation of TextMate grammars normalises newlines before performing a match, so that a naïve pattern like `}\n` would also match `}\r\n`. I could be wrong.

Anyway, it's less of a concern now that Lightshow has improved its support for CSON-based grammars, so you're right, we can close the book on this issue. =) 👍
