### ISSUE TITLE
Allow LOC statistics for a whole repository

### ISSUE THREAD

**Issue by cezarykluczynski** [github/linguist#3131]
Currently, language statistics retrieved for a whole repository are calculated as a sum of blob sizes. 

It would be a nice addition to have a high level API allowing retrieval of LOC statistics for a whole repository.

**Comment by lildude** [comment]
Linguist isn't designed to calculate the lines of code for an entire repository, and I'm not entirely sure it should be either. Yes, there is a measure of LOC of a file when checking an individual file, but  it's not 100% accurate and I think that it's more of a "nice to have" than actual function of Linguist as it's not used for anything else.

If you really need to know the lines of code of an entire repo, there are much better tools for this than Linguist.

With this in mind, I'm closing this issue and the referenced PR. I'm happy to re-evaluate this decision if a good explanation for why we need this can be provided.
