### ISSUE TITLE
Please consider extending fences' notation to allow specifying highlightable lines

### ISSUE THREAD

**Issue by StoneCypher** [github/linguist#3133]
One great feature of embeddable code blocks that's present in a lot of implementations is the ability to nominate lines for whole-line highlighting (usually through the background color.)  This is typically used to bring attention to a specific part of a code block.  For example, I like to use this in code tutorials, to highlight which lines have changed in a sequence of code blocks; it's also great for pointing out relevant pieces in example configurations.

[Jekyll supports this as `hl_lines`](https://github.com/jekyll/jekyll/issues/516).  @zpao has [a patch](https://zpao.com/posts/adding-line-highlights-to-markdown-code-fences/) that covers fenced blocks, using the following notation:

<tt>```javascript{1,8-11,14}</tt>

In fact, Github even already supports this on things rendered from a url, such as the #L123 syntax at the end of file references.

It would be super neat as well as somewhat awesome if we could get these in fenced blocks, especially for tutorials and readmes.

![image](https://cloud.githubusercontent.com/assets/77482/17123769/e241cf32-529a-11e6-9ce5-8aba0362a51b.png)

**Comment by Alhadis** [comment]
Yeah, I feel ya. For [one of my projects](https://github.com/Alhadis/GetOptions#getoptions), I actually resorted to raw HTML instead of fenced-blocks, just to emphasise the important parts (as well as [add links](https://github.com/Alhadis/GetOptions/blob/master/docs/advanced-settings.md#advanced-settings) where it made sense to).

Anyway, this isn't an issue related to Linguist. Your best bet is bringing this up with GitHub as a support request, or filing an issue at [a more relevant repository](https://github.com/github/markup). =) This one concerns language classification and identification, not its precise appearance. Beyond selecting TextMate grammars for highlighting, I mean.

**Comment by StoneCypher** [comment]
I've already been redirected through four different repos as "the relevant one" :frowning:

**Comment by StoneCypher** [comment]
The reason the last person thought that this was the appropriate place was that the extra data indicating which lines were to be highlighted would have to go in with the language identifier, the parsing of which is ostensibly linguist's job (not that I really know)

Do you know whether that's correct, @Alhadis ?

**Comment by StoneCypher** [comment]
also actually it looks like step 3 in the numbered list in that other repo's readme points back here

**Comment by pchaigno** [comment]
Hi @StoneCypher! Sorry for the delay and the "redirects".

> The reason the last person thought that this was the appropriate place was that the extra data indicating which lines were to be highlighted would have to go in with the language identifier, the parsing of which is ostensibly linguist's job (not that I really know)

Were you redirected here by GitHub support?
The parsing of the language identifier is not Linguist's job as far as I know. It's more likely to be the job of the GitHub markdown parser, which is not open source (yet?).

That said, the feature you propose would probably require modifications to several projects (as far as I can tell, not to Linguist). That's probably why you got redirected so many times :confused:
Since your feature cannot be implemented in a single open source repository, you should forward it to [GitHub support](https://github.com/contact). In general, it's the best place to send feature requests.

**Comment by StoneCypher** [comment]
> Were you redirected here by GitHub support?

no, they generally don't respond.

> That said, the feature you propose would probably require modifications to several projects

honestly, in the worst case i can imagine, even in a train wreck codebase, it should be two one-liners

one just takes a list of integers from the opening line of the fence, split by commas

the other just looks at a container of integers, sees if the current line is a member, then emits a background color styling on the line

i would bet money that you have a developer who could have done this in half an hour.  

> Since your feature cannot be implemented in a single open source repository, you should forward it to GitHub support. In general, it's the best place to send feature requests.

thanks, did in may, never heard back

[i feel like the community has to throw extremely public temper tantrums to get you guys to even talk to us decently.](https://github.com/dear-github/dear-github)  i feel like you've made it clear that you aren't very interested in what we want or need, @pchaigno .  tons of people have been asking you for this for a very long time.

this is so important that it was one of the first features you implemented, for the web viewer of code.  every single way you can view code on github does this, *except* fences, the single most important place.

i'm not filing this a fifth time.  i already implemented a completely different way to do this.

**Comment by pchaigno** [comment]
I should clarify that I'm not from GitHub. I'm just one of the maintainers of this project.

> no, they generally don't respond.

Weird, I always get an answer in the next 24 hours :/

**Comment by StoneCypher** [comment]
i apologize.  i was confused by your usage of an octocat icon.

**Comment by lildude** [comment]
As previously mentioned, this is a nice idea, however not a function of Linguist. If you still feel strongly about this, please feel free to reach out to [GitHub Support](https://github.com/contact) and suggest this feature (I couldn't find a similar request in any of your previous contact with our support team).

Closing.

**Comment by StoneCypher** [comment]
Github support is who told me this was a feature of linguist :(

**Comment by StoneCypher** [comment]
It would be awesome if you would tell me what this was a feature of

I've asked for this now in nine Github projects, for about two years, and staff responses are generally "that's not here," (closed with no further help or suggestions)

**Comment by StoneCypher** [comment]
I feel like as a paying customer it would probably be nice if someone would just tell me where to put this, after two years and change

**Comment by lildude** [comment]
> It would be awesome if you would tell me what this was a feature of

I did. You need to contact the support team using the "Contact GitHub" link at the bottom of any page on GitHub, which I also linked to in my previous comment, as GitHub doesn't currently have any formal public location for gathering feature requests.

**Comment by StoneCypher** [comment]
As mentioned, they led me here

**Comment by lildude** [comment]
I really can't find your previous interactions requesting this, but nevermind. I've taken note of your feature request so you don't need to contact support.

**Comment by StoneCypher** [comment]
I would rather file a public bug, please.

Where do these go?

**Comment by StoneCypher** [comment]
It's very difficult for me to write this for you guys if you won't tell me
what project is the relevant project

I've been ready to pitch in since 2015

**Comment by lildude** [comment]
> It's very difficult for me to write this for you guys if you won't tell me
> what project is the relevant project

The project is the main GitHub repository (github/github) which is a private repository.

> I would rather file a public bug, please.

We don't have a public forum for logging feature requests against GitHub.com functionality that is not covered by a public repository/project. As the main github/github repository is private, you won't have access to it so the closest we can offer is to contact our support team. 

We've recently launched a [Community Forum](https://github.community) which _may_ at some point accept and start documenting feature requests publicly, but as stated in [this post asking about where to log bug reports and feature requests](https://github.community/t5/Welcome/Where-do-I-post-bug-reports-and-feature-requests-about-the/m-p/279), the best option is to contact support.

I apologise if you've previously been bounced here, but our support team is definitely the best port of call. If you need some sort of "weighting" for your contact, please feel free to @-mention my handle (I'll be automatically pinged when our tool receives your email/note) and even link back to this issue. I'm happy to act as a contact for our support team if they have any questions about which project is this falls under to prevent any further project ping-pong.
