### ISSUE TITLE
A new example comparison for docs

### ISSUE THREAD

**Issue by pchaigno** [github/linguist#3135]
We're regularly receiving "incorrect pull request" to merge the `an-example-comparison-for-docs` branch in `master` ([21 PRs](https://github.com/github/linguist/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aclosed%20an%20example%20comparison%20for%20docs) to this date). This is due to [this help page](https://help.github.com/articles/comparing-commits-across-time/) which uses Linguist as the example repository.
I understand that a realistic repository (with tags, releases and enough commits) is needed for this documentation, but maybe a clone of linguist would be more suited to this purpose...? (I'm suggesting a clone because that would require only minor modification to links in the documentation.)

/cc @arfon

**Comment by arfon** [comment]
> We're regularly receiving "incorrect pull request" to merge the `an-example-comparison-for-docs` branch in master (21 PRs to this date). This is due to this help page which uses Linguist as the example repository.

Thanks for raising this @pchaigno. I think we should probably change this. I think the link in the docs is a good idea (showing people a real diff etc. in a PR) but it's unnecessary noise for Linguist maintainer plus it doesn't feel that great to be closing these PRs with little/no interaction with the user.

I think a fork of Linguist would work well here. @bernars - what do you think?

**Comment by bernars** [comment]
> I think a fork of Linguist would work well here. @bernars - what do you think?

I think that's a great solution, and sorry for the problems! We'll get an issue opened to address this ASAP. 👍 ❤️

**Comment by arfon** [comment]
> I think that's a great solution, and sorry for the problems! We'll get an issue opened to address this ASAP. 👍 ❤️

💖 wonderful. Thanks @bernars

**Comment by jmarlena** [comment]
Created a bug fix issue for this in https://github.com/github/help-docs/issues/3703. 💫

**Comment by bernars** [comment]
@jmarlena has updated "[Comparing commits across time](https://help.github.com/articles/comparing-commits-across-time/) to reference a new fork of this repository.

Thank you for letting us know about the problem, and do reach out to me if we can help further! 🌠

**Comment by arfon** [comment]
Wonderful, thanks @jmarlena & @bernars

**Comment by pchaigno** [comment]
Thanks @jmarlena, @bernars!
