### ISSUE TITLE
inline code line number

### ISSUE THREAD

**Issue by golanguz** [github/linguist#3136]
Hello guys, i'm here to request a feature. Can we have inline code line number ? thank you

**Comment by Alhadis** [comment]
What are you talking about?

**Comment by pchaigno** [comment]
@golanguz Do you mean code line numbers in snippets such as:
```python
def test():
  return 0
```
Unfortunately, that's not something that can be changed in Linguist. You should mention it to support@github.com.

**Comment by golanguz** [comment]
@pchaigno yes that what i mean. also https://golanguz.github.io/public/markdown.html when i use it with gists the code is too small

**Comment by pchaigno** [comment]
None of these issues can be addressed in Linguist as it only selects the grammars best suited to highlight a piece of code (it can only influence the colors applied to characters). I encourage you to mention this to GitHub support.
