### ISSUE TITLE
.storyboard and .pbxproj should be marked `generated`

### ISSUE THREAD

**Issue by asarazan** [github/linguist#3139]
Seems like this fits both the letter and spirit of the `generated` category. Happy to PR this, just wanted to get dev's thoughts on it first.

**Comment by pchaigno** [comment]
These are file extensions (`foo.storyboard`) and not filenames (`.storyboard`) right?

**Comment by Alhadis** [comment]
Correct. They're created by Xcode... XML files, evaluated as data.

**Comment by Alhadis** [comment]
I'd give you an example file, but lol, Apple:

<img width="409" alt="screen shot 2016-08-02 at 3 13 32 pm" src="https://cloud.githubusercontent.com/assets/2346707/17317686/c0471b9c-58c3-11e6-81e3-db4ac30729a3.png">

Soon as they drop support for Mavericks, I'm switching to Ubuntu. =)

**Comment by arfon** [comment]
Some historical context for `.pbxproj` here: https://github.com/github/linguist/issues/2349

**Comment by asarazan** [comment]
Ah interesting. I figured there must be a back-story here. Seems like `generated` is off the table, but I'd love to see the .gitattributes suppression stuff get finished. 

I'll shoot an email to enterprise support with a +1 from Capital One.

**Comment by lildude** [comment]
It's been possible to suppress files from diffs using `linguist-generated` in `.gitattributes` for a while on GitHub.com and GitHub Enterprise 2.10 and newer now so I'm closing this issue.
