### ISSUE TITLE
perl's HTML::Template files are misclassified

### ISSUE THREAD

**Issue by nasa9084** [github/linguist#3140]
I use HTML::Template(perl) scripts.
The extension is usually .tpl or .tmpl (sometime I use this extension for Jinja2(Python) Template), but the files are classified as smarty(php).
For Example, my organization repository is here: [web-apps-tech/hubotmaker_frontend/templates](https://github.com/web-apps-tech/hubotmaker_frontend/tree/master/templates)

**Comment by Alhadis** [comment]
See the section in the readme file on [language overrides](https://github.com/github/linguist#overrides).

Your best bet is adding something like this to your repository's `.gitattributes` file:

```
*.tpl linguist-language=Perl
```

**Comment by nasa9084** [comment]
@Alhadis 
Thank you your comment.
I will do that.
