### ISSUE TITLE
GitHub Code highlighting for React file with js extension

### ISSUE THREAD

**Issue by ktalebian** [github/linguist#3144]
If you create a React file but save it with `.js` extension, then GitHub code highlighting breaks when it reaches a single quote in text. Saving the same file in `.jsx` works fine.

See example on [this repo](https://github.com/ktalebian/react-highlighting-problem). Both file `correct-highlighting.jsx` and `incorrect-highlighting.js` have the same content. As you can, the `.js` has wrong syntax highlighting.

A solution is to add `// vim: syntax=JSX` to the top of the file, but this will get annoying really fast. Ideally, Linguist is intelligent to determine that the file is a React file and applies correct syntax.

**Comment by muescha** [comment]
same here:
https://github.com/keybase/client/blob/master/shared/nav.android.js#L113

**Comment by pchaigno** [comment]
We'd first have to add `.js` as a [JSX extension](https://github.com/github/linguist/blob/b958779e3d7364b89a988c0b41dfc012ad7fd450/lib/linguist/languages.yml#L1985-L1994) for Linguist to be able to distinguish the two. Please see the [guidelines to add support for a new extension to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language).
