### ISSUE TITLE
Haskell highlighting: class definition with no "where"

### ISSUE THREAD

**Issue by Fedjmike** [github/linguist#3146]
When a class definition doesn't have a "where" body (which is legal Haskell) the hightlighter gets stuck and doesn't highlight the rest of the code correctly. Examples:

```haskell
-- Highlighted as comment
class X y
-- Not highlighted correctly
```

https://github.com/Fedjmike/ngen/blob/07296373ff6dc9a7933652f6fa1bc373f0c3d06f/language.hs#L12

**Comment by Alhadis** [comment]
This is an issue with the [language-grammar](https://github.com/textmate/haskell.tmbundle) Linguist uses to provide syntax highlighting. You're better off submitting a bug report there. =)
