### ISSUE TITLE
Code incorrectly recognised as Objective-C

### ISSUE THREAD

**Issue by alamaison** [github/linguist#315]
Our project, Swish (https://github.com/alamaison/swish), is almost entirely C/C++ with the odd MS-DOS batch file and Python script for build support.  However, linguist, as used by Github, is detecting 8.3% of the code as Objective-C.

I can't work out why.  In particular, there are no files with a .m or .mm extension.

**Comment by DinosaurBlanket** [comment]
[This repo](https://github.com/DinosaurBlanket/marbles) is still showing 9.7% Objective-C where there is none.

**Comment by arfon** [comment]
> This repo is still showing 9.7% Objective-C where there is none.

Sorry to hear this. Disambiguating C, C++ and Objective C is an ongoing issue for us. If you're after a quick fix for the language statistics bar then you could correct Linguist's analysis using the overrides: https://github.com/github/linguist#overrides

**Comment by avcado** [comment]
[This repo](https://github.com/avcado/desparity)  is showing 38.3% Objective-C but there is none.

**Comment by lildude** [comment]
@avcado no it's not 😁 Also, if you wish to discuss further, please open a new discussion. This issue is very very old and Linguist has moved on quite a bit since then.
