### ISSUE TITLE
Repository language is (incorrectly) mostly SourcePawn

### ISSUE THREAD

**Issue by conlain-k** [github/linguist#3150]
[Our project](https://github.com/projectchrono/chrono) is written mostly in C++, but the language breakdown in the main repo page says that it is written primarily in SourcePawn. There is no SourcePawn in our repository.

**Comment by rserban** [comment]
To add to this: although 62.1% of the code is supposedly SourcePawn, no files are listed as such.  Instead, clicking on SourcePawn in the stats bar, we get:
`We couldn’t find any code matching ''`
Any suggestions?

**Comment by larsbrinkhoff** [comment]
Your repository have some `.inc` files which are misclassified as SourcePawn.  It seems they really avre POV-Ray include files.

A large number of languages use `.inc` for include files, and unfortunately, Linguist doesn't support them all yet.

**Comment by rserban** [comment]
Interesting, some of the `.inc` files are recognized as "POV-Ray SDL", but not all of them.  In fact, the larger ones are not and those are probably what skews the statistics (even though this doesn't really explain why they would be classified as SourcePawn, yet no files are listed when I click on that category).

We will look into using `.gitattributes` to fix this.

**Comment by larsbrinkhoff** [comment]
Right, `.gitattributes` is a quick fix.  As a long-term solution, I have submitted a pull request to look for `#declare` in `.inc` files to classify them as POV-Ray.  That should at least be a small step in the right direction.

**Comment by rserban** [comment]
Thanks.  Thinking a bit more about this, I believe the `.gitattributes` route is anyway the right thing to do in our case.  Even if these `.inc` files were classified correctly as POV-Ray, due to their size they would make our project look like a POV-Ray project which it's not...
