### ISSUE TITLE
Repository incorrectly reporting Groovy

### ISSUE THREAD

**Issue by FarbodSalamat-Zadeh** [github/linguist#3153]
I was browsing through [one GitHub repository](https://github.com/astuetz/PagerSlidingTabStrip) (not mine) where I noticed that the language bar says it contains 7.7% Groovy.

When [clicking/searching for Groovy](https://github.com/astuetz/PagerSlidingTabStrip/search?l=groovy), no files showed up, so I'm not sure whether this is an error, or if there's something I'm missing here.

**Comment by pchaigno** [comment]
Thanks for your report!

> I was browsing through one GitHub repository (not mine) where I noticed that the language bar says it contains 7.7% Groovy.

Statistics are not up-to-date, it's now 100% Java with the last version of Linguist. It should update with the next push to the repository.

> When clicking/searching for Groovy, no files showed up, so I'm not sure whether this is an error, or if there's something I'm missing here.

This is a known bug: there's some synchronization issue in the caching of statistics and search results. It has already been reported upstream.
