### ISSUE TITLE
Added Dut Lang

### ISSUE THREAD

**Issue by avelino** [github/linguist#3155]
Source: https://github.com/dut-lang/dut
Sample: https://github.com/dut-lang/unittest/blob/master/unittest.dut

    Dut:
    type: programming
    color: ""
    extensions:
      .dut tm_scope: source.c++ ace_mode: c_cpp

**Comment by pchaigno** [comment]
Please see the [guidelines to add support for a new language to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). If Dut meets the requirement on in-the-wild usage, don't hesitate to open a pull request.
