### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by jcubic** [github/linguist#3158]
What about markdown except README files. I have blog written in jekyll and it's marked as mostly html.

**Comment by Alhadis** [comment]
Could you elaborate?

**Comment by jcubic** [comment]
Markdown should be marked as language in statistics.

**Comment by Alhadis** [comment]
Certain language types are excluded from language statistics, which includes Markdown. If you click on the language's name above the stat-bar, you'll find a detailed summary of every listed file-type.
