### ISSUE TITLE
Use .gitattributes to override not work for me. 

### ISSUE THREAD

**Issue by alexazhou** [github/linguist#3163]
Hi:

I readme the readme of linguist and try to use .gitattributes file to override language of my Repo. But it not work right on github, So I install linguist local, and try many kind of format in .gitattributes file but it now work at at all 😅.

Has I misunderstood something? If somebody knows, please tell me

 Here is my repo  [VeryNginx](https://github.com/alexazhou/VeryNginx).

**Comment by pchaigno** [comment]
What are you trying to achieve?

**Comment by alexazhou** [comment]
I want to hide html part. In fact there is only one very big html file in my Repo, I want linguist to ignore it 

The html is 
```
verynginx/dashboard/index.html
```

and write a **.gitattributes** to the root path of my repo 
```
verynginx/dashboard/index.html linguist-vendored=false
```

I alse tryed 

```
verynginx/* linguist-vendored=false
*.html  linguist-vendored=false
```

but it all don't work

**Comment by Alhadis** [comment]
@alexazhou [These are the files](https://github.com/alexazhou/VeryNginx/search?l=html) that are inflating your repository's language statistics. It looks like they haven't been indexed recently. If you push a change to either one of them, they should disappear from the indexing, because it's forcing GitHub to recalculate that folder's statistics.

**Comment by pchaigno** [comment]
@alexazhou You want the opposite:
```
verynginx/* linguist-vendored=true
```
or
```
*.html  linguist-vendored=true
```

**Comment by Alhadis** [comment]
... yeah, that too.

😂👌 I'll pretend I said that.

**Comment by alexazhou** [comment]
@Alhadis 

Oh, thanks .

I had commit once on the index.html just now, but nothing changed, do I need to wait a little longer?

**Comment by alexazhou** [comment]
@pchaigno 

Thanks ，It works after change **.gitattributes** to
 ```
*.html  linguist-vendored=true
```

I think If the document can be more detail will be very nice

**Comment by Alhadis** [comment]
More detailed? You kiddin'? We have enough problems getting people to read the damn thing already. :D

**Comment by alexazhou** [comment]
😄，That's ok.  It just my personal opinion

**Comment by alexweissman** [comment]
@Alhadis I agree with @alexazhou, the documentation could be a *lot* clearer about how to explicitly exclude entire directories from github's language parsing.

**Comment by arfon** [comment]
> @Alhadis I agree with @alexazhou, the documentation could be a lot clearer about how to explicitly exclude entire directories from github's language parsing.

We'd welcome suggestions/modifications in the form of a pull request.

**Comment by alexweissman** [comment]
Sure thing!  I think I managed to successfully exclude all files of a certain *type* from the statistics, but I'm still not clear about how to properly exclude an entire directory.  I tried something similar to `verynginx/* linguist-vendored=true`, but without any success.

**Comment by pchaigno** [comment]
@alexweissman That should work. Could you open a new issue with a link to the repository and your goal?
