### ISSUE TITLE
Should all *.tpl files be treated as Smarty templates?

### ISSUE THREAD

**Issue by hckr** [github/linguist#3167]
In my own repository I have *.tpl file which serves as template (even contains some HTML inside) but isn't a Smarty template, yet GitHub (linguist) counts it as such.

Should it work that way? What do you think - maybe some heuristics could be added?

**Comment by pchaigno** [comment]
What's the language of these `.tpl` files? You should check the [guidelines to add support for a new language to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). If it meets the requirement on in-the-wild usage, don't hesitate to open a pull request.

**Comment by hckr** [comment]
The thing is that it isn't anything standard, like *.txt or *.cfg. I managed to find in-the-wild usage from Mozilla (these are definetely not Smarty templates): https://github.com/search?utf8=%E2%9C%93&q=extension%3Atpl+user%3Amozilla&type=Code&ref=searchresults

**Comment by hkiel** [comment]
[OpenModelica uses .tpl files](https://github.com/OpenModelica/OMCompiler/search?l=smarty) for [Susan](http://www.ida.liu.se/labs/pelab/modelica/OpenModelica/releases/1.6.0/doc/OpenModelicaTemplateProgramming.pdf) language  These are definitely not Smarty.
Those are text files which start with the keyword "package". C++ like comments and white space may occur before the keyword.

Can you implement this new language, please?

Filter by extension is not appropriate here, as I can imagine many people using *.tpl as simple template file for whatever they like...

**Comment by brandonblack** [comment]
@hkiel @hckr please take a look at our contributing guide for instructions on how to create a pull request for a new language. We'd love to review a PR from one of you for this. Thanks!

https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language
