### ISSUE TITLE
GLSL file recognized as JavaScript

### ISSUE THREAD

**Issue by karol-202** [github/linguist#3168]
I've got a geometry shader written in GLSL, file has .gs extension. In my repository it's recognized as JavaScript file.

```
#version 330

layout (triangles) in;
layout (triangle_strip, max_vertices = 18) out;

uniform mat4 viewProjectionMatrices[6];

out vec4 pos;

void main()
{
    for(int face = 0; face < 6; face++)
    {
        gl_Layer = face;
        for(int i = 0; i < 3; i++)
        {
            pos = gl_in[i].gl_Position;
            gl_Position = viewProjectionMatrices[face] * pos;
            EmitVertex();
        }
        EndPrimitive();
    }
}
```

**Comment by Alhadis** [comment]
Can you elaborate?

BTW, to insert a code-block, you insert this:

	```
	<code here>
	```

**Comment by larsbrinkhoff** [comment]
Currently, GitHub doesn't support `.gs` as a GLSL file extension.  A while ago, I did some research to find popular GLSL extensions, and indeed `.gs` was among them.

I tried to estimate the number of `.gs` files for different languages:

Language | Files
--- | ---
all | [42000](https://github.com/search?q=extension%3Ags+NOT+slartibartfast)
Gosu | [18000](https://github.com/search?q=extension%3Ags+package+uses+var)
JavaScript | [8500](https://github.com/search?q=extension%3Ags+function+NOT+package)
GLSL | [2400](https://github.com/search?q=extension%3Ags+uniform+OR+vec3+OR+gl)

**Comment by smola** [comment]
PR with fix: https://github.com/github/linguist/pull/3747

**Comment by pchaigno** [comment]
Closing in favor of #3747.
