### ISSUE TITLE
cython syntax highlighting could use some improvements

### ISSUE THREAD

**Issue by anntzer** [github/linguist#3169]
Picking an example from a well-known python library... https://github.com/numpy/numpy/blob/master/numpy/random/mtrand/mtrand.pyx#L134

`ctypedef`, `cdef`, `cdef extern`, `cimport`, `gil`, `nogil` should be highlighted as keywords; `object` should likely be highlighted as keyword (technically, "type") too.

**Comment by pchaigno** [comment]
Linguist only selects the grammar to use for highlighting. For Cython, GitHub uses [textmate/cython.tmbundle](https://github.com/textmate/cython.tmbundle/tree/e9f4d3a1e44a14df8f245f98591f62df34fbabd8). You should open an issue there if there isn't already one.
