### ISSUE TITLE
wrong repository statistics on github (TypeScript insted of c++)

### ISSUE THREAD

**Issue by narunlifescience** [github/linguist#3170]
wrong detection of language 
https://github.com/narunlifescience/AlphaPlot
https://github.com/highperformancecoder/scidavis
these are Qt c++ projects & don't contain TypeScript.

**Comment by pchaigno** [comment]
@narunlifescience Thanks for reporting this issue! #3171 should fix it.

**Comment by narunlifescience** [comment]
Thanks :)

**Comment by pchaigno** [comment]
Should be fixed with the next release of Linguist (usually every couple weeks).
