### ISSUE TITLE
JSX Syntax highlighting broken again.

### ISSUE THREAD

**Issue by cozos** [github/linguist#3178]
https://github.com/github/linguist/commit/cb5bc91fe3550f6332c94e19bc74b0a2489bfb27#diff-464b0c6cffb722d15311d573b2265c58R1

`language-babel` was version locked (See https://github.com/github/linguist/pull/3091) but was updated.

**Comment by cozos** [comment]
```jsx
import React from 'react';

var ExampleApplication = React.createClass({
  render: function() {
    var elapsed = Math.round(this.props.elapsed  / 100);
    var seconds = elapsed / 10 + (elapsed % 10 ? '' : '.0' );
    var message =
      'React has been successfully running for ' + seconds + ' seconds.';

    return <p>{message}</p>;
  }
});

var start = new Date().getTime();

setInterval(function() {
  ReactDOM.render(
    <ExampleApplication elapsed={new Date().getTime() - start} />,
    document.getElementById('container')
  );
}, 50);
```

**Comment by pchaigno** [comment]
> If we continue with this pull request, I think we should add a test with the version hardcoded. Otherwise we could update it again by mistake on the next release :/

:stuck_out_tongue_winking_eye:

**Comment by Alhadis** [comment]
Or somebody could fork the guy's repo and use that instead.

**Comment by cozos** [comment]
Thanks for looking into it :) I think that the fork would be the most long term solution.

**Comment by pchaigno** [comment]
@arfon Should I fork the repository in the [`github-linguist`](https://github.com/github-linguist) group until the issue is fixed upstream?

**Comment by Alhadis** [comment]
The issue will never be fixed upstream. The author of the grammar doesn't give a shit about GitHub's highlighting, only Atom. He's even said so himself.

**Comment by arfon** [comment]
> @arfon Should I fork the repository in the github-linguist group until the issue is fixed upstream?

Let's do it.

**Comment by pchaigno** [comment]
@Alhadis upstream can be another grammar ;)

@arfon Done in #3201.

**Comment by morenoh149** [comment]
So jsx should work in github PRs now? not sure what merging #3201 actually means for the site.

**Comment by arfon** [comment]
> So jsx should work in github PRs now? not sure what merging #3201 actually means for the site.

It should be working yes. Are you seeing issues?

**Comment by Alhadis** [comment]
@morenoh149 Are you seeing broken highlighting in a pull request somewhere?

If so, please file an issue at the [forked grammar](https://github.com/github-linguist/language-babel) with links to the affected content.

**Comment by Alhadis** [comment]
Shit, man, talk about timing.

**Comment by morenoh149** [comment]
@Alhadis I don't think I can open an issue on that fork actually. Don't see the tab.

**Comment by Alhadis** [comment]
@pchaigno / @arfon Could you enable issue-tracking for the repo, please? Unless he's supposed to report this particular issue here...

**Comment by arfon** [comment]
> @pchaigno / @arfon Could you enable issue-tracking for the repo, please? Unless he's supposed to report this particular issue here...

@pchaigno could you enable issue tracking on https://github.com/github-linguist/language-babel?

**Comment by pchaigno** [comment]
Done. I don't think we can really afford to maintain a fork of the JSX grammar though. The best solution would be to fix the original issue on the parent repository.
