### ISSUE TITLE
Go: False positive format string detection

### ISSUE THREAD

**Issue by mcandre** [github/linguist#3184]
The Go highlighter sometimes highlights percent signs in strings, even though the usage of the string is not as a C-style printf format string, but an ordinary literal string.

Example:

https://github.com/mcandre/mcandre/blob/master/go/ddg/ddg.go

**Comment by pchaigno** [comment]
Linguist only selects the grammar to use for highlighting. For Go, GitHub uses [AlanQuatermain/go-tmbundle](https://github.com/AlanQuatermain/go-tmbundle/tree/0bdec37eded22e8416d046fe28e50d2c5c666798). You should open an issue there if there isn't already one.

**Comment by mcandre** [comment]
Thanks for the tip!

https://github.com/AlanQuatermain/go-tmbundle/issues/61
