### ISSUE TITLE
Shell: Incorrect syntax highlighting for command substitution using backticks with comment inside

### ISSUE THREAD

**Issue by Herst** [github/linguist#3186]
All these would output `(foo)()(bar)`, which is not what the syntax highlighting implies:

``` sh
printf '(%s)' foo "`# '`" bar
```

``` sh
printf '(%s)' foo "`# "`" bar
```

``` sh
printf '(%s)' foo "`# '`" \
  bar
```

``` sh
printf '(%s)' foo "`# "`" \
  bar
```

**Comment by Alhadis** [comment]
Syntax highlighting on GitHub is provided by TextMate-compatible grammars, which Linguist selects to provide code colouring. For shell-scripts, the highlighting is provided by [atom/language-shellscript](https://github.com/atom/language-shellscript). You should report this issue there.

**Comment by Herst** [comment]
Oh, OK. It was https://help.github.com/articles/creating-and-highlighting-code-blocks/ ("We use Linguist to perform language detection and syntax highlighting.") that lead me here.

**Comment by pchaigno** [comment]
> It was https://help.github.com/articles/creating-and-highlighting-code-blocks/ ("We use Linguist to perform language detection and syntax highlighting.") that lead me here.

@arfon Maybe this could be slightly rephrased to explain that Linguist only *selects* the grammars for syntax highlighting? I'm not sure what's the best way to redirect users to those grammars though :/

**Comment by arfon** [comment]
> @arfon Maybe this could be slightly rephrased to explain that Linguist only selects the grammars for syntax highlighting?

Yeah, that's probably worth updating to make things a little clearer. 

>  I'm not sure what's the best way to redirect users to those grammars though :/

I mean, [this list](https://github.com/github/linguist/tree/master/vendor/grammars) is the source of truth here but the idea of sending people to a folder of Git submodules is literally the least user-friendly thing I think I've ever thought of...

**Comment by Alhadis** [comment]
We could add a `README.md` file to the [`vendor/` directory](https://github.com/github/linguist/tree/master/vendor) that lists what each language uses for syntax highlighting. Something like this, perhaps:

> - **1C Enterprise:** [xDrivenDevelopment/atom-language-1c-bsl](https://github.com/xDrivenDevelopment/atom-language-1c-bsl)
> - **AGS Script:** [textmate/c.tmbundle](https://github.com/textmate/c.tmbundle)
> - **AMPL:** [ampl/sublime-ampl](https://github.com/ampl/sublime-ampl)
> - **API Blueprint:** [apiaryio/api-blueprint-sublime-plugin](https://github.com/apiaryio/api-blueprint-sublime-plugin)
> - **APL:** [Alhadis/language-apl](https://github.com/Alhadis/language-apl)

Obviously, this wouldn't be updated by hand: it'd be done automatically whenever `bundle exec rake whatever` is called.

**Comment by arfon** [comment]
> Obviously, this wouldn't be updated by hand: it'd be done automatically whenever bundle exec rake whatever is called.

👍 love it.

**Comment by Alhadis** [comment]
I'll have a crack at it then. =) Will give me an excuse to brush up on my Ruby skills. Which're currently so rusty, I installed `cargo` instead of `gem`.

That might very well be the funniest thing I'll say, ever.

**Comment by Alhadis** [comment]
Righto, [actioned](https://github.com/github/linguist/pull/3192). This is the first serious Ruby script I've ever written, so go easy on me, heh.
