### ISSUE TITLE
Is there a way to get my own version of lightshow?

### ISSUE THREAD

**Issue by vors** [github/linguist#3187]
[I'd like to use API](https://github.com/PowerShell/EditorSyntax/issues/2) that [lightshow](https://github-lightshow.herokuapp.com/) provides for automatic testing. It's desirable to avoid using the actual service and host it locally on the CI worker machine for few reasons

* I don't want to abuse github-lightshow.herokuapp.com
* Sending WebRequests takes time
* If site is unavailable, our tests will start failing

I could not find any information about lightshow backend. Can you, please, share some information about it and validate my idea?

**Comment by pchaigno** [comment]
@vors Unfortunately, Lightshow is still closed source, so that's not possible :/

**Comment by nixel2007** [comment]
You can try atom-grammar-test package. 
Example of use is here in spec folder https://github.com/xDrivenDevelopment/atom-language-1c-bsl?files=1
