### ISSUE TITLE
R/ Rebol disambiguation reloaded

### ISSUE THREAD

**Issue by ppernot** [github/linguist#3190]
Hi, 

[these](https://github.com/ppernot/Reproducible-Research/search?l=rebol) R files in my projects are incorrectly identified as Rebol.

Thanks,

Pascal

**Comment by pchaigno** [comment]
You can mark those files as vendored using [Linguist overrides](https://github.com/github/linguist#overrides).

**Comment by larsbrinkhoff** [comment]
Some low-hanging fruit: R uses `#` for comments, and Rebol uses `;`.

**Comment by ppernot** [comment]
@pcaigno Thanks for the tip

**Comment by pchaigno** [comment]
@ppernot - Thanks to @larsbrinkhoff :point_up: , all your R files might be correctly detected in the future :smiley:

**Comment by ppernot** [comment]
@pchaigno 
Note that the sem--column can be used in R to separate several instruction on the same line.
This might be tricky...
I realize that, even using .gitattributes, I have [these](https://github.com/ppernot/Reproducible-Research/search?l=rebol) R files tagged as Rebol, and they contain semi-columns...

**Comment by Alhadis** [comment]
Nothing a regular expression can't handle, mate. :)

```ruby
line =~ /^\s*;/
```

I'm assuming any line *beginning* with a semicolon is a comment, right? (I know less R than I know French, which says something).

**Comment by larsbrinkhoff** [comment]
@ppernot I didn't add `;` to the heuristic because Rebol files are already recognised well enough by looking for `rebol`.

I tested all your files with the new heuristic, and they all came out as R.

**Comment by ppernot** [comment]
@larsbrinkhoff OK, so I just have to wait for the new heuristic to be active, right ?
Thanks, anyway !

**Comment by larsbrinkhoff** [comment]
Right, when a new release has been done.

**Comment by Alhadis** [comment]
And an outstanding avalanche of pending pull requests has been reviewed and merged. ;) `\*knuff\*`

... dude, "knuff" is Swedish for "nudge"? :( It also means "cuddle" in Dutch, so this feels pretty freakin' awkward.

**Comment by larsbrinkhoff** [comment]
Sure, that would be the closest word.  The Dutch also have "klant" all wrong.  Or maybe just right.

**Comment by Alhadis** [comment]
Nah, the Dutch are like a confused lovechild of German and English that doesn't know which way to swing, so it winds up trying to sound like both. :D

Learning Dutch was simultaneously the most frustrating and hilarious endeavour I've ever taken.

(I'll shaddap now, I just wanted an excuse to draw attention to my awesome Ruby scripts I feel so proud of for some reason...)

**Comment by ppernot** [comment]
Works grat now. Thanks!
