### ISSUE TITLE
create new syntax for Level language

### ISSUE THREAD

**Issue by elucian** [github/linguist#3191]
I'm the author of Level language that is stored on GitHub. I wish to have Level language syntax available so that I can create program examples and have the language recognized for Wiki articles. The syntax is work in progress and is symilar to ADA and Pascal.

Project: [Level language specification](https://github.com/sage-code/level/wiki)

**Comment by Alhadis** [comment]
Please see the [contribution guide](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language), particularly the part about existing language usage.

**Comment by elucian** [comment]
Yes I understend. If I make a clone pf ;omgiost project and I include the new language specification it will be approved? Then I will be the sole user until the language become popular.

**Comment by Alhadis** [comment]
> Then I will be the sole user until the language become popular

... erh... no. If it ever DOES get popular, then we'll add it.
