### ISSUE TITLE
Diffs suppressed for diffs with comments

### ISSUE THREAD

**Issue by bcr** [github/linguist#3194]
If a diff has comments, and would ordinarily be suppressed, I am of the opinion that the diff should be shown (or you won't see the comments).

I think the spirit of suppressing the diff is to eliminate the chatter from things you care about in the changelist. The flipside is if someone comments on that part of the diff, then it is something I think they care about.

SynchroLabs/SynchroServer@082a5ba4c1910010986b2f5dca257f14572dc7e8 demonstrates this issue. The file `json.js` has its diff suppressed but has comments on it.

**Comment by pchaigno** [comment]
This is not something that can be changed/implemented in Linguist. You should report it to GitHub support. (I'd report it as a bug.)
