### ISSUE TITLE
Invalid highlighting in PHP doc comments

### ISSUE THREAD

**Issue by kissarat** [github/linguist#3200]
https://github.com/phpbb/phpbb/blob/9596db9b8869d2d9d68112ac7aadf394545d2811/phpBB/phpbb/auth/auth.php#L216
<img width="902" alt="screen shot 2016-09-08 at 4 34 10 pm 1" src="https://cloud.githubusercontent.com/assets/1538346/18415258/c056565c-77f4-11e6-9222-d67c29b73d30.png">
I was redirected here from github support
<img width="472" alt="screen shot 2016-09-11 at 7 53 54 am" src="https://cloud.githubusercontent.com/assets/1538346/18415276/ef7b4140-77f4-11e6-9056-2851c26b9122.png">

**Comment by Alhadis** [comment]
@pchaigno, @arfon : The sooner #3192 gets merged, the better.

@kissarat: As stated in the e-mail, Linguist isn't responsible for the actual syntax highlighting. Linguist only selects the grammar to be used to highlight code. In this case, the grammar that's highlighting PHP is [textmate/php.tmbundle](https://github.com/textmate/php.tmbundle). You should report this issue there.
