### ISSUE TITLE
GNU Indent profile mistaken as Prolog source

### ISSUE THREAD

**Issue by AelitaStyles** [github/linguist#3202]
Linguist mistakes [GNU indent](https://www.gnu.org/software/indent/manual/indent.html) profile files (usually named `.indent.pro`) as being Prolog source files. Here's an [example](https://github.com/AelitaStyles/libirctree/blob/master/.indent.pro) of this happening.

**Comment by pchaigno** [comment]
I'm not sure what the language of those files should be. Should we simply mark them as vendored (hidden in statistics)?

**Comment by AelitaStyles** [comment]
Possibly. That'd be the easiest solution, at any rate. It's essentially just a list of command-line flags for GNU Indent, with the additional support of C/C++ comments. Though I guess considering it's a configuration file, it'd count as "data".

**Comment by Alhadis** [comment]
Would it be inaccurate if it were lumped under the ever-nebulous banner of "INI"?

**Comment by pchaigno** [comment]
I'd prefer to avoid that, the grammar wouldn't be able to handle it and it could throw the Bayesian classifier off course.

@arfon @larsbrinkhoff Any idea for a better solution than simply marking it vendored?

**Comment by Alhadis** [comment]
Sounds like another use for the proposed `Not a language` language. =)

**Comment by larsbrinkhoff** [comment]
Or the not proposed `Just Random Data` language.

**Comment by pchaigno** [comment]
Until we get better tools to solve this issue, #3361 should mitigate it. It marks all `.indent.pro` files as vendored.
