### ISSUE TITLE
Elm language's syntax highlighting seems broken

### ISSUE THREAD

**Issue by Warry** [github/linguist#3204]
Example:

https://github.com/elm-lang/core/blob/master/src/Array.elm

This was working fine until I noticed it this morning. Any suggestion about what might go wrong?

**Comment by rtfeldman** [comment]
Yikes, and two days before elm-conf too. D:

**Comment by arfon** [comment]
Is *all* `Elm` highlighting broken? We updated the Linguist gem last night which included [some updates to the `Elm` grammar](https://github.com/github/linguist/compare/v4.8.9...fdec52c). 

Looks like some additional scopes were added in https://github.com/github/linguist/commit/adaf4011bc629060f98a63625b3706ecfe9048d4. Any ideas @pchaigno?

**Comment by rtfeldman** [comment]
@arfon yep, all Elm files appear to highlight as 190% plaintext. Same symptoms as if the grammar had been removed.

**Comment by arfon** [comment]
> @arfon yep, all Elm files appear to highlight as 190% plaintext. Same symptoms as if the grammar had been removed.

Ugh. Really sorry about this. I'll investigate and try and get a new (emergency) gem cut for Linguist tomorrow to fix this.

**Comment by pchaigno** [comment]
I introduced the bug in adaf401. #3206 should fix this.

**Comment by Alhadis** [comment]
Wait, this is all your fault?

<img src="https://cloud.githubusercontent.com/assets/2346707/18432805/7afb3daa-7927-11e6-9ec5-ba056c454a79.jpg" width="300" alt="ＡＢＳＯＬＵＴＥＬＹ ＤＩＳＧＵＳＴＩＮＧ" />

You're fired, git out.

**Comment by Warry** [comment]
I hate to bring bad news, but the fix doesn't seems to have done its magic.

**Comment by Alhadis** [comment]
... nothing's been merged yet...

**Comment by Warry** [comment]
Duh... my bad...

**Comment by pchaigno** [comment]
@Warry #3206 has been merged. This issue should be fixed with the next release of Linguist, probably soon since @arfon said tomorrow 16 hours ago (I don't know on which timeline he is currently but unless he's not in the US that should be today :smile: )

**Comment by Warry** [comment]
@pchaigno Sweet :) Thanks for the feedback, I'm sure the whole community will be happy to hear it !

**Comment by rtfeldman** [comment]
Awesome, thanks so much @pchaigno @arfon!

**Comment by arfon** [comment]
Just testing out #3212 in production: 

<img width="996" alt="screen shot 2016-09-13 at 12 57 48 pm" src="https://cloud.githubusercontent.com/assets/4483/18489272/bd54efa4-79b1-11e6-9130-d46a17480f8d.png">

**Comment by arfon** [comment]
This is now fixed. Sorry for the trouble @Warry!

**Comment by preedee136** [comment]
เมื่อ 14 ก.ย. 2016 03:02 "Arfon Smith" <notifications@github.com> เขียนว่า
