### ISSUE TITLE
SQL not being identified

### ISSUE THREAD

**Issue by haskellcamargo** [github/linguist#3210]
Repository: [DROP_PROCEDURE_IF_EXISTS](https://github.com/haskellcamargo/drop-procedure-if-exists)

The repository language is not correctly being identified. The source is SQL, and the extension also.

I've also added a `.gitattributes` in order to force it. It works when forcing to `php` or `haskell`, for example, but not for `sql`.

**Comment by pchaigno** [comment]
SQL is not counted in statistics because it's considered a data language by Linguist. We discussed (and tried to change) this behavior [several times in the past](https://github.com/github/linguist/search?utf8=%E2%9C%93&q=sql+data+programming&type=Issues).

**Comment by yangsoosong** [comment]
You can now [override](https://github.com/github/linguist/blob/master/README.md#detectable) language definitions and file paths. You just need to make sql detectable for linguist library.
Adding *.sql linguist-detectable=true in .gitattributes solved this issue for me!

**Comment by darrentu** [comment]
@yangsoosong Thanks for the information!
