### ISSUE TITLE
QBasic/QuickBasic support

### ISSUE THREAD

**Issue by jalbam** [github/linguist#3216]
Hello,

In some of my projects which use QBasic, the .bas files are detected as Visual Basic. So I edited the .gitattributes file and added the followinng line:

`*.bas linguist-language=QBasic`

This does not seem to work at all. I also tried "qbasic" (lower case), "Basic", "basic", etc. nothing seems to work so far.

Is there any way to show QBasic as the language used in GitHub (which uses Linguist)?

Thank you in advance.

**Comment by pchaigno** [comment]
Linguist doesn't have support for QBasic yet. Please see the [guidelines to add support for a new language to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). If QBasic meets the requirement on in-the-wild usage, don't hesitate to open a pull request.

**Comment by vwbusguy** [comment]
@jaboles Looks like it now shows up as "FreeBASIC", which is an improvement, but it certainly be useful to differentiate it from QB64.  It should probably be generically reported as "Quick Basic" in either case, which would certainly meet the in-the-wild usage requirement.
