### ISSUE TITLE
mIRC Scripting Language (mSL) support

### ISSUE THREAD

**Issue by jalbam** [github/linguist#3217]
Hello,

Any chances to get mSL (mIRC Scripting Language) support? Some info can be found here: https://en.wikipedia.org/wiki/MIRC_scripting_language

Thank you,
 Joan

**Comment by pchaigno** [comment]
Please see the [guidelines to add support for a new language to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). If mSL meets the requirement on in-the-wild usage, don't hesitate to open a pull request.

**Comment by Harmon758** [comment]
This has now been added with #4652 as part of [v7.7.0](https://github.com/github/linguist/releases/tag/v7.7.0).
