### ISSUE TITLE
Objective-C detected even if no Objective-C files in repo

### ISSUE THREAD

**Issue by Skylark13** [github/linguist#3222]
Hello,
My repo https://github.com/Skylark13/AVSwitcher gets flagged as containing mostly Objective-C.
The languages bar says: Objective-C 83.8% , C 13.6% , C++ 2.6%

However, if I click on the language bar to get to the Code section, on the left side, what I see is:
C++ : 8 files
C : 4 files
XML : 2 files
Markdown : 1 file
Text : 1 file

And actually, if in the language bar I click on Objective-C, I get to a page that says `We couldn't find any code matching ""` (where if I click on the C++ part of the language bar I get to a page that has the C++ files displayed already.

I could use .gitattributes to set the record straight, but from the previous paragraph I think it's actually a bug in linguist or the github web UI.

Thanks in advance.

**Comment by saxbophone** [comment]
I too have this problem with my project here: https://github.com/saxbophone/libsaxbospiral - It's all C, no Objective-C at all. The header file it is detecting as Objective-C is here: https://github.com/saxbophone/libsaxbospiral/blob/53c05689827253c973d08f9bb9609d117ada22c0/saxbospiral/serialise.h

**Comment by pchaigno** [comment]
I ran the last released version of Linguist against your repository:
```
$ linguist
81.67%  Objective-C
13.25%  C
5.08%   C++
```
Objective-C/C/C++ misclassifications are tracked at #1626.

The `We couldn't find any code matching ""` error is a caching bug. It has already been reported to support@github.com several times but you can ping them to fix your repository.
