### ISSUE TITLE
Rails mime_type.rb considered as "E"?

### ISSUE THREAD

**Issue by siegy22** [github/linguist#3226]
Hey!

Why is [this file](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/http/mime_type.rb) considered as "E"?

See the screenshots how I got this:

On the rails repo:
<img width="996" alt="screen shot 2016-09-16 at 12 13 54" src="https://cloud.githubusercontent.com/assets/8779283/18582808/3d8edf0c-7c07-11e6-90f2-d19e8741f347.png">

And by clicking the "E":
<img width="991" alt="screen shot 2016-09-16 at 12 14 03" src="https://cloud.githubusercontent.com/assets/8779283/18582807/3d8e35d4-7c07-11e6-8fbe-a322ba70788c.png">

**Comment by Alhadis** [comment]
That would be because of this line, here:

```rb
# -*- frozen-string-literal: true -*-
```

The current Emacs modeline is a little buggy and needs fixing... I'm currently working on that, actually.

You can fix this issue by moving the modeline to the bottom of the file, as Linguist only scans the first five lines to look for a modeline.

**Comment by siegy22** [comment]
Okay, but when I replace it with `# frozen_string_literal: true` it should work right?

**Comment by Alhadis** [comment]
Yes. It's the `-*-` parts that're telling Linguist it's an Emacs modeline.

**Comment by arthurnn** [comment]
This seems like a bug indeed.

**Comment by Alhadis** [comment]
Don't worry, I'm revising the modeline regex as we speak. :)

**Comment by Alhadis** [comment]
@arthurnn Done. #3227 will fix this as well as a [similar issue](https://github.com/github/linguist/issues/3018) reported previously.

**Comment by Alhadis** [comment]
@pchaigno, this can be closed, because [everything's fixed](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/http/mime_type.rb). =)

Note the refreshing absence of "E" in the [language breakdown](https://github.com/rails/rails/search?l=ruby).

**Comment by pchaigno** [comment]
Thanks @siegy22 for reporting the issue! Thanks @Alhadis for fixing it :+1:
