### ISSUE TITLE
Linguist misclassifying scidavis project

### ISSUE THREAD

**Issue by highperformancecoder** [github/linguist#3231]
See https://github.com/highperformancecoder/scidavis

Linguist states that 69.2% of the code is Typescript. There is no typescript code in the scidavis codebase, and clicking on the typescript icon for more detail brings up blank.

The project is predominantly C++ in fact.

**Comment by larsbrinkhoff** [comment]
Hello @highperformancecoder,

This has been corrected in the current version of Linguist, but the fix has not been released and deployed yet.

**Comment by Alhadis** [comment]
Wait, what exactly caused the misclassification?

**Comment by larsbrinkhoff** [comment]
I don't know.  I just ran v4.8.9 and current and saw that it was fixed.  One might suspect 6763b73 has something to do with it.

**Comment by pchaigno** [comment]
The fix was shipped in v4.8.10, the statistics should update with the next push to the repository. Alternatively, you can ask GitHub support to manually update them.
