### ISSUE TITLE
Dashes in HTML comments should not be highlighted as an error

### ISSUE THREAD

**Issue by zcorpan** [github/linguist#3232]
Example:

    ```html
    <!--------------------------------->
    ```

->

```html
<!--------------------------------->
```

should be without error syntax highlight; see https://github.com/whatwg/html/issues/1351

**Comment by zcorpan** [comment]
See https://github.com/whatwg/html/pull/1356#issuecomment-222793570 for test cases

**Comment by Alhadis** [comment]
Linguist only selects the grammars that provide syntax highlighting on GitHub. For HTML, highlighting is provided by [textmate/html.tmbundle](https://github.com/textmate/html.tmbundle). You're better off filing an issue there.

**Comment by zcorpan** [comment]
OK thanks!
