### ISSUE TITLE
VCRpy cassettes are not recognized

### ISSUE THREAD

**Issue by jseabold** [github/linguist#3239]
The ruby project provides different information in the cassettes than the Python project. As such, cassettes generated with the pyhon version of VCR do not get identified by the code here.

Would be great to work the vcrpy developers to find a solution.

Incidentally, should file diffs be suppressed regardless if they are new or changes? I haven't been able to suppress the former for the VCRpy cassettes and am not sure what exactly I've done wrong.

https://github.com/kevin1024/vcrpy/issues/273

**Comment by pchaigno** [comment]
Please see the [guidelines to add support for a new language to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). If VCRpy meets the requirement on in-the-wild usage, don't hesitate to open a pull request.
