### ISSUE TITLE
can i make a pr of a new syntax?

### ISSUE THREAD

**Issue by jarriztg** [github/linguist#3257]
We have a new language in github, but i cant create my own colors of syntax

**Comment by pchaigno** [comment]
What's the language? Is it already recognized by Linguist?

**Comment by Alhadis** [comment]
I think he means that he's made a new language called "Sintaxis", and he wants to apply syntax highlighting to it on GitHub.

@jarriztg, is this correct?

**Comment by jarriztg** [comment]
https://github.com/primitivorm/latino
Here can i add my sintax? haha

**Comment by pchaigno** [comment]
To add syntax highlighting for a language, you first need to add support for that language in Linguist. Please see the [guidelines to add support for a new language to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). If your language meets the requirement on in-the-wild usage, don't hesitate to open a pull request.
