### ISSUE TITLE
Syntax highlighting after \" in Clojure

### ISSUE THREAD

**Issue by Mikechaos** [github/linguist#3260]
Hi,

There is already an issue [here](https://github.com/github/linguist/issues/1819)
This refers to an issue on [language-clojure](https://github.com/atom/language-clojure/issues/11). The issue was said to be fixed more than a year ago, but I am still seeing it in [this project](https://github.com/Mikechaos/Pragmatic-Programmer-Exercices/blob/master/Ex6-BNF-Interpreter/ex-6-draft.clj#L81).

Would it be a regression, or was the fix never pulled in?

Thank you!

**Comment by pchaigno** [comment]
@Mikechaos Thanks for reporting this issue!

It appears to be a regression in language-clojure. I filed a fix at atom/language-clojure#55.
We'll pull automatically it with the next release of Linguist after its merged.

**Comment by pchaigno** [comment]
Fixed upstream. Should be fixed on github.com with the next release of Linguist.
