### ISSUE TITLE
document local installation of linguist

### ISSUE THREAD

**Issue by nathany** [github/linguist#3261]
https://github.com/github/linguist/blob/master/CONTRIBUTING.md#testing says to run `script/bootstrap`, but the build fails due to missing dependencies.

on macOS Sierra, it was necessary to run:

```
brew install icu4c cmake 
```

**Comment by lildude** [comment]
I think we can close this issue now. Docs have been updated to make it clearer as to how Linguist works and the search gotcha. Feel free to open a new issue if docs need further clarification.
