### ISSUE TITLE
Bootstrap Sass and Font Awesome directories are not picked up by vendor.yml

### ISSUE THREAD

**Issue by sahat** [github/linguist#3263]
[Hackathon Starter](https://github.com/sahat/hackathon-starter) (Node.js boilerplate) is misclassified as a CSS repository.

If I am not mistaken, the current Bootstrap regex only filters out individual files like `bootstrap.css|less|scss|styl` instead of `bootstrap/**/*.scss|css|less|styl`. Same goes for the font-awesome package.

I am no expert with regular expressions, so perhaps someone could submit a PR?

**Comment by sahildua2305** [comment]
@sahat [This](https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml#L57) should match `bootstrap/**/*.scss|css|less|styl` as well.

**Comment by pchaigno** [comment]
The `59.6% CSS` comes from the following files:
```
public/css/lib/font-awesome/_animated.scss
public/css/lib/font-awesome/_bordered-pulled.scss
public/css/lib/font-awesome/_core.scss
public/css/lib/font-awesome/_fixed-width.scss
public/css/lib/font-awesome/_icons.scss
public/css/lib/font-awesome/_larger.scss
public/css/lib/font-awesome/_list.scss
public/css/lib/font-awesome/_mixins.scss
public/css/lib/font-awesome/_path.scss
public/css/lib/font-awesome/_rotated-flipped.scss
public/css/lib/font-awesome/_screen-reader.scss
public/css/lib/font-awesome/_stacked.scss
public/css/lib/font-awesome/_variables.scss
public/css/main.scss
public/css/themes/default/_default.scss
public/css/themes/default/_variables.scss
public/css/themes/flatly/_flatly.scss
public/css/themes/flatly/_variables.scss
public/css/themes/ios7/_ios7.scss
public/css/themes/modern/_modern.scss
public/css/themes/modern/_variables.scss
```
You might want to look at [Linguist overrides](https://github.com/github/linguist#overrides) to ignore these files in statistics.
