### ISSUE TITLE
Ruby being detected where there is no Ruby

### ISSUE THREAD

**Issue by strawberryentrypoint** [github/linguist#3265]
[My repository](https://github.com/strawberryentrypoint/libstrawberry) has a couple of Shell scripts which, if containing the license, makes my repository report that it contains Ruby code (while it does not, to my knowledge).

I'm guessing this is a bug, not a feature.

Removing the license fixes the problem.
Moving the license around does not seem to fix the problem.
Adding ```*.sh linguist-language=Shell``` to ```.gitattributes``` does not either.

**Comment by Alhadis** [comment]
Most definitely a bug, especially since clicking [Ruby](https://github.com/strawberryentrypoint/libstrawberry/search?l=ruby) brings up nothing.

@arfon, do you know if this is related to #3256?

**Comment by strawberryentrypoint** [comment]
[Search results for Ruby](https://github.com/strawberryentrypoint/libstrawberry/search?l=ruby) just started showing that [my license template](https://github.com/strawberryentrypoint/libstrawberry/blob/master/libstrawberry/doc/FileLicenseTemplate.spec) was the cause.

I added `*.spec linguist-documentation=true` to my `.gitattributes` file, which seems to have fixed the issue.

Thank you for your time.

**Comment by Alhadis** [comment]
You can also fix the highlighting by using an Emacs modeline. :) Just put this in the first or last five lines of each incorrectly-hinted file:

```
-*- language-name -*-
```

Replacing `language-name` with [whatever language](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml) it's supposed to be.
