### ISSUE TITLE
Wrong classification of Jupyter notebook vs Python

### ISSUE THREAD

**Issue by mayou36** [github/linguist#3282]
Hey all,

My repository consists of ~ 5'000 lines of python code and ~500-1000 of Jupyter notebooks (which just serve as an example).
First of all, it seems as if one of my notebooks is not recognized at all (the reweighting). 
Second, it is marked as 80% Jupyer notebooks and 20% Python. This is probably the ratio of the filesizes, but does definitely not reflect the true composition.

Best,
Mayou

**Comment by Alhadis** [comment]
You can use `.gitattributes` to mark the files as documentation, so they'll be excluded from language statistics.

```
.ipynb linguist-documentation
```

More info on that [here](https://github.com/github/linguist#using-gitattributes).

**Comment by mayou36** [comment]
Ok, I can do that. Actually, I still think the problem is not solved in its core: If the algorithm classifies a language as 80% of the package whereas (in lines of code) it is only 20% of it, it seems wrong somehow (even dough the size may is distributed like that)

Anyway, the first thing is that a Jupyter Notebook is not recognized at all (the reweight.ipynb). This is the repo: https://github.com/mayou36/raredecay.

**Comment by pchaigno** [comment]
Actually, `reweight.ipynb` is recognized (and counted) as Jupyter Notebook by Linguist. Here's the complete breakdown:
```
$ linguist --breakdown
83.61%  Jupyter Notebook
16.39%  Python

Jupyter Notebook:
howto/.ipynb_checkpoints/Data Storage-checkpoint.ipynb
howto/.ipynb_checkpoints/data_storage-checkpoint.ipynb
howto/.ipynb_checkpoints/reweighting-checkpoint.ipynb
howto/IO_handling_and_settings.ipynb
howto/data_storage.ipynb
howto/reweighting.ipynb

Python:
raredecay/__init__.py
raredecay/analysis/__init__.py
raredecay/analysis/ml_analysis.py
raredecay/analysis/physical_analysis.py
raredecay/globals_.py
raredecay/meta_config.py
raredecay/run_config/__init__.py
raredecay/run_config/config.py
raredecay/settings.py
raredecay/tools/__init__.py
raredecay/tools/data_storage.py
raredecay/tools/data_tools.py
raredecay/tools/dev_tool.py
raredecay/tools/estimator.py
raredecay/tools/metrics.py
raredecay/tools/output.py
setup.py
```
I think it's not shown in the search results because of recent cache issues. You can report it to support@github.com; it's unfortunately not something that can be fixed in Linguist.

As for how the language statistics are computed, I agree that it's not perfect. Alternatives have been discussed before (#2139) but we haven't found a clearly better solution yet :/

**Comment by mayou36** [comment]
Ok, then everything's clear to me, thanks for your investigation!
