### ISSUE TITLE
Language stats bar percentage calculation incorrect

### ISSUE THREAD

**Issue by mbmccormick** [github/linguist#3283]
The Language stats bar on my [mbmccormick/purdue](https://github.com/mbmccormick/purdue) repo does not seem to be calculating correctly:

![image](https://cloud.githubusercontent.com/assets/377537/19450934/399c846e-9460-11e6-9530-1e0a32565bca.png)

When I click on the LLVM link, I only get 6 results totaling 1,086 lines. When I click on the C link, I get over 1,400 results each at 100s or 1000s of lines. Yet LLVM is ranked at 58.3% and C is only at 19.4%. This calculation seems to be way off. Am I doing something wrong?

**Comment by pchaigno** [comment]
Looks like the search results are not up-to-date (we've been having a lot of caching issues lately, you can report it to support@github.com). Linguist detects 8 LLVM files, one of which has more than 200k lines:

Number of lines | File
---|---
202332 | cs490st/project03/gnupg-1.0.5/build/klee-out-0/assembly.ll
     184 | cs490st/project03/klee-out-0/assembly.ll
     184 | cs490st/project03/klee-out-1/assembly.ll
     184 | cs490st/project03/klee-out-2/assembly.ll
     193 | cs490st/project03/klee-out-3/assembly.ll
   19706 | cs490st/project03/p2/klee-out-0/assembly.ll
      74 | cs490st/project03/p2/klee-out-1/assembly.ll
      66 | cs490st/project03/p2/klee-out-2/assembly.ll
  222923 | **total**

**Comment by pchaigno** [comment]
You can mark those files as vendored using [Linguist overrides](https://github.com/github/linguist#overrides).

**Comment by mbmccormick** [comment]
Thanks, that explains it!
