### ISSUE TITLE
Single quote inside heredoc causes remainder of file to be rendered as string

### ISSUE THREAD

**Issue by cdown** [github/linguist#3290]
Currently this is still considered a string opening quote, even though it doesn't act as one

```bash
cat << EOF
test ' test
EOF
echo foo bar
# Note that these are still highlighted as if they were a string
```

I'll take a look at fixing this when/if I have time, but otherwise I think this is worth fixing anyway.

**Comment by cdown** [comment]
Looks like this is a bug in https://github.com/atom/language-shellscript, judging by the grammars file.

**Comment by Alhadis** [comment]
@cdown You can close this, because this is an upstream issue. When/if it gets fixed, Linguist will pick the latest changes up automatically at the next release.

**Comment by cdown** [comment]
Yeah, sure.
