### ISSUE TITLE
Misclassified language statistics

### ISSUE THREAD

**Issue by austintoddj** [github/linguist#3293]
My project, [Canvas](https://github.com/austintoddj/canvas), is a Laravel application primarily written in PHP. The GitHub statistics however show CSS as being 49% of the project even though I've manually vendored the files in question in `.gitattributes`. Is there something else I should be doing to show PHP as the primary language of the repository? Thanks!

**Comment by Alhadis** [comment]
Include [these as vendored](https://github.com/austintoddj/canvas/search?l=css) in your `.gitattributes` file too.

There're only three CSS files, but the combined weight of them is what's skewing the language stats.

**Comment by Alhadis** [comment]
I'd say the results might be cached... If you push an update to any of the vendored directories, it might force a refresh.

Otherwise, it *should* be excluded.

**Comment by austintoddj** [comment]
@Alhadis Thanks, I'll try and push an update to one of those directories and close this out as soon as the change happens.

**Comment by austintoddj** [comment]
Hm, still no changes when I push or try to force refresh GitHub's cache.

**Comment by arfon** [comment]
> Hm, still no changes when I push or try to force refresh GitHub's cache.

This usually 'fixes' itself in < 24 hours. Let's wait this out a little longer 😄

**Comment by austintoddj** [comment]
@arfon Any idea why 24 hours would not have been enough to clear GitHub's statistics cache? Repo still showing CSS as the primary language when the specific files have been vendored.

**Comment by Moberstein** [comment]
We have a similar issue with [this project](https://github.com/JVMerkle/mMio/tree/playground), also a Laravel project. There are only three small JavaScript files but it is shown as 87%, also adding a `*.js` filter to [`.gitattributes`](https://github.com/JVMerkle/mMio/blob/playground/.gitattributes) doesn't seem to exclude the files from the statistics.

**Comment by austintoddj** [comment]
Ended up deleting the `.gitattributes` file, adding it again, and everything started working properly.

**Comment by pchaigno** [comment]
@Moberstein Only the `.gitattributes` on the `master` branch will impact statistics. And statistics are only computed for the `master` branch anyway.

**Comment by Moberstein** [comment]
Well, thanks! Didn't thought about that, updating the correct '.gitattributes' helped.

**Comment by yangsoosong** [comment]
Adding `*.sql linguist-detectable=true` in `.gitattributes` solved this issue for me!
