### ISSUE TITLE
jlord/git-it-electron have strange languages list

### ISSUE THREAD

**Issue by lubien** [github/linguist#3298]
https://github.com/jlord/git-it-electron

![](http://i.imgur.com/krpgDwe.png)

Even tho the repo only contains js, css and html.

**Comment by arfon** [comment]
Try clicking some of those languages. The Perl one will take you to https://github.com/jlord/git-it-electron/search?l=perl which shows there's lots of vendored Perl in the project.

**Comment by lubien** [comment]
My fault
