### ISSUE TITLE
Incorrectly classifying TeX files as OpenEdge ABL

### ISSUE THREAD

**Issue by Ho-Holic** [github/linguist#3299]
[This file](https://github.com/Ho-Holic/meta/blob/717b54908e82bbeced5a5d1f4a2222a88f28ef9f/cv-rus/curricula-vitae.cls) is valid TeX class file, but it has OpenEdge ABL 43.2%

**Comment by jwnorman** [comment]
Classifying either [a .txt (tsv) file or a Python pickled file](https://github.com/jwnorman/glamour_profession/tree/master/relevant_words/data) as OpenEdge ABL. I'll use a Linguist override, but I thought I'd document this here in case it's helpful.

**Comment by Alhadis** [comment]
No access. Is it a private repository?

**Comment by jwnorman** [comment]
Oops, duh, yeah I'm sorry it is.

Head of the txt file:
```
AA	AA	rough, cindery lava [n -S]	41		b	hls
ABRACADABRA	AAAAABBCDRR	[n -S]	16880			s
ABRACADABRAS	AAAAABBCDRRS	ABRACADABRA [n]	11985
ANAGRAMMATICAL	AAAAACGILMMNRT	[adj]	4852
ARCHAEBACTERIA	AAAABCCEEHIRRT	ARCHAEBACTERIUM [n]	4085
BACCALAUREATES	AAAABCCEELRSTU	BACCALAUREATE [n]	3846
```

Head of the first pickled file:
```
ccollections
defaultdict
p0
(c__builtin__
list
p1
tp2
Rp3
S'DISPLAYERS'
p4
```

Head of the second pickled file:
```
ccollections
defaultdict
p0
(c__builtin__
list
p1
tp2
Rp3
S'SHAGS'
p4
```
