### ISSUE TITLE
Files with 'vendor' in the path seem to be getting suppressed in pull request diffs

### ISSUE THREAD

**Issue by soul2197** [github/linguist#3300]
This seems to be a recent change, and now it seems like anything with `vendor` appearing anywhere in the url seems to be getting suppressed.

![screen shot 2016-10-27 at 3 02 23 pm](https://cloud.githubusercontent.com/assets/510009/19787226/85949ae8-9c56-11e6-806f-92e59f9280a7.png)

Is this an intentional change? Is this the right place to report this issue?

**Comment by arfon** [comment]
Hi @soul2197. This should be fixed now. Can you confirm? If not, could you link to a diff that demonstrates this issue?

**Comment by soul2197** [comment]
@arfon seems good now. thanks for the quick fix!
