### ISSUE TITLE
Pascal: missed n keywords on hiliting

### ISSUE THREAD

**Issue by Alexey-T** [github/linguist#3301]
- std word "override" not hilited: (not keyword, special one)
~~~Pascal
     procedure Paint2; override;
     procedure PaintSection(Index: Integer); virtual;
~~~

- words "read"/"write" good to hilite too, if they have lowercase:
~~~Pascal
property DragReorder: boolean read FDragReorder write FDragReorder;
~~~
(read/write means getter, setter)

**Comment by Alexey-T** [comment]
"exit" is special word, need to hilite too:
~~~Pascal
  if key=2 then
  begin
    key:= 0;
    exit
  end;
~~~

**Comment by arfon** [comment]
👋 @Alexey-T. Thanks for filing these bug reports with the syntax highlighting. 

All of our syntax highlighting on GitHub is controlled by upstream dependencies (see https://github.com/github/linguist/tree/master/vendor/grammars) so you'll need to report the problems on these repositories, not here.

When grammars are updated we automatically incorporate the updates in Linguist during our build process.
