### ISSUE TITLE
C: wrong hiliting of string

### ISSUE THREAD

**Issue by Alexey-T** [github/linguist#3303]
1st str not hilited correctly:
~~~C
#error "dddd \
    edddd \
    "
#warning This is a short warning
/* <- keyword.control.import */
#endif
 /* <- keyword.control.import */
~~~

**Comment by arfon** [comment]
👋 @Alexey-T. Thanks for filing these bug reports with the syntax highlighting. 

All of our syntax highlighting on GitHub is controlled by upstream dependencies (see https://github.com/github/linguist/tree/master/vendor/grammars) so you'll need to report the problems on these repositories, not here.

When grammars are updated we automatically incorporate the updates in Linguist during our build process.

**Comment by pchaigno** [comment]
@Alexey-T For C, github.com uses [textmate/c.tmbundle](https://github.com/textmate/c.tmbundle/tree/936e4347d22d1a821588551ca8f7e960c1242120). You might want to check first that there isn't already an issue for that.
