### ISSUE TITLE
What repos?

### ISSUE THREAD

**Issue by Alexey-T** [github/linguist#3304]
i found repo for C#: is it correct for GH? https://github.com/atom/language-csharp/tree/daf3fe2d64d7e9892836fdf7e1bf509f8b8bfbdf

i found repo Pascal: correct? https://github.com/textmate/pascal.tmbundle/tree/3b11b782368065e55acce0423f385722771d28b0

where's repo  for C?

**Comment by Alhadis** [comment]
[C is here](https://github.com/textmate/c.tmbundle).

@arfon Just a reminder [this](https://github.com/github/linguist/pull/3192) is still sitting open.. =)

**Comment by pchaigno** [comment]
> i found repo for C#: is it correct for GH? https://github.com/atom/language-csharp/tree/daf3fe2d64d7e9892836fdf7e1bf509f8b8bfbdf
i found repo Pascal: correct? https://github.com/textmate/pascal.tmbundle/tree/3b11b782368065e55acce0423f385722771d28b0

That's correct.

> [C is here](https://github.com/textmate/c.tmbundle).

:+1:

**Comment by nowen094** [comment]
Hi could you please kindly help me out Iam new to this coding and I do OK
with some but other stuff Iam just stupider than well you know so it would
be great if you might be in to kindly explaining bit of this to me thanks

**Comment by nowen094** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Nicola

Confirm that you know Nicola: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=LS3SOVcy&invitationId=6206354359350018048&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eivrp9no9%7Egp








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ivrp9no9-gp&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGqNgJ_SKUVhgAAAViFml6PTrGOQErt1Su_CtxHKUk8R6VONdlKwtHjIE_WG_FagS_u4AM7FD-0KUIw2MDSyyu04BxPxfC3cwnj9GuU63G00s8uwHnBvWYKIqEnn1xUjXVfYzHG_dRb_0bzDsfO4vAdL-K8QH6RjqhJTXBX41U3kG4FO7JbhkQpnwGswJI6SgCS&eid=0-ivrp9no9-gp


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ivrp9no9-gp&a=customerServiceUrl&ek=invite_guest

© 2016 LinkedIn Corporation, 1000 West Maude Avenue, Sunnyvale, CA 94085. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
