### ISSUE TITLE
coq-contribs is reported incorrectly

### ISSUE THREAD

**Issue by siddharthist** [github/linguist#3305]
[This repo](https://github.com/coq-contribs/coq-contribs) has no source files, just markdown, which is incorrectly read as "GCC Machine Description"

**Comment by larsbrinkhoff** [comment]
Strange, the heuristic returns Markdown, but linguist still thinks they are GCC.  I'll investigate.

**Comment by pchaigno** [comment]
@larsbrinkhoff It doesn't match the heuristic rule for me. I tested with the last release of Linguist and the last dev version.

Also, I'm not sure I understand the Markdown heuristic rule: `/(^[-a-z0-9=#!\*\[|])|<\//i`. Does that mean GCC Machine Description can never begin with `[-a-z0-9=#!\*\[|]`? Would it still be correct if we add indentation in that regular expression: `/(^\s*[-a-z0-9=#!\*\[|])|<\//i`?

**Comment by larsbrinkhoff** [comment]
@pchaigno The intent is that the heuristic should err on the side of Markdown.  GCC files usually only have `;` or `(define` at the start of a line.  `-`, `a`-`z`, `0`-`9`, `=`, `#`, `!`, `*`, `[`, `|`, and `]` at the start of a line indicates Markdown.

I haven't considered indentation.

**Comment by Alhadis** [comment]
Looks like an easy fix then!

Note: Quantifiers have no meaning inside a character class, so it's safe to write `[*]`, not `[\*]`. ;)

**Comment by pchaigno** [comment]
> I haven't considered indentation.

Should I go ahead then (or are any of you already on it)?

**Comment by Alhadis** [comment]
I'm busy working File-Icons v2 (for the second time, first attempt sucked) so, go ahead! 👍

**Comment by larsbrinkhoff** [comment]
As we can see here: https://github.com/coq-contribs/coq-contribs/search?l=gcc-machine-description
two of the `.md` files are recognized correctly, and only `TODO.md` is recognized as GCC.  Yet, the repository is classified as 100% GCC.  Why is that?

@pchaigno Sure, if you figure something out, go ahead.  GCC files can have pretty much anything after initial indentation.

**Comment by larsbrinkhoff** [comment]
Ah, of course Markdown doesn't count towards repository language statistics.

**Comment by Alhadis** [comment]
That's mark**up** you're thinking of. ;)

**Comment by pchaigno** [comment]
@siddharthist I have a fix ready for this and I'd like to use your `TODO.md` for our test set. Any chance you could add a [LICENSE file](http://choosealicense.com) to the repository so that I can use it?

**Comment by siddharthist** [comment]
@pchaigno It's not my repo - maybe make an issue?

**Comment by larsbrinkhoff** [comment]
@pchaigno Has this stalled?

**Comment by Caged** [comment]
👋  It looks like the original repository is no longer mistakenly classified (or classified at all).  Can someone clarify if this is still an issue?

**Comment by siddharthist** [comment]
@Caged I think that's appropriate, as it doesn't contain any code.
