### ISSUE TITLE
In language fence for markdown mutliparagraph list items do not keep order but default to 1.

### ISSUE THREAD

**Issue by Dbz** [github/linguist#3309]
Hello,

List items with paragraphs between them all default to starting at `1.` when in a markdown code fence. A great feature of markdown is able to start all list items with the same number (`1.`) in order to make editing your document and moving around list items easy. However, when fenced, the markdown will not show correctly even though it works properly outside of the fence. See this example markdown:

``` markdown

1. First item

  paragraph of text   

1. Second item

  paragraph of text
```

Each item is defaulted to `1.` even though the second item should be `2.`

This is how the same markdown actually renders:

1. First item

  paragraph of text   

1. Second item

  paragraph of text

**Comment by Alhadis** [comment]
Fenced code-blocks don't exist for presentational purposes: they're for depicting source code verbatim, exactly as the author wrote it. Processing Markdown in such constructs runs counter to the idea of **preprocessed** text.

**Comment by Dbz** [comment]
That makes perfect sense, thank you!
