### ISSUE TITLE
a question about license of samples

### ISSUE THREAD

**Issue by matej-kosik** [github/linguist#3313]
Hi,

I have noticed that you include [some files](https://github.com/github/linguist/tree/master/samples/Coq) from [Coq's standard library](https://github.com/coq/coq/tree/trunk/theories).

Your [README.md](https://github.com/github/linguist/blob/ec562138f8302a1b50c8bcf17ea4fe2be070b64d/README.md) file currently says:

> All other files are covered by the MIT license

Are you sure you can re-release [those files](https://github.com/github/linguist/tree/master/samples/Coq) under different license than then [original one](https://github.com/coq/coq/blob/trunk/LICENSE)?

**Comment by Alhadis** [comment]
> 		  GNU LESSER GENERAL PUBLIC LICENSE
>		       Version 2.1, February 1999

Jesus. How'd that one slip by?

Gonna nuke that into orbit.

**Comment by Alhadis** [comment]
I'd really love to know which wrong turn in life lead to me looking up Coq on GitHub.

I know what the word means in French, but that isn't making this scenario any less awkward.

Asking for @pchaigno to take over in 10... 9... 8...

**Comment by Alhadis** [comment]
@matej-kosik, thanks for bringing this to our attention. These should have been removed long ago, but the removal of the copyright headers caused them to slip beneath our notice. This will be resolved in #3314.

**Comment by matej-kosik** [comment]
You are welcome.

**Comment by arfon** [comment]
Fixed in #3314. Thanks for flagging this @matej-kosik and thanks for fixing this @Alhadis
