### ISSUE TITLE
Issue with my Europe Localization Menu saying HTML instead of Javascript 

### ISSUE THREAD

**Issue by GiorgioMaroki** [github/linguist#3317]
Issue with my Europe Localization Menu saying HTML instead of Javascript (Most of the code is Javascript inside the HTML file though). How do I switch it to Javascript?

**Comment by pchaigno** [comment]
The HTML code comes from [this file](https://github.com/GiorgioMaroki/Europe-Localization-Menu/blob/6d839454fce46eed7db4513e3e3f6b1e89a854db/index.html). You might want to use [Linguist overrides](https://github.com/github/linguist#overrides).
