### ISSUE TITLE
Files ignored for language classification

### ISSUE THREAD

**Issue by CodingAnarchy** [github/linguist#3322]
I have some Brainfuck files in my repository [here](https://github.com/CodingAnarchy/bf-compile).  At first blush, it would be enough to make this be a Brainfuck repository, but it doesn't appear to recognize these files at all.

Nor does the `.gitattributes` file included in the repository change this, which was an attempt to override it.

**Comment by Alhadis** [comment]
Well, the files [are being indexed correctly](https://github.com/CodingAnarchy/bf-compile/search?l=Brainfuck), so at a guess, I'd say the language-bar's cached an old version of the codebase's stats. If you push a change to one of the source files (even trivial), it should force a refresh. =)

**Comment by CodingAnarchy** [comment]
Huh, didn't expect that.  Looks like that fixed it.  Thanks!
