### ISSUE TITLE
Mark file as generated in .gitattributes

### ISSUE THREAD

**Issue by bradynpoulsen** [github/linguist#3324]
I have been trying to test the use of `linguist-vendored` and `binary` and `-diff` to suppress the diffs of select files. I cannot get them to be ignored.

This is my test PR I am using to try it out bradynpoulsen/linguist-test#1

I propose we add support for `linguist-generated` in the `.gitattributes` file that will mark the file as generated in the [`Linguist::Generated#generated?`](https://github.com/github/linguist/blob/master/lib/linguist/generated.rb#L53-L81) checks.

**Comment by Alhadis** [comment]
Hey @bradynpoulsen,

This is a known issue on GitHub's end, I'm afraid. See #2206.

Since this is a duplicate issue, I'll close this, but I recommend subscribing to the aforementioned issues for updates.
