### ISSUE TITLE
PRU assembly misidentified as OpenEdge ABL

### ISSUE THREAD

**Issue by sv3** [github/linguist#3330]
[relevant files in my repo](https://github.com/sv3/freq/search?l=openedge-abl)
The same mis-identification occurs [here](https://github.com/beagleboard/am335x_pru_package/search?l=openedge-abl) (among other places)

The code is assembly for a TI PRU (Programmable Realtime Unit)
[TI PRU assembly reference](http://processors.wiki.ti.com/index.php/Programmable_Realtime_Unit_Software_Development)

**Comment by Alhadis** [comment]
Hey @sv3,

You can add a [`.gitattributes` file](https://github.com/github/linguist#using-gitattributes) to your repository to correct the language classification:

```
*.p linguist-language=TI Program
```

**Comment by Alhadis** [comment]
@scottmangiapane Do you know much about the `.p` file extension's usage in TI programs? Is it common enough to consider registering as a TI extension?

Or should this actually be regarded as a different language altogether? You said in [#3258](https://github.com/github/linguist/pull/3258#issuecomment-251463948) that there were no "official" file extensions, but the ones listed in [PRU's wiki](http://processors.wiki.ti.com/index.php/PASM_Syntax_Highlighting) sound fairly concrete:

> Note that by default, only files with the extensions `.pru`, `.hpru`, or `.pasm` are treated as PASM syntax files (`filetype=pru`).
> Specify which files are members of that class. (`*.p`,`*.hp`,`*.pdsp`,`*.pasm`)

I'm starting to get the impression "PRU assembly" is different from "TI Program" assembly... could you elucidate?

**Comment by scottmangiapane** [comment]
Hey @Alhadis, unfortunately I have never heard of a '.p' extension in TI programs. There's three different kinds of Ti-84 languages: z80 assembly, Axe Parser, and TI-BASIC. TI-BASIC is always in the form '.8xp', Axe source code is '.8xp', and both Axe source and z80 source can be compiled into '.8xp' or '.8xk'. I've only written TI-BASIC and Axe though, so I'm not sure how the z80 assembly compiling process works or what the source files for it look like 

But I did a quick Google search, and it looks like these are actually for a different device! "TI PRU (Programmable Realtime Unit)" looks more like a Raspberry Pi than a TI-84. Probably best to label them as "PRU assembly" in my opinion.

**Comment by Alhadis** [comment]
Alright, thanks!

@sv3 This sounds like it should be classified as assembly, so I've updated my original answer. If you feel PRU assembly is widespread enough to warrant classification, please don't hesitate to send us a pull request. You can find more information about adding a language [here](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language).

**Comment by sv3** [comment]
That works for me! Thank you guys for your quick response.

**Comment by Alhadis** [comment]
No problem! :-) Glad to help!
