### ISSUE TITLE
.editorconfig files not recognized

### ISSUE THREAD

**Issue by tomlutzenberger** [github/linguist#3331]
A project of mine (https://github.com/tomlutzenberger/coding-guideline-collection) consists of dotfiles over 80%, mainly `.editorconfig` and some JSON Files (Linter config).
As language the repo shows, well... nothing.

Is there a reason why no languages are displayed at all? As the [samples directory](https://github.com/github/linguist/tree/master/samples/INI/filenames) says, they should be displayed as INI files.

**Comment by Alhadis** [comment]
Hey @tomlutzenberger,

Certain languages are excluded from the language statistics bar. Languages on GitHub fall into one of [four distinct classifications](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L3):

* **Prose:** Material intended to be consumed by a human reader, with little to no processing
* **Markup:** Material intended to be presented to a reader after being processed or parsed by a program
* **Programming:** Material with instructions designed to be interpreted or compiled by software
* **Data:** Virtually anything that doesn't fit into the above

INI files are classed as `data`, while the statistics bar only considers languages that fall under `markup` or `programming`.

**Comment by tomlutzenberger** [comment]
Hi @Alhadis, thanks for your feedback.

IMO, INI files (or configuration files in general) should be classified as *Programming* as they get intrepreted by software. They don't contain data like e.g. JSON files.

**Comment by Alhadis** [comment]
INI files aren't executable source code, so they clearly don't fall under the category of `programming`. They *do* contain data in the form of values or configuration variables to be consumed elsewhere.

As I feel I've addressed your question, I'm closing this. Please contact GitHub support if you have any further questions or feedback.

**Comment by tomlutzenberger** [comment]
I already contacted GitHub support and they refered me to this repo.
Do I have any chance to fix this by myself?

**Comment by Alhadis** [comment]
I'm afraid not. There isn't any way to include excluded languages, only the other way around.

**Comment by tomlutzenberger** [comment]
OK, I see 😞 
Thanks though.
