### ISSUE TITLE
github license detection for Apache-2

### ISSUE THREAD

**Issue by alexjfisher** [github/linguist#3334]
Firstly, I hope I'm raising this issue against the correct project! :)

The appendix of the [apache 2 license](http://www.apache.org/licenses/LICENSE-2.0.txt) explains how to apply the license to your work.

> APPENDIX: How to apply the Apache License to your work.

      To apply the Apache License to your work, attach the following
      boilerplate notice, with the fields enclosed by brackets "[]"
      replaced with your own identifying information. (Don't include
      the brackets!)  The text should be enclosed in the appropriate
      comment syntax for the file format. We also recommend that a
      file or class name and description of purpose be included on the
      same "printed page" as the copyright notice for easier
      identification within third-party archives.

If you follow these instructions and include just the boilerplate as directed, github won't detect the license.  It'd be great if this could be fixed.  Here's one example https://github.com/puppetlabs/puppet-agent picked at random.

Many thanks.

**Comment by pchaigno** [comment]
@alexjfisher github.com uses [Licensee](https://github.com/benbalter/licensee) to detect licenses of projects. You should open an issue there if there isn't already one.

**Comment by Alhadis** [comment]
... oh yeah. Whoops.

Uhm, what he said.

<img src="http://i3.kym-cdn.com/photos/images/newsfeed/000/698/489/2f7.png" width="300" alt="hurrrr" />

**Comment by alexjfisher** [comment]
@pchaigno Thanks.  I wasn't too sure this was the correct place, but had been directed here after attending this [excellent talk](https://www.devopsdays.org/events/2016-berlin/program/johannes-nicolai/) yesterday.

Looks like there is already an open issue where it's being discussed. https://github.com/benbalter/licensee/issues/103

@jonico Thanks for your talk.  It was one of the best of the conference!
