### ISSUE TITLE
Isolated semicolon in MATLAB class definition file identifies as M programming language

### ISSUE THREAD

**Issue by ojdo** [github/linguist#3338]
I have pushed a MATLAB class definition file named [`GAMS.m`](https://github.com/ojdo/gams-matlab/blob/fbfda1e5db3de7c22a848388bdd207baecaa9135/GAMS.m) to my repository [ojdo/gams-matlab](https://github.com/ojdo/gams-matlab), which begins as follows:

```matlab
classdef GAMS < handle
%GAMS Interface class to call GAMS models from within Matlab
%   This class can be used for quick scenario generation and result
%   analysis for GAMS models. Call 'help GAMS.method_name' for information
%   [...]
```

Somehow, the linguist heuristic matches this file as the `M` programming language. 
I wonder whether a check for the string `classdef` at the beginning of the file in `heuristics.rb` could amend this? After all, there is already a matching [`matlab_class.m`](https://github.com/github/linguist/blob/master/samples/Matlab/matlab_class.m) sample file in the repository.

**Comment by pchaigno** [comment]
This happens because of [this line](https://github.com/ojdo/gams-matlab/blob/fbfda1e5db3de7c22a848388bdd207baecaa9135/GAMS.m#L1683), which matches the M heuristic rule. Is it common for Matlab lines of code to start with `;`? If not, I think the best in your case would be to use [Linguist overrides](https://github.com/github/linguist#overrides).

**Comment by ojdo** [comment]
Thank you for looking into the file for me! I now went with the manual override for the language statistic.

Concerning the frequency of `;` in Matlab: it is not frequent, though the only way to create no-op where a statement is expected (as it is in the catch block), similar to the `pass` keyword in Python. [Here](http://de.mathworks.com/matlabcentral/answers/117519-do-nothing-command-in-matlab#comment_210703) is another instance of an isolated `;` to do nothing in a chain of `if`, `elseif`s and `else`.

**Comment by ojdo** [comment]
I have to back up a bit: apparently, [no statement, but only a comment](https://github.com/ojdo/gams-matlab/commit/d2008c210a5b99ef22b45d20118e8f1f1f673b89) seems to work as well.

**Comment by pchaigno** [comment]
I'd consider this a corner case of our M heuristic rule, so I'm going to close it. Please reopen if you find this bug happens too often.
