### ISSUE TITLE
Language not showing up in this repos

### ISSUE THREAD

**Issue by lucasrodes** [github/linguist#3342]
Hi, I have one repo not showing its language. 
Namely,
https://github.com/lucasrodes/book-author-classifier

Any ideas?
Thanks

**Comment by pchaigno** [comment]
I think this has to do with the limit on the number of files Linguist can analyze at once. I reported this issue some time ago in #2915:
> Linguist currently returns no language counts - even when run locally - because of [this line, which limits the number of blobs in the repository to 100,000](https://github.com/github/linguist/blob/829eea01396e8e5747cd83f799d41196b2b9d898/lib/linguist/repository.rb#L135).

@vmg @brandonblack I'm wondering if it would be worth increasing this limit...?

**Comment by lucasrodes** [comment]
Thanks @pchaigno ! This makes sense since I uploaded a lot of text files to this repo. I will try to fix this soon and report if I solved it. Thanks again!

**Comment by vmg** [comment]
We can't increase this limit. CPU is not free and 100k blobs in a Git repository is not a reasonable thing at all. The Linux Kernel and Webkit _together_ have much fewer files than 100k, so we don't plan to support bigger repositories for language analysis.

@lucasrodes: Your are indeed hitting our maximum blob limit for repository language analysis. Given that all the files in your repository are actually just test data, I'd encourage you to save them in a single `.tar.gz` file and update your code to uncompress it when accessing the data. That will fix your language detection issues. Thanks!

**Comment by RushiY** [comment]
what is the maximum for java files in a private repo?

**Comment by pchaigno** [comment]
@RushiY This is not a per-language setting since it is enforced _before_ language detection.

**Comment by RushiY** [comment]
I see, thanks for letting me know.

**Comment by darkRaspberry** [comment]
What about small repo like https://github.com/darkRaspberry/Forest

**Comment by darkRaspberry** [comment]
What about small repo like https://github.com/darkRaspberry/Forest
