### ISSUE TITLE
Language name is shown wrong

### ISSUE THREAD

**Issue by Faizaankhan3** [github/linguist#3343]
My repository contains Django file system and the codes are written purely in HTML and Python, but the language as predicted by linguist is shown as javascript.

**Comment by pchaigno** [comment]
Do you have a link to the repository or is it private? If you click on JavaScript does the search returns any `.js` files?

**Comment by Faizaankhan3** [comment]
The link to the repository is this

https://github.com/Faizaankhan3/TechTrix_Transactions

No there are no .js files being used

Regards


*Faizaan Ahmed Khan       *
*RCC Institute of Information Technology  *
Email : faizaan.khan3@gmail.com
Contact No: 9832710273 / 8013584657

**Comment by souravbadami** [comment]
@Faizaankhan3 -- Your code has 61.2% JavaScript. See here: https://github.com/Faizaankhan3/TechTrix_Transactions/tree/master/TechTransact/static/admin/js

**Comment by pchaigno** [comment]
Thanks @souravbadami!

@Faizaankhan3 You can mark those files as vendored using [Linguist overrides](https://github.com/github/linguist#overrides).
