### ISSUE TITLE
Create a "book" category

### ISSUE THREAD

**Issue by thewhitetulip** [github/linguist#3346]
I am writing a short book and it does not have a single code file, only markdown files. Thus, there is no way to identify that is is a book, it might as well be a blog written in static file generators. I feel that Github has now matured and is being used for writing books as well, it'd be great if we can classify repos as books. Helps in the "trending" page. _Here are the 10 trending books_

**Comment by brandonblack** [comment]
@thewhitetulip how would we distinguish between a book and a project with lots of markdown? 

In any case, I'm really not sure this falls within the scope of what linguist does. In the case of your book, markdown is code and linguist would correctly identify your repository as that. The function of your markdown is for a book, but that's really meta information beyond linguist's scope and purpose.

I agree it would be great to identify standards for books being made on GitHub so we can surface those to users, but I don't think there really is such a standard way of doing that yet and I don't really feel like linguist is the right place to try and do it.

**Comment by thewhitetulip** [comment]
@brandonblack You do have a valid point, and yes, linguist is probably not the place to propose this change, but I really didn't know how to contact anyone in Github (and not the customer support), hence I raised an issue here.

One thing I can suggest is that we can somehow classify the repo as "book", rather than classifying the language by the metadata file which is used to override linguist. I don't see any other way of identifying books with lots of markdown

**Comment by Caged** [comment]
@thewhitetulip While we don't have a feature for formal definitions,  you should now be able to classify your repository as a book by using topics.  https://github.com/blog/2309-introducing-topics
