### ISSUE TITLE
PARI/GP scripts (extension .gp) are being missclassified as Gnuplot files

### ISSUE THREAD

**Issue by oscarsaleta** [github/linguist#3347]
PARI/GP is a computer algebra system (http://pari.math.u-bordeaux.fr/) which unfortunately uses the extension *.gp* for its scripts (same as gnuplot).
Take this script as an example: https://github.com/oscarsaleta/Lyapunov/blob/master/polops.gp, it is a PARI/GP script from my repository which is classified as Gnuplot.
The repository states that it's a 60.4% Gnuplot but there are not Gnuplot files in it: https://github.com/oscarsaleta/Lyapunov.

**Comment by pchaigno** [comment]
Teaching Linguist the difference between PARI/GP and Gnuplot first requires to [add support for PARI/GP](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). If it meets the requirement on in-the-wild usage, don't hesitate to open a pull request. If it doesn't, your best bet it to use [Linguist overrides](https://github.com/github/linguist#overrides) for now.
