### ISSUE TITLE
Misclassified repo language

### ISSUE THREAD

**Issue by gumblex** [github/linguist#3362]
This repo https://github.com/ZhanruiLiang/jinyong-legend is classified as 100% Python. However there is no Python code, and it's at least a Lua repo.

**Comment by Kochise** [comment]
https://github.com/Kochise/cdtrack and https://github.com/Kochise/scroll4d classified as Scheme (SS files) but is 68030 assembler. Tried the .gitattributes trick, added the upper case version only to see the Scheme files disappearing from the Language stats bar instead to switch to 'assembler' like expected.

**Comment by pchaigno** [comment]
@gumblex The statistics for this repository are just not up-to-date. I get the following when I run the last released version of Linguist against it:
```
$ linguist
93.82%  Lua
5.99%   C
0.15%   C++
0.04%   Makefile
0.00%   Shell
0.00%   Batchfile
```
The statistics should update with the next push to the repository. Alternatively you can ask support@github.com to update it.

@Kochise It's `Assembly` and not `Assembler` ;)

**Comment by Kochise** [comment]
Tried as you indicated and switched to 'Assembly', Now the repo shows brown 'Assembly 42.6%' but when I click on it, it shows nothing with the https://github.com/Kochise/cdtrack/search?l=nasm filter. If I click on 'Scheme' on the left, I finally get back my SS files.

**Comment by pchaigno** [comment]
@Kochise This is probably due to a caching error. We get these a lot lately. You should fix itself within the next 48 hours. Alternatively, you can contact support@github.com to update it.

**Comment by Kochise** [comment]
OK, thanks, will wait a bit before contacting support. That's rather strange though.
