### ISSUE TITLE
Swift syntax highlighting breaks on complex constructs

### ISSUE THREAD

**Issue by idrougge** [github/linguist#3365]
Some Swift sequences cause the syntax highlighter to quit its job, apparently it is caused by chains of closures. This can be observed at the end of https://github.com/idrougge/advent_of_code_2016/blob/master/idrougge-swift/day5/md5.swift where the text turns a uniform blue in the last portion of the code. It seems to be triggered by this line:
```        c.h.forEach{hh+=String(format:"%08X\($0.distanceTo(c.h.last!)==0 ? "":" ")",$0.bigEndian)}```

**Comment by Alhadis** [comment]
Linguist doesn't provide the actual syntax highlighting - it simply selects the language grammar which does. In Swift's case, highlighting is powered by [textmate/swift.tmbundle](https://github.com/textmate/swift.tmbundle), so you'd best file an issue there.

Once the issue has been fixed upstream, the changes will be automatically picked up by Linguist and included in its next release. =)
