### ISSUE TITLE
MEAN stack (JavaScript) application reported as mostly CSS, but no CSS sources.

### ISSUE THREAD

**Issue by amnotafraid** [github/linguist#3369]
When I click on the stats bar in this repository:  [MeanSeed](https://github.com/amnotafraid/MeanSeed)
I see this:
![mean seed language stats](https://cloud.githubusercontent.com/assets/1727761/20975801/2db148fa-bc66-11e6-974f-f8f446713dcf.png)
When I click on CSS, I get this:
![no code matching](https://cloud.githubusercontent.com/assets/1727761/20975828/41f5c73c-bc66-11e6-952e-146345cff1c8.png)
The advanced options are incomprehensible to me.  I imagine that the CSS is coming from client/app/styles which has SASS files in there.
I tried adding a .gitattributes file to that repository that had this line:
```
client/app/styles/* linguist_vendored
```
but nothing changed.

My code is a Mongo, Express, Angular, Node project.
How can I get linguist to report my project as JavaScript?

**Comment by pchaigno** [comment]
> The advanced options are incomprehensible to me. I imagine that the CSS is coming from client/app/styles which has SASS files in there.

Yes, the 46.8% come from [the SCSS files](https://github.com/amnotafraid/MeanSeed/search?l=SCSS). It's a known discrepancy between the language statistics and the search results: one language in statistics can be mapped to several languages in search results and the web UI doesn't handle that very well :/

> I tried adding a .gitattributes file to that repository that had this line `client/app/styles/* linguist_vendored` but nothing changed.

It's `linguist-vendored` instead of `linguist_vendored` ;)

**Comment by amnotafraid** [comment]
Hey pchaigno, thanks so much!  Changing from linguist**_**vendored to linguist**-**vendored got me what I wanted.  That was easier than I thought it was going to be.
![correct language stats](https://cloud.githubusercontent.com/assets/1727761/20991403/dede0cfc-bca3-11e6-90d4-19331d1a84cd.png)
