### ISSUE TITLE
Haml syntax highlighting got worse

### ISSUE THREAD

**Issue by meganemura** [github/linguist#3371]
I noticed that the haml syntax highlighting got worse, since #3355 merged linguist (v4.8.18) was applied to GitHub. I don't know why [lightshow output](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fezekg%2Flanguage-haml%2Fblob%2F301625dff414653eb88320c624434429ef8e244c%2Fgrammars%2Fruby%2520haml.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgist.githubusercontent.com%2Fmeganemura%2F161ba93782d5dbb6930c279797adb8a6%2Fraw%2F406e8a004649d1813e0f473fe5dbf5b8a3be4f15%2Flinguist.html.haml&code=) is different to GitHub syntax highlighting.
This affects many people using haml, so please consider reverting #3355 for workaround. I'm so sorry about this.

Please compare the lightshow ouput and the next haml.
```haml
/ HAML comment
- # ruby comment
string
= "string"
= "string" #comment
= "string #{not_comment}" # comment

-# 
  multi line comment
  multi line comment
  multi line comment
```

**Comment by pchaigno** [comment]
> I don't know why lightshow output is different to GitHub syntax highlighting.

@aroben Any idea how that could happen?

**Comment by Alhadis** [comment]
I'm wondering if this could be related to #3130. The new grammar [makes use](https://github.com/ezekg/language-haml/blob/master/grammars/ruby%20haml.cson#L64) of the `$\n?` trick for skipping newline boundaries, which I learned has portability issues between different regex engines/implementations.

**Comment by lildude** [comment]
> I don't know why lightshow output is different to GitHub syntax highlighting.

It's because it's a different application that hasn't been updated inline with the Linguist updates as they're applied to GitHub.com.  I'll update this :soon:

**Comment by Alhadis** [comment]
If you blokes could open-source it too so I can fix all its bugs, that'd be great too. ;)

**Comment by meganemura** [comment]
Thanks @vmg.
Close this issue in favor of #3627.
