### ISSUE TITLE
Can't overwrite language of Markdown (.md) file type

### ISSUE THREAD

**Issue by ryanmcdermott** [github/linguist#3374]
I set the `linguist-language` of `*.md` files to `JavaScript` in my `.gitattributes` file but my project is not showing up as JavaScript. Is there anything I am doing wrong or is this a bug specifically with `.md` files.

https://github.com/ryanmcdermott/clean-code-javascript

**Comment by pchaigno** [comment]
By default, [READMEs are considered documentation](https://github.com/github/linguist/blob/2c78dd2c66bef6da17d1f0beb59a394037f66477/lib/linguist/documentation.yml#L26) and not included in statistics. You'll need to add the following to your `.gitattributes` to change that behavior:
```
*.md linguist-documentation=false
```

**Comment by ryanmcdermott** [comment]
Thank you that worked!
