### ISSUE TITLE
Respository Type Wrong: HTML vs JavaScript

### ISSUE THREAD

**Issue by anywhichway** [github/linguist#3381]
This repository is JavaScript: https://github.com/anywhichway/iMemoized

It is not clear why is is being marked as HTML even after reviewing the linguist documentation.

**Comment by pchaigno** [comment]
Statistics are computed from the total size of files for each language. The first language becomes the repository language.
You can mark those HTML files as vendored using [Linguist overrides](https://github.com/github/linguist#overrides).

**Comment by anywhichway** [comment]
Thanks. I had to read the docs three times to grock them ... time to sleep.
