### ISSUE TITLE
Deprecation of Blob Helper

### ISSUE THREAD

**Issue by brblck** [github/linguist#3387]
This task is here to track the effort to deprecate the following:
- [`Generated.generated?`](https://github.com/github/linguist/blob/d46a529b6a0f4e9994bb513e39f6dc672529ee19/lib/linguist/generated.rb#L7)
- [`BlobHelper`](https://github.com/github/linguist/blob/8dc4a1308f7d309ebdf5566251eca3f5562d8901/lib/linguist/blob_helper.rb#L8)

These deprecations involve some pending changes on GitHub's side.
#
CC: @pchaigno

**Comment by freddyrpina** [comment]
ok cool  what if u use a rrs.

**Comment by Alhadis** [comment]
@freddyrpina What do you mean?

**Comment by pchaigno** [comment]
@lildude Was there any progress on this?

PS: @Alhadis I removed a spam comment and your answer.

**Comment by Alhadis** [comment]
Wait, what did they say again? It's already vanished from my memory. :(

**Comment by lildude** [comment]
> @lildude Was there any progress on this?

I have no idea 😁 I don't know any of the history or backstory around this.

**Comment by pchaigno** [comment]
These are just a few functions of the API that have been marked as deprecated on the Linguist side for a while. See [2006# (Comment)](https://github.com/github/linguist/pull/2006#issuecomment-264705864) and #3359 for context.

**Comment by pchaigno** [comment]
I'm assigning you @lildude. Since it's something to do on closed-source code, it's out of my hands.

**Comment by Alhadis** [comment]
No idea what the hell's going on here, but I'm pretty damn sure that if I don't know, a bot doesn't know. :|

Unstale'd.

**Comment by pchaigno** [comment]
@brblck Have the changes required on GitHub's side been implemented? :tadaa:
