### ISSUE TITLE
Language bar says as HTML, should be C#

### ISSUE THREAD

**Issue by SyndARn** [github/linguist#3390]
The repo is this one : [https://github.com/SyndARn/ARnActorModel](url) ...
I have already try to customize vendor language, remove the last HTML file, push to force an update, but the language bar is still wrong.

**Comment by pchaigno** [comment]
This is happening because of [this file](https://github.com/SyndARn/ARnActorModel/blob/master/ARnActorSolution/TestActor/Report/summary.htm).

**Comment by SyndARn** [comment]
Fine enough, removing the file clears the issue !
Thanks for your help !
