### ISSUE TITLE
Rename Mathematica to Wolfram Language

### ISSUE THREAD

**Issue by tjrana** [github/linguist#3391]
I would like to suggest changing the language label "Mathematica" to "Wolfram Language" (or just "Wolfram" for short). Mathematica is a program that uses the Wolfram Language.

Mathematica's language was officially named "Wolfram Language" sometime around 2013, according to the following official blog posts:
- http://blog.stephenwolfram.com/2013/02/what-should-we-call-the-language-of-mathematica/
- http://blog.stephenwolfram.com/2013/11/something-very-big-is-coming-our-most-important-technology-project-yet/

Other references:
- https://www.wolfram.com/language/
- https://www.wolframlanguage.org/

**Comment by yegortimoshenko** [comment]
However, mind that a) they previously called the actual language Mathematica, [see this PDF](http://reference.wolfram.com/legacy/v1/contents/4.2.7.pdf) for example, b) most people call it Mathematica despite the rebranding. Consider these search queries:

* [created:>=2014 language:mathematica mathematica](https://github.com/search?utf8=✓&q=created%3A%3E%3D2014+language%3Amathematica+mathematica) (708 results)
* [created:>=2014 language:mathematica wolfram language](https://github.com/search?utf8=✓&q=created%3A%3E%3D2014+language%3Amathematica+wolfram+language&type=Repositories&ref=searchresults) (59 results)

And in the second search, some repositories actually call it "Mathematica/Wolfram Language", and if you exclude such results, the result count will go down even further:

* [language:mathematica wolfram language NOT mathematica](https://github.com/search?utf8=✓&q=language%3Amathematica+wolfram+language+NOT+mathematica&ref=simplesearch) (41 results)

I continue to call it Mathematica, the new name sounds unnatural for me. Stephen Wolfram really likes his last name :-) While I don't feel strongly either way, I'd prefer to see more adoption before this particular change.

**Comment by smola** [comment]
Could this be reopened and reconsidered? Wolfram Language is the official name and post-2013 tooling tends to use it.

cc @lildude @pchaigno @Alhadis
