### ISSUE TITLE
Repository lang stats graph: Poor color contrast

### ISSUE THREAD

**Issue by jonsuh** [github/linguist#3394]
I’m color blind (deutan) and found the CoffeeScript blue nearly impossible to tell apart from the CSS purple with the naked eye:

![image](https://cloud.githubusercontent.com/assets/359871/21320838/f2d2fb9a-c5d7-11e6-8b1a-5e34e91f278b.png)
From repo https://github.com/postcss/autoprefixer

Nothing critical, but I thought it was worth mentioning from an accessibility standpoint.

I was directed to open an issue here by @jasonlong on Twitter: https://twitter.com/jasonlong/status/810887402260692992

Thanks!

**Comment by gabru-md** [comment]
The same is the case with `Go` and `Python`.
I am not color blind, but even I find it difficult to differentiate between the two.
![cb](https://user-images.githubusercontent.com/25414121/39965239-d33acc0a-56b2-11e8-978d-a0b605f57113.png)

From the repository [https://github.com/taskcluster/json-e](https://github.com/taskcluster/json-e)

**Comment by Alhadis** [comment]
Colour-blind as well (deutan), and just chiming in to say some colours are impossible for me to distinguish... I often find myself clicking the language bar out-of-habit just to bring up the language stats, because I'm so used to seeing CSS/CoffeeScript repos... 😞

**Comment by tiehuis** [comment]
Wrote a small program that compares the colors for languages as specified by linguist. Would probably require a bit of context in what languages are commonly found together but may prove helpful.

https://github.com/tiehuis/linguist-color-checker

**Comment by jonsuh** [comment]
@Alhadis Dividers definitely help define the breakdown! I think it’s a good solution—consider this solved :) Thank you for the follow up!
