### ISSUE TITLE
Lisp Flavored Erlang highlighting error

### ISSUE THREAD

**Issue by deadtrickster** [github/linguist#3400]
Looks like binaries aren't highlighted properly:

[![Highlight Error](http://i.imgur.com/MyyAmfg.png)](https://github.com/rvirding/lfe/blob/develop/test/clj-tests.lfe#L127)

**Comment by pchaigno** [comment]
Linguist only selects the grammar to use for highlighting. For LFE, GitHub uses [textmate/lisp.tmbundle](https://github.com/textmate/lisp.tmbundle). You should open an issue there if there isn't already one.
