### ISSUE TITLE
Repo doesn't shows any language

### ISSUE THREAD

**Issue by madclaws** [github/linguist#3401]
My Repository with bunch of c++ files has not been detected as c++ language

**Comment by pchaigno** [comment]
Is it a private repository? Can you share a link to it?

**Comment by madclaws** [comment]
Sorry for the delay,link is here
github link <https://github.com/madclaws/OverCover-Game_Engine>

**Comment by pchaigno** [comment]
Only programming and markup languages are part of the language statistics and displayed in the language bar. The 2 files in your repository are XML files, which is considered a data language.

**Comment by madclaws** [comment]
Sorry That was master branch link .The files are in Development branch.
here is the link.
https://github.com/madclaws/OverCover-Game_Engine/tree/development/OverCover
This branch has .cpp files.

**Comment by pchaigno** [comment]
Ah. Unfortunately, statistics are only computed for the main branch (which you can redefine to be the `development` branch though).

**Comment by madclaws** [comment]
By redefining you mean setting it default?

**Comment by pchaigno** [comment]
Yes.

**Comment by madclaws** [comment]
Ok thanks

**Comment by SidPaliwal** [comment]
My repo [https://github.com/SidPaliwal/CryptoCurrency-Tracker](url) is not showing any language? Can anyone please resolve this issue !

**Comment by lildude** [comment]
Please start a new [discussion](https://github.com/github/linguist/discussions) as this issue is old and has already been resolved.
