### ISSUE TITLE
Repo marked wrongly as shell, should be C

### ISSUE THREAD

**Issue by pepa65** [github/linguist#3404]
Have a look: https://github.com/pepa65/didiwiki
How is this ever being classified as shell??

**Comment by pchaigno** [comment]
Because of [these files](https://github.com/pepa65/didiwiki/search?l=bash) probably.

**Comment by pepa65** [comment]
Right..! Those are just part of the build system. Maybe they can be added to a ignore type list in these cases?

**Comment by Alhadis** [comment]
You can use a [`.gitattributes`](https://github.com/github/linguist#using-gitattributes) file to mark the files as vendored. =)

```
compile linguist-vendored
configure linguist-vendored
depcom linguist-vendored
install-sh linguist-vendored
missing linguist-vendored
```

[Full information on that subject here](https://github.com/github/linguist#using-gitattributes).

**Comment by pepa65** [comment]
Thanks for the pointers, that totally fixed it.
Is it too error-prone to have linguist consider these as vendored by default? It must be 99.9% of all repos where this would be desirable.

**Comment by Alhadis** [comment]
Well, each of the [filename patterns](https://github.com/pchaigno/linguist/blob/master/lib/linguist/vendor.yml) we mark as vendored by default are all pretty obvious. Stuff like `jquery.js`, `.min.js` and so forth... it'd be surprising if such things *weren't* vendored code.

Filenames as generic as `configure` and `compile`, on the other hand... you can bet whatever stuffed animal you ate today that'd be too error-prone. Hell, it'd [even hit something I'm working on right now](https://github.com/DanBrooker/file-icons/blob/v2-reloaded/bin/compile).

We have another mechanism for that called [generated files](https://github.com/pchaigno/linguist/blob/master/lib/linguist/generated.rb), where we use pattern substrings for determining whether the file's source is auto-generated or not. If you believe these shell-scripts should not be considered in repository statistics, a pull request would be warmly welcomed. :)
