### ISSUE TITLE
Repository's language is being reported incorrectly as HTML, should be typescript

### ISSUE THREAD

**Issue by plantain-00** [github/linguist#3405]
https://github.com/plantain-00/ws-tool

The `index.ts` is ignored.

Seems the source contains `^@`(control-@) make the file ignored.(https://github.com/plantain-00/ws-tool/blob/master/index.ts#L56)

**Comment by pchaigno** [comment]
This is an issue in git itself unfortunately. Git recognizes as binary any file that contains a zero byte in the first 8000 bytes.

**Comment by plantain-00** [comment]
It seems so, official git cannot diff the file too, but the vscode can diff the file correctly, maybe the git used by vscode is not official git.
