### ISSUE TITLE
Language statistics of the previous default  branch

### ISSUE THREAD

**Issue by Mike-Now** [github/linguist#3406]
After updating the default branch from gh-pages to master,
the bar shows the old statistics.
https://github.com/Mike-Now/fovris

**Comment by pchaigno** [comment]
Statistics usually update when you push to the repository. Not sure they do when changing the default branch (@brandonblack ?). I get the following when running the last released version of Linguist against your repository:
```
$ linguist
92.89%  C++
3.32%   Yacc
2.27%   CMake
1.19%   Python
0.30%   Makefile
0.03%   C
```
So it's not an issue with Linguist. You should try waiting a little bit longer or try to push something.

**Comment by brandonblack** [comment]
@pchaigno is correct. This looks to be resolved now 👍
