### ISSUE TITLE
Files with .mysql extension are not recognized as sql

### ISSUE THREAD

**Issue by danilaml** [github/linguist#3410]
The usage seems pretty extensive:
https://github.com/search?p=6&q=extension%3Amysql+NOT+nothack&ref=searchresults&type=Code&utf8=%E2%9C%93

Simply adding `mysql` to extension lists doesn't seem like the best solutions though, since there is very small number of files which use this extensions while are not SQL. Like https://github.com/pawel2105/Ballet-bugs/blob/df4ee344fd9f908ac76ee3c310b97620133c6787/config/database.yml.mysql and https://github.com/xrmx/freeswitch/blob/cb675394c2073425640dd1e604df4a3aca6aefb5/libs/apr-util/INSTALL.MySQL

**Comment by pchaigno** [comment]
Thanks for investigating this!

One solution so far could be to add `INSTALL.mysql` as a filename for `Text`, `.yml.mysql` as an extension for YAML, and `.mysql` as an extension for SQL. I think there are enough [`.yml.mysql`](https://github.com/search?utf8=%E2%9C%93&q=filename%3Ayml.mysql+extension%3Amysql&type=Code&ref=searchresults) and [`INSTALL.mysql` files](https://github.com/search?utf8=%E2%9C%93&q=filename%3AINSTALL.mysql) to warrant it.

Did you found other non-SQL files with a `.mysql` extension?

**Comment by danilaml** [comment]
@pchaigno In the [link](https://github.com/search?p=6&q=extension%3Amysql+NOT+nothack&ref=searchresults&type=Code&utf8=%E2%9C%93) I posted above there is a relatively small number of files (you can see them in the languages histogram) with sql extension which are detected (correctly) as having a different language, because they use something like `#!/bin/sh` at the start. Large number of those follow the `*.lang.mysql` pattern, though not all. I'm not sure whether introducing `mysql` extension would overwrite their highlighting options and how much there other files with no highlighting at all (so they were not counted by GitHub)

Where are also these files: https://github.com/search?p=1&q=filename%3AREADME.mysql&ref=searchresults&type=Code&utf8=%E2%9C%93
Which looks to contain only text.

**Comment by pchaigno** [comment]
> I'm not sure whether introducing mysql extension would overwrite their highlighting options

It wouldn't. Shebang (`#!`) detection gets priority over other types of detection.

> Where are also these files: https://github.com/search?p=1&q=filename%3AREADME.mysql&ref=searchresults&type=Code&utf8=%E2%9C%93
Which looks to contain only text.

Okay, we can add those as a filename for `Text` as well.

Do you want to go ahead and open the pull request? You can follow the guidelines to [add support for a new extension here](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language).

**Comment by danilaml** [comment]
@pchaigno Are `filenames` case-sensitive for linguist? It seems like `INSTALL.mysql` files are plain text, while `install.mysql` are sql.

**Comment by pchaigno** [comment]
Yes, it's case-sensitive.
