### ISSUE TITLE
NetLogo 3D not properly detected

### ISSUE THREAD

**Issue by lrq3000** [github/linguist#3412]
NetLogo supports both 2D or 3D models. For 3D models, the default extension is `.nlogo3d`, although `.nlogo` also works (I don't know if it internally makes a difference, but NetLogo 3D by default saves project as `.nlogo3d`).

I did a search on GitHub but it seems GitHub cannot properly detect this extension.

However using [Google, I get a hundred results](https://encrypted.google.com/search?q=site%3Agithub.com+nlogo3d).

Here is my repository, as an example: https://github.com/lrq3000/netlogo-mas-drones

Would it be possible to add support for `.nlogo3d`? The parsing should be very similar to `.nlogo`, it's basically just a variant name (although maybe the header has some differences).

/EDIT: Yes in the footer (not the header), the version will be different:

`NetLogo 3D x.x.x` where x.x.x is the version number, instead of `NetLogo x.x.x`.

**Comment by pchaigno** [comment]
> I did a search on GitHub but it seems GitHub cannot properly detect this extension.

I counted [45 repositories among 38 users](https://github.com/search?p=1&q=extension%3Anlogo3d+NOT+dfhdfdhfjdhfdhd&type=Code&utf8=%E2%9C%93). I don't think that will be enough to add the `.nlogo3d` file extension yet.

**Comment by lrq3000** [comment]
Fair enough, even if that's sad :/

2017-01-01 12:17 GMT+01:00 Paul Chaignon <notifications@github.com>:
