### ISSUE TITLE
Wrong language detected

### ISSUE THREAD

**Issue by jcubic** [github/linguist#3414]
On repo [markdown-it](https://github.com/markdown-it/markdown-it) github recognize [mardown files as GCC Machine Description files](https://github.com/markdown-it/markdown-it/search?l=GCC+Machine+Description).

**Comment by pchaigno** [comment]
Given that these seem to be small example files, it will be difficult to improve Linguist's accuracy. However, you can mark those files as vendored using [Linguist overrides](https://github.com/github/linguist#overrides).

**Comment by jcubic** [comment]
Great, I've added [issue to that repo ](https://github.com/markdown-it/markdown-it/issues/319)
