### ISSUE TITLE
Repository is tagged with the wrong language

### ISSUE THREAD

**Issue by Zaid-Safadi** [github/linguist#3417]
My repository (link below) quick stats shows JavaScript as the main language with 83.7% and C# with 15.9% although it is almost the opposite. 

It seems the file detection is working properly when clicking on a language so I'm confused why my repository is listed as a JavaScript rather than C#
 C# 249 files vs. JS 47 files
 
Link to repo: [https://github.com/Zaid-Safadi/DICOMcloud](https://github.com/Zaid-Safadi/DICOMcloud)

**Comment by nixel2007** [comment]
Did you check the files' size? Linguist detects the main language by lines in files, not quantity of files.

**Comment by wopian** [comment]
Most of those JavaScript files look like vendor code so you can add the following to `.gitattributes`:

```properties
DICOMcloud.Wado/Scripts/**/* linguist-vendored
```.

etc.

**Comment by Zaid-Safadi** [comment]
This fixed it for me, thank you both for your help!
