### ISSUE TITLE
^M appears at the end of lines of some files that use CRLF line endings

### ISSUE THREAD

**Issue by nwhetsell** [github/linguist#3418]
I’m not sure if this is a Linguist issue, but `^M` can appear at the end of lines of some files that use CRLF line endings, for example [here](https://github.com/rorywalsh/Morpheus/blob/master/Morpheus.csd). I don’t recall seeing this before the [5.0.0](https://github.com/github/linguist/commit/a4d12cc8e42aae26a9469edb9fedb25a7cdbc9e9) release.

**Comment by pchaigno** [comment]
This ma have to do with how github.com applies syntax highlighting in the backend. I don't think it's an issue with Linguist. You should report it to support@github.com.

**Comment by nwhetsell** [comment]
Done.
