### ISSUE TITLE
Branch gh-pages counted in stats?

### ISSUE THREAD

**Issue by jeremylong** [github/linguist#3419]
The [OWASP dependency-check](https://github.com/jeremylong/DependencyCheck) repo is being counted as 78% HTML; yet the main branch contains no HTML. All of the HTML is generated and is contained in the gh-pages branch. What is the best way to configure linguist so that it does not count the generated HTML contained in the gh-pages branch?

**Comment by pchaigno** [comment]
Actually, [this very large file](https://github.com/jeremylong/DependencyCheck/blob/5d73faa1f08aeaa7c939b86f2e5bc7dc8ff9c293/src/site/resources/general/SampleReport.html) accounts for the 78.1% of HTML.

**Comment by jeremylong** [comment]
Thank you; I missed this file because when I click on the HTML link in the language stats github shows that there are no [HTML files](https://github.com/jeremylong/DependencyCheck/search?l=html) so the only thing I could think of is that the branches were being counted.

**Comment by pchaigno** [comment]
Yep, unfortunately, language statistics are not always in sync with search results :/
We're having this issue a lot lately, it seems to be related to a cache invalidation error.
