### ISSUE TITLE
5.0.1 build undersized

### ISSUE THREAD

**Issue by kivikakk** [github/linguist#3425]
I think the 5.0.1 gem build on RubyGems is faulty; the gem I get is 817kb and seems to misbehave, but a local build gives 1,954kb gem.

We may want to just tag master as 5.0.2 and rebuild (and check it's around 2mb).

**Comment by Alhadis** [comment]
Uh. Any chance I could squeeze in a quick PR before cutting a release?

Because I've rewritten the hell out of a [CSS grammar](https://github.com/atom/language-css) with the express intent of getting it used on GitHub. Should be approved any day now...

(Sorry for side-tracking, but this has taken MONTHS...)

**Comment by kivikakk** [comment]
Looks like it already got approved, just needs someone from the atom org to merge! I'll ping them. :) Should be a simple grammar update here then, so :+1:

**Comment by 50Wliu** [comment]
Hey there, I'm about to merge it!  No ping necessary :)

**Comment by kivikakk** [comment]
Awesome, thank you!

**Comment by Alhadis** [comment]
1. Oh, that's the thing, we're still using TextMate's old grammar.

2. WHOO-HOO CAVALRY HAS ARRIVED!

In that order.

**Comment by kivikakk** [comment]
1. Ahhh, I see! So you'll open a PR to switch it around here then? (I'm actually a linguist noob, if you couldn't tell >.>)
2. ![](http://8gmwp015fo-flywheel.netdna-ssl.com/wp-content/uploads/sites/10/2014/11/Tracer.jpg)

**Comment by Alhadis** [comment]
I used to be a Linguist noob like you, then I ~~took an arrow to the knee~~ made the mistake of getting addicted to writing language grammars, because regexp + making stuff look pretty = excuse to be obsessed.

CSS PR inbound, once my crappy Australian connection finishes downloading...

**Comment by kivikakk** [comment]
Cool, just @ me on it as I'm not watching this repo currently!

(I used to be able to empathise, but then I moved into a new apartment that happened to have NBN 📈)

**Comment by Alhadis** [comment]
I live in the outskirts of Melbourne, where NBN is a myth.

(Previously South Yarra, but had to move back to Healesville... -_- Kuradi põrgu)

**Comment by brandonblack** [comment]
Thanks for catching this. The new release is coming in at 1.9M 👍
