### ISSUE TITLE
could it take yarn.lock as generated?

### ISSUE THREAD

**Issue by sunderls** [github/linguist#3430]
yarn.lock is really very large, maybe a good idea to suppress the diff, by checking filename?

example: https://github.com/yarnpkg/yarn/blob/867cf4f2e4fefee5b682b1b61fc360502834d70c/yarn.lock

**Comment by pchaigno** [comment]
Looks like it's a generated file. You could add it to [`generated.rb`](https://github.com/github/linguist/blob/master/lib/linguist/generated.rb); it will be recognized as generated and the diff will be hidden.

**Comment by pchaigno** [comment]
Never mind, that's what you did in #3431. Closing in favor of #3431 :smile:

**Comment by sunderls** [comment]
@pchaigno ah yes,  thank you~
