### ISSUE TITLE
Perl 5 code being misidentified as Perl 6

### ISSUE THREAD

**Issue by bradhaywood** [github/linguist#3435]
Hello there,

As it stands now, Github is marking my repo as almost 50/50 Perl 5 and Perl 6. The confusing part is it's 100% Perl 5.
I believe the issue is caused by a module I'm using called Method::Signatures::Simple - this allows me to use `method` and `func` keywords, while also the benefit of proper signatures, like Perl 6.
This project will, in no way run, run as perl 6, so is there any way we could fix this?
The repo is: https://github.com/bradhaywood/p5-Discord

Cheers!

**Comment by yegortimoshenko** [comment]
Linguist has to use heuristics to distinguish between Perl and Perl 6. If all you want to do is to fix language detection in your particular repo, create `.gitattributes` file in your repo that contains:

```
*.pl linguist-language=Perl
```

**Comment by bradhaywood** [comment]
That's perfect, thanks!
