### ISSUE TITLE
Wrong language mark on repositories

### ISSUE THREAD

**Issue by koop4** [github/linguist#3437]
Hi,
I'm not sure how the language classification happen, but the following repository are wrong:

[This one ](https://github.com/koop4/spaceInvaders) should be marked as Java

[This one](https://github.com/koop4/Hanoi) should be marked as Assembly

[This one](https://github.com/koop4/UnityTutorial) should be marked as C#

**Comment by wopian** [comment]
The Java one is because of your [JavaDoc](https://github.com/koop4/spaceInvaders/tree/master/Javadoc) directory which contains a multitude of HTML.

Not familiar with Java, but if its documentation then you can do the following as per the README:

>Just like vendored files, Linguist excludes documentation files from your project's language stats. lib/linguist/documentation.yml lists common documentation paths and excludes them from the language statistics for your repository.
>Use the linguist-documentation attribute to mark or unmark paths as documentation.
```
$ cat .gitattributes
project-docs/* linguist-documentation
docs/formatter.rb linguist-documentation=false
```

---

The C# one showing >90% ASP for only having 2 ASP files is because the language bar uses the file size, not file count - and those 2 files are [huge](https://github.com/koop4/UnityTutorial/search?l=asp)

**Comment by koop4** [comment]
thanks for clarifying.
Do you have any idea why the other one which contain a simple assembly script (.asm) isn't marked?

**Comment by pchaigno** [comment]
If I run Linguist against the repository locally, I get:
```$ linguist --breakdown
100.00% Assembly

Assembly:
HanoiTower.asm
```
I'm guessing your statistics are simply not up-to-date. They should update with the next push to the repository.

**Comment by koop4** [comment]
point 1: is solved. thx @wopian 
point 2 is solved. thx @pchaigno 
point 3 is explained. Before closing i'd like to ask if there's a chance to make the check only on a single folder (in this case i would point to the script folder containing the C# code which i actually wrote)

**Comment by pchaigno** [comment]
> Before closing i'd like to ask if there's a chance to make the check only on a single folder (in this case i would point to the script folder containing the C# code which i actually wrote)

No, but you can [tell Linguist to ignore other directories](https://github.com/github/linguist#overrides).

**Comment by koop4** [comment]
thank you :)
