### ISSUE TITLE
How to disable the "file extension" heuristic ?

### ISSUE THREAD

**Issue by touisteur** [github/linguist#3439]
Hi,

I'd like to use the language classification features of github/linguist, without using the "file extension" heuristic. I'm trying to classify source code trees where files maybe wrongly or strangely named, sometimes without extensions, sometimes with the wrong one.

I thought I could to use github/linguist to give me a hint of what the file could be *without* relying on the extension.

When I try to remove the file extension (on Ada files for example), github/linguist gives an empty language as a result ? I also tried to rename an Ada file to "testfile.c" and the file is classified as "language: C".

Thanks in advance for your help.

**Comment by noxdafox** [comment]
Same issue here. 

I'd like to bypass the extension heuristic and try to guess the language based on the code only.

**Comment by pchaigno** [comment]
As @lildude explained, we use a number of strategies to select the language for a file. The Extension strategy (which filters out languages not associated with the file extension) does 99% (not the actual number obviously) of the job; it reduces the set of candidate languages from all to only a few and in some cases, to a single language.

Subsequent strategies (heuristics and Bayesian classifier) weren't built to choose a language among all possible languages. They are only refinement strategies. If you try to use them with all languages as input, you'll most likely end up with very poor results.

In my opinion, this is a design choice of Linguist; it was meant to classify files, not code snippets. Changing this would likely require a complete code rewrite, and we would not get the same accuracy/performance.
