### ISSUE TITLE
Why did ```cs code snippets stop being recognized as C#?

### ISSUE THREAD

**Issue by jamesqo** [github/linguist#3440]
I usually use ```cs to mark my C# code snippets. I recently noticed that code snippets marked like that no longer highlight on GitHub:

```cs
using System;

Console.WriteLine("Hello, world!");
```

While ```c# works fine:

```c#
using System;

Console.WriteLine("Hello, world!");
```

Did something change in Linguist recently that could have caused this?

**Comment by pchaigno** [comment]
Do you remember when you saw it last working?

**Comment by jamesqo** [comment]
@pchaigno Probably around 2 or 3 days ago. I use GitHub on a daily basis, so if it had stopped working earlier than that I would probably have noticed.

**Comment by pchaigno** [comment]
Hum... The last release of Linguist is from 4 days ago and the [only changes related to C# are in the grammar](https://github.com/atom/language-csharp/compare/71b8930b315b0793c4fb63314161dee5d2962dde...f1462897f9805520733f6dd2060360bd002b3e02). Maybe it's due to a change on github.com side. @brandonblack Any idea?

**Comment by brandonblack** [comment]
We did push a release with updated grammars this week, but I don't [see any changes in the upstream grammar](https://github.com/atom/language-csharp/compare/daf3fe2...master) that would have caused this. This language was not part of the rename so it wouldn't have been impacted by that either. 

On GitHub's side and within linguist, this [hasn't changed in 6 years](https://github.com/github/linguist/blame/master/lib/linguist/languages.yml#L465).

I suspect while `cs` might have worked before, it wasn't actually C# and was just something similar. The two officially supported language identifiers for snippets are the name `c#` or the alias `csharp`.

#### Using `c#`:
```c#
using System;
Console.WriteLine("Hello, world!");
```

#### Using `csharp`:
```csharp
using System;
Console.WriteLine("Hello, world!");
```

**Comment by jamesqo** [comment]
> I suspect while cs might have worked before, it wasn't actually C# and was just something similar.

I am pretty sure it was C# and not something similar. I used a variety of language keywords (e.g. `yield`, `async`, `nameof`) under ```cs and they were all highlighted correctly.

Just a guess, but since `cs` wasn't even listed as one of the aliases for C#: Maybe there was a feature in the library that automatically added a `cs` alias because `.cs` is a file extension for C#? And that feature got removed in a recent update? It would explain how this is happening with little C#-specific changes.

**Comment by brandonblack** [comment]
@jamesqo it looks like this was related to the breaking changes made in v5.0.0 for `find_by_extension`. 

https://github.com/github/linguist/blob/master/lib/linguist/language.rb#L151-L173

We should have a fix out shortly.
