### ISSUE TITLE
Wrong languages detected

### ISSUE THREAD

**Issue by jtgrassie** [github/linguist#3446]
I have a repository with both Java and CPP but the repo is being tagged as Java only. See https://github.com/jtgrassie/dd2feet

**Comment by brandonblack** [comment]
Looks ok now. 
![screen shot 2017-02-02 at 11 53 50 am](https://cloud.githubusercontent.com/assets/489331/22565786/4f380644-e93e-11e6-89d2-7f635e071250.png)

Language analysis is done when the contents of your repository change (eg. after you commit some code). As a result, you may see delayed stats.
