### ISSUE TITLE
Language miscalculated

### ISSUE THREAD

**Issue by AaronBratcher** [github/linguist#3449]
Not sure why, but https://github.com/AaronBratcher/ALBNoSQLDB is being shown as an Objective-C project when it only has 1 tiny .h file and several .swift files.

**Comment by pchaigno** [comment]
Actually, Linguist fails and recognizes [the `sqlite3.h` file](https://github.com/AaronBratcher/ALBNoSQLDB/blob/dbefdd68b7cdeb44c50c30312e52e1a5b81bad57/ALBNoSQLDB/ALBNoSQLDB/sqlite3.h) as Objective-C too. You might want to [mark it as vendored](https://github.com/github/linguist#overrides).

**Comment by rrohrer** [comment]
I'm also having .h files reported as Objective-C (and some reported as C++).  It seems to be the case where headers are nested in the repo?

ex: `include/foo.h` registers as C, but `include/data_structures/bar.h` registers as Objective-C.

It's worth noting I have a `.gitattributes` file that contains: `*.h linguist-language=C`.

**Comment by pchaigno** [comment]
> EDIT: Apparently this is an ongoing issue... #1626

Classification for such languages will never be perfect (Linguist rely on probabilistic methods as a last resort). You can override classifications using [Linguist overrides](https://github.com/github/linguist#overrides).
