### ISSUE TITLE
Language எழில் (Ezhil) - Tamil script based programming language 

### ISSUE THREAD

**Issue by arcturusannamalai** [github/linguist#3455]
Hi, I'm using ezhil language files that I'd be happy to see syntax highlighting available on github for this. 

Previously we added support for Ezhil to the Pygments project http://pygments.org/languages/. 
There repository with code is at 
https://github.com/Ezhil-Language-Foundation/Ezhil-Lang

and syntax hilighter with Pygments is at,
https://github.com/Ezhil-Language-Foundation/Ezhil-Lang/blob/master/ancilla/ezhil.py

That would be awesome :) to have gist and github level support for the Ezhil code.

Sincerely,
-Muthu

**Comment by pchaigno** [comment]
Please see the [guidelines to add support for a new language to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). If Ezhil meets the requirement on in-the-wild usage, don't hesitate to open a pull request.

**Comment by arcturusannamalai** [comment]
Thanks you. We are not that popular, but maybe bitbucket has some syntax hilighting I havent seen before. 
Cool beans.
