### ISSUE TITLE
Simple method to detect the type of a file, possibly optimized for a language

### ISSUE THREAD

**Issue by Dorian** [github/linguist#3456]
I'm trying to detect ruby files for [rubocop](https://github.com/bbatsov/rubocop/pull/3997) and noticed there is no easy and/or fast way to tell if a file is a ruby from a filename.

What about a `Linguist::Language['ruby'].detect_by_filename?('script.rb')` for instance?

And a more generic `Linguist::Language.detect_by_filename('script.rb') => :ruby` for instance?

Also, loading linguist takes ~2s on my computer, so having something like `require 'linguist/languages/ruby'` could potentially be much faster.

**Comment by pchaigno** [comment]
You can't always determine the language of a file from its name, but you could use the [Extension strategy](https://github.com/github/linguist/blob/4f11062304ae28b09a9b90c4536a92a27e142dcb/lib/linguist/strategy/extension.rb) to retrieve the list of candidate languages from the file extension.
