### ISSUE TITLE
My repository is detected as the wrong language

### ISSUE THREAD

**Issue by durul** [github/linguist#3461]
Hello, 

This is my repository https://github.com/durul/DRL-Theme-Manager. And I have added 
.gitattributes
*.rb linguist-language=Swift. 

But There is no change. I have been still seeing shell. 

I could not fix this problem. 

thanks.

**Comment by pchaigno** [comment]
It doesn't look like you have any `.rb` files. I could only find [two `.sh` Shell scripts](https://github.com/durul/DRL-Theme-Manager/search?l=shell)...

**Comment by durul** [comment]
Ok. Understood now. I fixed.

**Comment by pchaigno** [comment]
Don't forget you can also [tell Linguist to ignore `.sh` files](https://github.com/github/linguist#overrides) if that's what you want.
