### ISSUE TITLE
Language Stats Not Responding To Updated .gitattributes File

### ISSUE THREAD

**Issue by lots0logs** [github/linguist#3465]
The language stats for one of our repos are incorrect. They include a bunch of vendor javascript files. Some of those files have `.min.js` extensions so that in of itself should be enough for them to be excluded from the stats according to the Linguist docs. Still, I updated the `.gitattributes` file to mark the vendored files manually just like I've done in a few of our other repos. Except, it's not having any effect in the repo in question.

* [Repo Where It Doesn't Work](https://github.com/Antergos/lightdm-webkit2-greeter)
* [Repo Where It Works Properly](https://github.com/Antergos/Cnchi)
* [Another Repo Where It Works Properly](https://github.com/Antergos/antbs)

Please let me know if there is any other information I can provide that would be helpful in resolving the issue. Thanks!

**Comment by pchaigno** [comment]
These are the three files that contribute to the 37.79% of JavaScript in your repository:
```
themes/antergos/.tx/combine_translations.js
themes/antergos/js/greeter.js
web-greeter/resources/js/ThemeUtils.js
```
(I ran the last released version of Linguist against your repository to make sure.)

**Comment by lots0logs** [comment]
![homer-simpson-doh](https://cloud.githubusercontent.com/assets/4675662/22824330/1b74ac8a-ef4d-11e6-8284-03b4d54c3b93.gif)

Thanks :sweat_smile:
