### ISSUE TITLE
Supposedly a bug in modeline.rb

### ISSUE THREAD

**Issue by osorgin** [github/linguist#3467]
There appears to be a bug in [modeline.rb](https://github.com/github/linguist/blob/master/lib/linguist/strategy/modeline.rb) introduced in 5c19f1f.
```ruby
def self.call(blob, _ = nil)
-  Array(Language.find_by_alias(modeline(blob.data)))
+  header = blob.lines.first(SEARCH_SCOPE).join("\n")
+  footer = blob.lines.last(SEARCH_SCOPE).join("\n")
+  Array(Language.find_by_alias(modeline(header + footer)))
end
```
Looks like, instead of getting blob.data first, it tries to call .lines directly from Blob object. Currently, this causes a problem with updating github-linguist gem to version 4.8.5 and higher in GitLab Community Edition (more info [here](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/7270)).‌

This variant seems to work fine:
```ruby
 def self.call(blob, _ = nil)
   header = blob.data.lines.first(SEARCH_SCOPE).join("\n")
   footer = blob.date.lines.last(SEARCH_SCOPE).join("\n")
   Array(Language.find_by_alias(modeline(header + footer)))
 end
```
[test_modelines.rb](https://github.com/github/linguist/blob/master/test/test_modelines.rb) runs without errors in both cases though. I maybe overlooked something here, so would be nice if a more experienced Linguist contributor double-checked this and fixed if necessary.

**Comment by pchaigno** [comment]
`.lines` refers to [this method in `BlobHelper`](https://github.com/github/linguist/blob/0056095e8ce7fa731030b86f5e952bbe70a17b9e/lib/linguist/blob_helper.rb#L259-L290). How do you call `Linguist.detect`?

**Comment by osorgin** [comment]
It is called from the `.language` method of `BlogHelper`.
The file which triggers the error is [binary-1.bin](https://gitlab.com/gitlab-org/gitlab-test/blob/binary-encoding/encoding/binary-1.bin) used in [gitlab-ce/spec/controllers/blob_controller_spec.rb](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/spec/controllers/blob_controller_spec.rb). Below I attached a screenshot for reference (local GitLab GDK, trying to open this exact file).

However, I couldn't reproduce it by calling `.language` for this file in a local script, but the change in [5c19f1f](https://github.com/github/linguist/commit/5c19f1f546e56effbf1562f30c24042206a248fa) somehow broke the detection in the above case. Would be glad to know if there is nothing wrong in Linguist.

![gitlab gdk - binary-1 bin](https://cloud.githubusercontent.com/assets/20356328/23172487/f0998c56-f866-11e6-86db-00852e51f08a.png)

**Comment by lildude** [comment]
@osorgin do you have the full stack, in text form, for the failure that we can view?

**Comment by lildude** [comment]
Closing this issue as stale. Please feel free to re-open if you wish to continue it at some point in future.
