### ISSUE TITLE
Minified JS not detected

### ISSUE THREAD

**Issue by railix** [github/linguist#3486]
Hello, I have added a JS file, but the language stats are not detected:
https://github.com/railix/divPlayer/blob/master/divplayer.js
It is minified, but I would like it to be detected.  How can I achieve this?
.gitattributes is created with this content:
***.js linguist-language=JavaScript**
..but no effect.

**Comment by pchaigno** [comment]
Try:
```
*.js linguist-vendored=false
```

**Comment by railix** [comment]
No effect. It will still not show the JS language stats.

**Comment by pchaigno** [comment]
Oops, my bad. It should be:
```
*.js linguist-generated=false
```

**Comment by railix** [comment]
It works! Thanks pchaigno.

**Comment by pchaigno** [comment]
You're welcome!

**Comment by 0joshuaolson1** [comment]
I have the same problem, but I don't want to add a useless file to fix Linguist?

**Comment by pchaigno** [comment]
> I have the same problem, but I don't want to add a useless file to fix Linguist?

If it fixes an issue, it doesn't sound that useless to me :wink: 

> I wrote the file it apparently thinks is minified.

What qualifies as minified to you??

**Comment by 0joshuaolson1** [comment]
> If it fixes an issue, it doesn't sound that useless
> What qualifies as minified to you??
Linguist assumes minified == generated. It also assumes generated == not relevant to language statistics. By 'fix' I mean workaround.

**Comment by pchaigno** [comment]
> Linguist assumes minified == generated.

You minify your files manually?

**Comment by 0joshuaolson1** [comment]
[Code golf](https://esolangs.org/wiki/Golf)

**Comment by pchaigno** [comment]
Fair enough :smile: 

I'm afraid we don't have a wait to override this behavior other than using a `.gitattributes` file at the moment.

**Comment by 0joshuaolson1** [comment]
...which is misnamed anyway because this is a GitHub thing? :P

**Comment by pchaigno** [comment]
The overrides are, [the file is not](https://git-scm.com/docs/gitattributes).
