### ISSUE TITLE
Typescript language display incorrectly in status bar but detected correctly in language page

### ISSUE THREAD

**Issue by wcxaaa** [github/linguist#3499]
Hi!

One of my repo [wcnexus.com](https://github.com/wcxaaa/wcnexus.com) has a language proportion display issue, in which typescript takes up most of it, but in the end it shows css consists of 99%.

When I click css and turn to the language page, the language list on the left shows typescript indeed is the biggest part.

In the dev process, I mainly commit using [vscode](https://github.com/Microsoft/vscode) built-in git. Platforms are Windows 10 x64 and Ubuntu 16.04 x86_64. 

Later I did a testing, commiting a test ts file via Windows git. It has been recognized in the language page too, however does not appear in Language stats bar as well.

---

Same applies on committing via vanilla git on Ubuntu.

**Comment by lildude** [comment]
Looks like things are behaving correctly now:

<img width="999" alt="screen shot 2017-04-26 at 19 03 14" src="https://cloud.githubusercontent.com/assets/627280/25464785/177ba0a6-2ab3-11e7-8d1a-4f857fbfd03f.png">

Closing, but please feel free to re-open if this is still and issue.
