### ISSUE TITLE
Change fishshell language color.

### ISSUE THREAD

**Issue by jbucaran** [github/linguist#3503]
Hi :wave:! @arfon @pchaigno

I'd like to propose using a different color for the fishshell language. The current color is the same `#88E251` green used for Shell (bash/*sh).

It's not impossible to find similarities between both *sh scripts and fishshell scripts, but they are syntactically different. Fish is also not POSIX compatible. 

For this reason, I think it deserves its own color, just like PowerShell has its own color.

Maybe the color can be `#EC3C2D` orange/red used in the "official" logo.

![1828073](https://cloud.githubusercontent.com/assets/56996/23576122/9c24ad28-00df-11e7-99af-03a1cb8d03d6.png)

**Comment by Alhadis** [comment]
👋  Hey @jbucaran, thanks for the suggestion.

Differentiating between Fish-shell and Bourne-shell scripts would be an invitation for disaster, as both shell-flavours are similar enough to risk widespread misclassification. I imagine we'd quickly get a new swarth of issues reporting Bash-repos misclassified as Fishshell.

It's safer and simpler to keep shell-scripts lumped together as they are now; also note that the current definition of the "Shell" language isn't necessarily Bourne-specific.

> Fish is also not POSIX compatible.

Neither is Bash, or at least [many parts of it](http://mywiki.wooledge.org/Bashism). ;-)
