### ISSUE TITLE
Language Tab Inaccessible in Mobile Screen

### ISSUE THREAD

**Issue by C-F-4** [github/linguist#3505]
Language Tab shown on web UI of Github is not on Github for Mobile Website and requires almost 200% zoom to be clickable when viewed the Desktop Version on the Mobile Browser.

PS I'm not sure if this library is responsible for how the bar is rendered on the smaller screens.

**Comment by pchaigno** [comment]
> I'm not sure if this library is responsible for how the bar is rendered on the smaller screens.

It's not. You can take this to [GitHub staff](https://github.com/contact) :-)

**Comment by lildude** [comment]
As this isn't a Linguist issue, I'm closing this issue.
