### ISSUE TITLE
Language bar and statistics not aligned with top ten score and source code

### ISSUE THREAD

**Issue by BrainCrumbz** [github/linguist#3507]
Hello all

We searched around, asked [on StackOverflow](http://stackoverflow.com/questions/42544813/paths-not-excluded-from-github-language-statistics), updated `.gitattributes` a number of times, waited time until the stats could catch up with changes, but still there's something not clear in language stats for [NSpec](https://github.com/nspec/NSpec) repository.

The language bar on project home shows:

![lang-stats-bar](https://cloud.githubusercontent.com/assets/3185573/23588344/9ae5241e-01bc-11e7-8ee1-eac09a9951f1.png)

which does not respect the source code, given the following exclusions in *.gitattributes*:

```
# Exclude additional vendor directories from GitHub language statistics

.nuget/**                 linguist-vendored
libs/**                   linguist-vendored
NUnit.Runners*/**         linguist-vendored
packages/**               linguist-vendored
RubyInstallationFiles/** linguist-vendored
```

Then, clicking on HTML numbers on the bar, you see [this](https://github.com/nspec/NSpec/search?l=html):

![lang-stat-score](https://cloud.githubusercontent.com/assets/3185573/23588360/dd945ff0-01bc-11e7-82d5-95bf128221eb.png)

where HTML is not at all at the top. Also, the two files should anyway be part of a path excluded by *.gitatrributes*.
Did also a local check with `git check-attr` and the right files are flagged as *vendored*.

**[EDIT]** At some point also thought that it could be due to web site code in *gh-pages* branch, but that does not seem to be the case, also because site is Jekyll-generated and contains almost no HTML

What are we doing wrong here? Thanks!

**Comment by pchaigno** [comment]
[I ran the last released version of Linguist against your repository](https://gist.github.com/pchaigno/0cee2ddbf7b4e3a6977afa531da3878c). Apparently, the 61.2% of HTML come from [this HTML file](https://github.com/nspec/NSpec/blob/master/sln/src/NSpec/Domain/Formatters/Templates/TiddlyWiki_Template.html).
It looks like the search results in your repository are not up-to-date. This is happening increasingly often. @brandonblack Could there be some bug in github.com backend?

**Comment by BrainCrumbz** [comment]
Oh, I see. Thanks a lot for the pointer! It just was what we were after.

**Comment by rustamgaifullin** [comment]
Thanks for the pointer from me also! 
I had just 2 html files for testing purposes but they ruined my repository language statistic. 
For now in my profile it shows correct language but the language bar still shows old statistics (I guess it requires some times for update).

**Comment by lildude** [comment]
Looking at the repo now, it appears things are now behaving as you expect @BrainCrumbz. Accordingly, I'm going to close this issue, but please feel free to re-open if I've got it wrong.
