### ISSUE TITLE
Support for *.Rnw

### ISSUE THREAD

**Issue by konstunn** [github/linguist#3508]
Please add support for *.Rnw or provide some guildelines how should one deal with these files to take them into account of languages statistics.

**Comment by pchaigno** [comment]
Please see the [guidelines to add support for a new language to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). If the `.Rnw` language meets the requirement on in-the-wild usage, don't hesitate to open a pull request.

**Comment by konstunn** [comment]
Is it possible to classify and account different chunks of bytes within one source file? - Such as *.Rnw which contain TeX and R code together.

**Comment by pchaigno** [comment]
That's not currently possible with Linguist. Are you interested in highlighting the TeX and R chunks differently or is it just a matter of statistics?

**Comment by konstunn** [comment]
It's not just but is a matter of statistics, right. I've got many *.Rnw files in a number of repositories. And these files are not taken into account. So that it seems just like if I didn't write in R, but only in TeX.

**Comment by pchaigno** [comment]
Unfortunately, Linguist can only assign a single language to each file. If you'd prefer these files to be recognized as R, you can use [Linguist overrides](https://github.com/github/linguist#overrides).

I was asking because it may be possible to fix the highlighting issue at the grammar level (by defining a special grammar for `.Rnw` files that supports both R and TeX).

**Comment by konstunn** [comment]
Thanks. I've asked the question on StackOverflow [here](http://stackoverflow.com/questions/43123475/how-one-can-make-github-linguist-take-rnw-files-into-account-of-repository-lan). Now there is only a couple of comments. You can answer it there and get reputation.

**Comment by pchaigno** [comment]
Will do.
