### ISSUE TITLE
Register generated files via .gitattributes?

### ISSUE THREAD

**Issue by jelder** [github/linguist#3515]
We use a lot of code generation in our Elm project and the generated files can make it hard to read pull requests. They aren't documentation and `vendored` doesn't make sense here either. Is it possible to register generated files via .gitattributes? If not, would a pull request for this be welcomed?

**Comment by lildude** [comment]
> Is it possible to register generated files via .gitattributes?

Yup. You can do so using the [`linguist-generated`](https://github.com/github/linguist/blob/c0e242358af6a3ad0ace66e29b480d3f507917cb/lib/linguist/lazy_blob.rb#L47-L53) override.

> If not, would a pull request for this be welcomed?

It's possible, just not doc'd. We'd definitely welcome a PR. We don't shy away from PRs here 😉.  In this case it should only be documentation related.

**Comment by Caged** [comment]
This is resolved via https://github.com/github/linguist/pull/3588.  Thanks @jelder!
