### ISSUE TITLE
Invalid byte sequence error when reading files with malformed utf-8 sequences

### ISSUE THREAD

**Issue by mrorii** [github/linguist#353]
For example, running linguist on [this file](https://raw.github.com/leoniedu/CongressoAberto/a4785785cb37e8095893dc411f0a030a57fd30f8/CongressoAbertoWP/wp-includes/js/swfupload/swfupload.js) throws an invalid byte sequence error:

<pre>
$ wget https://raw.github.com/leoniedu/CongressoAberto/a4785785cb37e8095893dc411f0a030a57fd30f8/CongressoAbertoWP/wp-includes/js/swfupload/swfupload.js
$ linguist swfupload.js
/Users/orii/.rvm/gems/ruby-1.9.3-p286/gems/github-linguist-2.4.0/lib/linguist/blob_helper.rb:209:in `split': invalid byte sequence in UTF-8 (ArgumentError)
        from /Users/orii/.rvm/gems/ruby-1.9.3-p286/gems/github-linguist-2.4.0/lib/linguist/blob_helper.rb:209:in `lines'
        from /Users/orii/.rvm/gems/ruby-1.9.3-p286/gems/github-linguist-2.4.0/lib/linguist/blob_helper.rb:240:in `loc'
        from /Users/orii/.rvm/gems/ruby-1.9.3-p286/gems/github-linguist-2.4.0/bin/linguist:24:in `<top (required)>'
        from /Users/orii/.rvm/gems/ruby-1.9.3-p286/bin/linguist:23:in `load'
        from /Users/orii/.rvm/gems/ruby-1.9.3-p286/bin/linguist:23:in `<main>'
</pre>

**Comment by arfon** [comment]
I'm going to close this. Ruby 2.0 is nearly two years old now and I just don't see us investigating this any time soon sorry.

If anyone else wants to take a stab at this then please be my guest :smile:

**Comment by pchaigno** [comment]
@arfon I get this error on [the original file of this post](https://raw.github.com/leoniedu/CongressoAberto/a4785785cb37e8095893dc411f0a030a57fd30f8/CongressoAbertoWP/wp-includes/js/swfupload/swfupload.js) with Ruby 2.2:
```
$ ruby --version
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
```

**Comment by arfon** [comment]
Well then.

**Comment by echatman** [comment]
I have also encountered this many times using ruby 2.2. Here is a recent stack trace:

    $ linguist swfupload.js 
    /var/lib/gems/2.2.0/gems/github-linguist-4.2.7/lib/linguist/blob_helper.rb:266:in `split': invalid byte sequence in UTF-8 (ArgumentError)
	    from /var/lib/gems/2.2.0/gems/github-linguist-4.2.7/lib/linguist/blob_helper.rb:266:in `lines'
	    from /var/lib/gems/2.2.0/gems/github-linguist-4.2.7/lib/linguist/blob_helper.rb:283:in `loc'
	    from /var/lib/gems/2.2.0/gems/github-linguist-4.2.7/bin/linguist:51:in `<top (required)>'
	    from /usr/local/bin/linguist:23:in `load'
	    from /usr/local/bin/linguist:23:in `<main>'

**Comment by pyyzcwg2833** [comment]
I still can confirm this error.
When I run the following command, my program crashed.
```sh
github-linguist Inderxer.asp.txt
```
BTW, The encoding for `Inderxer.asp.txt`  is GB2312

**Comment by lildude** [comment]
This has been resolved by https://github.com/github/linguist/pull/4730 which is now live on GitHub.com. Closing.
