### ISSUE TITLE
BBC Basic highlighting 

### ISSUE THREAD

**Issue by Comportment** [github/linguist#3537]
Would love some love for the BBC files.
https://github.com/Comportment/BASICally-games/blob/master/Snake.bbc

![img_0517](https://cloud.githubusercontent.com/assets/26597492/24248389/1711d330-0fc7-11e7-8668-60143dac5f3a.JPG)

**Comment by pchaigno** [comment]
Please see the [guidelines to add support for a new language to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). If BBC meets the requirement on in-the-wild usage, don't hesitate to open a pull request.
