### ISSUE TITLE
Incorrect syntax highlighting

### ISSUE THREAD

**Issue by revolter** [github/linguist#3538]
[This file][1] has incorrect syntax highlighting after this line:

    defaults write com.apple.Safari ProxiesInBookmarksBar "()"

  [1]: https://github.com/mathiasbynens/dotfiles/blob/dd808d5d50912afbb9c78d359a8e4f773621f769/.macos#L488

_Moved from https://github.com/textmate/shellscript.tmbundle/issues/37_

**Comment by pchaigno** [comment]
We're now using [atom/language-shellscript](https://github.com/atom/language-shellscript) instead of [textmate/shellscript.tmbundle](https://github.com/textmate/shellscript.tmbundle). It think your bug corresponds to atom/language-shellscript#70...?

**Comment by revolter** [comment]
Looks like it's the same issue indeed, thank you.
