### ISSUE TITLE
Typescript files are hidden in PR and diffs

### ISSUE THREAD

**Issue by diestrin** [github/linguist#3539]
I have no `.gitattributes` file, but github is hiding all my TS files in PR and diffs.

![typescript-hidden-files](https://api.monosnap.com/rpc/file/download?id=cyx8KmwJ45QMTrQiKOTyPHm5EnyJIr)

**Comment by lildude** [comment]
Are you able to link to the repository in question so we can take a peek and see what's going on?

**Comment by diestrin** [comment]
I found the issue, sorry I didn't close this before.
The problem was I have my modules in a folder called src/node_modules so it was being parsed as lib code. `src/node_modules/* linguist-generated=false` fixed it
