### ISSUE TITLE
Wrong language for pgloader project

### ISSUE THREAD

**Issue by dimitri** [github/linguist#3540]
Hi,

While linguist seems to do a good job at profiling individual files in the pgloader project as shown at https://github.com/dimitri/pgloader/search?l=plpgsql in the Languages box on the left, it still fails to properly figure out it's mainly a Common Lisp project and shows it as PLpgSQL for some reason: https://github.com/dimitri/pgloader. The stated PLpgSQL 83.6% refers to a single 34 lines long file when clicked...

Can you fix it?

**Comment by pchaigno** [comment]
The search results are not up-to-date, but the statistics are. I ran Linguist against your repository locally and it found the following SQL files:
```
test/geolite.sql
test/sqlite/Chinook_Sqlite.sql
test/sqlite/Chinook_Sqlite_AutoIncrementPKs.sql
```
I'm guessing the two `sqlite/` files are quite large and contribute to te 83.6% PLpgSQL

**Comment by dimitri** [comment]
Those files are test cases initialisation data. How can I tell that to linguist?

**Comment by pchaigno** [comment]
You can mark those files as vendored using [Linguist overrides](https://github.com/github/linguist#overrides).

**Comment by dimitri** [comment]
I failed to install GitHub-linguist locally with `brew gem install` then `brew bundle exec`, so I hope the patch is good. What's the usual time to refresh on the GitHub repositories?

**Comment by dimitri** [comment]
Ok seems it's done already. Thanks!
