### ISSUE TITLE
Support for Python highlighting in .pyi files

### ISSUE THREAD

**Issue by dmoisset** [github/linguist#3547]
Some time ago, python standardized (PEP-484) the use of ".pyi" extension for type stub files. These are syntactically Python files but currently github shows them without any highlighting at all (see for example https://github.com/python/typeshed/blob/master/stdlib/2and3/argparse.pyi , or most files in that repo). Would it be possible to enable python language for that extension? I see a few thousand of files in github already using this.

**Comment by pchaigno** [comment]
Please see the [guidelines to add support for a new extension to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language). It's rather straightforward and I can help if needed :-)
