### ISSUE TITLE
Forcing syntax highlighting for file X

### ISSUE THREAD

**Issue by ThomDietrich** [github/linguist#3551]
This is an example and can be adopted to a lot of cases.

I've got a samba configuration file ([smb.conf](https://github.com/openhab/openhabian/blob/master/includes/smb.conf)) and it ends with the vim modeline `# vim: filetype=samba`, which is necessary as the filename can change and vim would identify it incorrectly.

Is there a way to overwrite the Linguist syntax highlighting (on GitHub, see link above) with a specific language (in this case "ini") without compromising the vim modeline / function. The setting `smb.conf linguist-language=ini` in gitattributes doesn't seem to have any effect.

**Comment by pchaigno** [comment]
> The setting `smb.conf linguist-language=ini` in gitattributes doesn't seem to have any effect.

Do you have a link to the repository where you tried that? You might need to state the absolute path.

**Comment by ThomDietrich** [comment]
The link is hidden behind smb.conf above :)
I've tried the absolute path as well. Let me re-add this change so you can have a look.

**Comment by ThomDietrich** [comment]
@pchaigno any other way I can help resolve that issue?

**Comment by ThomDietrich** [comment]
@pchaigno not trying to be pushy ... :)

**Comment by pchaigno** [comment]
@ThomDietrich Sorry for the delay :S

The file looks highlighted [as expected](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=source.ini&grammar_url=&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fopenhab%2Fopenhabian%2Fblob%2Fmaster%2Fincludes%2Fsmb.conf&code=) (meaning, as an INI file). What were you expecting to be different?

**Comment by ThomDietrich** [comment]
@pchaigno now it is indeed working, even without the gitattributes setting. I swear it didn't when I was creating the issue :sweat_smile:
I'll close the issue, reopen if I encounter the problem again. Thanks for your help!

**Comment by ThomDietrich** [comment]
Everyone encountering similar issues: settings inside .gitattributes need some time to propagate through GitHub. Just give it a few hours.
