### ISSUE TITLE
PHP syntax broken with ' and "

### ISSUE THREAD

**Issue by fulldecent** [github/linguist#3555]
Please see here 

> https://github.com/Purus/MailChimp-PHP-API-Simple-Example/blob/master/Service.php#L49

The line that breaks it is:

    if ($result['msg'] == "Everything's Chimpy!") {

**Comment by pchaigno** [comment]
There's a missing double quote here: https://github.com/Purus/MailChimp-PHP-API-Simple-Example/blob/master/Service.php#L13
