### ISSUE TITLE
Idris highlighting is highly incorrect

### ISSUE THREAD

**Issue by be5invis** [github/linguist#3557]
Missing features:

- `interface`, `implementation`, `namespace`, `export`, and `rewrite … in …` are not colored as keywords
- Identifier names ending with multiple `'`s will cause all text after it being colored as string.
- Does not support `'identifier`, "label-as-type".

cc. @edwinb

**Comment by pchaigno** [comment]
Linguist only selects the grammar to use for highlighting. For Idris, GitHub uses [idris-hackers/idris-sublime](https://github.com/idris-hackers/idris-sublime). You should open an issue there if there isn't already one.

**Comment by be5invis** [comment]
@pchaigno I think the idris-sublime project is discontinued since 2015, their syntax is outdated and may not being updated.
An updated syntax is here: https://github.com/zjhmale/vscode-idris/blob/master/syntaxes/idris.json

**Comment by pchaigno** [comment]
> I think the idris-sublime project is discontinued since 2015, their syntax is outdated and may not being updated.

There was some activity (PR merged) ~1 month ago...

> An updated syntax is here: https://github.com/zjhmale/vscode-idris/blob/master/syntaxes/idris.json

If you can demonstrate the improvement using [Lightshow](https://github-lightshow.herokuapp.com/), we'll gladly welcome a pull request!

**Comment by be5invis** [comment]
@pchaigno The syntax has not been changed for three years.

**Comment by pchaigno** [comment]
Sure. I just meant that it's an active project; if you submit a pull request, it's likely to get reviewed. Then again, if [zjhmale/vscode-idris](https://github.com/zjhmale/vscode-idris) is far ahead, feel free to open a pull request. I can help if necessary.

**Comment by be5invis** [comment]
cc. @zjhmale
