### ISSUE TITLE
Library not being recognized as JavaScript

### ISSUE THREAD

**Issue by lansana** [github/linguist#3558]
No language is set on my project at https://github.com/lansana/chatty

The language should be JavaScript.

Can someone look into this? Thank you.

**Comment by Alhadis** [comment]
👋  Hi @lansana,

Linguist skips [directories with certain names](https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml) when calculating usage statistics. In your case, the folder name `dist` is what's causing the contents to be ignored by the classifier.

You can fix this by adding a `.gitattributes` file to the root of your project, containing the following line:

~~~
dist/* linguist-vendored=false
~~~

More information on `.gitattributes` can be [found here](https://github.com/github/linguist#overrides).

**Comment by lansana** [comment]
Awesome, that solved it for me. Although I have more CSS than JS,so I used
`dist/js/*` instead because I want it to be recognized as JavaScript.

Thanks!

**Comment by Alhadis** [comment]
You're most welcome!
