### ISSUE TITLE
wrong language on new repo

### ISSUE THREAD

**Issue by depazsierra** [github/linguist#3561]
My repo https://github.com/depazsierra/zoiperExample is only set to "C" and the mainly language of the project is swift & objective - c

**Comment by pchaigno** [comment]
I'm guessing this is because of [these two huge files](https://github.com/depazsierra/zoiperExample/search?l=c). You can tell Linguist to ignore them using [Linguist overrides](https://github.com/github/linguist#overrides).

**Comment by Caged** [comment]
👋 @depazsierra, I recommend @pchaigno's suggestion as a resolution here.

**Comment by depazsierra** [comment]
Thanks @pchaigno / @Caged !
