### ISSUE TITLE
JSON output not working when running on a single file

### ISSUE THREAD

**Issue by armijnhemel** [github/linguist#3562]
I tried the command line interface to linguist (updated to master) and JSON output does not seem to be working when trying to process a single file:

$ ./bin/linguist ./grammars.yml --json
grammars.yml: 693 lines (692 sloc)
  type:      Text
  mime type: text/x-yaml
  language:  YAML

The help text seems to suggest that JSON output should be available:

$ ./bin/linguist -h
  Linguist v5.0.8
  Detect language type for a file, or, given a directory, determine language breakdown.

  Usage: linguist <path>
         linguist <path> [--breakdown] [--json]
         linguist [--breakdown] [--json]

**Comment by armijnhemel** [comment]
Hm, it appears that some output went missing. Anyway, once you run linguist -h it should be clear that the --json option is also advertised for individual paths, but that's not working.

**Comment by pchaigno** [comment]
Thanks for reporting the issue.
We'd welcome a pull request to fix this!

**Comment by armijnhemel** [comment]
I'd like to but unfortunately Ruby is not my forte :(
