### ISSUE TITLE
Syntax highlighting for PHP 7 does not work well

### ISSUE THREAD

**Issue by stof** [github/linguist#3565]
the grammar repo used for PHP (https://github.com/brandonblack/php.tmbundle) is not the source repo of the grammar, but a fork of https://github.com/textmate/php.tmbundle

The fork is behind the source repo by 8 commits. And some of these commits are about adding support for PHP 7 features.
Could you switch to the source repo for the PHP grammar instead ?

**Comment by stof** [comment]
note that PHP 7 syntax highlighting is still not perfect in the source repo (there are some bugs reported on it), but it is better than in the fork (the bug annoying me most is not yet fixed though 😢)

**Comment by brandonblack** [comment]
@pchaigno thanks for flagging. I am no longer helping maintain linguist, but I think @lildude should be familiar with this problem and might be able to help.

**Comment by lildude** [comment]
@stof I can't think of any reason why we can't or shouldn't revert to using the upstream grammar.  Wanna open a PR for the switch?

**Comment by stof** [comment]
@lildude done
