### ISSUE TITLE
Add highlight support for "module-info.java"

### ISSUE THREAD

**Issue by reebr** [github/linguist#3566]
[module-info][1] is a new source file used on Java projects for module declaration. It will be released on jdk9 ([7/17/2017][2]) as part of [project Jigsaw][3]. For now, the file does not have hightlight support as you can see [here][5].

I don't know about this file yet, but reading [the specification][4]:

> **`open`, `module`, `requires`, `transitive`, `exports`, `opens`, `to`, `uses`, `provides`, and `with` are restricted keywords** (...)

> (...) **A module name consists of one or more Java identifiers separated by "." tokens**. In the declaration of a module name (after module) and in any use of a module name (by requires, exports, or opens), every identifier in the name must end with a Java letter, or a compile-time error occurs.

Annotations and `static`/`transitive` modifiers are allowed too.

This information is sufficient to add support for this file? 

_- cheers._

[1]:https://github.com/reebr/playground/blob/master/java/jigsaw-calculator/src/calculator/classes/module-info.java
[2]:http://www.java9countdown.xyz/
[3]:http://openjdk.java.net/projects/jigsaw/quick-start
[4]:http://cr.openjdk.java.net/~mr/jigsaw/spec/lang-vm.html#jigsaw-1.1
[5]:https://github.com/search?utf8=%E2%9C%93&q=module-info+extension%3Ajava&type=Code&ref=advsearch&l=&l=

**Comment by lildude** [comment]
Linguist uses the [TextMate Java bundle](https://github.com/textmate/java.tmbundle) for syntax highlighting. In order to get highlighting support for the new module-info source file, you'll need to open an issue on the TextMate repo.  Once the bundle has been updated, it'll be pulled in by Linguist.
