### ISSUE TITLE
C repo partially misclassified as C++

### ISSUE THREAD

**Issue by rafael-santiago** [github/linguist#3568]
Hi there,

One of my repositories has only [C code](https://github.com/rafael-santiago/kryptos/) but the Linguist is pointing also C++ sources.

The repo has some macros that could remember a "CPP from stone age" but I am not tracking any ``.C|.CC|.cc|.[cC][pP][pP]`` file just ``.c`` files. Considering this, maybe the heuristics could be improved.

**Comment by lildude** [comment]
> Considering this, maybe the heuristics could be improved.

I think you're right on this point. We'll happily accept a PR for these improvements.

**Comment by rafael-santiago** [comment]
Okay. I proposed some improvements [here](https://github.com/github/linguist/pull/3585).

**Comment by gdonald** [comment]
Similar problem here:

https://github.com/gdonald/cpama/search?l=c%2B%2B

No C++ files or .hh file extensions in my repo but quite a few .h files are being mis-labled as C++.  Github Support asked me to post my info here.
