### ISSUE TITLE
LabVIEW files not being recognised

### ISSUE THREAD

**Issue by hsmistry** [github/linguist#3576]
Hi,

I have noticed that the LabVIEW vi and llb files are not being detected as LabVIEW files in our repository:

https://github.com/picotech/picosdk-ni-labview-examples

I will be adding a .gitattributes file but is it possible for them to be automatically detected?

Thanks,

**Comment by pchaigno** [comment]
Yes, it's possible if they meet the requirement on in-the-wild usage. See the [guidelines to add support for a new extension to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language).
