### ISSUE TITLE
Feature request: make linguist capable of being run on non-repositories

### ISSUE THREAD

**Issue by fusion809** [github/linguist#3577]
Hi,

This tool is great, except there is one shortcomming, namely that it seems to only be able to be run on git repositories. I have source code directories locally that I'd rather not commit to a git repository, but I'd still like to get a source code composition breakdown using this tool. Presently when I run `linguist` on a non-repository directory I get the error:

```bash
/home/fusion809/.gem/ruby/2.1.0/gems/github-linguist-5.0.8/bin/linguist:27:in `new': Could not find repository from '.' (Rugged::RepositoryError)
```

Thanks for your time,
Brenton

**Comment by larsbrinkhoff** [comment]
See #3563.

**Comment by PuZZleDucK** [comment]
I've hacked together a simple script that allows linguist to run on non repos, but it's very much a hack that temporarily creates a local repo then removes it after analysis:
https://gist.github.com/PuZZleDucK/a45fd1fac3758235ffed9fe0e8aab643

**Comment by trevor** [comment]
I'd like to see this too. I still keep version 2.12 installed since it has this capability.

**Comment by pchaigno** [comment]
I'm pretty sure we'd welcome a pull request to implement this if it's not too invasive (/cc @lildude for confirmation). In the meantime, creating a git repository and deleting it after the analysis as suggested by @PuZZleDucK is a quick workaround.

**Comment by pchaigno** [comment]
Closing as this is not something we need ourselves, but if anyone is interested in this feature, they're welcome to submit a pull request!
