### ISSUE TITLE
wrong syntax high lighting

### ISSUE THREAD

**Issue by toralf** [github/linguist#3581]
IMO there's a bug at the used syntax grammers, because both expressions (below) are valid sed expressions (although the non-fixed version wasn't what I wanted)

this foolished the syntax highlighting : sed -i ... -e 's,[()], ,g'
this not: sed -i ... -e 's,[()], ,g'

An example is in https://github.com/toralf/tinderbox/commit/8949694523dca46029dc0b644609eef63a58e567
Before my commit there happpend a wrong colour rendering from around line 456 till around line 582.

**Comment by lildude** [comment]
Linguist uses the [Atom language-shellscript package](https://github.com/atom/language-shellscript) for syntax highlighting. If there is a problem with the syntax highlighting, you'll need to open an issue on that repo to have it rectified.  Once the package has been updated, it'll be pulled in by Linguist.
