### ISSUE TITLE
Jupyter Notebook repo was defined as HTML

### ISSUE THREAD

**Issue by kuznetsovn** [github/linguist#3596]
in the root folder there are only *.ipynb
but there was a folder html_versions_of_ipynb with html copies of the notebooks
that's why, as I see, your algo defines the repo as HTML
currently I'm deleting the folder with html copies but the issue is still actual

https://github.com/kuznetsovn/PZZ
![2017-05-02 10 37 56](https://cloud.githubusercontent.com/assets/16565318/25608424/6e99b052-2f23-11e7-9154-76be1b81ef82.png)

**Comment by kuznetsovn** [comment]
deleted the only folder with html and.. language was not fixed :(

**Comment by lildude** [comment]
The clarification is happening like this because of these two html files:

```
data_progress/negative.html
data_progress/positive.html
```

For ref:

```
$ ~/github/linguist/bin/linguist ./ --breakdown
80.11%  HTML
19.88%  Jupyter Notebook
0.00%   Shell

Jupyter Notebook:
1. extract data from finereader.ipynb
2. extract data from acrobat.ipynb
3. add features.ipynb
4. add coordinates.ipynb
5. prepare map data.ipynb
6. analytics.ipynb
7. heatmap.ipynb

Shell:
all_ipynb_to_html.sh

HTML:
data_progress/negative.html
data_progress/positive.html
$
```

Of those two HTML files, the first one is over 4MB in size which is considerably larger than the total size of all your `.ipynb` files combined:

```
$ ls -lhS **/*.(html|ipynb)
-rw-r--r--  1 lildude  staff   4.2M  2 May 09:44 data_progress/negative.html
-rw-r--r--  1 lildude  staff   615K  2 May 09:44 data_progress/positive.html
-rw-r--r--  1 lildude  staff   432K  2 May 09:41 3. add features.ipynb
-rw-r--r--  1 lildude  staff   277K  2 May 09:41 2. extract data from acrobat.ipynb
-rw-r--r--  1 lildude  staff   206K  2 May 09:41 5. prepare map data.ipynb
-rw-r--r--  1 lildude  staff   118K  2 May 09:41 6. analytics.ipynb
-rw-r--r--  1 lildude  staff    97K  2 May 09:41 4. add coordinates.ipynb
-rw-r--r--  1 lildude  staff    54K  2 May 09:41 7. heatmap.ipynb
-rw-r--r--  1 lildude  staff    30K  2 May 09:41 1. extract data from finereader.ipynb
$
```

If you don't want the HTML files to count, you'll need to implement a [manual override](https://github.com/github/linguist#overrides).

**Comment by kuznetsovn** [comment]
Ok, thanks for such quick and comprehensive reply!
I've just read the readme, I should have done that earlier
