### ISSUE TITLE
exclude Maven project resources

### ISSUE THREAD

**Issue by IgorRodchenkov** [github/linguist#3598]
Please configure it to ignore files in a maven project's resources folders (usually - src/main/resources, src/test/resources).

**Comment by lildude** [comment]
We'd certainly welcome a PR to add these directories to the https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml file if you're 100% sure they should be ignored across all repos, like the other directories listed in that file.

In the mean time, you can do this for your own repo with a [manual over-ride](https://github.com/github/linguist#overrides) by setting these directories as vendored.
