### ISSUE TITLE
Short Rust files misclassified as RenderScript

### ISSUE THREAD

**Issue by newpavlov** [github/linguist#3600]
[Files in question.](https://github.com/RustCrypto/hashes/search?l=renderscript)

**Comment by lildude** [comment]
Looks like the files are too small and don't have any of the characteristics we use to differentiate Rust from RenderScript at https://github.com/github/linguist/blob/master/lib/linguist/heuristics.rb#L407-L413 so is falling through to the classifier which in turn is only just classifying the files as RenderScript:

```
$ LINGUIST_DEBUG=1 ~/github/linguist/bin/linguist ./hashes/gost94/src/cryptopro.rs
cryptopro.rs: 13 lines (11 sloc)
  type:      Text
  mime type: application/rls-services+xml
RenderScript =   -158.368 +  -6.808 =   -165.177
      Rust =   -162.173 +  -6.403 =   -168.576
  language:  RenderScript
$ LINGUIST_DEBUG=1 ~/github/linguist/bin/linguist ./hashes/gost94/src/s2015.rs
s2015.rs: 13 lines (11 sloc)
  type:      Text
  mime type: application/rls-services+xml
RenderScript =   -158.368 +  -6.808 =   -165.177
      Rust =   -162.173 +  -6.403 =   -168.576
  language:  RenderScript
$ LINGUIST_DEBUG=1 ~/github/linguist/bin/linguist ./hashes/gost94/src/test_param.rs
test_param.rs: 13 lines (11 sloc)
  type:      Text
  mime type: application/rls-services+xml
RenderScript =   -158.368 +  -6.808 =   -165.177
      Rust =   -162.173 +  -6.403 =   -168.576
  language:  RenderScript
$
```

The decision to compare Rust to RenderScript is initially being made off the file extension.

You can help improve the classification by submitting some more real-world Rust examples.

Until then, a [manual override](https://github.com/github/linguist#overrides) is the only option to get these picked up as Rust.

**Comment by newpavlov** [comment]
I am not familiar with RenderScript, but based on a cursory search it seems it does not have anything like Rust macros. (i.e. `gost94_impl!(...)`) So maybe it's worth to add macro detection heuristic? Either way manual override will be sufficient for me, so if you want you can close this issue.

**Comment by lildude** [comment]
:cool:  I know there is some work on the horizon to improve the language detection so I'm going to close this now.
