### ISSUE TITLE
Highlighting of PHP code is broken in diffs

### ISSUE THREAD

**Issue by stof** [github/linguist#3601]
A few days ago, highlighting of PHP code was mostly working in PR diffs. Now, the diff breaks on the PHP opening tag.
The difference comes probably from the switch to the upstream PHP bundle (done in #3575). While the upstream repo contains some fixes to support new PHP 7.1 features, it also includes some commits affecting the matching of the PHP open tag according to the history: https://github.com/brandonblack/php.tmbundle/compare/master...textmate:master

Some of these commits may be incompatible with the way Github uses the bundle

**Comment by kevingimbel** [comment]
As far as I can see PHP highlighting is completely broken as of now. Both Markdown-based highlighting (Wiki, README.md,...) as well as the actual code inside of files is broken, only showing a red `<` and black-on-white code.

**Comment by segadora** [comment]
All the colors are gone

**Comment by lildude** [comment]
Blast!!! This is my fault. I updated github.com to the latest linguist build this morning :gb: time.  We've got a test in place to catch this issue but it seems it doesn't catch it in diffs 😞

**Comment by samsonasik** [comment]
if the code is exactly one line after php open tag, it shows the highlight, eg:

<?php
namespace Foo;

and it not work if there is one line after php open tag, eg:

<?php

namespace Foo;

**Comment by lildude** [comment]
@samsonasik Whoops, the code in your comment has been swallowed. Can you wrap it in backquotes etc to show the code.

**Comment by samsonasik** [comment]
@lildude I've updated

**Comment by samsonasik** [comment]
oh, it seems both are not working right now ( the first one was working a few hours ago )

**Comment by samsonasik** [comment]
It seems my file was show the hightlight because of it "Executable File" like below screenshot:

![screen shot 2017-05-05 at 10 46 53 pm](https://cloud.githubusercontent.com/assets/459648/25753283/19ba41ea-31e5-11e7-9734-83bc526a84ab.png)

**Comment by lildude** [comment]
This has now been resolved on github.com by reverting back to linguist v5.0.8.  I'll continue testing 5.0.10 and see if I can workout why the upstream bundle keeps breaking PHP syntax highlighting.
