### ISSUE TITLE
New PHP syntax highlighting code is displaying incorrectly

### ISSUE THREAD

**Issue by cubiclesoft** [github/linguist#3602]
When using the three-backtick + 'php' indicator for PHP code in a code snippet, red blocks (I assume syntax "errors") now appear:

```php
<?php
	require_once "support/http.php";

	$url = "https://www.youtube.com/watch?v=dQw4w9WgXcQ";
	$parts = HTTP::ExtractURL($url);
	if ($parts["host"] === "www.youtube.com" && isset($parts["queryvars"]["v"]))
	{
		$videoid = $parts["queryvars"]["v"];
		if ($videoid === "dQw4w9WgXcQ")  echo "You're going to love this!";
	}
?>
```

Oddly, the above looks fine in its source context:

https://github.com/cubiclesoft/ultimate-web-scraper/blob/master/docs/http.md#httpextracturlurl

**Comment by cubiclesoft** [comment]
Probably related to #3601.

Markdown results in pregenerated HTML on GitHub, so GitHub will need to either regenerate those pages once the issue is fixed or shrug their shoulders and wait for another commit to affected repos to fix the issue.

This:

https://github.com/cubiclesoft/php-flexforms/blob/master/docs/flex_forms.md

Indicates that even explicit PHP mode is falling back to or selecting HTML instead, which explains why the syntax highlighting sees the opening `<?php` as an invalid HTML tag.  The HTML tags have correct-ish syntax highlighting applied.  I originally thought that this was a syntax highlighting issue with mixed PHP + HTML, but it now appears to just be a problem with PHP.  The earlier commit that didn't mangle highlighting is probably cached content that was generated before the breakage.

**Comment by lildude** [comment]
Thanks @cubiclesoft. This is my fault. I'm working on reverting https://github.com/github/linguist/pull/3575 now.

Closing in favour of https://github.com/github/linguist/issues/3601

**Comment by lildude** [comment]
This has now been resolved on github.com by reverting back to linguist v5.0.8.  I'll continue testing 5.0.10 and see if I can workout why the upstream bundle keeps breaking PHP syntax highlighting.
