### ISSUE TITLE
Puppet is often misclassified as many different languages

### ISSUE THREAD

**Issue by Caged** [github/linguist#3605]
We've noticed internally that Puppet is often misclassified as Pascal.  After [a little further digging](https://github.com/search?l=Pascal&q=extension%3App+include&type=Code&utf8=%E2%9C%93), it looks like Puppet is misidentified as a host of different languages from Pascal to Ruby. 

Prior art:
https://github.com/github/linguist/pull/2333
https://github.com/github/linguist/pull/2031
https://github.com/github/linguist/pull/1267

**Comment by Caged** [comment]
Quick update...It appears most of the Ruby classifications are correct if we're looking at the vim modeline.  Even though they are puppet, the author or authoring application tagged them as ruby. The Haskell classifications also appears to be correct.

**Comment by smola** [comment]
It seems the main problem are these Puppet files that have only `include foo` lines. Adding a simple sample seems to solve the problem at the classifier (as in #3606).

**Comment by pchaigno** [comment]
The new pull request at #4289 should fix this. @Caged I'd love a review if you've got the bandwidth!
