### ISSUE TITLE
Upstream PHP grammar breaks syntax highlighting on github.com

### ISSUE THREAD

**Issue by lildude** [github/linguist#3607]
The PHP grammar has been causing problems with PHP snippets on github.com for quite some time and we've avoided this for the most part by _not_ updating the grammar and instead have been relying on a fork (https://github.com/brandonblack/php.tmbundle) taken at a known good point.

This isn't a good long term solution.

https://github.com/github/linguist/pull/3575 switched us back to the upstream grammar and this didn't exhibit any problems during manual and automated testing both within Linguist and on github.com so I went ahead and deployed the change but some caching or something (not sure yet what) resulted in breakage later in the day leading to https://github.com/github/linguist/issues/3601 and https://github.com/github/linguist/issues/3602 and a ton of support tickets.

Opening this for my own reference and to track my findings.

/cc @stof FYI

**Comment by pchaigno** [comment]
From #3601:
> https://github.com/brandonblack/php.tmbundle/compare/master...textmate:master
Some of these commits may be incompatible with the way Github uses the bundle

I don't see anything specific to GitHub's regex engine, but @Alhadis is the expert.

**Comment by lildude** [comment]
I've looked into this this morning and I've worked out it's https://github.com/brandonblack/php.tmbundle/commit/9cfcc6d3c0fb76ef37232e28a4380f698f46ebcd that is breaking things.

Changing that line to: 

```
"text.html.* - (meta.embedded | meta.tag), L:^text.html meta.tag, L:text.html.php source.js": {
```

... solves the problem.

I'll do more digging later.

**Comment by lildude** [comment]
I can't find any references or examples suggesting this new key is valid so I've opened https://github.com/textmate/php.tmbundle/issues/77 questioning it.

As a side thought, I wonder if it may be worth switching to the [atom language-php grammar](https://github.com/atom/language-php).  It works as we expect as it still uses the original injection key, though I'm not sure if it's in sync with the TextMate bundle it was converted from.

**Comment by Alhadis** [comment]
Atom's grammar is probably much more up-to-date and maintained.

The injection mechanism has always puzzled me, though.

**Comment by Ingramz** [comment]
Last time I synced Atom's php grammar was in 2015 and since then there have been not that many modifications on the TextMate side. I can do another sync if needed.

You can expect Atom's injection selector to stay the same for a while, because Atom does not recognize `^` and `$` anchors in scope selectors yet, because originally they were thought to be unnecessary. I have a prototype, which has those implemented, so Atom might also support those soon as well, but there's still some work that needs to be done before I can propose this to get merged.

Could the issue be here that the scope selector implementation used on GitHub does not support these anchors?

**Comment by lildude** [comment]
> Could the issue be here that the scope selector implementation used on GitHub does not support these anchors?

Yeah, I think that may be it.

**Comment by lildude** [comment]
We've worked it out. This is indeed a problem with the GitHub parser. We had the functionality there already, we just had an off-by-one error 😂. This may affect other grammars in yet-to-be-noticed ways.

A fix is coming to GitHub 🔜..

Once it lands, we can switch back to the upstream TextMate bundle... assuming peeps are happy with that rather than favouring a switch to the Atom bundle.

**Comment by lildude** [comment]
And we're all fixed on GitHub.com.  Thanks for the candid feedback too @Ingramz. I'm going to revert my previous revert to bring us back to using the upstream TextMate grammar.
