### ISSUE TITLE
Are exceptions in injected grammar scopes applied?

### ISSUE THREAD

**Issue by nwhetsell** [github/linguist#3612]
I doubt *exception* is the right word for these, so here’s an example. Say you want to add some highlighting to a pre-existing grammar, in its `foo.bar.grammar` scope. My understanding is that one way to do this is with an injection like this:

```cson
injections:
  "foo.bar.grammar":
    patterns: [
      {
        name:  "my.addition"
        match: "some-regex"
      }
    ]
```

Now say, after doing this, you realize that you *don’t* want your extra highlighting in comments or strings. To keep your highlighting out of comments and strings, you could write:

```cson
injections:
  "foo.bar.grammar -(comment | string)":
    patterns: [
      {
        name:  "my.addition"
        match: "some-regex"
      }
    ]
```

I’m calling that `-(comment | string)` thing an exception, because the result is to put highlighting in everything *except* comments and strings.

Does Linguist apply exceptions when it performs syntax highlighting? [Here](https://github-lightshow.herokuapp.com/?utf8=✓&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fcdibbs%2Flanguage-jison%2Fmaster%2Fgrammars%2Fjison.cson&grammar_text=&code_source=from-text&code_url=https%3A%2F%2Fraw.githubusercontent.com%2FGerHobbelt%2Fjison%2Fmaster%2Fexamples%2Fcompiled_calc_BURG.jison&code=%25%25%0D%0Aempty%3A+%25empty%0D%0A%7B%0D%0A++console.log%28%23YES%29%3B%0D%0A++%2F%2F+comment+%23NO+comment+%23NO%23+comment%0D%0A++%27string+%23NO+string+%23NO%23+string%27%3B%0D%0A%7D%0D%0A) is an example on Lightshow where it doesn’t look like it. In Atom, the same example, with the same grammar, shows comments and strings as I’d expect (without extra highlighting).

**Comment by Ingramz** [comment]
I had the same problem recently. When I had `L:a - (b | c)` as the selector for injection, GitHub recognized it differently from Atom. I have to note that Atom's implementation of scope selectors is somewhat broken at the moment and I've been working on fixing that, but despite that even with my fixes applied, that specific selector seems to function the way it used to with the currently used implementation. I have not tested this with TextMate yet, so even my implementation could be right now incorrect.

If you want a quick fix and do not really care whether it is actually the correct thing, then `L:(a - (b | c))` or `a - (b | c)` should do the trick, but I would consider testing whether `L:a - (b | c)` works in TextMate or Sublime Text and then start drawing conclusions about which implementation is handling them incorrectly.

**Comment by nwhetsell** [comment]
Using `L:(a - (b | c))` works, thanks!
