### ISSUE TITLE
Repo reporting language that's not even in repo

### ISSUE THREAD

**Issue by xiaoxyy** [github/linguist#3618]
Hey all,

I'm working on a project that's mostly JavaScript, but language statistics are reporting that it's mainly HTML, which isn't the case. When I click on "HTML" in the language statistics bar, no results are returned. While linguist detected 19 files written in JS, it couldn't even find a single file written in HTML, yet reported that HTML takes up most of the project? What could be the problem, and how do I go about fixing it? It's been like this for a few days.

Thank you!

**Comment by wopian** [comment]
its cause of [this](https://github.com/mooody-princeton/finalproject/blob/d21f94e17aed74f99853ad5d8fe27c4c5bc9be23/views/index.ejs) huge JS template file.

The language search on GitHub unfortunately doesn't show files that are a subgroup (EJS) of another (HTML)
