### ISSUE TITLE
Python pickles are not OpenEdge ABL

### ISSUE THREAD

**Issue by pratheeksh** [github/linguist#3619]
It mistakes .p files to be something strange and since they're large, my repo is considered to be ABL. That makes no sense

**Comment by pchaigno** [comment]
`.p` is currently not recognized by Linguist as a Python extension. If you think it should, you can take a look at the [guidelines to add support for a new extension](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language). In particular, notice the requirement on in-the-wild usage.
