### ISSUE TITLE
Unity C# project showing as 66% ASP

### ISSUE THREAD

**Issue by DrJoson** [github/linguist#3622]
2 files in the project are ASP, with 22 C# files and over 100 Unity 3D files, yet the bar shows 66% of it as ASP. Any help or advice with this would be appreciated
https://github.com/DrJoson/3D-Tile-based-project

**Comment by pchaigno** [comment]
The percentages count the total file size for each language, not the number of files. The 2 ASP files look huge, which probably explains the 66%.

If you wish, you can mark those files as vendored to exclude them from statistics using [Linguist overrides](https://github.com/github/linguist#overrides).
