### ISSUE TITLE
Kotlin, Javascript, etc. not identified, added .gitattributes & re-committed w/no change?

### ISSUE THREAD

**Issue by mkitchin** [github/linguist#3623]
Hi there,

Hope the title says it.

It's a public repo, here:
https://github.com/mkitchin/geo-convo-server

Note Kotlin:
https://github.com/mkitchin/geo-convo-server/tree/master/src/main/kotlin/com/opsysinc/learning

Note Java:
https://github.com/mkitchin/geo-convo-server/tree/master/src/test/kotlin/com/opsysinc/learning

Note Javascript & CSS:
https://github.com/mkitchin/geo-convo-server/tree/master/src/main/resources/static

Best wishes,
Michael J. Kitchin

**Comment by lildude** [comment]
Looks to all be correctly identified now. It's worth pointing out that the language information is updated my an asynchronous background job so can take a while to appear/update.

**Comment by mkitchin** [comment]
Hi there,

Doesn't appear to be (at least from my repository summary).
![image](https://cloud.githubusercontent.com/assets/11393563/26028429/521800ba-37dd-11e7-8ef5-0e66817b399a.png)

The two below it are included for comparison.

**Comment by wopian** [comment]
The language bar displays the total filesize of each language. There's ~80 KB of HTML and ~50 KB of JS in `geo-convo-server`, whilst Kotlin only consists of around 40 KB

![](https://i.imgur.com/R8XTIFg.png)

**Comment by mkitchin** [comment]
Hi there,

Got it -- hadn't noticed the language bar, before. Neat.

I understand how this works, now. Thanks so much for the clarification :) .

Issue closed.

Best wishes,
Michael J. Kitchin
