### ISSUE TITLE
QMake project file incorrectly detected as Prolog

### ISSUE THREAD

**Issue by Venemo** [github/linguist#3624]
[In this repository](https://github.com/communi/communi-desktop) GitHub reports that it is written 0.1% in Prolog, because it incorrectly identifies the [root project file](https://github.com/communi/communi-desktop/blob/master/communi.pro) as Prolog instead of a QMake project file. Note that other `.pro` files are correctly detected as QMake, just this one is mistaken.

**Comment by lildude** [comment]
Looks like this is happening because the [`.pro` disambiguation](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.rb#L363-L373) expects to find  `HEADERS` and `SOURCES` in QMake files.  Your file has neither.

We'd certainly welcome a PR to improve this disambiguation.

**Comment by Venemo** [comment]
@lildude I'd recommend the QMake disambiguator to check for `QMAKE`, `QT_` and `SUBDIRS` and if either of these are found, the file should be QMake. The syntax of the file you linked is totally alien to me, but it also looks like the Prolog disambiguator catches the file before the QMake one does. Is that correct?

**Comment by pchaigno** [comment]
> The syntax of the file you linked is totally alien to me, but it also looks like the Prolog disambiguator catches the file before the QMake one does. Is that correct?

Yes, that's correct.

To improve the disambiguation with your new keywords, you'd only need to change [this line](https://github.com/github/linguist/blob/ca6121e3eabfd26c9d3098a64039c56c07d4e9d2/lib/linguist/heuristics.rb#L368) and add new sample files that highlight the issue (i.e., that were previously incorrectly classified).

**Comment by Venemo** [comment]
@pchaigno Thanks! How can I test my modification before submitting a pull request?

**Comment by pchaigno** [comment]
@Venemo You'll have to install a RUby environment and follow [these guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#testing). At the moment, it's the best we have. Otherwise, if you're confident in your changes, you can send the pull request and Travis will check it automatically.
