### ISSUE TITLE
Dockerfile showing as shell in language stats bar

### ISSUE THREAD

**Issue by esalter-va** [github/linguist#3628]
I recently created [esalter-va/shairport-sync-docker-pi](https://github.com/esalter-va/shairport-sync-docker-pi) and noticed that the language stats bar says it's 100% shell.

I have 2 files other than `README.md` and `LICENSE`, and they are as follows:

|Name|Bytes|
|---|---|
|`Dockerfile`|673|
|`start.sh`|74|

So the bar should be closer to 90% Dockerfile, 10% Shell.  It might be because the Dockerfile doesn't have an extension, but it would be nice if it was recognized in the language stats.

**Comment by lildude** [comment]
This is expected. Dockerfile, like SQL, is not counted in statistics because it's considered a data language by Linguist.

**Comment by pchaigno** [comment]
@lildude It seems weird to categorize Dockerfiles as data. In the end, they're just scripts. Should we reconsider this?

**Comment by lildude** [comment]
Sure, I thought it was odd too, but it's addition pre-dates me. 

@vmg was there any particular reason you marked Dockerfile as data when adding it in https://github.com/github/linguist/pull/1714?

(Re-opening to continue the discussion)

**Comment by ElectricWarr** [comment]
Coming across this issue almost a year on - I also would have expected to see Docker or Dockerfile in the languages bar by now.

Seems all it would take would be to replace the `type` here with `programming`:
https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L1060

@lildude / @vmg any further? It would be really interesting to see the effect this could have on the site - take this search, for example: https://github.com/search?utf8=%E2%9C%93&q=Dockerfile&type=
