### ISSUE TITLE
.gitattributes does not work while computing language stats in local pc

### ISSUE THREAD

**Issue by wkentaro** [github/linguist#3632]
It won't affect the result by linguist command, is this an expected behavior?

```bash
% git clone https://github.com/github/linguist
% cd linguist

% linguist --version
  Linguist v5.0.10
  Detect language type for a file, or, given a repository, determine language breakdown.

  Usage: linguist <path>
         linguist <path> [--breakdown] [--json]
         linguist [--breakdown] [--json]

% linguist
99.61%  Ruby
0.39%   Shell

% echo '*.rb linguist-language=Java' > .gitattributes

% linguist
99.61%  Ruby
0.39%   Shell
```

**Comment by pchaigno** [comment]
Yes, changes to `.gitattributes` should be committed for them to take effect.

**Comment by wkentaro** [comment]
Thanks. I committed.
Then, does it take a few days to take effect?
It still won't change the language stats: 
- https://github.com/start-jsk/jsk_apc/blob/master/.gitattributes#L4
- https://github.com/start-jsk/jsk_apc/search?l=common-lisp

**Comment by lildude** [comment]
@wkentaro I've looked into what GitHub is doing behind the scenes and it is successfully ignoring the files under archives as you've configured when calculating the language stats. 

Your config changes however won't change the language detection as reported in your second link.

**Comment by wkentaro** [comment]
@lildude I see. Thank you.
