### ISSUE TITLE
Syntax highlighting is weird for Yaml escape sequences

### ISSUE THREAD

**Issue by stof** [github/linguist#3635]
In YAML double-quoted strings, escaped sequences are highlighted with a red background on Github, which is used elsewhere to identify invalid markup. This is not a good experience as escape sequences are not invalid.
I checked the Atom grammar (which is used for YAML), and it looks like it should properly identify these escape sequences as `constant.character.escape.yaml`.

I tried using this YAML file in Atom and it properly detects the token type (and highlights it by putting the text in blue):

```yaml
test: "some string\_with and escape sequence"
```

**Comment by lildude** [comment]
A quick test using the [TextMate grammar](https://github.com/textmate/yaml.tmbundle) shows this is likely to be a problem with the Atom grammar itself.  

- [Atom grammar showing problem](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Ftextmate%2Fyaml.tmbundle%2Fmaster%2FSyntaxes%2FYAML.tmLanguage&grammar_text=&code_source=from-text&code_url=&code=test%3A+%22some+string%5C_with+and+escape+sequence%22)
- [TextMate grammar not showing problem](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=source.yaml&grammar_url=&grammar_text=&code_source=from-text&code_url=&code=test%3A+%22some+string%5C_with+and+escape+sequence%22)

As this appears to be a problem with the grammar itself, I'm going to close this. Please open an issue in https://github.com/atom/language-yaml/ for this issue.

**Comment by stof** [comment]
Well, I tried using Atom itself to see how it was parsing things previously (and it was detecting things as `constant.character.escape.yaml` properly). But I just discovered that Atom updates just don't seem to work on ubuntu, as it always tells me that there is no update of packages available, even though the YAML package is not at 0.30.0 which is the latest release 😞

**Comment by pchaigno** [comment]
@stof atom/language-yaml#88 should fix this. We'll update the reference to the grammar in Linguist with the next release after the fix is merged.
