### ISSUE TITLE
Perl 5 code being mistaken for Perl 6

### ISSUE THREAD

**Issue by wchristian** [github/linguist#3637]
This is recognized as Perl 6, wrongly:

```

=head1 NAME

class

=cut

package PH;

use 5.010;
```

This is recognized as Perl 5:

```

=head1 NAME



=cut

package PH;

use 5.010;
```

**Comment by wchristian** [comment]
I don't get reliable results when i push this to github with changes, but this looks like it also is recognized as Perl 6, wrongly:

```
use 5.006;
use strict;
use warnings;

=head1

module

=cut
```

And removing `module` changes it to perl 5.

**Comment by wchristian** [comment]
Forgot to mention, in both examples the files were `Word.pm`.

**Comment by zoffixznet** [comment]
Looks like just swapping [these conditionals](https://github.com/github/linguist/blob/58ab593a64088be56e3323a9fb121fe0988bdb3c/lib/linguist/heuristics.rb#L347-L353) to check for Perl 5 regex first will solve the issue.

**Comment by kentfredric** [comment]
https://github.com/github/linguist/blob/58ab593a64088be56e3323a9fb121fe0988bdb3c/lib/linguist/heuristics.rb#L348

^ That heuristic would false positive on anything using MooseX::Declare  style perl-5 syntax anyway.

So yeah, +1 on inversion.

**Comment by pchaigno** [comment]
We'd welcome a pull request with a test ([`test/test_heuristics.rb`](https://github.com/github/linguist/blob/master/test/test_heuristics.rb)) to implement that change :smiley:

**Comment by zoffixznet** [comment]
> Is it really worth it to have Perl 6 separated from Perl

Yes, considering it's an entirely different language. It's like C vs C++, except with poorer name.

**Comment by Alhadis** [comment]
@smola Perl 5 and Perl 6 are, as @zoffixznet put it, two entirely separate languages. To quote *"Programming Perl"*:

> That 6 is deceptive though; Perl 6 is really a “kid sister” language to Perl 5, and not just a major update to Perl 5 that version numbers have trained you to expect.

**Comment by tessarin** [comment]
@pchaigno Do you know if this was in fact fixed? I've got a similar problem in a repository for a Perl 5 module which has its main file being incorrectly interpreted as Perl 6, making the repository also Perl 6 (funny enough, named [**p5**-POD-Auto](https://github.com/tessarin/p5-POD-Auto)). Thanks!

**Comment by pchaigno** [comment]
@tessarin No, I don't think a pull request for the above proposed change was submitted.

**Comment by tessarin** [comment]
@pchaigno May I submit one then? You mentioned adding a test to `test/test_heuristics.rb`, however there is already a test for loading samples and disambiguate _Perl_ | _Perl 6_ (lines [224-231](https://github.com/github/linguist/blob/a47008ea007caca33f2f38b4025f3ff49e0a7daf/test/test_heuristics.rb#L224-L231)). In this case, adding a minimal example to `samples/Perl` (like the ones posted here) causes tests to fail. With the change in `heuristics.rb` they pass again. So, is adding the sample enough?

**Comment by pchaigno** [comment]
> May I submit one then?

Sure, go ahead 😄 

> You mentioned adding a test to `test/test_heuristics.rb`, however there is already a test for loading samples and disambiguate _Perl_ | _Perl 6_ (lines [224-231](https://github.com/github/linguist/blob/a47008ea007caca33f2f38b4025f3ff49e0a7daf/test/test_heuristics.rb#L224-L231)). 

Oh, right. In that case, yes, a sample is enough. Please add it in `test/fixtures/Perl/` rather than in `samples/` though. `samples/` files should originate from "real" application. `test/fixtures/` is for this kind of test-only example files.

**Comment by sidyll** [comment]
Any chance that this will get fixed soon?

**Comment by tessarin** [comment]
@sidyll well the pull request was already made and it was approved, but I'm not sure about how the review process works or the release frequency.

**Comment by lildude** [comment]
PR has been merged. I've been AFK for a week so need to do some catching up before I can make a new release. I can't say when this will be right now though.

**Comment by tessarin** [comment]
Thank you @lildude!
