### ISSUE TITLE
S-Lang support

### ISSUE THREAD

**Issue by oldmud0** [github/linguist#3653]
Interested in syntax highlighting for John E. Davis's S-Lang: http://www.jedsoft.org/slang/
It's been around for longer than I was born, so I'm a little surprised the language hasn't been added yet. GitHub does not even recognize the language. I believe many of the other projects (other than the programs JED, sc, slrn, mutt) using the language are so dated that they aren't on GitHub - after all, this is a pretty old language.

I'll probably end up adding the language in myself, but I'm putting the issue out there if anyone else wants to do it.

**Comment by Alhadis** [comment]
Hrm, the page you've linked to mentions that this is a library. Are you sure this is a language distinct from C?

**Comment by oldmud0** [comment]
@Alhadis Yes, this is a distinct interpreted language. It is written in tandem with C "for extensibility." A full guide to the language can be found here: http://www.jedsoft.org/slang/doc/html/slang.html#toc2.2

 - [hankem/S-Lang](https://github.com/hankem/S-Lang) is a mirror of the S-Lang library, which uses C *and* S-Lang itself.
 - [LeComm/vxw-server](https://github.com/LeComm/vxw-server) uses S-Lang.
 - [wookay/da](https://github.com/wookay/da) appears to be a list of sample files for various languages, including S-Lang.
 - [hankem/ISIS](https://github.com/hankem/ISIS) (Interactive Spectral Interpretation System) is a full project written with C and S-Lang.

all right, after making that list I made [a search query](https://github.com/search?p=16&q=extension%3Asl+variable+AND+if+AND+define+AND+return&type=Code&utf8=%E2%9C%93) to show that there are at least 2,000 files on GitHub that use S-Lang, although GitHub erroneously marks such files as [Slash](https://github.com/slash-lang/slash).

**Comment by lildude** [comment]
If you’ve got the bandwidth, we’d happily accept a PR implementing this.

**Comment by pchaigno** [comment]
@oldmud0 As @lildude said, if you've got time, we'd accept a pull request to add support for S-Lang to Linguist.

I'm closing this in the meantime, but anyone if welcome to submit a pull request.

**Comment by oldmud0** [comment]
No problem - thanks for your help.
