### ISSUE TITLE
Language stats don't update

### ISSUE THREAD

**Issue by alexjoverm** [github/linguist#3655]
Hi! In my [TypeScript starter repo](https://github.com/alexjoverm/typescript-library-starter) I've updated a couple of days ago my JS files under `tools` to TS. When you click on the language to see [the details, they're shown correctly](https://github.com/alexjoverm/typescript-library-starter/search?l=typescript). But the summary (color bar + languages) are shown incorrectly:

![image](https://cloud.githubusercontent.com/assets/5701162/26563127/9687f168-44cd-11e7-8b18-ac182ca1e571.png)

It should be around 80% TS and 20% JS

**Comment by Alhadis** [comment]
👋 Hey @alexjoverm,

That's interesting. I wasn't aware that Linguist [treats](https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml#L24) the `tools/` directory as a [vendored path](https://github.com/github/linguist#vendored-code). This means it's deliberately excluding the contents from affecting the codebase's language statistics.

You can tell it not to do that by adding a `.gitattributes` file to your project containing the following line:

~~~
tools/ linguist-vendored=false
~~~

~~~console
$ git clone git@github.com:alexjoverm/typescript-library-starter.git
$ cd typescript-library-starter
$ linguist --breakdown .
75.04%  JavaScript
24.96%  TypeScript

JavaScript:
rollup.config.js

TypeScript:
src/library.ts
test/library.test.ts

$ echo 'tools/* linguist-vendored=false' > .gitattributes
$ git add !$ && git commit -m "Add .gitattributes file"
[master 53072e0] Add .gitattributes file
 1 file changed, 1 insertion(+)
 create mode 100644 .gitattributes

$ linguist --breakdown .
85.74%  TypeScript
14.26%  JavaScript

JavaScript:
rollup.config.js

TypeScript:
src/library.ts
test/library.test.ts
tools/gh-pages-publish.ts
tools/init.ts
tools/semantic-release-prepare.ts
~~~

**Comment by alexjoverm** [comment]
That worked as a charm, Thanks!
