### ISSUE TITLE
Modula-2 file extension recognition incomplete

### ISSUE THREAD

**Issue by trijezdci** [github/linguist#3657]
Modula-2 has two source file types:

* definition modules with file ending .def/.DEF
* implementation modules with file ending .mod/.MOD

Your listing only has the .mod for Modula-2, the .def is missing.

https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L2655

Github doesn't therefore syntax highlight the definition modules.

Can you add the .def wherever that needs to be added, please?

thanks a lot in advance.

**Comment by lildude** [comment]
> Can you add the .def wherever that needs to be added, please?

We'd happily accept a PR with the addition from someone who knows Modula-2.  A quick cursory glance suggests adding a `.def` extension may be all we need, but I'd prefer it if someone with more experience with the language to offer up the PR.

**Comment by trijezdci** [comment]
Hi and thanks for your response.

I know Modula-2 in and out, but I don't know Ruby and I don't have the time right now to get side tracked with Ruby just to teach your software to recognise .def as a Modula-2 source file ending.

Modula-2 has two ancient dialects, called PIM (from 1979) and ISO (from 1992), and there is a recent revision of the language (from ~2010) adding a third dialect. Also, most of the available PIM and ISO compilers have added their own predefined identifiers for additional built-in types.

For the Python based Pygments syntax highlighting package I had written and contributed a multi-dialect Modula-2 lexer. Modula-2 developers can control the dialect selection by dialect tags embedded within Modula-2 comments at the beginning of a Modula-2 source file which the Pygments lexer understands.

For example ...

(*!m2pim*) indicates PIM Modula-2
(*!m2iso*) indicates ISO Modula-2
(*!m2r10*) indicates Modula-2 Revision 2010
(*!m2iso+gm2*) indicates ISO Modula-2 with additions by the GNU Modula-2 compiler
(*!m2pim+mocka*) indicates PIM Modula-2 with additions by the MOCKA Modula-2 compiler

etc etc etc

The lexer also has an Algol-60 publishing mode where source code is rendered in the style of the Algol-60 report which set a standard for rendering algorithms in scientific papers. Modula-2 uses all uppercase reserved words and predefined identifiers which was actually intended to mean boldface. Thus in Algol-60 mode the Pigments package renders all Modula-2 reserved words in lowercase boldface, all predefined identifiers in lowercase boldface italic, and comments in grey. For scientific papers this is preferable to colours and an established de-facto standard used to this day.

I agree it would be very nice to port this capability to Linguist (and thus Github) but we are far too busy working on our two Modula-2 compilers (one for bootstrapping, the other self-hosting) and nobody in our team knows Ruby.

A port of this from Pygments to Linguist will therefore have to wait until some time later.

For the time being, just adding support for recognising .def file endings will be workable.

kind regards
benjamin

**Comment by jcchu** [comment]
@trijezdci Textmate grammar files are more of lexer definitions.  It suffices to get keywords, reserved identifiers, literals, and comments recognized to get a highlighter working fine.  Is [the current Modula-2 grammar](https://github.com/harogaston/Sublime-Modula-2/blob/master/Modula-2.tmLanguage) good for definition modules in all of those dialects you mentioned?

**Comment by trijezdci** [comment]
On 10 August 2018 at 13:00, jcchu <notifications@github.com> wrote:

> @trijezdci <https://github.com/trijezdci> Textmate grammar files are more
> of lexer definitions.
>
So?

> It suffices to get keywords, reserved identifiers, literals, and comments
> recognized to get a highlighter working fine.
>
There are cases where proper recognition of those tokens depends on context.

For example, what is a reserved word in one dialect, may be a reserved
identifier or non-reserved identifier in another.

In one dialect ! starts a single line comment, in another it is an
alternative for |.

In one dialect -- is a decrement suffix and it denotes descending iteration
in a for loop. In one sub-dialect by a popular compiler -- is used to start
a single line comment but only if it has previously been enabled by a
pragma, which requires context not doable with regular expression matching.

Although the impact of getting this wrong is limited to a single line, it
is annoying.

In one dialect a single quote in between two digits within a number literal
is permitted for digit grouping. But a single quote at the start of a
symbol designates a single quoted string. Most of the regular expressions
used for quoted string matching get this wrong because it ignores context.
This then messes up the rendering of large sections of code.

A more complex issue arises from the difference in pragma syntax accross
different dialects.

In older dialects pragmas were special comments (*$...*), in newer dialects
pragmas have their own delimiters <* and *>.

A lexer for a newer dialect would colourise the old style pragmas as
comments, that would be desired behaviour.

But a lexer for an older dialect would misinterpret new style pragma
delimiters as operators < and * or * and > respectively. It would then
misinterpret anything in between these delimiters as ordinary source code.
This way it would colourise pragma names as reserved words, reserved
identifiers or non-reserved identifiers. Since compilers following the new
style pragmas often implement conditional compilation through pragmas this
can easily mess up the display of large sections of code if a lexer for an
older dialect is used to tag the tokens.

There is also an issue with the lexing of identifiers. The original
language report did not permit _ nor $ within identifiers, but many
compilers permit them in some way. Since Modula-2 uses qualified naming for
name spaces, symbols are generated from the module identifier followed by
one or two lowlines or dollars followed by the unqualified identifier. Thus
if lowlines or dollars are to be allowed within identifiers, care must be
taken so that user code cannot define any identifier that might
accidentally clash with an internal symbol name. For this reason there are
several different schemes how to restrict the use of lowlines and/or
dollars within identifiers.

One common scheme is to only permit non-leading, non-trailing and
non-consecutive lowlines, and only non-trailing and non-consecutive dollars.

Another scheme is to only permit lowlines and dollars in identifiers within
modules that are tagged as foreign function interfaces, but not to restrict
how lowlines and dollars may occur in identifiers. The tagging of a module
as a foreign function interface is again context and dialect dependent. In
some cases the module header is prefixed with a reserved word FOREIGN, in
the GNU Modula-2 compiler the module header is suffixed with 'FOR "C"' and
in others pragmas such as (*$F*), (*$FOREIGN*) or <*FFI="C"*> are used
before or after the module header.

Whilst the identifier issue is relatively minor compared to the others
mentioned above, using a lexer that gets the identifier recognition wrong
will usually have a knock on effect on the proper recognition of subsequent
tokens. Thus any implementation should be designed in such a way that it
will permit future refinement to get this right eventually.

Is the current Modula-2 grammar
> <https://github.com/harogaston/Sublime-Modula-2/blob/master/Modula-2.tmLanguage>
> good for definition modules in all of those dialects you mentioned?
>
As I had previously mentioned, that grammar is NOT CORRECT FOR ANY Modula-2
dialect.


I have studied the issues of lexing different Modula-2 dialects very
extensively.

Based on my experience, the use of different separate lexers or lexing rule
sets depending on dialect tags is an absolute necessity.

And in addition, some context is required within some dialects in some
cases.


Last but not least, lexing does not address the issue that only
implementation files are rendered but not definition files.

Github needs to recognise .def file extensions as Modula-2 source files.
Further, there probably needs to be some mechanism to disambiguate .mod
file extensions as they are also used by some other languages. In the
implementation we made for the VIM and Emacs editors, this is done by
scanning the first 100 lines of source for the presence of a dialect tag
(*!m2pim*) etc, or failing that, reserved word MODULE.

Many source files have multiple lines spanning comments with a description
of the file and copyright and license information before the actual source
code starts, for this reason it is wise not to simply look at the first
couple of lines but scan further down to make sure to reach past any such
comment.

hope this clarifies

regards
trijezdci

**Comment by trijezdci** [comment]
Last but not least, any Modula-2 source code renderer should provide an option to render the code in the style of the Algol-60 report which established a standard for source code in academic publications that is still widely in use today.

You see, reserved words and built-in identifiers in Algol and its descendants are **boldface**. In the literature of the 1960s they were even called **bold names**. The terminology reserved word was not yet established back then.

Owing to its Algol ancestry, reserved words and built-in identifiers in Modula-2 are **bold names**. They are supposed to be rendered in **lowercase boldface**. Their being in all-uppercase in source files is nothing but an encoding for boldface, or in modern terminology it is a markup convention.

There are two styles. One style is the original style of the Algol-60 report. In this style reserved words are rendered boldface underlined and built-in identifiers are rendered boldface without underlining. The other style is a modernised version where reserved words are rendered boldface and built-in identifiers are rendered boldface italic.  

The multi-dialect Modula-2 lexer for the Pygments source code rendering framework which was previously used by Github and still used by Bitbucket has an option to render Modula-2 source code in the original Algol-60 style (boldface-underlined/boldface) and the modernised style (boldface/boldface-italic). Likewise, the Emacs Modula-2 mode also uses the latter convention.

Ideally, Github should render Modula-2 source code in this way.

Thus, the raw ASCII source text below ...

DEFINITION MODULE String;

CONST StringCapacity = 80;

TYPE String = ARRAY StringCapacity OF CHAR;

VAR str : String;

PROCEDURE length ( str : String ) : LONGCARD;
...
END String.

should be rendered

**definition** **module** String;

**const** StringCapacity = 80;

**type** String = **array** StringCapacity **of** **_char_**;

**var** str : String;

**procedure** length ( str : String ) : **_longcard_**;
...
**end** String.

regards
trijezdci

**Comment by Alhadis** [comment]
@trijezdci Your arguments are correct, but they're mistargeted for a few reasons:

* GitHub's has several mechanisms for identifying languages, none of which are simple lexical parsing.
* TextMate grammars are only used for highlighting syntax: they have zero influence on GitHub's language analysis. In fact, they only come into play *after* languages have been classified.
* TextMate grammars aren't lexers. They may resemble `flex` or `bison` on the surface, but their underlying mechanics are more primitive than that.

> but I don't know Ruby and I don't have the time right now to get side tracked with Ruby just to teach your software to recognise .def as a Modula-2 source file ending.

You won't need to edit any Ruby. =) Most contributions to Linguist involve a few changes to `languages.yml`, nothing more. The steps involved are [documented in `CONTRIBUTING.md`](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language).
