### ISSUE TITLE
my Crystal repository is seen as 97.7% HTML

### ISSUE THREAD

**Issue by azah** [github/linguist#3658]
https://github.com/azah/cowapi/tree/master

**Comment by azah** [comment]
this test.html file I had checked in was the issue.
https://github.com/azah/cowapi/blob/c577e327707ba81cd6d4bbe102f3a14415cc0aeb/spec/test.html

**Comment by lildude** [comment]
Good to see you found the cause. Closing.

**Comment by grahamc** [comment]
but the test.html file is valid HTML

**Comment by lildude** [comment]
@grahamc I'm not sure I understand why you're pointing that out.

**Comment by Alhadis** [comment]
I'm not particularly sure either... 😕

**Comment by grahamc** [comment]
D'oh! Sorry for the noise. I was confused and thought the test was being categorized as Crystal incorrectly. Sorry again!
