### ISSUE TITLE
Cannot run linguist binary from repository

### ISSUE THREAD

**Issue by JonasT** [github/linguist#3663]
I cannot run the `linguist` tool from the repository as instructed:

```
[jonas@falcon linguist]$ bundle install
Resolving dependencies...
Using rake 12.0.0
Using public_suffix 2.0.5
Using byebug 9.0.6
Using charlock_holmes 0.7.3
Using coderay 1.1.1
Using color_difference 0.0.1
Using escape_utils 1.1.1
Using multipart-post 2.0.0
Using mime-types-data 3.2016.0521
Using rugged 0.25.1.1
Using thor 0.19.4
Using metaclass 0.0.4
Using method_source 0.8.2
Using minitest 5.10.2
Using plist 3.3.0
Using slop 3.6.0
Using yajl-ruby 1.3.0
Using bundler 1.12.5
Using addressable 2.5.1
Using color-proximity 0.2.1
Using faraday 0.12.1
Using mime-types 3.1
Using licensee 8.8.5
Using mocha 1.2.1
Using pry 0.10.4
Using sawyer 0.8.1
Using github-linguist 5.0.11 from source at `.`
Using octokit 4.7.0
Using licensed 0.6.0
Bundle complete! 11 Gemfile dependencies, 29 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
[jonas@falcon linguist]$ bundle exec linguist --breakdown
bundler: failed to load command: linguist (/home/jonas/.gem/ruby/2.3.0/bin/linguist)
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/jonas/Develop/linguist/lib/linguist/samples.json
  /home/jonas/Develop/linguist/lib/linguist/samples.rb:24:in `read'
  /home/jonas/Develop/linguist/lib/linguist/samples.rb:24:in `cache'
  /home/jonas/Develop/linguist/lib/linguist/language.rb:505:in `<module:Linguist>'
  /home/jonas/Develop/linguist/lib/linguist/language.rb:18:in `<top (required)>'
  /home/jonas/Develop/linguist/lib/linguist.rb:5:in `require'
  /home/jonas/Develop/linguist/lib/linguist.rb:5:in `<top (required)>'
  /home/jonas/Develop/linguist/bin/linguist:5:in `require'
  /home/jonas/Develop/linguist/bin/linguist:5:in `<top (required)>'
  /home/jonas/.gem/ruby/2.3.0/bin/linguist:23:in `load'
  /home/jonas/.gem/ruby/2.3.0/bin/linguist:23:in `<top (required)>'
[jonas@falcon linguist]$
```

**Comment by lildude** [comment]
Yes, this is kind of expected as you're attempting to install from source and not from the gem. When we create the gem, we generate the `samples.json` file that is causing you problems (see step 4 at https://github.com/github/linguist/blob/master/CONTRIBUTING.md#releasing).

Reinstalling using the gem as documented or manually generating the `samples.json`will get you going.

**Comment by pchaigno** [comment]
You can use `bundle exec rake samples` to generate the `samples.json` file.

**Comment by JonasT** [comment]
How about adding a small section to the README.md at the very bottom on how to run directly from source for developers? I did actually peek into the CONTRIBUTING.md guide to see if there was a hint for developers of how to run from source and expected it in the section that explains how to add a new language (since how are you expected to test it otherwise??) but even there nothing is mentioned. That it is buried down in the release section is a bit counter-intuitive.

**Comment by lildude** [comment]
Good idea. Feel free to start a PR and we can discuss etc there.

**Comment by JonasT** [comment]
I'm probably not the best person, since I'm super unfamiliar with ruby and ruby gems and I don't know how the process actually works. E.g., the contributions guide has this section:

```
Test the gem:
Bump the Gemfile and Gemfile.lock versions for an app which relies on this gem
Install the new gem locally
```
How do I even install a new gem locally? Would I need to bump the versions just to be able to install and test the dev version locally? The steps seem to be currently written for someone who has a much better idea of ruby gems than I do, so I'm not in a position to easily tell what basic steps are needed just to run it (instead of making a full-blown new release as described there).

**Comment by pchaigno** [comment]
I made a [Dockerfile for Linguist](https://github.com/pchaigno/linguist/blob/dockerfile/Dockerfile) a long time ago. I haven't had time to look into it since then, but it might help you figure the general steps.
Maybe we should even provide a Dockerfile for developers who don't want to install a full Ruby environment on their machine.
