### ISSUE TITLE
C++ > Arduino for Arduino Library

### ISSUE THREAD

**Issue by MichaelCalleia** [github/linguist#3670]
This is an Arduino Library but is displaying as C++ (since /examples is ignored by default this makes sense).

To override, placed .gitattributes in the repository: https://github.com/MichaelCalleia/MorseCode-Library.  .gitattributes contains:

```
$ cat .gitattributes
examples/**.ino linguist-documentation=false
*.rb linguist-language=Arduino
```
It is still showing up as C++

Thanks in advance for your help.

**Comment by Alhadis** [comment]
👋 Hey @MichaelCalleia,

I'm afraid you've used the `.gitattributes` file incorrectly.

1. The first line needs to be removed
2. `examples/**.ino` can be simplified to just `examples/` instead.
3. The third line is achieving nothing because it targets Ruby files (`*.rb`).

**Comment by MichaelCalleia** [comment]
@Alhadis  Thank you for your help.

.gitattributes is now: 

```
examples/ linguist-documentation=false
*.ino linguist-language=Arduino
*.cpp linguist-language=Arduino
*.hpp linguist-language=Arduino
*.h linguist-language=Arduino
```
Which is likely overkill, but seems work.
