### ISSUE TITLE
Rename Perl6 to Perl 6

### ISSUE THREAD

**Issue by rightfold** [github/linguist#3671]
The official name of the language is "Perl 6".

**Comment by pchaigno** [comment]
@hoelzro added support for `Perl6` [4 years ago](d66147a277855f6a22f0cccbe3acf91df9f7f296), he may have some comments/other opinion here. Otherwise, I'm :+1: !

**Comment by hoelzro** [comment]
That's cool with me!

**Comment by Alhadis** [comment]
The extra space also increases the language-name to 6 characters.

This is clearly an omen of something deeply important and revolutionary coming this way.

`#Perl666`

**Comment by pchaigno** [comment]
@rightfold Do you want to open the pull request for this? It should simply be a matter of changing the name in `lib/linguist/languages.yml` and then running the tests, which will tell you what else needs a change.

**Comment by Alhadis** [comment]
... as well as fixing the language's name wherever it's mentioned in Ruby source, too. Specifically in [`heuristics.rb`](https://github.com/github/linguist/blob/44f03e6/lib/linguist/heuristics.rb#L343). ;-)
