### ISSUE TITLE
Breakdown refuses to change

### ISSUE THREAD

**Issue by neilbalch** [github/linguist#3673]
I have a repo (neilbalch/RPi-Computer-Power) with a lot of `pug` files, but it refuses to show that in the breakdown. Is it because `pug` wasn't assigned a color, or what?

**Comment by lildude** [comment]
>  Is it because pug wasn't assigned a color, or what?

No, it is because Pug is considered part of the [HTML group](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L3395) by Linguist so it's included in the HTML total.

**Comment by neilbalch** [comment]
Okay. Got it. That makes sense now.
