### ISSUE TITLE
syntax parsing is not working properly with lots of single quotes

### ISSUE THREAD

**Issue by xinglin** [github/linguist#3674]
See below for an example. A large code section is marked as red.  

https://github.com/xinglin/cloud-management-kits/blob/master/src/main/scala/Prefix.scala

**Comment by pchaigno** [comment]
Linguist only selects the grammar to use for highlighting. For Scala, GitHub uses [mads-hartmann/scala.tmbundle](https://github.com/mads-hartmann/scala.tmbundle). You should open an issue there if there isn't already one (it looks related to mads-hartmann/scala.tmbundle#59).
