### ISSUE TITLE
Language kOS/kerboscript is missing

### ISSUE THREAD

**Issue by Kamik423** [github/linguist#3675]
documentation is [here](https://ksp-kos.github.io/KOS/index.html), example [here](https://github.com/kamik423/athena)

**Comment by pchaigno** [comment]
Please see the [guidelines to add support for a new language to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). If kOS meets the requirement on in-the-wild usage, don't hesitate to open a pull request.

**Comment by Kamik423** [comment]
What if I have neither the skills nor the knowledge to do that?

**Comment by pchaigno** [comment]
You'll have to find someone who has the information required to submit a pull request (someone who knows kOS). Then, the pull request itself only requires running a few scripts and changing the `languages.yml` file. We can help in case of issues.
