### ISSUE TITLE
React Native project tagged as Java instead of JavaScript

### ISSUE THREAD

**Issue by Boris-c** [github/linguist#3678]
Hi, our React Native project https://github.com/salathegroup/react-native-scandit is tagged as Java. It's basically a JavaScript project, even if it includes native Java and Objective-C wrappers.

Any way I can induce JavaScript detection instead of Java? Can you fix it on your side?

Thanks

Boris

**Comment by pchaigno** [comment]
You can mark those wrapper files as vendored using [Linguist overrides](https://github.com/github/linguist#overrides).
