### ISSUE TITLE
Thrift map syntax highlighting doesn't work

### ISSUE THREAD

**Issue by blkperl** [github/linguist#3680]
See example:

```thrift
const map<string,list<string>> SERVER_TYPES_SUPPORTED_BY_OS = {
```

**Comment by pchaigno** [comment]
Linguist only selects the grammar to use for highlighting. For Thrift, GitHub uses [textmate/thrift.tmbundle](https://github.com/textmate/thrift.tmbundle). You should open an issue there if there isn't already one.
