### ISSUE TITLE
Why changing GitHub repository language not working?

### ISSUE THREAD

**Issue by reza-khalafi** [github/linguist#3684]
i have been made a repository in GitHub with as Xcode project with Objective-C language.
Beside .gitignore file in root of my project made .gitattributes file and set this code in it:

```
* linguist-vendored
*.objective-c linguist-vendored=false
```
But does not show any language in Github homepage.

**Comment by lildude** [comment]
Is this repository public?  If so, can you provide a link so we can see what you're seeing.

**Comment by reza-khalafi** [comment]
OHHHhhhhh it's works. with several days delay. @lildude   tnx.

**Comment by reza-khalafi** [comment]
Oh now i was wrong  [My repo](https://github.com/reza-khalafi/mytest1)  
It's not working. @lildude

**Comment by pchaigno** [comment]
[I can't find any `.objective-c` files in your repository](https://github.com/reza-khalafi/mytest1/search?utf8=%E2%9C%93&q=extension%3Aobjective-c&type=).

**Comment by reza-khalafi** [comment]
.m and .h files  
These are not Objective C ? 
I had this problem in swift but solved with 
```
* linguist-vendored
*.swift linguist-vendored=false
```

code ...  @pchaigno @lildude @defunkt

**Comment by pchaigno** [comment]
The `*.stuff` needs to match files. Try:
```
`* linguist-vendored
*.c linguist-vendored=false
*.h linguist-vendored=false
```

**Comment by reza-khalafi** [comment]
**SOLVED**: 
I tried this and it's woks.

```
* linguist-vendored
*.c linguist-vendored=false
*.h linguist-vendored=false
*.c linguist-language=Objective-C
*.h linguist-language=Objective-C
*.m linguist-language=Objective-C
```

**Comment by pchaigno** [comment]
Great!
