### ISSUE TITLE
Euphoria language detected incorrectly as Eiffel lang

### ISSUE THREAD

**Issue by megatux** [github/linguist#3685]
[Example repo](https://github.com/redy-project/RedyCode)
[Euphoria homepage](http://openeuphoria.org/)

**Comment by pchaigno** [comment]
Linguist does not currently support Euphoria. See the [guidelines to add support for Euphoria to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). If Euphoria meets the requirement on in-the-wild usage, don't hesitate to open a pull request.
