### ISSUE TITLE
Change my repository language

### ISSUE THREAD

**Issue by Minege** [github/linguist#3688]
Hello,

I've made an implementation and a Python binding of a protocol.
The code used for the base implementation is C, but my binding is in python, and i want people to find the "python" tag in language, because when they search they see C : https://github.com/Minege/eSSP

Thanks

**Comment by lildude** [comment]
As you are including the C code within your repo, the best thing to do would be to implement a [manual over-ride](https://github.com/github/linguist/blob/master/README.md#overrides).  Marking the original C code (in `_eSSP`) as vendored is probably the best thing to do.

**Comment by Minege** [comment]
Ok, thanks.
