### ISSUE TITLE
16-bit assembly misclassified as ActionScript

### ISSUE THREAD

**Issue by RafaelPAndrade** [github/linguist#3692]
Relevant code:
https://github.com/RafaelPAndrade/LEIC-A-IST/blob/943992d0ae5948fa9c16edb619ba624c3ecf7b1c/IAC/LAB/3/assembly1/lab.as

What should I do? Use .gitattributes?

I know that the normal assembly code file extension is .asm, but the assembler I use only accepts .as

**Comment by Alhadis** [comment]
You can use an [override](https://github.com/github/linguist/#overrides) to tell Linguist how the files are to be classified.

So, in the root of your project, add a `.gitattributes` file with the following content:

~~~
*.as linguist-language=Assembly
~~~

**Comment by RafaelPAndrade** [comment]
Thanks for the quick reply!

However, I'm am also concerned with the heuristics used.
If you open the file, it is clear that it is *not* ActionScript, but assembly...
Just my two cents

**Comment by Alhadis** [comment]
That's not how Linguist works. It uses a list of file extensions (or filenames) to identify a language, relying on Bayesian classification to distinguish between languages which share extensions. Heuristics are only used if the Bayesian classifier doesn't do a good enough job telling two languages apart.

**Comment by RafaelPAndrade** [comment]
Sorry to have misunderstood Linguist.
You are absolutely right. I'm going to close this issue. Thanks for the help!
