### ISSUE TITLE
web.config

### ISSUE THREAD

**Issue by theel0ja** [github/linguist#3694]
**web.config**, the config for at least Azure (I think that IIS) is XML, but the syntax highlighting is currently "plain text", not "XML".

**Comment by pchaigno** [comment]
We'd welcome a pull request to add it as a filename to [the XML entry](https://github.com/github/linguist/blob/d5c8db3fb91963c4b2762ca2ea2ff7cfac109f68/lib/linguist/languages.yml#L4875). You'll need to follow the three first steps from the [guidelines to add support for a new extension](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language).
