### ISSUE TITLE
ES6 not being detected as js

### ISSUE THREAD

**Issue by OmgImAlexis** [github/linguist#3695]
It seems ES6 features such as the fat arrow(`=>`) are causing the grammar to not detect it as javascript.

The top code block doesn't have any language set where as the bottom one is set to js.

```
agenda.define('success-test', (job, done) => done());
agenda.define('fail-test', (job, done) => done(new Error()));

agenda.on('start', job => console.log('start', job.attrs.name));
agenda.on('complete', job => console.log('complete', job.attrs.name));
agenda.on('success', job => console.log('success', job.attrs.name));
agenda.on('fail', (err, job) => console.log('fail', job.attrs.name));

agenda.on('ready', () => {
  agenda.now('success-test');
  agenda.now('fail-test');
});
```

```js
agenda.define('success-test', (job, done) => done());
agenda.define('fail-test', (job, done) => done(new Error()));

agenda.on('start', job => console.log('start', job.attrs.name));
agenda.on('complete', job => console.log('complete', job.attrs.name));
agenda.on('success', job => console.log('success', job.attrs.name));
agenda.on('fail', (err, job) => console.log('fail', job.attrs.name));

agenda.on('ready', () => {
  agenda.now('success-test');
  agenda.now('fail-test');
});
```

**Comment by OmgImAlexis** [comment]
I'm not sure where this issue should have been opened as Github staff pointed me to here yet the readme states I should be opening this with https://github.com/atom/language-javascript.

The problem with that is in atom itself using that library there's no issues with it detecting it as javascript.

**Comment by Alhadis** [comment]
Erm. The first language block hasn't been given a language tag... and the second one has.

~~~markdown
```
Not highlighted
```

```js
Highlighted
```
~~~

Where else are you seeing this?

**Comment by OmgImAlexis** [comment]
I was under the assumption that since linguist can detect the language that the language wasn't needed for most code blocks?

**Comment by Alhadis** [comment]
No. Linguist's responsibility is to identify the languages used by a *repository*. It doesn't extend beyond that. Not tagging a code block in Markdown means *"use monospace formatting, but don't use any highlighting"*.
