### ISSUE TITLE
GitHub detects github.com/StrawberryPerl/Perl-Dist-Strawberry as "Pascal"

### ISSUE THREAD

**Issue by mcandre** [github/linguist#3699]
`.pl`, `.PL`, and `.PM` files are more likely to be Perl than Pascal, and linguist should reflect this in its language detection priorities. For example, https://github.com/StrawberryPerl/Perl-Dist-Strawberry features Perl code, not Pascal code.

`.pl`/`.PL` file extensions are occasionally used by Pascal code, which is frustrating to text editors and other language detectors. As a workaround, Pascal users should probably use the `.pas` extension to help disambiguate.

**Comment by larsbrinkhoff** [comment]
It seems to be the `.pp` files which confuse Linguist:  
https://github.com/StrawberryPerl/Perl-Dist-Strawberry/search?l=pascal

The file extensions you listed are not linked to Pascal.

**Comment by smola** [comment]
`.pp` is very likely to be Puppet.

There are a few other repositories with Perl files (`.pp` extension) detected as Pascal: https://github.com/search?utf8=%E2%9C%93&q=+extension%3App+pdl+language%3APascal&type=Code

@mcandre You can include a shebang, modeline or .gitattributes to fix it for your repository.

**Comment by smola** [comment]
Probably still relevant.
