### ISSUE TITLE
Laravel package detected as HTML instead of PHP

### ISSUE THREAD

**Issue by AnandPilania** [github/linguist#3700]
Hello Sir, I'm a newbie to GITHUB, so please don't mind if I'm doing something wrong. Today I created an repository "https://github.com/AnandPilania/laravel-docs" and its detected as HTML instead of PHP.

**Comment by lildude** [comment]
This is happening because the files under `resources/views/` are mostly HTML with a few `yield()` calls and a `.php` extension. If you want them to be identified as PHP, you'll need to use a [manual override](https://github.com/github/linguist/blob/master/README.md#overrides).

**Comment by AnandPilania** [comment]
Thanks a lot
