### ISSUE TITLE
Code being classified as "Powerbuilder", but no "Powerbuilder" in repo

### ISSUE THREAD

**Issue by nickdiorio** [github/linguist#3701]
My C++ repository is being classified as mostly Powerbuilder
![powerbuilder](https://user-images.githubusercontent.com/5658281/27713287-435044a4-5ce8-11e7-931b-5c17c535c334.PNG)

There is no Powerbuilder code in my repository (don't even know what this is).  When I click on the Powerbuilder part of the language bar, it cannot find any matching code:
![nomatchingcode](https://user-images.githubusercontent.com/5658281/27713288-4351b14a-5ce8-11e7-9f88-d57e437510d1.PNG)
This seems like a bug, so I wanted to bring to your attention.

**Comment by lildude** [comment]
I can't view our access your source code from the GitHub backend view of your repo, but I can see the language breakdown. It's all the `.srw` files that are causing this, and as you can see at https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L3336 this extension is only associated with Powerbuilder.

You'll need a manual override to change this clarification. I'll need to look into why clicking the language doesn't show these files when I believe it should.

**Comment by nickdiorio** [comment]
Ok, thanks for the info.  I'll work on the manual overrides to try and ignore the .srw files.
