### ISSUE TITLE
My github repository DeepLearning shows wrong language

### ISSUE THREAD

**Issue by sumchat** [github/linguist#3705]
My github repository DeepLearning shows wrong language. It shows 'HTML' instead of 'Python'

**Comment by lildude** [comment]
This is happening because your repo contains five HTML files totalling over 4MB with `GAN_GenerateFaces/dlnd_face_generation.html` being over 2MB alone.

**Comment by PuZZleDucK** [comment]
If you don't mind the (minimal) extra work you can manually override language definitions in a `.gitattributes` file or move the html:
https://github.com/github/linguist#overrides

**Comment by sumchat** [comment]
Thanks! It worked.
