### ISSUE TITLE
Erroneous language?

### ISSUE THREAD

**Issue by hang-up** [github/linguist#3711]
Hi! I created Bük, a markdown based documentation generator.
It mainly uses JS, Vue and markdown but for some reason it shows 81.7% CSS?

Here's the link to the repo: https://github.com/hang-up/buuk

**Comment by wopian** [comment]
The `SCSS` directory is what's counting towards the CSS language % - which has a 139kb file in it. Marking it as a [vendored file](https://github.com/github/linguist#vendored-code) will fix the language bar

**Comment by hang-up** [comment]
Thanks! Just added `src/sass/themes linguist-vendored` to `.gitattributes`.  
Do you know how long i should wait before it takes effect?

**Comment by pchaigno** [comment]
> Thanks! Just added `src/sass/themes linguist-vendored` to `.gitattributes`.

I think it should be `src/sass/themes/* linguist-vendored`.

**Comment by hang-up** [comment]
Awesome it worked!
