### ISSUE TITLE
Ruby language source repository

### ISSUE THREAD

**Issue by adaedra** [github/linguist#3712]
Hello,

Currently ruby language definitions (and a few others) are fetched from `aroben/ruby.tmbundle#pl`. However, this repository is not updated anymore. It contains a few enhancements, but also lacks a lot of some that have been added upstream.

I discussed the issue with the owner of the current repository here: aroben/ruby.tmbundle#2.

IMO, the ideal situation on this one would be to use `textmate/ruby.tmbundle` directly as source, but that may require the improvements or aroben's repos to be pushed upstream.

Another solution hinted in the issue above would be to keep a separate live fork with most recent improvements, but it requires someone to maintain it.

So what is your opinion on this issue? What are the next steps to resolve this, and have GitHub be more up-to-date on Ruby syntax highlighting?

**Comment by lildude** [comment]
I watched the conversation unravel in https://github.com/aroben/ruby.tmbundle/pull/2 and I think the best thing for the long-term is to get those three changes you mentioned in that PR merged upstream so we can switch to using the upstream syntax.

Another solution would be to switch to the Atom grammar if it already has those changes.

**Comment by adaedra** [comment]
Since #3782 is merged, this can be closed.
