### ISSUE TITLE
Igor pro

### ISSUE THREAD

**Issue by shanemcmahon** [github/linguist#3713]
I have an atom package providing support for the Igor pro programming language (https://github.com/shanemcmahon/language-igor). I was recently asked by a github user to add it to linguist. I noticed that Igor Pro is already in lib/linguist/languages.yml and has associated samples, but doesn't appear in grammars.yml. How would I go about adding a grammar for Igor? Do I just follow the instructions for "adding a language."

**Comment by pchaigno** [comment]
You need to follow the step 2 of [Adding a language](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language).

**Comment by ukos-git** [comment]
@shanemcmahon I don't know how to do it. Can you look at it again?

I already built the [rouge lexer](https://github.com/jneen/rouge) for IgorPro syntax highlighting and it was merged to rouge master. We're getting closer to Igor Support.
