### ISSUE TITLE
How to check if syntax highlighting is working?

### ISSUE THREAD

**Issue by ppKrauss** [github/linguist#3718]
Syntax highlighting at code into `file.md` and at a file with specific extension... If not working on my repo, how to check if exist or need  be working (and my file has a wrong extension or wrong syntax)

?

Example: no syntax highlighting with `.ebnf`, [at this file](https://github.com/okfn-brasil/trazdia/blob/master/docs/fragId-syntax.ebnf).

**Comment by PuZZleDucK** [comment]
This link has some information on manually defining a language (allowing you to force detection):
https://github.com/github/linguist#overrides

It also mentions vim/emacs extensions which enable local checking:
https://github.com/github/linguist#using-emacs-or-vim-modelines

I don't run vim or emacs so I haven't tried, but it might be worth setting up just for this.

**Comment by pchaigno** [comment]
The link in the original issue is not working anymore, but for future reference: if a language is in the list [here](https://github.com/github/linguist/tree/master/vendor), then it receives syntax highlighting.
