### ISSUE TITLE
New rule for generated Go files

### ISSUE THREAD

**Issue by AlekSi** [github/linguist#3719]
See https://github.com/golang/go/issues/13560#issuecomment-288457920.

Related to #2724.

**Comment by lildude** [comment]
I don't think we need a new rule but rather a tweaking of the current rule as the current implementation at https://github.com/github/linguist/blob/37979b26b04e10868017469e5cc56263b0a39c84/lib/linguist/generated.rb#L262-L267 should already catch most generated files using the new format, assuming they include `by` in their generated string.

We'd certainly welcome a PR for the tweaking to catch others and bring things inline with the new spec, but without castigating those not using the new format.

**Comment by AlekSi** [comment]
I meant that Go now has an "official" rule, not Linguist. 😄
The big difference is that now that line can appear anywhere in the file, not just in the first line.

**Comment by lildude** [comment]
Ah yes. I missed that. 😊  Thanks for the clarification.

**Comment by pchaigno** [comment]
As @lildude said, we'd welcome a pull request to improve the generated rule for Go where necessary.
