### ISSUE TITLE
Some combination of braces, quotes and a comment containing the word "class" seems to confuse highlighting of C#

### ISSUE THREAD

**Issue by poizan42** [github/linguist#3721]
I noticed this here: https://github.com/StephenCleary/AsyncEx/blob/master/src/Nito.AsyncEx.Context/AsyncContext.cs

Note that the state of whether it's inside or outside a string is flipped after `DebuggerDisplay("Id = {Id}`.

Here is an almost minimal example that demonstrates the problem:

```CSharp
    // class x
    "{}"
    public; // "int"
```

The word class inside the comment followed by some other word seems to be neccessary. Either of the braces needs to be there but both are not neccessary. The last line is just to demonstrate that the inside/outside string state has been flipped.

**Comment by pchaigno** [comment]
Linguist only selects the grammar to use for highlighting. For C#, GitHub uses [atom/language-csharp](https://github.com/atom/language-csharp). You should open an issue there if there isn't already one.
