### ISSUE TITLE
My repository is identified as HTML but is C#

### ISSUE THREAD

**Issue by osjoberg** [github/linguist#3722]
Hello,

My repository for a HTML tokenizer, https://github.com/osjoberg/HtmlPerformanceKit is written i C#. The majority of the bytes of the files are *.html, due to some tests are parsing large html files. The repository language is identified as HTML with 90% of the content identified as HTML.

I have created a .gitattributes file in the root of my repository with the following content to ignore all *.html files:
*.html linguist-vendored=false

This did not help, still 90% of the code is identified as HTML, but when clicking on HTML to see what HTML files that are in the solution, no files are found (as I expect).
https://github.com/osjoberg/HtmlPerformanceKit/search?l=html

Did I misunderstand how this works, or is this a bug?

**Comment by pchaigno** [comment]
You want the opposite:
```
*.html linguist-vendored
```

**Comment by osjoberg** [comment]
Ah, my mistake, thanks!
