### ISSUE TITLE
Improved Makefile highlighting

### ISSUE THREAD

**Issue by fadeevab** [github/linguist#3724]
Initial pull request is here: https://github.com/textmate/make.tmbundle/pull/15

I need to prove to TextMate team that the pull request is ok. Unfortunately, https://github-lightshow.herokuapp.com/ stuck on GET request on my custom XML grammar (TextMate) and I can't check my updated XML grammar. _Screenshots below are from VSCode where I prepared a pull request and the grammar there has JSON format. XML is not tested._

**If I can't submit pull request to TextMate branch, I can't submit the JSON to VSCode.** This is dependency of hell. **Finally, I attempt to ask you: perhaps, you can find a time and motivation to test my grammar.**

Short description:
1). Colorize when the expression at the beginning of line.
2). Handle '\\' at the end of prerequisites (the next line should be colorized as a continuation of previous).
3). Colorize (origin|flavor).
4). Fix colorizing of built-in which stands after a common variable.

![makefile_before](https://cloud.githubusercontent.com/assets/5967447/26456340/7136beea-4175-11e7-985b-d3d6d7af3273.png)
![makefile_after](https://cloud.githubusercontent.com/assets/5967447/26456339/71335d90-4175-11e7-8d47-4c677847743f.png)

**Comment by lildude** [comment]
I'm not sure which Makefile you're testing your grammar against, but Lightshow works if I use your grammar in your PR and one of the Makefiles included in Linguist. See [here](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Ffadeevab%2Fmake.tmbundle%2F4f547858eac06033e562c1b08e3784466bd378fc%2FSyntaxes%2FMakefile.plist&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fgithub%2Flinguist%2Fmaster%2Fsamples%2FMakefile%2Ffile-icons.make&code=)

**Comment by fadeevab** [comment]
@lildude , I used the "Type of paste the grammar" to make experiment further. With URL it works, yes.

**Comment by fadeevab** [comment]
Actually, if you wish, you can take this patch to improve your grammars. I saw the link (and I clicked that link) "If you have an improved grammar we should be using on GitHub, please file an issue."

**Comment by lildude** [comment]
We'll get it automatically as soon as your PR is merged as we use that grammar 😄

**Comment by fadeevab** [comment]
Daaamn :)) :smile:

**Comment by lildude** [comment]
As the changes mentioned here will automatically be drawn in once the upstream grammar includes them, I don't think we need this issue anymore.  Closing.
