### ISSUE TITLE
Repository is being misclassified as CSS instead of TypeScript

### ISSUE THREAD

**Issue by jasalazar** [github/linguist#3726]
![captura de pantalla de 2017-07-20 17 50 55](https://user-images.githubusercontent.com/8170705/28440434-41473522-6d74-11e7-85f2-aa1c69d30f17.png)

My repository has only 4 CSS files, and 23 TypeScript files, however it is classified as a CSS repo.

What could be the reason?

**Comment by pchaigno** [comment]
This is happening because of these files:
```
src/assets/font-awesome/less/animated.less
src/assets/font-awesome/less/bordered-pulled.less
src/assets/font-awesome/less/core.less
src/assets/font-awesome/less/fixed-width.less
src/assets/font-awesome/less/icons.less
src/assets/font-awesome/less/larger.less
src/assets/font-awesome/less/list.less
src/assets/font-awesome/less/mixins.less
src/assets/font-awesome/less/path.less
src/assets/font-awesome/less/rotated-flipped.less
src/assets/font-awesome/less/screen-reader.less
src/assets/font-awesome/less/stacked.less
src/assets/font-awesome/less/variables.less
src/assets/font-awesome/scss/_animated.scss
src/assets/font-awesome/scss/_bordered-pulled.scss
src/assets/font-awesome/scss/_core.scss
src/assets/font-awesome/scss/_fixed-width.scss
src/assets/font-awesome/scss/_icons.scss
src/assets/font-awesome/scss/_larger.scss
src/assets/font-awesome/scss/_list.scss
src/assets/font-awesome/scss/_mixins.scss
src/assets/font-awesome/scss/_path.scss
src/assets/font-awesome/scss/_rotated-flipped.scss
src/assets/font-awesome/scss/_screen-reader.scss
src/assets/font-awesome/scss/_stacked.scss
src/assets/font-awesome/scss/_variables.scss
src/styles.css
```

Maybe we should consider the whole `font-awesome` directory vendored...?

**Comment by jasalazar** [comment]
Probably, @pchaigno . Should I do anything with the directory?

**Comment by pchaigno** [comment]
I'll make a pull request to mark the `font-awesome` directory vendored. What types of files can be found in this directory? `.scss`, `.less`, anything else?

In the meantime, you can mark those files as vendored using [Linguist overrides](https://github.com/github/linguist#overrides).

**Comment by lildude** [comment]
`font-awesome` is now classified as vendorered:

https://github.com/github/linguist/blob/8d27845f8caeb5bb5633d1e4b09b2d3c796e1d9a/lib/linguist/vendor.yml#L64-L65

Closing.

**Comment by pchaigno** [comment]
Actually, I forgot to send the pull request. We need to vendor the whole `font-awesome` directory. #3932 should fix it.
