### ISSUE TITLE
TypeScript file is being JavaScript.

### ISSUE THREAD

**Issue by gluons** [github/linguist#3733]
Some `.ts` file is treated as JavaScript file.

<img width="779" alt="default" src="https://user-images.githubusercontent.com/4688092/28508902-551b352a-7068-11e7-8441-5e8a17f2de36.PNG">

**Comment by pchaigno** [comment]
Oo, you can interpret TypeScript with the Node interpreter??

**Comment by gluons** [comment]
@pchaigno Did you mean that this file can run directly by Node? If you mean that, I think it can't.

This file contains some variable type declaration that isn't valid JavaScript.

**Comment by pchaigno** [comment]
Hm. So this file is detected as JavaScript because of the [shebang on the first line](https://github.com/gluons/changelog/blob/6f8c6fc314dae149882e8ef5624aa090abcd3010/src/changelog.ts#L1).

**Comment by gluons** [comment]
Haha. **shebang** make this file to be detected as JavaScript. 🤣

**Comment by Alhadis** [comment]
> Oo, you can interpret TypeScript with the Node interpreter??

@pchaigno [Relevant issue](https://github.com/file-icons/atom/issues/606#issuecomment-304558298) at `file-icons` which has an explanation:

>  No, it cannot [execute], but the shebang string gets propagated from the TS source to the JS compiled with `tsc`. If I omit it in the source, it won't appear in the output JS.

This isn't something Linguist currently accommodates, AFAIK. 😕

**Comment by pchaigno** [comment]
Thanks for the explanation @Alhadis!

@gluons You can override the language detected using [Linguist overrides](https://github.com/github/linguist#overrides).

**Comment by gluons** [comment]
@pchaigno OK. I'll try. Thank you.
