### ISSUE TITLE
.gitattributes linguist-vendored attribute not working unless 'true' is set

### ISSUE THREAD

**Issue by cetinajero** [github/linguist#3737]
Hi,

I was reading the documentation https://github.com/github/linguist/blob/master/README.md#L48-52 and there is a little example on how to use `linguist-vendored` that goes like this:

```
$ cat .gitattributes
special-vendored-path/* linguist-vendored
jquery.js linguist-vendored=false
```

I followed the instructions to vendoring (exclude) some paths of my source code with the following snippet:

```
# Vendoring bourbon scss files
_sass/bourbon/* linguist-vendored
_sass/base/* linguist-vendored
_sass/neat/* linguist-vendored
```

I waited for a while but it didn't work until I forced with a `true` Bool on `.gitattributes` file like this:

```
# Vendoring bourbon scss files
_sass/bourbon/* linguist-vendored=true
_sass/base/* linguist-vendored=true
_sass/neat/* linguist-vendored=true
```

I think it's important to clarify this in the documentation `README.md` file so other readers don't have this issue.

If I can help, I'll gladly do so.

Regards.

**Comment by pchaigno** [comment]
Both should work (i.e., with and without `=true`). There may be some delay before it's applied.
You can check locally that it works by running linguist on a vendored file.

**Comment by lildude** [comment]
Yup, both definitely work. To clarify, when you make a change, a new low priority background job is kicked off to reassess your repository. This can take quite some time to take effect. With that in mind, your change to using `=true` which appeared to take effect straight away was probably you seeing the results of your first change which just happened to coincide with your subsequent update.

**Comment by NEGU93** [comment]
But how long does it take? I did my commit [yesterday](https://github.com/NEGU93/cvnn/commit/891d3e1dcca9c55aa16939a1ab38cc0826a4ef21) to avoid everything inside the docs file with the line `docs/** linguist-vendored=true` and it stills says my code is HTML and less than 10% Python (it is 100% Python btw).

**Comment by lildude** [comment]
@NEGU93 

> But how long does it take?

Normally a few minutes at most, but can take a few hours depending on how busy things are, eg US West Coast working hours are much busier than European hours.

> `docs/** linguist-vendored=true`  and it stills says my code is HTML and less than 10% Python (it is 100% Python btw).

First off, you don't need the `=true` part any more, but there's no harm keeping it.  Your change _has_ taken effect too.

The reason your repo is still showing such a high HTML content is because of one massive file you're _not_ ignoring: https://github.com/NEGU93/cvnn/blob/master/filled-3d-lines.html:

```console
$ github-linguist . --breakdown
91.43%  HTML
8.52%   Python
0.05%   Shell

Shell:
auto-version-commit.sh

Python:
cvnn/__init__.py
cvnn/__main__.py
cvnn/_version.py
cvnn/activation_functions.py
cvnn/cli.py
cvnn/cvnn_model.py
cvnn/data_analysis.py
cvnn/dataset.py
cvnn/initializers.py
cvnn/layers.py
cvnn/losses.py
cvnn/main.py
cvnn/montecarlo.py
cvnn/utils.py
debug/capacity_real_equivalent.py
debug/conv_memory_script.py
debug/fft_testing.py
debug/gradient_tape_complex.py
debug/initialization.py
setup.py
versioneer.py

HTML:
filled-3d-lines.html
$
$ 
It's 3.3MB on its own which far outweighs everything else.  It is also over 384kb so isn't indexed by search so won't appear in the list of files you see when clicking HTML in the sidebar.

**Comment by NEGU93** [comment]
Ups, I had not seen that file before, it is fixed! sorry about that (PS: didn't know about that `github-linguist . --breakdown` command, very helpful).

**Comment by albertbayazidi** [comment]
I have the same problem have been waiting more than 2 hours. Am trying to remove ipynb stas of this [repo](https://github.com/albertbayazidi/Prosjekt_Teknisk_fysikk)
