### ISSUE TITLE
HolyC not included in the list of languages

### ISSUE THREAD

**Issue by nukeop** [github/linguist#3742]
HolyC repositories don't have a language bar and the language is not being detected correctly.
Here's an example HolyC repository:
https://github.com/tramplersheikhs/megaman

HolyC is a language developed by Terry A. Davis for the Temple Operating System.

**Comment by pchaigno** [comment]
See the [guidelines to add support for a new language to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). If HolyC meets the requirement on in-the-wild usage, don't hesitate to open a pull request.
