### ISSUE TITLE
Use a bigger dataset to train the classifier

### ISSUE THREAD

**Issue by smola** [github/linguist#3745]
The classifier that is built from samples in the `samples` directory can be improved a lot by training on a bigger dataset. However, it is sometimes difficult to get enough samples that are released under a liberal license.

I would like to propose to built a separate project with the dataset, where each file retains each own license and authorship attribution and the dataset itself is released under a database license such as the [ODbL 1.0](https://opendatacommons.org/licenses/odbl/).

As far as I know, this would work because the dataset project wouldn't constitute a derived work, at least in GPLv3 (see: `A compilation of a covered work with other separate and independent works, which are not by their nature extensions of the covered work, and which are not combined with it such as to form a larger program, in or on a volume of a storage or distribution medium, is called an “aggregate” if the compilation and its resulting copyright are not used to limit the access or legal rights of the compilation's users beyond what the individual works permit. Inclusion of a covered work in an aggregate does not cause this License to apply to the other parts of the aggregate.`)

There would still be the question about if the model built from this dataset (`samples.json`) would constitute a derived work from all its parts. I guess that, in order to do this, we would need some legal advice. And maybe `samples.json` would need to get distributed separately, but I think this is a detail that could be worked out if you think the proposal is worth it.

**Comment by diegocrzt** [comment]
This is a really interesting idea, and wanted to ask, what are exactly the limitations or problems to include  code that is already open sourced ? or why could we just use sources like [Rosetta Code](https://github.com/acmeism/RosettaCodeData) (Disclaimer: I am not an expert in license as you may see)

**Comment by lildude** [comment]
> This is a really interesting idea, and wanted to ask, what are exactly the limitations or problems to include code that is already open sourced ?

Two-fold: licenses and performance.  See https://github.com/github/linguist/pull/2117 for more deets.

**Comment by smola** [comment]
I'm trying this with a generated dataset in a separate repository: https://github.com/smola/language-dataset
So far, testing with leave-one-out cross validation is giving very good results.

Licensing is tricky but it could be solved, see this repo for an example: https://github.com/smola/language-dataset
The key would be:
- Using a separate repository.
- License with a database license such as ODbl https://opendatacommons.org/licenses/odbl/
- Ensure that each of the included files has a license that allows redistribution.
- Add an index file with a link to the original source and the license.

**Comment by pchaigno** [comment]
> So far, testing with leave-one-out cross validation is giving very good results.

Very interested in the numbers when you'll have them. In particular, I'd love to see how many samples we need to add for a given improvement in accuracy (to see how much effort we'd have to make [on performance](https://github.com/github/linguist/pull/2117#issuecomment-74776022)).

**Comment by smola** [comment]
This will still take some time. I still have to get the dataset cleaned up to ensure that all samples are assigned to the right language. I'll post the benchmark once the dataset is accurate enough.
