### ISSUE TITLE
Specify disambiguation rules in YAML

### ISSUE THREAD

**Issue by smola** [github/linguist#3746]
## What?

Disambiguation rules in `heuristics.rb` are specified with a DSL in a very structured way. It should be possible to move this to YAML instead of Ruby.

## Why?

We work on a linguist port to Go: [enry](https://github.com/src-d/enry). Most of the Go code is generated from the YAML files in the linguist project. The disambiguation rules are also generated, but using a custom parser, written ad hoc for the `heuristics.rb` file. Having these rules specified in YAML would make it easier to reuse them in other languages.

This is something we've been thinking about for a long time, but I didn't make the proposal yet since I was not sure there is any benefit for the linguist project itself. However, it came to my knowledge that there is other people interested in porting linguist to other languages (e.g. C++), so it would be also good for them to have something like this.

The way I see it, the biggest value of linguist is not the code itself, but all the knowledge about language detection that is included in it, and making this knowledge more accessible from other software would benefit everyone by making it easier to collaborate.

## How?

If you think this is worth it, I can work on a specific implementation proposal and PR.

**Comment by smola** [comment]
cc @vmg

**Comment by vmg** [comment]
Hi @smola!

Sorry for the late reply, you caught me on holidays. I really like this idea. It should make contributing to Linguist easier for people who don't know Ruby, and it will let you kill the custom parser in `enry`, which I know you really want to do. :)

> If you think this is worth it, I can work on a specific implementation proposal and PR.

Absolutely, I'll merge a PR like that if it has identical functionality to the existing code. Let' see it!

**Comment by smola** [comment]
I'm implementing this in https://github.com/github/linguist/pull/4087. It's still work in progress, but the YAML syntax should already be pretty stable.

**Comment by smola** [comment]
Merged.
