### ISSUE TITLE
Wishlist: Gem to include the linguist command

### ISSUE THREAD

**Issue by hyandell** [github/linguist#3758]
The licensee RubyGem installs the licensee command. It would be very nice if the linguist RubyGem did the same (I'm invoking it from a NodeJS script: https://github.com/todogroup/repolinter/blob/master/lib/linguist.js ).

I have linguist-3.2.0 installed and no linguist script in ls ~/.rvm/gems/ruby-2.4.1/bin/.

**Comment by lildude** [comment]
Woah. You're running Linguist v3.2.0? That's nearly three years old. A lot has changed in that time.

Do you see this problem if you install the latest version (v5.2.0)?

Whilst I don't use RVM, I do use rbenv and I get the linguist command where I expect it to be:

```
$ which linguist
/Users/lildude/.rbenv/shims/linguist
$
```
