### ISSUE TITLE
Repository misclassifed as Roff

### ISSUE THREAD

**Issue by FabriDamazio** [github/linguist#3759]
https://github.com/FabriDamazio/Free-Inventory-Manager

**Comment by pchaigno** [comment]
[This file](https://github.com/FabriDamazio/Free-Inventory-Manager) is detected as Roff. You can change that using [Linguist overrides](https://github.com/github/linguist#overrides).

**Comment by Alhadis** [comment]
@FabriDamazio I believe @pchaigno meant to point to this file, here:

https://github.com/FabriDamazio/Free-Inventory-Manager/blob/master/FreeInventoryManager/FreeInventoryManager.Web/App_Data/Logs/Logs.txt.1

It's the `.1` suffix that's causing the misclassification, and this file is a whopping 9.68 MBs in filesize.

To fix this, add a `.gitattributes` file to your project's base directory, and add the following line:

~~~
*.1 linguist-language=Text
~~~

**Comment by pchaigno** [comment]
What he said :point_up:

**Comment by FabriDamazio** [comment]
Ty, i followed the instructions and created the file with the line. It didint worked yet. I need wait some amount of time?

**Comment by Alhadis** [comment]
It's probably cached. It should refresh the next time you modify a source file.

**Comment by FabriDamazio** [comment]
Ty, i followed the instructions and created the file with the line. It didint worked yet. I need wait some amount of time?

**Comment by pchaigno** [comment]
Yes, it's fine now:
```
$ linguist
71.21%  JavaScript
19.90%  C#
8.81%   CSS
0.06%   HTML
0.01%   ASP
```
The language bar should refresh next time you commit something.

**Comment by Alhadis** [comment]
What he said. ☝️

**Comment by FabriDamazio** [comment]
Lmao! Thank you!
