### ISSUE TITLE
Java repository language not recognized

### ISSUE THREAD

**Issue by igorbolic** [github/linguist#3766]
Linguist is not able to determine the [repository](https://github.com/igorbolic/memcached-spring-boot) language created on Github. This is an Gradle multi-module project written in **Java**. 

I've installed and run **Linguist** locally, still the language is not recognized.

**Comment by lildude** [comment]
Oooo several things are coming into play here:

1. everything under `gradle/wrapper` and the `gradlew` files are ignored as they are considered vendored code [here](https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml#L260-L263)
2. all the files in the remaining two directories only have files in paths that contain `cache` or `META-INF` with the former also being considered vendored code [here](https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml#L12-L13) and the latter containing unrecognised files.
3. Gradle itself is considered a data language [here](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L1576-L1582), as opposed a programming language, so the remaining `*.gradle` files don't count towards language statistics either.

Once you consider all that, you've only got markdown, text or unrecognised files which explains why you don't have any language statistics.

If you wish to have these things recognised, you'll need to implement a [manual override](https://github.com/github/linguist#overrides) to unvendor any vendored files you want counted and override the language for the Gradle files to something like Java.

**Comment by igorbolic** [comment]
Never mind. Works when committing `.gitattrubutes` file. Thanx for help.
