### ISSUE TITLE
Add support for the ante language

### ISSUE THREAD

**Issue by Elronnd** [github/linguist#3769]
Language is [here](https://github.com/jfecher/ante).  Since you seem to use sublime text for syntax highlighting, you'll probably want to use [this](https://github.com/jfecher/ante_sublime).

**Comment by pchaigno** [comment]
Please see the [guidelines to add support for a new language to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). If Ante meets the requirement on in-the-wild usage, don't hesitate to open a pull request. For syntax highlighting, GitHub supports TextMate, Sublime Text, and Atom grammars.
