### ISSUE TITLE
Some files are not indexed → improperly detected language

### ISSUE THREAD

**Issue by kroitor** [github/linguist#3770]
Hi! I'm developing a portable library in three languages (JavaScript, PHP and Python), I listed everything in .gitattributes:

```
*.js linguist-language=JavaScript
*.py linguist-language=Python
*.php linguist-language=PHP

ccxt.js linguist-language=JavaScript
ccxt-es5.js linguist-language=JavaScript
ccxt.php linguist-language=PHP
ccxt/__init__.py linguist-language=Python
```

But it still does not want to detect the language properly.

The files are:

```
~ 500Kb ccxt.js 
~ 550Kb ccxt/__init__.py 
~ 600Kb ccxt.php 
~ 1.5Mb ccxt-es5.js
```

The language is incorrectly detected as PHP, though the amount of code in JS is definitely larger. How can I fix the language to `JavaScript` as expected?

**Comment by kroitor** [comment]
UPD: forgot the link to the library: https://github.com/kroitor/ccxt

**Comment by kroitor** [comment]
When I click the language, I don't see the main ccxt.js files to be indexed at all...
https://github.com/kroitor/ccxt/search?l=javascript

**Comment by lildude** [comment]
I've clone your repository and run Linguist against it locally and this is returned:

```
$ ~/github/linguist/bin/linguist --breakdown
34.86%  PHP
33.85%  JavaScript
31.24%  Python
0.05%   Shell

JavaScript:
ccxt.js
countries.js
example.js
export-exchanges.js
run-tests.js
test.js
transpile.js
update-badges.js
vss.js

PHP:
ccxt.php
test.php

Python:
ccxt/__init__.py
setup.py
test.py

Shell:
push-wiki.sh
push.sh
test.sh
```

... which matches what the language bar shows and as you can see includes all the files you've pointed out with the exception of the `ccxt-es5.js`. This file doesn't count as it appears to be generated code and Linguist has detected this and excluded it from the results, thus making what is shown as correct.  

If you really want to have this file included in the stats, you can implement a [manual override](https://github.com/github/linguist#overrides).

> When I click the language, I don't see main ccxt.js files to be indexed at all...
> https://github.com/kroitor/ccxt/search?l=javascript

Yeah, this is a bit odd and something I've been meaning to raise an issue on as we've seen it quite a few times when clicking the language bar. The file is definitely being detected as Javascript, it's just not appearing in the search results for some reason.

**Comment by kroitor** [comment]
> If you really want to have this file included in the stats, you can implement a manual override.

Can you please show how to force-detect the ccxt-es5.js? It is generated, but I want to include it and to make it count for linguist. In the overrides section I see how to exclude, but I can't see how to force-include. Is that possible? I'm sorry if I missed something obvious here.

**Comment by kroitor** [comment]
I mean, my .gitattributes are currently as follows:

```
*.js linguist-language=JavaScript
*.py linguist-language=Python
*.php linguist-language=PHP

ccxt.js linguist-language=JavaScript
ccxt-es5.js linguist-language=JavaScript
ccxt.php linguist-language=PHP
ccxt/__init__.py linguist-language=Python
```

Don't how else I can make it count the generated JavaScript... Need a hint from you )

**Comment by Alhadis** [comment]
Erm, you may as well delete those lines, because they're telling Linguist what it already knows. ;-) `linguist-language` is meant to be used for files marked with the *wrong* language.

The attribute you're after is `linguist-generated`:

~~~
ccxt-es5.js linguist-generated
~~~

**Comment by kroitor** [comment]
@Alhadis , I don't really understand this. In the doc they say that 'linguis-generated' is for ignoring. And i need the exactly opposite – to count it (not to ignore it).

My .gitattributes file is now:

```
ccxt-es5.js linguist-generated
```

But it still shows wrong percentage of language usage (without counting for the biggest JS file). So, how do I fix it, really?

**Comment by Alhadis** [comment]
@kroitor Oh, sorry! I misinterpreted the explanation.

In that case, you'd use the same line in its negated form:

~~~
ccxt-es5.js linguist-generated=false
~~~

(Note that writing `linguist-generated=true` is equivalent to writing only `linguist-generated`, since it's a boolean-type attribute).

Now, the reason `ccxt-es5.js` is being marked as a generate file is... well, it's minified source. We have a routine to deal with files that've been minified and/or compressed: [`lib/linguist/generated.rb`](https://github.com/github/linguist/blob/edabdc75a5373e84dccc059a48cfc2d7c38bbde1/lib/linguist/generated.rb#L98-L113)

~~~ruby
    # Internal: Is the blob minified files?
    #
    # Consider a file minified if the average line length is
    # greater then 110c.
    #
    # Currently, only JS and CSS files are detected by this method.
    #
    # Returns true or false.
    def minified_files?
      return unless ['.js', '.css'].include? extname
      if lines.any?
        (lines.inject(0) { |n, l| n += l.length } / lines.length) > 110
      else
        false
      end
    end
~~~

I'm not sure why you'd want this file inflating your repository's statistics unfairly, but it's your choice. =)

**Comment by kroitor** [comment]
@Alhadis, thanks! Adding the `linguist-generated=false` helped!

> I'm not sure why you'd want this file inflating your repository's statistics unfairly, but it's all up to you. =)

Because otherwise it determines that my repository is PHP, whereas it is 33% js, 33% python and 34% php (because php has much longer syntax than the other two). And I don't want my library to be detected and shown to others as being mainly PHP – it's better for the library to be labelled as JS or Python in the marketing sense (PHP is not the main lang of my repo).

**Comment by Alhadis** [comment]
I understand wanting to distance yourself from PHP, heh.

Glad you've now got everything sorted out! =)
