### ISSUE TITLE
Ruby spec files misclassified as Python

### ISSUE THREAD

**Issue by rewinfrey** [github/linguist#3773]
I noticed several of the Ruby spec files in https://github.com/ruby-formatter/rufo/pull/12/files are being misclassified as Python files.

The contents of the files, like this example: https://github.com/bweave/rufo/blob/890662841e84cb93fd1822b71803e87d7c8fc6cb/spec/lib/rufo/formatter_source_specs/semicolons.rb.spec can be easily confused with Python syntax.

It is surprising these files are misclassified because their file extensions include `.rb`.

**Comment by Alhadis** [comment]
> It is surprising these files are misclassified because their file extensions include `.rb`.

Does that even have a bearing on classification if `.spec` [is registered](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L3537) as a Python extension...?

**Comment by pchaigno** [comment]
[The `.spec` extension is associated to RPM Spec, Ruby, and Python](https://github.com/github/linguist/blob/edabdc75a5373e84dccc059a48cfc2d7c38bbde1/lib/linguist/languages.yml), so it's expected that there would be some misclassifications, especially for small files.

We could add the `.ruby.spec` extension for Ruby, but is that [widespread enough](https://github.com/search?p=11&q=extension%3Aspec+filename%3Arb.spec&type=Code&utf8=%E2%9C%93)?

**Comment by rewinfrey** [comment]
@Alhadis @pchaigno thanks for comments. As @pchaigno asks, this doesn't appear to affect a large number of projects or files, and am closing this out.
