### ISSUE TITLE
It is possible for a repository to have languages adding up to >100%

### ISSUE THREAD

**Issue by CAD97** [github/linguist#3774]
![>100% classification](http://i.imgur.com/rEwg45a.png)

(#3600 probably enabled this.)

It is possible to have a repository's language makeup add up to >100%. https://github.com/behnam/rust-unic currently does so (though a PR is in suppressing interpretation of `.rs` files as anything other than Rust). The commit that has the issue: https://github.com/behnam/rust-unic/commit/b6b521118c90f0130f76c826f7f9d892f45b2ee8

I _suspect_ this was triggered by the addition of a Rust file that Linguist interpreted as RenderScript. My guess is then every other Rust file (`.rs`) was then double-counted, once as Rust and once as RenderScript.

**Comment by lildude** [comment]
I think I'm missing something... My maths says the language bar in you screenshot and as the repo stands at this moment...

![img_0161](https://user-images.githubusercontent.com/627280/29304355-6c9c71fe-818a-11e7-96f5-16a0b00412fb.PNG)

... adds up to 100%. 😉

**Comment by CAD97** [comment]
The PR to change `.gitattributes` went through. Here's my fork with the pictured language bar: https://github.com/cad97/rust-unic/

(ping @lildude)

**Comment by lildude** [comment]
Thanks @CAD97 but I'm still not seeing where you're seeing the total exceeding 100%: 

53.7 + 45.5 + 0.8 = 100

98.3 + 1.7 = 100

Can you point out specifically where you are seeing the total exceeding 100%

**Comment by CAD97** [comment]
oh, I can't add............................................................................................
