### ISSUE TITLE
Repository with wrong mainly Language

### ISSUE THREAD

**Issue by sant0ro** [github/linguist#3787]
So... Linguist it's saying my repository is it 58.9% HTML. but doesn't exists any HTML file at all.

Repo: https://github.com/sant0ro/chocolatey
Linguist: https://github.com/sant0ro/chocolatey/search?l=html

![image](https://user-images.githubusercontent.com/12037269/29491810-5beb9766-853d-11e7-97dc-d69f259d6612.png)

So what I can do in this scenario?

Observation.: Some `.php` files have at all html codes. But are mixed with php.... (But there isn't any file with `.html` extension.

**Comment by lildude** [comment]
All the files under `resources/views/` mostly contain HTML and it is this that is resulting in HTML being the predominant language. 

You'll need to use a [manual override](https://github.com/github/linguist#overrides) if you want these files to be counted as PHP instead.

**Comment by sant0ro** [comment]
I see, thanks @lildude 

And thanks for the quick answer.

Upvoted.
