### ISSUE TITLE
Language stats on repository landing page incorrect

### ISSUE THREAD

**Issue by seppestas** [github/linguist#3795]
We have a repository consisting of mostly KiCAD design files and C++ firmware files (and Makefiles, since someone checked in dependency files -.-). However when looking at the project's landing stats it shows 62.6% Pyhton and it does not mention the KiCad files.

![screen shot 2017-08-24 at 14 23 37](https://user-images.githubusercontent.com/1408377/29709102-73ea43c4-898b-11e7-8869-b90749b0a007.png)

The only Python files in our repository are small boilerplated config files for [mbed-cli](https://github.com/ARMmbed/mbed-cli).

Looking at the project's search view gives a better image of what is actually in the repository.

![screen shot 2017-08-24 at 14 24 44](https://user-images.githubusercontent.com/1408377/29709186-bdbf246a-898b-11e7-840f-ba3084651fbc.png)

**Comment by Alhadis** [comment]
👋 Hey @seppestas,

Before I explain about KiCad, it's important you understand how GitHub classifies languages, and how that classification impacts the way a repository is categorised.

Linguist distinguishes between 4 different language types
1. **Programming:**
Executed or interpreted source code (e.g., C++, JavaScript, Perl, Assembly, etc)
2. **Markup:**
Code defining a document's presentation or formatting., This can include "true" markup languages (e.g., HTML), templating languages (e.g., Blade, Handlebars), or programming languages mostly used as page-description languages (e.g., PostScript, Roff, TeX).
3. **Prose:**
Similar to markup, except the content is composed mostly of human-readable content, and can usually be consume without additional processing. Most "lightweight markup" languages fall into this category (e.g., Markdown, AsciiDoc).
4. **Data:**  
If it's plain-text which doesn't fit into any of the above categories, it probably comes under `Data`.

Only the first two language-types are considered when calculating a repository's language usage. This stops repositories being classified as being JSON or XML projects, as these files tend to be very large and can unfairly skew how a repository is classified.

Now, until recently, KiCad had been categorised as a ["programming" language](https://github.com/github/linguist/pull/3743/files?diff=split#diff-3552b1a64ad2071983c4d91349075c75L2141). We both know that's an awfully far-fetched way to classify KiCad project files. The KiCad language's type was changed in #3743, which went live on GitHub with the recent release of [v5.2.0](https://github.com/github/linguist/releases/tag/v5.2.0). That's the reason you're suddenly seeing your KiCad projects no longer classified as "KiCad".

/cc @5N44P, who voiced similar concerns in #3784.

**Comment by 5N44P** [comment]
Hi @Alhadis, thank you for your explanation.

So this won't be revised? And the same rule will be applied e.g. to Eagle and all the other not strictly programming languages that exist on github repositories? 

Thank you again, 
Valerio

**Comment by seppestas** [comment]
Thanks for the explanation @Alhadis.

In this case Kicad files should be categorised as "Markup" IMHO. The layout files are s-expression based files very similar to XML/HTML, and are definitely human-readable (for humans familiar with the syntax). Just like HTML, their purpose is to be rendered, both in GUI applications to accommodate editing and to image files for production.
The schematic files are weirder, but still human readable and again meant to be rendered and exported to netlists.

A typical project for us contains both KiCad design files and C/C++/Assembly source files, together with some build scripts typically based on makefiles and python. Having it flagged as just a C++ project, or worse, a Python project, seems wrong to me.

Another thing I don't get is why [Eagle projects are still being recognized as such](https://github.com/search?utf8=%E2%9C%93&q=language%3AEagle&type=Repositories&ref=advsearch&l=Eagle&l=), even though [Eagle files are also classified as data](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L1088).

I strongly agree with #3784 and I think the changes in #3743 was a pretty bad regression for KiCad users. [It makes it impossible to find KiCad projects on Github](https://github.com/search?utf8=%E2%9C%93&q=language%3A%22KiCad+Board%22&type=Repositories&ref=advsearch&l=KiCad+Board&l=) 😥. 

In any case, this does not explain why Github thinks the repository contains 62.6% Python files. As you can see, there is only one Python file checked in, and it contains fairly little code. There is also no Objective-C in this repository, only C++ and a bit of C.

**Comment by Alhadis** [comment]
Eagle has already been corrected, actually. Any Eagle-type projects you see on GitHub are likely the result of caching. Being able to search using a data-type language is probably a bug with GitHub's UI... 😕 

> In this case Kicad files should be categorised as "Markup" IMHO. The layout files are s-expression based files very similar to XML/HTML, and are definitely human-readable (for humans familiar with the syntax). Just like HTML, their purpose is to be rendered, both in GUI applications to accommodate editing and to image files for production.

Erm, you've just described a perfect example of what the site considers a data format... its definition of `markup` is quite literally document-specific. Otherwise, an INI file that happens to describe the shape and layout of something visual may as well be regarded as "markup" too.

I think the underlying issue here is not being able to override the classification of a repository, which is a feature that has been requested in the past, but is ultimately up to the decision of GitHub staff...

**Comment by seppestas** [comment]
> Erm, you've just described a perfect example of what the site considers a data format... its definition of markup is quite literally document-specific. Otherwise, an INI file that happens to describe the shape and layout of something visual may as well be regarded as "markup" too.

Could you clarify what you mean with "document specific"? While an INI file is a generic file that can be used for a variety of purposes, the purpose of a KiCad schematic and layout file is always the same. I fail to see the difference between an HTML, which I think we can agree clearly falls under the "Markup" category, and e.g a KiCad layout. Both are an hierarchical model of something that can be rendered on a screen / a piece of paper / a PCB.

But again, we're getting sidetracked here. This issue is about the language stats being incorrect. There is no 62.5% python code in the affected repo. Could it be all the KiCad files are being counted as Python files? I think we should continue the discussion about KiCad file formats in Github in #3784 or a new issues more broadly addressing non-code file formats.

**Comment by seppestas** [comment]
It looks like a lot of KiCad schematic files got mis-qualified as KiCad layout files. Sadly this is a proprietary repo, so I can't really expose a lot more details without risk of breaking our NDA with our client. I'll look into creating some open-source example repositories.

**Comment by seppestas** [comment]
I was able to reproduce the problem by running `linguist` localy on the repository. Output:
```
84.86%  Python
14.40%  C++
0.31%   C
0.26%   HTML
0.10%   Objective-C
0.04%   Makefile
0.02%   Shell
```
This is definitely incorrect.

The stats did not change when I removed or added vendored code (which I guess is by design?). The only place containing a lot of Python code is vendored code, all the rest is pretty much only C++ source code, KiCad design files, documentation in the form of PDFs and PCB production (gerber, CSV and drl) files. The only python file checked into the repo is the ~50 line mbed_settings.py file.

My guess is still that for some reason, Linguist counts data files like the KiCad files toward Python.

**Comment by seppestas** [comment]
Upon further investigation, the problem seems to be that my colleague checked in the source code for [KiCad StepUp](https://sourceforge.net/p/kicadstepup/wiki/Home/)... 3 times. This is Python source code using a special .FCMacro extension (as in [FreeCAD](https://www.freecadweb.org/) Macro) but probably recognized by Linguist because of the `#!/usr/bin/python`.

The stats now show
```
95.12%  C++
2.05%   C
1.71%   HTML
0.68%   Objective-C
0.28%   Makefile
0.16%   Shell
```
which is closer to what I expect since the KiCad source files are classified as data because of #3743.

I still think it's weird that clicking "Python" in the language stats only ends up showing the Python files with a .py extension in the repo's search view. I would expect this to show the same files as `linguist --breakdown`.
