### ISSUE TITLE
MinGW builds, gemspec escape_utils to 1.2?

### ISSUE THREAD

**Issue by MSP-Greg** [github/linguist#3797]
Apparently a recent patch in `escape_utils` allows it to compile on MinGW builds.  See [oneclick/rubyinstaller2 #73](https://github.com/oneclick/rubyinstaller2/issues/73#issuecomment-325385907) response by brianmario ([`charlock_holmes`](https://github.com/brianmario/charlock_holmes) & [`escape_utils`](https://github.com/brianmario/escape_utils))

Also, #3649

Could [gemspec](https://github.com/github/linguist/blob/63ff51e2ed4b0f89cdf28ba57f4a8d98ccdc82ea/github-linguist.gemspec#L17) be updated?  Thanks...

**Comment by lildude** [comment]
> Could gemspec be updated? Thanks...

In theory, yup, though I'll need to see what the knock-on effect is, if any, on GitHub.com

**Comment by gluons** [comment]
I unable to use `linguist` on any Windows laptop now. Can't find the way. Sad 😭
