### ISSUE TITLE
Help with classifying code

### ISSUE THREAD

**Issue by teaearlgraycold** [github/linguist#3801]
If I have a list of files to classify how do I avoid miss-classifying BLOBs, markdown, etc. as source code?

Currently when classifying files I am feeding the repository's list of languages (as stated by the GitHub API), but I'm finding that SVGs, markdown, and whatnot are being classified as `Shell`.

Is there a "null" language that I should pass in to the call method of the Classifier class? Is there a heuristic I need to check first on whether a file is even code at all?

**Comment by lildude** [comment]
@teaearlgraycold could you provide a bit or information on how you're attempting to use Linguist as it should already be doing what you're asking.

**Comment by pchaigno** [comment]
@teaearlgraycold As I understand, you're trying to use the Classifier strategy of Linguist directly. Linguist was not meant to be used that way. The Classifier strategy alone won't provide good results and you should go through the full list of strategies, including the selection of candidate languages based on the file extension.

**Comment by teaearlgraycold** [comment]
Apologies for leaving this open. I ended up doing this:

https://github.com/teaearlgraycold/Commit-Language-Visualizer/blob/master/read_commits.rb#L20

```ruby
# Determine the language of a given file
def get_lang(client, repo, file)
  blob = VisBlob.new(file.filename, '')
  strategies = [
    Linguist::Strategy::Filename,
    Linguist::Strategy::Extension
  ]

  strategies.
    map { |strat| strat.call(blob, nil) }.
    flatten.
    select { |language| not language.color.nil? }.
    first
end
```
