### ISSUE TITLE
Incorrect language classication

### ISSUE THREAD

**Issue by Anobium** [github/linguist#3803]
https://github.com/Anobium/Great-Cow-BASIC

All GCB files are BASIC files.  Currently https://github.com/Anobium/Great-Cow-BASIC is classified as C or INI.

Can we add GCB to the Language ids please?

Evan

**Comment by lildude** [comment]
Please have a look at the [guidelines to add support for a new language to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md). If GCB meets the requirement on in-the-wild usage and you can provide the necessary information, feel free to submit a pull request.
