### ISSUE TITLE
Perl's xs ppport.h is detected as C++

### ISSUE THREAD

**Issue by Mons** [github/linguist#3808]
Many XS Perl libraries are detected as C++, since all of them include generated tool file/header `ppport.h` (ex: https://github.com/Mons/EV-Tarantool/search?l=C%2B%2B)
It is very big and with a great probability will become top1 language in repo.

I think it would  be good to include it into vendor.yml

**Comment by lildude** [comment]
The comment in the file "Automatically created by..." suggests this may be better classified as "generated". It could also be classified as vendored as you suggested, but it really depends if you want changes to it to appear in PR diffs or not (vendored do, generated don't).

Please feel free to review https://github.com/github/linguist/blob/master/CONTRIBUTING.md and submit a PR.

**Comment by lildude** [comment]
Flagging as stale. Linguist is behaving as expected as this file is technically a C-family header file, and we've not received a PR to change the behaviour.
