### ISSUE TITLE
buildozer.spec missidentified as ruby

### ISSUE THREAD

**Issue by Narcolapser** [github/linguist#3814]
I have a couple of projects written in python making use of buildozer to compile them for android. These are pure python repos but because of the presents of the buildozer.spec file, they are seen as containing ruby:

https://github.com/Narcolapser/Kivy-Kazam/search?l=ruby
https://github.com/Narcolapser/Octo/search?l=ruby

I believe buildozer.spec should just be viewed as a plain text or a config file. It's not a programming language, just options.

**Comment by Alhadis** [comment]
Well, they're certainly config files... and they appear to be INI-style in their syntax. My recommendation would be to override their language classification using a `.gitattributes` file. Simply add one to the root directories of each project, which contain the following lines:

~~~
bulldozer.spec linguist-language=INI
~~~

This will cause Linguist to treat `buldozer.spec` files as being INI.

You can read all about the [overrides features here](https://github.com/github/linguist#using-gitattributes).

**Comment by pchaigno** [comment]
@Alhadis Should we add [`buildozer.spec`](https://github.com/search?utf8=%E2%9C%93&q=filename%3Abuildozer.spec&type=) as a filename for INI?

**Comment by Alhadis** [comment]
Yep, I'd say so. Only 1,382 results, but they're extremely well-distributed. 954 unique repositories, distributed between 770 users. Coupled with the fact their classifications are all over the place, it certainly warrants inclusion:

<img src="https://user-images.githubusercontent.com/2346707/30242006-990d4230-95d1-11e7-9c4f-bf5081a8cb7e.png" width="242" alt="Figure 1" />

PR following up shortly.

**Comment by Narcolapser** [comment]
Grand! Thanks.
