### ISSUE TITLE
SaltStack file missidentified as Scheme

### ISSUE THREAD

**Issue by thewilkybarkid** [github/linguist#3821]
[This `.sls`](https://github.com/elifesciences/profiles-formula/blob/24141a29ab89ceb07524fd9e65fbdaf0e45495f1/salt/pillar/profiles.sls) file is being treated as Scheme, rather than SaltStack. All the other files in the repo (eg [this one](https://github.com/elifesciences/profiles-formula/blob/24141a29ab89ceb07524fd9e65fbdaf0e45495f1/salt/pillar/top.sls)) are correctly identified as SaltStack.

**Comment by lildude** [comment]
Sorry about the delay in responding to this.

It looks like we've got `.sls` associated with both SaltStack and Scheme but without a heuristic to differentiate things. As a result, the analysis is falling through to the naïve bayesian classifier and it's getting it wrong for this file, but only just. It's very close.

We'd certainly welcome a PR to add a heuristic and maybe another sample to help improve the detection in future.

In the mean time you can force the correct classification using an [override](https://github.com/github/linguist#overrides)
