### ISSUE TITLE
Some C# operator overloads breaking syntax highlighting after their appearance

### ISSUE THREAD

**Issue by Elmuti** [github/linguist#3831]
https://gist.github.com/Elmuti/ae2a071cc9d21f78d0f993a49bef0396#file-vector3-cs-L170

On Line 170 I define a "=="-operator overload and it seems to break all the highlighting from that line onwards, presumably due to the highlighter not recognizing it as an overload, but rather an actual == operator.

**Comment by lildude** [comment]
Borrowing @pchaigno's words to say...

Linguist only selects the grammar to use for highlighting. For C#, GitHub uses [atom/language-csharp](https://github.com/atom/language-csharp). You should open an issue there if there isn't already one.

**Comment by pchaigno** [comment]
I actually have a saved reply for that one :-)
