### ISSUE TITLE
perl files with no extension and POD and a shebang should be rendered as syntax-highlighted perl, not POD

### ISSUE THREAD

**Issue by dgholz** [github/linguist#3832]
This bug was introduced in #3735. Here's an expanded version of my comment from there.

This change recognizes files with no extension and a perl shebang and POD contents as POD files, but I'd expect them to be shown as syntax-highlighted perl. I would expect POD-only files to (maybe) have a `.pod` extension, and (always) no shebang. Some examples from CPAN:

https://metacpan.org/source/LEONT/Module-Build-0.4224/lib/Module/Build/API.pod has no shebang and a `.pod` extension.

https://metacpan.org/source/LEONT/Module-Build-0.4224/lib/Module/Build/Cookbook.pm has no shebang and a `.pm` extension.

Here's an example of where linguist chooses to render as POD rather than as syntax-highlighted perl: https://github.com/sitaramc/gitolite/blob/5c2fe87019dadbecb1883bedd075cd07b07b2078/src/gitolite
It previously displayed as a highlighted perl script (good), but now displays as the embedded POD (requiring me to use the Raw view to be able to see the code). It has a shebang.

Please fix it to correctly detect these kinds of files as perl (not POD) or revert it, thanks!

**Comment by biell** [comment]
Change #3735 needs to be rolled-back.  If a file starts with "#!/usr/bin/perl", "#!/usr/bin/env perl", or anything similar, then it should be rendered as perl code, not as pod.  Rendering as code is the correct decision 99% of the time when a shebang is present, and so should be the default.

If you want to review the entire file and find no actual code, then you can render as pod.  But, when in doubt, render as code when a shebang is present.  This bug affects hundreds of repositories; including, but not limited to:

  * https://github.com/libwww-perl/libwww-perl
  * https://github.com/rurban/perl-compiler
  * https://github.com/oetiker/mrtg
  * https://github.com/briandfoy/PerlPowerTools
  * https://github.com/duckduckgo/duckduckgo-publisher
  * https://github.com/neilb/Module-Path
  * https://github.com/SUSE/smt
  * https://github.com/hachi/Perlbal
  * https://github.com/skx/sysadmin-util
  * https://github.com/kraih/mojo
  * https://github.com/duckduckgo/p5-app-duckpan
  * https://github.com/jmcnamara/excel-writer-xlsx
  * https://github.com/neilb/Net-Dict
  * https://github.com/preaction/Statocles
  * https://github.com/gugod/App-perlbrew
  * https://github.com/skx/templer
  * https://github.com/kasei/perlrdf
  * https://github.com/briandfoy/Unicode-Tussle
  * https://github.com/PerlDancer/Dancer2
  * https://github.com/briandfoy/git-github-creator
  * https://github.com/pssc/squeezy
  * https://github.com/soarpenguin/perl-scripts
  * https://github.com/msimerson/mail-dmarc
  * https://github.com/abw/Template2
  * https://github.com/bruceravel/demeter
  * https://github.com/davorg/perlanet
  * https://github.com/nichtich/Pandoc-Elements
  * https://github.com/pjlsergeant/test-bdd-cucumber-perl
  * https://github.com/beanz/xpl-perl
  * https://github.com/skx/markdownshare.com
  * https://github.com/Starlink/ORAC-DR
  * https://github.com/PerlDancer/Dancer
  * https://github.com/fusioninventory/fusioninventory-agent
  * https://github.com/beyondgrep/ack3
  * ...

**Comment by ascherer** [comment]
[Seconded](https://github.com/ascherer/debbuild/blob/master/debbuild#L1703). Please give priority to highlighted code over pod.

**Comment by omkensey** [comment]
I spent some considerable time the other day looking for a Perl script in the spacewalk repo and seeing only what looked like a rendered README where it should be, thinking maybe somebody had committed over it accidentally, going back in time further and further.  I stumbled on the idea of viewing it Raw purely by chance, and sure enough, there was the Perl code I'd been wanting all along.

**Comment by kivikakk** [comment]
Fix incoming. Sorry for such a long delay, all. :heart:

**Comment by kivikakk** [comment]
Fix is now live.

**Comment by dgholz** [comment]
Thank you!
