### ISSUE TITLE
C# code is detected as SmallTalk

### ISSUE THREAD

**Issue by jannesrsa** [github/linguist#3833]
51.6% of the code in my repro gets identified as SmallTalk, but all code in the repro should be C#.

Things I've tried:
- Changed all code files to UTF8
- Added a .gitattributes to exclude *.dll files and GlobalSuppressions.cs.
- Add `using System;` to all code files

https://github.com/jannesrsa/smartobjects-services-tests/tree/FixLlinguist

**Comment by pchaigno** [comment]
Have you tried this in the `.gitattributes`?
```
*.cs linguist-language=C#
```

**Comment by jannesrsa** [comment]
I've just tried it, but it doesn't look like it makes a difference.
https://github.com/jannesrsa/smartobjects-services-tests/blob/FixLlinguist/.gitattributes

**Comment by lildude** [comment]
The repo statistics only apply to the primary branch of your repo, which is normally `master`. Unless `FixLInguist` is your primary branch as configured within your repo settings, your changes won't take effect as your `master` branch doesn't contain a `.gitattributes` file.

**Comment by jannesrsa** [comment]
Thanks, after merging the changes to `master` with the `.gitattributes` from the branch, the language is now identified correctly.

**Comment by lildude** [comment]
Geen probleem 😉  🤘 🇿🇦

**Comment by ChayimFriedman2** [comment]
Had the same issue; fixed thanks to @pchaigno 's solution.

**Comment by LeMorrow** [comment]
@pchaigno's solution works, just be patient as the changes aren't immediate (at least they weren't for me). Took between 5-20 minutes. If it doesn't work, try making another change to the repository (change any file) which should fix it for you.
