### ISSUE TITLE
.mjs alias for js though supported, doesn't get highlighted

### ISSUE THREAD

**Issue by zeusdeux** [github/linguist#3834]
The `.mjs` extension for js modules is [already registered as an alias](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L2101) but it [doesn't seem to be kicking in](https://github.com/zeusdeux/goodreads-graphql/blob/es6/schema.mjs) as of 09/22/2017.

**Comment by Alhadis** [comment]
Hey @zeusdeux,

Changes made to Linguist won't take effect on GitHub until a new release is cut. I believe the next release will be somewhere in early October, so you won't see syntax highlighting for `.mjs` files before then.

**Comment by zeusdeux** [comment]
Fair. Thanks! Closing.
