### ISSUE TITLE
Language of repo incorrectly identified as OpenEdge ABL

### ISSUE THREAD

**Issue by tmadhuri** [github/linguist#3835]
I had a repo with majorly python files and some data files in `.txt` and `.p`. The `.p` files are incorrectly identified as OpenEdge ABL source files.

Edit: Repo link: https://github.com/tmadhuri/Community-Detection

**Comment by lildude** [comment]
This is happening because of the `.p` extension. This is only associated with OpenEdge. You'll need to implement a manual override to force these to Python or use one of the more commonly used Python extensions for those files.

**Comment by pchaigno** [comment]
See the [README.md](https://github.com/github/linguist#overrides) for manual overrides.
