### ISSUE TITLE
.scpt files not identified

### ISSUE THREAD

**Issue by xilopaint** [github/linguist#3840]
`.scpt` files are not identified as AppleScript in the repo: https://github.com/xilopaint/alfred-things.

**Comment by Alhadis** [comment]
Hey @xilopaint,

The reason those files aren't being counted in your repository's language statistics is that they've been compiled. Linguist doesn't analyse binary (non-textual) files. As for textual `scpt` files, Linguist [already recognises](https://github.com/github/linguist/blob/e98728595bc2f3e72b0668d60e31cbe441c48799/lib/linguist/languages.yml#L257) that file extension as being AppleScript.

So the solution here is to simply replace the `scpt` files in your repo with their uncompiled forms. I understand you mightn't have meant to publish them as compiled scripts: that's something that macOS's script editor does automatically when you save it, I believe.

**Comment by xilopaint** [comment]
Thanks for the fast response and explanation! I just replaced the `scpt` file for a `applescript` one.
