### ISSUE TITLE
Angelscript detected as Actionscript

### ISSUE THREAD

**Issue by ANybakk** [github/linguist#3841]
AngelScript ( http://www.angelcode.com/angelscript/ ) is a scripting language with C++-like syntax. Files usually have a **.as** file ending, which causes them to be recognized as ActionScript, which is incorrect. Would be nice if that didn't happen.

**Comment by codecat** [comment]
Related pull request: #3422

Can this file extension ambiguity be solved at all?

**Comment by ifarbod** [comment]
I'd say have an alternate extension for it as well (.acs for instance - which is short for [AngelCode](http://angelcode.com) Script)

**Comment by pchaigno** [comment]
@ANybakk Is this still an issue? Linguist supports both Angelscript and Actionscript. You can use [Linguist overrides](https://github.com/github/linguist#overrides) if the classification is incorrect in your repository.

**Comment by codecat** [comment]
This was merged in #3844. @ANybakk's [repositories](https://github.com/ANybakk?tab=repositories) are listed as mixed Actionscript & Angelscript, I assume because some haven't had recent pushes in order to update the language detection.

**Comment by pchaigno** [comment]
> This was merged in #3844.

Oo right! 👍 

> @ANybakk's repositories are listed as mixed Actionscript & Angelscript, I assume because some haven't had recent pushes in order to update the language detection.

Yes, that would be the likely reason.
@ANybakk I'm going to close this; don't hesitate to open a new issue if you still have issues after pushing to those repositories.

Thanks @codecat for the precision!
