### ISSUE TITLE
bin/linguist conflicts with Qt5.7

### ISSUE THREAD

**Issue by q5sys** [github/linguist#3843]
Qt5.7 uses  bin/linguist as a core component for handling translations within qt applications.  If Qt is installed, this package will conflict as it tries to replace bin/linguist with its version.

Only resolution I can see is for one project to use a different binary name or path.  I don't want to pick sides in the 'which software has a greater claim to bin/linguist', but I kinda feel like it'd be easier to get changed in GitHub than it would be in Qt.

**Comment by pchaigno** [comment]
@lildude I've encountered this problem as well on at least one of my systems. Any idea how we could solve this?

**Comment by lildude** [comment]
I've not played with Qt in years and don't plan to anytime soon but isn't this only really a problem if you _don't_ use something like rvm or rbenv to manage your Ruby envs?
