### ISSUE TITLE
Jupyter Notebook being counted as part of project despite being vendored.

### ISSUE THREAD

**Issue by peter-moran** [github/linguist#3845]
https://github.com/peter-moran/highway-lane-tracker

My git repository is marked as being primary Jupyter Notebook, even though I've set `.gitattributes` to ignore it. I've tried multiple settings and nothing works!

**Comment by lildude** [comment]
It's cos you've got a typo in your `.gitattributes` file: `experiements` 😉

**Comment by peter-moran** [comment]
Ah! I naturally checked the spelling of everything else. Thank you!

FYI for anyone checking this in the future, I found out the best way to make sure this does not happen is to use `git check-attr` first.
