### ISSUE TITLE
Scala project identified as XSLT

### ISSUE THREAD

**Issue by luminescent** [github/linguist#3847]
Hi 

I have this repository: https://github.com/luminescent/try-rss which is classified as XSLT, although it is developed in Scala.

**Comment by lildude** [comment]
It may be developed predominantly in Scala, but it does contain [two rather large (compared to the other files in the repo) XSLT files](https://github.com/luminescent/try-rss/search?l=xslt) hence the classification.

You'll need to implement a manual override if you don't want these included in the stats.

**Comment by pchaigno** [comment]
@luminescent You can find diverse solutions to implement overrides in the README: https://github.com/github/linguist#overrides

**Comment by luminescent** [comment]
Thank you for the explanations and suggestions. All clear now.
