### ISSUE TITLE
Makefiles with .wat extensions misclassified as WebAssembly

### ISSUE THREAD

**Issue by FlyingJester** [github/linguist#3854]
The Watcom makefiles in https://github.com/FlyingJester/Kashyyyk2/ are being classified as WebAssembly, which is incorrect. They are wmake-compatible makefiles, and the .wat is short for watcom.

**Comment by Alhadis** [comment]
The ideal solution would be if Linguist supported pattern-based matching of filenames to identify file extensions, so any filename beginning with `Makefile.*` could be recognised as one. Sadly, that's not how things work, I'm afraid. In the meantime, you'll need to override the files manually by using a `gitattributes` file with a `linguist-language` directive in it. You can read more about [that subject here](https://github.com/github/linguist#using-gitattributes)).

The exception is if `Makefile.wat` is widely-used enough on GitHub to warrant registering in Linguist's [`languages.yml`](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml) directory.
