### ISSUE TITLE
Node module repo declared HTML

### ISSUE THREAD

**Issue by Steveorevo** [github/linguist#3875]
Node-RED module (based on NodeJS) labelled as HTML project. Pretty safe to say that if a project contains a package.json file and subsequent dependencies section within it that it's going to be a JavaScript based project. This issue appears on, despite placing a .gitattributes file (as suggested in prior support) as well as .getattributes'less repos:

https://github.com/Steveorevo/node-red-contrib-string

https://github.com/Steveorevo/node-red-contrib-nbrowser

**Comment by lildude** [comment]
Both repo's are being identified 100% correctly, regardless of your .gitattributes overrides (which aren't doing anything Linguist isn't already doing).  You're missing one vital point about how Linguist calculates the language stats (taken from the [README](https://github.com/github/linguist#troubleshooting) - emphasis mine):

> The Language stats bar **displays languages percentages** for the files in the repository. The percentages are calculated based on the **bytes of code** for each language as reported by the List Languages API.

For https://github.com/Steveorevo/node-red-contrib-string, you have 32.1 KB of HTML vs only 3.62 KB of Javascript, thanks to [this one file](https://github.com/Steveorevo/node-red-contrib-string/search?l=html) (clicking the language bar and then HTML brings you to this page).

For https://github.com/Steveorevo/node-red-contrib-nbrowser, you have 40.5 KB of HTML vs 20.5 KB of Javascript thanks to these [two files](https://github.com/Steveorevo/node-red-contrib-nbrowser/search?l=html).

If you want your repo to appear as if it is predominantly Javascript, you'll either need to write more Javascript 😉  or mark the HTML files as vendored, generated or documentation using an override.

**Comment by Steveorevo** [comment]
Ahh, explains why many node-red objects are showing up as HTML vs JavaScript. Do any of the markings for vendored, generated, or documentation preserve visibility in diffs? (rumor is vendored omits this). Thanks for the reply.

**Comment by lildude** [comment]
Only generated affects diff visibility (also stated in the README) so vendored should probably do the trick. Or you could add a topic to the repo as the language bar doesn't really depict the repo language; it only shows the breakdown of the languages in a repo, and HTML is a valid and common occurrence (expected, maybe?) language for Node-red repos AFAICS.

**Comment by Steveorevo** [comment]
Ahh, then this open issue may no longer be an issue https://github.com/github/linguist/issues/2206
Node-RED's focus is JavaScript. It's a "runtime/design time" paradigm kinda animal. I'll try documentation first; as the HTML in Node-RED projects contain a **brief** "design time" explanation of the JavaScript object, which I guess is a documentation of sorts. But it also contains mostly JavaScript to aid the IDE in interfacing with said JavaScript "runtime" object.

**Comment by lildude** [comment]
> Ahh, then this open issue may no longer be an issue #2206

Yes and I think we can probably close it as you can now mark files as generated or not in `.gitattributes`. We did try implementing suppression for vendored files but this was reversed but I can't remember why right now.
