### ISSUE TITLE
 Edje data collection (.edc) files are not recognized

### ISSUE THREAD

**Issue by sylveon** [github/linguist#3876]
https://www.enlightenment.org/program_guide/edje_pg

Example repo: https://github.com/sylveon/terminology-themes
Tells me my repo is 100% makefile.

**Comment by tessarin** [comment]
It says 100% Makefile as a side effect of not recognising _.edc_. Check out the [contributing guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md) if you plan to add this language extension yourself. Also, from the same document:

> We try only to add new extensions once they have some usage on GitHub. In most cases we prefer that extensions be in use in hundreds of repositories before supporting them in Linguist.

**Comment by pchaigno** [comment]
What he said :point_up:
