### ISSUE TITLE
Object-C code detected while absolute zero files are present, also, no files are detected.

### ISSUE THREAD

**Issue by siscia** [github/linguist#3881]
Hi All :)

I have this repo: https://github.com/RedBeardLab/rediSQL

The github bar says that most of the code is in Objective-C

![screenshot from 2017-10-30 12-44-45](https://user-images.githubusercontent.com/640555/32169275-2301ad44-bd70-11e7-81b8-d56263ab7518.png)

While actually no code in Objective-C is committed in the project.

Moreover, If I click on Objective-C, the page is completely empty (this is actually correct).

How can I fix this?

Best Regards,

**Comment by tessarin** [comment]
This comes from the big `sqlite3.h` header:

```
$ linguist --breakdown
85.92%  Objective-C
11.06%  Rust
2.98%   Python
0.03%   C++

Rust:
build.rs
src/lib.rs
src/redis.rs
src/redisql_error.rs
src/sqlite.rs

C++:
redis_dependencies.h
sqlite_dependencies.h

Objective-C:
sqlite3.h

Python:
test/correctness/test.py
test/performance/rediSQL_bench.py
```

To fix this you could add a `.gitattibrutes` file and set this header as vendored (just like what is described in the [README](https://github.com/github/linguist)):

    sqlite3.h linguist-vendored

And yes, it's actually a C header, not Objective-C. This has been discussed before, I'm sure you will find references of other issues with a simple search. C and Objective-C headers (C++ as well) can be highly ambiguous.

As for the code not appearing when you filter the repo by language, I can't explain why. I'm guessing it won't show header files, but we need to wait for a specialist.

**Comment by siscia** [comment]
Thank you!!!

That really solved my problem.

I didn't think about using linguist to figure out what was wrong in the repo.

I leave it open since we haven't figured out why github didn't show the list of files.

Feel free to close the issues, though.

**Comment by lildude** [comment]
> I leave it open since we haven't figured out why github didn't show the list of files.

I can answer that. What's happening here is a little odd due to the way Linguist works versus how search works.

Linguist is detecting `sqlite3.h` as Objective-C and thanks to its size (480KB) is responsible for for it being marked as the predominant language. 

Search on the other hand is ignoring the file because of its size. [Files larger than 384KB are not indexed](https://help.github.com/articles/searching-code/#considerations-for-code-search) hence it doesn't show up in the search results.

This comes up a bit so I'm going to add it to the troubleshooting section in the README file.

**Comment by siscia** [comment]
Great! :+1: 
Do you need the issues to be open, or I can close it?

**Comment by lildude** [comment]
I think we've covered everything so I'm gonna close it.

**Comment by tessarin** [comment]
I'm happy that it worked for you @siscia! I think this issue can be closed.

Thanks @lildude for the enlightenment. I knew a specialist would know the precise reason. For me, the 384KB limit was something new. Back to reading docs 😬

Yes please do add to the README if possible. It would really benefit from the greater visibility.
