### ISSUE TITLE
Lightshow gives illusion of Unicode-aware regexes

### ISSUE THREAD

**Issue by Alhadis** [github/linguist#3884]
Compare the third line here...

~~~console
$ command # Command
  command # Output
λ command # Command
  command # Output
$ command # Command
~~~

... [with how Lightshow claims it'll look:](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=text.shell-session&grammar_url=&grammar_text=&code_source=from-text&code_url=&code=%24+command+%23+Command%0D%0A++command+%23+Output%0D%0A%CE%BB+command+%23+Command%0D%0A++command+%23+Output%0D%0A%24+command+%23+Command%0D%0A)

<img src="https://user-images.githubusercontent.com/2346707/32257233-f68f39e0-bf07-11e7-9688-282e2c18add9.png" width="168" alt="Figure 1" />

### Why this is happening

See [`atom/language-shellscript#85`](https://github.com/atom/language-shellscript/pull/85) for some backstory.

~~Basically, the grammar for highlighting snippets of terminal output (using `~~~console … ~~~`) was updated so Greek characters could be used as prompt-string symbols. My own `PS1` string uses a Lambda symbol, and I've seen many others use it too.~~

~~Only now I remembered GitHub parses text with Unicode features disabled for performance reasons. This comes from @vmg in [his explanation](https://github.com/github/linguist/issues/3291#issuecomment-255750842) in #3291:~~

> ~~… we don't currently use the `PCRE_UCP` flag because it's a really significant performance degradation. I acknowledge this is not an ideal answer -- I'm looking into the option to only enabling this flag on documents that we know contain extended Unicode characters, but we can't enable it by default because it really slows down syntax highlighting.~~

~~Lightshow should reflect this.~~

~~/cc @lildude @50Wliu~~

##  Why this is really happening. Nah, seriously.

**EDIT:** Because @Alhadis clearly can't wait longer than 30 minutes after a new Linguist release without expecting grammar updates to be visible.

**Comment by Alhadis** [comment]
Note to self: wait a minimum of 9 hours before filing a grammar-related issue after a new Linguist release.

![wat](https://user-images.githubusercontent.com/2346707/32274162-ae5de6f6-bf59-11e7-8f73-7b4ddde886a4.png)

**Comment by 50Wliu** [comment]
Haha I was confused as well :laughing:.  To join in the laughing party, I'll laugh at you in Chinese!

**Comment by lildude** [comment]
I'm actually 🇿🇦 but live in 🇬🇧 so you can have a 😂🇿🇦🤣🇬🇧😂🇿🇦😂🇬🇧

**Comment by Alhadis** [comment]
GitHub: Where borders come to die.
