### ISSUE TITLE
Oberon source files are erronously classified as Modula-2 and or Shell

### ISSUE THREAD

**Issue by btreut** [github/linguist#3888]
all Oberon source files are incorrectly classified as Modula-2, see for example Andreas' Pirklbauers repositories here: https://github.com/andreaspirklbauer

There are also other repositories where Oberon is misclassified as Shell: https://github.com/AlexIljin/OPCL

Admitted: Oberon is a language in the tradition of Pascal and Modula-2, but it is a different language, see: http://www.inr.ac.ru/~info21/pdf/Modula-Oberon-June-2007.pdf (or: https://dl.acm.org/citation.cfm?id=1238847&dl=ACM&coll=DL&CFID=825109146&CFTOKEN=75438417 and https://dl.acm.org/ft_gateway.cfm?id=1238847&type=ppt&path=%2F1240000%2F1238847%2Fsupp%2FModula%202%20Oberon%2Eppt&supp=1&dwn=1&CFID=825109146&CFTOKEN=75438417).

Currently I do not have enough understanding of linguist to add it myself, but I might offer help and more information, e.g. source code samples, language definition in EBNF, and/or a parser. 

regards
--
  Bernhard Treutwein

**Comment by pchaigno** [comment]
Please have a look at the [guidelines to add support for a new language to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). It Oberon meets the requirement on in-the-wild usage and you can provide the necessary information, I can open the pull request for you.

**Comment by btreut** [comment]
I had a look at the Guidelines **before** filing the issue. I think that Oberon meets the requirement on in-the-wild usage. 

What do you Need?

**Comment by pchaigno** [comment]
A color, a grammar, a link to a GitHub search result showing that it meets the requirement on in-the-wild usage, links to sample files with permissive licenses, the list of file extensions, etc.

**Comment by lildude** [comment]
If you’ve got the bandwidth, we’d happily accept a PR implementing this.

**Comment by btreut** [comment]
Sorrily I  have neither spare time to invest and additionally I the following has not changed at all (citing from my original post):

> Currently I do not have enough understanding of linguist to add it myself, but I might offer help and more information, e.g. source code samples, language definition in EBNF, and/or a parser.

**Comment by btreut** [comment]
> My offer still stands ...

oops, I provided links to grammars and appended an EBNF grammar on Nov.30, 2017.. 
Apparently you wanted something different, what should I provide?

**Comment by pchaigno** [comment]
The grammar can only be a TextMate, Sublime Text, or Atom grammar, and, as I wrote above, the search result link for in-the-wild usage is required (a short list of repositories won't do).

**Comment by pchaigno** [comment]
Flagging as stale.

**Comment by btreut** [comment]
This [search](https://github.com/search?utf8=%E2%9C%93&q=extension%3A%22Mod+Odc+ob%22+language%3AModula-2&type=Repositories&ref=advsearch&l=Modula-2&l=) results in 94 hits, where on the first two result pages with 20 hits only four repos are not containing Oberon sources ([gorilla-cpm](https://github.com/sblendorio/gorilla-cpm), [jpoial/forth](https://github.com/jpoial/forth), [sblendorio/mod-xterm-cpm](https://github.com/sblendorio/mod-xterm-cpm) and [OS2World/UTIL-DISK-Compress](https://github.com/OS2World/UTIL-DISK-Compress)).

**Comment by pchaigno** [comment]
Like [this search query example](https://github.com/search?p=1&q=extension%3Aodc+NOT+implementation+NOT+definition&type=Code), but for each extension. We'll then count the number of repositories in those search results with another tool. You'll want to use Oberon-specific keywords to limit the search results to Oberon files.

**Comment by pchaigno** [comment]
Without a way to distinguish the two languages, it's going to be very difficult to estimate their usage on GitHub.com or to classify `.mod` files... Until we have such a discriminator, I'd recommend we close this issue as, as far as I understand, the current miss-classification doesn't break syntax highlighting.

**Comment by btreut** [comment]
but it will appear that Modula-2 is still a living language, which I severely doubt. 

There is a lot of legacy Modula-2 software, which may be given a second life on github (see  e.g. [parts of OS2World](https://github.com/OS2World?utf8=%E2%9C%93&q=&type=&language=modula-2)), but I don't think there is any significant new development going on in Modula-2. I have no idea, how you could differntiate between legacy and currently used.

**Comment by btreut** [comment]
Paul Reed suggested on the Oberon mailing list to change the classification from Modula-2 to Modula-2/Oberon.

**Comment by btreut** [comment]
> Until we have such a discriminator

I think I've found two important discriminators between Modula-2 and Oberon, but I still have to think deeper how these can be formulated as regexes. 

I can tell these first two discriminators in plain words:

1. Any source file containing the key words DEFINITION or IMPLEMENTAION are definitely Modula-2 and not Oberon.

2. Every source file containing a construct RECORD (identifier) ... END  is definitely Oberon. 

of course there may be any number of white space (including comments of the form (* ... *) between RECORD and (id).

**Comment by pchaigno** [comment]
For the second one, what if the file only contains `RECORD identifier `? Would that be enough to identify it as Oberon?

**Comment by btreut** [comment]
This search definitely finds [Component Pascal](https://github.com/search?p=1&q=extension%3Aodc+NOT+implementation+NOT+definition&type=Code), yet another Oberon dialect. Most probably these files are classified as binaries, but this is a kind of rich text format as quite often used in the world of Oberon.

The next search also finds Oberon files: [Extension Ob2](https://github.com/search?p=1&q=extension%3AOb2+NOT+implementation+NOT+definition&type=Code)

**Comment by btreut** [comment]
> ... what if the file only contains RECORD identifier? Would that be enough to identify it as Oberon?

no, not at all. the construct RECORD ... END is legal Modula-2. 

The construct RECORD (father-record) ... END is the Oberon version of inheritance, which is not existing in Modula-2. 

These contructs are the equivalents to C structs and the Oberon form inherits all fields from its father.
