### ISSUE TITLE
Perl 5 and Perl 6 disambiguation rules are broken/inconsistent

### ISSUE THREAD

**Issue by zoffixznet** [github/linguist#3906]
The [.pl disambiguation](https://github.com/github/linguist/blob/71bf640a47e37bff3c616e84bf005728749f7035/lib/linguist/heuristics.rb#L359-L366) as well as [.pm disambiguation](https://github.com/github/linguist/blob/71bf640a47e37bff3c616e84bf005728749f7035/lib/linguist/heuristics.rb#L369-L377) and [.t disambiguation](https://github.com/github/linguist/blob/71bf640a47e37bff3c616e84bf005728749f7035/lib/linguist/heuristics.rb#L464-L467) should all use the same regexes for disambiguating between Perl 5 and Perl 6.

In addition, `use v6` in Perl 6 is just a general form; a more common form is likely the full language version, such as `use v6.c` or `use v6.d`. The `.pl` rule seems to allow for that, but `.t` and `.pm` expect a semicolon to follow the `6`.

**Comment by pchaigno** [comment]
Thanks for the report! We'd welcome a pull request with test cases.

**Comment by Alhadis** [comment]
Hi @zoffixznet, does #3880 help at all?

**Comment by zoffixznet** [comment]
> Hi @zoffixznet, does #3880 help at all?

Not the code, no. It'd still won't detect `use v6.c` as Perl 6 code. Also, the code doesn't fix similar issue in `.pm` disambiguation. Lastly, all of the versions could add an additional test to Perl 6 for `unit package`

**Comment by pchaigno** [comment]
Fixed by @Alhadis in #3880.
