### ISSUE TITLE
PostCSS

### ISSUE THREAD

**Issue by jhpratt** [github/linguist#3912]
Currently, PostCSS isn't supported. Though it's officially supposed to use the `.css` extension, `.pcss` is used by many (including myself).

**Comment by pchaigno** [comment]
Please have a look at the [guidelines to add support for a new language to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). It PostCSS meets the requirement on in-the-wild usage, we'd welcome a pull request!
