### ISSUE TITLE
Kotlin syntax highlighting in blue stops working when it hits a , character in the method name

### ISSUE THREAD

**Issue by JLLeitschuh** [github/linguist#3913]
Example:

```kotlin
@Test
fun `🦆 ~|~test with a really, (really) terrible name & that needs to be changed!~|~`() { }
                             ^
```
You can see that everything after the comma is no longer syntax highlighted.

This is a valid method name in Kotlin.

I discovered this problem as part of writing up this issue: https://github.com/junit-team/junit5/issues/1170

**Comment by pchaigno** [comment]
Linguist only selects the grammar to use for highlighting. For Kotlin, GitHub uses [vkostyukov/kotlin-sublime-package](https://github.com/vkostyukov/kotlin-sublime-package). You should open an issue there if there isn't already one.
