### ISSUE TITLE
Arduino is not a language

### ISSUE THREAD

**Issue by oldmud0** [github/linguist#3929]
The points of argumentation have already been made here: http://forum.arduino.cc/index.php?topic=413259.30

Simply put, Arduino ought to be be detected as C++, not as "Arduino." The .ino format is a wrapper used by the Arduino "IDE" to make some things simpler to make programs to be compiled to Arduino (such as adding in `#include <Arduino.h>` invisibly at the top of the source for you). But at the end of the day, the "IDE" simply invokes avr-g++ to do all of the compilation and avrdude to do the uploading.

This illusion of Arduino being classified as its own programming language should not be extended to Linguist, just as Qt's flavored C++ (with signals and slots) is not classified as "Qt."

**Comment by pchaigno** [comment]
Fair point. @oldmud0 Could you open a pull request to add `.ino` as a C++ extension and remove the Arduino entry?

**Comment by MarcianoPreciado** [comment]
Although Arduino definitely isn't it's own language I would argue that it should be kept in linguist. Without the Arduino identifier tag searching for smaller repositories written for Arduino would become more difficult. The sort-by-language function in the search page would no longer sort projects based on Arduino which I think is a pretty commonly used feature. I didn't really see this argument represented in the thread posted.

**Comment by lildude** [comment]
> Without the Arduino identifier tag searching for smaller repositories written for Arduino would become more difficult. The sort-by-language function in the search page would no longer sort projects based on Arduino which I think is a pretty commonly used feature.

@MarcianoPreciado That's where [Topics](https://help.github.com/articles/about-topics/) come to the rescue. This has the disadvantage that owners would need to add topics to their repos, but the problem you highlight is precisely what Topics is attempting to address.

**Comment by MarcianoPreciado** [comment]
@lildude Would it be possible to implement some sort of auto-topic addition feature? Perhaps based on  certain file types? Or maybe a small reminder/suggestion when a topic is applicable? I worry that the topic feature could slip under a lot of people's radar and become underused.

**Comment by lildude** [comment]
> @lildude Would it be possible to implement some sort of auto-topic addition feature?

GitHub automatically suggests topics for a repo. From the page I linked to:

> Additionally, GitHub analyzes public repository content and generates suggested topics that repository admins can accept or reject.

I doubt we'll go the route of automatically adding the topics, though you never know 😄.  Feel free to use the "Contact GitHub" link at the bottom of any GitHub.com page to contact our support peeps and offer up your suggestion if the auto-suggest isn't sufficient.

**Comment by lildude** [comment]
https://github.com/github/linguist/pull/3933 has 🚢 . Closing.
