### ISSUE TITLE
WeBWorK PG files not recognized

### ISSUE THREAD

**Issue by jirilebl** [github/linguist#3939]
For example the files in the Open Problem Library, https://github.com/openwebwork/webwork-open-problem-library

The extension is .pg, and the syntax is a combination of perl and tex

**Comment by lildude** [comment]
All your `.pg` files are being identified as Perl. The predominance of PostScript in your language stats bar is because of all the `.eps` and `.ps` files you have in the directories in https://github.com/openwebwork/webwork-open-problem-library/tree/master/Contrib/CAPA/CAPA_Graphics (~14.4MB in total).

As the parent directory is called Contrib it suggests to me that it contains third-party code you probably don't want it counted in you language stats so the best thing to do is implement a [override and mark this directory as vendored](https://github.com/github/linguist#vendored-code).

This will cause that entire directory to be ignored when calculating the language stats.

**Comment by jirilebl** [comment]
Hmmm, I think I was wrong, but I am still confused.  I realized that I can click on the language details to see which files are recongized as what.  But it seems the .pg files aren't recognized as anything.  I'll edit the title of the issue.  Under "Perl" I only find actual ".pl" files

**Comment by lildude** [comment]
Keep scrolling through the results; they're definitely classified as Perl as you can see at https://github.com/openwebwork/webwork-open-problem-library/search?l=perl&p=12

**Comment by jirilebl** [comment]
There are 50586 .pg files in the repository, that page only lists 187 files.  That's basically 99.7% of them aren't recognized.

**Comment by jirilebl** [comment]
If I am counting right, even by file size the .pg files should win by a longshot, there's 228megs of .pg files, there are only 20 megs of .eps files (817 files).

**Comment by lildude** [comment]
Ok, I see what's happening now. Those that are being recognised as Perl have a modeline in the file identifying them as Perl, eg https://github.com/openwebwork/webwork-open-problem-library/blob/0914437ac334603bf1f15257757073ac63121956/OpenProblemLibrary/Westmont/ActiveCalculus/Preview_5_2/preview_5_2_abcde.pg. Those that aren't recognised, don't, like https://github.com/openwebwork/webwork-open-problem-library/blob/master/OpenProblemLibrary/CollegeOfIdaho/setAlgebra_01_01_AlgebraicExpressions/11IntAlg_01_AlgebraicExpressions.pg

I've just double checked and the `.pg` extension isn't associated with any languages either.

The best thing to do is to add a [language override](https://github.com/github/linguist#using-gitattributes) for the `.pg` extension.

**Comment by jirilebl** [comment]
Well 1) that's why I'm reporting it, because there's quite a few PG files out there, not just in the open problem library.

2) I've been testing overrides on my own repository of webwork problems, and adding "*.pg linguist-language=WeBWorKPG" to .gitattributes doesn't seem to have any effect.  It seems to work to set it to show up as Perl but I don't think it would be correct to classify it as Perl, it really isn't normal Perl.  For example perl syntax highlighting, isn't totally correct.  PG files have a specific syntax, mix a-kind-of-LaTeX (that's where Perl syntax highlighting fails), and can't be run in anything other than webwork software.

**Comment by lildude** [comment]
> that's why I'm reporting it, because there's quite a few PG files out there, not just in the open problem library.

Ah, I thought you were reporting a problem and expecting them to be identified as Perl. As that's not the case and you wish to have support, please review the details in CONTRIBUTING.md and if WeBWorKPG meets all the requirements, we'd be pleased to get a PR for it. 

> I've been testing overrides on my own repository of webwork problems, and adding "*.pg linguist-language=WeBWorKPG" to .gitattributes doesn't seem to have any effect. It seems to work to set it to show up as Perl but I don't think it would be correct to classify it as Perl, it really isn't normal Perl. For example perl syntax highlighting, isn't totally correct. PG files have a specific syntax, mix a-kind-of-LaTeX (that's where Perl syntax highlighting fails), and can't be run in anything other than webwork software.

Yeah, the overrides can't be used to set a language Linguist doesn't know about.

**Comment by pchaigno** [comment]
Looks like the next step is to submit a pull request and use the Linguist overrides in the meantime. Closing.
