### ISSUE TITLE
Protocol Buffers files are incorrectly ignored

### ISSUE THREAD

**Issue by whymarrh** [github/linguist#3940]
The repository in question: [LakeMaps/schemas](https://github.com/LakeMaps/schemas) (as of LakeMaps/schemas@b1daa28ea0607580ef05ee839fa9211a292f9efe)

I've marked the script in the build directory and the index.js file in the root as vendored using the Git attrs file and now the repository has no language, missing the many Protocol Buffer files in the schemas directory. Removing the `linguist-vendored` lines from the root Git attrs file shows the repository as Shell with JavaScript (still missing the Protocol Buffer files).

I tried double-checking with the Ruby library (`github-linguist-5.3.2`) but that doesn't seem to work:

```ruby
require 'rugged'
require 'linguist'

repo = Rugged::Repository.new('.')
project = Linguist::Repository.new(repo, repo.head.target_id)
project.language # => nil
project.languages # => {}
```

What's even more weird is that I get the exact same result using the Ruby library after removing the Git attrs file (whereas GitHub shows two languages).

**Comment by whymarrh** [comment]
For the record I see the following on GitHub:

![screen shot 2017-12-07 at 12 24 06 am](https://user-images.githubusercontent.com/1623628/33698113-0140f13c-dae5-11e7-831b-eed813ae83f5.png)

**Comment by lildude** [comment]
Linguist considers Protocol Buffer files as data as you can see at https://github.com/github/linguist/blob/e7e64bf39abb90cce9df2f531873d316f5d6b18f/lib/linguist/languages.yml#L3516-L3516.

Data files are not considered when calculating the language stats hence they will not appear in the language stats bar. If you then mark the things that are counted as vendored, they too are ignored and you end up with no language bar. 

It is not currently possible to force data files to be counted in the language stats.

**Comment by whymarrh** [comment]
Oh. Is this new? The repository was previously showing Protocol Buffer as the language type.

[There seems to be a number of repositories still listed as Protocol Buffer](https://github.com/search?utf8=✓&q=language%3A%22Protocol+Buffer%22&type=Repositories) and it still shows up as an option in the language dropdown places:

![GitHub search for repositories written in Protocol Buffer](https://user-images.githubusercontent.com/1623628/33720100-7a3bd9fa-db3d-11e7-927f-7862c34407a4.png)

**Comment by whymarrh** [comment]
This looks to be from the 5.3.0 release (#3859) and #3751 more specifically, yeah?

**Comment by lildude** [comment]
> This looks to be from the 5.3.0 release (#3859) and #3751 more specifically, yeah?

Yup. 

> There seems to be a number of repositories still listed as Protocol Buffer and it still shows up as an option in the language dropdown places:

This is expected. Any repository that hasn't been updated since GitHub.com was updated to use 5.3.0 will still show the old behaviour and thus show "Protocol Buffer" in the language stats.

As for the search options and results: these are completely independent of Linguist. Search (and Linguist) will still recognise "Protocol Buffer" as a valid language and even highlight the code according to the syntax associated with the language, it just doesn't count towards the language statistics shown on the repo front page anymore.

**Comment by whymarrh** [comment]
I'm sad to see it go, but I understand. Thanks for the explanation!
