### ISSUE TITLE
wrongly syntax highlighting in Julia project

### ISSUE THREAD

**Issue by iblis17** [github/linguist#3950]
For example: https://github.com/dmlc/MXNet.jl/pull/373/files#diff-0ca423d226049cc5744ebade856d9f1b

This is a normal Julia code block, but the highlighting is weird.
![2017-12-14 2 26 35](https://user-images.githubusercontent.com/761623/33978425-a1b6873a-e0da-11e7-8b54-f4410831fabc.png)

**Comment by pchaigno** [comment]
The rest of the file looks okay, so I'd say it's an error with the grammar used for syntax highlighting. 
Linguist only selects the grammar to use for highlighting. For Julia, GitHub uses [JuliaEditorSupport/atom-language-julia](https://github.com/JuliaEditorSupport/atom-language-julia). You should open an issue there if there isn't already one.

**Comment by iblis17** [comment]
Thanks!
I filed it: https://github.com/JuliaEditorSupport/atom-language-julia/issues/134

**Comment by iblis17** [comment]
This issue has been fixed in latest release:
https://github.com/JuliaEditorSupport/atom-language-julia/releases/tag/v0.14.0

How to updating the dependency in this repo?

**Comment by lildude** [comment]
The updated grammar will be automatically pulled in when we next make a release which will be early next year.
