### ISSUE TITLE
Correct language statistics without .gitattributes

### ISSUE THREAD

**Issue by anselal** [github/linguist#3951]
Hi there,

I stumbled upon this project https://github.com/richardkiss/pycoin which has no .gitattributes file but the language statistics shows only python. How is he doing that ?

**Comment by pchaigno** [comment]
Hi,

What makes you think other languages should be displayed?

**Comment by anselal** [comment]
My bad, I thought files like *.bat are showing too as languages since they are scripts

**Comment by pchaigno** [comment]
They would, if they weren't in the `docs/` folder. For this reason, they're considered by Linguist as documentation and not included in the language statistics.

**Comment by anselal** [comment]
Thank you very much for the quick reply !!!
