### ISSUE TITLE
Addition: .sbc (in this case SpaceEngineers block/item/entity/etc definitions) as XML

### ISSUE THREAD

**Issue by ReikaKalseki** [github/linguist#3958]
The game SpaceEngineers uses the .sbc extension for its data files, which define basically any property of the game (blocks, items, sound lists, etc). These files are simple XML, but being not named .xml, are not recognized as such.

Here is an example: https://github.com/ReikaKalseki/DragonIndustries_ElectronicWarfare/blob/master/Data/CubeBlocks_EMP.sbc

I realize that the .sbc extension may not be unique, and if the system does not have language *recognition* capabilities from the text/source/etc directly, it might be desirable to allow the owner of the repository to specify "treat extension X as language Y".

**Comment by pchaigno** [comment]
Please have a look at the [guidelines to add support for a new extension to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language). In particular, notice the requirement on in-the-wild usage.

> it might be desirable to allow the owner of the repository to specify "treat extension X as language Y".

It should already be possible to mark `.sbc` files as XML with [Linguist overrides](https://github.com/github/linguist#overrides).
