### ISSUE TITLE
GPG detached sig as Standard ML

### ISSUE THREAD

**Issue by lucidBrot** [github/linguist#3959]
All my `something.sig` files that are detached signatures from gpg were detected as "Standard ML" language. Their content looks e.g. like this:

> -----BEGIN PGP SIGNATURE-----
> 
> iQIcBAABAgAGBQJZPaNNAAoJEDVK2YKhpOe5jfcP/RrkO1kDI7+EvNKGDW5+aO2G
> eIn5FtC/LmzU8usYIucT6Ka4X1vRrsr6RQrKgdnYq3kUn1D45sjdqr87dCpfiRku
> acvjJpZiZ2YbIzb+klCR3uC38DX/KsLAIUn39KwrwspHnH6mFGAzQw4WMabY7FOD
> vLEH7Ygpc41KEyPhjx3pLNXJX638ITK9/iFRv9TZkkmLzXBPWsJcr0IPkP/YUjYn
> 4eQ1HLwiwcLPdpzIXCNCP9RWKvK6b6aAx8GOlzGuhHuIdSi8/ev5URpmFL0qWV5p
> 8KYm+njFKBXIfHEXuT1ufQW2HAulpc0HA84u39X+tf4hp/HDuwWnWY82N1SIRk9k
> cPIGqm/CE8jVjnMDH9B/3qk+WZFNXGZorSI5kckQszWZmmjsnn3WYS+/MsrNlZVP
> C/m+W5zNQ8MosW2nXs774QungCr3yqN9yo/QRSNMhl2wBhOJpJYntWzVYwv3f36S
> aikTjNxbw0m613K8g8zQta8GVsHwmBp00uDA2eKdZ4nA1ZiC8ZqOIAUR5iTpDqV7
> 3IjHYYwZBY5VMcy5a1JDmDaQ+qhMVNETLaI/9ESz18yolgEHC7xptus4hfiIXoZd
> 2arVgT+dz8XhcTYC8T/hslIdzpD/Tk9bgJhQzdkvPV4eZggBjKZDM1XxO9qPXb/e
> +FMw6s22J8U3SaGAH8g2
> =ayaL
> -----END PGP SIGNATURE-----

**Comment by lildude** [comment]
This is because the `.sig` extension is associated with the  "Standard ML" and nothing else.  As GPG isn't an actual programming language, we can't add it to Linguist, so the only thing to do is implement a [manual override](https://github.com/github/linguist#using-gitattributes) to mark the files as text.

**Comment by pchaigno** [comment]
@lildude We do have a [Public Key](https://github.com/github/linguist/blob/d0b906f1289af4f2d9ee778348f61b3b7f472f81/lib/linguist/languages.yml#L3528) entry in `languages.yml`. Maybe we could/should extend it to include signatures? It looks straightforward to distinguish from Standard ML with a heuristic rule...

**Comment by lildude** [comment]
Oh yes. Good idea.

**Comment by pchaigno** [comment]
Not sure what the new name should be though...

**Comment by lucidBrot** [comment]
@lildude thanks for the link to the manual override, that worked!

About your naming issue, just my two cents: I think it would make sense to just name it signature or similar to that - after all, it's a `*.sig` file, so any kind of signature tool producing that would probably also call it a signature (else why name it .sig).

**Comment by pchaigno** [comment]
Sure, but my initial idea was to extend the Public Key entry with the `.sig` file extension. We might have to add a new entry if we can't think of a good way to name both public keys and signatures.

**Comment by lildude** [comment]
> Sure, but my initial idea was to extend the Public Key entry with the .sig file extension. We might have to add a new entry if we can't think of a good way to name both public keys and signatures.

I've been thinking about this one and off for a few months and I can't think of a name that I'm comfortable with that encompasses both signatures and keys and makes it clear the "language" contains both. I'd also rather not rename a language for something so small as it involves a pretty lengthy database migration (I got caught out by this when we renamed Perl6/Perl 6 😊).

Given GPG signatures are tied to keys, I'm inclined to add the extension to the current Public Keys language and we can deal with the pedants if and when they notice 😉
