### ISSUE TITLE
Github detects SourcePawn as PHP

### ISSUE THREAD

**Issue by NiketGandhir** [github/linguist#3961]
Not exactly sure why is this happening. 
I've had a few SourcePawn repos before and never faced this issue, not sure what is happening with this one. 

Anyway, this is the repo link - 
https://github.com/NiketGandhir/functions.inc

**Comment by pchaigno** [comment]
Linguist has the `.inc` file extension registered for both PHP and SourcePawn and sometimes gets it wrong. You can override the language for this file to SourcePawn with [Linguist overrides](https://github.com/github/linguist#overrides).
