### ISSUE TITLE
C++ files may take a .C extension.

### ISSUE THREAD

**Issue by 0mk** [github/linguist#3962]
In languages.yml,  please consider adding the line
 
\- ".C"                  

to the C++: extension list, since capital C is a valid C++ extension for the gnu compiler and its omission from the list is causing mis-classification of my repository.

Thank you

**Comment by adamyi** [comment]
See pchaigno's comment at https://github.com/github/linguist/pull/2930. Linguist treats extensions case-insensitively. I mentioned a solution at https://github.com/github/linguist/pull/3937 but haven't got a reply yet

**Comment by 0mk** [comment]
I managed to solve the problem by adding a .gitattributes file to my repository as suggested in the Overrides section of the README.md of github/linguist.
