### ISSUE TITLE
Need to change language of repo

### ISSUE THREAD

**Issue by lja672** [github/linguist#3963]
I have committed a Java Web project, but Githup detected it wrong as JavaScript. There exist JavaScript files within the repo , but JavaScript is definitely not the main language.

![image](https://user-images.githubusercontent.com/4653820/34454202-3951dd4c-eda1-11e7-83e0-3a298b873980.png)

Address: https://github.com/lja672/zuelbs

**Comment by lildude** [comment]
As detailed in the [README, Linguist uses the total bytes of code](https://github.com/github/linguist#how-linguist-works) to determine the language breakdown of a repo. In your case, you've clearly got more bytes of Javascript code than Java code.

A quick look at your repo shows the breakdown of:

JavaScript 1.57 MB
Java 390 KB
CSS 207 KB

... with most of that 1.57MB being attributed to https://github.com/lja672/zuelbs/blob/master/zuelbs/WebRoot/js/plugin/echarts.js which is 1.12MB.

If you don't want these files to count, you'll need to implement a [manual override](https://github.com/github/linguist#overrides) to ignore these files.

**Comment by lja672** [comment]
@lildude Thanks！
