### ISSUE TITLE
Markdown language is not detected

### ISSUE THREAD

**Issue by dialex** [github/linguist#3964]
Most of my repo is composed of Markdown (`.md`) files. However my repo does not display any language, as you can see at https://github.com/dialex/start-testing.

It should display 100% Markdown, or at least more than 90%.

**Comment by lildude** [comment]
This is correct and expected behaviour as documented in several places in the README:

> Linguist starts by going through all the files in a repository and excludes all files that it determines to be binary data, vendored code, generated code, documentation, or are defined as data (e.g. SQL) or prose (e.g. Markdown) languages, whilst taking into account any overrides.

Markdown isn't a programming language so it makes sense for it to be excluded from the stats. That said, you will be able to override this in future when https://github.com/github/linguist/pull/3807 is merged.

**Comment by 0xdevalias** [comment]
In case you end up here from google (like I just did), this article is a good overview of how to solve this: https://joshuatz.com/posts/2019/how-to-get-github-to-recognize-a-pure-markdown-repo/
