### ISSUE TITLE
github detects TS repo as CSS

### ISSUE THREAD

**Issue by MrFrankel** [github/linguist#3968]
https://github.com/MrFrankel/ngx-popper

Thanks

**Comment by lildude** [comment]
As detailed in the [README, Linguist uses the total bytes of code](https://github.com/github/linguist#how-linguist-works) to determine the language breakdown of a repo. In your case, you've clearly got more bytes of CSS code than TypeScript code.

A quick look at your repo show the breakdown of

CSS 132 KB
TypeScript 18 KB
HTML 5.16 KB
JavaScript 1.44 KB

... with all of the CSS being attributed to the only CSS file returned by the search results (obtained by clicking CSS in the language stats) https://github.com/MrFrankel/ngx-popper/search?l=css.

So the repo breakdown is correct. 

If you don't want CSS to be the primary language you'll need to reduce the amount of CSS, write more TypeScript 😉 or implement a [manual override](https://github.com/github/linguist#overrides) to ignore the file you don't want to count.

**Comment by MrFrankel** [comment]
@lildude thanks for the quick reply!!
