### ISSUE TITLE
Add GameMaker Studio 2 file types to Game Maker Language

### ISSUE THREAD

**Issue by YellowAfterlife** [github/linguist#3969]
Extensions: .yyp, .yy

Examples: [yyp](https://github.com/GameMakerDiscord/handytools/blob/master/handytools/handytools.yyp), [yy](https://github.com/GameMakerDiscord/handytools/blob/master/handytools/scripts/array_unpack/array_unpack.yy).

Currently [GameMaker Studio 2](https://www.yoyogames.com/gamemaker) files are mis-detected as Yacc due to using the .yy file extension.

GMS2 files always contain a JSON object as a top-level structure; object will always contain at least a few key-value pairs.

It doesn't seem like Yacc allows any statements starting with a curly bracket at the start of the file, but can match for a following double quote character (`^\{\s*"`) just to be sure.

**Comment by lildude** [comment]
If you’ve got the bandwidth, we’d happily accept a PR implementing this.

**Comment by pchaigno** [comment]
Flagging as stale.
