### ISSUE TITLE
github detects my CloudPi project as C but it is Java

### ISSUE THREAD

**Issue by suraj-ravishankar** [github/linguist#3971]

**Comment by lildude** [comment]
There's probably an easy explanation for this, however without knowing which repo it is, there's no way we can even attempt to guess or explain 😉 . At a guess, it's probably down to the file extensions, but we'd really need to see the repo to be sure.

Can you please let us know which repo you are seeing this on.

**Comment by lildude** [comment]
NM, found it by searching your profile: https://github.com/suraj-ravishankar/CloudPi/

Clicking the language bar and C shows these files: https://github.com/suraj-ravishankar/CloudPi/search?l=c and the sum of all the bytes of those four C files far outweighs the sum of all the Java files:

C 223 KB
Java 44.9 KB
Shell 4.4 KB
PHP 551 Bytes
Makefile 323 Bytes

... so the analysis is 100% correct.

As the README [states](https://github.com/github/linguist#how-linguist-works), we use the bytes of code to determine the repo breakdown.

To have your repo shown as Java you need to either more Java 😉 or use an [override to ignore the C files](https://github.com/github/linguist#overrides).
