### ISSUE TITLE
Repository marked with wrong language due to included library

### ISSUE THREAD

**Issue by D4RKS0UL23** [github/linguist#3975]
I created a repository for my C++ Project. In this project I used some libraries (SOIL and Freetype) that are written in C. Since the C-Files are no outnumbering my C++-Files, Github thinks it is a C Project.

Can I either change the language manually or hide certain folders from the language detection tool?

**Comment by lildude** [comment]
You can indeed ignore files or folders. The README.md file in this repo has everything you need to know. Mark the files/folders as vendored to not count but still appear in diffs, or mark as generated to be excluded from counts and diffs.
