### ISSUE TITLE
Perl 6 highlights broken in Markdown

### ISSUE THREAD

**Issue by zoffixznet** [github/linguist#3976]
Currently, if you try to use a code block in Markdown, while specifying `perl6` as highlight, you get no highlighting at all:

```perl6
my $rd := RDev.new: :$conf;
my %*SUB-MAIN-OPTS = :named-anywhere;
multi MAIN(Bool :$test) { $rd.re-make-rakudo: :$test }
```

This used to work just fine in the past, and I did a bit of digging and found it was likely broken in August 2017, when [`Fix spelling of Perl 6 #3672`](https://github.com/github/linguist/pull/3672) was merged to fix [`Rename Perl6 to Perl 6`](https://github.com/github/linguist/issues/3671).

[`Many Perl 6 repos no longer recognized #3763`](https://github.com/github/linguist/issues/3763) was opened around that time, and comments there suggest that due to the rename, the highlights in Markdown need to be requested by specifying `perl 6` (with a space in it):

    ```perl 6
       some code
    ```

If we try to do that, at first glance it will appear like highlights indeed start to work, *however* those highlights are for plain "Perl" language. This can be more clearly [seen in this gist](https://gist.github.com/zoffixznet/2faa177a2ea0745b54d8847d6f1f8294) where the first file is a Markdown document that uses `perl 6` code block and below are two code files: plain Perl (`.pl`) and Perl 6 (`.p6`). Looking at the differences, it's clear the Mardown is highlighted using Perl, not Perl 6 highlights.

So my question is, how to fix this? I can do the work, if someone can point me to what needs to be changed. 

Thanks.

**Comment by pchaigno** [comment]
Thanks for the report!

The new Markdown key for Perl 6 would be `perl-6`:
```perl-6
my $rd := RDev.new: :$conf;
my %*SUB-MAIN-OPTS = :named-anywhere;
multi MAIN(Bool :$test) { $rd.re-make-rakudo: :$test }
```

#3977 introduces `perl6` back as a Markdown key.
