### ISSUE TITLE
Wrong syntax coloring in shell scripts

### ISSUE THREAD

**Issue by yurivict** [github/linguist#3979]
Please observe how two items ">&2 ;" are colored red, instead of just the first one:
https://github.com/yurivict/freebsd-stats/blob/master/port-committer-productivity

Semicolon is a command separator, and shlouldn't be colored with ">&2".

Additionally, please consider differentiating the colors of ">" and "&2", since they are, again, different elements, but the coloring makes them look like they are one.

**Comment by pchaigno** [comment]
Linguist only selects the grammar to use for highlighting. For Shell scripts, GitHub uses [atom/language-shellscript](https://github.com/atom/language-shellscript). You should open an issue there if there isn't already one.
