### ISSUE TITLE
Can't set the language - Web Ontology Language

### ISSUE THREAD

**Issue by sichkar-valentyn** [github/linguist#3980]
The problem:
My repository isn't showing my language.
Played a lot, changed everything that is possible, but doesn't show any.

Files created in Protege and saved in all possible formats with it.

Also created .gitattributes file with following text inside:
$ cat .gitattributes
*.owl linguist-language=Web Ontology Language
Can't recognize, but if we put Java instead, it'll show the language.

Repository:
https://github.com/sichkar-valentyn/Knowledge_Base_Represented_by_Semantic_Web_Language

At the same time it's easy to find the repository just with a single .owl file and with the recognized language - Web Ontology Language, e.g. like this one: https://github.com/bahtyyarbabajanov/Green_Library_Ontology

What is the problem and how to set the language for the .owl files?

**Comment by lildude** [comment]
![](https://ci.memecdn.com/6335232.jpg)

😁 

GitHub.com currently had a momentary outage (see https://status.github.com/messages) so there's a bit of a backlog in jobs.

As the README states:

> ## How Linguist works on GitHub.com
>
> When you push changes to a repository on GitHub.com, a low priority background job is enqueued to analyze your repository as explained above. The results of this analysis are cached for the lifetime of your repository and are only updated when the repository is updated. As this analysis is performed by a low priority background job, it can take a while, particularly during busy periods, for your language statistics bar to reflect your changes.

You created the repo less than 15mins before you opened this issue. The repo you referenced as working was last updated 2 years ago 😄

Give it a few hours to catch up. I'll keep an eye out too and will close this issue when I notice the language stats have been updated, if you haven't closed it before me.

**Comment by lildude** [comment]
Oh yes, and you have an error in your .gitattributes file - you don't need the first line.

**Comment by pditommaso** [comment]
LOL

**Comment by sichkar-valentyn** [comment]
Yes, that's all true.

But, this repository I posted link about I created as new one.
I started to play yesterday and left it "to think" for more then 12 hours, after no result I deleted it.

As I mentioned, I tried a lot of changes, and also to change language to Java, and it shows Java language immediately. And that is strange.

**Comment by sichkar-valentyn** [comment]
The first from .gitattributes deleted now, but also tried it before.

Thanks for the information, let's wait a bit again.

**Comment by lildude** [comment]
Ah, I missed that. I've just checked the queues and they've recovered and your repo is still showing now language stats.

I've checked locally and I'm seeing the same problem.

Investigating...

**Comment by lildude** [comment]
Doh!!! Just spotted it. "Web Ontology Language" is considered "data" and not a programming language (as it's declared as XML and XML is considered data too):

https://github.com/github/linguist/blob/5fbe9c090254f75e01f035943044f027e4fd4f1c/lib/linguist/languages.yml#L4857-L4863

There is no way to override this yet.

The reason the older repo shows the language is because it was last updated prior to the changes introduced in https://github.com/github/linguist/pull/3751 which corrected the previous incorrect behaviour.

When https://github.com/github/linguist/pull/3807 has been merged and GitHub.com has been updated, you'll be able to force this to be counted in the stats again.

**Comment by sichkar-valentyn** [comment]
Thanks! Got it. So, we need just to wait, right?

**Comment by lildude** [comment]
Yup. I hope to have that PR included in our next release due sometime this month. There's no easy way to tell when it's live on GitHub.com, but you can check the Linguist version at the bottom of the page at https://github-lightshow.herokuapp.com/ as I update both at the same time.

Once that shows the new version, you just need to push a change to your repo (adding the new attribute for example) and it'll be reanalysed.

**Comment by sichkar-valentyn** [comment]
Thanks a lot!
