### ISSUE TITLE
Classify Cargo.lock as a generated file

### ISSUE THREAD

**Issue by ilianaw** [github/linguist#3988]
In binary Rust crates, the expectation is to commit your Cargo.lock file along with Cargo.toml and other files.

I've not seen a case where the Cargo.lock file is hand-generated, and it often comes first in a diff (Cargo.lock sorts before Cargo.toml sorts before src/main.rs).

**Comment by Loridawn99** [comment]
wallpaper/get_bingcom_wallpaper.py

**Comment by lildude** [comment]
If you’ve got the bandwidth, we’d happily accept a PR implementing this.

**Comment by pchaigno** [comment]
Flagging as stale.
