### ISSUE TITLE
for the wish list: log4j and log4j2

### ISSUE THREAD

**Issue by jottyfan** [github/linguist#3990]
Didn't find log4j or log4j2 in the list of possible code syntax languages. I'm not involved in development and cannot give you anything, but I think logfile results will be used in issues very often. Therefore, this extension would be very welcome.

**Comment by lildude** [comment]
Can you please elaborate further and provide an example of the types of file you're looking to be detected by Linguist.

AFAICT, log4j and and the newer log4j2 is logging API that was originally written in Java but usable and now implemented in other languages. Accordingly, the detection would be dependent on the implementation language and not log4j and log4j2 specifically.

If you're referring to the resulting log files, Linguist won't get support for log file highlighting as that's beyond the scope of the project.

**Comment by jottyfan** [comment]
here is an example: https://github.com/TheCoder4eu/BootsFaces-OSP/pull/903#issuecomment-358270196

Yes, indeed, I wanted to add chosen log messages from the log file. If this is out of your project's scope, that's bad, but I can understand that this might be too heavy to be solved.

**Comment by lildude** [comment]
Thanks for the explanation.

Yup, this is definitely beyond the scope of Linguist. Linguist detects programming languages and pulls in third party syntax highlighting grammars to do the highlighting of code files in repositories. Log files would also be considered data by Linguist so wouldn't be included in the repo stats.

The codeblocks like the one you've referenced are controlled by https://github.com/github/markup not Linguist, so if you want colourful logs in codeblocks, that would be the best place to log your request.

As this issue doesn't pertain to Linguist, I'm closing this issue.
