### ISSUE TITLE
C code marked as PHP

### ISSUE THREAD

**Issue by D1W0U** [github/linguist#3991]
This happened to me twice. First my project php-security is marked as PHP, when it's a PHP 7 extension coded in C, with a bit of PHP. And second my project ARPRootKit is marked as 75% PHP when there're only .c and .h files with full C.

## Preliminary Steps

I've implemented .gitattributes you can see in my project and it still doesn't detects well the language.

## Problem Description

Detects 75% of PHP code when they're full C.

### URL of the affected repository:

https://github.com/D1W0U/ARPRootKit

### Last modified on:
17-01-2018

### Expected language:
C 100% and ASM (will come in future)

### Detected language:
PHP 75% C 12% C++ 12%

**Comment by pchaigno** [comment]
Some of the `.inc` files in [this repository](https://github.com/D1W0U/ARPRootKit/tree/master/capstone/arch/X86) are recognized as PHP. You can change that with [Linguist overrides](https://github.com/github/linguist#overrides).

**Comment by D1W0U** [comment]
Cool, thanks!
I fixed it.
