### ISSUE TITLE
Repository is reported as 65% HTML with no HTML present

### ISSUE THREAD

**Issue by fuchstraumer** [github/linguist#3993]
## Problem Description

My repository "VulpesRender" is being reported as containing 65% HTML, despite not containing any HTML - on develop, at least. I missed a 5mb HTML file ([this one](https://github.com/fuchstraumer/VulpesRender/blob/master/ext/MoltenVK/Vulkan_1.0_Spec_with_MoltenVK_Extensions.html)) and removed it from the develop branch and waited a day or two to see if things updated. I had also tried to use .gitattributes overrides to fix this - but the code percentage still hasn't budged. Hopefully this isn't something incredibly simple, as I did try to fix it myself and read through the readme on this repo several times looking for more solutions.

This seemed to occur after I added a doxyfile, so not sure how that affects things.

### Last modified on:
2018-01-16

### Expected language:
C++ with a dash of C

### Detected language:
65% HTML, 27.5% C++, 7.0% C

**Comment by pchaigno** [comment]
> on develop, at least

Linguist only runs on the primary branch. If you make `develop` your primary branch, the language statistics should update with the next push.

**Comment by fuchstraumer** [comment]
And that did it, should have caught that earlier. Cheers!
