### ISSUE TITLE
No syntax highlighting for Elm

### ISSUE THREAD

**Issue by zwilias** [github/linguist#4006]
Since the release of Linguist 6.0.0, Elm files on GitHub no longer have syntax highlighting.

## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Elm files on GitHub (for example [this file](https://github.com/zwilias/json-decode-exploration/blob/master/src/Json/Decode/Exploration.elm), but this applies to every Elm file on GitHub) no longer have any syntax highlighting since earlier today.

Linguist uses `elm-community/Elm.tmLanguage` to provide a grammar for Elm. However, that repo was since renamed to `elm-community/SublimeElmLanguageSupport` and only provided `sublime-syntax` files going forward.

As a stopgap measure, we've reinstated the `elm-community/Elm.tmLanguage` repository with the `tmlanguage` files back in place. I'll try to PR a submodule update of the relevant submodule.

### URL of the affected repository:

Any GitHub repository containing Elm files

### Expected language:
Elm

**Comment by pchaigno** [comment]
> I'll try to PR a submodule update of the relevant submodule.

👍

**Comment by lildude** [comment]
Linguist v6.0.1 has now been deployed to GitHub.com and TypeScript syntax highlighting is working again, eg https://github.com/github/linguist/blob/master/samples/Elm/Basic.elm

**Comment by zwilias** [comment]
Thanks for getting this deployed! <3
