### ISSUE TITLE
Update GitHub.com's User Documentation

### ISSUE THREAD

**Issue by pchaigno** [github/linguist#4009]
The [current documentation for code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) is a bit misleading:
> We use Linguist to perform language detection and syntax highlighting.

Given the number of issues opened for highlighting bugs that usually don't belong here, I think it would be worth changing the wording to clarify that Linguist only takes care of language detection and point to the [list of grammars](https://github.com/github/linguist/blob/master/vendor/README.md) for syntax highlighting issues.

I'm opening the issue here instead of reporting to support@github.com directly so that we can discuss it if necessary.

/cc @lildude

**Comment by pchaigno** [comment]
What about this sentence instead?

> We use Linguist to perform language detection and a number of [third-party grammars](https://github.com/github/linguist/blob/master/vendor/README.md) for syntax highlighting.

@lildude Should I ping someone else inside GitHub regarding this (someone from the doc team maybe)?

**Comment by Alhadis** [comment]
Try this:

> We use Linguist to perform language detection and select [language grammars](https://github.com/github/linguist/blob/master/vendor/README.md) to provide syntax highlighting.

**Comment by Alhadis** [comment]
The "number of" part did sound a little awkward, yes. What about

> We use Linguist to perform language detect and to select [third-party grammars](https://github.com/github/linguist/blob/master/vendor/README.md) for syntax highlighting

Basically, I feel the "select" verb communicates Linguist's relationship to grammars a bit better.

**Comment by pchaigno** [comment]
Yep, that sounds fine!

As a side question: do you know why "a number of" sounds weird?

**Comment by Alhadis** [comment]
Not so much "weird", merely superfluous. =) It adds no new information for the reader.

Conciseness and clarity go hand-in-hand, I've learned.

**Comment by lildude** [comment]
> @lildude Should I ping someone else inside GitHub regarding this (someone from the doc team maybe)?

I can do it. Once we've finalised on the wording, I'll open the PR.

**Comment by pchaigno** [comment]
I think we're settled on:

> We use Linguist to perform language detection and to select [third-party grammars](https://github.com/github/linguist/blob/master/vendor/README.md) for syntax highlighting.

**Comment by lildude** [comment]
PR raised with the ☝️ wording.

**Comment by pchaigno** [comment]
Thanks @lildude, @Alhadis, and @emilyistoofunky!
