### ISSUE TITLE
Broken Vue syntax highlighting following recent update

### ISSUE THREAD

**Issue by lildude** [github/linguist#4011]
Opening this as a tracking issue so others know it's a known issue.

As part of the most recent update to Linguist deployed to GiHub.com, the latest commit of the Vue grammar was incorrectly pulled into the gem rather than that latest commit on the master branch.

This resulted in the syntax highlighting for Vue breaking as Vue has switched to using a SublimeText-based grammar by default, which Linguist and GitHub.com doesn't currently support.

The problem has happened because the submodule update I performed as part of the update didn't flip the submodule back to the master branch and thus didn't find the TextMate-based grammar.

I plan to release an update in the week commencing 29 Jan to address this.

**Comment by yyx990803** [comment]
See https://github.com/github/linguist/pull/4010 - this should be auto-fixed on next release

**Comment by lildude** [comment]
Linguist v6.0.1 has now been deployed to GitHub.com and Vue syntax highlighting is working again, eg https://github.com/github/linguist/blob/master/samples/Vue/basic.vue
