### ISSUE TITLE
c++ repository detected as makefile

### ISSUE THREAD

**Issue by uglyoldbob** [github/linguist#4020]
This is regarding my repository at
https://github.com/uglyoldbob/decompiler

Please confirm you have...

- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
_I'm not sure what I would override here, unless I can override the whole repository to c++_

- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Linguist sees only Makefile.am as a makefile source. This is accurate. It is 197 lines and 5.59 kB.
_This is somehow 59.5% of the project._

Looking at what is detected for c++:
_All of c++ somehow is only 28.5% of the project._
src/disassembly/disass_ppc.cpp shows up in the list for c++
It is 2133 lines and 79.9 kB. 

This one c++ file is definitely more than the one makefile file detected.

### URL of the affected repository:
https://github.com/uglyoldbob/decompiler

### Last modified on:
Jan 27, 2018

### Expected language:
C++

### Detected language:
Makefile

**Comment by lildude** [comment]
Your repo has Makefile as the predominant language thanks to https://github.com/uglyoldbob/decompiler/blob/master/Makefile.in - it's 390KB on its own with the total for Makefile being 396 KB.  On its own it accounts for more bytes of code than all your C++ files put together - they only total 190 KB, hence the classification.

If you don't want Makefile to be your predominant language, you'll need to mark this file as vendored or generated. As it's generated by automake, the latter is probably more apt.

**Comment by uglyoldbob** [comment]
Ah, Makefile.in was not being reported in the search. Knowing that makes perfect sense. I added the override and see the expected results.
Makefile.in does not show up in the search because it is larger than 384 kB.

**Comment by lildude** [comment]
> Makefile.in does not show up in the search because it is larger than 384 kB.

Yup, that's why we've had to add the "code search restrictions" part to the troubleshooting section of the README 😄.

As all is well now, I'm gonna close this.
