### ISSUE TITLE
SPARQL (.rq) files aren't detected

### ISSUE THREAD

**Issue by ivanhercaz** [github/linguist#4022]
Hi,
I have a repository in which I have [two SPARQL queries](https://github.com/ivanhercaz/CanaryBot/queries), but this files isn't being detected in the languages graph.

## Problem Description

It is strange because there is only one `sh` files and it is detected, but the two SPARQL files aren't detected. At the beginning I thought that maybe SPARQL wasn't admitted as language for the graph or it haven't been added, but I confirmed that it is well-configured checking [languages.yml](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml).

### URL of the affected repository:
[CanaryBot](https://github.com/ivanhercaz/CanaryBot)
### Last modified on:
2018-02-02

### Expected language:
SPARQL

### Detected language:
I don't know if it is being confusing with Python or with Shell, but I think the main problem is that it isn't being detected.

Thanks in advance!
Iván

**Comment by lildude** [comment]
It expected that for your SPARQL files to be counted in the language stats as SPARQL is considered a data language and not a programming language by Linguist:

https://github.com/github/linguist/blob/812797b51da51356deeacfbe18b5a5990246918d/lib/linguist/languages.yml#L4076-L4077

... and Linguist doesn't include data languages in the stats by default.

You can however now change that by using the [`linguist-detectable`](https://github.com/github/linguist/blob/master/README.md#detectable) override.

**Comment by ivanhercaz** [comment]
Oh, thank very much @lildude :), for the information and for the help to make it detectable.

I am going to close this issue because you have explained me why it happens with this kind of languages and how it can be "solved" if I want to make it detectable.

Regards,
Iván
