### ISSUE TITLE
C Header miscategorized as Objective C file

### ISSUE THREAD

**Issue by jweinst1** [github/linguist#4024]
A C-library that is header only is being classified as objective C. 

## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

The [header file](https://github.com/jweinst1/DataBlock/blob/master/src/DataBlock.h) of the repo is being mis-categorized as an Objective C file, according to the language stats.

https://github.com/jweinst1/DataBlock/search?l=objective-c

This seems like an error, since it's not an Objective C file

### Last modified on:
 2018-02-06

### Expected language:
C

### Detected language:
Objective C

**Comment by pchaigno** [comment]
Any reason why the [Overrides](https://github.com/github/linguist#overrides) would not work in this case?

**Comment by jweinst1** [comment]
@pchaigno It could work, but there appears to be a bug where it's falsely categorizing things in comments as actual language syntax, or it's not picking up things like `#include <stdio.h>`. In  #1626 , it discusses certain syntaxes like picking up standard library includes.

Is there a reason why it classifies it as Objective-C?

**Comment by jweinst1** [comment]
I added an override, but I was wondering just where in the repo is the objective C or C regexes? Curious if I could see how to fix this or contribute a pr.

**Comment by pchaigno** [comment]
We already have [a few heuristic rules for `.h`](https://github.com/github/linguist/blob/812797b51da51356deeacfbe18b5a5990246918d/lib/linguist/heuristics.rb#L233-L239). Unfortunately, this is one of those extensions that are difficult to classify correctly. For extensions used by several languages, Linguist will never have a perfect accuracy. Hence, the overrides :-)

If you have new ideas to contribute to #1626, please go ahead.

**Comment by jweinst1** [comment]
@pchaigno will do, but question, I notice in the heuristics file there is no rule for a .c file? I just see a C++ regex.

Right now, how are C files selected or detected?

**Comment by pchaigno** [comment]
We have a Bayesian classifier after the heuristic rules. I wrote [an answer on SO detailing how Linguist works](https://stackoverflow.com/a/45781398/6884590) a few months back if you want more details.

**Comment by jweinst1** [comment]
Thanks! Ill have a look!
