### ISSUE TITLE
Why some "programming" languages don't have colors?

### ISSUE THREAD

**Issue by IonicaBizau** [github/linguist#4041]
> `# color             - CSS hex color to represent the language. Only used if type is "programming" or "prose".`

https://github.com/github/linguist/blob/052c048fb5095e76b88c04d8e09a51962a048076/lib/linguist/languages.yml#L20

---

Why some languages do not have the `color` property (e.g. `CMake` or `COBOL`)?

https://github.com/github/linguist/blob/052c048fb5095e76b88c04d8e09a51962a048076/lib/linguist/languages.yml#L554-L564

**Comment by pchaigno** [comment]
Some programming languages don't have a color because they're part of a group, in which case they will always be presented under their parent language and don't need a color.

There are also languages that do not have a color because nobody assigned one, as it appears to be the case for CMake.

**Comment by IonicaBizau** [comment]
@pchaigno Is that the reason why `CMake` appears in a gray-ish color? 

Thanks!

**Comment by pchaigno** [comment]
Yes, the default color is gray.

**Comment by IonicaBizau** [comment]
Thanks for quick feedback! :apple:

**Comment by pchaigno** [comment]
You're welcome!
