### ISSUE TITLE
Matlab repo with two mex files classified as c++

### ISSUE THREAD

**Issue by joakimlindblad** [github/linguist#4043]
### URL of the affected repository:
https://github.com/joakimlindblad/FuzzConn

### Expected language:
Matlab

### Detected language:
C++

**Comment by Alhadis** [comment]
Linguist is getting confused by [these two files](https://github.com/joakimlindblad/FuzzConn/search?l=c%2B%2B), which use the `.cc` file extension (which is common to C++ files). You can either [override them](https://github.com/github/linguist#my-repository-is-detected-as-the-wrong-language) using a `.gitattributes` file, or (as would be my approach), add an Emacs or Vim modeline to the top line to indicate the file is MATLAB:

~~~MATLAB
% -*- mode: octave -*- vim:ft=matlab
~~~

Not only will that fix the file's misclassification on GitHub, but it'll keep other people who open your file in their editor from seeing incorrectly highlighted syntax. :wink:
