### ISSUE TITLE
Github listing as JavaScript when it should be c#

### ISSUE THREAD

**Issue by asudbury** [github/linguist#4046]
Hi,

The programming language listed for the repo below says JavaScript but its actually C# - can this be changed please?

https://github.com/asudbury/spectrum

thanks

adrian.

**Comment by Alhadis** [comment]
When you filed this, there should have been a list of steps to help you resolve this issue yourself.

What happened to them?

**Comment by asudbury** [comment]
i read those articles - didn't make a lot of sense!

its not that important - please close this issue if it cant easily be resolved.

I love github and im not trying to be awkward!

thanks

adrian.

**Comment by pchaigno** [comment]
> i read those articles - didn't make a lot of sense!

Could you detail what you think doesn't make much sense? That would help us improve our templates and guidelines for future contributors.

Now, given your issue, I'd recommend reading [*My repository is detected as the wrong language*](https://github.com/github/linguist#my-repository-is-detected-as-the-wrong-language) in the README.

**Comment by asudbury** [comment]
Hi,

First of all i didn't know what the 'language stats bar' was! i do know after googling it :-)

I think if you had included some sort of graphic it in the article to explain where to find it - it might be obvious to you, it might be obvious to a lot of people but it wasn't to me.

Following the article you provided a link for - it mentions moving files to a vendor - i cant do that. 

I had assumed it would be a github setting to override the language - i know now that not the case.

You can close this issue.

thanks

adrian.

**Comment by pchaigno** [comment]
Thanks for the suggestion. I'll look into it!

> If you see files that you didn't write in the search results, consider moving the files into one of the [paths for vendored code](/lib/linguist/vendor.yml), or use the [manual overrides](#overrides) feature to ignore them.

You might want to pay closer attention to the third phrase of this sentence ;)
You do have more option than moving files to a vendor directory: https://github.com/github/linguist#overrides.
