### ISSUE TITLE
Wrong Language

### ISSUE THREAD

**Issue by Priyanka1527** [github/linguist#4047]
Hi,
My Repository Search_Engine is saying HTML while the files I've uploaded are written in Python. Please help make it correct.

**Comment by Alhadis** [comment]
👋 Hi @Priyanka1527,

Your repository contains [47 HTML files](https://github.com/Priyanka1527/Search_Engine/search?l=html), and only [2 small Python scripts](https://github.com/Priyanka1527/Search_Engine/search?l=Python).

You can exclude the HTML files from your repository's language statistics by [using an override](https://github.com/github/linguist/#using-gitattributes):

~~~
*.html linguist-generated=true
~~~
