### ISSUE TITLE
wrong language detected

### ISSUE THREAD

**Issue by miketsivinsky** [github/linguist#4060]
## Problem Description

I have a little test project for build C/C++ using make.
Some file language are detected correct, but all headers are detected as 'ObjectiveC' (incorrect)

### URL of the affected repository:
https://github.com/miketsivinsky/make_probe

### Expected language:
C, C++ in my project there are no difference (C or C++) for these headers

### Detected language:
ObjectiveC

**Comment by lildude** [comment]
This is a known limitation with the current method used to detect the language of the C-family header files. https://github.com/github/linguist/pull/4025 will hopefully improve things.

In the mean time, the only option is to implement an [override](https://github.com/github/linguist#using-gitattributes) to force the correct language.

**Comment by miketsivinsky** [comment]
OK, thank you.
