### ISSUE TITLE
Manual overrides doesn't work

### ISSUE THREAD

**Issue by miketsivinsky** [github/linguist#4061]
## Problem Description

I have a problem with C/C++ headers which detected as written at Objective-C (wrong)
As you recommend I add .gitattributes file with manual override:

_*.h linguist-language=C++_

**But this solution does not work:**
1. The *.h files are marked as "Objective-C"
2. Repository marked as "makefile" but really there is only one makefile and a lot of C/C++ sources and headers

**My questions:**
1.What I do wrong?

2. Can I manually set my own "name" for rep language - say "foo-bar" - in some case I don't need complex language recognition engine and manual setup is better solution for me

### URL of the affected repository:
https://github.com/miketsivinsky/make_probe

### Expected language:
C/C++

### Detected language:
makefile and Objective-C

**Comment by lildude** [comment]
Hmmm, it looks good to me:

![screen shot 2018-03-06 at 09 59 47](https://user-images.githubusercontent.com/627280/37026048-2d398746-2125-11e8-8d6f-22cf5a6e4915.png)

> The *.h files are marked as "Objective-C"

Not anymore. I see no mention of Objective-C at all.

> Repository marked as "makefile" but really there is only one makefile and a lot of C/C++ sources and headers

Remember from the README, Linguist calculates the language percentage by bytes of code... your makefile is by far the biggest file in your repo at 2.04 KB on its own. All your C++ files added together only amount to 1.11 KB

> 1.What I do wrong?

Nothing.

> Can I manually set my own "name" for rep language - say "foo-bar" - in some case I don't need complex language recognition engine and manual setup is better solution for me

Nope. GitHub doesn't offer the ability to explicitly set a repo language as there is no such concept. To GitHub the concept is "this repo is primarily made up of language X".

The closest you can get is to use an override to mark your makefile as C++, documentation, vendored, or generated. The first will make it count towards the stats, whilst the others will exclude it from the stats calculations.

**Comment by pchaigno** [comment]
> Not anymore. I see no mention of Objective-C at all.

@lildude The [search results](https://github.com/miketsivinsky/make_probe/search?l=Objective-C) didn't update though.

**Comment by miketsivinsky** [comment]
1)

The *.h files are marked as Objective-C 

https://github.com/miketsivinsky/make_probe/search?l=Objective-C  


https://screenshots.firefox.com/pkDtKhF7M6dk9FwC/github.com  


2)

Thanks for info about other quetions.

Mike

**Comment by lildude** [comment]
> @lildude The search results didn't update though.

Hmmm, well that's technically not Linguist at play, but rather search... search and Linguist are separate components.

I've just kicked off a reindex and that doesn't appear to have helped. It appears the search is indexing based on your develop branch when it should be indexing on your default branch.  You may be able to confirm this by adding the same .gitattributes to this branch and see if it makes any difference.

The search side of things isn't really my forte so the only suggestion I can make is to contact our support team using the "Contact GitHub" link at the bottom of the page.

**Comment by miketsivinsky** [comment]
OK, thanks.
