### ISSUE TITLE
[PHP] Folded comments do not highlight annotations

### ISSUE THREAD

**Issue by carusogabriel** [github/linguist#4064]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [ ] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
Hi. I don't know if this repo is the correct one to report this, but if it is, here we go: folded comment in PHP `/** */` does not highlight annotations. Example: https://github.com/doctrine/mongodb-odm/pull/1750/files

### Last modified on:
2018-03-12

### Expected language:
PHP

### Detected language:
PHP

**Comment by pchaigno** [comment]
From the Troubleshooting docs:

> ### There's a problem with the syntax highlighting of a file
> Linguist detects the language of a file but the actual syntax-highlighting is powered by a set of language grammars which are included in this project as a set of submodules [as listed here](https://github.com/github/linguist/blob/master/vendor/README.md).
> If you experience an issue with the syntax-highlighting on GitHub, **please report the issue to the upstream grammar repository, not here.** Grammars are updated every time we build the Linguist gem so upstream bug fixes are automatically incorporated as they are fixed.
