### ISSUE TITLE
Language wrongly identified in my two repositories

### ISSUE THREAD

**Issue by aysunakarsu** [github/linguist#4074]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

### URL of the affected repository:
https://github.com/aysunakarsu/is-my-site-in-googles-mobile-first-index
### Last modified on:

2018-03-25

### Expected language:

Bash shell script

### Detected language:

 OpenEdge ABL

**Comment by pchaigno** [comment]
[This file](https://github.com/aysunakarsu/is-my-site-in-googles-mobile-first-index/blob/48892b46aadbe1855ba0b2bb322e0979abf61171/is_my_site_in_googles_mobile_first_index.p) is recognized as OpenEdge ABL because of its file extension. Is that a Bash script?

**Comment by aysunakarsu** [comment]
Yes, it is a bash script.
Thanks

2018-03-25 18:56 GMT+02:00 Paul Chaignon <notifications@github.com>:

**Comment by pchaigno** [comment]
Then, as indicated [in the Troubleshooting guide](https://github.com/github/linguist#my-repository-is-detected-as-the-wrong-language) and detailed [in the overrides instructions](https://github.com/github/linguist#overrides), you can either tell Linguist to ignore this file from statistics or force it to be recognized as Bash.
