### ISSUE TITLE
Language wrongly identified 

### ISSUE THREAD

**Issue by aysunakarsu** [github/linguist#4075]
## Preliminary Steps

Please confirm you have...
- [ ] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [ ] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [ ] considered implementing an [override](https://github.com/github/linguist#overrides),
- [ ] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

### URL of the affected repository:
https://github.com/aysunakarsu/googlebot_crawled_urls_per_status_code
### Last modified on:

2018-03-25
### Expected language:

Bash shell script
### Detected language:

C++

**Comment by pchaigno** [comment]
[This file](https://github.com/aysunakarsu/googlebot_crawled_urls_per_status_code/blob/51458257943d8fc2e2861d602542c7fa1eac7544/googlebot_crawled_urls_per_status_code.h) is detected as C++ because of its extension. Is that a Bash script?

**Comment by aysunakarsu** [comment]
yes it is a bash script.
thanks

2018-03-25 18:57 GMT+02:00 Paul Chaignon <notifications@github.com>:

**Comment by pchaigno** [comment]
Then, as indicated [in the Troubleshooting guide](https://github.com/github/linguist#my-repository-is-detected-as-the-wrong-language) and detailed [in the overrides instructions](https://github.com/github/linguist#overrides), you can either tell Linguist to ignore this file from statistics or force it to be recognized as Bash.
