### ISSUE TITLE
Repo language misclassified

### ISSUE THREAD

**Issue by Meteorix** [github/linguist#4076]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

### URL of the affected repository:
https://github.com/AirtestProject/Airtest
### Last modified on:

2018-03-22
### Expected language:

python
### Detected language:

html

**Comment by lildude** [comment]
HTML is being identified as the primary language of your repo because of the heeeeeaaawg file at https://github.com/AirtestProject/Airtest/blob/master/playground/test_blackjack.air/test_blackjack.html - it's 495 KB on its own, which is more than all your Python code put together (263 KB).

As the file is over 384 KB in size, it is also excluded from the search results, hence you don't see it when clicking HTML in the language bar.

You will need to implement a manual override to ignore this file or containing directory to remove it from the stats.

**Comment by Meteorix** [comment]
@lildude Thanks! You saved my day. I have been stuck in this issue for days.

**Comment by Alhadis** [comment]
@Meteorix Are the troubleshooting docs unclear? I see you added a `.gitattributes` file a few days ago, but the cause of the misidentification is (quite literally) explained in the [first paragraph](https://github.com/github/linguist#troubleshooting)...

> If the language stats bar is reporting a language that you don't expect:
>
> 1. Click on the name of the language in the stats bar to see a list of the files that are identified as that language.

**Comment by Meteorix** [comment]
@Alhadis  as @lildude explained, I can't see that file after clicking the stats bar.
> As the file is over 384 KB in size, it is also excluded from the search results, hence you don't see it when clicking HTML in the language bar.

**Comment by Alhadis** [comment]
Yes, but there's a link to the [code-search restrictions](https://help.github.com/articles/searching-code/#considerations-for-code-search). :)

Although the filesize limit is a common gotcha. @lildude, should we mention that in the docs?

**Comment by Meteorix** [comment]
Actually, I remember that I have read that line, but was not able to locate the problem. 
Maybe because file size is not displayed on github. And also I failed to install linguist on my mac  :(

**Comment by lildude** [comment]
> Although the filesize limit is a common gotcha. @lildude, should we mention that in the docs?

Yeah, I'm starting to think it's worth calling this out explicitly as it is almost always the cause outside of actual misidentification.
