### ISSUE TITLE
Perl 5 vs Perl 6 mis-detection

### ISSUE THREAD

**Issue by zoffixznet** [github/linguist#4090]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Perl 5 and Perl 6 are different languages (despite similar names; like C vs C++). However, the heuristic fails in some cases. This was previously opened in https://github.com/github/linguist/issues/3906 and the cases covered in that issue were resolved.

### URL of the affected repository:

https://github.com/zoffixznet/Music-ScaleNote

As far as I can see, the heuristic is failing because the heuristic looks for `use strict`, but the module uses `use strictures` instead.

### Last modified on:
No idea

### Expected language:
Perl 5 (aka "Perl")

### Detected language:
Perl 6

### Details

Since the previous times we had ambiguity issues, the Perl 6 language has now decided [more strongly](https://github.com/perl6/doc/commit/483b883c7e1bd7608489cf3dfa81588e09e1bbe2) that its extensions are `.pm6` for modules, `.p6` for files and `.t` for scripts.

Thus, I'd argue that the [heuristic for `.pm` and `.pl` files](https://github.com/github/linguist/blob/f4526126661d6f6ea15c967144454b088d7cd96f/lib/linguist/heuristics.rb#L363-L381) should prefer Perl 5 much more strongly. Likely just checking for Perl 6 first, with `use\s+v6\b` only, not the current regex, and marking code as Perl 6 if detected, otherwise, going to Perl 5. (personally, I'd say it shouldn't be disambiguated with Perl 6 at all and just assume those extensions are always Perl 5 or other lang). 

That leaves `.t` disambiguation. I'm less certain of this one, but just thinking that it can be improved if Perl 6 is tested first and checked against `use\s+v6\b`, along with some testing subs that have a dash in their names `done-testing|is-deeply|isa-ok|throws-like`. If that doesn't match, then assume the code's Perl 5 or other lang.

If someone submits a PR, is there a way to somehow preview that the changes give right results? Is [installing Linguist locally sufficient](https://github.com/github/linguist#usage)?

**Comment by pchaigno** [comment]
> As far as I can see, the heuristic is failing because the heuristic looks for `use strict`, but the module uses `use strictures` instead.

Could we add `use strictures` to the Perl 5 heuristic rule then?

We should also be able to use the shebang in [the `.t` file](https://github.com/zoffixznet/Music-ScaleNote/blob/master/t/01-methods.t). I'll look into it.

> If someone submits a PR, is there a way to somehow preview that the changes give right results? Is installing Linguist locally sufficient?

Yes, it's sufficient to test detection.

**Comment by pchaigno** [comment]
> This is a losing battle - here's the most comprehensive list I know of for modules that import strict and warnings for you, and this isn't including opinionated ones that only use part of strict: https://metacpan.org/source/PETDANCE/Perl-Critic-1.130/lib/Perl/Critic/Utils/Constants.pm#L84-126

Heuristic rules were never meant to catch 100% cases (I guess it's in the name...). I'm only asking here if adding `use strictures` would help us catch a greater number of Perl 5 files, or is it only used in rare cases? (i.e., is it worth it?)

> There is no requirement for perl test files to contain a shebang, since they are normally executed via a makefile or prove.

The Shebang strategy is also a heuristic, so same as above.

> Note #!perl as in that file isn't even a valid shebang, it's just a convention.

Sure, but it's a convention [we should recognize](https://github.com/github/linguist/blob/f4526126661d6f6ea15c967144454b088d7cd96f/lib/linguist/shebang.rb#L49-L50).

**Comment by pchaigno** [comment]
As far as I can see (with GitHub.com's search engine), we still have quite a few [`.pl`](https://github.com/search?p=1&q=extension%3Apl+%22use+v6%22&type=Code&utf8=%E2%9C%93) and [`.pm`](https://github.com/search?p=1&q=extension%3Apm+%22use+v6%22&type=Code&utf8=%E2%9C%93) Perl 6 files. Of course, these search use the `use v6` statement, so we can use our current heuristic rule to detect those files. But the point is that many still use `.pl` and `.pm`, and I doubt all of them have `use v6` at the top. In any case, we try to avoid these kinds of fallback `else` in heuristic rules.

For now, I think we can address this by both improving the heuristic rule for Perl 5 and fixing the issue with the shebang. If you have other cases of misclassifications I can look into them, but it's unlikely will be able to detect them all accurately (that's what [Linguist overrides](https://github.com/github/linguist#overrides) are for). If/When the number of `.pl` and `.pm` Perl 6 files gets low enough, we'll change the heuristic rule or even remove those extensions for Perl 6.

**Comment by Grinnz** [comment]
I would still ask why it should mark a file as Perl 6 when it can't disambiguate between them. Perl 5 usage is far more widespread and as noted will be the only use of these extensions going forward, so it's a more sensible default.

**Comment by pchaigno** [comment]
> I would still ask why it should mark a file as Perl 6 when it can't disambiguate between them.

Because the Heuristic strategy is [not the last strategy](https://github.com/github/linguist/blob/f4526126661d6f6ea15c967144454b088d7cd96f/lib/linguist.rb#L65-L66). It's actually the naive Bayesian classifier that runs last and misclassifies your files here.

**Comment by pchaigno** [comment]
#4099 was just merged, so this issue should be fixed with the next release of Linguist. There's usually a new release every couple weeks.
