### ISSUE TITLE
Release date for v6.0.2?

### ISSUE THREAD

**Issue by stringfellow** [github/linguist#4104]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

There are a fair few commits in master since the last release, including some syntax highlighting which would be really good to have available on GitHub, so I was wondering what the process was to get a release out and then have that included in the latest GH release?

**Comment by lildude** [comment]
I'm aiming for some time this week. I wanted to do it last week but didn't get the chance.

**Comment by worldbeater** [comment]
Please, consider also updating a reference to the latest https://github.com/atom/language-csharp grammar if you have any time! We've just finished working there on a new grammar providing first-class syntax highlighting for C# language on GitHub and in Atom (it uses Microsoft's grammar now, ported to support PCRE). 

See it in action:
- [Before](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fatom%2Flanguage-csharp%2Fcc00335ae822a69e19ae6fe4ad74bfb3c53c9a30%2Fgrammars%2Fc%2523.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgist.githubusercontent.com%2Fworldbeater%2Fc7cb51a1f6b07d5b8a46d3df5983d047%2Fraw%2F918acf82490816ea8d9a36f0bb9dccee8c2e6c97%2FFeedbackFormViewModel.cs&code=) vs [After](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fworldbeater%2Flanguage-csharp%2Faf991b07b724c7f42a4fde9800143d31fb68c7fc%2Fgrammars%2Fcsharp.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgist.githubusercontent.com%2Fworldbeater%2Fc7cb51a1f6b07d5b8a46d3df5983d047%2Fraw%2F918acf82490816ea8d9a36f0bb9dccee8c2e6c97%2FFeedbackFormViewModel.cs&code=)
- [Before](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fatom%2Flanguage-csharp%2Fcc00335ae822a69e19ae6fe4ad74bfb3c53c9a30%2Fgrammars%2Fc%2523.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fworldbeater%2FmyFeed%2Fmaster%2FmyFeed%2FViewModels%2FSearchViewModel.cs&code=) vs [After](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fworldbeater%2Flanguage-csharp%2Faf991b07b724c7f42a4fde9800143d31fb68c7fc%2Fgrammars%2Fcsharp.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fworldbeater%2FmyFeed%2Fmaster%2FmyFeed%2FViewModels%2FSearchViewModel.cs&code=)
- [Before](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fatom%2Flanguage-csharp%2Fcc00335ae822a69e19ae6fe4ad74bfb3c53c9a30%2Fgrammars%2Fc%2523.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fworldbeater%2FmyFeed%2Fblob%2Fmaster%2FmyFeed%2FServices%2FBackgroundService.cs&code=) vs [After](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fworldbeater%2Flanguage-csharp%2Faf991b07b724c7f42a4fde9800143d31fb68c7fc%2Fgrammars%2Fcsharp.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fworldbeater%2FmyFeed%2Fblob%2Fmaster%2FmyFeed%2FServices%2FBackgroundService.cs&code=)

Thanks in advance and keep up your great work!

**Comment by lildude** [comment]
I’ll perform a grammar update too so all grammars will be updated to their latest versions at the same time.

@damieng does ☝️ include the changes you mentioned earlier when you said you’d found a way to use the same grammar for GitHub and Atom?

**Comment by damieng** [comment]
@worldbeater produced a script that fixed up the grammar so it works in both and is fully merged into language-csharp.

I've done some preliminary testing and I am seeing some odd issues I'd like to investigate where lightshow is highlighting using keywords instead of entity names.  I'll be able to spend some time checking this out this evening if that works with your timeline.

**Comment by lildude** [comment]
Yup, good for me. We've got a few other PRs I'd like to try sneak in before
I cut a new release so it may be late tomorrow or early Thursday before I
cut the release.

**Comment by damieng** [comment]
I just published 1.0.2 which solves those problems and now looks great. The only 'missing' feature is colorization of string interpolation which works in Atom but not in Linguist.  Is there anything I need to do to make that happen?

**Comment by Alhadis** [comment]
@damieng I checked out `atom/language-csharp` locally and dev-linked it to `~/.atom/dev/packages`, but I'm actually not seeing anything in Atom:

<img width="387" alt="screen shot 2018-04-18 at 8 32 30 pm" src="https://user-images.githubusercontent.com/2346707/38926959-a9084dc8-4347-11e8-9272-35db30d5eecb.png">

Is [this](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated) what you're referring to by "string interpolation"? Or have I got that wrong?

**Comment by Alhadis** [comment]
Never mind, I really did get that wrong. 😅It needed a leading `$`. But it still [appears to be working fine on GitHub's end](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fatom%2Flanguage-csharp%2Fmaster%2Fgrammars%2Fcsharp.cson&grammar_text=&code_source=from-text&code_url=&code=Console.WriteLine%28%24%22Hello%2C+%7B0%7D%21+Today+is+%7B1%7D%2C+it%27s+%7B2%3AHH%3Amm%7D+now.%22%2C+name%2C+date.DayOfWeek%2C+date%29%3B).

<img width="371" alt="screen shot 2018-04-18 at 8 40 10 pm" src="https://user-images.githubusercontent.com/2346707/38927315-b58d561e-4348-11e8-930f-b9f2accf963f.png">

Admittedly, the interpolations aren't terribly obvious due to having very similar colours...

**Comment by kasper3** [comment]
I think this kind of variable interpolation is not highlighting correctly on GitHub:

```c#
var test = "foo";
Console.WriteLine($"Hello, {test}! Today is {1}, it's {2:HH:mm} now.", date.DayOfWeek, date);
```

(color of `test`)

**Comment by Alhadis** [comment]
@kasper3 Changes to Linguist don't take effect on GitHub until the next release, so until Linguist v6.0.2 is released, improvements to grammars won't be visible.

Hence the reason @stringfellow was asking. =)

**Comment by damieng** [comment]
Going to work on one more revision tonight to get the variable names to be black to be consistent with the current theme but then should be good to ship :)

**Comment by damieng** [comment]
That link works for me but the difference between the various colors in interpolated strings is very close.  Inspecting element shows it correctly tokenizing constants etc. tho.

**Comment by kasper3** [comment]
![image](https://user-images.githubusercontent.com/33230602/38945577-8c56ee26-433f-11e8-911f-26af6294095f.png)

Maybe my expectation is wrong; to get color of `{test}` and `:HH:mm` same as `{1}`, `{2}`?

**Comment by worldbeater** [comment]
@kasper3 it seems that only numbers and boolean values are highlighted using light blue color, and variable names and properties always use black color. I think it is because syntax highlighting should 
 be consistent and predictable.
```csharp
42 12345.24f true false
```

**Comment by Alhadis** [comment]
A shortlist of supported scope-names can be found at [`primer/github-syntax-light`](https://github.com/primer/github-syntax-light/blob/master/lib/github-light.map.json), with a more readable-looking list copied [here](https://gist.github.com/Alhadis/f742feb8f5c871b449dff39bb3dd6f5d).

If a scope appears to be "highlighted incorrectly", it might be that its choice of names are causing it not to be highlighted *at all*.

**Comment by damieng** [comment]
Thanks to the @worldbeater we look good to ship on language-csharp for github.com as of 1.0.3 that was just published!

**Comment by lildude** [comment]
Great!! I've not had the chance to build a test gem today as I've been trekking across London to get my race entry for Sunday's London Marathon, but I will cut the first test gem tomorrow morning :gb: time and test it. If all goes well, I hope to cut the final release gem by the end of the day or first thing on Monday with the aim of merging it mid-week pending PR approval etc.

**Comment by stringfellow** [comment]
Thanks @lildude and good luck with the marathon! Will cheer you on from the sides :)

**Comment by worldbeater** [comment]
YAY! It seems Linguist is now released and deployed, we can already see improvements in the C# grammar. The code now looks absolutely perfect. Thanks a lot and keep up your great work!

```csharp
this.WhenAnyValue(x => x.LinguistRelease)
    .Where(x => x.TestsSucceeded)
    .InvokeCommand(DeployToGitHub);
```

**Comment by lildude** [comment]
Woohoo!!! 🎉 

As we're now running 6.1.0, I'm gonna close this. Thanks for your patience peeps. 🙇 I hope to get into a regular monthly release cycle :soon:.

**Comment by stringfellow** [comment]
Thankyou @lildude, really appreciate it. Code review just got less painful :D
