### ISSUE TITLE
read docs folders

### ISSUE THREAD

**Issue by svnpenn** [github/linguist#4105]
i could be misreading the regex, but it appears that

https://github.com/github/linguist/commit/3837fed59e03f50047bc27efe2ff213baffdddcb

broke reading the `docs` folder for GitHub Pages

**Comment by svnpenn** [comment]
it is because linguist thinks "documentation" should not be included in language stats - here is fix:

~~~
$ cat .gitattributes
docs/* linguist-documentation=false
~~~

**Comment by pchaigno** [comment]
> broke reading the docs folder for GitHub Pages

What do you mean by that? Linguist shouldn't impact GitHub Pages...

**Comment by svnpenn** [comment]
@pchaigno i am using "master branch /docs folder" for github pages - because of that, i have to put my javascript files in that folder - because of that - linguist thinks that my javascript is "documents" and doesnt count it towards the language stats

the fix is as i put above, but maybe this whole situation should be reviewed

**Comment by pchaigno** [comment]
Oh, okay. I thought it was breaking your GitHub page. It works as expected then.
We expect most users don't want their documentation to be counted in the language statistics (otherwise, Java repositories could end up tagged as HTML for example).
