### ISSUE TITLE
LLVM MachineIR is identified as Mirah Language

### ISSUE THREAD

**Issue by Naville** [github/linguist#4113]
## Preliminary Steps

Please confirm you have...
- [✅] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [✅] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [✅] considered implementing an [override](https://github.com/github/linguist#overrides),
- [✅] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

LLVM has a small obscure format known as MIR which stands for MachineIR. This is currently being recognized as Mirah language due to the file extension ``.mir``. This could be detected by using LLVM MIR's keywords like ``liveins:`` ``body:`` ``tracksRegLiveness`` and whatnot
### URL of the affected repository:

[LLVM-Mirror](https://github.com/llvm-mirror/llvm)

### Last modified on:

2018-04-23
### Expected language:

LLVM MachineIR
### Detected language:

Mirah

**Comment by pchaigno** [comment]
Thanks for the report @Naville!

Looks like there's [a large enough corpus of such file on GitHub.com](https://github.com/search?p=1&q=extension%3Amir+liveins+OR+tracksRegLiveness&type=Code&utf8=%E2%9C%93) to warrant its support in Linguist. Would you like to [take a stab at it](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) @Naville?

**Comment by Naville** [comment]
@pchaigno I'd love to. Unfortunately after reading the contributing guide I figured it's a little bit too much for me😢

**Comment by gabru-md** [comment]
Hello, I have never contributed to this project before, but would really like to contribute here.
Can I try this issue once? If no one is looking into it as of now? :smiley: :sweat_smile:

**Comment by pchaigno** [comment]
@gabru-md Go ahead. We'll help if there's any issue. Don't forget to check out [the contribution guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language).

**Comment by gabru-md** [comment]
Thank you @pchaigno.
I'll go through the contribution guidelines and start working on it :+1:

@Naville even if YAML is the container it is using, but since the extension format is .MIR then I guess it should be identified as LLVM MIR? :sweat_smile: What are your thoughts ?

**Comment by pchaigno** [comment]
You're right, we should add it as a new extension for YAML instead of a new language. Unless there is grammar specific to LLVM MachineIR, in which case we can add it as its own entry but under the YAML group.

**Comment by gabru-md** [comment]
So am I supposed to add it as a new language? In that case I will go through the adding language guide as in the repository. 
I am sorry, I am a beginner to this project :sweat_smile: , but do you mean that adding it LLVM MIR as an extension to YAML will classify it as YAML only? 
I might need a bit of clarification :sweat_smile:

**Comment by pchaigno** [comment]
> So am I supposed to add it as a new language?

That depends if you found a grammar specific to LLVM MIR or if you're going to use that for YAML.

> but do you mean that adding it LLVM MIR as an extension to YAML will classify it as YAML only?

Yes. There are guidelines for that too, under the guidelines for adding a language.

**Comment by gabru-md** [comment]
Okay, So I will be updating `languages.yml` specifically the `LLVM`( by adding `.mir` extension) portion and adding Samples into the Sample Directory. Because we want the `.mir` to be identified as LLVM as well :sweat_smile: 
But I could not find a suitable subdirectory for adding samples for `LLVM`. Since I will be adding the `.mir` samples to it, can you please tell me what to do ? :sweat_smile: 
should I take the  [code for samples from here?](https://github.com/search?p=1&q=extension%3Amir+liveins+OR+tracksRegLiveness&type=Code&utf8=%E2%9C%93)
and provide the reference to the main code in the comments of files ?

**Comment by pchaigno** [comment]
> Because we want the `.mir` to be identified as LLVM as well :sweat_smile: 

Do we? It does look like they have the same syntax at all. From what I understand, while LLVM MIR is related to LLVM, it is YAML.

**Comment by gabru-md** [comment]
Okay, I will add it to YAML then.
So my work involves adding `.mir` extension to YAML types and creating some examples inside the `YAML` samples directory. 
Please point me if I am wrong. Sorry, for asking too many questions :sweat_smile:

**Comment by gabru-md** [comment]
@pchaigno is this all I need to do? Because if it is, then I will send a PR asap. :sweat_smile:

**Comment by pchaigno** [comment]
Yes, you'll only need to follow [the first 3 steps from the contribution guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language). We'll make sure the classifier can distinguish Mirah files from LLVM MIR files once the PR is opened.

**Comment by gabru-md** [comment]
I've created a PR for the same. Please review it when you have time :smiley: :+1:
