### ISSUE TITLE
RMarkdown Repo Not Being Recognized as Having Any Languages

### ISSUE THREAD

**Issue by stefmolin** [github/linguist#4119]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
This repo has code in it, but nothing shows up after a few hours even. Other repos that I added today are properly identified. I saw RMarkdown in the languages that Linguist knows (from the YAML file); however, my repo isn't being identified. 

### URL of the affected repository: 
https://github.com/stefmolin/R-training-program

### Last modified on:
2018-04-29

### Expected language:
RMarkdown

### Detected language:
nothing

**Comment by stefmolin** [comment]
It is also not being recognized in this repo: https://github.com/stefmolin/SCOPE-Anomaly-Detection-Case-Study

There I have mostly RMarkdown and Jupyter Notebooks with some R and Python; however, RMarkdown doesn't show up at all while the others do.

**Comment by lildude** [comment]
This is expected as, as you would have noticed from reading how Linguist works (you checked the box 😉)

> Linguist starts by going through all the files in a repository and excludes all files that it determines to be binary data, vendored code, generated code, documentation, or are defined as data (e.g. SQL) or **prose (e.g. Markdown) languages**, whilst taking into account any overrides.

The big clue is right near the end and I’ve emphasised it. RMarkdown, like regular Markdown, is prose:

https://github.com/github/linguist/blob/f9c00deecfb63efad37108f7b13699fc74bccbfe/lib/linguist/languages.yml#L3797-L3798

You also checked the “considered implementing an override” checkbox so you acknowledge you read https://github.com/github/linguist#detectable so know how to override the default behaviour too 😁

So Linguist is working as expected and this is really a squishy problem 😜

**Comment by dfalbel** [comment]
I understand that linguist is working as expected, but I don't think RMarkdown documents should be considered pure prose. They are more like a Jupyter Notebook that is marked as a different language in Github repo statistics.

**Comment by Alhadis** [comment]
@dfalbel If you'd like RMarkdown counted in your own project statistics, you can override it by setting `linguist-detectable=true` in your `.gitattributes` file. The [Linguist readme explains more](https://github.com/github/linguist#detectable).

It's interesting you mention Jupyter Notebook, because we've had quite a number of reports from users complaining that their entire project was classified as "Jupyter Notebook" because of the how huge a single `.ipynb` file was.  I predict if we gave RMarkdown the same treatment, we'd get the same issues reported by users whose R projects became "RMarkdown" overnight.

**Comment by dfalbel** [comment]
@Alhadis you are right! I agree! Thank you very much for your answer!
