### ISSUE TITLE
Detectable, generated and vendored attributes unexpected behaviour

### ISSUE THREAD

**Issue by 5N44P** [github/linguist#4121]
Detectable, generated and vendored attributes are behaving differently from what they are supposed to do

## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
I'm not sure if it's just me unable to use linguist attributes properly, or it's a cache thing or it's a bug.
I have a repo containing mainly kicad and c sources. I have made this `.gitattributes` file:
```
*.kicad_pcb linguist-detectable=true
*.sch linguist-detectable=true
fp-lib-table linguist-generated=true
*.xml linguist-generated=true
*.txt linguist-generated=true
*.kicad_mod linguist-vendored=true
```
To:
- Make kicad_pcb and kicad schematic files listed in the language breakdown
- Hide fp-lib-table, xml and txt files as generated
- Hide .kicad_mod files as vendored  

As a result:
- kicad_pcb are not shown in the language breakdown ❌
- fp-lib-table, xml and txt files are hidden ✔️
- .kicad_mod files are shown as "kicad layout" in the language breakdown ❌

As of today i've made a small modification to the `gitattributes` file that may fix the `kicad_mod` problem, but the other problem should persist. As i said, i'm not totally sure about my usage of the attributes. Please excuse the issue if i'm using them wrong. The latest version states:

```
. . . 
*.kicad_mod linguist-vendored=true
Hardware/customfootprints.pretty/* linguist-vendored
```

### URL of the affected repository:
[.gitattributes in 5N44P/Banana-Random-Number-Generator](https://github.com/5N44P/Banana-Random-Number-Generator/blob/75d5c5c1f3aa236749553fb38e7177e8913007ac/.gitattributes)

[Older version of .gitattributes in 5N44P/Banana-Random-Number-Generator](https://github.com/5N44P/Banana-Random-Number-Generator/blob/95ff1b85cddd5113abd97bca49ec5b0d29991e89/.gitattributes)

### Last modified on:
2018-05-02

### Expected behaviour:
Kicad_pcb detected and kicad_mod hidden

### Current behaviour:
Kicad_mod detected and kicad_pcb hidden

**Comment by lildude** [comment]
I've checked your repo and everything _is_ working as you expect from a Linguist perspective.  The only files that are contributing to your language stats are:

- KiCad Layout:
`Hardware/BRNG.kicad_pcb`
- KiCad Schematic: 
`Hardware/BRNG.sch`

All other files are being ignored or not considered.

You can verify this locally too (this is with your old .gitattributes file in place locally):

```
$ cat .gitattributes
*.kicad_pcb linguist-detectable=true
*.sch linguist-detectable=true
fp-lib-table linguist-generated=true
*.xml linguist-generated=true
*.txt linguist-generated=true
*.kicad_mod linguist-vendored=true
$
$ linguist --breakdown .
91.51%  KiCad Layout
8.49%   KiCad Schematic

KiCad Layout:
Hardware/BRNG.kicad_pcb

KiCad Schematic:
Hardware/BRNG.sch

$
```

The issue that comes up is how you're verifying things. Clicking the language within the stats bar actually hands things over to the search side of things (note the URL) and for the most part, this is independent of Linguist. Linguist is only used to determine the language and calculate the repo breakdown statistics. Search will use the language info but will not honour the other Linguist gitattributes as they're not really relevant to search.

You can't hide files from search and wouldn't I think you'd want to either.

When it comes to creating a pull request, you should find your overrides will take effect as you expect then too.

**Comment by 5N44P** [comment]
@lildude Thank you! So i'm using the attributes right.
Is `Hardware/customfootprints.pretty/* linguist-vendored` a good practice? 

So it is a search-related issue, breakdown bar percentage are confirmed.
But if that's the case:
- Why fp-lib-table, XML and txt files are hidden in the search? 
In this other repo, where the same .gitattributes are set, i can see [.kicad_pcb and fp-lib-tables](https://github.com/5N44P/omega-dock-new/search?l=kicad-layout), [.txt files](https://github.com/5N44P/omega-dock-new/search?l=Text), and [xml files](https://github.com/5N44P/omega-dock-new/search?l=XML). 
- Why is kicad_pcb hidden or not recognized in the search? 

Does this have any relevance on the linguist side?
Is this a github-linguist integration issue? I understand that we're a bit on the github-linguist dividing edge...

**Comment by lildude** [comment]
> So i'm using the attributes right.

Yup 😄 

> Is Hardware/customfootprints.pretty/* linguist-vendored a good practice?

I couldn't really say as I know nothing about it 😄 but it's certainly the right thing to do if you don't it to count towards your language stats.

> Why fp-lib-table, XML and txt files are hidden in the search?

This one is easy to answer: search won't index what's not there 😉.

Your new repo doesn't appear have any of those files from what I can see:

```
$ find ./Banana-Random-Number-Generator | egrep '.txt|fp-lib-tables|.xml'
$
```

It _does_ however [identify your LICENSE file as txt](https://github.com/5N44P/Banana-Random-Number-Generator/search?l=Text) as it does for your omega-dock-new repo.

> Why is kicad_pcb hidden or not recognized in the search?

[Considerations for code search](https://help.github.com/articles/searching-code/#considerations-for-code-search) 😉. Your one `.kicad_pcb` file is 508.21 KB so exceeds the 384 KB indexing limit.

That reminds me, I really need to reword [point 1](https://github.com/github/linguist#my-repository-is-detected-as-the-wrong-language) to make the size thing clearer as this is commonly missed.

> Does this have any relevance on the linguist side?
> Is this a github-linguist integration issue? I understand that we're a bit on the github-linguist dividing edge (well... linguist is a standalone project, i guess that's not technically correct to speak of a dividing edge)...

Nope cos of the explanation on each point above.

**Comment by 5N44P** [comment]
> This one is easy to answer: search won't index what's not there wink.
> Your new repo doesn't appear have any of those files from what I can see:

That's me being retarded 😅 

> Your one .kicad_pcb file is 508.21 KB so exceeds the 384 KB indexing limit.

And that's me being retarded part 2.

Ok so it's totally my fault. Thank you for your help and for further clarifying the usage of the attributes

I'm closing this, but I've one more question left:
I'm trying to make my `.gitattributes` file as reusable as possible. Would something like `*.pretty/* linguist-vendored` work for classifying as vendored every file in a "something.pretty" folder as vendored?

**Comment by lildude** [comment]
> I'm trying to make my .gitattributes file as reusable as possible. Would something like *.pretty/* linguist-vendored work for classifying as vendored every file in a "something.pretty" folder?

I'm not sure off the top of my head. I know .gitattributes behaves slightly differently when it comes to wildcards in paths. I recall @Alhadis mentioning something about this difference recently, but can't find where right now.

**Comment by Alhadis** [comment]
@5N44P My comment was a bit long-winded, so I'll link instead of copy+paste:

https://github.com/github/linguist/issues/4102#issuecomment-381550820
