### ISSUE TITLE
Linguist-vendored can't suppress files in paths with spaces

### ISSUE THREAD

**Issue by Peter-Simpson** [github/linguist#4122]
Hi,
I'm trying to suppress recognition of some .c and .h files in a committed directory from a Windows machine that contains spaces in its name: "SOFA/Release Zip Files"

I've tried both these variants in the .gitattributes file:
SOFA/Release[[:space:]]Zip[[:space:]]Files/** linguist-vendored
SOFA/Release Zip Files/** linguist-vendored

 but the files are still recognised by Linguist in the list of C files.

Please can you advise correct syntax or approach?

Thanks, Peter

## Preliminary Steps

Please confirm you have...
- [Yes] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [Yes] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [Yes] considered implementing an [override](https://github.com/github/linguist#overrides),
- [Yes] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

As above, probably not a bug but I've tried the answers I've found through Googling the issue and they haven't worked. The files in question can be seen on page 57 of the list of C files in the ASCOMPlatform reporsitory.

### URL of the affected repository:
https://github.com/ASCOMInitiative/ASCOMPlatform

### Last modified on:
2018-05-04

### Expected language:
Files should be ignored

### Detected language:
C

**Comment by pchaigno** [comment]
This should work for what you're trying to achieve:
```
SOFA/Release?Zip?Files/** linguist-vendored
```

I'll shamelessly cite my own answer from [SO](https://stackoverflow.com/a/44990789/6884590) :p

> Unfortunately, [git does not support white space escaping in .gitattributes' paths](http://git.661346.n2.nabble.com/gitattributes-escape-character-td5701115.html). `[[:space:]]` is only for regular expressions (`wordRegex`). `?` will match any character and not only spaces, but it might be enough in your case.

**Comment by Alhadis** [comment]
Moral of the story: don't use spaces in pathnames. 😁

(Sorry, but somebody *had* to say it)

**Comment by Peter-Simpson** [comment]
Hi Paul,

That didn't work for me, I think it was then getting stuck on a lower sub-directory that also had spaces in its name. I've just renamed the directory and sub directory to omit spaces and I can see that the code statistics have now changed.

Thanks for your help!

Regards, Peter

**Comment by Peter-Simpson** [comment]
Hi John

The moral that I take from this story is that applications should be resilient and should report issues in input data that they cannot handle... 😁

Perhaps some parameter checking on the path before carrying out the search would be in order?

Regards, Peter

**Comment by Alhadis** [comment]
Yes, of course. 😅 It was just a lighthearted reference to the widespread dislike that terminal users have for pathnames containing spaces.

> Perhaps some parameter checking on the path before carrying out the search would be in order?

Well... The Right Way™ to do this would be to add support for `[[:space:]]` so Linguist's interpretation of `gitattributes` syntax is strictly equivalent to Git's interpretation. But as @pchaigno said, that's already a known issue with Linguist. 😞

**Comment by pchaigno** [comment]
> The Right Way™ to do this would be to add support for `[[:space:]]` so Linguist's interpretation of `gitattributes` syntax is strictly equivalent to Git's interpretation.

@Alhadis From what I understand, Linguist's interpretation of `.gitattributes` syntax **is** that of Git.

**Comment by Alhadis** [comment]
@pchaigno Erh... it clearly can't be when Linguist lacks support for `[[:space:]]` when Git doesn't:

~~~console
λ tmp (master): ls -alh
total 8
drwxr-xr-x   5 johngardner  staff   160B  4 May 23:13 .
drwxr-xr-x+  7 johngardner  staff   224B  4 May 23:13 ..
drwxr-xr-x  12 johngardner  staff   384B  4 May 23:14 .git
-rw-r--r--   1 johngardner  staff    41B  4 May 23:14 .gitattributes
-rw-r--r--   1 johngardner  staff     0B  4 May 23:13 foo bar
λ tmp (master): cat .gitattributes
foo[[:space:]]bar linguist-documentation
λ tmp (master): git check-attr --all *
foo bar: linguist-documentation: set
~~~

**Comment by Alhadis** [comment]
Most definitely.

I vaguely remember encountering another discrepancy a long time ago, but have forgotten which. It certainly wasn't this, because I had no idea the `[[:space:]]` feature even existed until this issue was filed.
