### ISSUE TITLE
GML Projects get marked as Yacc because of .yy files

### ISSUE THREAD

**Issue by RobQuistNL** [github/linguist#4129]
Newer Game Maker Studio 2 projects will contain .gml files with GameMakerLanguage code in it, and corresponding .yy files - which contain metadata in a JSON structure. They get falsely detected as Yacc files.

We (in the community) have been working around this problem by adding ``*.yy linguist-language=Game Maker Language`` to our .gitattributes file.

We would prefer to have .GML detected as GML, and .yy as JSON. (Maybe even GML because its a part of the .gml files).

Is this something I could create an MR for? I'm not sure how to implement this case into this repository, but I'd love to.

> If there's a .yyp, a bunch of .gml and a bunch of .yy - I'm 99% sure its a GMS2 project, with .yyp and .yy being JSON files and .gml being GML.

### URL of the affected repository:
Example with override: https://github.com/GameMakerDiscord/handytools
Example without override: https://github.com/RobQuistNL/handytools

### Expected language:
GML, JSON

### Detected language:
GML, Yacc

**Comment by pchaigno** [comment]
You could follow [the contribution guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language) to add `.yy` as an extension to JSON. [It looks like the in-the-wild requirement is met](https://github.com/search?p=99&q=modelname+extension%3Ayy&type=Code&utf8=%E2%9C%93).

`.gml` should already be [recognized as Game Maker Language files](https://github.com/github/linguist/blob/59f5b05161e7b17236f90a6aa8f9085389d64b1f/lib/linguist/languages.yml#L1494). The detection is not 100% accurate though. One way to improve it would be to add new [heuristic rules](https://github.com/github/linguist/blob/59f5b05161e7b17236f90a6aa8f9085389d64b1f/lib/linguist/heuristics.rb) for `.gml`. Do you have an easy way to differentiate between Game Maker Language, Graph Modeling Language, and XML (I'm guessing not the three, but if you have something for Game Maker Language, that's already something we might be able to use)?

**Comment by RobQuistNL** [comment]
Ah, the heuristic rules is probably something I'll look in to. It seemed like there were certain keywords and built-in functions missing, so I'll see if I can open up a PR for that. I'll open up a PR for the .yy as well.

**Comment by kt-altyn** [comment]
has been over 5 years and not fixed lol

**Comment by lildude** [comment]
@kt-altyn this was fixed over five years ago by https://github.com/github-linguist/linguist/pull/4130. If you are still experiencing misclassification, it'll be because the files don't match the heuristics implemented in that PR and those heuristics could do with improvement.

Feel free to open a new [discussion](https://github.com/github-linguist/linguist/discussions) and we can look into your specific case.

**Comment by RobQuistNL** [comment]
There might have been some changes since I think a lot of the heuristics have changed (as well as the file format of .yy and .yyp)

I haven't touched GM in a while but I'll be sure to check up on it in the future. Can't say when exactly though

**Comment by kt-altyn** [comment]
> 
i just have setup github repo for my gamemaker project and it detected 99% of the project as yacc as you see
![image](https://github.com/github-linguist/linguist/assets/92668715/1072abc8-57ee-450c-93a2-d7c4b8f45dfe)

**Comment by lildude** [comment]
@kt-altyn do you have a URL we can visit to check? We really need a URL to be able to workout what’s going on. If you’d prefer not to make it public, feel free to add me as a collaborator and I can take a look.

**Comment by kt-altyn** [comment]
i have added both of you

**Comment by RobQuistNL** [comment]
I think this is because its the newer GM Studio 2.3 format.

I'll look into this soon, but can't give any guarantees

**Comment by lildude** [comment]
@kt-altyn I think @RobQuistNL has got it. From a quick look at the files in your repo, those that are being identified as Yacc do _not_ match this:

https://github.com/github-linguist/linguist/blob/916bd8f3df802fa98b0ea85539e67bd0b88ef158/lib/linguist/generated.rb#L672-L683

... or this ...

https://github.com/github-linguist/linguist/blob/916bd8f3df802fa98b0ea85539e67bd0b88ef158/lib/linguist/heuristics.yml#L810-L814

... so are falling through to "Yacc".

I've opened https://github.com/github-linguist/linguist/issues/6517 to track this improvement.

If you've got the time and skills, feel free to submit a PR.

Until then, you can resolve this by implementing an override that does both of these:

```gitattributes
*.yy linguist-language=JSON,linguist-generated
```

This will result in only your `.gml` files contributing to your language stats.

I'm going to lock comments on this very very old issue now. If you want any further help, please start a new discussion.

**Comment by Alhadis** [comment]
> Until then, you can resolve this by implementing an override that does both of these:
>
> ```gitattributes
> *.yy linguist-language=JSON,linguist-generated
> ```

@lildude I believe you meant:

~~~gitattributes
*.yy linguist-language=JSON linguist-generated
~~~

(… unless something changed more recently that I'm not aware of?)

**Comment by lildude** [comment]
Whoops, yes. No comma and a space instead. Good catch.
