### ISSUE TITLE
How to override a file extension for all subfolders?

### ISSUE THREAD

**Issue by klacol** [github/linguist#4135]
We want to attach the file type XML to all files with the extension .ifcXML in this repo:

https://github.com/BuildingSMART/ProductData

In the root folder, I have created the file ".gitattributes" with this content:

```
$ cat .gitattributes
**/*.ifcXML linguist-language=XML
**/**/*.ifcXML linguist-language=XML
**/**/**/*.ifcXML linguist-language=XML
**/**/**/**/*.ifcXML linguist-language=XML
```
But this does not activate the synatx highlighting for XML in the files in the subfolders.

When I put a ".gitattributes" file directly in a [subfolder](https://github.com/BuildingSMART/ProductData/tree/master/SampleFiles/bSDD%20product%20room%20sample), the syntax highlighting can be activated.

Does anyone has a tip, how I can active the syntax higlighting for all .ifcXML files in all folders, without saving the ".gitattributes" file in every folder?

**Comment by pchaigno** [comment]
The following should be enough:
```
*.ifcXML linguist-language=XML
```
Any reason why you chose to discard the issue template?

**Comment by klacol** [comment]
Oh, sorry, here is the issue template:

I have
- [ x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x ] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x ] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x ] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

see above, I do not think it is a bug, I suppose there is something else wrong.

### URL of the affected repository:
https://github.com/BuildingSMART/ProductData

### Last modified on:
2018-05-22

### Expected language:
XML for files with the extension ifcXML

### Detected language:
no syntax highliting in sub folders

**Comment by klacol** [comment]
I think I got it, thanks,

The push of the ".gitattributes" file is not enough to update the statistics. After pushing another change, the syntax highlighting was rendered.

**Comment by pchaigno** [comment]
Yes, that delay is [explained in the README](https://github.com/github/linguist#how-linguist-works-on-githubcom):

> When you push changes to a repository on GitHub.com, a low priority background job is enqueued to analyze your repository as explained above. The results of this analysis are cached for the lifetime of your repository and are only updated when the repository is updated. As this analysis is performed by a low priority background job, it can take a while, particularly during busy periods, for your language statistics bar to reflect your changes.
