### ISSUE TITLE
Modula-3 and Quake

### ISSUE THREAD

**Issue by jcchu** [github/linguist#4136]
Modula-3 and Quake are not recognized by Linguist.

## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

[Modula-3](https://en.wikipedia.org/wiki/Modula-3) is a systems programming language [designed](https://dx.doi.org/10.1145/142137.142141) in the late 1980s.  It resembles but is not compatible with Modula-2, which (I believe) Linguist recognizes.  Modula-3 uses four filename extensions: [i3](https://github.com/modula3/cm3/blob/master/m3-libs/slisp/src/SLisp.i3) (for interfaces), [ig](https://github.com/modula3/cm3/blob/master/m3-libs/libm3/src/list/List.ig) (for generic interfaces), [m3](https://github.com/modula3/cm3/blob/master/m3-libs/libm3/src/pickle/ver2/BuiltinSpecials2.m3) (for modules), and [mg](https://github.com/modula3/cm3/blob/master/m3-libs/digraph/src/DiGraph.mg) (for generic modules), none of which currently appears in [languages.yml](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml).

Quake is a scripting language used by Critical Mass Modula-3 (CM3), the major implementation of the language.  Typically, Quake scripts don’t have filename extensions, and are usually named [“m3makefile”](https://github.com/modula3/cm3/blob/master/m3-sys/m3front/src/m3makefile) or [“m3overrides”](https://github.com/modula3/cm3/blob/master/m3overrides).  The language is documented at [https://github.com/modula3/cm3/blob/master/doc/help/cm3/quake.html](https://htmlpreview.github.io/?https://github.com/modula3/cm3/blob/master/doc/help/cm3/quake.html).

### URL of the affected repository:

* https://github.com/modula3/cm3  
* https://github.com/modula3/pm3  
* https://github.com/metacore/spin

### Last modified on:
2018-05-24

### Expected language:
* Modula-3  
* Quake

### Detected language:
(none)

**Comment by lildude** [comment]
Take a look at our [contributing guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md) and feel free to submit a PR for each of those languages, provided their usage meets the minimum requirements.

**Comment by jcchu** [comment]
Thanks.  I’ve opened a pull request.  Let’s see how it goes.
