### ISSUE TITLE
grammar-compiler XML parser errors are reported as "source contains no grammar files"

### ISSUE THREAD

**Issue by wesinator** [github/linguist#4141]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Trying to run `sudo ./script/add-grammar https://github.com/infosec-intern/textmate-snort`, getting 
```
Registering new submodule: vendor/grammars/textmate-snort
$ git submodule add -f https://github.com/infosec-intern/textmate-snort vendor/grammars/textmate-snort
$ script/grammar-compiler add vendor/grammars/textmate-snort
  > latest: Pulling from linguist/grammar-compiler
  > Digest: sha256:b019869fcf736922e21dd44d2982a0f78ce31b9d24f73f4f758ef1a071c8b4a7
  > Status: Image is up to date for linguist/grammar-compiler:latest
  > source 'vendor/grammars/textmate-snort' contains no grammar files
Command failed. Aborting.
```
Grammar is at https://github.com/infosec-intern/textmate-snort/blob/master/syntaxes/snort.tmLanguage

It sounds like this should have been fixed by https://github.com/github/linguist/pull/4015

**Comment by lildude** [comment]
@vmg any hints on why this isn't being detected?

**Comment by lildude** [comment]
After a lot of debugging, I've worked out the problem... your `snort.tmLanguage` file has syntax errors:

```
$ xmllint vendor/grammars/textmate-snort/syntaxes/snort.tmLanguage
vendor/grammars/textmate-snort/syntaxes/snort.tmLanguage:57: parser error : StartTag: invalid element name
            <string>(-\>|\<\>)</string>
                           ^
vendor/grammars/textmate-snort/syntaxes/snort.tmLanguage:157: parser error : StartTag: invalid element name
			<string><</string>
			         ^
vendor/grammars/textmate-snort/syntaxes/snort.tmLanguage:184: parser error : StartTag: invalid element name
			<string><</string>
			         ^
```

When the grammar compiler runs when adding a grammar it validates the XML and disregards the file if a syntax error is found.

You need to use `&gt;` and `&lt;` instead of `>` and `<` respectively.

Once those are addressed, you'll then encounter another problem which will prevent the grammar from being added:

```
The new grammar repository `vendor/grammars/textmate-snort` (from https://github.com/infosec-intern/textmate-snort) contains 1 errors:
    - Unknown keys in grammar: `source.snort` (in `syntaxes/snort.tmLanguage`) contains invalid keys (`smartTypingPairs`, `highlightPairs`)
```

I'm not a TextMate grammar expert, but I believe these keys shouldn't be in the `tmLanguage` file, but rather the `tmPreferences` file.

**Comment by wesinator** [comment]
Ok, thanks.
Why doesn't it catch XML validation errors and print them ?

**Comment by lildude** [comment]
> Why doesn't it catch XML validation errors and print them ?

Well, it does catch them. I’m not sure why they’re not printed but I suspect it’s for a few reasons:

1. These kind of errors should normally be picked up long before the grammar is added to Linguist as it wouldn’t perform correctly in the various editors, and
2. Errors could be printed for files that appear to be grammar files but aren’t really, potentially leading to confusion and a lot of yak shaving.

@vmg may know more.
