### ISSUE TITLE
Add Snort language

### ISSUE THREAD

**Issue by wesinator** [github/linguist#4142]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
Add https://github.com/infosec-intern/textmate-snort

https://github.com/search?utf8=%E2%9C%93&q=alert+tcp+extension%3Arules

Trying to make a PR, blocked by #4141

**Comment by lildude** [comment]
Gonna close this as the lack of support is implied by your attempts, and problems encountered, detailed in https://github.com/github/linguist/issues/4141.
