### ISSUE TITLE
My repository isn't showing my language (python)

### ISSUE THREAD

**Issue by zhoudaxia233** [github/linguist#4162]
## Problem Description
My repository contains some python files but nothing is shown on my repository language statistics.
I've tried all methods on Troubleshooting page, but it still doesn't work.

### URL of the affected repository:
https://github.com/zhoudaxia233/AsciiArt

### Last modified on: 
2018-06-10

### Expected language:
Python

### Detected language:
Nothing

![image](https://user-images.githubusercontent.com/30392089/41204672-0320b088-6ce8-11e8-8c7b-a9b042161a69.png)

**Comment by zhoudaxia233** [comment]
I don't know why, but after 24 hours later it suddenly works!

**Comment by pchaigno** [comment]
From the [README](https://github.com/github/linguist#how-linguist-works-on-githubcom):
> When you push changes to a repository on GitHub.com, a low priority background job is enqueued to analyze your repository as explained above. The results of this analysis are cached for the lifetime of your repository and are only updated when the repository is updated. As this analysis is performed by a low priority background job, it can take a while, particularly during busy periods, for your language statistics bar to reflect your changes.

I looks like it's taking longer and longer... Maybe something for @lildude to check when he'll be back from vacations.

**Comment by lildude** [comment]
Yup, looks like we had a large build up of higher priority jobs meaning it took a lot longer for the low priority jobs, like language analysis. All's good now.
