### ISSUE TITLE
Allowing for overriding an extension to an unknown language

### ISSUE THREAD

**Issue by jakob-hendrix** [github/linguist#4166]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

My team has just begun moving a quite old code base that uses an obscure COBOL-esque language called __DBC__ into my employer's enterprise Github server,

This language uses __*.ps__ as its extension, which results in all repos with __DBC__ code being labelled as __Postscript__.

If I use the override entry in _.gitattributes_ (`*.ps linguist-language=DBC`) this results in the repo being labelled as a __shell__ language, as the next most common language is the _Korn shell_.

I am guessing that the override is looking for "DBC" in linguist, not finding it, thus ignoring all __*.ps__ files.

Would it be possible to either:
* use the current override to force the repo label to whatever language we enter, and ignore syntax-highlighting if the language is otherwise undefined, or
* add a new `*.ps linguist-language-force=[obscure language]` (or something) option instead

This would greatly ease my OCD and also allow for a more default Github organizing experience for older/obscure language developers and we creep into the modern era.

### URL of the affected repository:
I have copied over a sample of this code. The initial load had no __.gitattributes__ and so was labelled as _Postscript_. I then added the __.gitattributes__ and merged into _master_, which changed the labelling to _shell_.

https://github.com/jakob-hendrix/dbc-linguist-sample.git

### Expected language:
DBC

### Detected language:
Shell

**Comment by lildude** [comment]
This has been brought up before and unfortunately, won't be implemented anytime soon. To quote my response at https://github.com/github/linguist/issues/3792#issuecomment-382391903

> This is expected behaviour. Allowing an override for an unknown language would be a major security risk, would require additional sanitisation of user input and would be prime for abuse.

As your language is COBOL-esque, you could try forcing the language to COBOL using `*.ps linguist-language=COBOL`. You may not get the best syntax highlighting, but it may be good enough. I've done this in my fork of your sample repo at https://github.com/lildude/dbc-linguist-sample

Alternatively, mark them as text using `*.ps linguist-language=text` which will exclude them from the language stats and disable syntax highlighting.

As for:

> The initial load had no .gitattributes and so was labelled as Postscript. I then added the .gitattributes and merged into master, which changed the labelling to shell.

This will be because the next most popular language in your repo is your Korn shell script. Keep in mind:

> The result of this analysis is used to produce the language stats bar which displays the languages percentages for the files in the repository. The percentages are calculated based on the bytes of code for each language as reported by the List Languages API.

... so the "primary" language is really just the most popular by bytes of code.

**Comment by jakob-hendrix** [comment]
Yeah, I assumed that was the case regarding the fall-through to _shell_.  Is it at all possible to do a personal fork of linguist and force our enterprise Git account to use _that_ version instead of the primary repo?

**Comment by lildude** [comment]
No. Linguist is bundled into a gem and then pulled into the main GitHub code base. Replacing individual gems on your GitHub Enterprise appliance is not supported and attempts to do so are likely to lead to unpredictable results. Things are further complicated by the fact that Linguist requires several tables to be populated with the languages and their IDs and the jobs to do this are not shipped with GitHub Enterprise as they're not needed within the appliance. Any unsupported changes you make to your GitHub Enterprise would also be lost on subsequent upgrades or updates.

**Comment by jakob-hendrix** [comment]
Ah. Thanks for the help. I guess the only definitive answer is to transition to a more common language. Your work-around will do for now, as at least the languages (DBC and COBOL) share some common syntax and the goal of sorting, though roughly the same as leaving them marked "Postscript", is accomplished.
