### ISSUE TITLE
Notice: Lightshow is temporarily offline

### ISSUE THREAD

**Issue by lildude** [github/linguist#4168]
We don't really have a better place for notifications, so I'm opening an issue.

Lightshow has been temporarily pulled offline whilst we address a few critical problems with it. We'll bring it back up as soon as we can.

I'll close this issue once it's back online.

Sorry for the inconvenience.

**Comment by pchaigno** [comment]
@lildude Any news on this? We can't really test syntax highlighting without Lightshow...

**Comment by lildude** [comment]
Nope. 😞 Still ironing out the issues.

**Comment by kivikakk** [comment]
Hiya! I've been working on getting Lightshow up and running with our new backend; it should be usable right now! Would you like to give it a test and tell me how you find it?

https://github-lightshow.herokuapp.com/

**Comment by kivikakk** [comment]
(We might like to ping the issues in the [Awaiting Lightshow](https://github.com/github/linguist/issues?utf8=%E2%9C%93&q=label%3A%22Awaiting+Lightshow%22) tag, but I think @pchaigno is mostly on top of them all!)

**Comment by pchaigno** [comment]
Thanks @kivikakk for working on this!!

I get an HTTP 503 though when I try to use it with grammar https://github.com/github-linguist/babel-sublime/blob/master/JavaScript%20(Babel).tmLanguage and example https://github.com/github/linguist/blob/master/samples/JSX/sample.jsx :-/

**Comment by kivikakk** [comment]
Something weeeeird happened with its HTTPS certificates. I've restarted the app and that particular problem seems to have cleared up, but now I'm getting timeouts on actually doing the work. Maybe because it's `…/blob/…` and not `…/raw/…`.

**Comment by pchaigno** [comment]
Nop, looks like a timeout with `../raw/..` too. I'll try another grammar.

**Comment by kivikakk** [comment]
Yep, just tried. It's hitting the 10s processing timeout on the actual highlighting service. I could extend that, but I'd be wary of going too far.

**Comment by pchaigno** [comment]
Same issue with grammar https://raw.githubusercontent.com/FStarLang/atom-fstar/master/grammars/fstar.cson and example https://raw.githubusercontent.com/github/linguist/e4fd0f8cdc7c80d3c36eda3cf4dedfd482846084/samples/F*/Hacl.HKDF.fst. Was the timeout higher before?

**Comment by kivikakk** [comment]
Actually, weird: it's Lightshow's own configured timeout that is being hit here. Your latest example is trivial and not working. Looking into it. Thanks so much for your patience 🙏

**Comment by kivikakk** [comment]
Okay, turns out the lovely new service I've put into production has died hard on a malformed grammar, and hasn't restored itself 😅  It's a trivial fix/oversight of mine, so I'll let you know when I've fixed it and tested that the above samples you've demonstrated actually work.

**Comment by Alhadis** [comment]
What grammar was it, out of interest?

**Comment by kivikakk** [comment]
No idea, haven't looked that deeply into it yet. Still testing the hopeful-fix locally.

**Comment by kivikakk** [comment]
Oh, it was indeed https://github.com/github-linguist/babel-sublime/raw/master/JavaScript%20(Babel).tmLanguage ! A bool which isn't playing ball (playing bool?):

```xml
					<key>applyEndPatternLast</key>
					<integer>1</integer>
```

It looks like the newer compiler is expecting an actual bool here, i.e. `<true/>` or `<false/>` instead of an integer. We're quite a lot stricter now, but I suspect this is something we should handle. I'll try making the adjustment.

**Comment by Alhadis** [comment]
> playing bool?

Aahaaaaa, I get it.

https://i.pinimg.com/originals/f5/78/98/f578989f94381d4942c1163b77166e1d.jpg

**Comment by kivikakk** [comment]
Yay! Working locally. I'll deploy now.

![image](https://user-images.githubusercontent.com/1915/43885013-05994734-9bfb-11e8-922b-3fe9f5a3a534.png)

**Comment by Alhadis** [comment]
Yay!

God I hate that indentation.

**Comment by kivikakk** [comment]
It's online and 'working' again, but for a reason I cannot fathom it's highlighting very poorly compared to my local deploy of the same (!) code.

![image](https://user-images.githubusercontent.com/1915/43885702-ee58a3e2-9bfc-11e8-98cb-887728e10f39.png)

This weirdness aside (I'll need to look into it), it should be ready for testing against again.

**Comment by worldbeater** [comment]
Trying to test <a href="https://raw.githubusercontent.com/worldbeater/MemeBot/master/Memes/Start.fs">this F# source file</a> highlighting using <a href="https://raw.githubusercontent.com/ionide/ionide-fsgrammar/master/grammar/fsharp.json">this F# grammar</a>, but Lightshow says something went wrong :(

**Comment by kivikakk** [comment]
It's getting very newly hammered by spammers/metasploit-type stuff, and it's not happy. Looking into it again today though 👍

**Comment by kivikakk** [comment]
Finally back online. There's an intermittent issue with SSL causing page load fails which I'm _hoping_ has gone away with a change, but may not have; please report if you see any further difficulties.

**Comment by kivikakk** [comment]
@pchaigno Fixed! The method is a little on the conservative side; let me know if you think it's too conservative. It'd just be super annoying if legitimate input outright failed because it picked GET incorrectly.

**Comment by kivikakk** [comment]
Right now the results are a bit non-deterministic (!) — sometimes the result looks correct, sometimes it looks half-errored-out like the above screenshot of the `source.js.jsx` render. I'm on this today.

**Comment by kivikakk** [comment]
Determinism has returned to Lightshow!

![image](https://user-images.githubusercontent.com/1915/44075842-8bed23ac-9fe1-11e8-8a26-ffe2344de303.png)

This is the last issue **I'm** aware of, so if you see any more, please, let me know!

**Comment by davidhq** [comment]
Hi ! 

Is Lightshow gone?

<img width="915" alt="Screenshot 2022-04-20 at 11 57 42" src="https://user-images.githubusercontent.com/3899/164203076-3f650cea-43b2-4113-ae66-2972215d76cd.png">

**Comment by lildude** [comment]
@davidhq yes. See https://github.com/github/linguist/issues/5844

Unfortunately, we've had to abruptly bring the sunset date forward due to https://github.blog/2022-04-15-security-alert-stolen-oauth-user-tokens/

**Comment by davidhq** [comment]
@lildude thank you for explaining... does this mean the tool is gone forever?

**Comment by lildude** [comment]
@davidhq yes. There are more details in the issue.
