### ISSUE TITLE
Question: Vendor grammar submodule link update procedure?

### ISSUE THREAD

**Issue by omniomi** [github/linguist#4170]
Just a question: how would you prefer updates to vendor grammar files be handled? Would you prefer a PR with the change or an issue with a request to update the link? The PowerShell grammar is under active development so there are semi-frequent fixes and improvements.

Thanks.

**Comment by pchaigno** [comment]
Grammar submodules are updated automatically with each new release.
No need to send a pull request :smiley:

**Comment by omniomi** [comment]
@pchaigno perfect, thanks!
