### ISSUE TITLE
Fields in languages.yml

### ISSUE THREAD

**Issue by ikatyang** [github/linguist#4172]
I noticed some fields are missing in the header docs of `languages.yml`:

https://github.com/github/linguist/blob/4e239d9ecc6aa74641d604db66a39f7848693b98/lib/linguist/languages.yml#L1-L27

- `codemirror_mime_type`
- `filenames`
- `lexer`
  https://github.com/github/linguist/blob/4e239d9ecc6aa74641d604db66a39f7848693b98/lib/linguist/languages.yml#L2944-L2958

- `alias`: I guess this one should be `aliases`?
  
  https://github.com/github/linguist/blob/4e239d9ecc6aa74641d604db66a39f7848693b98/lib/linguist/languages.yml#L725-L736

  https://github.com/github/linguist/blob/4e239d9ecc6aa74641d604db66a39f7848693b98/lib/linguist/languages.yml#L826-L838

**Comment by lildude** [comment]
Ooo, I seem to recall noticing we were lacking a few comments a while back but then forgot to do anything about it 😊

`alias` should indeed be `aliases`.

Looks like the `lexer` entry was missed when removing the pygments dependency in https://github.com/github/linguist/pull/1707
