### ISSUE TITLE
Detecting wrong language in a python code with shebang

### ISSUE THREAD

**Issue by maane018** [github/linguist#4176]
I have written a python code. It has a shebang on the first line, which will determine the folder name and the environment dynamically, using awk, so that I don't need to change the shebang in every folder. 
Screenshot:
![screen shot 2018-06-26 at 3 19 30 pm](https://user-images.githubusercontent.com/11513835/41903876-a58e1b76-7954-11e8-8a1c-0ab60eff32dd.png)

### Detected language: Awk

Since, I am using Enterprise Github, I cannot paste the entire code.

**Comment by lildude** [comment]
Hmmm, this is a tricky one to automatically detect as your shebang is technically saying "use this shebang to run a bit of awk to determine the shebang to use for the rest of the file's content" so from the bit Linguist reads, this is really awk and it's being detected as such. 

In order for this to be automatically and reliably detected as python based on the result of the shebang, we'd need to somehow exec the shebang, which is never going to happen for various security, resource and other reasons.

The only options you really have are to use an [override to force these files to be Python(https://github.com/github/linguist#using-gitattributes) or use a [modeline in each file](https://github.com/github/linguist#using-emacs-or-vim-modelines) as the modeline strategy is used before the shebang strategy when analysing files.

https://github.com/github/linguist/blob/a5df9a00ab7c9828bd7038bb9f9bd5e56d325dc9/lib/linguist.rb#L59-L67

**Comment by maane018** [comment]
The first method (https://github.com/github/linguist#using-gitattributes) worked. Thanks.

**Comment by lildude** [comment]
Great!!
