### ISSUE TITLE
Correct per file detection, wrong overall percentage

### ISSUE THREAD

**Issue by tmeisel** [github/linguist#4177]
My private repository and the cli version of linguist are calculating a wrong percentage for each language used. Here is the output of linguist and the lines of code reported by GitHub for each file:

```
>>linguist --breakdown

55.52%  HTML
44.48%  Go

Go:
controller/baseController.go (64 lines (50 sloc)  1.13 KB)
controller/employeeController.go (142 lines (107 sloc)  3.15 KB)
main.go (65 lines (46 sloc)  1.3 KB)
model/directory.go (397 lines (302 sloc)  6.61 KB)
model/emloyee.go (43 lines (33 sloc)  649 Bytes)
model/person.go (41 lines (30 sloc)  680 Bytes)
server/logResponseWriter.go (55 lines (42 sloc)  1.1 KB)
server/server.go (145 lines (117 sloc)  2.87 KB)

HTML:
public/index.html (426 lines (397 sloc)  21.8 KB) 
```

While the index.html file might be the file with the most loc in the whole project, the accumulated percentage of go loc is way higher.
### URL of the affected repository:
github.com/tmeisel/optiopay (private, sorry!)

### Expected language:
Go

### Detected language:
HTML

**Comment by pchaigno** [comment]
Any reason why you removed part of the template for issues?

**Comment by tmeisel** [comment]
Sorry for that, was not sure if it was meant to be "double check" or "actually confirm". Anyhow, I did incl. local version (obviously) and all hints in the trouble shooting section do not apply to a wrong calculation of the overall percentage. Last modified would also not apply, as I'm explicitly also referring to the cli version (`v6.2.0`) of linguist.

**Comment by tmeisel** [comment]
I was just digging through closed issues and found #1434 with the explanation that file size matters instead of loc. With all due respect, I question this logic and would appreciate a brief explanation, why this strategy was chosen. While it leads to -at least- questionable results as above, I can not imagine a scenario, where loc > size would also lead to an abnormal result.

**Comment by pchaigno** [comment]
In the [*How Linguist Works*](https://github.com/github/linguist#how-linguist-works) section of the README, you'll find this sentence:

> The percentages are calculated based on the bytes of code for each language as reported by the List Languages API.

I recomputed the sum to be sure and the 55.52% HTML does correspond to the ratio of HTML files in file sizes (`21.8KB / sum_of_all_files`).

**Comment by pchaigno** [comment]
Who! A 1sec diff between our answers :-)

> With all due respect, I question this logic and would appreciate a brief explanation, why this strategy was chosen.

I agree that it's not perfect. Alternatives have been discussed before (#2139) but we haven't found a clearly better solution yet :/

> I can not imagine a scenario, where loc > size would also lead to an abnormal result.

For example: Assembly vs. C.

**Comment by tmeisel** [comment]
Thank you for the explanation. Reading through #2139 indicates a general consensus of HTML files being over-represented due to their size and that considering the number (in my case 1 html vs. 8 go files) would make sense. The [list at the end of the thread](https://github.com/github/linguist/pull/2139#issuecomment-75560215) seems to confirm that. Would it make sense to leave this issue open for a re-consideration? Otherwise, I would close it for now.

**Comment by pchaigno** [comment]
I don't think it's an issue we're going to address in the near future now that we have [overrides](https://github.com/github/linguist#overrides). In your case, you could use an override to mark the HTML file as either vendored or documentation, in which case it won't be counted in statistics.

**Comment by tmeisel** [comment]
Okay, I'll close it then. But since this file is neither a vendor file nor documentation, it is more of a work around with the downside of losing it in the stats.
