### ISSUE TITLE
Repo's owner has changed. Do i need to PR something with submodules?

### ISSUE THREAD

**Issue by nixel2007** [github/linguist#4180]
Hello!

Language 1C (BSL) repo was moved from xDrivenDevelopment org to 1c-syntax org.

https://github.com/1c-syntax/atom-language-1c-bsl.

https://github.com/xDrivenDevelopment/atom-language-1c-bsl link redirects to 1c-syntax org also.

Do I need to send a PR with updated submodule path?

**Comment by lildude** [comment]
> Do I need to send a PR with updated submodule path?

Yes please.

**Comment by pchaigno** [comment]
@nixel2007 Please follow [the guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#changing-the-source-of-a-syntax-highlighting-grammar), as the submodule path is not the only things that needs to be updated. The `add-grammar` script will take care of that for you.

**Comment by nixel2007** [comment]
Thanks! I'll send a PR soon.
