### ISSUE TITLE
Wrong language on my Jammming project

### ISSUE THREAD

**Issue by annech787** [github/linguist#4196]
Wrong language on my Jammming project

Javascript is not the language used to do the Jammming project.  It is React.  Please change the language to React.

Anne

**Comment by pchaigno** [comment]
Was there an issue with the template?

Are we writing about the same React? The JavaScript library?

**Comment by Alhadis** [comment]
Yes, she does. She's used the [`create-react-app`](https://github.com/facebook/create-react-app) module to generate her project's scaffolding (and the readme hasn't been modified, either...)

@annech787 It sounds like you're new to Web development, and you may not be aware that React *is* JavaScript. Granted, it adds some syntactic sugar that allows XML tags to be used instead JavaScript source code, but React is still just JavaScript.

React is just one of many thousands of libraries and frameworks that people have written in JavaScript. It may be slightly confusing for a newcomer to be taught to use React before they understand how it relates to the underlying browser languages (JS, CSS, and HTML).

**Comment by annech787** [comment]
Yes, it is React.

**Comment by Alhadis** [comment]
There you have it. React isn't a language, so the current language classification of JavaScript is therefore correct.

On another note, next time please fill out the issue template that @pchaigno asked about. It's there to help you as much as it helps us.

**Comment by KyleXie** [comment]
Vue is similar with React, why Vue is a separate language in github linguist?

**Comment by lildude** [comment]
Vue in Linguist is only targetting the HTML/markup side of things with the `.vue` extension:

https://github.com/github/linguist/blob/1b4993f2a091c9177658ef3cb6c719f5b5eaa6d7/lib/linguist/languages.yml#L5549-L5556

The Javascript files will still be classified as Javascript.

**Comment by KyleXie** [comment]
@lildude That makes sense. Thanks for you reply.
