### ISSUE TITLE
I am very new to python and I am trying to install the linguist package to my python virtual enviroment. I got this error "python setup.py egg_info" failed with error code 1. 

### ISSUE THREAD

**Issue by IlyasAzeem** [github/linguist#4197]
I have created a virtual environment using Annaconda. I am using python 2.7 and my operating system is windows 7. I searched for this issue, some suggested to upgrade setuptools, mine is already upgraded version but still not working. Kindly help me. 
![linguisterror](https://user-images.githubusercontent.com/22872324/42809107-5eb7912a-89e7-11e8-89d3-bbdf5d0101e2.png)

## Preliminary Steps

Please confirm you have...
- [ ] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [ ] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [ ] considered implementing an [override](https://github.com/github/linguist#overrides),
- [ ] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

**Comment by pchaigno** [comment]
Linguist is not a Python package, it's a Ruby gem. You'll need a working Ruby environment to install it. I don't know if anyone already tried to install Linguist on Windows.

**Comment by Alhadis** [comment]
@IlyasAzeem You're better off filing this issue at the appropriate repository: https://github.com/douban/linguist

I wonder how many other languages Linguist has been ported to...

**Comment by IlyasAzeem** [comment]
Thank you dear @Alhadis  Sorry for the mistake

**Comment by IlyasAzeem** [comment]
As I have asked a question in wrong place, therefore I am closing this issue
