### ISSUE TITLE
Syntax highlighting for Elixir is broken

### ISSUE THREAD

**Issue by michalmuskala** [github/linguist#4203]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

It seems that all files written in the Elixir programming language (file extensions `.ex` and `.exs`) lost syntax highlighting. This is something very recent.

### URL of the affected repository: 
https://github.com/elixir-lang/elixir and all repositories using Elixir programming language

### Last modified on:

2018-07-20, 10:48 CEST

### Expected language: 

Elixir

### Detected language: 

Elixir but without syntax highlightng

**Comment by nixel2007** [comment]
@michalmuskala we use atom-grammar-test https://www.npmjs.com/package/atom-grammar-test
You need to write simple boilerblate spec for atom and a set of grammar-specs.
See a real project here - spec - https://github.com/1c-syntax/1c-syntax/blob/master/spec/language-1s-bsl-spec.coffee
grammar-spec (one of them) - https://github.com/1c-syntax/1c-syntax/blob/master/spec/fixtures/grammar/syntax_test_bsl.bsl

**Comment by pchaigno** [comment]
@michalmuskala I can only recommend @nixel2007's suggestion of writing tests with the grammar. We also have some tests when compiling grammars in Linguist, but it's currently difficult to distinguish actual issues from other warnings due to the high number of warnings (cf. #3924). If you know another Elixir grammar with tests and equivalent support for the syntax, we could switch to it.

**Comment by lildude** [comment]
Linguist 6.3.1 is now live and all the Elixir files are pretty again. 🌈🌈🌈
