### ISSUE TITLE
.FTL files are identified as FreeMarker, even when they are actually Fluent

### ISSUE THREAD

**Issue by MikkCZ** [github/linguist#4206]
The [Fluent](https://projectfluent.org/) localization format by Mozilla uses `.ftl` suffix for filenames. That's the same as FreeMarker. The current FreeMarker detection probably works only based on the file suffix, not the actual file content, so all localization files in the Fluent format are detected by GitHub as FreeMarkes files (example [https://github.com/MozillaCZ/l10n-mozilla-central-cs/search?l=freemarker](here)). If there is an existing detector using the actual file content besides the suffix, someone can point me to, I am interested in adding support for Fluent.

CC @stasm.

## Preliminary Steps

Please confirm you have...
- [ ] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [ ] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [ ] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

### URL of the affected repository:
https://github.com/MozillaCZ/l10n-mozilla-central-cs

### Last modified on:
2018-07-22

### Expected language:
Fluent

### Detected language:
FreeMarker

**Comment by lildude** [comment]
You’re pretty much spot on. The only language associated with the `.ftl` extension is indeed FreeMarker… 

https://github.com/github/linguist/blob/73972dcf591310295052834274941cdd801e6622/lib/linguist/languages.yml#L1389-L1398

In order for Fluent to be recognised, you’ll need to open a PR to add the language and extension, and as there is already a `.ftl` extension, a heuristic is needed to differentiate the two too. You can find full details on how to add a language in [Adding a Language](
https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). Please note the usage requirement: we will not merge a PR that doesn’t meet this requirement.

**Comment by MikkCZ** [comment]
AFAIK only Mozilla uses Fluent for now, which can be ~40 repositories. I will try the override for my specific case and wait for wider Fluent adoption. ;)

**Comment by alerque** [comment]
@pchaigno or other collaborators, can we please re-open this issue? Fluent is not just a Mozilla thing any more, their internal usage has turned into a [well received spec](https://github.com/projectfluent) with language implementations for Rust, Javascript, React, Python, Perl, C#, Lua, Handlebars templates, and more. I came here to open an issue because my FTL files are reporting the wrong types and to look into what it would take to fix it. I'd rather not open a new issue, but this one should definitely be re-opened until a satisfactory detection is made.

**Comment by lildude** [comment]
>  I'd rather not open a new issue, but this one should definitely be re-opened until a satisfactory detection is made.

Re-opening an issue won't solve the problem and it'll probably go stale 😉.

Linguist is a community driven project as there's no way the three primary maintainers could ever know enough about every language out there to add support ourselves so a PR adding support is the best option (We don't need an issue for a PR).

**Comment by sandalwoodbox** [comment]
I ran into this as well and opened a new issue to track it. It looks like there's now a process for opening tickets to add language support. If folks who commented on this ticket want to upvote the new one, it's at https://github.com/github/linguist/issues/5340.

**Comment by Mailaender** [comment]
@OpenRA is in to process of using it as well. Is there anything that can be used to descriminate FreeMarker from Fluent `*.ftl`? The wrong syntax highlight of https://github.com/blushingpenguin/Fluent.Net/blob/master/Fluent.Net.Test/fixtures/full_reference/variant_lists.ftl already looks kinda plausible.

**Comment by alerque** [comment]
@Mailaender The file & repository you linked to was last updated *before* Fluent support was merged into linguist. GitHub does not update old repositories based on new language syntax rules until there are changes. Pushing a new commit (with any content) to the repository should trigger a re-read that should classify the file correctly.
