### ISSUE TITLE
JavaScript project (BS4, jQuery plugin) identified as 100% HTML

### ISSUE THREAD

**Issue by shaack** [github/linguist#4214]
I am not shure why, but my project https://github.com/shaack/bootstrap-show-modal is identified as **HTML 100%**. Why is the `src/bootstrap-show-modal.js` ignored?

### URL of the affected repository:

https://github.com/shaack/bootstrap-show-modal

### Last modified on:
Today

### Expected language:
JavaScript

### Detected language:
HTML 100%

**Comment by pchaigno** [comment]
The `src/bootstrap-show-modal.js` file is detected as vendored [because of its name](https://github.com/github/linguist/blob/f9ca0dc683986359c7d708ed22257f6d9072d60a/lib/linguist/vendor.yml#L61). You can change that behavior with Linguist overrides.

**Comment by shaack** [comment]
Ahh, ok, thanks for the fast support!
