### ISSUE TITLE
Extension popularity monitoring

### ISSUE THREAD

**Issue by pchaigno** [github/linguist#4219]
I'm opening this issue to track the popularity of submitted file extensions (pull requests with the label `Pending Popularity`). I've used [Harvester](https://github.com/Alhadis/Harvester) to count the number of repositories for all extensions where it makes sense (i.e., if the number of files is below 200 we already know there won't be hundreds of repositories as required). All numbers were updated today, in the last few hours.

I'll update the numbers in a few months and will probably stop counting for extensions whose number of repositories stagnated or reduced.

Extension | PR | Files | Repo. | Date | +/- at Feb. 21
---|---|---|---|---|---
[~~`.mxl`~~](https://github.com/search?p=3&q=extension%3Amxl+www.musicxml.org&type=Code&utf8=%E2%9C%93) | #3651 | 106 | - | Aug. 4 18 | +0 files
[~~`.exw`~~](https://github.com/search?q=extension%3Aexw+NOT+djfhdjfjd) | #3754 | 618 | 41 | Aug. 4 18 | +8 repo.
[~~`.exu`~~](https://github.com/search?q=extension%3Aexu+NOT+djfhdjfjd) | #3754 | 54 | - | Aug. 4 18 | +4 files
[~~`.sarl`~~](https://github.com/search?utf8=%E2%9C%93&q=extension%3Asarl+io.sarl.lang.core&type=Code) | #3772 | 252 | 49 | Aug. 4 18 | +5 repo.
[~~`.hsig`~~](https://github.com/search?q=extension%3Ahsig+NOT+dkfjdfh) | #3855 | 459 | 64 | Aug. 4 18 | +21 repo.
[~~`.imba`~~](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aimba+NOT+djfhdjfdj&type=) | #3869 | 611 | 58 | Aug. 4 18 | +57 repo.
[~~`.coco`~~](https://github.com/search?utf8=%E2%9C%93&q=extension%3Acoco+NOT+nothack&type=Code) | #3872 | 641 | 79 | Aug. 4 18 | +11 repo.
[~~`.pbf`~~](https://github.com/search?utf8=%E2%9C%93&q=extension%3Apbf+Event+NOT+nothack&type=Code) | #3926 | 62 | - | Aug. 4 18 | +0 files
[~~`.pbp`~~](https://github.com/search?utf8=%E2%9C%93&q=extension%3Apbp+xml+NOT+nothack&type=Code) | #3926 | 133 | - | Aug. 4 18 | +11 files
[~~`.smk`~~](https://github.com/search?q=extension%3Asmk+NOT+djfhdjf) | #3953 | 1k | 157 | Aug. 4 18 | +76 repo.
[~~`.zig`~~](https://github.com/search?utf8=%E2%9C%93&q=import+extension%3Azig&type=Code) | #4005 | 904 | 80 | Aug. 4 18 | +144 repo.
[~~`.rho`~~](https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Arho+contract+NOT+nothack) | #4071 | 222 | 19 | Aug. 4 18 | +33 repo.
[~~`.wren`~~](https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Awren+wren+NOT+nothack) | #4088 | 112 | - | Aug. 4 18 | +110 files, 55 repo.
[~~`.archimate`~~](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aarchimate+NOT+nothack&type=Code) | #4128 | 581 | 258 | Aug. 4 18 | +49 repo.
[~~`.varlink`~~](https://github.com/search?utf8=%E2%9C%93&q=extension%3Avarlink+NOT+notahack) | #4164 | 43 | - | Aug. 4 18 | +5 files
[~~`.pq`~~](https://github.com/search?q=extension%3Apq+NOT+TOPSRC+NOT+include+NOT+gnuplot+NOT+define&type=Code) | #4191 | 701 | 147 | Aug. 4 18 | +24 repo.
[~~`.pqm`~~](https://github.com/search?q=extension:pqm+NOT+nothack&type=Code) | #4191 | 51 | - | Aug. 4 18 | +26 files
[~~`.m`~~](https://github.com/search?q=extension%3Am+Source+Table+let+in+NOT+%22%23import%22+NOT+%22func%22+NOT+%22%23include%22+created%3A%3E2015-01-01+NOT+tableView+-language%3AMatlab+-language%3AM+-language%3AMathematica&type=Code) | #4191 | 84 | - | Aug. 4 18 | -19 files
[~~`.asx`~~](https://github.com/search?p=1&q=extension%3Aasx+equ+OR+dta&type=Code) | #4193 | 706 | 122 | Aug. 4 18 | +5 repo.
[~~`.jsonnet`~~](https://github.com/search?q=extension%3Ajsonnet+NOT+djfhdjfhdhf) | #2653 | 7k | 93 | Oct. 3 18 | +18 repo.
[~~`.htmlx`~~](https://github.com/search?q=extension%3Ahtmlx+export+default&type=Code) | #4323 | 5 | - | Nov. 14 18 | +0 files
[~~`.rego`~~](https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Arego+package+NOT+nothack) | #4371 | 296 | 80 | Jan. 20 19 | -
[~~`cabal-ghcjs.project`~~](https://github.com/search?q=filename%3Acabal-ghcjs.project&type=Code) | #4419 | 71 | 70 | Mar. 3 19 | -
[~~`.asddls`~~](https://github.com/search?q=extension%3Aasddls+NOT+jfhdjfhdjf&type=Code) | #4614 | 804 | 109 | Aug. 31 19 | +140 repos.
[`.daml`](https://github.com/search?q=extension%3Adaml+nonconsuming) | #4523 | 155 | 37 | Aug. 31 19 | +122 repo.
[`.aplf`](https://github.com/search?q=extension%3Aaplf+NOT+dkfjdfhdjffjdj) | #4526 | 2709 | 33 | Aug. 31 19 | +16 repo.
[`.carp`](https://github.com/search?p=1&q=extension%3Acarp+NOT+nothack&type=Code) | #4530 | 362 | 75 | Aug. 31 19 | +466 files. -4 repo *.
[`.scilla`](https://github.com/search?q=extension%3Ascilla+NOT+nothack) | #4635 | 559 | 61 | Sept. 15 19 | +21 repo.
[~~`.raku`~~](https://github.com/search?p=1&q=extension%3Araku+NOT+nothack&type=Code) | #4731 | 74 | 29 | Jan. 7 20 | -
[~~`.rakumod`~~](https://github.com/search?p=1&q=extension%3Arakumod+NOT+nothack&type=Code) | #5168 | 200 | 9 | Jan. 7 20 | +259 repo.
[`.curry`](https://github.com/search?q=extension%3Acurry+NOT+nothack&type=Code) | #5111 | 4437 | 56 | Jan. 6 21 | +403 files, -18 repo *.
[`.ispc`](https://github.com/search?p=1&q=extension%3Aispc+NOT+nothack&type=Code) | #5191 | 6790 | 142 | 9 Feb. 21 | -
[`.isph`](https://github.com/search?p=1&q=extension%3Aisph+NOT+nothack&type=Code) | #5191 | 3074 | 158 | 9 Feb. 21 | -
[`.hla`](https://github.com/search?p=1&q=extension%3Ahla+NOT+nothack&type=Code) | #5194  | 12618 | 71 | 9 Feb. 21 | -

Please avoid discussing issues with specific extensions (such as an improved search query) here and prefer the associated pull request.

\* GitHub's search indexing [changed at the end of 2020 to only index repositories active in the last year](https://github.blog/changelog/2020-12-17-changes-to-code-search-indexing/). A decrease in repositories indicates less activity and a potential decrease in overall popularity.

**Comment by andrewrk** [comment]
What's the acceptance criteria? archimate has over 200 repositories and yet it's in this list with its PR closed.

**Comment by tajmone** [comment]
Excellent idea @pchaigno! And very useful too.

Thanks.

**Comment by mattmasson** [comment]
@pchaigno thanks for doing this! 

Can we remove the .m file extension from consideration for #4191 then? The code change only includes .pq and .pqm file support (specifically because we didn't want to conflict with the existing .m file highlighters). I think .m was mentioned in the PR comments because that was our old convention (and no longer used).

**Comment by andrewrk** [comment]
Zig update - nov 4, 2018 - 1547 files, 151 repos

**Comment by andrewrk** [comment]
Hello @pchaigno 

I have just run harvester on Zig extension and came up with these results:
 * 1861 files
 * 203 repos
 * 93 unique users

https://gist.github.com/andrewrk/33650712e74a65873dd84d82d25f449a

It is time to re-open #4005

**Comment by pchaigno** [comment]
It's been five and a half months. I've update the numbers in the initial post with new counts from today. Those numbers are also below, with the decisions I think we should take as a consequence concerning support of these extensions in Linguist. The three codes for decisions are:
- Drop: I think we should stop monitoring adoption for that extension as it's growing too slowly. Of course, it doesn't mean we'll never add it to Linguist.
- Accept: I think that extension has achieved a high enough adoption to mandate support in Linguist.
- Wait: Adoption is growing and I think we should wait for another ~6 months and see then.

@lildude @Alhadis Could you take a look? If you agree with the "Decisions", I'll post an update for the *accept* on their original pull requests.

Extension | PR | Initial adoption | +/- at Jan. 20 | Decision?
---|---|---|---|---
[`.mxl`](https://github.com/search?p=3&q=extension%3Amxl+www.musicxml.org&type=Code&utf8=%E2%9C%93) | #3651 | 106 files | +0 files | Drop
[`.exw`](https://github.com/search?q=extension%3Aexw+NOT+djfhdjfjd) | #3754 | 41 repo. | +8 repo. | Drop
[`.exu`](https://github.com/search?q=extension%3Aexu+NOT+djfhdjfjd) | #3754 | 54 files | +4 files | Drop
[`.sarl`](https://github.com/search?utf8=%E2%9C%93&q=extension%3Asarl+io.sarl.lang.core&type=Code) | #3772 | 49 repo. | +5 repo. | Drop
[`.hsig`](https://github.com/search?q=extension%3Ahsig+NOT+dkfjdfh) | #3855 | 64 repo. | +21 repo. | Wait
[`.imba`](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aimba+NOT+djfhdjfdj&type=) | #3869 | 58 repo. | +57 repo. | Wait
[`.coco`](https://github.com/search?utf8=%E2%9C%93&q=extension%3Acoco+NOT+nothack&type=Code) | #3872 | 79 repo. | +11 repo. | Wait
[`.pbf`](https://github.com/search?utf8=%E2%9C%93&q=extension%3Apbf+Event+NOT+nothack&type=Code) | #3926 | 62 files | +0 files | Drop
[`.pbp`](https://github.com/search?utf8=%E2%9C%93&q=extension%3Apbp+xml+NOT+nothack&type=Code) | #3926 | 133 files | +11 files | Drop
[`.smk`](https://github.com/search?q=extension%3Asmk+NOT+djfhdjf) | #3953 | 157 repo. | +76 repo. | Wait
[`.zig`](https://github.com/search?utf8=%E2%9C%93&q=import+extension%3Azig&type=Code) | #4005 | 80 repo. | +144 repo. | Accept*
[`.rho`](https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Arho+contract+NOT+nothack) | #4071 | 19 repo. | +33 repo. | Wait
[`.wren`](https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Awren+wren+NOT+nothack) | #4088 | 112 files | +110 files, 55 repo. | Wait
[`.archimate`](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aarchimate+NOT+nothack&type=Code) | #4128 | 258 repo. | +49 repo. | Accept
[`.varlink`](https://github.com/search?utf8=%E2%9C%93&q=extension%3Avarlink+NOT+notahack) | #4164 | 43 files | +5 files | Drop
[`.pq`](https://github.com/search?q=extension%3Apq+NOT+TOPSRC+NOT+include+NOT+gnuplot+NOT+define&type=Code) | #4191 | 147 repo. | +24 repo. | Wait
[`.pqm`](https://github.com/search?q=extension:pqm+NOT+nothack&type=Code) | #4191 | 51 files | +26 files | Drop
[`.m`](https://github.com/search?q=extension%3Am+Source+Table+let+in+NOT+%22%23import%22+NOT+%22func%22+NOT+%22%23include%22+created%3A%3E2015-01-01+NOT+tableView+-language%3AMatlab+-language%3AM+-language%3AMathematica&type=Code) | #4191 | 84 files | -19 files | Drop
[`.asx`](https://github.com/search?p=1&q=extension%3Aasx+equ+OR+dta&type=Code) | #4193 | 122 repo. | +43 files | Wait
[`.jsonnet`](https://github.com/search?q=extension%3Ajsonnet+NOT+djfhdjfhdhf) | #2653 | 93 repo. | +18 repo. | Accept**
[`.htmlx`](https://github.com/search?q=extension%3Ahtmlx+export+default&type=Code) | #4323 | 5 files | +0 files | Drop

\* Support for the `.zig` extension was already merged.
** That is 93 and 111 repositories among those I downloaded. I downloaded about 2k among the 7/11k `.jsonnet` files. I might be missing something here, but I don't see why we didn't add that extension 6 months ago...

**Comment by Alhadis** [comment]
Sounds like a reasonable approach to me. 👍 I say go for it.

**Comment by pchaigno** [comment]
@lildude Could you take a look to the above please?

**Comment by lildude** [comment]
> Could you take a look to the above please?

Only if you take a look at https://github.com/github-linguist/babel-sublime/pull/1 😜

>  If you agree with the "Decisions", I'll post an update for the _accept_ on their original pull requests.

Make sense to me. 👍 go for it.

**Comment by pchaigno** [comment]
> > Could you take a look to the above please?
> 
> Only if you take a look at [github-linguist/babel-sublime#1](https://github.com/github-linguist/babel-sublime/pull/1) 

Ah, sorry! I'm not sure how I did not see this...

**Comment by hellerve** [comment]
Little nitpick in the original list: the Carp PR was #4530, not #4526 (which was APL) :)

**Comment by pchaigno** [comment]
@hellerve Ah, thanks! I forgot to change from the previous line.

**Comment by tsandall** [comment]
@pchaigno any chance you could review the numbers for #4371 again? We've watched sustained growth over the past 8-9 months when it was originally raised. I believe there are over 200 repos now.

**Comment by pchaigno** [comment]
I ran the numbers again, after 8 months. **+/- Sept. 13** corresponds to the delta since the last count (in January for most extensions).

As a reminder, the three codes for decisions are:
- Drop: I think we should stop monitoring adoption for that extension as it's growing too slowly. Of course, it doesn't mean we'll never add it to Linguist.
- Accept: I think that extension has achieved a high enough adoption to mandate support in Linguist.
- Wait: Adoption is growing and I think we should wait for another ~6 months and see then.

Extension | PR | Initial adoption | +/- Jan. 20 | +/- Sept. 13 | Decision?
---|---|---|---|---|---
[`.hsig`](https://github.com/search?q=extension%3Ahsig+NOT+dkfjdfh) | #3855 | 64 repo. | +21 repo. | +17  repo. | Drop
[`.imba`](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aimba+NOT+djfhdjfdj&type=) | #3869 | 58 repo. | +57 repo. | +50 repo. | Drop*
[`.coco`](https://github.com/search?utf8=%E2%9C%93&q=extension%3Acoco+NOT+nothack&type=Code) | #3872 | 79 repo. | +11 repo. | +21 repo. | Drop
[`.smk`](https://github.com/search?q=extension%3Asmk+NOT+djfhdjf) | #3953 | 157 repo. | +76 repo. | +107 repo. | Accept
[`.rho`](https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Arho+contract+NOT+nothack) | #4071 | 19 repo. | +33 repo. | +9 repo. | Drop
[`.wren`](https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Awren+wren+NOT+nothack) | #4088 | 112 files | +110 files, 55 repo. | +1 repo. | Drop
[`.pq`](https://github.com/search?q=extension%3Apq+NOT+TOPSRC+NOT+include+NOT+gnuplot+NOT+define&type=Code) | #4191 | 147 repo. | +24 repo. | +60 repo. | Accept
[`.rego`](https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Arego+package+NOT+nothack) | #4371 | 80 | - | +137 | Accept
[`cabal-ghcjs.project`](https://github.com/search?q=filename%3Acabal-ghcjs.project&type=Code) | #4419 | 70 repo. | - | +18 repo. | Drop

\* I hesitated between Wait (again) and Drop for the `.imba` file extension. Since adoption is slowing down (+50 in 8 months compared to +57 in 5.5 months before) I lean toward dropping the extension. It doesn't mean we won't reconsider it in the future of course.

@lildude @Alhadis Could you take a look? If you agree with the "Decisions", I'll post an update for the accept on their original pull requests.

**Comment by lildude** [comment]
> @lildude @Alhadis Could you take a look? If you agree with the "Decisions", I'll post an update for the accept on their original pull requests.

👍 from me on all your decisions.

**Comment by Alhadis** [comment]
Sorry @pchaigno, missed your /cc. 👍  from me too.

**Comment by Grinnz** [comment]
FYI, running Harvester on the given searches now shows about 78 repositories for each of .raku and .rakumod.

**Comment by xfix** [comment]
Could `.rakutest` be added to extension tracking? It initially wasn't, because it was used by "7 files, 3 repos, 3 users" (which is not surprising, as at that time Raku test framework did not support `.rakutest` extension).

**Comment by pchaigno** [comment]
@xfix It looks like `.rakutest` is still only used by a handful of users. The purpose of this issue is to track usage for extensions that we expect to reach our threshold soon. It doesn't look like that's the case for `.rakutest`. Don't hesitate to ping me if that changes.

**Comment by stefanobaghino** [comment]
Update on `.daml` (#4523) as of 2020.04.24:
- 2210 unique files (+155 compared to 2019.08.31)
- 180 unique repositories (+37 compared to 2019.08.31)

Ran Harvester with `extension:daml`.

Raw data: https://gist.github.com/stefanobaghino/6439072413623b0a9b05aabeaeebb4e6

Unique repository count method
```
cat daml.txt | awk -F '/' '{print $1 "//www.github.com/" $4 "/" $5 }' | sort -u | wc -l
```

Disclaimer: with my private account @stefanobaghino-da, I'm a member of @digital-asset, which is the author of the DAML language. I ran Harvester with my private account (the one I'm using right now) to exclude private repositories.

**Comment by stefanobaghino** [comment]
It looks like the main conflict of the `.daml` extension is an XML format using in geospatial processing. I'll look if I can use this fact to produce a more accurate result. I'll gladly take suggestions if you have any. :slightly_smiling_face:

**Comment by Alhadis** [comment]
@pchaigno I've added `.curry` to the list. Just an FYI in case you need to update any extension lists locally.

@lildude Could we pin this issue?

**Comment by lildude** [comment]
> @lildude Could we pin this issue?

✅ Done.

**Comment by Nixinova** [comment]
Can all of the entries be updated? Its been a year.

**Comment by BenStigsen** [comment]
I'd like this as well, specifically Wren support.

**Comment by Ganesha2282882** [comment]
#5377

**Comment by xfix** [comment]
Could `.rakutest` be added to extension tracking? It has 584 files.

**Comment by timo-cmd2** [comment]
Hi 👋🏻

How can we add a language to the pending popularity section?

**Comment by lildude** [comment]
> How can we add a language to the pending popularity section?

Languages are normally added when a PR is opened that doesn't quite yet meet the documented usage requirements, though we've not really been maintaining this list much as PRs no longer auto-close.

**Comment by Pakon2543** [comment]
> I'm opening this issue to track the popularity of submitted file extensions (pull requests with the label `Pending Popularity`). I've used [Harvester](https://github.com/Alhadis/Harvester) to count the number of repositories for all extensions where it makes sense (i.e., if the number of files is below 200 we already know there won't be hundreds of repositories as required). All numbers were updated today, in the last few hours.
> 
> I'll update the numbers in a few months and will probably stop counting for extensions whose number of repositories stagnated or reduced.
> 
> Extension	PR	Files	Repo.	Date	+/- at Feb. 21
> [~`.mxl`~](https://github.com/search?p=3&q=extension%3Amxl+www.musicxml.org&type=Code&utf8=%E2%9C%93)	#3651	106	-	Aug. 4 18	+0 files
> [~`.exw`~](https://github.com/search?q=extension%3Aexw+NOT+djfhdjfjd)	#3754	618	41	Aug. 4 18	+8 repo.
> [~`.exu`~](https://github.com/search?q=extension%3Aexu+NOT+djfhdjfjd)	#3754	54	-	Aug. 4 18	+4 files
> [~`.sarl`~](https://github.com/search?utf8=%E2%9C%93&q=extension%3Asarl+io.sarl.lang.core&type=Code)	#3772	252	49	Aug. 4 18	+5 repo.
> [~`.hsig`~](https://github.com/search?q=extension%3Ahsig+NOT+dkfjdfh)	#3855	459	64	Aug. 4 18	+21 repo.
> [~`.imba`~](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aimba+NOT+djfhdjfdj&type=)	#3869	611	58	Aug. 4 18	+57 repo.
> [~`.coco`~](https://github.com/search?utf8=%E2%9C%93&q=extension%3Acoco+NOT+nothack&type=Code)	#3872	641	79	Aug. 4 18	+11 repo.
> [~`.pbf`~](https://github.com/search?utf8=%E2%9C%93&q=extension%3Apbf+Event+NOT+nothack&type=Code)	#3926	62	-	Aug. 4 18	+0 files
> [~`.pbp`~](https://github.com/search?utf8=%E2%9C%93&q=extension%3Apbp+xml+NOT+nothack&type=Code)	#3926	133	-	Aug. 4 18	+11 files
> [~`.smk`~](https://github.com/search?q=extension%3Asmk+NOT+djfhdjf)	#3953	1k	157	Aug. 4 18	+76 repo.
> [~`.zig`~](https://github.com/search?utf8=%E2%9C%93&q=import+extension%3Azig&type=Code)	#4005	904	80	Aug. 4 18	+144 repo.
> [~`.rho`~](https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Arho+contract+NOT+nothack)	#4071	222	19	Aug. 4 18	+33 repo.
> [~`.wren`~](https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Awren+wren+NOT+nothack)	#4088	112	-	Aug. 4 18	+110 files, 55 repo.
> [~`.archimate`~](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aarchimate+NOT+nothack&type=Code)	#4128	581	258	Aug. 4 18	+49 repo.
> [~`.varlink`~](https://github.com/search?utf8=%E2%9C%93&q=extension%3Avarlink+NOT+notahack)	#4164	43	-	Aug. 4 18	+5 files
> [~`.pq`~](https://github.com/search?q=extension%3Apq+NOT+TOPSRC+NOT+include+NOT+gnuplot+NOT+define&type=Code)	#4191	701	147	Aug. 4 18	+24 repo.
> [~`.pqm`~](https://github.com/search?q=extension:pqm+NOT+nothack&type=Code)	#4191	51	-	Aug. 4 18	+26 files
> [~`.m`~](https://github.com/search?q=extension%3Am+Source+Table+let+in+NOT+%22%23import%22+NOT+%22func%22+NOT+%22%23include%22+created%3A%3E2015-01-01+NOT+tableView+-language%3AMatlab+-language%3AM+-language%3AMathematica&type=Code)	#4191	84	-	Aug. 4 18	-19 files
> [~`.asx`~](https://github.com/search?p=1&q=extension%3Aasx+equ+OR+dta&type=Code)	#4193	706	122	Aug. 4 18	+5 repo.
> [~`.jsonnet`~](https://github.com/search?q=extension%3Ajsonnet+NOT+djfhdjfhdhf)	#2653	7k	93	Oct. 3 18	+18 repo.
> [~`.htmlx`~](https://github.com/search?q=extension%3Ahtmlx+export+default&type=Code)	#4323	5	-	Nov. 14 18	+0 files
> [~`.rego`~](https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Arego+package+NOT+nothack)	#4371	296	80	Jan. 20 19	-
> [~`cabal-ghcjs.project`~](https://github.com/search?q=filename%3Acabal-ghcjs.project&type=Code)	#4419	71	70	Mar. 3 19	-
> [~`.asddls`~](https://github.com/search?q=extension%3Aasddls+NOT+jfhdjfhdjf&type=Code)	#4614	804	109	Aug. 31 19	+140 repos.
> [`.daml`](https://github.com/search?q=extension%3Adaml+nonconsuming)	#4523	155	37	Aug. 31 19	+122 repo.
> [`.aplf`](https://github.com/search?q=extension%3Aaplf+NOT+dkfjdfhdjffjdj)	#4526	2709	33	Aug. 31 19	+16 repo.
> [`.carp`](https://github.com/search?p=1&q=extension%3Acarp+NOT+nothack&type=Code)	#4530	362	75	Aug. 31 19	+466 files. -4 repo *.
> [`.scilla`](https://github.com/search?q=extension%3Ascilla+NOT+nothack)	#4635	559	61	Sept. 15 19	+21 repo.
> [~`.raku`~](https://github.com/search?p=1&q=extension%3Araku+NOT+nothack&type=Code)	#4731	74	29	Jan. 7 20	-
> [~`.rakumod`~](https://github.com/search?p=1&q=extension%3Arakumod+NOT+nothack&type=Code)	#5168	200	9	Jan. 7 20	+259 repo.
> [`.curry`](https://github.com/search?q=extension%3Acurry+NOT+nothack&type=Code)	#5111	4437	56	Jan. 6 21	+403 files, -18 repo *.
> [`.ispc`](https://github.com/search?p=1&q=extension%3Aispc+NOT+nothack&type=Code)	#5191	6790	142	9 Feb. 21	-
> [`.isph`](https://github.com/search?p=1&q=extension%3Aisph+NOT+nothack&type=Code)	#5191	3074	158	9 Feb. 21	-
> [`.hla`](https://github.com/search?p=1&q=extension%3Ahla+NOT+nothack&type=Code)	#5194	12618	71	9 Feb. 21	-
> Please avoid discussing issues with specific extensions (such as an improved search query) here and prefer the associated pull request.
> 
> * GitHub's search indexing [changed at the end of 2020 to only index repositories active in the last year](https://github.blog/changelog/2020-12-17-changes-to-code-search-indexing/). A decrease in repositories indicates less activity and a potential decrease in overall popularity.

**Comment by stefanobaghino** [comment]
@lildude I would be interested in having a look if Daml now meets the popularity requirements, should I report my findings back in https://github.com/github/linguist/pull/4523 and re-open or open a new one?

**Comment by lildude** [comment]
> @lildude I would be interested in having a look if Daml now meets the popularity requirements, should I report my findings back in #4523 and re-open or open a new one?

That PR is over three years old, so it's probably best to start a new PR, though from a quick look... usage is still incredibly low with only [698 files](https://github.com/search?q=path%3A*.daml+&type=code) which is still waaaay too low.

**Comment by stefanobaghino-da** [comment]
Thanks for checking that! By the way the query you linked actually returns an empty result to me. Is that `path:` kind of search limited to internal usage at Github or something like that?

**Comment by lildude** [comment]
> Thanks for checking that! By the way the query you linked actually returns an empty result to me. Is that `path:` kind of search limited to internal usage at Github or something like that?

Nope. It's the new [Codesearch beta](https://github.com/features/code-search)

**Comment by stefanobaghino** [comment]
> That PR is over three years old, so it's probably best to start a new PR, though from a quick look... usage is still incredibly low with only [698 files](https://github.com/search?q=path%3A*.daml+&type=code) which is still waaaay too low.

I finally got access to Codesearch. How did you get that number? Clicking on your query (which accounts for a similarly named XML-based configuration format) I get ~5.9K results and scoping it down to include a couple of keywords ([like so](https://github.com/search?q=path%3A*.daml+template+where&type=code)) narrows it down to ~2.9K.

Do you have a rough figure with regards to the expected numbers to include the language in Linguist?

**Comment by lildude** [comment]
> I finally got access to Codesearch. How did you get that number?

It is what was returned at the time. It's certainly possible there are more files returned now as the Codesearch beta has been expanding and indexing more and more files.

> Do you have a rough figure with regards to the expected numbers to include the language in Linguist?

This is documented in the CONTRIBUTING.md file.

From a quick look at the results, it looks like support can be added so feel free to open a new PR. You're going to need to add support to XML for this extension as the same time in the same PR too (it looks popular enough too as it appears to be about one per repo) to ensure they remain being classified as XML with the correct syntax highlighting.

**Comment by stefanobaghino-da** [comment]
> From a quick look at the results, it looks like support can be added so feel free to open a new PR. You're going to need to add support to XML for this extension as the same time in the same PR too (it looks popular enough too as it appears to be about one per repo) to ensure they remain being classified as XML with the correct syntax highlighting.

To clarify, while an XML-based configuration format with the same name exists, the `daml` I'm talking about is a Haskell dialect. 🙂

**Comment by lildude** [comment]
> To clarify, while an XML-based configuration format with the same name exists, the `daml` I'm talking about is a Haskell dialect. 🙂

Yup, but as there are clearly two different languages using the same extension, you will need to add support for both at the same time else they'll all be classified as the one language you add, in this case the Haskell dialect, which won't be correct for the XML files. Think about it the other way, you wouldn't want all the Haskell dialect `.daml` files to be classified as XML which they would be if the extension were only added to XML.

**Comment by stefanobaghino-da** [comment]
> Yup, but as there are clearly two different languages using the same extension, you will need to add support for both at the same time else they'll all be classified as the one language you add, in this case the Haskell dialect, which won't be correct for the XML files. Think about it the other way, you wouldn't want all the Haskell dialect `.daml` files to be classified as XML which they would be if the extension were only added to XML.

Got it, thanks.
