### ISSUE TITLE
Java language highlighting is not maintained anymore

### ISSUE THREAD

**Issue by michihausheer** [github/linguist#4228]
The https://github.com/textmate/java.tmbundle project that provides java highlight support isn't maintained anymore it seems.
There is an issue regarding module-info.java highlight support that is open for more than a year now (https://github.com/textmate/java.tmbundle/issues/47, also mentioned in #3566).

**Comment by pchaigno** [comment]
It's probably still maintained, but [Michael Sheets](https://github.com/infininight), being the maintainer of all (?) official TextMate grammars, kinda of lack time to answer everything :/

If you have a better grammar (Sublime Text, Atom, or TextMate grammar) to propose, [we'd gladly accept a pull request](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#changing-the-source-of-a-syntax-highlighting-grammar). I'm closing this issue in the meantime, as unless you have a better grammar to propose, there's not much we can do.
