### ISSUE TITLE
Some PHP files detected as Hacklang

### ISSUE THREAD

**Issue by theel0ja** [github/linguist#4229]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#troubleshooting),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [ ] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

<img width="1019" alt="screen shot 2018-08-14 at 13 59 52" src="https://user-images.githubusercontent.com/5832930/44088018-59285fc0-9fca-11e8-95d5-82b3b07af11a.png">

### URL of the affected repository:
https://github.com/theel0ja/IPLookup/blob/fc18200e8678a3cc9fc071ecd6be10c8b95a3a10/src/add-to-flagfox.php

### Last modified on:

2018-08-04

### Expected language:

PHP

### Detected language:

Hack

**Comment by pchaigno** [comment]
Thanks for the report.

Since Linguist considers each file independently and that file only contains HTML code, it's going to be difficult (impossible?) for Linguist to understand that it is a Hack file. You can use an [override](https://github.com/github/linguist#overrides) to change that behavior.

**Comment by theel0ja** [comment]
I mean it detects PHP files that contain only HTML as Hack files

**Comment by pchaigno** [comment]
Yep, `.php` files can be either PHP or Hack since both languages use that extension. Linguist usually relies on the content to distinguish between the two. Since the file contains only HTML code, it fails to do so properly.

**Comment by Arkanic** [comment]
hey
i have this problem
https://github.com/Arkanic/warriorcats

**Comment by lildude** [comment]
@Arkanic https://github.com/github/linguist/issues/4229#issuecomment-412847227 applies to your case too.

**Comment by iMaz1n** [comment]
> hey
> i have this problem
> https://github.com/Arkanic/warriorcats

cause you created a php file that doesn't contain php code, so you need to add some php code

**Comment by yannikbloscheck** [comment]
> Yep, `.php` files can be either PHP or Hack since both languages use that extension. Linguist usually relies on the content to distinguish between the two. Since the file contains only HTML code, it fails to do so properly.

If it can't really decide based on the content, the fallback language should still be the far more popular and original language for that file extension. This is PHP and not Hack. I find the current behaviour very confusing. Took me some time to finally find this issue with an explanation.

**Comment by Hnnx** [comment]
I don't mind, it makes me look like I'm using some super secret language while.
Also experiencing this on certain .php files

**Comment by geraldelorm** [comment]
Thank you

**Comment by iotstudent** [comment]
Thanks for this explanation

**Comment by przemub** [comment]
Should not it be detected as HTML then? What Hack has to do with this?

**Comment by pierreminiggio** [comment]
Hello !
Same issue on this private repo : https://github.com/pierreminiggio/kevin

**Comment by luisfelipesdn12** [comment]
Now overrides documentation is in: https://github.com/github/linguist/blob/master/docs/overrides.md
