### ISSUE TITLE
[Question] How does linguist detect the file to use as the grammar?

### ISSUE THREAD

**Issue by FreHu** [github/linguist#4231]
The contributing guidelines state that

> Switching the source of a grammar is really easy:
> 
> script/add-grammar --replace MyGrammar https://github.com/PeterPan/MyGrammar
> This command will analyze the grammar and, if no problems are found, add it to the repository. If problems are found, please report these problems to the grammar maintainer as you will not be able to add the grammar if problems are found.
> 

I have a slightly different use case: If I were to convert my tmlanguage from xml to json or yaml for the sake of readability and host it in the exact same repository, will linguist automatically pick up the new file? Assume I name it x.tmlanguage.json.

**Comment by lildude** [comment]
> If I were to convert my tmlanguage from xml to json or yaml for the sake of readability and host it in the exact same repository, will linguist automatically pick up the new file?

Yup. When we make a release we often update the submodules for each of the grammars. As part of this, the grammar compiler will run and process the files in the repo as follows: https://github.com/github/linguist/blob/3176166966731806828e4681385424ddcfcf5543/tools/grammars/compiler/loader.go#L119-L128

> Assume I name it x.tmlanguage.json.

Almost. You'll need to put the `x.tmLanguage.json` file into `/grammars` or `/syntaxes` (note the lowercase `s`).

Alternatively, if you use YAML instead, then renaming it to `x.YAML-tmLanguage` within the same directory will do the trick too.

Off the top of my head, I think you may be able to test this yourself by making your change and then replacing the grammar with itself.

**Comment by pchaigno** [comment]
@FreHu The three `case`s above encode de facto standards for the names and locations of grammars in TextMate, Sublime Text, and Atom modules. I'm closing this issue as I think the question has been answered, but if you run into any problem after making the change, don't hesitate to ping us!
