### ISSUE TITLE
Cannot clone repo on Windows

### ISSUE THREAD

**Issue by coldner** [github/linguist#4234]
I suspect that Windows files cannot contain '*' character.

PS C:\projects> git clone https://github.com/github/linguist.git
Cloning into 'linguist'...
remote: Counting objects: 32811, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 32811 (delta 4), reused 0 (delta 0), pack-reused 32798
Receiving objects: 100% (32811/32811), 33.56 MiB | 1.04 MiB/s, done.
Resolving deltas: 100% (17916/17916), done.

**fatal: cannot create directory at 'samples/F*': Invalid argument**

warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by lildude** [comment]
Whoopsie. That's gonna be due to https://github.com/github/linguist/pull/4178

/cc @pchaigno

**Comment by pchaigno** [comment]
Did we really support Windows before that #4178?

@coldner Could you try `git clone --branch v6.4.1 https://github.com/github/linguist`?

@lildude I'm not sure how to best address this to be honest...

**Comment by Alhadis** [comment]
* FStarLing, with the "-Ling" suffix comically pertaining to LINGuist fans. ;) 

I have access to a Windows 10 environment, installed by Microsoft's VagrantFile. Fee free to shoot me some instructions if you need me do help out here. 😉

**Comment by pchaigno** [comment]
> What about rename directory to FStar or FStarLang?

Currently Linguist expects the directory to be named after the language. To rename the directory, we would have to dissociate directories from names and add a new key in `languages.yml`. This change wouldn't be too complex but it'd handle a specific case (Windows) I'm not even sure we want to support...

**Comment by smola** [comment]
We have Windows users on [src-d/enry](https://github.com/src-d/enry), I would not be surprised if they are common on github/linguist too.

**Comment by pchaigno** [comment]
@lildude Do we want to support Windows? Should I make the necessary changes?

**Comment by lildude** [comment]
> Do we want to support Windows? 

I don't see why not as the gems should be installable. It is a bit annoying Git on Windows behaves this way, but it's also kinda weird to have a wildcard char in a directory name too.

> Should I make the necessary changes?

Please do. Please also remind me that I'll need to perform the DB nudge when I make the next release once that PR has been merged so the language rename is picked up in the DB.

**Comment by pchaigno** [comment]
@coldner Could you try the fix at #4285? (Cloning the appropriate branch from my repository should do.)

**Comment by pchaigno** [comment]
I have checked that it works as expected under Windows. Closing in favor of #4285.
