### ISSUE TITLE
Show the language on a repository page, too

### ISSUE THREAD

**Issue by peter-kehl** [github/linguist#4236]
Dear Linguist contributor,

This is not a request for Linguist, but for GitHub. However, this is related to showing a repository's language - the Linguist's mission.

Currently, only https://github.com/userName or https://github.com/organizationName show the repo languages. The actual repository page doesn't. For example, https://github.com/github shows 'Ruby' for Linguist. But https://github.com/github/linguist doesn't, unfortunately.

Why show the language on a repository page, too? Could you see that it would help users to realise whether a repository matches their programming language. It would simplify their search for a project that they can use or where they can contribute.

If I reported it directly to GitHub, it wouldn't be trackable... Also, you (or if you are a volunteer contributor, then your peers working at GitHub) may know whom to address to get it actioned.

Thank you for Linguist. Imagine how awesome it would be if GitHub showed Linguist's result on every repository page.

**Comment by lildude** [comment]
> Currently, only https://github.com/userName or https://github.com/organizationName show the repo languages. The actual repository page doesn't.

Oh, but it does. 😁 

The common misconception is GitHub.com shows "a repository language", which is doesn't, and never has. There is no place within GitHub.com where you can specify a "repository language".  Instead, GitHub uses a concept of "this repo contains these languages in X, Y and Z proportions", and these proportions are determined by Linguist based on the bytes of code found within the repository.  This is detailed in the README: 

> The result of this analysis is used to produce the language stats bar which displays the languages percentages for the files in the repository. 

https://github.com/userName or https://github.com/organizationName showing a language is only showing the most prominent language detected within the repo, determined by Linguist - this is not necessarily the "repository language".

With this mind...

> Imagine how awesome it would be if GitHub showed Linguist's result on every repository page.

... it already is. Linguist is 100% responsible for all language representation and determination of a repo.

The closest you can get to marking a repo as an explicit language, regardless of what Linguist has determined, is by setting applicable topics on the repo, which are searchable.

**Comment by peter-kehl** [comment]
Hi Colin or his friend,

Thank you for explaining.

Yes, github.com/organisationName shows the most prominent language at the bottom left of each repo item. For example 'Ruby' for https://github.com/github > Linguist:
![image](https://user-images.githubusercontent.com/4270240/44346607-36946f00-a44b-11e8-8d4d-b7ccadb30dcc.png)

However, github.com/organisationName/repoName (for example https://github.com/github/linguist) doesn't. People are missing out. That's where Linguist's result could help.

**Comment by pchaigno** [comment]
> However, github.com/organisationName/repoName (for example https://github.com/github/linguist) doesn't. People are missing out. That's where Linguist's result could help.

It does, you just need to click on the bar at the top of the repository:

![untitled0](https://user-images.githubusercontent.com/1764210/44348755-a599b400-a49b-11e8-9306-01c3eb80f2d0.png)

**Comment by peter-kehl** [comment]
Hi Paul,

Thank you.

I set up several GitHub organisations, many repositories, browsed through even more... But never realised that the bar was clickable. It's so hidden.

Dear GitHubbers,

Imagine how you'd help people to see results of Linguist, and to find a project relevant to their programming language faster, if you made the "clickability" of the bar obvious.

Yes, it changes the mouse pointer on mouseover. But it's so thin and unexpected that most people won't notice. I guess UI designers want to save the screen space. There must be another way and more indicative.

**Comment by lildude** [comment]
@peter-kehl You raise a valid point that it's not immediately obvious that the bar is clickable. Unfortunately, there's absolutely nothing we can do about it from Linguist's perspective.

If you'd like to get your suggestion in front of the 👀 of the peeps who do have influence on this, I'd recommend either contacting our support team using the "Contact GitHub" link at the bottom of any page on GitHub.com or try the community forum at https://github.community/.

**Comment by peter-kehl** [comment]
Hi Colin and Paul,

Thank you.

Anyone who agrees that the language indicator should be easier to see: Could you comment/add kudo to https://github.community/t5/Welcome/Easier-indication-of-a-repository-s-language-s/m-p/11541#M1721.
