### ISSUE TITLE
Add Esri/ArcGis ASCII data format (.asc)

### ISSUE THREAD

**Issue by smola** [github/linguist#4237]
## Problem Description

There is a significant amount of `.asc` files in GitHub that are some kind of ArcGis/Esri ASCII format. I'm sorry to not be more specific, but I am not really sure what the name of the format is, you can see some more info here: https://gis.stackexchange.com/questions/71867/understanding-esris-asc-file https://desktop.arcgis.com/en/arcmap/latest/tools/conversion-toolbox/raster-to-ascii.htm https://community.esri.com/thread/174978

Currently they are usually misclassified as Public Key or AGS Script.

### URL of the affected repository:

~A search on GitHub yields 98,737 results with extensions (.asc, .esri and others):~
Wrong URL, actually very rare:
- 2 .arc https://github.com/search?utf8=%E2%9C%93&q=xllcorner+++extension%3Aarc&type=Code
- 2 .esri https://github.com/search?q=xllcorner+++extension%3Aesri&type=Code

### Last modified on:
2018-09-06

### Expected language:
Not sure, see above.

### Detected language:
Public Key, AGS Script

**Comment by smola** [comment]
I made a mistake in my initial search. These actually seem pretty rare. I might have been just too unlucky to stumble across them myself.

**Comment by pchaigno** [comment]
Should we close then?

**Comment by smola** [comment]
Yes, closing. I'll reopen if I come across more than just a few of these files.

**Comment by smola** [comment]
Meh. It is quite more popular, just a little less than my original query. Here is a, hopefully, more reliable search query:

- 86,175 https://github.com/search?l=Public+Key&q=xllcorner+++extension%3Aasc&type=Code
