### ISSUE TITLE
Add ClearSilver templates

### ISSUE THREAD

**Issue by smola** [github/linguist#4238]
## Problem Description
ClearSilver templates are classified as C# or SmallTalk.

See: http://www.clearsilver.net/

### URL of the affected repository:
See example search: https://github.com/search?p=2&q=extension%3Acs+h1+include&type=Code

### Last modified on:
2018-08-20

### Expected language:
HTML+ClearSilver?

### Detected language:
C#, Smalltalk

**Comment by smola** [comment]
Still relevant.

**Comment by pchaigno** [comment]
@smola Do you plan to add support for this new language?
