### ISSUE TITLE
Wrong language detection, any makefile inside repo, but linguist detected that makefiles has 51% 

### ISSUE THREAD

**Issue by bielu000** [github/linguist#4239]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

### Detected language:
Makefile 51.8% 
CMake 19.8% 
C++ 14.6% 
C 12.3% 
Tcl 1.5%

**Comment by lildude** [comment]
Hmmm, this appears to be a caching issue. I've just forced a reanalysis and it is now reflecting C as the only language in the repo, but the language bar hasn't picked this up this yet for some reason.

Try making another commit to the repo or give it some time for the caching to expire.
