### ISSUE TITLE
Add support for Quake3 shaders

### ISSUE THREAD

**Issue by smola** [github/linguist#4240]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
Quake3-based games contain shaders that are misclassified as GLSL and ShaderLab. These seem pretty common.

### URL of the affected repository:
Some of them: https://github.com/search?p=1&q=extension%3Ashader+blendfunc&type=Code

### Last modified on:
2018-08-20

### Expected language:
Not sure.

### Detected language:
GLSL, ShaderLab

**Comment by RobQuistNL** [comment]
It looks like its a "Quake3 Shader Script" - its not really a shader, but its configuration for "materials" and "shader settings" within Quake3 engine games.

More information about the format can be found here: http://toolz.nexuizninjaz.com/shader/
