### ISSUE TITLE
docs and github pages

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [github/linguist#4241]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
i am using github pages and want to recognise the python files in the docs folder

### URL of the affected repository:
https://github.com/Abdur-rahmaanJ/pymug

### Expected language:
python

### Detected language:
none

**Comment by lildude** [comment]
You'll need to use an override to negate `/docs` being treated as documentation as per 
https://github.com/github/linguist#documentation

**Comment by Abdur-rahmaanJ** [comment]
thank you !

Abdur-Rahmaan Janhangeer
https://github.com/Abdur-rahmaanJ
