### ISSUE TITLE
SCSS Is classified as CSS in the language bar, but not in the search feature

### ISSUE THREAD

**Issue by AlexejheroYTB** [github/linguist#4245]
## Problem Description

SCSS files are classified as being CSS, but when clicked, there are no search results

![](https://user-images.githubusercontent.com/32238504/44513041-00622400-a6c5-11e8-8af6-82b0fd562288.png)  

***
***

![](https://user-images.githubusercontent.com/32238504/44512978-d3ae0c80-a6c4-11e8-84f3-a53fbdcd3fff.png)  

***
***

![](https://user-images.githubusercontent.com/32238504/44513065-107a0380-a6c5-11e8-9285-bd28b9240c26.png)

**Comment by lildude** [comment]
This is a side effect of the Language grouping that happens within Linguist but not differentiated by search. 

SCSS is part of the CSS group:

https://github.com/github/linguist/blob/1221480189454d80e02f3811612f79e2aadd8f91/lib/linguist/languages.yml#L4191-L4194

**Comment by pchaigno** [comment]
@lildude might be time to fix that one on GitHub.com's side...?

**Comment by AlexejheroYTB** [comment]
So this is working as intended?

**Comment by Alhadis** [comment]
> SCSS is part of the CSS group

This has always irked me.

SCSS has less in common with CSS than CoffeeScript does with JavaScript. I know this has been discussed before, time and again, but as someone with a background in front-end web development, I can honestly tell you that classifying SCSS as CSS looks *very* jarring.

**Comment by lildude** [comment]
> @lildude might be time to fix that one on GitHub.com's side...?

Possibly, though I'm not part of the team that controls search and how it behaves so have little influence on the behaviours or product direction. I also don't know how it works on that side of thing 😄

**Comment by lildude** [comment]
@AlexejheroYTB you removed your comment, but I saw it 😉... yes, it is working as intended.

**Comment by AlexejheroYTB** [comment]
What about on the github side?

**Comment by lildude** [comment]
> What about on the github side?

Yup. It's working as intended too.

**Comment by AlexejheroYTB** [comment]
"No files found" ?

**Comment by lildude** [comment]
It's returning no files because it is searching for the language CSS as you can see from the URL (you pointed this out in your first screenshot):

```
https://github.com/SMLHelper/SMLHelper.github.io/search?l=css   <---- LOOKY HERE
```

As you pointed out, your repo doesn't have any CSS files, hence no results. Change `css` to `scss` and 🎉 , files as shown in your third screenshot.

The limitation is search doesn't have a concept of searching for a language group, only individual languages.

**Comment by AlexejheroYTB** [comment]
Every limitation can be overcome ;)

**Comment by AlexejheroYTB** [comment]
This might be confusing for some users, thats why I asked

**Comment by AlexejheroYTB** [comment]
Should I close this now, or wait for a "fix"?

**Comment by lildude** [comment]
Best to close. This isn't on anyone's roadmap right now and isn't likely to change on the GitHub side of things anytime soon. When it does, Linguist will certainly be updated to accommodate, if necessary.
