### ISSUE TITLE
Wrong repo language for Scala project

### ISSUE THREAD

**Issue by tahakashaf** [github/linguist#4252]
Github url : https://github.com/tahakashaf/LearnSpark_2.X
Launguage showing as XSLT but it needs to be scala

## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [ ] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

**Comment by pchaigno** [comment]
The language shown in the search results is the first in the language statistics for your repository (in your case, XSLT). Please see Linguist overrides to tell Linguist to ignore XSLT and CSS files.

**Comment by tahakashaf** [comment]
Got it ..Fixed...thanks
