### ISSUE TITLE
Grammar for JS seems to be incorrect

### ISSUE THREAD

**Issue by devsnek** [github/linguist#4272]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

I noticed the issue here: https://github.com/devsnek/node/commit/ab9c03afab7482aec9ae30ba065de414f66f1d19

![](https://gc.gy/5343307.png)

When I made this commit (aug 15) the view was definitely correct.

**Comment by pchaigno** [comment]
Linguist only selects the grammar to use for highlighting. For JavaScript, GitHub uses [atom/language-javascript](https://github.com/atom/language-javascript). You should open an issue there if there isn't already one.
