### ISSUE TITLE
add support for .aia files

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [github/linguist#4275]
add support for .aia for app inventor http://appinventor.mit.edu/explore/ such as in this repo : https://github.com/dotcomboom/AIA

**Comment by pchaigno** [comment]
Please have a look at the [guidelines to add support for a new language to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). It `.aia` files meets the requirement on in-the-wild usage, we'd welcome a pull request!

**Comment by Abdur-rahmaanJ** [comment]
only detect file ^^_ no need grammar

**Comment by lildude** [comment]
> only detect file ^^_ no need grammar

That file is _never_ going to be recognised as a language as it's a zip file and all binary files are expressly not analysed by Linguist...

https://github.com/github/linguist/blob/8cd9d744caa7bd3920c0cb8f9ca494ce7d8dc206/lib/linguist.rb#L19-L21

**Comment by lildude** [comment]
I've taken another look at those files and it would be more apt for linguist to recognise the language(s) of the files in the `src` directory, if it doesn't already, but those files would need to be committed a repo, not the `.aia` files.

**Comment by Abdur-rahmaanJ** [comment]
ok thought it recognised by file extention

Abdur-Rahmaan Janhangeer
https://github.com/Abdur-rahmaanJ
