### ISSUE TITLE
Issue: Linguist not being running when accepting a pull request

### ISSUE THREAD

**Issue by pulimento** [github/linguist#4276]
## Preliminary Steps

Please confirm you have...
- [X] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [X] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [X] considered implementing an [override](https://github.com/github/linguist#overrides),
- [X] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

It totally seems that linguist is not running when accepting a pull request (e.g. merging dev branch to master, from an opened pull request, from the web client). Reading how Linguist (and when) should run, I've pushed a manual silly commit, and now works fine. The problem is solved at the moment, but just before doing that newline commit, language reported was wrong. The [accepted pull request](https://github.com/WaveEngine/Samples/pull/13) deletes **all** HTML files. Before and after accepting this pull request, language was detected as HTML. Seeing that linguist didn't run, I created [this commit](https://github.com/WaveEngine/Samples/commit/18ce3f2f92852c3b1179bea280644b792804219c), and
it fixed the issue.  

### URL of the affected repository:
https://github.com/WaveEngine/Samples (not anymore an issue).

### Last modified on:
Today, 28/09/2018

### Expected language:
Mostly c#

### Detected language:
(before last gitignore commit) Mostly HTML

**Comment by pchaigno** [comment]
Thanks for the report!

Do you remember how long you waited before pushing the "silly commit"?

**Comment by lildude** [comment]
For a start, this is not a Linguist problem (it's technically a jobs problem on GitHub.com, if it were a problem), and secondly, this can happen and is documented in the README…

> How Linguist works on GitHub.com
>
> When you push changes to a repository on GitHub.com, a **low priority background job is enqueued** to analyze your repository as explained above. The results of this analysis are cached for the lifetime of your repository and are only updated when the repository is updated. **As this analysis is performed by a low priority background job, it can take a while, particularly during busy periods, for your language statistics bar to reflect your changes.**

If you left it long enough after the merge, you should have seen your language stats updated to reflect the changes. It's very likely your "silly commit" coincided with the running of the background job from the earlier merge.

If you can readily reproduce this and don't see your language stats updating after a few hours (excessive but ensures the job should definitely have run), please contact GitHub support.

**Comment by pulimento** [comment]
About 12-15 hours

**Comment by lildude** [comment]
Thanks. That should have been plenty of time, but does indicate a problem with the background job. As there's little we can do about it now, the best thing to do is contact GitHub support the next time you encounter the problem _before_ making any changes that could hide the state.

**Comment by pulimento** [comment]
Ok, thanks to both of you. You're right, this is not an issue with the tool itself, but with GitHub jobs. I'm closing the issue now. 

@lildude Yes, only I was aware of the problem when it was fixed.
@pchaigno Even on a low-priority queue, more than 12 hours should be enough. Don't think of a coincidence, but nevermind anyway.

Again, thanks. Hace a nice day
