### ISSUE TITLE
Code doesn't get recognised

### ISSUE THREAD

**Issue by Bartvhelvert** [github/linguist#4279]
## Problem Description
Kotlin and Java code doesn't get recognised for my repository. It works fine for my other projects but this one doesn't work for some reason.

## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

### URL of the affected repository:
https://github.com/RuneData/Cache

### Last modified on:
2018-9-30 

### Expected language:
Kotlin, Java

### Detected language:
None

**Comment by Alhadis** [comment]
Have you followed the steps that were included in the issue template?

**Comment by Bartvhelvert** [comment]
> Have you followed the steps that were included in the issue template?

Yes

**Comment by lildude** [comment]
All your files are being considered vendored because they all appear to have `cache` in the path so are hitting: 
https://github.com/github/linguist/blob/8cd9d744caa7bd3920c0cb8f9ca494ce7d8dc206/lib/linguist/vendor.yml#L13

You'll need to implement an override to mark this path as not vendored.

**Comment by Bartvhelvert** [comment]
Thank you, that solves it.
