### ISSUE TITLE
Does linguist load global/system gitattributes?

### ISSUE THREAD

**Issue by raphaelyancey** [github/linguist#4283]
I'm trying to make some languages detectable widly for every repository on a server.

I created a `/etc/gitattributes` (system) and a `/home/git/.gitattributes` (user-global) but neither of them seems to be taken into account, only a `.gitattribute` in the repository root.

Does linguist load global/system gitattributes?

**Comment by raphaelyancey** [comment]
@pchaigno In this case it is a self-hosted GitLab instance. So linguist has access to all the repositories on the server. I'd like linguist (in this GitLab) to detect some other files that are not the *programming* type, like `.pd` (Pure Data).

According to [git docs](https://git-scm.com/docs/gitattributes#_description), if no `.gitattributes` is present in the repository root directory, it should try `~/.gitattributes` and `$(prefix)/etc/gitattributes` right?

**Comment by pchaigno** [comment]
> According to [git docs](https://git-scm.com/docs/gitattributes#_description), if no `.gitattributes` is present in the repository root directory, it should try `~/.gitattributes` and `$(prefix)/etc/gitattributes` right?

We use [`Rugged::Repository.fetch_attributes`](https://github.com/github/linguist/blob/a5df9a00ab7c9828bd7038bb9f9bd5e56d325dc9/lib/linguist/lazy_blob.rb#L36) to retrieve the `.gitattributes` values. I don't know if it tries the global settings first. @vmg might know more since he authored that code.

**Comment by lildude** [comment]
Hmmm, I'm pretty sure GitLab doesn't take `/etc/gitattributes` into account when assessing a repository, regardless of whether Linguist does or not.

**Comment by raphaelyancey** [comment]
> Hmmm, I'm pretty sure GitLab doesn't take `/etc/gitattributes` into account when assessing a repository, regardless of whether Linguist does or not.

I followed the whole path from a `/languages` API request on GitLab and I ended up on [this function](https://gitlab.com/gitlab-org/gitaly/blob/master/internal/linguist/linguist.go#L28), which seems to simply call linguist with the repository path and a ref as parameters, and parse its output. Attributes handling seems to happen deeper than GitLab app, in `Rugged` as @pchaigno pointed out.

I just tested `Rugged` on local repositories (bare and non-bare) and it only takes `.gitattributes` (non-bare) and `info/attributes` (bare) into account when reading attributes with `.fetch_attributes()`. Didn't catch `~/.gitattributes` (and not tested with `/etc/attributes`).

Should I fill a issue over there?

**Comment by ZJvandeWeg** [comment]
GitLabber here, at the time of writing we don't read anything outside of the repository for linguist. Just to confirm, like previously stated by @pcantrell in https://github.com/github/linguist/issues/4283#issuecomment-425896765

@raphaelyancey My understanding is that it would be filed against either Rugged, the Ruby wrapper around LibGit2, or Libgit2 itself.

**Comment by pchaigno** [comment]
Closing in favor of libgit2/rugged#765.

**Comment by ineshbose** [comment]
Does this mean that if I want to test changes to my `.gitattributes`, I need to push to remote everytime?

**Comment by lildude** [comment]
> Does this mean that if I want to test changes to my `.gitattributes`, I need to push to remote everytime?

No. If you have Linguist installed locally, you can commit your changes to the repo and run Linguist against the repo.

If you don't have Linguist installed locally, then yes, you will need to commit your changes, push, and then wait for GitHub to run Linguist against your repo.
