### ISSUE TITLE
Missing many F* files from the main FStar repo

### ISSUE THREAD

**Issue by catalin-hritcu** [github/linguist#4284]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

With F* support added recently (#4178) we can finally benefit from linguist support in the main F* repo at <https://github.com/FStarLang/FStar>, which is great. However, the language statistics we get for this repo still seem highly inaccurate, since linguist fails to detect many of the F* files in that repo. For instance **no** F* file is detected in the `examples` or `doc/tutorial/code` dirs:
```
$ github-linguist --breakdown | grep examples                                                   (git)-[master] 
$
```
(complete breakdown here https://gist.github.com/catalin-hritcu/435ce9d171ca8e52ae3f09822d15749b)
... although the `examples` dir contains 1000+ F* files
```
$ find examples -name "*.fst" | wc -l                                                           (git)-[master] 
1179
$
```

Running linguist directly on one of the files does detect the right language, just that it seems that linguist somehow completely misses these files:
```
$ github-linguist examples/hello/hello.fst
hello.fst: 9 lines (5 sloc)
  type:      Text
  mime type: image/vnd.fst
  language:  F*
```

I've also tried adding various overrides, but they had no effect on this issue:
```
examples/* linguist-vendored=false
examples/* linguist-generated=false
examples/* linguist-detectable=true
examples/hello/* linguist-vendored=false
examples/hello/* linguist-generated=false
examples/hello/* linguist-detectable=true
examples/hello/hello.fst linguist-vendored=false
examples/hello/hello.fst linguist-generated=false
examples/hello/hello.fst linguist-detectable=true
```

### URL of the affected repository:

https://github.com/FStarLang/FStar

### Last modified on:
2018-10-02

**Comment by pchaigno** [comment]
Files in `examples/` and `doc/` are considered documentation by Linguist. You can use the `linguist-documentation` override to force Linguist to count these files in language statistics.

**Comment by catalin-hritcu** [comment]
@pchaigno Thanks for the quick answer. I tried adding the following to `.gitattributes`:
```
examples/* linguist-documentation=false
examples/hello/* linguist-documentation=false
examples/hello/hello.fst linguist-documentation=false
```
but this seems to have no effect either.

**Comment by pchaigno** [comment]
The following [seems to work for me](https://github.com/pchaigno/FStar):
```
*.fst linguist-documentation=false
```
Otherwise, to match all files under `examples/`, I think you need:
```
examples/**/*.fst linguist-documentation=false
```

**Comment by catalin-hritcu** [comment]
This seems indeed to work on your fork, but I can't reproduce the success locally with Linguist v7.0.0 (and ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]). I could try a blind fix on the FStar github repo, but I still have no clue what's going on. On my local machine, all of the following have no effect whatsoever:
```
*.fst linguist-documentation=false
*.fsti linguist-documentation=false
examples/**/*.fst linguist-documentation=false
examples linguist-documentation=false
examples/* linguist-documentation=false
examples/*/*.fst linguist-documentation=false
examples/*/*.fsti linguist-documentation=false
examples/hello/* linguist-documentation=false
examples/hello/hello.fst linguist-documentation=false
doc/tutorial/code/* linguist-documentation=false
doc/tutorial/code/exercises/Ex01a.fst linguist-documentation=false
```
I still get:
```
$ github-linguist --breakdown | grep examples
$
```

**Comment by catalin-hritcu** [comment]
Did the blind fix (https://github.com/FStarLang/FStar/commit/1e453cdd2523cef9a3ec0ba607acf69301def37b) and it indeed seems to work for <https://github.com/FStarLang/FStar>, but as I said I still don't understand why this doesn't also work for me locally.

**Comment by catalin-hritcu** [comment]
Wow! Me pushing this to F* master made it work locally. What's going on? Does `linguist` ignore local changes to files?

**Comment by catalin-hritcu** [comment]
I missed the following line in the documentation.

> When testing with a local installation of Linguist, take note that the added attributes will not take effect until the .gitattributes file is commited to your repository.

So while it seems odd to me, it's a documented (mis-)feature. Sorry for the noise!

**Comment by pchaigno** [comment]
> So while it seems odd to me, it's a documented (mis-)feature. Sorry for the noise!

Oh, right. Sorry, I forgot to mention that :S
