### ISSUE TITLE
Client-side usage

### ISSUE THREAD

**Issue by FreHu** [github/linguist#4292]
Is there any way to use linguist client-side for highlighting? I know there are other highlighting libraries for js, but they all seem to use different formats and tmlanguage seems to be the most widespread.

**Comment by pchaigno** [comment]
Linguist [only detects languages](https://github.com/github/linguist#theres-a-problem-with-the-syntax-highlighting-of-a-file), it doesn't highlight files.

**Comment by FreHu** [comment]
Do you know how the higlighting is done then? My markdown preview request goes to the server and comes back highlighted, so I assumed linguist does this since it contains all the grammars.

**Comment by pchaigno** [comment]
No, I don't know exactly. Grammars are used by a closed-source project to highlight files.

**Comment by FreHu** [comment]
Very informative, thanks for the answers guys!
