### ISSUE TITLE
Game Maker Studio 2's broken "json" file is misclassified as Yacc

### ISSUE THREAD

**Issue by RobQuistNL** [github/linguist#4293]
## Problem Description

As you can see [here](https://github.com/RobQuistNL/DSNet/blob/ad8bc9ffc37b920610f6524a86324f1b6503d3c0/options/main/inherited/options_main.inherited.yy), a custom "binary" format (some header info and then some JSON) is misclassified as Yacc.

Now, its not Yacc, its not really JSON either, but its not really binary, either. I don't really know how to classify this. My gut says "JSON", but if there's a way to mark it as a generated file and just ignore it, that would be better.

### Expected language:
GameMakerStudio 2 Generated file / JSON

### Detected language:
Yacc

**Comment by lildude** [comment]
> if there's a way to mark it as a generated file and just ignore it

Eeerrrm, did you read any of the links in the template you deleted when opening this issue? 😜

**Comment by RobQuistNL** [comment]
I know there are generated file marks, but since there are other YY files that are not marked as generated right now (they are partially generated, partially filled through the IDE), I was merely wondering if we _should_. Maybe my phrasing was a little off, but maybe this will convey the question better:

_Should_ we mark this as a generated file and ignore it? Or classify it as JSON?

**Comment by pchaigno** [comment]
Is there a sure way to identify these files? We could add them to [`generated.rb`](https://github.com/github/linguist/blob/master/lib/linguist/generated.rb) if there is.

There seem to be [a few of them](https://github.com/search?q=extension%3Ayy+targets+OR+option_gameguid) around.

**Comment by lildude** [comment]
Ah, thanks for the clarification. 

> but since there are other YY files that are not marked as generated right now (they are partially generated, partially filled through the IDE)

Looking into this now, that will be thanks to you and https://github.com/github/linguist/pull/4130 😁

> _Should_ we mark this as a generated file and ignore it? Or classify it as JSON?

Generally speaking, if a file is never or rarely created by hand, then it would make sense to mark it as generated, after all people generally don't want them to count in their language stats as they didn't write the code, a computer did. The example you referenced looks like an example where a human isn't likely to have created it so would make sense to be marked as generated, which means you've identified a scenario not already covered by the detection introduced in https://github.com/github/linguist/pull/4130

That example is definitely not JSON so should not be marked as such.

**Comment by RobQuistNL** [comment]
I think the easiest idenfitication would even be filename. The ".inherited.yy" is a broken binary with JSON, all the other .yy's are identified correctly.

Otherwise a regex would work as well, as the files contain a version ``1.0.0`` (some text, and then) ``{json}``

**Comment by RobQuistNL** [comment]
Also, I was mistaken - the .yy files _are_ marked as generated! You can see that here: https://github.com/github/linguist/blob/master/lib/linguist/generated.rb#L582-L592

I will extend this match and the testcases in a new PR.

**Comment by RobQuistNL** [comment]
Note to self: Also fix this misclassification:
https://github.com/NuxiiGit/GML2DSkeletalAnimation/blob/1a21957e6892cb48c1b16021b12115d945e1b4d8/2DSkeletalAnimationRuntime_Nuxii/datafiles_yy/Skeletons/DragonBones/Egret/Dragon/Dragon_ske.json.yy
