### ISSUE TITLE
Some GameMakerLanguage files are still marked as Graph Modeling Language

### ISSUE THREAD

**Issue by RobQuistNL** [github/linguist#4294]
Since there are some Game Maker Language files that slipped through the cracks in making the regex, I'm opening this issue.

The distinction between Graph Query Language and GameMaker Language is pretty clear, allthough you can see why it fails in [this case](https://github.com/GameMakerDiscord/PushEd/search?l=Graph+Modeling+Language).

The heuristics need to be a little more strict.

The heuristic rules added here should be revised: https://github.com/github/linguist/pull/4130

### URL of the affected repository:
https://github.com/GameMakerDiscord/PushEd/search?l=Graph+Modeling+Language

### Expected language:
GameMakerLanguage

### Detected language:
Graph Query Language

**Comment by pchaigno** [comment]
> As you added the heuristic, I'm a little unsure why you've opened this issue instead of a PR. We don't need an issue for fixes or improvements, so feel free to go straight to PR…

I agree with @lildude; :+1: for PRs!

> The distinction between Graph Query Language and GameMaker Language is pretty clear, allthough you can see why it fails in [this case](https://github.com/GameMakerDiscord/PushEd/search?l=Graph+Modeling+Language).

I don't see what's the issue with those files. They are Game Maker Language files and detected as such, no?

**Comment by RobQuistNL** [comment]
Ah, yeah Modeling is what I mean! 

I will be opening a PR for it, but since I dont have time this week and noticed the issue yesterday I figured I'd open an issue for it to keep track of it.

Also, if you look again at the link, there's ~500 which are correctly identified, but there are 3 (the actual page that opens when you click the link) that are identified as Graph Modeling Language - probably because they are strangely formatted arrays / matrixes (and matches the Graph heuristic rule).

I will probably be opening a PR that slightly edits the regex.

Feel free to close this issue if its not the way to go - a PR will be coming soon :)

**Comment by pchaigno** [comment]
> Also, if you look again at the link, there's ~500 which are correctly identified, but there are 3 (the actual page that opens when you click the link) that are identified as Graph Modeling Language - probably because they are strangely formatted arrays / matrixes (and matches the Graph heuristic rule).

These 3 files are actually detected as Game Maker Language as they should, as hinted by the correct syntax highlighting. The search result display is probably just not up-to-date; there are a lot of caching issues between Linguist results and the search results. If it persists, please contact GitHub staff.
