### ISSUE TITLE
Detect happy/alex source files as such

### ISSUE THREAD

**Issue by vmchale** [github/linguist#4302]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

When running linguist on a repository containing Alex/Happy source code (lexer/parser generator for Haskell), linguist detects this as Logos and Yacc, respectively. As an example, this repo requires overrides: https://github.com/vmchale/language-xats/blob/master/.gitattributes

### URL of the affected repository:

https://github.com/vmchale/language-xats/

### Last modified on:
2018-10-19

### Expected language:
Happy/Alex

### Detected language:
Logos/Yacc

**Comment by lildude** [comment]
Linguist doesnt know about the Happy or Alex languages hence the next closest was guessed based on extensions and content. We'd certainly consider a pull request to add support, though keep in mind the languages need to already have widespread use on GitHub.com. See CONTRIBUTING.md for more details.
