### ISSUE TITLE
Hotfix for Kotlin syntax highlighting

### ISSUE THREAD

**Issue by nishtahir** [github/linguist#4329]
It looks like there was a bug in the grammar that causes major issues. See https://github.com/nishtahir/language-kotlin/issues/5. I've put up a patch to fix the problem and tested it on Lightshow and it seems to be working.

## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [c] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

It looks like the cause of the problem is a difference in how VSCode and Github parse and render the grammar since it works with VSCode. Unfortunately I don't know if there are any other tools to aid in debugging the exact cause of the issue on GitHub besides using Lightshow 😕.

### URL of the affected repository:
Specific repositories affected were listed https://github.com/nishtahir/language-kotlin/issues/5. I can confirm that more have been affected

### Last modified on:
2018-11-14

### Detected language: 
Kotlin

**Comment by lildude** [comment]
Thanks. Your changes will be pulled in automatically the next time I perform a Linguist release. I've just made a release today and am out of the office until the end of the week so won't be able to make another release until early next week at the earliest.

There isn't really an easy way to check how things will behave on GitHub short of ensuring the [compiler we use in Linguist](https://github.com/github/linguist/tree/master/tools/grammars) doesn't report any problems and checking on Lightshow.

Another tip is your grammar is a TextMate-compatible grammar: it's probably worth checking how it behaves with TextMate just in case VSCode is doing something clever to catch inconsistencies which GitHub isn't.

@Alhadis has a fair amount of experience with writing grammars so he may be able to also offer some assistance in determining why the current grammar version we're shipping isn't playing nicely.

**Comment by lildude** [comment]
I aim for a release approximately once a month, with exceptions. I won't have the time for another release until late next week at the earliest, though it could possibly the week after.

**Comment by DanielJette** [comment]
@lildude How is that acceptable? Isn't this impacting thousands of developers?

**Comment by lildude** [comment]
This may indeed be affecting a lot of developers, however this is no different from any other aesthetic bug that occurs in a third-party grammar used by GitHub (and GitLab) or any other third-party library used by any other piece of software for that matter. There is only one of me and maintaining Linguist isn't my primary role at GitHub. It is also impractical for me (or anyone else) to drop everything they're doing to make a new release every time we're notified of fix for a bug in a third party grammar as the time it takes to build, test and deploy and actually release a new version of Linguist is quite significant so I need to actively schedule time to do it.  This is why we don't make a release more frequently.

The opportunity I thought I was going to have this week was taken up by higher-priority tasks. If I get the opportunity to schedule time sooner than anticipated, I will.

**Comment by DanielJette** [comment]
Thank you for providing this context.
Is there any way to involve another developer or team in this process? Any opportunity to prioritize this issue would be greatly appreciated.

Even though it's aesthetic, we feel that this issue is starting to take a toll on our development velocity at Shopify. We don't use a QA team in our process and so the code review process is a significant and irreplaceable part of how we work. The lack of syntax highlighting is impacting our ability to effectively review code.

**Comment by lildude** [comment]
> Is there any way to involve another developer or team in this process? Any opportunity to prioritize this issue would be greatly appreciated.

Possibly, and I might get a gap tomorrow or Friday thanks to most of my colleagues being off for thanks giving (I'm not in the 🇺🇸 so I won't be taking the time off) so won't be needing much of my attention, however that comes with the caveat that most of the peeps needed to approve deploys to GitHub.com will also be off. 😞 

I'll certainly try to squeeze it in tomorrow and/or Friday.

**Comment by DanielJette** [comment]
Thank you very much @lildude that'd be greatly appreciated

**Comment by DanielJette** [comment]
🎉

**Comment by lildude** [comment]
This release is now live on GitHub.com and the sample in the OP of #4336 is now rendering correctly.
