### ISSUE TITLE
ES BigInteger support

### ISSUE THREAD

**Issue by NN---** [github/linguist#4330]
https://tc39.github.io/proposal-bigint/
Big integer is highlighted as an erroneous.

```js
var a = 1n; // Should be highlighted as correct code, not as error.

var b = 2q; // Invalid code, highlighted accordingly.
```

## Preliminary Steps

Please confirm you have...
- [X] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [X] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [X] considered implementing an [override](https://github.com/github/linguist#overrides),
- [X] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

BigInteger is part of ECMAScript and should be highlighted accordingly.

### URL of the affected repository:
Any repository with ES files.

### Expected language:
ECMAScript, JavaScript, ES, JS

### Detected language:
ECMAScript, JavaScript, ES, JS

**Comment by pchaigno** [comment]
From the [*Troubleshooting docs*](https://github.com/github/linguist#theres-a-problem-with-the-syntax-highlighting-of-a-file):

> Linguist detects the language of a file but the actual syntax-highlighting is powered by a set of language grammars which are included in this project as a set of submodules [as listed here](https://github.com/github/linguist/blob/master/vendor/README.md).
>
> If you experience an issue with the syntax-highlighting on GitHub, **please report the issue to the upstream grammar repository, not here**. Grammars are updated every time we build the Linguist gem so upstream bug fixes are automatically incorporated as they are fixed.

**Comment by NN---** [comment]
Thanks for quick reply.
Will do so.
