### ISSUE TITLE
[Question] Language support for an existing extension

### ISSUE THREAD

**Issue by ConsoleTVs** [github/linguist#4332]
I was told to ask this here by the github support team:

I'm currently in development of a programming language called "Nuua" (https://nuua.io). Suprisingly, the extension I've chosen to use (.nu) has already been chosen by a lisp-like language called Nu.

Could a new programming language have the same extension and be recognized as Nuua instead of Nu in the github repository depending on it's content?

**Comment by lildude** [comment]
> Could a new programming language have the same extension and be recognized as Nuua instead of Nu in the github repository depending on it's content?

Yup, but Linguist would need a heuristic (regex) that can be used to clearly differentiate between the two languages as detailed in [Adding a Language](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language).

Pay special attention to the very first line under the heading... we won't accept a PR if the language doesn't meet this requirement.

**Comment by ConsoleTVs** [comment]
Thanks for the response, I'll take it into consideration.
