### ISSUE TITLE
CSON is not CoffeeScript (strictly speaking)

### ISSUE THREAD

**Issue by Alhadis** [github/linguist#4344]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

I used a `linguist-detectable=true`  override [earlier tonight](https://github.com/Alhadis/language-etc/commit/59cfb4f29fad185471edc2f9d65f896afacfca0a) to mark my `Alhadis/language-etc` repo as CSON, not CSS. I was surprised to see the repo flagged as CoffeeScript instead.

I know it's a parent language (although should it be?), but this goes against the Principle of Least Astonishment.

### URL of the affected repository:
https://github.com/Alhadis/language-etc/commit/59cfb4f29fad185471edc2f9d65f896afacfca0a

### Last modified on:
2018-12-06

### Expected language:
CSON

### Detected language:
CoffeeScript

**Comment by Alhadis** [comment]
Whoops. Just realised what was wrong with the title. `/facepalm`'

**Comment by Alhadis** [comment]
Wait, no, you're goddamn right. 😥 This is another language which shouldn't be grouped under a "similar" language (like JSON and JavaScript). I believe I only connected CSON to CoffeeScript because, well... that's how JSON/JavaScript did it. 😠

**Comment by Alhadis** [comment]
So, after making a typo in this issue's title that turned out to be correct the *first* time (but only after correcting and pointing it out), I feel like an idiot and am now obliged to close this with a PR. 😢

**Comment by pchaigno** [comment]
Closing with a PR is never a bad thing :p

**Comment by Alhadis** [comment]
BTW:

> Imagine if `JSON with Comments` was displayed when you mark Sublime Text files to be detectable...

That reminded me that doing so would result in JSON files classified as JavaScript. Which, like CSON/CoffeeScript, isn't... really accurate. I'll fix both. 👍
