### ISSUE TITLE
Not all Hack files are detected correctly

### ISSUE THREAD

**Issue by azjezz** [github/linguist#4346]
## Preliminary Steps

- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

### URL of the affected repository:
https://github.com/azjezz/waffle

### Last modified on:
2018-12-08

### Expected language:
Hack ( 100% )

### Detected language:
Hack ( 61.5% )
C++ ( 38.5% )

**Comment by pchaigno** [comment]
Thanks for the report @azjezz!

We could probably improve results here with a partial heuristic rule based on `<?hh` for Hack. I'll look into it.

You checked the `considered implementing an override` checkbox. Why did you choose not to implement such an override in the end?

**Comment by azjezz** [comment]
i could do that, but i guess this can be fix as you said based on `<?hh`.
a long term solution would be better than using override.

**Comment by azjezz** [comment]
@pchaigno i talked with on of hack core team member before about `<?hh` and he said that when @hhvm drops support for php - there's chance that `<?hh` would be gone too ( unlike php, in hack you don't close `<?hh` and you can't mix hack with html ) so that's another problem.

**Comment by pchaigno** [comment]
Okay. Thanks for the information.

I've made a pull request (cf #4347) to add a new heuristic rule. It should help detect Hack `.hh` files properly, but won't address misclassifications of C++ `.hh` files.

**Comment by pchaigno** [comment]
The fix will take effect with the next release of Linguist, which usually happens once a month.
