### ISSUE TITLE
Reconsidering auto-detecting Yarn files as auto-generated

### ISSUE THREAD

**Issue by arcanis** [github/linguist#4348]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

#3431 added support for generated file detection for Yarn. I'm not sure this is a good idea.

While generated, the lockfile contains important information regarding the dependencies used by a project; maybe it would make sense to display them so that they can be properly reviewed? For example, it would be important for a reviewer to understand that a PR adds N packages to the lockfile (which might be much higher than the number of lines added to the `package.json` file).

This might also have security implication. A malicious author could easily change some resolved versions inside the `yarn.lock` file while also upgrading a `package.json` dependency to a innocent release. Since Github won't show the lockfile content by default the reviewer might forget to check it, accept the apparently harmless upgrade, and let the malicious override make its way to the lockfile.

Note that the same concerns might apply to the `package-lock.json` file from npm (except that they are much harder to review due to their nested design).

**Comment by mohamedmansour** [comment]
Its very unpleasant to review lockfiles, many devs glance over it without paying attention. I agree with you that marking it as auto generate would bring in more vulnerable packages. 

Is there a way to validate the `lockfile` was derived from the `package.json` for example, make sure the PR doesn't downgrade a package from the previous already committed file given the version within `package.json`.  Github should create such server side hook by default instead of devs placing that action in their build definition.

**Comment by arcanis** [comment]
I think it could be solved in interesting ways by offering a dedicated diff view for lockfiles that would pretty-print the changes (similar to how images are directly displayed rather than being shown as binary diff). That would require development time on the Github side, though, so in the meantime removing the file from the generated list would be a good start.

**Comment by lildude** [comment]
Your reasoning makes sense to me, however it's important to keep in mind that this has been in place for nearly two years so will potentially startle devs when they start to see these appearing in their diffs. After recent furores around simple things like colours, I'm apprehensive making such a noticeable change without larger community buy-in and support first.

Is there a general Yarn community discussion or consensus on this change that we can reference when making such a change?

If there isn't, are you able to raise such a discussion on the appropriate community forum that can be used as qualification for this?

**Comment by arcanis** [comment]
> Is there a general Yarn community discussion or consensus on this change that we can reference when making such a change?

Nope, but this one is as good as any! I maintain Yarn on a daily basis so on our side I don't think it'd be an issue (paging some other contributors if you want to shim in: @rally25rs / @gudahtt / @bestander). I can also tweet this discussion for the Yarn twitter account if you wish?

**Comment by pchaigno** [comment]
Let's also ping the person who made the change we want to revert, in case they have something to add: @sunderls.

**Comment by rally25rs** [comment]
Trying to catch up on the discussion... It doesn't look like #3431 was ever merged, so I'm guessing this functionality isn't actually in-place?

-----

My take on this is that the behvior `yarn.lock` should follow whatever other lockfiles do; npm's `package-lock.json`, Ruby bundler's `Gemfile.lock`, etc...

Personally, I _want_ to know when my lockfile changes.  Changes to these lock files represent actual functional changes to the final system (a version change to a dependency can have breaking changes).

-----

The other thing to note here is that I assume the intent behind the "generated files" behaviors is that "this generated file change is the result of a different file changing" for example changing a coffeescript file will result in a corresponding "generated"/compiled js file change.

Though lockfiles are generated from `package.json`, a change to one does not always mean a change to the other. A `yarn.lock` file can change without `package.json` changing, which could indicate that someone changed the version of a dependency incorrectly.

-----

To @mohamedmansour 's comment "_Its very unpleasant to review lockfiles_" that can be true, however to me it's more of a "am I expecting this file to have changes?" thing.  If I don't expect that file to change but it shows up in my diff, then I know something is wrong. If the changes are so massive that its "unpleasant" to review, then you probably make some dependency updates and are expecting a big change to that file. That's the case where I don't actually inspect it line by line.

If you are talking about it from a package maintainer / PR reviewer perspective, then I do think it's even more important to show that change for the reasons @arcanis mentioned. If someone is manipulating your dependencies, they should have a good reason. Sure they can still hide a subtle version change amongst some other "noise" in the file changes, but that's no excuse for a maintainer to say " 🤷‍♂️ eh, too complex. Approve/merge. Whatever."

**Comment by pchaigno** [comment]
> It doesn't look like #3431 was ever merged, so I'm guessing this functionality isn't actually in-place?

It was, in a different pull request, #3432.

**Comment by arcanis** [comment]
Ping? 🙂

**Comment by Alhadis** [comment]
@arcanis's reasoning is sound. NPM is plagued with enough security concerns as it is, I don't think we should be adding one more potential attack vector for malicious users.

In most cases, `yarn.lock` files will be listed at the end of a PR's file diffs, making them pretty easy to overlook. Since dependencies don't get changed/added by contributors too often, it's unlikely that `yarn.lock` files will cause too much noise in the long run.

**Comment by sunderls** [comment]
+1 for removing `yarn.lock` from the list.
since large diff is already auto collapsed, its not gonna be a problem.

**Comment by edmorley** [comment]
Another datapoint: when I review Renovate bot dependency update PRs on mobile, there is no way to view the contents of the automatically hidden yarn.lock changes without first switching to desktop view. This means the I have to use the frustrating workflow of:
open PR at files tab -> switch to desktop view -> click the expand link for yarn.lock and review the changes -> switch back to mobile view -> approve PR -> ...

Having yarn.lock changes be visible by default would save having to do this.

**Comment by pchaigno** [comment]
Would one of you like to open the pull request to revert #3431?

**Comment by Alhadis** [comment]
> Would one of you like to open the pull request to revert #3431?

Done. See #4445.

**Comment by edmorley** [comment]
@Alhadis hi! Thank you for opening #4445. It seems to have only reverted the tests, rather than the logic that implements the behaviour?

**Comment by edmorley** [comment]
I've opened a follow-up, PR #4459.

**Comment by Alhadis** [comment]
Damn, sorry about that. :confused: I kind of assumed reverting a merge commit would undo everything else in a PR, but I guess not. Lesson learnt.

**Comment by billyjanitsch** [comment]
@Alhadis have you considered following suit for npm lockfiles (package-lock.json and npm-shrinkwrap.json), as suggested in the OP? It seems odd to me for Yarn's lockfiles to behave differently than npm's.

**Comment by Ghazgkull** [comment]
If the linguist maintainers prefer to treat package-lock.json files as auto-generated, is there a way for Github users to override that preference for individual repos?

**Comment by lildude** [comment]
There is… the inverse of https://github.com/github/linguist/blob/master/README.md#generated-code

**Comment by Ghazgkull** [comment]
@lildude Thanks for taking the time to reply. As a poor soul who just uses Git and isn't really familiar with Linguist, I'm not sure what the inverse of that looks like. Unless I'm missing it, that doc doesn't seem to explain how to inverse a statement.

Could I bother you for a concrete example of what I would need to add to my .gitattributes file in order to not treat package-lock.json files as auto-generated?

Something like... ?
```
!package-lock.json linguist-generated
package-lock.json !linguist-generated
package-lock.json NOT linguist-generated```

**Comment by pchaigno** [comment]
@Ghazgkull See the third example for [`linguist-detectable`](https://github.com/github/linguist/blob/master/README.md#detectable): a dash negates your attribute; `=false` should also work:
```gitattributes
package-lock.json -linguist-generated
package-lock.json linguist-generated=false
```

**Comment by silverwind** [comment]
I have to strongly disagree with marking yarn lockfiles as non-generated because that's what they are: generated by a machine, not meant for human consumption. They are certainly polluting diffs, e.g. on medium sized project a dependency update it's still a 1-2k line change.

The fact that yarn lockfile is the only lockfile that is not considered generated is rather disturbing, but I guess it may be time to migrate off of it anyways 😉.

**Comment by arcanis** [comment]
> not meant for human consumption

You're meant to review them - so insofar as you are a human, they are in part meant for human consumption.

**Comment by silverwind** [comment]
In an ideal world, yes. But realistically no one is really going to review a 2k lockfile change in a react project. If the author is trusted, I just look at `package.json` and skip over the lockfile. If not, I pull the branch and regenerate the lockfile to see if it matches the provided one.

**Comment by arcanis** [comment]
Yarn's changesets have very rarely that many changed lines - since we don't encode the recursive dependency tree via a nested structure, adding a package is often just 5-10 lines. Having more than that is actually a useful signal, since it shows that perhaps you're installing more packages than you expected.

That being said we also have more improvements in the pipeline to improve the general security even further, and having a reviewable lockfile is important to this goal.
