### ISSUE TITLE
Prolog interpreted as Perl

### ISSUE THREAD

**Issue by maebert** [github/linguist#435]
`.pl` files containing prolog code are often classified as Perl. 

Related to #394, which basically makes [the page listing the most popular Prolog repos](https://github.com/languages/Prolog) completely pointless as exactly none of the projects listed there contain any Prolog source files...

**Comment by Enerccio** [comment]
I don't think this is fixed...

**Comment by arfon** [comment]
Can you link to a file that's being incorrectly classified?

**Comment by Enerccio** [comment]
https://github.com/jansegre/jwar this one still reports perl

**Comment by arfon** [comment]
Ah ok. It hasn't been updated for over a year and language stats are only updated when a push is made to the code.

**Comment by jansegre** [comment]
I'll make a dummy push then. Thanks.

**Comment by Anniepoo** [comment]
we're accumulating a bunch of them that are misclassified again

https://github.com/search?l=perl6&p=5&q=put_attr&type=Code&utf8=%E2%9C%93

**Comment by arfon** [comment]
@Anniepoo - looks like the [`class`](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.rb#L277) keyword is causing trouble in Perl6 code: http://rubular.com/r/t6eSZ338M1

**Comment by Anniepoo** [comment]
Thanks for the quick analysis! 
Yes, both class and module are used by Prolog as well - module is particularly problematic, as module and use_module ar the Prolog equivilents of Java's package and import statements.

**Comment by Anniepoo** [comment]
got a recruit to do a fix, stay tuned

**Comment by batchmcnulty** [comment]
Great. Now it thinks one of my perl programs is a Prolog program! >:-(

**Comment by Anniepoo** [comment]
batch, can you point us at the file(s)?

Since this is still happening, reopening bug

**Comment by batchmcnulty** [comment]
Thanks - was happening to uberscan at 

[https://github.com/batchmcnulty/uberscan](https://github.com/batchmcnulty/uberscan)

but I've fixed it by adding the .gitattributes file containing this text:

`*.pl linguist-language=Perl`

which seems to fix the problem. *phew*

**Comment by Anniepoo** [comment]
Doesn't that break Uberscan for Prolog?

**Comment by Anniepoo** [comment]
Oh, neat!  I didn't know about this. 8cD will spread in prolog community.

**Comment by Anniepoo** [comment]
and re 'its not a Prolog program, so...' , yeah , I misunderstood

**Comment by lildude** [comment]
> @egryaznov from my understanding, the repository needs to receive a push to trigger linguist to run, so that one will stay like that if left untouched.

Correct. We do not go back and update the cached language stats whenever we update Linguist as this would be prohibitively resource intensive to do this for every repo on GitHub.com.  That repo hasn't been touched in over 5 years and thus shows the results of the last analysis. 

Linguist has moved on quite a bit in that time and if you fork that repo, a new analysis will be performed on the fork and you'll see the `.pl` file is correctly identified as Prolog now.

**Comment by vagman** [comment]
I still get this! Only workaround is to call your files `.prolog` but the problem here is that Visual Studio Code reads it as Plain Text then...the Prolog plugin doesn't work.

**Comment by lildude** [comment]
@vagman can you please open a new issue linking to your repo experiencing this as Prolog uses the `.pl` extension as the default now:

https://github.com/github/linguist/blob/7c2adbdb15d4efd25d92cd5ed20d0025f0d32d28/lib/linguist/languages.yml#L4262-L4275

... so if it's not detecting your files correctly, something else may be at play here.

**Comment by ProphetPX** [comment]
It's now May 2021!!!!  Hello is anything being done to fix this?  My PERL files are showing up as Prolog just simply because they have a .pl filename extension! :(  https://github.com/ProphetPX/PF1eCharBuilder/

**Comment by pmoura** [comment]
@ProphetPX Poetic justice? Given that Prolog was using the `.pl` extension long before Perl was created? 😛 Kidding aside, a quick fix is for you to add a `.gitattributes` to the root of your repo with the following contents:

```text
*.pl  linguist-language=Perl
```

You may need to push some commits to this solution to take effect, however. Hope this helps.
