### ISSUE TITLE
Kotlin single quoted double quote breaks highlight

### ISSUE THREAD

**Issue by TWiStErRob** [github/linguist#4361]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

`'"'` seems to start a new String literal, instead of being recognized as a character literal. See how most of the code is blue:
![image](https://user-images.githubusercontent.com/2906988/50450731-a51c9880-0927-11e9-99eb-91cf7cad583c.png)

### URL of the affected repository:
https://github.com/holgerbrandl/kscript/blob/c9f515ed3bb7855dd325b35672311e803aa9312a/src/main/kotlin/kscript/app/Script.kt#L166

### Last modified on:
See holgerbrandl/kscript@c9f515ed3bb7855dd325b35672311e803aa9312a

### Expected language:
Kotlin

### Detected language:
Kotlin

**Comment by TWiStErRob** [comment]
May have been the wrong repo, also opened https://github.com/nishtahir/language-kotlin/issues/10

**Comment by pchaigno** [comment]
Closing in favor of nishtahir/language-kotlin#10. We will automatically catch the fix once fixed upstream.
