### ISSUE TITLE
GDScript highlighting breaks on signal token

### ISSUE THREAD

**Issue by schweigert** [github/linguist#4364]
GDScript view is breaking with this script:

![image](https://user-images.githubusercontent.com/13274722/50500171-983a9a80-0a36-11e9-976a-60d81179badf.png)

## Preliminary Steps

Please confirm you have...
- [ ] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [ ] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [ ] considered implementing an [override](https://github.com/github/linguist#overrides),
- [ ] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

I do not know the location that describes the syntax for gdscript, since the atom has no native support for this language.

**Comment by pchaigno** [comment]
> since the atom has no native support for this language.

Which atom are you talking about?

I think you should read the troubleshooting docs.

**Comment by schweigert** [comment]
The CSharp coloration comes from an atom library, however there is no native coloring library for GDScript syntax, only on github. I can not find the repository to which I can report this bug.

**Comment by pchaigno** [comment]
From the Troubleshooting docs:

> Linguist detects the language of a file but the actual syntax-highlighting is powered by a set of language grammars which are included in this project as a set of submodules [as listed here](/vendor/README.md).

Is the wording unclear? Should we improve it?
