### ISSUE TITLE
OSAscript JS is detected incorrectly

### ISSUE THREAD

**Issue by Gaelan** [github/linguist#4366]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

In addition to AppleScript, Apple also allows JavaScript to be used for desktop automation. Such scripts can be executed with `#!/usr/bin/env osascript -l JavaScript`. Linguist incorrectly identifies this as an AppleScript shebang.

### URL of the affected repository:
https://github.com/Gaelan/WordGit

### Last modified on:
2018-05-30

### Expected language:
JavaScript

### Detected language:
AppleScript

**Comment by Gaelan** [comment]
How hard would it be to detect args to the shebang interpreter?

**Comment by pchaigno** [comment]
Not very, but I'm not sure it's worth adding that complexity to the code to accommodate the specific case of one interpreter. Same for the heuristic rules: we could change them to allow for candidate languages as indexes, but I'm not sure it's going to be useful to any other language...

**Comment by Alhadis** [comment]
> @Alhadis Other ideas?

Whoops, I completely missed this.

None, I'm afraid. 😞  The first and only thing I could think of was letting heuristics disambiguate between two languages with the same interpreter, but you mentioned how that's not currently possible...

@Gaelan Does `osascript` require all JavaScript files to declare a function named `run`? If so, we could add a heuristic to match against that.

**Comment by Gaelan** [comment]
@Alhadis Sadly, no. It's the only way to get a hold of `argv`, but if you don't use command line args then you don't need it.

**Comment by Gaelan** [comment]
Not that it's a big deal, but this is still a bug.

**Comment by lildude** [comment]
> @lildude @Alhadis Other ideas?

Completely forgot to come back to this one. Yup, extend the shebang strategy to look for `-l (Java|Apple)Script` is the only way I can think of - like [this](https://github.com/github/linguist/compare/master...lildude/osascript-shebang)

**Comment by lildude** [comment]
Oh wait, that won't work as "JavaScript" and "AppleScript" aren't interpreters.

**Comment by Gaelan** [comment]
Not fixed yet.

**Comment by Alhadis** [comment]
@lildude, how're you tracking with the fix?

**Comment by lildude** [comment]
> @lildude, how're you tracking with the fix?

Whoops. Got distr.... oh look, a kite 😄
