### ISSUE TITLE
Colours need borders

### ISSUE THREAD

**Issue by mxplusb** [github/linguist#4380]
## Preliminary Steps

Please confirm you have...
- [X] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Similar colours are hard to distinguish. This was originally brought up in github/linguist#4331, where @Alhadis recommended creating a colour border to really help distinguish the differences. I agree with his idea and wanted to file this issue to start a discussion about that idea.

**Comment by pchaigno** [comment]
As far as I know, this was [already implemented and shipped](https://blog.github.com/changelog/2019-01-09-more-readable-repository-language-bar/).

**Comment by Alhadis** [comment]
He's right. What exactly is there to discuss? :confused

**Comment by RobQuistNL** [comment]
The borders are there, like this:
![image](https://user-images.githubusercontent.com/1442796/51181856-9c870480-18cc-11e9-8868-855ece124310.png)

I think what @mxplusb means, is defining actual border colours - but I doubt if thats going to add anything..
