### ISSUE TITLE
what happens if upstream grammar repository is dead but has bug ?

### ISSUE THREAD

**Issue by thechile** [github/linguist#4382]
General question, for the SLS grammar it doesn't work correctly with comment blocks. Seems the upstream has not been touched in 5 years even though MR were submitted that could resolve the problem i mention. 

So if we need to report the issue to the upstream grammar repository, not here, but that leads nowhere.. what is the next steps/advice please ?

many thanks.

**Comment by thechile** [comment]
sorry.. i meant this one:

> SaltStack: saltstack/atom-salt

As an example of the problem [here](https://gist.github.com/whiteinge/1bf3b1fa525c2e883b805f271ec6f7d7) the multi-line code blocks within `{# ... #}` only apply the comment css to the first line.  

thanks.

**Comment by pchaigno** [comment]
Ok. And the open pull request on that repository would solve the issue?

**Comment by thechile** [comment]
https://github.com/saltstack/atom-salt/pull/2 

looking at `atom-jinja2` code it should handle the comments as expected.

**Comment by thechile** [comment]
as it turns out that never fixed it either, but i have a working grammar with my own regex changes that has been tested in Lightshow. Going back to the original question if the upstream isn't maintained or merging requests.. how to proceed ? Fork it with my changes and request Linguist change ?

**Comment by pchaigno** [comment]
Please send a pull request upstream to the grammar first. If you don't get an answer either, and if you're ready to maintain the grammar yourself, we can consider switching to your fork.

**Comment by Alhadis** [comment]
I formally declare @pchaigno the rightful owner of all my grammar repositories should I die a sudden death.

**Comment by thechile** [comment]
mm ok , i hit a bit of a snag.

the grammar in question uses `      {
        'include': 'source.python'
      }` which in turn has its own `#` related comment pattern and seems to be clobbering the locally defined pattern. And i have no idea how to make the local defined pattern with updated/fixed regex take precedence.
