### ISSUE TITLE
Tests: assert_heuristics does not fail on missing samples

### ISSUE THREAD

**Issue by bzz** [github/linguist#4391]
Discovered as part of work on disambiguate `.ice` by heuristics under #4376 #4243 

A [test](https://github.com/github/linguist/pull/4243#issuecomment-423562889) that supposed to be checking disambiguation by heuristics between `.ice` JSON and Slice was failing silently due to empty fixture at [test_heuristics.rb#L194](https://github.com/github/linguist/blob/4d8d65eb5d342f6df5f7dc65b9f7bb4fea31e434/test/test_heuristics.rb#L194). 
Fixture was empty  because there were no samples of `.ice` files in JSON dir.

That could be caught by a 2 LoC change at `assert_heuristics` helper that can notify about such cases e.g:
```ruby
  def assert_heuristics(hash)
    hash.each do |language, blobs|
      Array(blobs).each do |blob|
        ...
      end.empty? and begin
        flunk "Failed for #{language}: nothing to run"
      end
    end
  end
```

but doing that triggers 8 potentially similar cases (in details) that I did not have time to examine.

Please, let me know what you think what would be the best approach here!

<details>

```
 1) Failure:
TestHeuristics#test_builds_by_heuristics [test/test_heuristics.rb:81]:
Failed for Text: nothing to run

  2) Failure:
TestHeuristics#test_ch_by_heuristics [test/test_heuristics.rb:88]:
Failed for xBase: nothing to run

  3) Failure:
TestHeuristics#test_pm_by_heuristics [test/test_heuristics.rb:327]:
Failed for XPM: nothing to run

  4) Failure:
TestHeuristics#test_x_by_heuristics [test/test_heuristics.rb:475]:
Failed for Linked Script: nothing to run

  5) Failure:
TestHeuristics#test_ml_by_heuristics [test/test_heuristics.rb:258]:
Failed for Standard ML: nothing to run

  6) Failure:
TestHeuristics#test_ncl_by_heuristics [test/test_heuristics.rb:293]:
Failed for NCL: nothing to run

  7) Failure:
TestHeuristics#test_props_by_heuristics [test/test_heuristics.rb:361]:
Failed for INI: nothing to run

  8) Failure:
TestHeuristics#test_h_by_heuristics [test/test_heuristics.rb:179]:
Failed for C: nothing to run
```
</details>

**Comment by pchaigno** [comment]
@ stalebot #4410 should fix this. We should teach you to recognize issues that are going fixed by a pending pull request...
