### ISSUE TITLE
bin/github-linguist:27:in `new': could not find repository from '[dir]' (Rugged::RepositoryError)

### ISSUE THREAD

**Issue by davidhq** [github/linguist#4392]
I'm testing `linguist` locally, trying just the `github-linguist` command at various places with my code, it works on most directories.

I noticed it sometimes fails with this message:

```
/.gem/ruby/2.3.3/gems/github-linguist-7.1.3/bin/github-linguist:27:in `new': could not find repository from '~/Desktop/examples' (Rugged::RepositoryError)
	from /Users/david/.gem/ruby/2.3.3/gems/github-linguist-7.1.3/bin/github-linguist:27:in `<top (required)>'
	from /Users/david/.gem/ruby/2.3.3/bin/github-linguist:22:in `load'
	from /Users/david/.gem/ruby/2.3.3/bin/github-linguist:22:in `<main>'
```

I isolated the simplest possible example here:

```
~/Desktop/examples$ tree
.
└── new_contract.sol
```

Is there any other info I can provide to try to troubleshoot this?

I'm exploring this package to figure out why it isn't highlighting some Solidity code and thus I want to explore further to be able to show you where the other possible problem is...

thank you

**Comment by pchaigno** [comment]
Is `~/Desktop/examples` a git repository?

**Comment by davidhq** [comment]
No. So this is the reason.. I checked README again, it does actually indicate it should be run inside a repository, but it's not especially emphasized... Is there a specific reason for this? Just asking... probably it is.

I have another question at this point if maybe we can use this thread to find the other issue, namely:

(this)[https://github.com/makerdao/sai/blob/master/src/mom.sol]

vs

(this)[https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/cryptography/ECDSA.sol] 

Not sure why syntax highlighting doesn't work on the first... wanted to check this out and see if I can replicate locally on command line... I'll try this now and thank you. If we should open a new thread (now or later), I'll do it...
