### ISSUE TITLE
Linguist missing languages

### ISSUE THREAD

**Issue by lgmagalhaes88** [github/linguist#4396]
## Preliminary Steps

Please confirm you have...
- [X] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [X] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [X] considered implementing an [override](https://github.com/github/linguist#overrides),
- [X] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
My [repo](https://github.com/lgmagalhaes88/herobot) has typescript, javascript and shell languages. But it only display typescript and "Other".  Getting in github api, I received that the repository is made by

```json
{
  "TypeScript": 66324,
  "JavaScript": 509,
  "Shell": 144
}
```
May be it's just the linguist job that has not passed in the repository yet ?

### URL of the affected repository:

https://github.com/lgmagalhaes88/herobot

### Last modified on:
2019-01-29

### Expected language:
TypeScript, JavaScript, Shell

### Detected language:
TypeScript, Other

**Comment by lgmagalhaes88** [comment]
Hmm. I got it. Thanks so much for the help!

 So I have, TypeScript 99% Shell 0.2% and Javascript 0.7%.
But I have a repo with this languages:

![image](https://user-images.githubusercontent.com/19666463/51941088-de4e9980-23fa-11e9-9f43-858807fd4129.png)

In this repo Shell language is displayed because there are only 2 languages ?

**Comment by Alhadis** [comment]
Ah, yes. =) Basically, if there are too many languages squashed together at the back of the language bar, and none of them are spread far enough apart to have enough room to show their names.... they just get squashed together as "Other".

If you click one of the labels, though, it'll bring up a more detailed listing of every file/language used in your repository, so you can see everything that's been buried and hidden under the "Other" umbrella. 😉

**Comment by Alhadis** [comment]
[See?](https://github.com/lgmagalhaes88/herobot/search?l=typescript)

![screen shot 2019-01-30 at 8 47 48 am](https://user-images.githubusercontent.com/2346707/51942652-bea38980-246b-11e9-85af-45dceae83479.png)

**Comment by lgmagalhaes88** [comment]
Yees. It's i little sad (I would like to see the three languages 😄). But it's ok. Thank you so much!

**Comment by Alhadis** [comment]
Write more shell and JavaScript then! 😉
