### ISSUE TITLE
Generated ANTLR files

### ISSUE THREAD

**Issue by pchaigno** [github/linguist#4409]
Just a reminder for myself to do it later. It's also a good first issue for beginners with Linguist.

From [#4404](https://github.com/github/linguist/pull/4404#issuecomment-460610853):

> Many of these files seem to be generated: https://github.com/search?q=extension%3Ag+%22generated+by+xtext%22&type=Code. Maybe we should add that to the `generated.rb` file? (I can do it in a separate pull request if you prefer.)

The solution is to add the appropriate code in `lib/linguist/generated.rb` to recognize these files as generated.

**Comment by Nixinova** [comment]
Should this still be done?

**Comment by Nixinova** [comment]
Added in #5199, can be closed
