### ISSUE TITLE
Repository language being misclassfied. Link- https://github.com/Aashishmandyaanilkumar/R-with-Statistics-for-predictive-analytics

### ISSUE THREAD

**Issue by aashish2020** [github/linguist#4414]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

### URL of the affected repository:
https://github.com/Aashishmandyaanilkumar/R-with-Statistics-for-predictive-analytics

**Comment by pchaigno** [comment]
Please fill in the issue template.

**Comment by aashish2020** [comment]
> Please fill in the issue template.

Repository language being misclassfied. Link- https://github.com/Aashishmandyaanilkumar/R-with-Statistics-for-predictive-analytics

**Comment by pchaigno** [comment]
Looks like [this file](https://github.com/aashish2020/R-with-Statistics-for-predictive-analytics/blob/6585847237f7fb2d44602fc5e1bf784dcf7ec2e8/Logistics%20regression%20in%20Rmarkdown/My_first_Markdown.html) is making the whole 95.7% of HTML. You can add an override to tell Linguist to ignore it or consider it documentation.
