### ISSUE TITLE
Solidity color syntax not longer appearing in GitHub.

### ISSUE THREAD

**Issue by tomasaftalion** [github/linguist#4422]
## Problem Description
/.gitattributes
```
*.sol linguist-language=Solidity
```
This approach no longer highlights in GitHub. Having this issue on my private repo, however checked that it is also occurring in [OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-solidity) (one of the authorities in the language itself).

### URL of the affected repository:
https://github.com/OpenZeppelin/openzeppelin-solidity

### Last modified on:
2019-02-06 (when I first noticed)

Thank you.

**Comment by pchaigno** [comment]
This is being discussed in [#3973 (Comment)](https://github.com/github/linguist/pull/3973#issuecomment-461797745) and should be fixed with a quick release soon.
