### ISSUE TITLE
Linguist cannot set my projects language

### ISSUE THREAD

**Issue by BuoYancYdabl** [github/linguist#4426]
I have a little project here: https://github.com/BuoYancYdabl/Buoyancy-s-Cleanup-Detail/blob/master/Buoyancy's%20Cleanup%20Detail and linguist cannot find language for my project. Im use a "Lua" with API of other programm (TIC-80).

Last modified 2019-02-16

Expected language is Lua

No unexpected languages

If it will be usefull i can send all custom API's.

**Comment by pchaigno** [comment]
Please read the README.

**Comment by BuoYancYdabl** [comment]
@pchaigno, i need to install it before use?

**Comment by pchaigno** [comment]
I'm not sure what you mean. You can read the README on this repository without installing Linguist.

**Comment by BuoYancYdabl** [comment]
Okay, thanks, im think i understood what issue is.
