### ISSUE TITLE
*.v linguist-language=Go doesn't work

### ISSUE THREAD

**Issue by medvednikov** [github/linguist#4431]
Hi,

I tried all possible combinations:
```
*.v linguist-language=Go
examples/*.v linguist-language=Go
* linguist-language=Go
*.* linguist-language=Go
```

No luck:
https://github.com/vlang-io/V/blob/master/.gitattributes
https://github.com/vlang-io/V/blob/master/examples/users.v

Thanks!

**Comment by lildude** [comment]
What's wrong with the template we provided? 😢

As for why this isn't working, well, you've read this already 😉 ... https://github.com/github/linguist#documentation
