### ISSUE TITLE
Wrong language detected

### ISSUE THREAD

**Issue by YuanWenqing** [github/linguist#4432]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Only one html file included in `test/resources` for unit test, but it seems like a lot of html code is detected

### URL of the affected repository:
https://github.com/YuanWenqing/product
### Last modified on:

2019-02-22

### Expected language:

java
### Detected language:

 Java 55.2%	 HTML 44.8%

**Comment by lildude** [comment]
> Only one html file included in `test/resources` for unit test, but it seems like a lot of html code is detected

Your repo is private so I can't check, but the likely cause is the size of that test file. As "How Linguist Works" in the README states (and you've acknowledged reading 😉):

> The percentages are calculated based on the _**bytes of code**_ for each language as reported by the List Languages API.

So if that one file is nearly as large as all your Java combined, the stats will show it having a high proportion. If you don't want this, you'll need write more Java to use an override.

**Comment by YuanWenqing** [comment]
I already added a `.gitattributes` file, but nothing changed

**Comment by lildude** [comment]
What did you put in your file? Remember, we can't see your repo so you need to be very clear about what you've done.

**Comment by YuanWenqing** [comment]
Finally, I rename the html file as a txt file. Now everything seems fine.

Thanks!!

**Comment by poikilos** [comment]
The real solution is to put something like this in your .gitattributes file:
```
*.html -linguist-detectable
```

- That prevents linguist from considering html files (the minus sign indicates NOT linguist-detectable).
- For generated files (does not seem to apply here), the more accurate option would be: `*.html linguist-generated`
- For more overrides, see <https://github.com/github/linguist#overrides>
