### ISSUE TITLE
Some of my repositories aren't showing my languages

### ISSUE THREAD

**Issue by nwtgck** [github/linguist#4436]
Hi, developers! Thank you very much for GitHub!

Recently, my repositories aren't showing my languages. I don't know the reason. **A repository was made over 20 days before, but it isn't showing my language**.

## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [ ] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Recently, my repositories aren't showing my languages.
Some of my repositories look like the following image.
<img width="1018" alt="screen shot 2019-02-25 at 14 07 24" src="https://user-images.githubusercontent.com/10933561/53315498-d6edb380-3906-11e9-9004-04437ef30fc0.png">

### URL of the affected repository:

Here is **public repositoies** affected.
* [nwtgck/verbose](https://github.com/nwtgck/verbose) (made over 20 days before)
* [nwtgck/hub-purge-dockerfile](https://github.com/nwtgck/hub-purge-dockerfile) (made about 8 month before)
* [nwtgck/h2database-dockerfile](https://github.com/nwtgck/h2database-dockerfile)
* [nwtgck/nachos-build-dockerfile](https://github.com/nwtgck/nachos-build-dockerfile)

Probably, some docker repos were created before Docker had the language rate.
**I couldn't list private repos**, but some private repos are also not showing my languages.

### Expected language:

I tried `github-linguist` in nwtgck/verbose. I had the following.

```
$ github-linguist
Ignoring executable-hooks-1.4.2 because its extensions are not built. Try: gem pristine executable-hooks --version 1.4.2
Ignoring gem-wrappers-1.3.2 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.3.2
100.00% Go
```

**Comment by Alhadis** [comment]
Okay, erm, that *definitely* shouldn't be happening. Looks like a server-side issue, not with Linguist itself.

/cc @lildude

**Comment by nwtgck** [comment]
@Alhadis Thank you. Should I close the issue and report by [Contact GitHub](https://github.com/contact)?

**Comment by Alhadis** [comment]
Actually hold on, I noticed each of these repositories have a different default branch to `master`.

Did you change the main branch recently? The `verbose` repository in particular has a `master` branch [that's detached](https://github.com/nwtgck/verbose/tree/master) from the main one (called "develop").

**Comment by nwtgck** [comment]
@Alhadis 

> Did you change the main branch recently?

My answer is "yes" and also "no". I changed main branch to `develop` 20 days before. But I found `verbose` still has no language rate yeasterday. So I toggled `develop` => `master` => `develop` because I thought it works well.

**Comment by Alhadis** [comment]
Sometimes it takes a push to one's branch to force a refresh of the language bar.

Other times, it's a caching issue caused by something server-side. I'm not staff, so I've no way of discerning which. 😞

**Comment by nwtgck** [comment]
@Alhadis 

> Sometimes it takes a push to one's branch to force a refresh of the language bar.

Thank you for the useful information to understand how it works! Probably, repos I listed above and some of my private repos were developed almost things locally and push to GitHub and just change the main branch to `develop`, and there was no push after the first GitHub push maybe. 

Maybe, I should try to continue to develop the repos and push something.

**Comment by abhimax** [comment]
You have changed the default branch main to master. It will be fixed after the git push with a small change.
