### ISSUE TITLE
bootstrap and fontawesome getting included in the language classification stats

### ISSUE THREAD

**Issue by Ferido07** [github/linguist#4441]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

### Detected language: CSS and Javascript

Linguist is not ignoring bootstrap and font awesome files under  
 -  /src/main/resources/static/vendor/bootstrap/css/
 - /src/main/resources/static/vendor/bootstrap/js/
 - /src/main/resources/static/vendor/fontawesome/css/

I have checked the vendor.yml and I see it does not match the criteria for bootstrap nor font-awesome and I have tried to add a different directory structure for bootstrap and font-awesome, and also added directory structure for vendor files in maven based java projects. I created a [pull request](https://github.com/github/linguist/pull/4440) hope it helps.

**Comment by lildude** [comment]
> Linguist is not ignoring bootstrap and font awesome files under

It most certainly is. Those aren't the only CSS and Javascript files in your repo. These are the ones Linguist is detecting and reporting on:

```console
$ github-linguist oms --breakdown
53.98%  Java
35.51%  HTML
9.64%   JavaScript
0.87%   CSS

Java:
src/main/java/com/kft/OmsApplication.java
[... truncated for brevity ...]

CSS:
src/main/resources/static/css/autocomplete.css
src/main/resources/static/css/offence-code-list.css
src/main/resources/static/css/offence-form.css

JavaScript:
src/main/resources/static/js/layout.js
src/main/resources/static/js/offence-form.js
src/main/resources/static/js/offence-list.js
src/main/resources/static/js/offence-show.js

HTML:
src/main/resources/templates/association/list.html
src/main/resources/templates/driver/list.html
src/main/resources/templates/layout.html
src/main/resources/templates/offence-code/list.html
src/main/resources/templates/offence/form.html
src/main/resources/templates/offence/list.html
src/main/resources/templates/offence/show.html
src/main/resources/templates/offence/status.html
src/main/resources/templates/offender/offence-list.html
src/main/resources/templates/vehicle/list.html
$
```

As you can see, _none_ of them are in bootstrap or fontawesome, both of which are correctly ignored thanks to:

https://github.com/github/linguist/blob/e4560984058b4726010ca4b8f03ed9d0f8f464db/lib/linguist/vendor.yml#L89-L93

**Comment by Ferido07** [comment]
But that is not what I'm looking at I have attached the screenshots below.
And I have recently added a .gitignore for linguist-vendored after posting the issue.

![screenshot 253](https://user-images.githubusercontent.com/22884375/53562722-2e885b00-3b63-11e9-9f57-4d1d3bcfec54.png)  

![screenshot 255](https://user-images.githubusercontent.com/22884375/53562733-3942f000-3b63-11e9-94b0-0f9d9932c67c.png)  

![screenshot 254](https://user-images.githubusercontent.com/22884375/53562784-5c6d9f80-3b63-11e9-8894-a9f750aa827a.png)

**Comment by lildude** [comment]
> But that is not what I'm looking at

Ah, ok. We're looking at two different things here.

First off, it does indeed appear the bootstrap and fontawesome paths were being included in the initial language stats - I completely missed you'd already added an override when I looked at your repo. Your language bar hasn't updated to reflect this as there is a known limitation in that `.gitattributes` changes don't currently kick off a re-analysis job, and you've not made any changes since adding the overrides. As soon as you push a change, you should see your language bar updated.

As for the two different things... your second and third screenshots are showing what Search has indexed (ie  _all_ of the files in your repo) and displaying the results of that indexing, independently from what Linguist has done. Linguist attributes in `.gitattributes` will have no influence over Search as you can see in the copy (not fork) I make of your repo at https://github.com/lildude/oms:

I've got the updated language bar:

![langbar](https://user-images.githubusercontent.com/627280/53564496-f7a84a00-3b4e-11e9-9c39-3d139434b001.png)

... and the search results continue to show all CSS files, including the bootstrap and fontawesome files - https://github.com/lildude/oms/search?l=CSS

**Comment by Ferido07** [comment]
Ok I've got your point that the search and the stats are independent but it seems like the search shows the breakdown of the stats since I reach the page through the stats. My bad didn't know.

And I have read in the documentation of linguist that it starts a low priority job when pushing updates and so I wasn't expecting it to update soon. But now I know that adding .gitignore doesn't even start the job so then I wont be expecting a change until  after I push an update and then wait for the stat breakdown job of linguist to complete.

Did I get it right?

**Comment by lildude** [comment]
> Ok I've got your point that the search and the stats are independent but it seems like the search shows the breakdown of the stats since I reach the page through the stats. My bad didn't know.

Yeah, this is a little confusing and definitely not your fault.

> But now I know that adding .gitignore doesn't even start the job so then I wont be expecting a change until after I push an update and then wait for the stat breakdown job of linguist to complete.
> 
> Did I get it right?

Yup.

**Comment by Ferido07** [comment]
Ok thanks.

**Comment by pchaigno** [comment]
I think we should clarify that sentence in the README:

> When you push changes to a repository on GitHub.com, a low priority background job is enqueued to analyze your repository as explained above.

As @Ferido07 noted, it's misleading. Some changes do not trigger the background job.

@Ferido07 Do you want to take a stab at it?

**Comment by Ferido07** [comment]
>>But now I know that adding .gitignore doesn't even start the job so then I wont be expecting a change >>until after I push an update and then wait for the stat breakdown job of linguist to complete.
>>
>>Did I get it right?
>
>Yup

@lildude But now the stats have updated to match those you got on your copy without me pushing any new commits.

**Comment by Ferido07** [comment]
@pchaigno I'll try my best once I understand when exactly the updates are made. Because if you see in my previous comment I just observed another unexpected behavior contrary to what @lildude said.

**Comment by lildude** [comment]
> @lildude But now the stats have updated to match those you got on your copy without me pushing any new commits.

Ah, that'll be due to some caching changes that happened this week on GitHub.com. This is most definitely not a normal or regular occurrence... you're just lucky we happened to be working on the cache this week 😁
