### ISSUE TITLE
javascript files not showing when clicking javascript on statistics bar

### ISSUE THREAD

**Issue by myyron** [github/linguist#4442]
Steps to reproduce:
1. Click javascript % on statistics bar
2. Next page will show "Couldnt find any code matching '' in <repo>"

Ref repo:
myyron/cogz-web

**Comment by lildude** [comment]
What's wrong with our template? This issue looks so bare without it and it's very very 😭 not to have it.

That said, this is _not_ a Linguist issue. This is a problem with the Search side of GitHub. Please contact GitHub support to report this issue.

**Comment by myyron** [comment]
sorry about that, was on mobile when i filed the issue and just want to inform you guys of what i have encountered. thanks.
