### ISSUE TITLE
Shebang detection when arguments to the shebang have a = in them

### ISSUE THREAD

**Issue by delfick** [github/linguist#4447]
It seems this line here https://github.com/github/linguist/blob/master/lib/linguist/shebang.rb#L42 is causing my python shebang to not be recognised because the options I give to `#!/usr/bin/env python` has an = in it.

## Problem Description
I have a pattern in my repository where I use the following shebang in the file:

```
#!/usr/bin/env python -cos=__import__("os");sys=__import__("sys");python=os.path.join(os.path.dirname(sys.argv[1]),".lifx/bin/python");os.execv(python,sys.argv)
```

This basically says use python to find the python in the virtualenv in that folder and use that to exec this file.

I don't want to add .py to these scripts cause I want all the scripts in there to just be commands you run and some of them are just bash rather than python.

This hack means I don't have to know to run the script with the python in the virtualenv and because of the /usr/bin/env python, my editor knows the file is actually python.

It seems however that linguist scans past the python in the string because the argument has an = sign in it.

### URL of the affected repository:
https://github.com/delfick/photons-core/blob/master/scripts/info

### Expected language:
Python

### Detected language:
None

**Comment by delfick** [comment]
I still would like this issue looked at.

I'd offer a fix myself but I'm unsure why `s.scan(/.*=[^\s]+\s+/) # skip over variable arguments e.g. foo=bar` is necessary.

**Comment by Alhadis** [comment]
>  I'm unsure why `s.scan(/.*=[^\s]+\s+/) # skip over variable arguments e.g. foo=bar` is necessary.

@delfick It's to prevent misinterpretation of something like `#!/usr/bin/env perl foo=python"` or `#!/usr/bin/perl foo=python` and the like.

I haven't looked into *precisely* why your hashbang isn't being matched, but I should warn you as an aside that passing switches to interpretator directives isn't portable, as not every shell or `env(1)` implementation will look past the second argument.

**Comment by delfick** [comment]
Yeah, I did end up having problems with linux that led to this change https://github.com/delfick/photons-core/commit/4332030db517fb6e0becc5a21b5b27798d607415

As for the code, as far as I can tell it only matches if we're using /usr/bin/env and in which case we can just look for the first word after the first space?

Also in the case of `#!/usr/bin/env perl foo=python` I imagine that won't determine perl is the script either because it scans to after foo=python before working out what the script is?

**Comment by delfick** [comment]
The good news is I just realised my original problem isn't there anymore given that commit I mentioned.....

**Comment by Alhadis** [comment]
>  I imagine that won't determine perl is the script either because it scans to after foo=python before working out what the script is?

Nope, because the first argument passed to `env` is supposed to be the name of an interpreter. We make an exception for `env` in the hashbang-matching logic because it is isn't a language interpreter; it simply picks one that is.

Hashbangs can also be written like `#!/usr/bin/python`, in when that's the case, Linguist stops parsing anything after the command's name, and simply uses that as the interpreter.

Hope that makes sense. :)

**Comment by delfick** [comment]
Yeah, that's my understanding. I'm saying that in the example of `#!/usr/bin/env perl foo=python` the `s.scan(/.*=[^\s]+\s+/)` will mean it scans past foo=python before the next line of `script = s.scan(/\S+/)` scans an empty string. If the example was `#!/usr/bin/env foo=python perl` then it would determine the script is perl. But unless I'm mistaken that's not how /usr/bin/env works....

**Comment by lildude** [comment]
> Nope, because the first argument passed to `env` is supposed to be the name of an interpreter.

Not necessarily. More coming up...

> Yeah, that's my understanding. I'm saying that in the example of #!/usr/bin/env perl foo=python the s.scan(/.*=[^\s]+\s+/) will mean it scans past foo=python before the next line of script = s.scan(/\S+/) scans an empty string.

Correct and this is essentially the cause of your issue.

> If the example was `#!/usr/bin/env foo=python perl` then it would determine the script is perl. But unless I'm mistaken that's not how /usr/bin/env works....

You are indeed mistaken and correct with your first interpretation 😉 If the `foo=boo` is before the interpreter it is passed as an environment variable.  From the env man page on macOS:

> The env utility executes another utility after modifying the environment as specified on the command line.  Each name=value option specifies the setting of an environment variable, name, with a value of value.  All such environment variables are set before the utility is executed.

This is easy to illustrate too:

```console
$ uname
Darwin
$ /usr/bin/env foo="bar" bash -c "env | grep foo"
foo=bar
$
```

And this applies to Linux too:

```console
$ uname
Linux
$ /usr/bin/env foo="bar" bash -c "env | grep foo"
foo=bar
$
```

So to answer your point @delfick :

> I'd offer a fix myself but I'm unsure why `s.scan(/.*=[^\s]+\s+/) # skip over variable arguments e.g. foo=bar` is necessary.

Now you do 😁 

How we resolve this? Well that's a challenge I can't think of a solution right now as we need to skip over _all_ instances of `foo=bar` before the interpreter (you can have more than one) and determining when these stop and the unknown interpreter begins is where things get tricky and can lead to a pretty complex regex.

I can however say that you're the first to raise this as an issue 👏, though it's no longer an issue.

**Comment by pchaigno** [comment]
Can't we just restrict
https://github.com/github/linguist/blob/bf95666fc15e49d556f2def4d0a85338423c25f3/lib/linguist/shebang.rb#L42
to be
```ruby
s.scan(/[^\s]+=[^\s]+\s+/)
```
and then iterate:
```ruby
s.scan(/([^\s]+=[^\s]+\s+)*/)
```
?

**Comment by lildude** [comment]
Oooo, good idea @pchaigno and from a quick test, it seems to do the trick:

```console
$ /bin/cat ~/tmp/trash/verbose-enigma/info
#!/usr/bin/env python -cos=__import__("os");sys=__import__("sys");python=os.path.join(os.path.dirname(sys.argv[1]),".lifx/bin/python");os.execv(python,sys.argv)

$
$ bundle exec github-linguist ~/tmp/trash/verbose-enigma/info
info: 2 lines (1 sloc)
  type:      Text
  mime type: text/plain
  language:  Python
$
$ /bin/cat ~/tmp/trash/verbose-enigma/info
#!/usr/bin/env foo=bar bar=foo python -cos=__import__("os");sys=__import__("sys");python=os.path.join(os.path.dirname(sys.argv[1]),".lifx/bin/python");os.execv(python,sys.argv)

$
$ bundle exec github-linguist ~/tmp/trash/verbose-enigma/info
info: 2 lines (1 sloc)
  type:      Text
  mime type: text/plain
  language:  Python
$
$ /bin/cat ~/tmp/trash/verbose-enigma/info 
#!/usr/bin/env foo=bar bar=foo bash

$
$ bundle exec github-linguist ~/tmp/trash/verbose-enigma/info
info: 2 lines (1 sloc)
  type:      Text
  mime type: text/plain
  language:  Shell
$
```

It's always the simplest solutions I overlook.

👏 👏

**Comment by lildude** [comment]
For reference, this was the change:

```diff
diff --git a/lib/linguist/shebang.rb b/lib/linguist/shebang.rb
index 7d1c0e8c..f5313196 100644
--- a/lib/linguist/shebang.rb
+++ b/lib/linguist/shebang.rb
@@ -39,7 +39,7 @@ module Linguist
       # if /usr/bin/env type shebang then walk the string
       if script == 'env'
         s.scan(/\s+/)
-        s.scan(/.*=[^\s]+\s+/) # skip over variable arguments e.g. foo=bar
+        s.scan(/([^\s]+=[^\s]+\s+)*/) # skip over variable arguments e.g. foo=bar
         script = s.scan(/\S+/)
       end
 ```

**Comment by lildude** [comment]
PR on its way

**Comment by lildude** [comment]
Done. ☝️

**Comment by delfick** [comment]
Awesome! Thanks so much!
