### ISSUE TITLE
Vue.js language color

### ISSUE THREAD

**Issue by shrpne** [github/linguist#4448]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
I think Vue language color should be changed.
Now it is gray with blue tone: #2c3e50.
But primary color on the https://vuejs.org/ website and Vue logo is green: #42b983

**Comment by lildude** [comment]
> But primary color on the https://vuejs.org/ website and Vue logo is green: #42b983

Not quite... the text logo in the top left is actually `#2c3e50`:

![vue js 2019-03-06 11-12-52](https://user-images.githubusercontent.com/627280/53877370-e2289980-4000-11e9-9d22-5488c7224334.png)

... and from the original PR that added support for Vue - https://github.com/github/linguist/pull/2513#issuecomment-123480804 - that colour was chosen as `#42b983` is too close to another already in use by Linguist.

We're currently waiting on GitHub's design team to see if we can remove this proximity check so languages can have their brand colours, but until such time as that has been approved, such a change is not going to be possible.

Additionally, if we were to change the colour, we will require some sort of brand guidelines and community consensus (the Vue community in this case) on the change before we do so, especially for languages like Vue that have had the same colour for many years. Many people have grown to love the colours currently used and get quite upset when these change without rhyme or reason or community consensus.

**Comment by shrpne** [comment]
Well, as I can see, it's the color of titles and leadings.
![image](https://user-images.githubusercontent.com/392907/53883546-53307700-402a-11e9-8224-4d3fdeb47856.png)
This color looks like base text color for me and I can't associate it with Vue.
I hope this color conflict with other languages will be resolved somehow. Thank you!

**Comment by shrpne** [comment]
> We're currently waiting on GitHub's design team to see if we can remove this proximity check so languages can have their brand colours
So I think we are still waiting

**Comment by lildude** [comment]
That's not gonna change any time soon. We're more waiting on:

> Additionally, if we were to change the colour, we will require some sort of brand guidelines and community consensus (the Vue community in this case) on the change before we do so, especially for languages like Vue that have had the same colour for many years. Many people have grown to love the colours currently used and get quite upset when these change without rhyme or reason or community consensus.

There has been no indication that the community has been consulted about this change.

If this has been discussed and approved, we'd like to a link to that discussion showing the consensus.

This issue is _not_ the place to gain that consensus.
