### ISSUE TITLE
JavaScript (node.js) "executable" script gets misidentified as TypeScript

### ISSUE THREAD

**Issue by ahwayakchih** [github/linguist#4469]
In `bin` subdirectory of my project there is an executable script with shebang pointing to node.
It's a pure JS code, shebang points to node and yet it's still classified as TypeScript :(.

I can of course write an override, but i thought it should be easy enough to correctly classify file as JavaScript by shebang alone.

My repo is pure JS, so i don't want to confuse people (at least those few that will look into repo and then check language stats there). It also annoys me a bit that it's used to inflate global TypeScript numbers ;).

## Preliminary Steps

I have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

I did not open repo to public yet, so here's the code from `/bin/bechmark` file:
```js
#!/usr/bin/env node

const mri = require('mri');
const test = require('../test.js');

/**
 * @private
 * @see {@link https://nodejs.org/api/process.html#process_process_argv}
 */
const files = mri(process.argv.slice(2))._; // eslint-disable-line no-magic-numbers

if (files.length < 1) {
	console.log('Usage: benchmark file1.js file2.js ... fileN.js');
	console.log('For example: benchmark --report tap examples/example1.js examples/example2.js');
	process.exit(); // eslint-disable-line no-process-exit
}

files.forEach(name => test(name));
```
### Expected language:
JavaScript

### Detected language:
TypeScript

**Comment by pchaigno** [comment]
The node interpreter can interpret TypeScript. See #4261 and #4112.

**Comment by lildude** [comment]
> I can of course write an override, but i thought it should be easy enough to correctly classify file as JavaScript by shebang alone.

Unfortunately not. As @pchaigno has pointed out, the node shebang is valid for both JavaScript and Typescript and as such is associated with both (the `interpreters` attribute):

https://github.com/github/linguist/blob/3feaaabfa16449d53ba3933f8bfba021d093bc6d/lib/linguist/languages.yml#L2363-L2397

... and ...

https://github.com/github/linguist/blob/3feaaabfa16449d53ba3933f8bfba021d093bc6d/lib/linguist/languages.yml#L5085-L5091

As it's associated with both, further analysis of the file needs to take place and things like the heuristics and finally the naïve Bayesian classifier are then used to further determine the language.

As your file doesn't have an extension the analysis is falling right through to the classifier and it is identifying your code as Typescript as it looks a lot closer to the tokenised Typescript samples than the JavaScript samples (I created a simple repo with a single file containing the above):

```
$ LINGUIST_DEBUG=2 github-linguist .
                      #JavaScriptTypeScript
                 (   10     2.015         -
                 )   10     1.982         -
                 -    8     2.968         -
                //    2     0.221         -
                 ;    7     0.094         -
                 <    1         -     0.749
     SHEBANG#!node    1     3.733         -
       console.log    2         -     3.162
             const    3         -     4.343
           disable    2         -     5.668
             files    1     2.634         -
                if    1     1.208         -
              line    2         -     1.509
              name    2     1.078         -
                no    2         -     3.260
           process    1     2.634         -
      process.exit    1     2.634         -
           require    2         -     4.857
              test    2         -     3.268
                 {    1         -     0.321
                 }    1         -     0.351
JavaScript =   -485.813 +  -3.982 =   -489.795
TypeScript =   -479.528 +  -5.673 =   -485.201
100.00% TypeScript
$
```

Your only option really is to implement an override. Adding a `.js` extension would also force JavaScript.

**Comment by ahwayakchih** [comment]
Thanks for your answers :).

@pchaigno AFAIK node will not interpret TypeScript, unless your code does not use any of the TypeScript features. I tried every example from https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html. Only the first one works (i replaced last line, where `document.body` is used, with `console.log(greeter(user));`), but then it's not really a TypeScript code, it's a JavaScript code.

@lildude shouldn't it default to JS, if there is no file extension and interpreter is `node`? I'm guessing that once someone uses TypeScript, they are using it for syntax features. Which means, they can't call the script directly from node.js (unless they just want to check how syntax errors look like). In rare cases they do not use TypeScript syntax, they are really writing JavaScript file (especially, if it does not have `.ts` extension in its name).

**Comment by lildude** [comment]
> @lildude shouldn't it default to JS, if there is no file extension and interpreter is `node`?

Nope, that's not [how Linguist works](https://github.com/github/linguist#how-linguist-works) 😉 The language selection based on the interpreter works in the same way as other methods do when it comes to whittling multiple languages down to a single language.

**Comment by ahwayakchih** [comment]
@lildude then maybe adding `node` as interpreter for TypeScript was a mistake? AFAIK node does not understand TypeScript syntax at all. Sure, after you compile TypeScript to JavaScript, result can be interpreted by node, but by then it is a JavaScript file, not TypeScript.

**Comment by lildude** [comment]
> @lildude then maybe adding node as interpreter for TypeScript was a mistake?

@ahwayakchih possibly. I'm not an expert on JavaScript or TypeScript, in fact I don't know the difference 😄 but from the discussion in https://github.com/github/linguist/issues/4112 we can see https://github.com/google/clasp/blob/master/src/index.ts is apparently TypeScript using a node shebang. https://github.com/github/linguist/pull/4261 which added the node interpreter to TypeScript also includes several examples which are also apparently TypeScript.

**Comment by ahwayakchih** [comment]
@lildude all those files contain regular JavaScript code (i tested only the first one, but glanced through other two too). Two of them just use `ts` extension, for whatever reason. That's why they can pass it to `node` safely. Node.js does not understand TypeScript specific syntax. Since TypeScript "builds on top" of JavaScript, it can be used as JS, as long as none of TypeScript language "extensions" are used. But then it's really a JavaScript code.

Situation would be harder if interpreter was set to `deno` (https://github.com/denoland/deno). Then i would probably agree that TypeScript should be default. But node is for JS (i mean, it has "js" in it's name, after all ;).

**Comment by ahwayakchih** [comment]
@lildude i don't know much about Bayesian classifiers, so maybe my thinking is completely stupid, but would it be possible to update samples so that the `console.log`, `const`, `require` and `process` tokens did not give so many "points" to one side or another? Or maybe classifier could watch for TypeScript specific tokens, like `interface` for example? Too bad it can't just call linters and check which one does not error out :).

**Comment by Alhadis** [comment]
Starting to think that adding `node` as a TypeScript interpreter was a mistake. As @ahwayakchih pointed out, Node doesn't grok TypeScript at all, meaning it's no closer to a TypeScript interpreter than it is to being a CoffeeScript interpreter.

I'm in favour of removing it.

> I'm not an expert on JavaScript or TypeScript, in fact I don't know the difference

TypeScript is just JavaScript with static typing, rather than dynamic. E.g., JS doesn't enforce arity or type-checking in function calls, unless the developer explicitly tests for it. TypeScript relieves programmers of that burden by checking it at compile time.

**Comment by pchaigno** [comment]
I would prefer to get @grant's opinion on this before we remove it.

**Comment by grant** [comment]
I don't fully understand how this project works. The shebang doesn't really tell the language. The extension does a better job. Like VSCode, I still expect the extension to tell the language.

Anyways, I've forced the `bin` .ts file to be identified as ts.
https://github.com/google/clasp/blob/master/.gitattributes#L3

**Comment by pchaigno** [comment]
Okay. Let's go for it then. I'll *Accept* #4470 with this change.
