### ISSUE TITLE
Ok

### ISSUE THREAD

**Issue by ardink** [github/linguist#4474]
https://github.com/github/linguist/blob/3feaaabfa16449d53ba3933f8bfba021d093bc6d/lib/linguist/vendor.yml#L1

**Comment by RobQuistNL** [comment]
Did you maybe open these issues on accident?

**Comment by Alhadis** [comment]
Please make a fork if you wish to continue poking around at random stuff. Doing so here is disruptive to the rest of the project's contributors.
