### ISSUE TITLE
Support TexInfo

### ISSUE THREAD

**Issue by FranklinYu** [github/linguist#4479]
Example file:
* https://github.com/ruby-debug/ruby-debug-ide/blob/master/doc/protocol-spec.texi
* https://github.com/rmloveland/scsh-manual-texinfo/blob/master/scsh.texi

Official website for GNU Texinfo: https://www.gnu.org/software/texinfo/

**Comment by siawash96** [comment]
Thanks for freand sheep

**Comment by Alhadis** [comment]
We can register it as a language on GitHub, but there won't be syntax highlighting as every TexInfo grammar out there is GPL-licensed 👎 (I've searched before).

I've been tempted to write one in the past, but I'm not familiar with the format, sadly.

**Comment by siawash96** [comment]
Hello
Thanks to all the friends
I'm not familiar with this language too.
With the information I got, I think Instagram uses this language
Thank you

**Comment by jchook** [comment]
Another example: https://github.com/westes/flex/blob/master/doc/flex.texi

**Comment by Alhadis** [comment]
I've written an original (non-copylefted) grammar that will fix this. See #4589.
