### ISSUE TITLE
Fix for ANTLR

### ISSUE THREAD

**Issue by CreatorVilius** [github/linguist#4482]
## Preliminary Steps

- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

**Search keys I used:** `antlr`, `g4`

## Problem Description

There are 2 problems as of now:
- Syntax highlighting isn't that good.
- Colour isn't right.

ANTLR colour is light blue for some reason. Thing is, ANTLR's logo contain red colour and overall whole theme is red. The example repository can be a [ANTLR4's grammar repository](https://github.com/antlr/grammars-v4/). As you can see, the colour is light blue. But if you check icon at [ANTLR's github account](https://github.com/antlr) you'd see that icon contains red logo. I think that ANTLR's colour should be `#F02F26`.

Syntax. Syntax is kind of weird. Let's take a look at [this](https://github.com/antlr/grammars-v4/blob/a2e568eee75c0c4dcb273ed96a07170aa2ea5de4/javascript/JavaScriptLexer.g4#L191). Since it used `["...]` it assumes it's unclosed string. It's actually character, rather than unclosed string. Syntax also assumes that `grammar` isn't keyword, but an identifier at [this place in same grammar file](https://github.com/antlr/grammars-v4/blob/a2e568eee75c0c4dcb273ed96a07170aa2ea5de4/javascript/JavaScriptLexer.g4#L30). But if you take a look at [this](https://github.com/antlr/grammars-v4/blob/a2e568eee75c0c4dcb273ed96a07170aa2ea5de4/ruby/Corundum.g4#L36), grammar is a keyword.

**Comment by lildude** [comment]
>  - Syntax highlighting isn't that good.

As per the troubleshooting doc you've just acknowledged reading 😉:

> If you experience an issue with the syntax-highlighting on GitHub, please report the issue to the upstream grammar repository, not here.

If the upstream grammar maintainer isn't responsive or won't make your suggested changes, then feel free to submit a PR referencing a better grammar as per the details at https://github.com/github/linguist/blob/master/CONTRIBUTING.md#changing-the-source-of-a-syntax-highlighting-grammar.

As for ...

> - Colour isn't right.
>
> ANTLR colour is light blue for some reason. Thing is, ANTLR's logo contain red colour and overall whole theme is red. 

This is going to be an exciting and fun challenge for you 😀

The current colour has been in place for well over 5 years when https://github.com/github/linguist/pull/697 was merged and many people will have come to expect this colour.

Given the furore we've had recently with other languages having their colour changed unexpectedly, I'm going to ask that you propose changing the colour to the wider ANTLR community - _not_ here, but some other public forum widely use by the ANTLR community.

Only once you've received consensus that the community is happy with this colour change, please feel free to open a PR making the change and linking to the public discussion where this was accepted by the community. If there are official branding guidelines to support the colour choice, please link to those too.

Please also note that we have proximity rules in place so you may not be able to use this precise colour as it may be too close to another colour already used on Linguist (reds and blues are really popular). As such, I recommend you test the colour change locally before making your plea to the wider ANTLR community.
