### ISSUE TITLE
gitattributes language overriding only works in subdirectories?

### ISSUE THREAD

**Issue by mathomp4** [github/linguist#4483]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

This is probably a FAQ but I can't seem to search for it. Namely, a colleague and I were trying to figure out how to have Github's highlighter consider .pf files as Fortran. We went our separate ways and hit on using `.gitattributes` with:
```gitattributes
*.pf linguist-language=fortran
```
But while it worked for him in a toy repo, it didn't for me. In the end the difference was that his code was in a subdir and mine wasn't! 

If you go to the repo below, you'll see that `subdir/Test_MAPL_Config.pf` is highlighted as Fortran but `Test_RegridderManager.pf` isn't.

Is this a feature of the `.gitattributes` that we should know more about? That it only affects files below itself? (Or above depending on how you see directory trees. In subdirectories.)

### URL of the affected repository:
https://github.com/Goddard-Fortran-Ecosystem/testhighlighting

### Last modified on:

2019-04-03
### Expected language:

Fortran
### Detected language:

None

**Comment by lildude** [comment]
> Is this a feature of the `.gitattributes` that we should know more about?

Nope. This is a known limitation with the way GitHub caches the blobs: the cache, and thus syntax highlighting, isn't refreshed when you make changes to the `.gitattributes`. You need to make a change to the files affected by the change.

In your repo, the file in the root directory was last changed _before_ you made the .gitattribute changes whilst the one in the subdir was changed after.

I've forked your repo and make added a blank line to the file in the root dir and you can see the syntax highlighting has taken effect - https://github.com/lildude/testhighlighting/blob/master/Test_RegridderManager.pf

**Comment by mathomp4** [comment]
Huh. Well I'll be. I would never have thought of that!

I have learned something today. Thanks!

I suppose I can now close this.

**Comment by siawash96** [comment]
Hello
Thanks to the efforts of all dear friends
Unfortunately, the opportunity to deliver the project ended and I could not find a solution
I've abandoned this thread
Thanks

**Comment by siawash96** [comment]
Hello
I stopped following the project
Please do not go any further
Thank you

**Comment by siawash96** [comment]
Hello
I stopped following the project
Please do not go any further
Thank you
