### ISSUE TITLE
Could not gem install github-linguist on Mac OS

### ISSUE THREAD

**Issue by Jingciii** [github/linguist#4484]
I tried to execute `sudo gem install github-linguist` as well as `gem install github-linguist --user-install` on my Macbook, but both failed with the error messages. My ruby version is 2.3.7.

```
Building native extensions. This could take a while...
ERROR:  Error installing github-linguist:
	ERROR: Failed to build gem native extension.

    current directory: /Users/wangjingci/.gem/ruby/2.3.0/gems/charlock_holmes-0.7.6/ext/charlock_holmes
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -I /Library/Ruby/Site/2.3.0 -r ./siteconf20190403-26984-11d2bzk.rb extconf.rb
checking for main() in -licui18n... no
checking for main() in -licui18n... yes
checking for unicode/ucnv.h... yes
checking for main() in -lz... yes
checking for main() in -licuuc... yes
checking for main() in -licudata... yes
creating Makefile

current directory: /Users/wangjingci/.gem/ruby/2.3.0/gems/charlock_holmes-0.7.6/ext/charlock_holmes
make "DESTDIR=" clean

current directory: /Users/wangjingci/.gem/ruby/2.3.0/gems/charlock_holmes-0.7.6/ext/charlock_holmes
make "DESTDIR="
compiling converter.c
compiling encoding_detector.c
compiling ext.c
compiling transliterator.cpp
In file included from transliterator.cpp:1:
In file included from ./common.h:9:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby.h:33:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby/ruby.h:24:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin18/ruby/config.h:365:31: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
#define RUBY_ARCH "universal-"RUBY_PLATFORM_OS
                              ^
                               
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin18/ruby/config.h:366:35: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
#define RUBY_PLATFORM "universal."RUBY_PLATFORM_CPU"-"RUBY_PLATFORM_OS
                                  ^
                                   
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin18/ruby/config.h:366:55: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
#define RUBY_PLATFORM "universal."RUBY_PLATFORM_CPU"-"RUBY_PLATFORM_OS
                                                      ^
                                                       
In file included from transliterator.cpp:1:
In file included from ./common.h:9:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby.h:33:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby/ruby.h:1988:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby/intern.h:47:19: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
void rb_mem_clear(register VALUE*, register long);
                  ^~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby/intern.h:47:36: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
void rb_mem_clear(register VALUE*, register long);
                                   ^~~~~~~~~
2 warnings and 3 errors generated.
make: *** [transliterator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/wangjingci/.gem/ruby/2.3.0/gems/charlock_holmes-0.7.6 for inspection.
Results logged to /Users/wangjingci/.gem/ruby/2.3.0/extensions/universal-darwin-18/2.3.0/charlock_holmes-0.7.6/gem_make.out
```
I have no prior knowledge on Ruby and just wanna use the linguist library. Can anyone help solve this? Thanks

**Comment by siawash96** [comment]
Hello
Thanks to the efforts of all dear friends
Unfortunately, the opportunity to deliver the project ended and I could not find a solution
I've abandoned this thread
Thanks

**Comment by Jingciii** [comment]
@siawash96 Thanks anyway!

I just found out that I only need to add spaces `/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin18/ruby/config.h` line 365 and 366 to distinguish between literal and identifiers. This solves my problem.

Guess this is caused by upgrade version of Xcode.

**Comment by pchaigno** [comment]
@Jingciii Can we close this then?

**Comment by Jingciii** [comment]
Sure

**Comment by ReyAnthony** [comment]
Same issue here
IMHO, having the user to fix manually the spaces is not a good workaround

**Comment by lildude** [comment]
> As far as I understand, it's not really an issue on linguist side, but maybe the right compilation options might do the trick ?

@ReyAnthony Yup, I think the flags mentioned at https://github.com/github/linguist/issues/4449#issuecomment-470208078 should do the trick.

It really bugs me that a third party gem requires peeps in an unrelated project to jump through hoops to get it installed. We could document this, but I fear we'll be continually updating our docs as this seems to change ever-so-slightly with almost every release of macOS 😞.

**Comment by ProjectBarks** [comment]
For those who struggled to understand what needed to be done:

Change line 365-366 to this:
```
#define RUBY_ARCH "universal-" RUBY_PLATFORM_OS
#define RUBY_PLATFORM "universal." RUBY_PLATFORM_CPU "-" RUBY_PLATFORM_OS
```

**Comment by hudsontavares** [comment]
@lildude I would suggest at least the inclusion of these steps in a FAQ or similar.

Not all the users have ever seen make error messages related to header files - so, not all of them will paste the error on Google as I did to find out this issue entry.

I agree that this is not linguist's call, but it ends blocking the usage of this amazing tool for many people.

**Comment by mihaierosx2** [comment]
> For those who struggled to understand what needed to be done:
> 
> Change line 365-366 to this:
> 
> ```
> #define RUBY_ARCH "universal-" RUBY_PLATFORM_OS
> #define RUBY_PLATFORM "universal." RUBY_PLATFORM_CPU "-" RUBY_PLATFORM_OS
> ```

Thanks man, for me it were the lines 413-414 👍

**Comment by hyeoksuhan** [comment]
The file path and lines are depends on your system.
In my case path was `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin19/ruby/config.h` and line was 413-414.

**Comment by adampeklay** [comment]
Macbook pro 2019 changes needed:

`root# vim /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin19/ruby/config.h
413 #define RUBY_ARCH "universal-" RUBY_PLATFORM_OS
414 #define RUBY_PLATFORM "universal." RUBY_PLATFORM_CPU "-" RUBY_PLATFORM_OS`

`root# uname -a
Darwin C02D98FMMD6M 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64`

**Comment by LoopsGod** [comment]
You can run 

```
sudo gem install charlock_holmes -- --with-icu-dir=/usr/local/opt/icu4c --with-cxxflags='-Wno-reserved-user-defined-literal -std=c++11'
```

and then run

```
sudo gem install github-linguist
```

**Comment by loyaltyarm** [comment]
> 

this worked for me on M1 Macbook Air with macOS `13.0.1 (22A400)`
