### ISSUE TITLE
Bash .inc misclassified as PHP

### ISSUE THREAD

**Issue by nametoolong** [github/linguist#4486]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [ ] considered implementing an [override](https://github.com/github/linguist#overrides),
  (not my own repo)
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

[ionic-team/ionic-storage has a Bash .inc file misclassified as PHP.](https://github.com/ionic-team/ionic-storage/search?l=php) Obviously the file does not match any of the heuristics. Maybe `.inc` should be added as a Bash file extension? (I have no idea how popular Bash .inc files are and further investigation is needed.)

### URL of the affected repository:
https://github.com/ionic-team/ionic-storage

### Last modified on:

[Commit 1da388](https://github.com/ionic-team/ionic-storage/blob/1da388aad85bdc3f5d3a7a484148d5fb5a02fc2c/scripts/utils.sh.inc).

### Expected language:

Bash, or none.

### Detected language:

PHP

**Comment by lildude** [comment]
🤔 I don't believe `.inc` is an extension officially associated with Bash, or any shell language, so I'm not sure if it's right to add it. It would also be really hard to a) search for these on GitHub and b) implement a heuristic to differentiate Bash `.inc` files from PHP's (or any other language that uses this extension officially - we're missing heuristics for quite a few of these) so others don't end up in the situation you're reporting.

A better option would be to use an official extension like `.sh` or `.bash`, or add a shebang or modeline to the script. All of these would also ensure editors automatically select the correct grammar too. For within the repo, there's the option of an override too.
