### ISSUE TITLE
I cannot get github-linguist to play nicely to save my life

### ISSUE THREAD

**Issue by alexhultman** [github/linguist#4490]
I tried vendoring JS code, does not work. Tried this:

.gitattributes:
```
alexhultman@alexhultman-N56VZ:~/uWebSockets.js$ cat .gitattributes
*.js linguist-language=C++
```

Get this classification:
```
alexhultman@alexhultman-N56VZ:~/uWebSockets.js$ github-linguist
78.13%  C++
15.02%  JavaScript
3.93%   Makefile
2.92%   QMake
```

Makes no sense

**Comment by lildude** [comment]
What's wrong with the template we provide when opening an issue? 😭  Your question is answered in the documentation referenced in the first four points.

> I tried vendoring JS code, does not work.
> Makes no sense

Assuming you've committed your `.gitattributes` to the repo, your output shows it is forcing all `.js` files to be identified as C++ and not vendored so the analysis makes perfect sense 😄.

Point three in the template:

> - [ ] considered implementing an [override](https://github.com/github/linguist#overrides)

... has the answer you're looking for vendoring 😉.

**Comment by alexhultman** [comment]
Your link to overrides points to the very section of the documentation I have followed like a slave in 8 different commits and locally, to no success.

Override section includes what I have in my issue comment

**Comment by lildude** [comment]
What about like you've done before: https://github.com/uNetworking/uWebSockets.js/blob/master/.gitattributes ?

**Comment by alexhultman** [comment]
That's where I started.


```
alexhultman@alexhultman-N56VZ:~/uWebSockets.js$ ls -a | grep .gitattributes
.gitattributes
alexhultman@alexhultman-N56VZ:~/uWebSockets.js$ cat .gitattributes 
*.js linguist-vendored
alexhultman@alexhultman-N56VZ:~/uWebSockets.js$ github-linguist
78.13%  C++
15.02%  JavaScript
3.93%   Makefile
2.92%   QMake
```

**Comment by lildude** [comment]
Works for me:

```console
$ github-linguist --breakdown
78.13%  C++
15.02%  JavaScript
3.93%   Makefile
2.92%   QMake

Makefile:
Makefile
tests/Makefile

QMake:
misc/addon.pro
misc/host.pro

C++:
src/AppWrapper.h
src/HttpRequestWrapper.h
src/HttpResponseWrapper.h
src/Utilities.h
src/WebSocketWrapper.h
src/addon.cpp
src/host.cpp

JavaScript:
src/uws.js
tests/Autobahn.js
tests/Hammer.js

$ /bin/cat .gitattributes

examples/* linguist-vendored
$ echo "*.js linguist-vendored" >! .gitattributes
$ git add .gitattributes
$ git commit -m 'Vendor JS'
[master 189786d] Vendor JS
 1 file changed, 1 insertion(+), 2 deletions(-)
$ github-linguist --breakdown                   
91.94%  C++
4.62%   Makefile
3.43%   QMake

Makefile:
Makefile
tests/Makefile

QMake:
misc/addon.pro
misc/host.pro

C++:
src/AppWrapper.h
src/HttpRequestWrapper.h
src/HttpResponseWrapper.h
src/Utilities.h
src/WebSocketWrapper.h
src/addon.cpp
src/host.cpp

$
```

And visible on my fork - https://github.com/lildude/uWebSockets.js

**Comment by alexhultman** [comment]
When it works it works. Thanks. My local github-linguist still won't move an inch.
