### ISSUE TITLE
Unable to override language type on .module file type

### ISSUE THREAD

**Issue by mxr576** [github/linguist#4491]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

I added a Drupal specific file type overrides to [.gitattributes ](https://github.com/mxr576/apigee-devportal-drupal/blob/gh_module_file_highligting/.gitattributes#L12) but it seems it is not working. I do not see PHP highlighting on [this file](https://github.com/mxr576/apigee-devportal-drupal/blob/gh_module_file_highligting/apigee_edge.module) in the root of the repo. Although highligthing is working on an other [.module file in a subdirectory](https://github.com/mxr576/apigee-devportal-drupal/blob/gh_module_file_highligting/modules/apigee_edge_teams/apigee_edge_teams.module). (But it seems[ it worked before this change too](https://github.com/mxr576/apigee-devportal-drupal/blob/c4e248d3f2186e2bbdd45cd343d5a502db1c9217/modules/apigee_edge_teams/apigee_edge_teams.module).)

### URL of the affected repository
https://github.com/mxr576/apigee-devportal-drupal/blob/gh_module_file_highligting

### Last modified on:
2019-04-10

### Expected language:
PHP

### Detected language:
???

**Comment by lildude** [comment]
Your change is taking effect in as much as the file is now being identified as PHP:

![screen](https://user-images.githubusercontent.com/627280/55880007-c4b69480-5b97-11e9-8be3-108087867ffc.png)

However you're also hitting a known limitation with the way GitHub caches the blobs: the cache, and thus syntax highlighting, isn't refreshed when you make changes to the `.gitattributes`. You need to make a change to the files affected by the change to force a refresh of the cache.

I've done just that in a fork of your repo as you can see here https://github.com/lildude/apigee-devportal-drupal/blob/gh_module_file_highligting/apigee_edge.module (I added the word foo in the comment).

**Comment by mxr576** [comment]
Ahh... Thanks!
