### ISSUE TITLE
gem install github-linguist --no-documentation 

### ISSUE THREAD

**Issue by drandreaskrueger** [github/linguist#4494]
just an idea, is something like this possible?

    gem install github-linguist --no-documentation

because the one thing "Installing ri documentation for github-linguist-7.3.1" takes ages, almost 10 minutes now.  And I just want to quickly check languages in my one repo, and I would happily use an online documentation for that.

**Comment by drandreaskrueger** [comment]
ready:


> Done installing documentation for charlock_holmes, escape_utils, mime-types-data, mime-types, rugged, github-linguist after 982 seconds
> 6 gems installed

**Comment by pchaigno** [comment]
Doesn't [this StackOverflow answer](https://stackoverflow.com/a/1386014/6884590) work for you?

**Comment by drandreaskrueger** [comment]
hah, fantastic. yei !

    gem install --no-document github-linguist

perfect. Thanks.
