### ISSUE TITLE
.gitattributes cannot represent a grammar name containing spaces

### ISSUE THREAD

**Issue by octogonz** [github/linguist#4496]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

I can specify a line like this in my .gitattributes file, and it works fine:
```gitattributes
*.json            linguist-language=JSON5
```

But If I try to use a grammar name that contains spaces, it does NOT work:
```gitattributes
*.json            linguist-language=JSON with Comments
```

The reason is that .gitattributes lines are a sequence of value pairs that are [delimited by spaces](https://www.git-scm.com/docs/gitattributes).  I examined Git's [parser](https://github.com/git/git/blob/e35b8cb8e212e3557efc565157ceb5cbaaf0d87f/attr.c#L297), and as far as I can tell, it actually provides no way to escape the value part of a `name=value` pair.

I also found an old [Linguist FAQ document](https://github.com/github/linguist/blob/22cd80721eb3984c740225dcafea5440a6405c82/FAQ.md#what-keywords-can-i-use-to-highlight-a-code-snippet-in-markdown) which suggests to put dashes instead of spaces, but that does NOT work either:

```gitattributes
*.json            linguist-language=JSON-with-Comments
```

Substituting hyphens for spaces seems like a pretty good solution.  Should we implement that?  If so, where's the code?

### Last modified on:
2019-04-15

**Comment by lildude** [comment]
> I also found an old [Linguist FAQ document](https://github.com/github/linguist/blob/22cd80721eb3984c740225dcafea5440a6405c82/FAQ.md#what-keywords-can-i-use-to-highlight-a-code-snippet-in-markdown) which suggests to put dashes instead of spaces, but that does NOT work either:

It certainly does 😁 

![screenie](https://user-images.githubusercontent.com/627280/56470694-120cee80-6441-11e9-9aa0-3c9811d7d854.png)

Even a copy of your `rush.json` file (ignore the typo 😊) does - https://github.com/lildude/super-potato/blob/master/ruah.json

The problem you're hitting is a known limitation with the way GitHub caches the blobs: the cache, and thus syntax highlighting, isn't refreshed when you make changes to the `.gitattributes`. A file affected by a language override needs to be modified too.

**Comment by octogonz** [comment]
Thank you very much @lildude !  I confirmed that the problem was the GitHub cache issue.  After touching the file, the highlighting is now working properly.

I will close this issue.  It would be helpful to document the .gitattributes syntax somewhere -- if I had confidence that my syntax was correct, then I would have tried harder to get it working before opening this issue.  Unfortunately the linguist FAQ is apparently no longer published.

**Comment by lildude** [comment]
> It would be helpful to document the .gitattributes syntax somewhere -- if I had confidence that my syntax was correct, then I would have tried harder to get it working before opening this issue.

Yeah, good idea. I think we can add it to https://github.com/github/linguist#using-gitattributes.

As for the FAQ... it's not _yet_ been published 😉. https://github.com/github/linguist/pull/4271 is the PR (/me nudges @pchaigno)
