### ISSUE TITLE
My repository isn't showing my language

### ISSUE THREAD

**Issue by matheusroleal** [github/linguist#4501]
## Preliminary Steps

- [ x ] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [ x ] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [ x ] considered implementing an [override](https://github.com/github/linguist#overrides),
- [ x ] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
My repository isn't showing my language

### URL of the affected repository:
https://github.com/matheusroleal/solidity-cookbook

### Last modified on:
2019-04-15
### Expected language:
Solidity

### Detected language:
None

**Comment by pchaigno** [comment]
Any reason you removed the checkboxes?

**Comment by matheusroleal** [comment]
Sorry, I didn't saw this part of the steps... Let me edit this.

**Comment by pchaigno** [comment]
So why did you not implement an override?

**Comment by matheusroleal** [comment]
Sorry... it worked after implementing an override ! I forgot to close the issue ;)
