### ISSUE TITLE
Add Sunaba Language

### ISSUE THREAD

**Issue by bofeiw** [github/linguist#4502]
## Preliminary Steps

Please confirm you have...
- [ ] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [ ] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
Please add Sunaba language, which is a introductory language to beginners.
https://github.com/hirasho/Sunaba is the repo of the language.

### URL of the affected repository:
https://github.com/bofeiw/Tetris-Sunaba 
"Tetris.txt" is written in Sunaba and its suffix is ".txt", it is not detected as any language.

### Last modified on:

2019-04-20
### Expected language:

Sunaba
### Detected language:

Not detected since its file suffix is ".txt"

**Comment by pchaigno** [comment]
We'd welcome a pull request adding this language if it meets the requirements detailed in the contribution guidelines. If you need help doing that, we can help. In the meantime I'll close this issue as it's unlikely one of us knows Sunaba enough to add it ourselves.

**Comment by bofeiw** [comment]
> We'd welcome a pull request adding this language if it meets the requirements detailed in the contribution guidelines. If you need help doing that, we can help. In the meantime I'll close this issue as it's unlikely one of us knows Sunaba enough to add it ourselves.

But its suffix ends in .txt 
How to solve this? I don't think detect all *.txt as Sunaba is a solution. Maybe I need a bit of help.

**Comment by pchaigno** [comment]
I think you'll need to add [a heuristic](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.yml).

**Comment by bofeiw** [comment]
Thanks, ill try that and create a PR.
