### ISSUE TITLE
Support Bosque

### ISSUE THREAD

**Issue by Narendra-Kamath** [github/linguist#4503]
It would be good to add the support for Bosque, that has been recently announced by Microsoft.

Language Repo: https://github.com/Microsoft/BosqueLanguage

**Comment by pchaigno** [comment]
We'd welcome a pull request if/when it meets the requirement on in-the-wild usage. We can help if needed. In the meantime, I'm going to close this as it's unlikely one of us knows Bosque enough to add it.
