### ISSUE TITLE
LOLCODE has no syntax highlighting

### ISSUE THREAD

**Issue by NELMVN** [github/linguist#4505]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

LOLCODE has no syntax highlighting even it's already detected as LOLCODE.
Example: [99 Bottles of Beer](https://github.com/NELMVN/LOLCODE/blob/master/examples/99%20Bottles%20of%20Beer.lol
)

### Expected language:
LOLCODE

**Comment by pchaigno** [comment]
LOLCODE [doesn't have a grammar](https://github.com/github/linguist/blob/9116c90fcbb82ac03b4b33c58cfbde1fcf745e99/lib/linguist/languages.yml#L2544) defined. If you know one (Sublime Text, Atom, or TextMate module) we'd welcome a pull request. In the meantime, I'm going to close this as none of us knows one.
