### ISSUE TITLE
Dependency information differs between README.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by X6B0ISI09wD4** [github/linguist#4519]
## Preliminary Steps

Please confirm you have...
- [ ] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [ ] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [ ] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
I noticed that both [README.md](https://github.com/github/linguist/blob/master/README.md) and [CONTRIBUTING.md](https://github.com/github/linguist/blob/master/CONTRIBUTING.md) both contain information on Linguist's dependencies and how to satisfy them. The problem I encountered is that neither of them seem to provide a complete rundown, [README.md](https://github.com/github/linguist/blob/master/README.md) does not mention Docker, and [CONTRIBUTING.md](https://github.com/github/linguist/blob/master/CONTRIBUTING.md) does not mention zlib or OpenSSL. There may be other disparities too.

This tripped me up when trying to contribute as I had to deal with the errors thrown while installing `charlock_holmes` and `rugged`.

**Comment by lildude** [comment]
A slight difference in dependencies is expected as they differ for using vs developing/contributing to. Using example of Docker: this isn't needed to _use_ or even install Linguist (it's shipped as a Ruby gem), but it is required to develop and contribute to it.

Both do detail the `charlock_holmes` and `rugged` requirements but sadly problems with installing `charlock_holmes` and `rugged` do happen, and change quite frequently. As these are only dependencies, the best place for tracking problems with them is with the projects themselves and not within Linguist.

If there's really a short-coming in the documentation, please feel free to submit a pull request.
