### ISSUE TITLE
Please add Logisim files recognizement ( .circ )

### ISSUE THREAD

**Issue by RicardoGuevara** [github/linguist#4521]
Hi, I'm using logisim ( .circ ) files (usually found in logic gates models) I'd be happy to see syntax highlighting available on github for this. 

There's a grammar available here:

https://github.com/RicardoGuevara/LogisimGame/blob/master/Game.circ

That would be awesome :)
Tanks.

**Comment by lildude** [comment]
🤔 Logisim appears to be standard XML with nothing special other than what its used for. It is already correctly detected as such (by the XML strategy) and correctly syntax highlighted too... 

![logisim](https://user-images.githubusercontent.com/627280/58478946-1f5b7e00-814f-11e9-95af-dedb1982d3a0.png)

It also appears to be computer generated and not written by hand.  As a result, this wouldn't really be considered a new language by Linguist.

**Comment by RicardoGuevara** [comment]
I get it, thanks
