### ISSUE TITLE
Wrong language detected

### ISSUE THREAD

**Issue by lukasz-migas** [github/linguist#4534]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Hi,

A project I recently released is tagged as HTML, however, it is mostly written in Python and there are no HTML files in the repo.

### URL of the affected repository:
[https://github.com/lukasz-migas/msalign](https://github.com/lukasz-migas/msalign)

### Last modified on:
2019-05-21

### Expected language:
Python

### Detected language:
HTML

**Comment by Alhadis** [comment]
Please fill out the issue template. It's there for your benefit as much as it is ours.

Chances are you'll find the answer to your problem in one of the links listed in the template.

**Comment by Alhadis** [comment]
Looks like [this 4.96 MB HTML file](https://github.com/lukasz-migas/msalign/blob/master/site-source/img/mass_spectrum_before_and_after_alignment.html) was to blame for the skewed stats. I noticed you [updated `.gitattributes`](https://github.com/lukasz-migas/msalign/commit/3ef06ddf13f6f8b3c1a42a914e5bb30fb18adba0) very recently. It should be noted that changes to `.gitattributes` don't take effect until a change has been pushed to one of the repository's files.

If you make a trivial modification to a Python or HTML file, you should see the statistics bar update with the correct statistics. :+1:

**Comment by lildude** [comment]
> If you make a trivial modification to a Python or HTML file, you should see the statistics bar update with the correct statistics. 👍

Not quite... there's a typo in the .gitattributes: you've got `site_source` but the path is actually `site-source`.

**Comment by Alhadis** [comment]
... oops. 😅 Yeah, I, uh, completely missed that.

**Comment by lukasz-migas** [comment]
Thanks! Changing to `site-source` solved the issue. Nice catch :)
