### ISSUE TITLE
Support vim snippet engines

### ISSUE THREAD

**Issue by ObserverOfTime** [github/linguist#4537]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

There are various snippet engines for Vim, but none of them are supported by linguist.

Here are some of the most popular engines:
* [SnipMate](https://github.com/garbas/vim-snipmate) (extension: `.snippets`)
* [UltiSnips](https://github.com/SirVer/ultisnips) (extension: `.snippets`)
* [Neosnippet](https://github.com/Shougo/neosnippet.vim) (extension: `.snip`)

And some examples:
* [vim-snippets](https://github.com/honza/vim-snippets): SnipMate & UltiSnips
* [neosnippet-snippets](https://github.com/Shougo/neosnippet-snippets): Neosnippet

UltiSnips and Neosnippet are (mostly) compatible with SnipMate, which means that SnipMate can be used as the only filetype if adding multiple filetypes for the same thing is not desirable.

**Comment by ObserverOfTime** [comment]
I have checked the code and this issue is still relevant because Vim snippet engines are still not supported.

**Comment by lildude** [comment]
Support is only going to be added when someone opens a pull request adding support. Please feel free to review CONTRIBUTING.md and submit a PR if snippets meet all the criteria.
