### ISSUE TITLE
Estimate for next release date?

### ISSUE THREAD

**Issue by olafurpg** [github/linguist#4548]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

There have been a large number of highlighting improvements since the last v7.4.0 release on April 17th, especially for Scala that I'm personally excited about 😄 I'm curious, is there an estimate for the next release?

**Comment by lildude** [comment]
What, this one https://github.com/github/linguist/pull/4547? 😀

**Comment by olafurpg** [comment]
Yay \o/ Thank you 🙏
