### ISSUE TITLE
Add SystemRDL language support

### ISSUE THREAD

**Issue by drom** [github/linguist#4553]
I have developed `tree-sitter` based syntax highlighter for [SystemRDL](https://en.wikipedia.org/wiki/SystemRDL) language:
* https://github.com/drom/language-systemrdl
* https://github.com/drom/tree-sitter-systemrdl

Could you recommend a process of adding `SystemRDL` support to the `linguist` package?

**Comment by pchaigno** [comment]
Please check CONTRIBUTING.md, where our contribution process and requirements are detailed.
