### ISSUE TITLE
linguist-language git attribute has no effect

### ISSUE THREAD

**Issue by gavv** [github/linguist#4559]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Hi,

Not a very important issues, but still...

I've set `linguist-language=C++` in `.gitattributes` but GitHub still classifies some matching files as `C` instead of `C++`.

.gitattributes: https://github.com/roc-project/roc/blob/master/.gitattributes

checking that it works:

```
$ git check-attr -a src/modules/roc_core/helpers.h
src/modules/roc_core/helpers.h: linguist-language: C++
```

```
$ git check-attr -a src/modules/roc_core/target_posix/roc_core/stddefs.h
src/modules/roc_core/target_posix/roc_core/stddefs.h: linguist-language: C++
```

Problematic files: https://github.com/roc-project/roc/search?l=c

![image](https://user-images.githubusercontent.com/8436629/59666000-a59e3980-91bc-11e9-991b-8613d960be91.png)

### URL of the affected repository:

https://github.com/roc-project/roc

### Last modified on:
.gitattributes file was pushed a couple weeks ago

### Expected language:
C++

### Detected language:
C

**Comment by lildude** [comment]
So, this gets "fun"... you're experiencing a caching behaviour of the search system. The search results are independent from Linguist when it comes to indexing and caching and will lag behind changes detailed in `.gitattributes` as the search index entry for a particular file isn't updated until you modify that file again.

In the example you've shown, the two files were last indexed _before_ you made your `.gitattributes` - note the "Last indexed on Feb 24" after each file name. Both of those files were modified around this time. Your `.gitattributes` file was however only modified on 31 May 2019 long after these files were last changed. In order for the search results to reflect this change, you'll need to push a change to the files.

As for `.gitattributes` _not_ having an effect... it most definitely is. You've only marked _some_ of the files Linguist determines as C as C++.

If we run Linguist against a clone of your repo we see these are the files still being identified as C and they make up the 6.5% you see in the language bar:

```
$ github-linguist ~/tmp/trash/roc --breakdown
83.63%  C++
9.22%   Python
6.50%   C
0.65%   Shell

Python:
SConstruct
scripts/3rdparty.py
[... truncated for brevity ...]

Shell:
scripts/travis/docker.sh
[... truncated for brevity ...]

C:
src/lib/example/receiver_sox.c
src/lib/example/sender_sinewave.c
src/lib/include/roc/address.h
src/lib/include/roc/config.h
src/lib/include/roc/context.h
src/lib/include/roc/frame.h
src/lib/include/roc/log.h
src/lib/include/roc/platform.h
src/lib/include/roc/receiver.h
src/lib/include/roc/sender.h
src/pulse/module-roc-sink-input.c
src/pulse/module-roc-sink.c
src/pulse/module_helpers.c
src/pulse/module_helpers.h

C++:
src/lib/src/address.cpp
src/lib/src/config.cpp
src/lib/src/context.cpp
src/lib/src/log.cpp
src/lib/src/private.h
src/lib/src/receiver.cpp
src/lib/src/sender.cpp
src/modules/roc_audio/depacketizer.cpp
src/modules/roc_audio/depacketizer.h
src/modules/roc_audio/frame.cpp
[... truncated for brevity ...]

$
```

As you can see, none of those C files match your `.gitattributes`, hence Linguist will do its thing and determine the language itself.

**Comment by gavv** [comment]
Ah, I see. Thanks for a detailed explanation!

> In order for the search results to reflect this change, you'll need to push a change to the files.

BTW, It would probably make sense to automatically reindex files on .gitattributes change too...

Anyway that's not an issue for me, so feel free to close this if it's not considered as a bug.

**Comment by lildude** [comment]
> BTW, It would probably make sense to automatically reindex files on .gitattributes change too...

It would and is quite a common request from Linguist, however it's much easier said than done from a search and repo perspective - it also affects syntax highlighting which uses the blob for caching independent of the .gitattrbutes file. The search and repo teams are well aware of this issue and it is on their radars, but not very high in priority.

**Comment by lildude** [comment]
Closing as this is a known limitation that Linguist has no control over.
