### ISSUE TITLE
babel-sublime jsx package lacks support

### ISSUE THREAD

**Issue by aforest-gvl** [github/linguist#4576]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

https://github.com/github/linguist/blob/001ca526694a32a5ac4c977a79032ced0b8c0aca/grammars.yml#L245-L247

The babel-sublime jsx grammar has not been updated in over a year, and there are known issues with it.  In one of the open issues, it was suggested that there are alternative packages with more support. https://github.com/babel/babel-sublime/issues/368#issuecomment-471160838

[Naomi](https://github.com/borela/naomi) and [JS Custom](https://github.com/Thom1729/Sublime-JS-Custom) were the suggested alternatives.

**Comment by aforest-gvl** [comment]
It looks like @pchaigno, @lildude, and @Alhadis were involved in the most recent update of the jsx grammar - https://github.com/github/linguist/pull/4223.

Are any of you the right people to get some traction on this?

**Comment by lildude** [comment]
@aforest-gvl sorry about the delay in responding, I've not had the time to prioritise any Linguist work recently.

So the babel-sublime/JSX grammar is an interesting one. The grammar used for JSX has a very long and complicated history as you'll be able to see from the discussions in https://github.com/github/linguist/pull/4223 (the PR that switched us to using a fork of babel/babel-sublime) and https://github.com/github/linguist/pull/3779 and https://github.com/github/linguist/issues/3775 and https://github.com/github/linguist/issues/3044 - this last one has the most history, and it's not pretty.

So back to your request... I've looked at those two grammars and neither are going to be suitable as they're both Sublime 3-specific grammars and not TextMate compatible. Linguist only supports TextMate compatible grammars.

If you know of another TextMate-compatible grammar that we could use that is still maintained and doesn't exhibit any of the problems you're inferring the current grammar suffers from, please feel free to open a PR request to switch to that grammar.  You can find details on replacing the grammar in the [CONTRIBUTING.md](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#fixing-syntax-highlighting).

**Comment by aforest-gvl** [comment]
@lildude Thanks for the information!  Unfortunately, I am not aware of any well-maintained TextMate compatible grammars for jsx.  I'll keep an eye out for one and follow up if I find one, but for now, it looks like there's not much we can do.
