### ISSUE TITLE
helm charts incorrectly classified as smarty code

### ISSUE THREAD

**Issue by moutons** [github/linguist#4578]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [ ] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

I was looking at some helm charts and noticed that there's a misclassification of helm charts as PHP/Smarty code. This appears to be due to Helm's use of the `.tpl` extension, it would be nice to have linguist look inside `*.tpl` files to determine whether a file is actually smarty code or not.

wrt submitting an override, I'll issue a PR but there's no support for Helm in linguist so 🤷‍♂ 

### URL of the affected repository:

https://github.com/helm/charts/search?l=smarty

### Last modified on:

2019-07-09

### Expected language:

there's no Helm Template or Helm Chart language in linguist (yet?), so probably none or text

### Detected language:

Smarty

### URL of the affected repository:

https://github.com/jjasghar/helm-stream-charts

### Last modified on:

2019-07-09

### Expected language:

there's no Helm Template or Helm Chart language in linguist (yet?), so probably none or text

### Detected language:

Smarty

**Comment by pchaigno** [comment]
> there's no Helm Template or Helm Chart language in linguist (yet?), so probably none or text

We don't currently have a *none* option, mostly because we don't have a confidence score which would allow us to say "this file is none of the candidate languages". That's unfortunately a know limitation of Linguist.

The solution here would be to add Helm Template or Helm Chart as a language. We'd welcome a pull request if the in-the-wild usage is high enough. If that's not the case (yet), you can always mark these files as vendored to avoid counting them in statistics.

**Comment by moutons** [comment]
Thanks for the explanation, currently trying to figure out how to consume syntaxes from https://github.com/Azure/vscode-kubernetes-tools

**Comment by RomeroGaliza** [comment]
Can we re-open this issue?

**Comment by moutons** [comment]
spoiler: I didn't figure out how to consume syntaxes, but it's on my to-do list for if I ever get free time again

**Comment by lildude** [comment]
> Can we re-open this issue? 

Please rather open a new "New language" issue requesting adding Helm support or go big and submit a PR that adds support (assuming it meets our usage requirements).
