### ISSUE TITLE
How to get "config files" syntax highlighted?

### ISSUE THREAD

**Issue by M-Reimer** [github/linguist#4581]
## Problem Description

I want to get a ".conf" file syntax highlighted.
I've tried several things, but so far without success.

My config file:
https://github.com/VDR4Arch/vdr4arch/blob/master/repo-make.conf

My ".gitattributes":
https://github.com/VDR4Arch/vdr4arch/blob/master/.gitattributes

### Expected language:
Something that makes at least my comments "stand out".
Worst-Case I would be OK if the file is highlighted as shell-script.

### Detected language:
None

**Comment by pchaigno** [comment]
I've run Linguist locally on your repository and the `.conf` file is correctly detected as Shell:
```
97.97%  Shell
1.34%   Perl
0.69%   C

Shell:
checkpkg
firmware/dvbsky-firmware/PKGBUILD
firmware/ngene-firmware/PKGBUILD
firmware/ttpci-firmware/PKGBUILD
fonts/ttf-sourcesanspro/PKGBUILD
...
repo-make.conf
...

C:
kodi-setwakeup/kodi-setwakeup.c
vdr/shutdown-wrapper.c

Perl:
newvdr
```
There might be a caching issue on GitHub's side. @lildude ?

**Comment by lildude** [comment]
> There might be a caching issue on GitHub's side. @lildude ?

Yup, it's the common problem that occurs when changing a file type in `.gitattributes`. When doing so you need to modify the affected file to force a reanalysis and invalidation of the syntax highlighting cache as this is cached based on the blob SHA.

The `.gitattributes` _did_ take effect as can be seen when viewing the source for this commit: https://github.com/VDR4Arch/vdr4arch/blob/06a43a41b93996e71e9465d77c114dac829b657f/repo-make.conf

![Screenshot 2019-07-15 at 10 50 48](https://user-images.githubusercontent.com/627280/61208126-97293c00-a6ee-11e9-82e4-c478029288b0.png)

However as the file hasn't been modified, the syntax cache isn't updated. There is already a long standing open issue in the main GitHub repo for this behaviour.

I've forked the repo, added back the `.gitattributes` and added a `# Foo` comment to the `repo-make.conf` file and 🎉 , syntax highlighting.
