### ISSUE TITLE
Incorrect highlighting with C/C++ when macro call does not end in semicolon

### ISSUE THREAD

**Issue by tristan957** [github/linguist#4582]
Not much else to say. Any extra information can be found at https://github.com/jeff-hykin/cpp-textmate-grammar/issues/311 because this is basically a duplicate. Please take a look at the line I specifically called out with an all-caps comment.

## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
When a macro invocation does not end in a semicolon, the following syntax is incorrectly colored. 

### URL of the affected repository:
https://github.com/jeff-hykin/cpp-textmate-grammar/issues/311

### Last modified on:
2019-07-15

### Expected language:
C/C++

### Detected language:
C/C++

**Comment by lildude** [comment]
As you've already identified, this is a problem with the grammar and _not_ Linguist. As per the README at https://github.com/github/linguist#theres-a-problem-with-the-syntax-highlighting-of-a-file

> If you experience an issue with the syntax-highlighting on GitHub, **please report the issue to the upstream grammar repository, not here**. Grammars are updated every time we build the Linguist gem so upstream bug fixes are automatically incorporated as they are fixed.

As you have already done this, I'm closing this issue. Any grammar updates will automatically be pulled in as and when releases are made.

**Comment by tristan957** [comment]
Well the upstream I reported the issue to isn't even the upstream you guys use for your grammar.

**Comment by tristan957** [comment]
Has been rectified https://github.com/textmate/c.tmbundle/issues/67

**Comment by lildude** [comment]
> Well the upstream I reported the issue to isn't even the upstream you guys use for your grammar.

Whoops missed that as I wasn't expecting you to reference a completely different grammar 😊.

> Has been rectified [textmate/c.tmbundle#67](https://github.com/textmate/c.tmbundle/issues/67)

🙇
