### ISSUE TITLE
site not working ?

### ISSUE THREAD

**Issue by oshada97** [github/linguist#4583]
site not working ?

**Comment by deangelo2005** [comment]
No

**Comment by lildude** [comment]
Which site? You'll need to be more explicit than that 😁 (making the comment from GitHub.com which is clearly working)

**Comment by deangelo2005** [comment]
Netbank

**Comment by Alhadis** [comment]
http://www.am-i-online.org/

**Comment by Alhadis** [comment]
> Netbank

He's right, I checked my bank balance and my life savings are at a total of $290.15 AUD.

Oh wait, I'm broke. 😢 Guess Netbank's working fine then.

(Also, I think you're in the wrong thread...)

**Comment by lildude** [comment]
> Netbank

Clearly the wrong place. Closing and locking.
