### ISSUE TITLE
 I added third party codes in the Dependencies folder but the files are still in the statistics

### ISSUE THREAD

**Issue by ramondeallima** [github/linguist#4590]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
I performed the procedure of adding unwanted statistic files in the Dependencies folder, but still it is still considered.

I performed a test with the same project on a test repository to see if the files would be found but not found.

### URL of the affected repository:
https://github.com/ramondeallima/projeto-biblioteca-games
Test: https://github.com/ramondeallima/projeto-biblioteca-games2
### Last modified on:

2019-07-24
### Expected language:

C#
### Detected language:

JavaScript

**Comment by Alhadis** [comment]
Did you read the section on [implementing an override](https://github.com/github/linguist#overrides)?

**Comment by ramondeallima** [comment]
Yes, but I did not understand very well!

I am Brazilian and I depend on google translator to understand, it may be bothering me

**Comment by Alhadis** [comment]
1.	Create a file named `.gitattributes` in the root of your project

2.	Add the following lines to the `.gitattributes` file:
	~~~gitattributes
	/BibliotecaGames.Entities/* linguist-vendored=true
	/BibliotecaGames.BLL/* linguist-vendored=true
	~~~

3.	Modify a file in your project to force GitHub to detect the new `.gitattributes` file

Does that help?

**Comment by ramondeallima** [comment]
I performed the procedure in the test repository but it didn't work.

https://github.com/ramondeallima/projeto-biblioteca-games2

**Comment by ramondeallima** [comment]
BibliotecaGames.Site/Dependencies/* linguist-vendored

Would this work to ignore files inside the folder highlighted in the image?

![image](https://user-images.githubusercontent.com/37948637/61842322-22809b00-ae6e-11e9-9f09-270df8b3163b.png)

**Comment by ramondeallima** [comment]
Friend, this worked out:

BibliotecaGames.Site/Dependencies/* linguist-vendored

Thank you!

**Comment by Alhadis** [comment]
You're welcome.
