### ISSUE TITLE
Language bar links exclude files within language groups from search queries

### ISSUE THREAD

**Issue by supernintendo** [github/linguist#4593]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Files with parent languages (files with prefixed file extensions that are consolidated into language groups) are excluded from the search results pages that Linguist links to in the language bar. For example, [this repository](https://github.com/dwyl/phoenix-chat-example) reports "3.7% HTML" usage but when clicking the link in the language bar to view those files, GitHub says it [couldn’t find any code](https://github.com/dwyl/phoenix-chat-example/search?l=html). To view those files the user has to click the [HTML+EEX](https://github.com/dwyl/phoenix-chat-example/search?l=HTML%2BEEX) link in the languages sidebar.

Ideally names within language groups would be combined in the link's search query but I'm not sure if GitHub's web search endpoints support this. Another idea is to have the most prevalent extension within the language group take precedence. So if I mostly have EEx templates in my repo, the "HTML" link would pass a `l=html%2Beex` query instead of `l=html`.

### URL of the affected repository:

All repositories with files containing prefixed file extensions that are aggregated into language groups (`.html.erb`, `.html.eex`, etc.)

### Last modified on:
2019-07-27

### Expected language:
N/A

### Detected language:
N/A

**Comment by pchaigno** [comment]
That's an old, known issue on GitHub NS side :(

/cc @lildude

**Comment by lildude** [comment]
> That's an old, known issue on GitHub NS side :(

Yup. Linguist is responsible for the grouping, but the main GitHub app is responsible for the search behaviour so not really something Linguist can control short of _not_ grouping. As per the discussions in https://github.com/github/linguist/issues/4291 this would be a case where the grouping makes sense and isn't likely to change.

**Comment by lildude** [comment]
Closing as this isn't a problem with Linguist.
