### ISSUE TITLE
$schema key in grammar prevents adding the grammar

### ISSUE THREAD

**Issue by FreHu** [github/linguist#4594]
Related to #4592 
scripts/add_grammar will fail if the grammar has a `$schema`  key in it.
```
> The new grammar repository `vendor/grammars/vscode-abap-cds` (from https://github.com/SAP-samples/vscode-abap-cds) contains 1 errors:
  >     - Unknown keys in grammar: `source.abapcds` (in `syntaxes/cds.tmLanguage.json`) contains invalid keys (`$schema`)
```
For now I've removed the schema.

The schema link is autogenerated by the vscode extension template and actually very useful, as you get autocompletion when developing the grammar, meaning more people will run into this issue. Is it possible to allow it to be present?

**Comment by pchaigno** [comment]
> Is it possible to allow it to be present?

Yes, you can create a pull request to add it to this list:
https://github.com/github/linguist/blob/72542687adfc47a5d8b941bb3d8a5311edaa10e1/tools/grammars/compiler/data.go#L20-L25

Do you have a link to the documentation for this field, for future reference?

**Comment by FreHu** [comment]
I'll submit the PR later.

> Do you have a link to the documentation for this field, for future reference?

https://json-schema.org/latest/json-schema-core.html#rfc.section.7
