### ISSUE TITLE
Broken JSX Highlighting in diff.

### ISSUE THREAD

**Issue by btnwtn** [github/linguist#4602]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
JSX breaking on closing bracket within JSX expression.
Sorry if this isn't the correct repo, but the JSX grammar won't let me create an issue.

![](https://i.imgur.com/1COBMFu.png)

```jsx
const Derp = (
  <React.Fragment>
    Blah. Please{' '}
    <Link to="/blah" target="_blank">
      derp
    </Link>
    .
  </React.Fragment>
);
```

### URL of the affected repository:
Private repo on GHE.

### Last modified on:

2019-08-12

**Comment by lildude** [comment]
Hmmm, we've definitely fixed this hence it shows correctly below your snapshot. I suspect you may need to upgrade your instance. What version of GHE are you running? (Hover you cursor over the Octocat logo at the bottom of the page if you're not an admin).

**Comment by btnwtn** [comment]
Interesting, we're on 2.16.12, maybe we just need to upgrade?

**Comment by lildude** [comment]
🤔 2.16.12 should already be using the newer grammar. Something else is at play here.

Your screenshot is showing a partial diff from a file. What is the extension of that file?

Does the excerpt you've pasted into the OP under the screenshot render correctly in an issue comment on your instance as you've added it in this issue?

**Comment by btnwtn** [comment]
Weird it actually does render correctly in a comment, but not in the file. Filetype was `.js` which may be the issue?

**Comment by lildude** [comment]
> Weird it actually does render correctly in a comment, but not in the file.

Do you mean when viewing the `.js` extensioned file on it's own, or only when viewing as part of the diff?

**Comment by btnwtn** [comment]
When viewing the diff

**Comment by lildude** [comment]
Thanks. I'm not having much luck reproducing this using a very simple example:

![Screenshot 2019-08-15 at 17 07 04](https://user-images.githubusercontent.com/627280/63108608-34da8a00-bf7f-11e9-901f-9df2e950896d.png)

Are you able to provide a complete sample that reproduces the issue but doesn't reveal any proprietary code?

**Comment by btnwtn** [comment]
Ah, I can't even find the code I originally screened... 😬.
I'll close this out since you can't repro!

**Comment by btnwtn** [comment]
Thanks for looking into the issue 😄
