### ISSUE TITLE
Unable to recognize and style .conf files by default on GitHub

### ISSUE THREAD

**Issue by kmehant** [github/linguist#4606]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [ ] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

`.conf` extensions are used to write configurations for different software like supervisord. Such files are not being recognized or rendered by GitHub. 

### URL of the affected repository:
https://github.com/scorelab/Bassa/blob/develop/components/core/supervisor_api.conf

**Comment by pchaigno** [comment]
Any reason you can't use an override?

**Comment by kmehant** [comment]
I think it works that way @pchaigno, Thank you.

**Comment by Alhadis** [comment]
@kmehant Add this to your project's [`.gitattributes`](https://github.com/scorelab/Bassa/blob/develop/.gitattributes) file:

~~~gitattributes
*.conf linguist-language=INI
~~~

[`.conf`](https://fileinfo.com/extension/conf) is a *very* generic file-extension used by many programs, and no assumptions can be made about their syntax.

**Comment by kmehant** [comment]
> @kmehant Add this to your project's [`.gitattributes`](https://github.com/scorelab/Bassa/blob/develop/.gitattributes) file:
> 
> ```gitattributes
> *.conf linguist-language=INI
> ```
> 
> [`.conf`](https://fileinfo.com/extension/conf) is a _very_ generic file-extension used by many programs, and no assumptions can be made about their syntax.

Thank you for the info, will close the issue for now 😁
