### ISSUE TITLE
C++ project got detected as a C project

### ISSUE THREAD

**Issue by JanFlan** [github/linguist#4608]
My project is a C++ but it's detected as C. I'm kinda new to Github. I've found some people talking about it but sadly I couldn't fix it! I even tried adding an empty .hpp file so it could be detected as a C++ project but nothing has changed. Any help, please?
The project : https://github.com/JanFlan/OpenGL-Robot

**Comment by KrzysztofSzewczyk** [comment]
You can add an override.
For me it's written in C, what's the deal?

**Comment by JanFlan** [comment]
> You can add an override.
> Also, why are you keeping these GLUT headers in your repository?

how can I do that? 
And I just pushed the whole project including the glew and glut stuff so it can be used directly without the need to configure anything. Isn't that correct?

**Comment by KrzysztofSzewczyk** [comment]
It's terrible way to do that.
Remove these C headers and you will be fine.

**Comment by JanFlan** [comment]
oh you mean in the code itself?
#include <GL/glew.h>
#include <GL/freeglut.h>
But how? The code will not run without them...

**Comment by JanFlan** [comment]
hmm, I didn't know that the Glew and Glut folder would be a problem! But Isn't there any way to include it with the project without it gets detected as a C project? I just want it to be usable directly without the need to download or configure anything

**Comment by KrzysztofSzewczyk** [comment]
No, no, no, please don't do that.
The user has to collect the headers himself because it's terrible practice to keep dependencies inside repository.
