### ISSUE TITLE
Provide simple comment-aware-only shell formatting

### ISSUE THREAD

**Issue by connorjclark** [github/linguist#4611]
## Problem Description

If you have a generic code snippet that is just a list of commands to run in the terminal (so doesn't need any of the language feature detection of, for example, bash or sh), it's common to just use `sh` (so comments are colored). It looks good, most of the time.

sh
```sh
yarn install
yarn build
# Because this is `sh`, comments are faded!
yarn deploy
```

But often, some commands get special treatment, and the result is odd emphasis on special keywords.

sh
```sh
# yarn should be installed first

git clone https://github.com/GoogleChrome/lighthouse

cd lighthouse
yarn
yarn build-all
```

There are also cases where "PowerShell" is better, but it also fails in other cases.

sh (BAD)
```sh
# lint and test all files
yarn test

# watch for file changes and run tests
#   Requires http://entrproject.org : brew install entr
yarn watch

## run linting, unit, and smoke tests separately
yarn lint
yarn unit
yarn smoke

## run tsc compiler
yarn type-check
```

PowerShell (GOOD)
```PowerShell
# lint and test all files
yarn test

# watch for file changes and run tests
#   Requires http://entrproject.org : brew install entr
yarn watch

## run linting, unit, and smoke tests separately
yarn lint
yarn unit
yarn smoke

## run tsc compiler
yarn type-check
```

PowerShell (BAD)
```PowerShell
# yarn should be installed first

git clone https://github.com/GoogleChrome/lighthouse

cd lighthouse
yarn
yarn build-all
```

___

It makes perfect sense that `PowerShell` and `sh` wouldn't do what I want. It's good that `sh` is close enough, but I would really like for a formatting option for just "fade comments" and "everything else is normal".

**Comment by lildude** [comment]
All of these are examples of the underlying grammars not accommodating your simple samples quite as you'd expect.  You can see this when putting these into individual files as I've done in the gist at https://gist.github.com/lildude/ea339f9b2eb6b4085862418839a0ae77 - you'd see the same thing if these were in a repo.

Accordingly, this isn't an issue for Linguist to address but rather each of the underlying grammars. You'll need to raise issues with the respective grammars.

**Comment by lildude** [comment]
Closing as this isn't a problem with Linguist.

**Comment by connorjclark** [comment]
I don't think any of these grammars should change their behavior to accommodate this. If this were to work, it'd have to be a new grammar for a pseudolanguage.

**Comment by Alhadis** [comment]
@connorjclark Linguist's first and foremost responsibility is to **identify languages**, then provide syntax highlighting based on that. Strictly speaking, it isn't to provide syntax highlighting per se.
