### ISSUE TITLE
Dockerfile `AS` keyword not highlighted

### ISSUE THREAD

**Issue by XVilka** [github/linguist#4612]
It is used in a FROM construction to alias the name:
```Dockerfile
FROM alpine:edge AS builder
```
See https://docs.docker.com/engine/reference/builder/#from for the reference.

![image](https://user-images.githubusercontent.com/203261/63162387-fadbb780-c054-11e9-8c6a-349dbd6925d4.png)

**Comment by lildude** [comment]
Why did you delete the template?  😢😭

We use the template to help and in this case, it would most definitely have helped you as the second point:

> - [ ] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,

... has a [section](https://github.com/github/linguist#theres-a-problem-with-the-syntax-highlighting-of-a-file) dedicated to this precise issue. It applies to inline code samples too.

Please let us know if there is anything we can do differently that would have made you reconsider deleting the template.

**Comment by lildude** [comment]
Closing as this isn't a problem with Linguist.
