### ISSUE TITLE
TSQL is being misclassified as PLpgSQL for repo sqlserver-kit

### ISSUE THREAD

**Issue by ktaranov** [github/linguist#4622]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
Many Microsoft SQL (T-SQL) file is classified as a PLpgSQL file.

### URL of the affected repository:
https://github.com/ktaranov/sqlserver-kit/

### Last modified on:
2019-08-23

### Expected language:
T-SQL

### Detected language:
PLpgSQL

**Comment by pchaigno** [comment]
Any reason you can't use an override to solve that particular repository's statistics?

For `.sql` files, we use [a number of heuristic rules](https://github.com/github/linguist/blob/ee6172a3b8558354da7dd7b992cb5a0ea0e10c9a/lib/linguist/heuristics.yml#L393-L411) to identify the language. Any way we could improve those heuristic rules without making them overly complex?

**Comment by ktaranov** [comment]
I add `*.sql linguist-language=TSQL` to .gitignore but it didn't help.

**Comment by lildude** [comment]
You've put it in the wrong file 😁

**Comment by ktaranov** [comment]
Sorry, fixed (move overrides to .gitatribute). But it did not help. Also many scripts and procedures without any syntax highlighting, see for example https://github.com/ktaranov/sqlserver-kit/blob/master/Stored_Procedure/dbo.sp_BenchmarkTSQL.sql

**Comment by ktaranov** [comment]
Also for heuristics.yml I suggest to add next patterns:
ISNULL, DATETIME2 and GETDATE

**Comment by lildude** [comment]
You'll need to edit one of the affected files to force a refresh as the caching isn't updated when the language is changed via the `.gitattributes`

**Comment by lildude** [comment]
Oh and the file you linked to shows syntax highlighting for me.

**Comment by ktaranov** [comment]
Great thanks for patience any help, after updating procedure now it has syntax highlighting.
Do I need to manually change each script (there are more than 100), for which there is no highlighting?
Also, why keyword `ALTER PROCEDURE` is not highlighted?

**Comment by lildude** [comment]
> Great thanks for patience and fast help, after updating procedure now it has syntax highlighting.
> Do I need to manually change each script (there are more than 100), for which there is no highlighting?

No, I think modifying just one might be enough.

> Also, why keyword `ALTER PROCEDURE` is not highlighted?

If it's being correctly identified as TSQL then you'll need to ask the grammar maintainer as it would definitely be an issue with the grammar and not Linguist.

**Comment by ktaranov** [comment]
@lildude great thanks for help!

**Comment by smola** [comment]
Could this be reopened? TSQL misclassification as PLpgSQL is quite frequent with linguist.

**Comment by lildude** [comment]
A PR to improve the heuristic would be better as this issue isn't going to be addressed otherwise. Will re-open, but if someone doesn't offer a solution, this issue is going to become stale repeatedly until someone does.

**Comment by ktaranov** [comment]
Hi @lildude, check this pr for this issue https://github.com/github/linguist/pull/4625#issuecomment-527941219

**Comment by lildude** [comment]
@ktaranov we can continue that PR. I'm not sure why you closed it anyway 😁
