### ISSUE TITLE
How to correct and overrides for C# language?

### ISSUE THREAD

**Issue by ktaranov** [github/linguist#4627]
## Preliminary Steps

Please confirm you have...
- [X] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [X] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [X] considered implementing an [override](https://github.com/github/linguist#overrides),
- [X] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
How to correct and overrides for C# language?
`*.cs linguist-language=CSHARP` or `*.cs linguist-language=csharp` or `*.cs linguist-language=C#`?

Do you have full list overrides for all languages?

**Comment by Alhadis** [comment]
`C#` should work. Have you not tried?

~~~gitattributes
*.cs linguist-language=C#
~~~

> Do you have full list overrides for all languages?

The full list of languages can be found in [`languages.yml`](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml). The name of each language is used as the value of `linguist-language=`.

**Comment by ktaranov** [comment]
Thanks for quick reply, solved.
