### ISSUE TITLE
Quarkus/Gizmo bytecode falsely detected as Zig

### ISSUE THREAD

**Issue by nrdmn** [github/linguist#4631]
## Problem Description

There's a library called [quarkusio/gizmo](https://github.com/quarkusio/gizmo) which produces bytecode in files with names ending in `.zig` which use syntax that is remotely similar to [Zig](https://github.com/ziglang/zig) which are falsely detected as Zig code. I think these bytecode files should not be detected as Zig.

### URL of the affected repository:
Examples of quarkus/gizmo bytecode detected as zig:  
https://github.com/herodes1991/gradle-quarkus-rest-client  
https://github.com/ashu-mehra/quarkus-test

### Expected language:
[Quarkus Bytecode](https://github.com/quarkusio/gizmo) 

### Detected language:
[Zig](https://github.com/ziglang/zig)

**Comment by Alhadis** [comment]
The issue template you neglected to fill out included links to pages with solutions to your problem.

**Comment by nrdmn** [comment]
The issue template that I neglected to fill out includes a link to the [troubleshooting section of linguist's readme](https://github.com/github/linguist#troubleshooting). You're talking about "pages", i.e. plural. What other pages did I miss? 

The first paragraph there labelled "My repository is detected as the wrong language" explains how to solve _a_ problem (but not _my_ problem). My problem is that other peoples' repositories are misclassified, which makes them show up when I search for repositories containing code in a specific language when they shouldn't.

The first two solutions suggested there are to move the files to specific directories or to add a .gitattributes file. However I do not consider going around and telling other people to fix their repos a valid solution. A third option offered in that paragraph is to open an issue here after verifying no such issue already exists, which I did.

**Comment by Alhadis** [comment]
Please read our page on [adding support for a new language](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). This "Quarkus" library you've linked us to is only a small project, and we require a language to be in use by hundreds of users on GitHub before we can register support for it.

> However I do not consider going around and telling other people to ~~fix their repos~~ change their repos to work around linguist's bugs a valid solution.

You don't think submitting pull-requests to add a `.gitattributes` with an override is a valid solution?

**Comment by nrdmn** [comment]
The quarkus library can remain unsupported for all I care.
>You don't think submitting pull-requests to add a .gitattributes with an override is a valid solution?

No, because that's not going to scale if the library becomes more popular. For now we can just ignore what appears to be a total of two repositories, I guess. But I imagined that linguist's classifier would (should?) be more accurate.

**Comment by Alhadis** [comment]
> No, because that's not going to scale if the library becomes more popular.

And when it does, that's when we look at getting it recognised by Linguist. 😉

> But I imagined that linguist's classifier would (should?) be more accurate.

How do you expect Linguist to have any knowledge of a format that barely 10 people have ever seen or come into contact with?

**Comment by nrdmn** [comment]
I expected linguist to not detect a language that doesn't use zig's syntax and not even any of zig's keywords as zig. The only three things both languages seem to have in common is ".zig" in the file name, curly braces, and `//` comments.

**Comment by Alhadis** [comment]
> so I guess it's the file name that triggered the detection?

If you had filled out the issue template, followed the steps, and [read the first section](https://github.com/github/linguist#how-linguist-works) of Linguist's readme titled “**How Linguist works**”, you'd know the answer to your question already and we wouldn't be having this conversation. 😉

So in other words, yes. If I take some random text-file on my computer, give it a `.py` extension, and then upload it to a repository, Linguist will assume it's Python and not stop to scrutinise its contents because there aren't any registered languages with a conflicting choice of file-extension. Even if it did, it would only attempt to identify languages it already knows.
