### ISSUE TITLE
Highlight clojurescript code block failed in github

### ISSUE THREAD

**Issue by jingtaozf** [github/linguist#4655]
Currently github can't highlight code block when its language is clojurescript, both in an markdown file and an org file.

An example can be found here:
https://gist.github.com/jingtaozf/5065ce5d768add4b9a70aee9b38fbb6a

## Preliminary Steps

Please confirm you have...
- [ X] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [ X] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [ X] considered implementing an [override](https://github.com/github/linguist#overrides),
- [ X] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
github can't highlight code block when its language is clojurescript, both in an markdown file and an org file.

I know github use org-ruby to render org files but don't use its syntax highlight feature,
you can confirm this by search "Org" in this file:
https://github.com/github/markup/blob/master/lib/github/markups.rb 

So this is should be an issue of linguist I think.

### URL of the affected repository:
https://gist.github.com/jingtaozf/5065ce5d768add4b9a70aee9b38fbb6a

### Last modified on:
2019-09-30
### Expected language:
ClojureScript

### Detected language:
None.

**Comment by lildude** [comment]
Linguist doesn't currently know about ClosureScript, hence the behaviour you are seeing.  Feel free to review CONTRIBUTING.md and open a PR to add support for ClosureScript.
