### ISSUE TITLE
Source-mapped CSS not recognised as generated

### ISSUE THREAD

**Issue by hvaoc** [github/linguist#4659]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Generated CSS are not identified correctly. 

Sometimes CSS generated by SCSS has the following comment

```
/*# sourceMappingURL=app.css.map */
```

while generated check is done for this format

```
//# sourceMappingURL=app.css.map 
```

This is inflating the STATS double the time. SCSS files once and CSS files again (which should be ignored as generated files)

I tried cloning locally to make changes. Not able to complete the setup

```
$ script/bootstrap
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 13.0.0
Using public_suffix 4.0.1
Using addressable 2.7.0
Using bundler 1.17.3
Using byebug 11.0.1
Fetching charlock_holmes 0.7.6
Installing charlock_holmes 0.7.6 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/nomad/bin/linguist/vendor/gems/ruby/2.3.0/gems/charlock_holmes-0.7.6/ext/charlock_holmes
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20191002-14673-3esxz2.rb extconf.rb --with-icu-dir /usr/local/opt/icu4c --with-cxxflags=-std=c++11
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/$(RUBY_BASE_NAME)
	--with-icu-dir
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:1733:in `dir_config': undefined method `split' for true:TrueClass (NoMethodError)
	from extconf.rb:24:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/nomad/bin/linguist/vendor/gems/ruby/2.3.0/gems/charlock_holmes-0.7.6 for inspection.
Results logged to /Users/nomad/bin/linguist/vendor/gems/ruby/2.3.0/extensions/universal-darwin-18/2.3.0/charlock_holmes-0.7.6/gem_make.out

An error occurred while installing charlock_holmes (0.7.6), and Bundler cannot continue.
Make sure that `gem install charlock_holmes -v '0.7.6' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  github-linguist was resolved to 7.6.1, which depends on
    charlock_holmes
```

Similar error occured when running gem install github-linguist which can fixed using this. 

```
sudo gem install charlock_holmes --version 0.7.6 -- --with-icu-dir=/usr/local/opt/icu4c --with-cxxflags=\'-Wno-reserved-user-defined-literal -std=c++11\'
```

But how do we fix the error in the project itself. 

Please fix this or help me setup locally so that I can fix it. 

Bundler version 1.17.3
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
Mac OSX Mojave

**Comment by Alhadis** [comment]
> Please fix this or help me setup locally so that I can fix it.

Heh. I have the exact same problem. I actually have to switch workstations to work on Linguist, because macOS is, well, macOS. You ever find a solution to this, let me know. 😉

Do you have a link to an affected repository? Just so it speeds up investigation.

**Comment by Alhadis** [comment]
Never mind... after sitting down to look at the problem, I noticed right away this was an *intentional* omission for some reason:

https://github.com/github/linguist/blob/d90f983f29101dc7c3e1f408acfbd0826f89d8c7/lib/linguist/generated.rb#L138-L151

Which makes no sense, because the source-map format is the same across both languages, and identifying source-mapped stylesheets is no more difficult than identifying JavaScript.

Gonna fix this.

**Comment by hvaoc** [comment]
> > Please fix this or help me setup locally so that I can fix it.
> 
> Heh. I have the exact same problem. I actually have to switch workstations to work on Linguist, because macOS is, well, macOS. You ever find a solution to this, let me know. 😉
> 
> Do you have a link to an affected repository? Just so it speeds up investigation.

My bad, should have linked the exact file and place since I already did that research, hopefully you didn't waste too much time on that, sorry.

**Comment by Alhadis** [comment]
It's okay, I'm wrapping up a PR for this as I type. 👌

As luck would have it, I was recently reading the [source-map specification](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit) so I noticed a few other things that weren't being covered with the current handlers, too.

**Comment by Alhadis** [comment]
Done. See #4661.
