### ISSUE TITLE
Lumber detected as TSQL even if SQL is ignored in a branch

### ISSUE THREAD

**Issue by rap2hpoutre** [github/linguist#4663]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

The repository https://github.com/ForestAdmin/lumber/ is considered as TSQL. It's because there is a dump in `assets/database-examples/movies`.

I override the rules here: https://github.com/ForestAdmin/lumber/blob/fix/github-linguist/.gitattributes following the recommandations about overriding. I tried two ways : 

```
assets/* linguist-generated=true
```

And:

```
*.sql linguist-detectable=false
```

But it seems to have no impact. When I go to my branch : https://github.com/ForestAdmin/lumber/tree/fix/github-linguist, it's still indicated as TSQL.

### Last modified on:
2019-10-04

### Expected language:
Javascript

### Detected language:
TSQL

_I hope I respected the guidelines for contributions. Feel free to ask for more info!_

**Comment by lildude** [comment]
> I override the rules here: https://github.com/ForestAdmin/lumber/blob/fix/github-linguist/.gitattributes following the recommandations about overriding.

You need to commit your .gitattributes file to your default branch for it to have any effect.

**Comment by lildude** [comment]
You can see this in action in the fork I made of your repo at https://github.com/lildude/lumber

**Comment by rap2hpoutre** [comment]
Ok thanks @lildude 🙏! Still I can't see it in action on your fork (it still displays TSQL):

<img width="1028" alt="Capture d’écran 2019-10-04 à 16 53 14" src="https://user-images.githubusercontent.com/1575946/66217384-7bb74700-e6c7-11e9-90b5-74842ecebff4.png">

Did I missed something?

**Comment by lildude** [comment]
🤔 not sure. I see this:

![Screenshot 2019-10-04 at 15 55 23](https://user-images.githubusercontent.com/627280/66217542-6d652d00-e6bf-11e9-941e-b9c5f2c4038f.png)

**Comment by lildude** [comment]
Looks to be a caching issue. It'll probably take a few mins to propagate out to all the front-end servers. Wait and refresh and you'll eventually see it.

**Comment by rap2hpoutre** [comment]
OK. I'm waiting for it! Thanks!

I will close the issue as soon as I don't see it anymore :)

**Comment by rap2hpoutre** [comment]
OK, I see it now! Thank you! 👍
