### ISSUE TITLE
HTML Embedded Code

### ISSUE THREAD

**Issue by ForgivenNin** [github/linguist#4675]
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description:
I was wondering if there is a way that the `script` and `.css` content in an `.html` file would be able to be picked up on. I know for sure that to some degree their presence can be verified using JavaScript, but the file size would probably be harder to figure out. That is, unless we can confirm there is a character to data size ratio! If there is, maybe I could whip up a script to make this enhancement possible.

### Last modified on:
2019-10-13

### Expected language:
HTML, CSS, JAVASCRIPT

### Detected language:
HTML

**Comment by pchaigno** [comment]
Linguist doesn't parse files to classify them. That would take way too much time given the number of files it has to process. And you can't identify CSS and JavaScript sections in a HTML document without parsing HTML.

**Comment by ForgivenNin** [comment]
I would say that it could have a lower priority in comparison to the processing it already does; but I think it could be a possibility if there is an option that, by default is disabled/inactive, does the search once a user decides to state such a `.gitattributes` setting.

**Comment by ForgivenNin** [comment]
I believe this is still relevant because it can be done on a practical level and gives deeper accuracy for embedded scripts, especially in web development.
