### ISSUE TITLE
Whitespace in .gitattributes linguist-language (again)

### ISSUE THREAD

**Issue by vinriviere** [github/linguist#4681]
Hi, I wonder how to specify a language name with spaces in `.gitattributes` for `linguist-language`. This question had been asked in issue #2751, but as the issue seemed to be solved differently, the question was not answered.

More specifically, I want to colorize [this file](https://github.com/Vretrocomputing/atari-devpac2-afficher_image/blob/master/IMAGE.S) with the language `Motorola 68K Assembly`. I found that name in [languages.yml](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L3226), but I'm stuck as spaces don't seem to be allowed in `.gitattributes` values.

BTW, to avoid confusion, it would be nice if GitHub could display the name of the currently detected language used for colorization.

**Comment by Alhadis** [comment]
Unfortunately, this is a limitation of the `gitattributes(5)` format itself; the best you can do is use an alias that doesn't contain whitespace.

Motorola assembly doesn't have any aliases defined yet, but `m68k` would be a good one. You're more than welcome to submit a pull-request to add it. 👍 Bear in mind the changes won't take place until the next release of Linguist (which will be soon, I believe — late this month).

**Comment by vinriviere** [comment]
@Alhadis Thanks for your feedback! I have just created the pull request #4683, as requested.

**Comment by Alhadis** [comment]
Aaaaand it's already been approved. 😉 Will get merged once GitHub staff (i.e., @lildude) gives it the final review.

Thanks!

**Comment by vinriviere** [comment]
Many thanks, it works fine now to colorize my assembler files on GitHub 😀
https://github.com/Vretrocomputing/atari-devpac2-afficher_image/blob/master/IMAGE.S
