### ISSUE TITLE
ReasonML detected as Ocaml

### ISSUE THREAD

**Issue by amiralies** [github/linguist#4684]
I think it happens because reason is in the `ocaml` group.

I know and agree that reason is just a syntax for ocaml but seprate detection will give some benfits such as searching through trending repos, know that how much of a monorepo, or a library which uses both reason and ocaml is written in reason / ocaml.

**Comment by amiralies** [comment]
@Alhadis any thoughts?

**Comment by jfrolich** [comment]
Just like showing Elixir and Erlang as separate languages I think this would make sense.
