### ISSUE TITLE
VB Language

### ISSUE THREAD

**Issue by pkrall520** [github/linguist#4685]
Hello, 
Is there any plan to add support for VB?

**Comment by lildude** [comment]
What does "VB" stand for?  Linguist already has support for "Visual Basic" if that's what you mean.

If this is not what you mean, Linguist is entirely community driven so there aren't any plans... it's entirely up to the community to submit a pull request adding the relevant languages, provided they meet all the requirements. 

See CONTRIBUTING.md for more details on how you can add support.

**Comment by zspitz** [comment]
See #2418

**Comment by smola** [comment]
Maybe #2418 should be reopened?

**Comment by lildude** [comment]
https://github.com/github/linguist/pull/4725 split things up into VBA, VBScript and Visual Basic .NET and is now live on GitHub so this is now resolved.  Closing.
