### ISSUE TITLE
Update docs to mention hyphenated aliases

### ISSUE THREAD

**Issue by Alhadis** [github/linguist#4697]
**UPDATE:** Our docs suck, let's make them not suck. Original issue below:

------------

An [acknowledged](https://github.com/github/linguist/issues/2751) [limitation](https://github.com/github/linguist/issues/4681) of ~~Linguist~~ Git is that it's currently impossible to override a language if its name contains whitespace (and lacks an alias that doesn't). For example, none of the following lines work:

~~~gitattributes
*.glyphs linguist-language=OpenStep Property List
*.glyphs linguist-language=OpenStep\ Property\ List
*.glyphs linguist-language="OpenStep Property List"
~~~

I propose a second override to enable users to specify a language using its [`language_id`](https://github.com/github/linguist/blob/770b6e636683d7eebf295adaec9ab7b175563710/lib/linguist/languages.yml#L23-L25):

~~~gitattributes
*.glyphs linguist-language-id=598917541
~~~

This is neither readable nor convenient, but it's better than nothing. Thoughts?

**Comment by pchaigno** [comment]
Wouldn't it be easier to make, say `*.glyphs linguist-language=OpenStep-Property-List` work? (Or does it already?)

**Comment by Alhadis** [comment]
> (Or does it already?)

[So it does](https://github.com/Alhadis/great-repository-names-are-short-and-memorable/blob/dev/blank.glyphs). I only thought hyphenating the name applied to fenced code-blocks in markdown files.

I think we need to document this...

**Comment by katef** [comment]
Thanks! This is just what I was looking for.
