### ISSUE TITLE
StandardML syntax highlighting is basically wrong

### ISSUE THREAD

**Issue by XVilka** [github/linguist#4698]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

While Linguist seems to detect the file as StandardML, but many keywords are not highlighted correctly, e.g. "Datatype", "Definition" or "End", that are mostly used in HOL

### URL of the affected repository:

https://github.com/facebook/infer/blob/master/sledge/semantics/llvmScript.sml

### Last modified on:

https://github.com/facebook/infer/commit/e9296d31b6c682313adce6d3c765b8d0af727432

### Expected language:
StandardML

### Detected language:
StandardML

**Comment by Alhadis** [comment]
Did you really complete this step?

> * [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,

See the third section, [*"There's a problem with the syntax highlighting of a file"*](https://github.com/github/linguist#theres-a-problem-with-the-syntax-highlighting-of-a-file).

**Comment by XVilka** [comment]
Ok, did an issue in the language repository: https://github.com/textmate/standard-ml.tmbundle/issues/7

**Comment by Alhadis** [comment]
Closing this issue because it isn't related to Linguist.
