### ISSUE TITLE
F# (FSharp) syntax highlighting issue for 'let', and the upstream grammar repo is archived

### ISSUE THREAD

**Issue by eternaldensity** [github/linguist#4702]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

This is a GitHub syntax highlighting issue.  I would raise the issue with the upstream grammar repository, but it is archives as read only so that is not possible.  Perhaps it would need to be forked or there might be an alternative grammar repository that isn't dead?

The problem is that the 'let' keyword is not detected and highlighted when followed by an attribute.  Here are [some ](https://gist.github.com/eternaldensity/7cbd12d8d4ee6b5818c7b9e04d2646c7)[examples](https://gist.github.com/eternaldensity/880d81786350f95afe0503fc2c4c8079) and here's an inline example:
```Fsharp
let foo = 1 //correct
let bar () = 5 //correct
[<Something>] let fizz number = "fizz" //correct
let [<Something>] buzz number = "buzz" //currently wrong: the let is not highlighted
//all the above are valid F# and every 'let' should be highlighted the same
```

I'm not sure how to test whether a potential fix for this would work (not that I have one) as I only know how to see the syntax highlighting in action within the context of GitHub.  (I initially raised the issue with GitHub and was pointed in the direction of the upstream grammars linguist uses, alas I cannot raise the issue there, due to that repo being archived and dead.)

### URL of the affected repository:

https://github.com/ionide/ionide-atom-fsharp/tree/c875802334ce03cd027a4127f8e6c974568ccc79

https://github.com/ionide/ionide-atom-fsharp/blob/c875802334ce03cd027a4127f8e6c974568ccc79/grammars/fsharp.json possibly has the relevant code.  While that repo does have some forks, they all seem to be equally dead.

### Last modified on:
2017-02-06

### Expected language:
Fsharp

### Detected language:
Fsharp

**Comment by pchaigno** [comment]
> I'm not sure how to test whether a potential fix for this would work

You could do that with [Lightshow](https://github-lightshow.herokuapp.com/).

If you know/create a fork to which we can point Linguist, we can change the grammar used, but without that, there isn't much we can do :/

**Comment by eternaldensity** [comment]
Thanks!
I had a look around for other F# grammars and I found one that's updated *much* more recently: https://github.com/ionide/ionide-fsgrammar (18 days ago in fact)

Trying it out in Lightshow, it gets my example case correct: [here ](https://github-lightshow.herokuapp.com/?utf8=✓&scope=from-url&grammar_format=json&grammar_url=https%3A%2F%2Fgithub.com%2Fionide%2Fionide-fsgrammar%2Fblob%2Fmaster%2Fgrammar%2Ffsharp.json&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgist.githubusercontent.com%2Feternaldensity%2F7cbd12d8d4ee6b5818c7b9e04d2646c7%2Fraw%2F5083957984113e1047ed2c2afa22b37ef43400eb%2Flet-formatting.fs&code=)

**Comment by pchaigno** [comment]
Great! It looks good on our sample files too.

Do you want to open a [pull request for the grammar switch](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#changing-the-source-of-a-syntax-highlighting-grammar)? I can assist if needed.

**Comment by eternaldensity** [comment]
I've succeeded in installing ruby and docker.  I've successfully script/bootstrap and even bundle exec rake samples.  But I can't get script/add-grammar to work, because docker doesn't appear to be running.
```Checking docker is installed and running
$ docker ps
/usr/lib/ruby/2.3.0/open3.rb:199: warning: Insecure world writable dir /home/ed/.cargo/bin in PATH, mode 040777
  > Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Command failed. Aborting.```

I cannot find any instructions for resolving this.  Should it be starting automatically?  If it's manual I need to specify a container and I cannot find any indication of what that should be.

**Comment by lildude** [comment]
You need to install docker on your system and start the service. You don't need a specific container as the script takes care of that. The CONTRIBUTING.md has details about the requirements for Linux and macOS.

**Comment by eternaldensity** [comment]
As per my previous message I did install docker.
I cannot find any instructions regarding starting a service.
Which script is meant to start docker?

**Comment by lildude** [comment]
That should be documented in the Docker installation guide for your platform. One thing to note is if you're using Linux, you should install `docker-ce`, not the old `docker` pkg.

**Comment by eternaldensity** [comment]
Sorry, forgot about this.  Still in the process of sorting out Docker in order to produce the fix.

**Comment by eternaldensity** [comment]
Yeah I had to wipe my VM and haven't had time to reinstalling everything needed to make this minor change.
Soon...

**Comment by eternaldensity** [comment]
I might actually be able to get on with this soon...
