### ISSUE TITLE
Proguard files classified as INI, IDL, Prolog, QMake and others

### ISSUE THREAD

**Issue by smola** [github/linguist#4705]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Proguard files are classified as INI, IDL, Prolog, QMake and others.

Do you think we should add explicit support for Proguard?

Personally, I'm not as interested in identifying Proguard itself as in avoiding polluting results for other languages.

Related issues: https://github.com/github/linguist/pull/1633 https://github.com/github/linguist/pull/445

### URL of the affected repository:
https://github.com/search?q=proguard+extension%3Apro&type=Code

### Last modified on:
2019-11-07

### Expected language:
Proguard?

### Detected language:
INI, IDL, Prolog, QMake and others

**Comment by pchaigno** [comment]
> Do you think we should add explicit support for Proguard?

Yes, that seems like the way to go :+1:

**Comment by smola** [comment]
Fixed in https://github.com/github/linguist/pull/4708
