### ISSUE TITLE
SQLite identified as PLpgSQL

### ISSUE THREAD

**Issue by smola** [github/linguist#4707]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
SQL files in SQLite dialect detected as PLpgSQL.

Related: https://github.com/github/linguist/issues/4706

### URL of the affected repository:
https://github.com/codeschool/sqlite-parser/blob/master/test/sql/official-suite/tkt1449-1.sql

### Last modified on:
2019-11-07

### Expected language:
SQL?

### Detected language:
PLpgSQL

**Comment by smola** [comment]
Still relevant.

**Comment by survtur** [comment]
This issue is still relevant:
https://github.com/survtur/codenames-like-web/blob/main/db/init_script.sql
