### ISSUE TITLE
How to handle 'Missing include in grammar' error

### ISSUE THREAD

**Issue by pchaigno** [github/linguist#4709]
I'm trying to add https://github.com/ptomato/sublime_autotools as a grammar for the M4 language. It however contains several errors related to references to another grammar, which I'm not sure how to address...

```
paul@pc:~/git/linguist$ ./script/add-grammar https://github.com/ptomato/sublime_autotools
Checking docker is installed and running
$ docker ps
Registering new submodule: vendor/grammars/sublime_autotools
$ git submodule add -f https://github.com/ptomato/sublime_autotools vendor/grammars/sublime_autotools
$ script/grammar-compiler add vendor/grammars/sublime_autotools
  > latest: Pulling from linguist/grammar-compiler
  > Digest: sha256:0d362af120d860fb90ca36e2a0e229d84fe4319f5eeb5d38324e4917a1efd54d
  > Status: Image is up to date for linguist/grammar-compiler:latest
  > The new grammar repository `vendor/grammars/sublime_autotools` (from https://github.com/ptomato/sublime_autotools) contains 7 errors:
  >     - Missing include in grammar: `source.m4` (in `Autoconf.tmLanguage`) attempts to include `source.shell.variable` but the scope cannot be found
  >     - Missing include in grammar: `source.m4` (in `Autoconf.tmLanguage`) attempts to include `source.shell.interpolation` but the scope cannot be found
  >     - Missing include in grammar: `source.m4` (in `Autoconf.tmLanguage`) attempts to include `source.shell.logical-expression` but the scope cannot be found
  >     - Missing include in grammar: `source.m4` (in `Autoconf.tmLanguage`) attempts to include `source.shell.string` but the scope cannot be found
  >     - Missing include in grammar: `source.m4` (in `Autoconf.tmLanguage`) attempts to include `source.shell.pathname` but the scope cannot be found
  >     - Missing include in grammar: `source.m4` (in `Autoconf.tmLanguage`) attempts to include `source.shell.comment` but the scope cannot be found
  >     - Missing include in grammar: `source.m4` (in `Autoconf.tmLanguage`) attempts to include `source.shell.case-clause` but the scope cannot be found
  > 
  > failed to compile the given grammar
Command failed. Aborting.
```

@lildude @Alhadis How do you usually deal with this?

**Comment by lildude** [comment]
I've fudged it before by adding `-f` to this command:

https://github.com/github/linguist/blob/a91db8f2ff13e0d99b6fe52902a540a725291c44/script/add-grammar#L108

... which is then picked up here:

https://github.com/github/linguist/blob/a91db8f2ff13e0d99b6fe52902a540a725291c44/tools/grammars/cmd/grammar-compiler/main.go#L34-L41

I've been meaning to come and make those non-blocking.

**Comment by pchaigno** [comment]
Okay, I'll do that now. Do we have a way to properly fix the warning though?

**Comment by Alhadis** [comment]
> @lildude @Alhadis How do you usually deal with this?

I don't. This is a complete pain-in-the-ass which severely limits my ability to support other grammars which don't happen to be used by Linguist.

IMHO, this shouldn't raise an error or warning at all, because `scopeName`s are inevitably going to differ within a community, and the `source.c++`/`source.cpp` is one good example of why we should tolerate missing/unknown grammar IDs.

**Comment by pchaigno** [comment]
@Alhadis Aren't there warnings turn into missing highlighting? Couldn't we include the referred grammars?

**Comment by Alhadis** [comment]
No, see, I'd normally include both:

~~~coffee
patterns: [
	{include: "source.c++"} # Support GitHub
	{include: "source.cpp"} # Support Atom users
]
~~~

The first inclusion causes noise from the grammar compiler; but removing the latter will make the grammar less useful to Atom users (which is admittedly less of an issue nowadays).

**Comment by Alhadis** [comment]
And sometimes, it's desirable to include grammars for users who happen to have them installed. For example, a code-block in a markup language could embed TeX highlighting if a TeX package is installed, with the worst-case-scenario being an unhighlighted code sample.

**Comment by pchaigno** [comment]
Okay, that makes sense.

In my case, however, `source.shell` is the correct name. We even have a grammar with that scope in Linguist...

**Comment by Alhadis** [comment]
Oh wait, you're adding an M4 grammar?

I already wrote one. Check [`language-etc/grammars/m4.cson`](https://github.com/Alhadis/language-etc/blob/master/grammars/m4.cson).

**Comment by Alhadis** [comment]
I never got around to finishing it though, so its highlighting might be incomplete. Hence why I never proposed it for use on GitHub (but the issue about `source.shell` is odd, let me check it out…)

**Comment by pchaigno** [comment]
Oh, cool ! I'll switch to that !

**Comment by Alhadis** [comment]
Again, let me know if there's something I'll need to add for the M4 grammar to be useful. :)

**Comment by Alhadis** [comment]
Oh, and the grammar you're attempting to add is GPL-licensed. Probably forked from the same copylefted `autotools` grammar that's floating around between editors. That was the reason I started work on the M4 grammar in the first place…

Anyway, I see what's causing the `include` error: the author of `sublime_autotools` appears to be attempting to include a specific rule in the `source.shell` grammar, but with the wrong syntax:

~~~diff
-source.shell.variable
+source.shell#variable
~~~

**Comment by pchaigno** [comment]
> Again, let me know if there's something I'll need to add for the M4 grammar to be useful. :)

Any chance you would add support for [these macros](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2FAlhadis%2Flanguage-etc%2Fblob%2Fmaster%2Fgrammars%2Fm4.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fstrace%2Fstrace%2Fblob%2Fmaster%2Fconfigure.ac&code=)? Also, `#include`s seem to be recognized as comments.

> Oh, and the grammar you're attempting to add [is GPL-licensed](https://github.com/ptomato/sublime_autotools/blob/master/LICENSE). Probably forked from the same copylefted `autotools` grammar that's floating around between editors. That was the reason I started work on the M4 grammar in the first place…

Arf!

> Anyway, I see what's causing the `include` error: the author of `sublime_autotools` appears to be attempting to include a specific rule in the `source.shell` grammar, but with the wrong syntax:

Ah! I'll send a pull request for that to the grammar's repository. We can't use it, but it may be useful to someone else.
Do you have a documentation for that syntax? I found a few references in blogs, but couldn't find anything in the official TextMate documentation.

**Comment by Alhadis** [comment]
I'll see what I can do…

> Do you have a documentation for that syntax? I found a few references in blogs, but couldn't find anything in the official TextMate documentation.

Nope, none. [This](https://macromates.com/manual/en/language_grammars#naming_conventions) and [this](https://github.com/Alhadis/.files/blob/752c89dbaa2716f62f7cf5aa8e16090b55ac91c7/share/man/man5/textmate.5) are the only official source concerning TextMate grammars… the system is somewhat notorious for being under-documented.

**Comment by pchaigno** [comment]
Thanks @Alhadis for your help! I'll close this issue now, but if you ever find the time to extend support for Autoconf that'd be great! Reading Autoconf files is a pain right now...
