### ISSUE TITLE
Feature Request: Bracket comment highlighting for CMake

### ISSUE THREAD

**Issue by mathomp4** [github/linguist#4710]
I would like to request the ability to syntax highlight [CMake bracket comments](https://cmake.org/cmake/help/latest/manual/cmake-language.7.html#comments) as "comment". That is, currently if I do this:
```cmake
# This is a comment
This is not a comment
```
linguist sees the #-comment as a comment.
```cmake
#[[ This is a bracket comment in CMake.
It lasts until the end of the bracket ]]
This is not a comment
```
is not seen as a comment. It would be nice if linguist (and thus GitHub) could display that as a "block comment" much like how it does with C-code:
```c
/* This is a nice multiple
 * line comment */
This isn't
```
NOTE: I know that the docs say that bracket comments are only supported since CMake 3.0 but that was 5+ years ago. I guess one could try to be smart and detect if `cmake_minimum_required` is set to something higher than 3.0, but I think it's a fair assumption to think 3.x is now standard enough.

**Comment by lildude** [comment]
This has nothing to do with Linguist. This is entirely driven by the grammar as this is a syntax highlighting behaviour. As pointed out in the Troubleshooting docs linked in the template you deleted, you will need to raise this with the maintainers of the grammar Linguist uses.

If the grammar is no longer maintained, please feel free to open a PR linking to a maintained grammar that behaves as you wish.

As this is not something Linguist has any control over, I'm closing this issue.

**Comment by nilason** [comment]
See https://github.com/github-linguist/linguist/issues/6496#issuecomment-2108321687
