### ISSUE TITLE
How to handle a file with no extension?

### ISSUE THREAD

**Issue by alessandro-gentilini** [github/linguist#4711]
## Preliminary Steps

Please confirm you have...
- [ ] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [ ] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [ ] considered implementing an [override](https://github.com/github/linguist#overrides),
- [ ] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

I confirm the above.

## Problem Description

I have tried  to implement an override at https://github.com/alessandro-gentilini/github-linguist-and-file-with-no-extension/blob/master/.gitattributes but it seems it does not work. With that override my intention was to inform github-linguist to check file with no extension.

### URL of the affected repository:
https://github.com/alessandro-gentilini/github-linguist-and-file-with-no-extension

### Last modified on:
2019-11-10

### Expected language:
FORTRAN

### Detected language:
none

**Comment by pchaigno** [comment]
I don't think there's currently a syntax that allows to refer to extension-less files. Note that the path matchers in `.gitattributes` are actually standard git-style path matchers and unrelated to Linguist.

It seems this repository is "just" a test repository. What's the actual problem/use case here? In what situation do you need to match all extension-less files?

**Comment by alessandro-gentilini** [comment]
@pchaigno https://git-scm.com/docs/gitignore says 

> An asterisk "*" matches anything except a slash

so I am expecting that github-linguist analyzes the file with no extension, am I right?

**Comment by lildude** [comment]
This is, oddly enough, expected behaviour as there are absolutely no clues as to the language of the file in question that Linguist can use to guess for any of the strategies:

https://github.com/github/linguist/blob/a91db8f2ff13e0d99b6fe52902a540a725291c44/lib/linguist.rb#L62-L71

... until it gets to the classifier at the end. The classifier itself needs a few languages from the previous strategies in order to perform an analysis as can be seen from:

https://github.com/github/linguist/blob/a91db8f2ff13e0d99b6fe52902a540a725291c44/lib/linguist/classifier.rb#L20-L25

... but as it doesn't get any clues from the steps before (`possible_languages` will be an empty array), it can't perform an X vs Y vs Z analysis, so you get nothing.

If you want the extensionless files to be identified, you're going to need to give Linguist a helping hand... either add a modeline to the file:

```console
$ echo 'vim: syntax=Fortran' >> hello
$ git commit -am 'Force it'
[master 7ce8c9c] Force it
 1 file changed, 1 insertion(+)
$ github-linguist --breakdown
100.00% Fortran

Fortran:
hello

$
```

...or explicitly tell Linguist with a specific language override, eg `* linguist-language=Fortran`:

```console
$ git reset HEAD~1 --hard
$ github-linguist --breakdown

$ echo '* linguist-language=Fortran' >! .gitattributes
$ git commit -am 'Force it'
[master 6faabff] Force it
 1 file changed, 1 insertion(+), 1 deletion(-)
$ github-linguist --breakdown
100.00% Fortran

Fortran:
hello

$
```

**Comment by alessandro-gentilini** [comment]
@lildude thank you for your help.
I cannot modify the source code and so I would prefer to help Linguist and adding the override `* linguist-language=Fortran`; but I do not know whether this override would be correct, maybe the code could be, let's say, Algol and not Fortran.

In that way, if I understood properly, `possible_languages` will contain `Fortran`, but will the classifier be able to correct my guess?

**Comment by lildude** [comment]
The classifier won't even be involved if you implement an override. None of the strategies are as you've told it precisely what language the file is.

Essentially, you need to give Linguist some sort of clue as to what language is in the files, whether that be via the filename, extension, the content of the file or an override as it _will_ not use the classifier to assess the file against every one of the 300+ languages it knows about as this would be prohibitively slow and costly in terms of resources. It also wouldn't be particularly accurate.

**Comment by alessandro-gentilini** [comment]
Is there any way to fill `possible_languages` with two or three guesses? In that way the classifier would refine its classification, wouldn't it?

**Comment by lildude** [comment]
Yes and no. No, not directly. Yes, this is precisely what the strategies before it do, so in order for the classifier to get a few languages, you need to satisfy one or more of the strategies before it.

**Comment by alessandro-gentilini** [comment]
Without touching the source code file, what are the available strategies? Will the override in `.gitattributes` support more than one language?

**Comment by lildude** [comment]
> Without touching the source code file, what are the available strategies?

I pointed them out in my first response.

> Will the override in .gitattributes support more than one language?

Nope, not for a wildcard or the same file name ie none of these will work

```
* linguist-language=Java,Ruby,whatever  # Only the Java will apply
foo linguist-language=Java,Ruby,whatever  # Only the Java will apply
foo linguist-language=Java
foo linguist-language=Ruby
foo linguist-language=whatever # This will override all the foos above
```

On a per path basis like this _will_ work:

```
foo linguist-language=Java
bar linguist-language=Ruby
```

But that of course requires you to know the language of those files.

If you're attempting to identify the language of all the files in a repo that you don't know the content of, Linguist is probably not the right tool to use.

**Comment by alessandro-gentilini** [comment]
@lildude Thank you! Unfortunately I do not know Ruby...
