### ISSUE TITLE
Modeline strategy misclassifies WebIDL as IDL

### ISSUE THREAD

**Issue by smola** [github/linguist#4712]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Linguist has support for IDL (Interactive Data Language) and WebIDL. However, some WebIDL files use `IDL` (for Interface Description Language) modelines, and are classified as WebIDL even when they have `.webidl` extension. See: https://github.com/web-dom/web-dom/blob/09eb388a4adfaee8e4ade0c7122486b703164f5c/webidl/UDPSocket.webidl

### URL of the affected repository:
https://github.com/search?l=IDL&q=org%3Aweb-dom+extension%3Awebidl+interface&type=Code

### Last modified on:
2019-11-12

### Expected language:
WebIDL

### Detected language:
IDL

**Comment by lildude** [comment]
🤔 I don't think the modeline strategy (or even Linguist) is doing anything wrong.  The author has explicitly told their editor (which Linguist interprets too) what language they want the syntax highlighting to use, so Linguist honours it. I'm pretty sure all editors with support for both would do the same thing.

I don't think Linguist or any editor can or would want to assume the user actually wants WebIDL based on the extension when they provide a deliberate override in the file itself in the form of the modeline.  The user is free to use any extension they like, regardless of convention. There are also grammars for both so there's a good chance the user prefers the IDL syntax highlighting over the WebIDL syntax highlighter in their editor of choice, hence the addition of the modeline.  I don't think Linguist should be assuming one thing in direct contradiction of an express statement.

Essentially it comes down to what do we treat as the "source of truth".  Extensions are fluid and fickle, so taking the author's express desires is the best option, which is what Linguist and probably all editors, do. 

Linguist is never going to get things 100% correct all of the time and in these cases, if the author really doesn't like IDL for WebIDL on GitHub, they can implement an override.

I'm open to any suggestions on how we could better handle this given current implementations and constraints if you've got any ideas.

**Comment by smola** [comment]
> @lildude  The author has explicitly told their editor (which Linguist interprets too) what language they want the syntax highlighting to use, so Linguist honours it. 

The problem here is that IDL stands both for _[Interactive Data Language](https://en.wikipedia.org/wiki/IDL_(programming_language))_ and _[Interface Description Language](https://en.wikipedia.org/wiki/IDL_specification_language)_. In Vim, IDL mode is expected to be _Interface Description Language_ ([see source](https://github.com/vim/vim/blob/master/runtime/syntax/idl.vim)). The author intent is not classifying as _Interactive Data Language_, which is linguist's assumption.

Classifying WebIDL under a broader _Interface Description Language_ group wouldn't be a problem, IMHO. But classifying it under _Interactive Data Language_ is.

**Comment by lildude** [comment]
Oooops. I missed the `Data` vs `Description` difference between the two languages 😊.

> Given the ambiguity, maybe the modeline strategy should handle this as a special case?

🤔 I think adding IDL as an alias for WebIDL should also solve this as this would return two languages from the modeline leaving it up to the subsequent strategies, including the extension strategy, to further refine things.

**Comment by smola** [comment]
Still relevant.

**Comment by Alhadis** [comment]
A possible solution might be to add two new fields to `languages.yml`: `vim_name` and `emacs_name`, which (if specified) take precedence over `aliases` when executing the modeline strategy:

~~~diff
 WebIDL:
   type: programming
   extensions:
   - ".webidl"
   language_id: 395
+  vim_name: idl
~~~

This would also solve the potential problem of two languages having the same mode-name in Vim and Emacs. For instance, [Emac's YASnippets](https://github.com/github/linguist/pull/4246) and [Vim's snippet engines](https://github.com/github/linguist/pull/4656) both use the mode-name `snippet`, so a file containing `vim: ft=snippet` would be erroneously identified as YASnippet.

**Comment by smola** [comment]
@Alhadis That sounds good to me.
