### ISSUE TITLE
Wrong language diplayed

### ISSUE THREAD

**Issue by seralouk** [github/linguist#4717]
Here is my repository:

https://github.com/seralouk/Signal2BrainPlot

The main language is python and I only have one HTML file but the language icon appears as HTML code.

> (base) serafeim:Signal2Glasser loukas$ github-linguist
> 99.96%  HTML
> 0.04%   Python

**Comment by Alhadis** [comment]
Why did you delete the issue template?

**Comment by lildude** [comment]
Agreed, this indicates you've probably not read any of the troubleshooting docs which would help you answer your own question. I'll give you a hint… use the `--breakdown` flag.

**Comment by seralouk** [comment]
This is the output of using `--breakdown` flag.

> Python:
> Utilities/SeraPlot.py
> main.py
> 
> HTML:
> example_outputs/3D_mapped_signal.html

I have read the docs but still not sure how to solve my problem.

**Comment by lildude** [comment]
The issue you’ve got isn’t really an issue. Your HTML file is over 10MB whilst all your Python is just over 4KB. If you don’t want your HTML file to count, you’ll need to implement an override as detailed in the readme.
