### ISSUE TITLE
Bro and Zeek are classified as separate languages

### ISSUE THREAD

**Issue by wesinator** [github/linguist#4721]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Bro was renamed by the authors to Zeek (for more political correctness reasons fwiw).
#4516 

However, they are displayed in GitHub as two separate languages:
![image](https://user-images.githubusercontent.com/5124946/69352503-0b4e9000-0c4b-11ea-9286-393830a301ce.png)

**Comment by lildude** [comment]
🤔 this appears to be a caching issue completely outside of the control of Linguist. Bro was renamed to Zeek in https://github.com/github/linguist/pull/4516 in May and made its way to GitHub.com with the v7.5.0 release - that's how you're seeing Zeek on some repos 😄 .

Please report this problem to GitHub Support.

**Comment by wesinator** [comment]
done ticket #468037
