### ISSUE TITLE
Maya ASCII identified as Mathematica

### ISSUE THREAD

**Issue by smola** [github/linguist#4728]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
[Maya ASCII](https://autodeskmaya.fandom.com/wiki/ASCII_File) scene files are detected as Mathematica, since Maya ASCII is not supported and `.ma` extension is associated to Mathematica.

### URL of the affected repository:
[maya ascii scene extension:ma](https://github.com/search?q=maya+ascii+scene+extension%3Ama)

### Last modified on:
2019-11-27

### Expected language:
Maya ASCII?

### Detected language:
Mathematica

**Comment by scottdmilner** [comment]
Bumping this
