### ISSUE TITLE
Clean applied to .icl and .dcl files incorrectly

### ISSUE THREAD

**Issue by smola** [github/linguist#4729]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
- SGML declarations with `.dcl` extension are identified as Clean.
- XML files with `.icl` extension (usually some kind of template) too.

### URL of the affected repository:
- [extension:dcl sgml](https://github.com/search?q=extension%3Adcl+sgml)
- [extension:icl xml](https://github.com/search?q=extension%3Aicl+xml)

### Last modified on:
2019-11-29

### Expected language:
XML or SGML

### Detected language:
Clean

**Comment by smola** [comment]
Still relevant. Can this be reopened?

**Comment by lildude** [comment]
It can, but it's just going to be closed again unless someone implements a fix. Are you able to provide a fix?
