### ISSUE TITLE
My repo ifmt-blog is detected as HTML, but is a Java Spring, how to i change de repo language to Java?

### ISSUE THREAD

**Issue by gustavo-silvalara** [github/linguist#4738]
## Preliminary Steps

Please confirm you have...
- [X ] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [X ] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [X ] considered implementing an [override](https://github.com/github/linguist#overrides),
- [X ] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

**Comment by Alhadis** [comment]
> * [X ] considered implementing an [override](https://github.com/github/linguist#overrides),

Did you read the link in this step?

**Comment by gustavo-silvalara** [comment]
tnks
