### ISSUE TITLE
Incorrect detection in a Unity project

### ISSUE THREAD

**Issue by nick-morhun** [github/linguist#4739]
## Preliminary Steps

Please confirm you have...
- [x ] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x ] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x ] considered implementing an [override](https://github.com/github/linguist#overrides),
- [ x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

I have a wrong language detected, and I tried to add .gitattributes as described in the docs but it doesn't work. It looks like spaces in paths are not supported in .gitattributes, but I could not find any confirmation or workaround in the docs.

### URL of the affected repository:
https://github.com/nick-morhun/ColorBumpPrototype/
### Expected language:
C#

### Detected language:
ShaderLab

**Comment by pchaigno** [comment]
[This StackOverflow exchange](https://stackoverflow.com/questions/44986970/github-linguist-overrides-with-wildcard/44990789#44990789) might provide a workable solution for you.

**Comment by nick-morhun** [comment]
Yes, thank you, now it displays C#. At the same time it's odd that the stats bar still displays the same languages percentage.

**Comment by lildude** [comment]
![](https://pics.me.me/patience-you-must-have-my-young-padawan-marmagennratar-17758009.png) 

It doesn't any more. Remember the bit about "the background job" you read in the README you acknowledged reading? 😉
