### ISSUE TITLE
Weird issue with CRLF on submodule

### ISSUE THREAD

**Issue by karlwbrown** [github/linguist#4742]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
I'm seeing a bizarre behavior with the Typescript-TmLanguage submodule - it shows as having a different change in the working tree. Nothing I have done has helped, including these commands:
```
git submodule foreach --recursive git clean -xfd
git reset --hard
git submodule foreach --recursive git reset --hard
git submodule update --init --recursive
```
It seems to have something to do with CRLF. I have not changed any git settings. I'm using OSX 10.14.
```
|kbrown ~/dev/github/linguist/vendor/grammars/TypeScript-TmLanguage[(HEAD detached at dc5fe35) !]
| > cat .gitattributes 
# Make sure baseline files have consistent line endings
*.txt text eol=lf
```
This is what I see what I try to see status:
```
|kbrown ~/dev/github/linguist/vendor/grammars[plantuml !]
| > git st
On branch plantuml
Your branch is up to date with 'origin/plantuml'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
	modified:   TypeScript-TmLanguage (modified content)

no changes added to commit (use "git add" and/or "git commit -a")
|kbrown ~/dev/github/linguist/vendor/grammars[plantuml !]
| > git diff
diff --git a/vendor/grammars/TypeScript-TmLanguage b/vendor/grammars/TypeScript-TmLanguage
--- a/vendor/grammars/TypeScript-TmLanguage
+++ b/vendor/grammars/TypeScript-TmLanguage
@@ -1 +1 @@
-Subproject commit dc5fe357ee5582244b798917a5fc9d7cd73e6220
+Subproject commit dc5fe357ee5582244b798917a5fc9d7cd73e6220-dirty
|kbrown ~/dev/github/linguist/vendor/grammars[plantuml !]
| > cd TypeScript-TmLanguage/
|kbrown ~/dev/github/linguist/vendor/grammars/TypeScript-TmLanguage[(HEAD detached at dc5fe35) !]
| > git st
HEAD detached at dc5fe35
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   ThirdPartyNotices.txt

no changes added to commit (use "git add" and/or "git commit -a")
|kbrown ~/dev/github/linguist/vendor/grammars/TypeScript-TmLanguage[(HEAD detached at dc5fe35) !]
| > git difftool
warning: CRLF will be replaced by LF in ThirdPartyNotices.txt.
The file will have its original line endings in your working directory

Viewing (1/1): 'ThirdPartyNotices.txt'
Launch 'bc3' [Y/n]? n
```

**Comment by lildude** [comment]
This doesn't sound like a Linguist-specific issue but rather a general git/user-environment or tools issue.

I suspect something (maybe your editor, an extension in your editor, or even the difftool you're using) may be iterating over all the submodules and performing some action (maybe `git status`?) which in turn is causing the `.gitattributes` to be assessed.

To troubleshoot this, I'd suggest shutting down all editors and tools that may touch repos, remove all modifications to the global git config file, remove all local and user git config files and then clone the repo from the CLI.  A quick way to do this would be to create a new user without any customisations to their env.

This should work without any problems and standard git commands shouldn't report any changes (they don't in my env). You can then slowly add back your customisations to work out which one is triggering this behaviour.

**Comment by karlwbrown** [comment]
I'm still not sure what caused this, but it was fixed by following this answer:
https://stackoverflow.com/a/27415757/4907881

specifically:
```
git submodule deinit -f .
git submodule update --init
```
