### ISSUE TITLE
FR: Script that generates "open" colors

### ISSUE THREAD

**Issue by karlwbrown** [github/linguist#4743]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
When trying to add a language, it is rather difficult to find a color that isn't in close proximity to other colors. It would be nice if there was a script you could run that would generate a bunch of valid colors that aren't close to other ones, based on the color algorithm used and the current colors used in language.yml.

**Comment by zspitz** [comment]
Aren't there still a very large number of possible available colors?

Perhaps users of the script should be prompted for a seed color, and the script will try to get as close as possible.

Alternatively, without a seed color, perhaps the script should find the color at the farthest distance from any other color. If there are multiple good choices, use a pseudo-random number generator to choose one arbitrarily.

Another possibility -- have a script that would generate (on build, both locally and on GitHub) a color map image showing where all the currently used language colors are located, and also the areas which are too close to existing colors. It would then be trivial for contributors to open this image, find an open area by hand, and select a color from there..

**Comment by karlwbrown** [comment]
I like the color map idea - that would be a fun project.

re: possible colors, I reckon in the "color space" there are, but it's not obvious how to find them...I tried several greens, blues, yellows, and red, and kept on getting rejected - which is what inspired this FR...

**Comment by Alhadis** [comment]
Ideally, there shouldn't be any need for this. See #4506; I've been pressing @lildude to press the other GitHub staff for a consensus on whether the colour proximity can be removed (as it was obviated long ago when dividers were added to the language bar).

Regarding the script, both @lildude and I had the same idea in the past. However, it's actually not that easy, because the colour proximity calculation is complex and non-linear (as in, it's not a simple matter of comparing RGB values).

**Comment by lildude** [comment]
Yes, this is incredibly hard and unfeasible to script for several reasons:

1. The [CIEDE2000 color-difference formula](http://www.ece.rochester.edu/~gsharma/ciede2000/ciede2000noteCRNA.pdf) is pretty complex
2. Assuming we scan through the entire valid HTML colour list, the resulting list of colours will vary based on where you start. If you start at `#000000` and iterate up to `#FFFFFF` you'll get a different set of results from starting at `#FFFFFF` and iterating down to `#000000`, or starting in the middle and iteration outwards.
3.  My initial attempt using an iterative method took several hours to do on my MacBook Pro in just one direction.
4. If someone finds a colour that doesn't clash and adds it to Linguist without consulting the previously determined list, that list would become invalid and would need regenerating.
5. A predetermined list isn't really much better than the current colour proximity enforcement.

So ultimately, the solution is to remove this, but I'm still waiting on the 👍 from our design team. As soon as I get it, it'll be removed within minutes.

**Comment by pchaigno** [comment]
>     2\. Assuming we scan through the entire valid HTML colour list, the resulting list of colours will vary based on where you start. If you start at `#000000` and iterate up to `#FFFFFF` you'll get a different set of results from starting at `#FFFFFF` and iterating down to `#000000`, or starting in the middle and iteration outwards.

I'm not sure I understand that point. Is CIEDE2000(color1, color2) different from CIEDE2000(color2, color1)?

I would expect that we "just" need to compute the distance for all colours and all languages with a color assigned, so 16M times a few hundreds computations.

**Comment by lildude** [comment]
I was referring to starting with an array of colours we know are in use and then use the color-proximity gem to iterate through all the free colours. If there's no clash, add it to the array and try the next considering that colour is now in use. This is probably far from the best way of doing it, but it was the way I initially tested this idea a long time ago.

**Comment by karlwbrown** [comment]
Another approach might be a randomized algorithm; start with just choosing 1000 random colors in the RGB space and testing those all against proximity, as soon as you get ~20 colors or so, generate an HTML and open it in the users browser so they can pick one.

you could get more clever, and divide the RGB space into say 512 cubes (8x8x8), calculate the number of colors extant in each mini-cube, then start your search in the cubes with the fewest number of extant colors. I know it's not the same as the color difference algorithm but it might be close enough to work.

for someone submitting a new language, they just need to pick a color, so if we could generate even like 20 colors that will work that will save time.
