### ISSUE TITLE
Jupyter notebook as part of languages.yml

### ISSUE THREAD

**Issue by championballer** [github/linguist#4745]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

What is the premise behind the design principle of counting the language of a repo as jupyter notebook when the written code is in Python? Thanks. :)

**Comment by lildude** [comment]
I think the original PR that started the addition is a good place to start: https://github.com/github/linguist/pull/2746

**Comment by championballer** [comment]
I will give it a look, thanks. :)
