### ISSUE TITLE
is:issue is:open 6502 ASM classified as 1C Enterprise

### ISSUE THREAD

**Issue by nathanriggs** [github/linguist#4747]
I'm obviously going to override this, I just think someone should probably know this.

**Comment by lildude** [comment]
🤔 Know what? This issue doesn't provide anything that anyone could find useful as there's absolutely no context or detail. We have the template to prevent these situations and as such I'm closing this issue.

**Comment by smola** [comment]
This is probably about a few files from different Assembly variants with `.os` extension that are classified as `1C Enterprise`. It's just a few dozens of them. The results also include `Makefile.os`, which is Makefile and should be fixed at some point with prefix patterns. See: https://github.com/search?p=1&q=extension%3Aos+%28lda+OR+ldx+OR+inc+OR+mov+OR+beq+OR+brk%29&type=Code
