### ISSUE TITLE
Language breakdown on profile page

### ISSUE THREAD

**Issue by rossjrw** [github/linguist#4758]
This is definitely not a bug and likely outside the scope of Linguist itself.

It'd be pretty nice to be able to have a language breakdown on a user's profile page. The language breakdown per repository is unquestionably useful, and I feel that the same on a profile page would serve much the same purpose as the dot matrix of activity.

I was trying to organise my pinned repositories in order to best represent where my skills lie language-wise, and realised that I shouldn't really have to do that at all. And this would enable me to tell, at a glance, where someone's skills lie - or verify that their open source persona is consistent with their CV.

Consider this a request to have the Linguist bar on the profile page. This is the wrong place to make this appeal and I apologise for that, but it is somewhere.

**Comment by Alhadis** [comment]
[Try submitting a feature request to site support.](https://github.com/contact)

**Comment by pchaigno** [comment]
As @Alhadis pointed out, the right place for feature requests is GitHub Support.
