### ISSUE TITLE
How can I analyze a single file?

### ISSUE THREAD

**Issue by dhyegocalota** [github/linguist#4770]
I'm sorry if this is the wrong place to ask.

## Problem Description

I know that I can analyze a repository commit specifically... but how can I analyze a single file only?

**Comment by pchaigno** [comment]
From the command line or from a Ruby script? From the command line it's as simple as giving that file as the first argument to `github-linguist`. To see how it works from Ruby, you can [have a look at the `github-linguist` script](https://github.com/github/linguist/blob/53379ce42c00e26a816434dd4471b304efd83b09/bin/github-linguist#L50).

**Comment by dhyegocalota** [comment]
@pchaigno thank so much for this! you helped me a lot!
