### ISSUE TITLE
Lex and Yacc C++-style extensions not supported

### ISSUE THREAD

**Issue by TheOnlyMrCat** [github/linguist#4771]
## Problem Description

Linguist supports Lex and Yacc, which typically have the `.l` and `.y` extensions. This is fine
when using them normally, but when paired with Automake, C++ lexers and parsers require C++-style extensions, such as `.ll`, `.lpp`, `.lxx`, or `l++` for Lex, and likewise for Yacc

In `languages.yml`, Yacc already allows `.yy`, and `.ll` is LLVM. None of the other extensions are present.

### URL of the affected repository:
https://github.com/TheOnlyMrCat/lok

This is my repository I noticed the issue on. Countless others are likely to suffer from the same issue

### Last modified on:
2020-01-17

### Expected language:
Lex, Yacc

### Detected language:
[Not classified]

**Comment by lildude** [comment]
As linguist is community developed, support isn't going to arrive until someone familiar with the languages submits a PR. If you're familiar with these languages, please review CONTRIBUTING.md and feel free to submit a PR if the usage requirements are met.
