### ISSUE TITLE
`/bin/csh - f` shebang not recognized

### ISSUE THREAD

**Issue by phil-blain** [github/linguist#4774]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

This file : https://github.com/CICE-Consortium/CICE/blob/master/configuration/scripts/cice.build is a csh script. Linguist does not seem to be able to parse the shebang line. 
I also tested in my fork to see if the `-f` argument to csh is the culprit, it is not: 
https://github.com/phil-blain/CICE/blob/linguist-csh-check/configuration/scripts/cice.build

### URL of the affected repository:
https://github.com/CICE-Consortium/CICE/
### Last modified on:
This issue was created on 2020-01-17.
The file `cice.build` in CICE-Consortium/CICE was last modified on 28 Aug 2019 (although the shebang has always been the same)
The file `cice.build` in my fork was created 3 hours ago.

### Expected language:
Csh

### Detected language:
None

**Comment by lildude** [comment]
This has already been fixed in https://github.com/github/linguist/pull/4760 and GitHub will get this when I next make a release, which I aim to do before the end of the month.

**Comment by phil-blain** [comment]
Super! I did Iook at the languages.yml file and saw this section but I didn't think about the fact that maybe it was not deployed yet. Thanks!

**Comment by phil-blain** [comment]
Seems like a new release has been deployed! thanks!
