### ISSUE TITLE
R file incorrectly classified as Rebol

### ISSUE THREAD

**Issue by ngriffiths21** [github/linguist#4782]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

An [R file](https://github.com/ngriffiths21/typer/search?l=rebol) in a new project was misclassified as Rebol. Last push was last night (1/23/19 @ 9pm EST) and it was indexed an hour after.

**Comment by ngriffiths21** [comment]
I am not familiar with REBOL but this could be easy to fix given that all valid rebol scripts [must begin](http://www.rebol.com/docs/core23/rebolcore-5.html#section-2) with `REBOL [ ... ]`. I see that the [heuristics](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.yml) already use this to classify Rebol files. Couldn't they use the lack of "REBOL" to classify R files?

**Comment by pchaigno** [comment]
That seems like a good idea, as far as I see. Maybe we should constrain the Rebol heuristic rule a little bit more though and match on `REBOL [` case-sensitively instead of `rebol` case-insensitively?

/cc @earl who contributed the Rebol heuristic rule originally.

**Comment by ngriffiths21** [comment]
The docs have `REBOL [` but some samples start with `Rebol [` so maybe case-insensitive is better?

For the R pattern, would something like `(?im:^(?!\s*rebol\s*\[).*)` be appropriate or is that too aggressive?

**Comment by pchaigno** [comment]
@ngriffiths21 Do you want to submit a pull request for this change?

> For the R pattern, would something like `(?im:^(?!\s*rebol\s*\[).*)` be appropriate or is that too aggressive?

We can simply improve a little the Rebol heuristic rule as discussed and remove the pattern for R. This way files that don't match the Rebol heuristic will be classified as R.

**Comment by tony-aw** [comment]
The issue in question is still present. .R files are still sometimes identified as Rebol instead of R.
