### ISSUE TITLE
Smalltalk files are misidentified as HTML

### ISSUE THREAD

**Issue by LinqLover** [github/linguist#4789]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
this seems to be a general problem of many Smalltalk repositories generated by [FileTree](https://github.com/dalehenrich/filetree).
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Same as #2517, but that has already been closed some years ago.

Without specific knowledge of the linguist implementation, here are some patterns that might indicate Smalltalk instead of HTML:
- The file is not well-formed, so there is no single root tag.
- (Specific to [FileTree](https://github.com/dalehenrich/filetree)-built repositories: The `.st` file paths follow the pattern: `**/<somePackage>.package/<someClass>.(class|trait|extension)/(instance|class)/*.st`)

### URL of the affected repository:

https://github.com/LinqLover/XmasDecorations/search?l=HTML

Absolutely nothing in this repository should be identified as HTML.

### Last modified on:
2019-11-29

### Expected language:
Smalltalk

### Detected language:
HTML

**Comment by pchaigno** [comment]
The best way to fix this is probably to add a [heuristic rule](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.yml) to help Linguist distinguish between Smalltalk and HTML.

Without someone who knows Smalltalk to do this, this issue is going to become stale and be closed. Note that writing heuristic rules doesn't require any Ruby knowledge, though is does require writing some regular expressions. We'd be happy to help you do this of course.

**Comment by LinqLover** [comment]
I can try to help :-)

## Possible `.st` file patterns

### 1. Method files
#### 1a Without class declaration

```smalltalk
methodName
	"some code"
```

```smalltalk
keyword1: arg1 keyword2: arg2 keyword3: arg3
	"some code"
```

```smalltalk
method-category-name
methodName
	"some code"
```

```smalltalk
method-category-name
keyword1: arg1 keyword2: arg2 keyword3: arg3
	"some code"
```

#### 1b. With class declaration

```smalltalk
ClassName >> method-category-name
methodName
	"some code"
```

```smalltalk
ClassName >> method-category-name
keyword1: arg1 keyword2: arg2 keyword3: arg3
	"some code"
```

#### 2. Script files
They are harder, because everything in Smalltalk is an object, so an ST script can start with almost every syntactical element:
```smalltalk
self inform: 'Hello world'
```
```smalltalk
#[1 2 3] do: #yourself
```
```smalltalk
{6. 7} sum
```
```smalltalk
#sum value: {6. 7}
```
```smalltalk
nil.
```
```smalltalk
Smalltalk garbageCollect
```
```smalltalk
123459789 sqrt
```
```smalltalk
"a comment"
```
So, you see, rather hard to match.

## First regex pattern for `.st` files indicating Smalltalk _method_ files (_only_ variant a from above!)

```regex
\A((\S+\h*>>\S+)?\S+\v)?(\S+|(\S+:\s*\S+\s+)?\S+:\s*\S+)
```

---

I'd rather tend to create a pattern for StringTemplate (HTML). If I understand it correctly, StringTemplates always have to be written in an XML format? So basically, we could write a pattern that checks whether the file starts with a tag.  
Something like this:
```regex
\A\s*(\<\?\S+|\<\S+\/?\>|\<!--)
```

I am looking forward to your opinion! :-)

**Comment by LinqLover** [comment]
Post scriptum: There are a lot of other Smalltalk dialects, which define several different `.st` file formats:
- Pharo has the tonel format (https://github.com/pharo-vcs/iceberg/blob/dev-1.0/Iceberg-Libgit/IceGitChange.class.st)
- Cuis has the changeset format (https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/blob/master/Packages/Goodies.pck.st)
(Thanks to @tom95 for the summary)

This strengthens my opinion that it might be better to identify StringTemplate instead.

**Comment by Nixinova** [comment]
Would 'not match `</[\w-]+>`' be a valid heuristic? Seems much simpler.

**Comment by Nixinova** [comment]
Actually, why is `.st` under raw HTML anyway? Was added in #1117 as a HTML variant, but per #4979 HTML variants should be split anyway. Should I issue a PR moving `.st` to its own languages and add a heuristic for Smalltalk vs StringTemplates?

**Comment by Nixinova** [comment]
Here's the heuristic I used:

https://github.com/Nixinova/fork_linguist/blob/f5687c201628180703431b1ea610615c400e0ccc/lib/linguist/heuristics.yml#L514-L521

@LinqLover is that good?

**Comment by LinqLover** [comment]
@Nixinova Many thanks for working on this issue! Does your proposal match [these examples](https://github.com/github/linguist/issues/4789#issuecomment-581166364) and also [these examples](https://github.com/search?q=doesnotunderstand%3A+aMessage&type=code) correctly as Smalltalk?

So your proposal is to reserve `.st` for Smalltalk and use an extra pattern to identify the HTML variants? From my perspective of a "Smalltalk stakeholder" this sounds great, of course. Maybe someone from the HTML party (@pchaigno?) could give their OK as well?

**Comment by Nixinova** [comment]
I'm using </endtags> and $dollar(functions)$ to identify the HTML one, and have a bunch of keywords to identify Smalltalk. They match all the samples given to Linguist, at least, and I went through your list and tries to match them all.

**Comment by LinqLover** [comment]
I don't really see how your pattern matches a Smalltalk program such as `nil` - but if it does, it sounds great to me! And anyway, it will be a clear improvement compared to the current state. Looking forward to your PR being merged ... :-)

**Comment by Nixinova** [comment]
> such as `nil`

The pattern starts with `\A\s*[\[{("\w\d#]`, meaning match any [, {, (, ", letter, number, or hashtag at the start of a document.

**Comment by LinqLover** [comment]
> > such as `nil`
> 
> The pattern starts with `\A\s*[\[{("\w\d#]`, meaning match any [, {, (, ", letter, number, or hashtag at the start of a document.

Maybe worth adding `^` (which is the return character in Smalltalk) and a `'` for strings?

**Comment by Nixinova** [comment]
> Maybe worth adding ^ (which is the return character in Smalltalk) and a ' for strings?

Okay, will do

**Comment by LinqLover** [comment]
Great you got this done! 🎉
