### ISSUE TITLE
My repository no longer displays the languages used

### ISSUE THREAD

**Issue by LoboMetalurgico** [github/linguist#4790]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

After one commit, all the languages ​​that were being used in the repository are gone and it looks like there is no language.

### URL of the affected repository:

https://github.com/Allons-y-Corp/allonsve

### Last modified on:
2020/02/02

### Expected language:
PHP
JS
CSS
OTHER

### Detected language:

None

**Comment by lildude** [comment]
You've committed a `.gitattributes` file with an incorrect override. Either delete the file or correct the override in it.

**Comment by LoboMetalurgico** [comment]
Oh, Thanks!
