### ISSUE TITLE
Support end of line comments in Indented Sass (.sass)

### ISSUE THREAD

**Issue by amercier** [github/linguist#4793]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Comments in **Indented Sass (.sass)** work mostly fine, except at the end of a line.

Note: this could be related to #1852.

#### Source

```
/**
 * Dockblock style comments are fine at the start of a line
 */
/* Slash-asterisk style comments are fine at the start of a line */

div
  color: green /* Slash-asterisk style comments are ignored at the end of a line */

// Double-slash style comments are fine at the start of a line

div
  color: red // Double-slash style comments are ignored at the end of a line
```

#### Output (screenshot):

![image](https://user-images.githubusercontent.com/1246795/73816669-84409b00-47e9-11ea-9841-e8aa550bc774.png)

#### Output (actual comment block):

```sass
/**
 * Dockblock style comments are fine at the start of a line
 */
/* Slash-asterisk style comments are fine at the start of a line */

div
  color: green /* Slash-asterisk style comments are ignored at the end of a line */

// Double-slash style comments are fine at the start of a line

div
  color: red // Double-slash style comments are ignored at the end of a line
```

#### Expected output

End of line comments (between `/* */`, or after `//`) should be parsed as comments.

### URL of the affected repository:

It's on a private repository, sorry I'm not able to disclose, please refer to screenshot and markup above.

### Last modified on:

2020-02-05

### Expected language:

Sass (indented)

### Detected language:

Sass (indented)

**Comment by Alhadis** [comment]
As explained by [our readme](https://github.com/github/linguist#theres-a-problem-with-the-syntax-highlighting-of-a-file):

> Linguist detects the language of a file but the actual syntax-highlighting is powered by a set of language grammars which are included in this project as a set of submodules [as listed here](https://github.com/github/linguist/blob/master/vendor/README.md).
>
> If you experience an issue with the syntax-highlighting on GitHub, **please report the issue to the upstream grammar repository, not here.**

Linguist currently uses [`atom/language-sass`](https://github.com/atom/language-sass) for SCSS and Sass highlighting, so this issue should be reported there.
