### ISSUE TITLE
Adding OpenQASM support

### ISSUE THREAD

**Issue by neelkamath** [github/linguist#4795]
## Preliminary Steps

I confirm that I have:
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

IBM's [OpenQASM](https://github.com/Qiskit/openqasm/blob/master/examples/generic/adder.qasm) language is a decently popular assembly language for running on real quantum computers. I'd like https://github.com to show language colors and statistics via **linguist** for these programs.

### URL of the affected repository: https://github.com/neelkamath/quantum-experiments

Here's an example of the [official repo's file](https://github.com/Qiskit/openqasm/blob/master/examples/generic/adder.qasm) not highlighting because it isn't being recognized.

### Expected language:
OpenQASM

### Detected language:
It's not detected

**Comment by Alhadis** [comment]
[This is all explained in the contribution guide](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language).

**Comment by pchaigno** [comment]
Closing in favor of #4796.

**Comment by Alhadis** [comment]
@pchaigno This was an issue, not a pull-request. :wink:

**Comment by pchaigno** [comment]
I know ;)
