### ISSUE TITLE
Linguist - Misclassified language for repository 

### ISSUE THREAD

**Issue by anushadatta** [github/linguist#4807]
## Preliminary Steps

Please confirm you have...
- [ ] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [ ] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [ ] considered implementing an [override](https://github.com/github/linguist#overrides),
- [ ] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

The predominant language featured in the repository has been identified as HTML, however that is incorrect. It is a purely Java based application.  

### URL of the affected repository:
https://github.com/anushadatta/Movie-Booking-Application

### Expected language:

Java

### Detected language:

HTML

**Comment by Alhadis** [comment]
Please fill out the template. The solution to your problem is quite literally in the links you didn't read.

**Comment by lildude** [comment]
> The predominant language featured in the repository has been identified as HTML, however that is incorrect. It is a purely Java based application.

🙈 https://github.com/anushadatta/Movie-Booking-Application/tree/master/assignment/doc 🙈
