### ISSUE TITLE
Linguist: Typescript syntax highlighting breaking on certain regex following !

### ISSUE THREAD

**Issue by infinnie** [github/linguist#4809]
> Funnily enough, it appears this code breaks GitHub's syntax highlighting as well.

Forwarded from: https://github.com/microsoft/TypeScript-TmLanguage/issues/806

## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

When using the TypeScript as the language, syntax highlight breaks.

```ts
class Foo {
    public foo(): boolean {
        return !/[():\w]/.test('foo');
    }

    private bar(): void {}
}
```

The JavaScript one, unlike in VS Code however, works:
```js
!/[():\w]/.test('foo');
```

It seems related to the aforementioned upstream bug.

**Comment by Alhadis** [comment]
> It seems related to the aforementioned upstream bug.

And *because* it's an upstream bug, this issue shouldn't be reported here. 😉

Please see our [troubleshooting section](https://github.com/github/linguist#theres-a-problem-with-the-syntax-highlighting-of-a-file) about syntax highlighting errors.
