### ISSUE TITLE
Error in master build after merge

### ISSUE THREAD

**Issue by rewinfrey** [github/linguist#4813]
After merging in https://github.com/github/linguist/pull/4805 the master build began failing. Here's the [latest build run](https://github.com/github/linguist/commit/69bd5e6bf8696812f2f7c8af5288beec4e803502/checks?check_suite_id=509475795). First time contributing to `linguist` and I'm not seeing a clear link between the test failure and the patch I merged and could use some help in getting master back to green.

```shell
  1) Failure:
TestRepository#test_repo_git_attributes [/home/runner/work/linguist/linguist/test/test_repository.rb:77]:
Expected false to be truthy.
```

/cc @lildude

**Comment by lildude** [comment]
That test is this one https://github.com/github/linguist/blob/69bd5e6bf8696812f2f7c8af5288beec4e803502/test/test_repository.rb#L49-L81... and is used to test the `.gitattributes` override behaviour which we test using the [`test/attributes`](https://github.com/github/linguist/tree/test/attributes) branch.

That error indicates the analysis of the repo hasn't found any files identified as Perl. We've hit this problem several times before and without checking, I'm guessing there was a new Rugged release in the last 24 hours - it seems to be the only gem update that we regularly detect breakage in... ie it breaks and we're the first to detect it. I think this is another one of those cases.

**Comment by lildude** [comment]
Bingo!!! https://github.com/libgit2/rugged/releases/tag/v0.99.0 released 16 hours ago.

Digging into this to see why this update has borked things again.

/cc @carlosmn

**Comment by carlosmn** [comment]
We were able to trace this to most likely a regression in libgit2 when the paths are not valid utf8. `Linguist::LazyBlob` is unable to look up the `linguist-vendored=false` attribute for this perl file in a directory with some nonsense in its name.

**Comment by lildude** [comment]
I'm going to lock Linguist to an earlier version of Rugged whilst we wait for the upstream regression to be fixed.

**Comment by carlosmn** [comment]
It turns out this is... erm.. expected... sort of.

git switch from fnmatch to wildmatch some time ago, and libgit2 only recently did so. What this does is change some of the rules around recursion. Linguist is expecting the old rules where `test/fixtures/*` covers everything under fixtures, but this is no longer the case.

Switching the rule to `test/fixtures/**` does make it match again. See libgit2/libgit2#5450 for some more discussion.

**Comment by lildude** [comment]
🤦‍♂ Of course. I wasn't thinking about that side of things. I've tested locally and that does indeed do the trick. I'll open a PR to update the `.gitattributes` instead of locking down the rugged version.
