### ISSUE TITLE
standalone scipt or binary?

### ISSUE THREAD

**Issue by balaprasathr** [github/linguist#4824]
I see this is more integrated to work with only on git repositories. By any chance can we have this as a standalone script or binary to make it work on any repository? It would be super helpful.

**Comment by lildude** [comment]
Unfortunately not. The language analysis part of Linguist is written entirely in Ruby which relies on several external third party gems. Inlining them all into a single standalone script would be brutal and lead to a massively complicated and unmaintainable script.

If you want language analysis in a single binary, checkout https://github.com/src-d/enry. It lags Linguist a little, but it's written in Go, doesn't require the files to be part of a git repo, and releases are shipped as a single binary.

**Comment by balaprasathr** [comment]
That worked. Thank you very much.
