### ISSUE TITLE
My repository is not showing a language bar

### ISSUE THREAD

**Issue by stormasm** [github/linguist#4833]
My repository is not showing a language bar...
https://github.com/stormasm/redsled

Thanks for looking into why my repo is not displaying a language bar.

## Preliminary Steps

Please confirm you have...
- [ x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x ] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [ x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [ x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
My repository is not displaying a language bar...

### URL of the affected repository:
https://github.com/stormasm/redsled

### Last modified on:

2020-03-27

### Expected language:

Rust

### Detected language:

Rust

**Comment by Alhadis** [comment]
Your Rust files are stored in a directory named `examples`, which Linguist [treats as documentation](https://github.com/github/linguist/blob/40992ba7f86889f80dfed3ba95e11e1082200bad/lib/linguist/documentation.yml#L17). You can override this by adding a [`.gitattributes` file](https://github.com/github/linguist/blob/master/README.md#documentation) with the following line:

~~~gitattributes
examples/* -linguist-documentation
~~~

**Comment by stormasm** [comment]
@Alhadis Thanks kindly that fixed the problem.  

You can go ahead and close this issue...


I really appreciate the quick turn around time on this issue.  Hopefully it will help other folks who have Rust repositories with mainly example files instead of src files.

**Comment by stormasm** [comment]
Attention Rust programmers viewing this issue !   
You must add a line to your .gitattributes file if most of your Rust programs are located in the example directory...
