### ISSUE TITLE
Issue publishing pure HTML site on GitHub.

### ISSUE THREAD

**Issue by Donnyman777** [github/linguist#4834]
I'm new to coding and even newer to understanding GitHub. When clicking the link to see my published site, it always shows this page https://donnyman777.github.io/CV/
which is completely blank save for the word 'CV' at the top.

I've done the preliminary steps to try and solve the problem, but I'm still confused. It's a basic HTML5-based practice website. My files are all uploaded to my repository, and they work fine when I open them locally, but not here on GitHub for some reason. Can this site host pure HTML sites?

My repository: https://github.com/Donnyman777/CV

**Comment by lildude** [comment]
I'm afraid you've come to the wrong place for help. This repo is specifically for the language detection of a repo's content. https://help.github.com/en/github/working-with-github-pages has loads of info on using GitHub Pages so try there first. If you're still having problems after reading the docs (it definitely has the necessary info as to why you're HTML isn't rendering 😉), try the https://github.community/ forums.

As this issue isn't related to Linguist at all, I'm closing this issue.
