### ISSUE TITLE
Bug: Repo is being reported as all CSS?

### ISSUE THREAD

**Issue by Abourass** [github/linguist#4836]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
Despite my repo being mostly Vue / JS, I'm showing 98% CSS. My only css file has about 10 lines, so can't be the majority of my repo. 

### URL of the affected repository:
https://github.com/Abourass/mevn-template-with-tailwindCSS

### Last modified on:
2020/1/04

### Expected language:
Majority JS / Vue

### Detected language:
CSS and "Other"

**Comment by lildude** [comment]
No bug. This is 100% accurate.  You have one mahoosive CSS file you've missed:

https://github.com/Abourass/mevn-template-with-tailwindCSS/blob/master/server/public/app.css

At 979 KB it far outweighs the total of everything else and its size makes your other files almost insignificant in the total - your other CSS file doesn't even register when things are rounded 😉 :

CSS 979 KB 
Vue 4.36 KB
JavaScript 4.26 KB
HTML 245 Bytes

**Comment by Abourass** [comment]
Ahhh, my bad. For some reason that didn't show when I tried looking up all the CSS files. Definitely my mistake, sorry about that. 
![image](https://user-images.githubusercontent.com/39917231/78263007-a2abd580-74be-11ea-9083-167309135e39.png)

**Comment by lildude** [comment]
> For some reason that didn't show when I tried looking up all the CSS files.

That's explained in the code search restrictions linked to in the first point at https://github.com/github/linguist#my-repository-is-detected-as-the-wrong-language of the README 😁

**Comment by Abourass** [comment]
Ah man, I really didn't follow that well. My bad again. Lesson learned
