### ISSUE TITLE
Kconfig Language

### ISSUE THREAD

**Issue by HappyFacade** [github/linguist#4838]
Hello, I thought I would open an issue to request support for the [Kconfig (Linux Kernel config) language](https://www.kernel.org/doc/Documentation/kbuild/kconfig-language.txt)

Grammar/syntax: https://github.com/luveti/kconfig-vscode

Example from [Chion82/netfilter-full-cone-nat](https://github.com/Chion82/netfilter-full-cone-nat) readme:

```kconfig
config IP_NF_TARGET_FULLCONENAT
  tristate "FULLCONENAT target support"
  depends on NETFILTER_ADVANCED
  select NETFILTER_XT_TARGET_FULLCONENAT
  ---help---
  This is a backwards-compat option for the user's convenience
  (e.g. when running oldconfig). It selects
  CONFIG_NETFILTER_XT_TARGET_FULLCONENAT.
```

**Comment by lildude** [comment]
The Linguist project relies upon community supplied contributions for new languages. Please feel free to review the CONTRIBUTING.md and submit a pull request adding support.
