### ISSUE TITLE
YAML Recognized Though Not Included in Stats

### ISSUE THREAD

**Issue by bwmills** [github/linguist#4848]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

I looked through open/closed issues, and confirmed that my initial idea was in fact wrong. (I thought our use of `.yml` as the file extension for Kubernetes manifests, rather than `.yaml`, was preventing the  language stats bar from including YAML; but I see now that `.yml` is a supported extension in [languages.yml](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml).) 

I saw some closed issues that relate to YAML, though none with my exact scenario.

## Note

Greetings and thanks for a great project. 
Please note that the GitHub repo in question is private.

## Problem Description

Given that `.yml` should be good to have YAML (manifests) recognized, the issue is this.

The language stats bar is showing only Python (56.2%) and Shell (43.8%), but no YAML at all. Selecting the blue (Python) / green (Shell) stats bar, and then selecting a listed language (e.g. Python), takes me to a page with this URL:

```
https://github.com/<owner>/<repo-name>/search?l=python
```

with this table of file types and languages:

```
Languages

  YAML         174
  Shell          3
  Markdown       2
  Python         1
  Text           1
  Ignore List    1
```

The 174 YAML files are Kubernetes manifests that were built by our team, pushed to GH to open PRs, and merged in a typical agile work flow. None of the YAML is vendored code, generated code, or documentation.

## Goals

* To have the YAML files (with `.yml` extension) included in the language stats bar
* To have the language stats correctly reflect accurate percentages

## Questions

* Am I missing something simple on this?
* Would this be a good case to use an override with `gitattributes`?

**Comment by Alhadis** [comment]
> Would this be a good case to use an override with `gitattributes`?

You've literally [answered your](https://github.com/github/linguist#my-repository-isnt-showing-my-language) [own question](https://github.com/github/linguist#detectable). :wink:

**Comment by bwmills** [comment]
Thanks @Alhadis for the fast response - ok I'll do just that and follow-up.

**Comment by lildude** [comment]
As for why you need the override, it's because YAML is considered a data language so not considered when calculating the language statistics:

https://github.com/github/linguist/blob/40992ba7f86889f80dfed3ba95e11e1082200bad/lib/linguist/languages.yml#L6120-L6121

**Comment by bwmills** [comment]
Thanks and understood @lildude 😄

**Comment by bwmills** [comment]
Thanks again @lildude - I'll monitor and check there.
