### ISSUE TITLE
My ASP.NET Core MVC project was detected like Javascript project

### ISSUE THREAD

**Issue by romarius-by** [github/linguist#4850]
## Problem Description
My project was detected by Linguist like Javascript project. But it's ASP.NET Core MVC project.

### Last modified on:
24.04.2020

### Expected language:
C#

### Detected language:
Javascript

**Comment by Alhadis** [comment]
Was there something wrong with the template you neglected to fill out...?

**Comment by romarius-by** [comment]
oh, yes, sorry)

**Comment by Alhadis** [comment]
https://github.com/github/linguist#my-repository-is-detected-as-the-wrong-language

**Comment by dush-a** [comment]
Even if you are using a C# web project, you might have references to JavaScript files such as jQuery. This can be fixed by adding a `.gitattributes` file to the root of the project and adding the following line at the end of the file.

`*.js linguist-detectable=false`
