### ISSUE TITLE
Does not work on non-git directory

### ISSUE THREAD

**Issue by arkban** [github/linguist#4854]
It looks like `linguist` will only successfully run inside an actual git repository, not just a directory.

## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [ ] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem

1. Run `linguist` in an empty directory
    1. I did this using [crazymax/linguist](https://github.com/crazy-max/docker-linguist) [docker image](https://hub.docker.com/r/crazymax/linguist) because it's easy to setup
1. Throws ugly error

## Expectation

- A nicer error that says something about "this has to be run in a git repo"
- Ignore the git stuff if not in a git repository

## Steps to replicate

```shell script
$ mkdir bar
    
$ cd bar
    
$  docker run -t --rm -v "$(pwd):/repo" crazymax/linguist:7.9.0
Unable to find image 'crazymax/linguist:7.9.0' locally
7.9.0: Pulling from crazymax/linguist
Digest: sha256:13e31803de310529e01e842bf31c5a4f8881469e5d855e1962e9c18073d60f75
Status: Downloaded newer image for crazymax/linguist:7.9.0
Traceback (most recent call last):
        3: from /usr/bin/github-linguist:23:in `<main>'
        2: from /usr/bin/github-linguist:23:in `load'
        1: from /usr/lib/ruby/gems/2.6.0/gems/github-linguist-7.9.0/bin/github-linguist:27:in `<top (required)>'
/usr/lib/ruby/gems/2.6.0/gems/github-linguist-7.9.0/bin/github-linguist:27:in `new': could not find repository from '/repo' (Rugged::RepositoryError)

$ git init
Initialized empty Git repository in /<REDACTED>/bar/.git/

$ docker run -t --rm -v "$(pwd):/repo" crazymax/linguist:7.9.0
Traceback (most recent call last):
       3: from /usr/bin/github-linguist:23:in `<main>'
       2: from /usr/bin/github-linguist:23:in `load'
       1: from /usr/lib/ruby/gems/2.6.0/gems/github-linguist-7.9.0/bin/github-linguist:28:in `<top (required)>'
/usr/lib/ruby/gems/2.6.0/gems/github-linguist-7.9.0/bin/github-linguist:28:in `head': reference 'refs/heads/master' not found (Rugged::ReferenceError)

$ echo "# README" > README.md                                                                                                                                         

$ git add README.md
    
$ git commit -m "Added README.md"
[master (root-commit) e42c0c5] Added README.md
1 file changed, 1 insertion(+)
create mode 100644 README.md

$ docker run -t --rm -v "$(pwd):/repo" crazymax/linguist:7.9.0

$
```

**Comment by arkban** [comment]
So, maybe this is "working as designed" because when linguist seems to ignore all _uncommitted_ code:
(following from above):
```shell script
$  ls
README.md

$ docker run -t --rm -v "$(pwd):/repo" crazymax/linguist:7.9.0

$ echo "import sbt" > build.sbt

$ docker run -t --rm -v "$(pwd):/repo" crazymax/linguist:7.9.0

$ git add build.sbt

$ git commit -m "Added build.sbt"
[master 43ed6bd] Added build.sbt
 1 file changed, 1 insertion(+)
 create mode 100644 build.sbt

$ docker run -t --rm -v "$(pwd):/repo" crazymax/linguist:7.9.0
100.00% Scala

$
```
The [README.md](https://github.com/github/linguist/blob/master/README.md) says "repository" a lot yet it never says that it _only_ looks at what is in the repository as opposed to the directory. I figured it was just using "repository" as a synonym for "working directory", but I guess not...?

**Comment by lildude** [comment]
Correct. This only works on Git repos and only on committed changes or single files. It's primary use is on GitHub.com which uses bare repositories and thus changes need to be committed as individual files don't show on the filesystem.

So whilst not explicitly stated, it is repeatedly indicated by "detect blob languages" in the very first sentence of the READNE.md and the term repository and not directory in all the documentation. The override method drives that home too.

If you really wanted to, you could iterate over every file and pass it to Linguist to analyse as it can perform analysis on a single file without committing to a repo, however this isn't likely to be very performant and you'll still need to implement a lot of other glue for the totals and override support.

Alternatively you could initialise a temp repo as demonstrated in the script mentioned in https://github.com/github/linguist/issues/3563 about this same topic.

**Comment by arkban** [comment]
Thank you for your detailed response!

I took a whack at trying to be a bit more explicit in the README, since clearly some people are missing these clues. https://github.com/github/linguist/pull/4856

**Comment by dudufyfihf** [comment]
https://api.whatsapp.com/send?phone=+967713683710

**Comment by dudufyfihf** [comment]
https://api.whatsapp.com/send?phone=+967713683710

**Comment by dudufyfihf** [comment]
https://api.whatsapp.com/send?phone=+967713683710

**Comment by dudufyfihf** [comment]
> Thank you for your detailed response!
> 
> I took a whack at trying to be a bit more explicit in the README, since clearly some people are missing these clues. #4856
