### ISSUE TITLE
Correctly highlight var in java

### ISSUE THREAD

**Issue by doctorpangloss** [github/linguist#4859]
<img width="479" alt="Screenshot 2020-05-08 13 47 31" src="https://user-images.githubusercontent.com/2229300/81448049-973d7100-9132-11ea-98df-cd6f2b09d0ba.png">

`var` is a Java keyword.

https://github.com/textmate/java.tmbundle/pull/57 is related

**Comment by Alhadis** [comment]
https://github.com/github/linguist#theres-a-problem-with-the-syntax-highlighting-of-a-file
