### ISSUE TITLE
ASP Classic vs ASP.NET

### ISSUE THREAD

**Issue by PieterCooreman** [github/linguist#4867]
Hello,

Linguist does not make any distinction between Classic ASP and ASP.NET. That is confusing for both groups of developers.

Is it possible to separate both? Classic ASP files always have the extension ".asp". ASP.NET applications never have the extension .asp. 

Many thanks for taking this into consideration.

Grts, Pieter

**Comment by pchaigno** [comment]
We'd welcome a pull request to separate the two! :+1:

**Comment by smola** [comment]
Bump [for stale bot].

**Comment by smola** [comment]
@PieterCooreman Maybe you can help by reviewing this PR: https://github.com/github/linguist/pull/4924

**Comment by PieterCooreman** [comment]
Guys please... stale ... what the heck?

This is SUUUUPER crucial if you're serious about MicroSoft technology... I mean, GitHub is OWNED by MicroSoft isn't it? I really don't get why you did get thisn right frm day 1.

No offense. Just super worried and shocked by this lack of professionalism.

**Comment by lildude** [comment]
> @PieterCooreman Maybe you can help by reviewing this PR: #4924

Looks like we're waiting on you 😉

**Comment by PieterCooreman** [comment]
> > @PieterCooreman Maybe you can help by reviewing this PR: #4924
> 
> Looks like we're waiting on you 😉

I have no clue what to do or where to start... Can you perhaps help me out a little? tx!

**Comment by lildude** [comment]
Sure. Have a look at the PR @smola has raised and see if this addresses your concerns. If you spot anything that may need changing or has been missed, comment as such in the PR.

If you're happy, feel free to approve the PR. It won't be merged until one of the other contributors and then me approve it too.

**Comment by PieterCooreman** [comment]
Ok thank you! I have approved the suggested changes.
