### ISSUE TITLE
Ignoring `.Rd` files in `man/` folder from GitHub's code stats

### ISSUE THREAD

**Issue by K-Maehashi** [github/linguist#4869]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
I am creating an R package and I want to exclude `.Rd` files from the stats. `.Rd` files are stored in `man/` folder.

I tried several things.

First, I checked [documentation.yml](https://github.com/github/linguist/blob/master/lib/linguist/documentation.yml) which lists documentation folders. `man/` is listed, but `.Rd` files are calculated as a part of R files (`.Rd` files show up if I click R's percentage).

Next, I added a `.gitattributes` file. All of the following attempts did not work.
```
# 1
man/* linguist-documentation
```

```
# 2
*.rd linguist-language=Text
```
```
# 3
man/*.Rd linguist-documentation
```

### URL of the affected repository:
Sorry it is in a private repository. But for example, [this repository](https://github.com/tidyverse/tibble/search?l=r&p=3) detects `.Rd` files in `man/` folder. The documentation says "Linguist excludes documentation files from your project's language stats.", so I am wondering why this happens and trying to find a way to exclude `.Rd`.

### Expected language:
R Documentation (just a text file)

### Detected language:
R

**Comment by lildude** [comment]
First and foremost, don't mix the results of clicking the language in the language bar with what has actually been counted: two different components are at play. The results are from the search results and the language bar stats are from Linguist. Linguist deliberately has no influence on the search results as you'd never be able to find any of the files you may have chosen to hide from the stats if it did.

With that in mind, you'll find thanks to this line https://github.com/github/linguist/blob/16507700cdf46a78368a571c04d1bc601f62947d/lib/linguist/documentation.yml#L16 your `man/*.Rd` files _will_ be excluded from the language stats (but not the search results), and they are for the repo you've referenced and we can confirm this by running Linguist on the command line:

```console
[~/t/t/tibble master]$ github-linguist . --breakdown
97.55%  R
2.38%   C
0.07%   Rebol

R:
R/aaa-pillar.R
R/add.R
R/as_tibble.R
R/class-tbl_df.R
R/compat-friendly-type.R
R/compat-lazyeval.R
R/compat-lifecycle.R
R/compat-purrr.R
R/deprecated.R
R/dftbl.R
R/enframe.R
R/error.R
R/glimpse.R
R/has-name.R
R/lst.R
R/names.R
R/new.R
R/options.R
R/pipe.R
R/print.R
R/rownames.R
R/str.R
R/strrep.R
R/subsetting-matrix.R
R/subsetting.R
R/tbl_sum.R
R/tibble-package.R
R/tibble.R
R/tidy_names.R
R/tribble.R
R/utils-msg-format.R
R/utils-tick.R
R/utils.R
R/view.R
R/zzz.R
revdep/check.R
revdep/post-mortem/01-load.R
revdep/post-mortem/02-clean.R
revdep/post-mortem/03-analyze.R
revdep/post-mortem/04-review.R
revdep/post-mortem/05-count.R
revdep/post-mortem/06-mail.R
revdep/problem-analyze.R
tests/testthat.R
tests/testthat/helper-api.R
tests/testthat/helper-data.R
tests/testthat/helper-encoding.R
tests/testthat/helper-error.R
tests/testthat/helper-expectations.R
tests/testthat/helper-output.R
tests/testthat/helper-rstudio.R
tests/testthat/helper-type-sum.R
tests/testthat/helper-unknown-rows.R
tests/testthat/helper-zzz.R
tests/testthat/test-add.R
tests/testthat/test-as_tibble.R
tests/testthat/test-class-tbl_df.R
tests/testthat/test-enframe.R
tests/testthat/test-error.R
tests/testthat/test-glimpse.R
tests/testthat/test-has-name.R
tests/testthat/test-lst.R
tests/testthat/test-matrix.R
tests/testthat/test-msg.R
tests/testthat/test-names.R
tests/testthat/test-new.R
tests/testthat/test-options.R
tests/testthat/test-print.R
tests/testthat/test-rownames.R
tests/testthat/test-str.R
tests/testthat/test-string-to-indices.R
tests/testthat/test-subsetting-matrix.R
tests/testthat/test-subsetting.R
tests/testthat/test-tibble.R
tests/testthat/test-tidy_names.R
tests/testthat/test-tribble.R
tests/testthat/test-type_sum.R
tests/testthat/test-utils-msg-format.R
tests/testthat/test-utils-tick.R
tests/testthat/test-utils.R
tests/testthat/test-zzz-add.R
tests/testthat/test-zzz-data-frame.R
tests/testthat/test-zzz-enframe.R
tests/testthat/test-zzz-glimpse.R
tests/testthat/test-zzz-has-name.R
tests/testthat/test-zzz-lst.R
tests/testthat/test-zzz-matrix.R
tests/testthat/test-zzz-msg-format.R
tests/testthat/test-zzz-msg.R
tests/testthat/test-zzz-name-repair.R
tests/testthat/test-zzz-options.R
tests/testthat/test-zzz-rownames.R
tests/testthat/test-zzz-string-to-indices.R
tests/testthat/test-zzz-syntactic-names.R
tests/testthat/test-zzz-tbl-df.R
tests/testthat/test-zzz-tidy_names.R
tests/testthat/test-zzz-tribble.R
tests/testthat/test-zzz-trunc-mat.R
tests/testthat/test-zzz-type_sum.R
tic.R

C:
src/attributes.c
src/coerce.c
src/init.c
src/matrixToDataFrame.c
src/tibble.h

Rebol:
tests/testthat/test-tbl_sum.R

[~/t/t/tibble master]$
```

As you can see, not a single file from the `man/` directory has been included when calculating the repo language stats and the repo owner has done nothing to force this as can be seen from the lack of linguist attributes in their `.gitattributes`. 

The same will apply for your private repo too.

**Comment by K-Maehashi** [comment]
Got it. I was mixing stats and search results. Thanks for the detailed response!
