### ISSUE TITLE
Implementing Vugu

### ISSUE THREAD

**Issue by hugolgst** [github/linguist#4872]
You should add the support of [Vugu](https://github.com/vugu/vugu)

**Comment by lildude** [comment]
It looks like Vugu is a library written in Go and not a unique programming language so should be classified as Go and not as it's own language.

**Comment by hugolgst** [comment]
Vugu is inspired from VueJS and on GitHub, VueJS is classified as its one language.

**Comment by lildude** [comment]
Ah ok. So it's a markup language as opposed to a programming language.

As Linguist relies upon community contributions to address such requests, we'd welcome a PR that adds support or attributes the files to an already defined language, assuming it meets the minimum usage requirements as detailed in CONTRIBUTING.md.
