### ISSUE TITLE
dotenv syntax highlighting support

### ISSUE THREAD

**Issue by probablykasper** [github/linguist#4873]
Feature request to add syntax highlighting support for `.env` files. This was discussed in #3717 in 2017, but seems to have been closed without reason.

The `.env` syntax is used to define environment variables, and it's very commonly used with Node.js, Docker and probably others.

Although `.env` is often used for passwords, it's also commonly used for general config files which are fine to commit. Some repos have a private `.env` file and one that is committed - For example Vue and React use `.env` and `.env.local`. In addition to that, some repos have `.env-sample`, `.env.example`, or a code block in `README.md`, to show how private `.env` files should look.

References:
- [package.json](https://github.com/mikestead/vscode-dotenv/blob/master/package.json) of the VSCode dotenv extension which lists all the `.env` file extensions it supports.
- [dotenv](https://www.npmjs.com/package/dotenv) npm package

**Comment by lildude** [comment]
As Linguist relies upon community contributions to address such requests, we'd welcome a PR that adds support or attributes the files to an already defined language.

**Comment by probablykasper** [comment]
Seems fair to keep this open as dotenv is a common syntax

**Comment by smola** [comment]
We might want to classify these as `Shell` and get proper syntax highlighting. As far as I know, `.env` is kind of inspired on shell configuration files and sometimes will even contain full sh/bash syntax.

You can find many real world examples of `.env` and `*.env` files which are predominantly shell scripts:
- https://github.com/shri314/google-api-client/blob/0433d7ac86d7ff7b263718105359d0d58f17fbe1/.env
- https://github.com/nixztez/DA524G/blob/020e0e77b445027fc21b05c759969fd364b8b115/vendor/m1/env/tests/mocks/variables.env
- https://github.com/Macnica-DHW/quartus_scripts/blob/dc7c72d3cd5e68aece9f90bb79e636cd189fbe20/altera.env
- https://github.com/davidljung/opensim/blob/265059a906c118405ee0c790bfbdf4d84bc1c19d/opensim/linux.env

Even the usual usage with just `key=value` and `# comments` is a subset of POSIX sh syntax.

**Comment by probablykasper** [comment]
@smola I think it would be best to keep dotenv separated from shell syntax.

The .env files with shell scripts you linked use hashbangs like `#!/bin/bash`. Is it possible for linguist to detect highlighting from that, and otherwise use dotenv syntax?

For reference, the dotenv npm package lists it's [syntax rules](https://www.npmjs.com/package/dotenv#rules), except variable expansion which is added using the [dotenv-expand](https://www.npmjs.com/package/dotenv#rules) package.

**Comment by smola** [comment]
@probablycorey Please, see the description of this PR: https://github.com/github/linguist/pull/4922

dotenv is not something new from the Node.js world. It's a convention to somewhat standarize a subset of shell script syntax to allow parsing from different languages. As far as I can tell, all dotenv variants (there are many, supporting different syntax) are strict subsets of Bash. So any highlighter supporting Bash scripts should work with all of them.

Also, the syntax supported by the Node package you are linking is far more limited than the syntax supported by the Ruby package (https://github.com/bkeepers/dotenv), the PHP package, etc. If we supported npm's dotenv syntax only, it would be broken with Ruby's dotenv syntax. But AFAIK shell syntax will work with all of them.

**Comment by smola** [comment]
Well, actually this syntax from the npm package is not valid Bash: `JSON={"foo": "bar"}`...

**Comment by probablykasper** [comment]
@smola Ah got it, didn't realize there are variants from the npm package's implementation. Makes sense to use shell syntax in that case

**Comment by smola** [comment]
Bump, not stale, there is an active PR.
