### ISSUE TITLE
Possible dependency to add to usage/installation: dylib

### ISSUE THREAD

**Issue by jakewilliami** [github/linguist#4879]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

I run `github-linguist --breakdown` and I get the following.  I have tried searching for the dependency `dylib` but cannot find it on gems.  I have previously had github-linguist working, and have not changed my system, but that was some months ago probably.  I am using OS X.

```
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Library/Ruby/Gems/2.3.0/gems/charlock_holmes-0.7.6/lib/charlock_holmes/charlock_holmes.bundle, 0x0009): dependent dylib '/usr/local/opt/icu4c/lib/libicudata.64.dylib' not found for '/Library/Ruby/Gems/2.3.0/gems/charlock_holmes-0.7.6/lib/charlock_holmes/charlock_holmes.bundle' - /Library/Ruby/Gems/2.3.0/gems/charlock_holmes-0.7.6/lib/charlock_holmes/charlock_holmes.bundle (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/charlock_holmes-0.7.6/lib/charlock_holmes.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/github-linguist-7.9.0/lib/linguist/blob_helper.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/github-linguist-7.9.0/lib/linguist.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/github-linguist-7.9.0/bin/github-linguist:5:in `<top (required)>'
	from /usr/local/bin/github-linguist:22:in `load'
	from /usr/local/bin/github-linguist:22:in `<main>'
```

### URL of the affected repository:
E.g., https://github.com/garrylachman/covid19-cli
though it works for all repos I try it on

### Last modified on:
See above: cannot specify

### Expected language:
See above: cannot specify

### Detected language:
Error

**Comment by Alhadis** [comment]
`dylib` means "dynamic library". Going by this:

	dependent dylib '/usr/local/opt/icu4c/lib/libicudata.64.dylib' not found

... it seems you don't have `libicu` installed. Run `brew install icu4c` and see if the error persists.

**Comment by jakewilliami** [comment]
> Run `brew install icu4c` and see if the error persists.

I have `icu4c` installed already.

**Comment by lildude** [comment]
Looks like you've run `brew upgrade` which has upgraded your version of `icu4c`. I hit this problem every time I update.

This package has the annoying "feature" of including the version number in the filename (`64` in this case) which breaks anything that is compiled against that library, which in this case is charlock_holmes.

You'll find you're probably on `65` or `66` now.  I've got `66` though I've not updated in a while because of this precise issue.

The quick hack is to symlink `/usr/local/opt/icu4c/lib/libicudata.64.dylib` to the version you have installed, eg `libicudata.66.1.dylib`. The fix is to reinstall the charlock_holmes gem which will force it to be recompiled against the newer library.

**Comment by jakewilliami** [comment]
@lildude thanks for this.  This is exactly the error I had.

I'll just rewrite the steps for the quick hack you mentioned more explicitly before closing this.  This is for those (like me) who mightn't immediately know how to do this.

1. Find which version of `icu4c` you have installed.  There might be an easier way to do this, but I ran `brew info icu4c | grep Cellar | awk -F'[/ ]' '{print $6}'`.  My output, for example, is `67.1`.  
2. Find where your version of `icu4c` is installed (once again, probably an easier way to find this): `brew info icu4c | grep Cellar | awk -F' ' '{print $1}'`.  My output is, for example, `/usr/local/Cellar/icu4c/67.1`.
2. Create the symlink: `ln -s /usr/local/opt/icu4c/lib/libicudata.64.dylib /usr/local/Cellar/icu4c/67.1`.

Thank you again @lildude!  I've had a few issues with this gem (which thankfully others have had too: [[1]](https://github.com/github/linguist/issues/4484) [[2]](https://github.com/github/linguist/issues/4449)) and you've been very active and helpful on those as well.  We all appreciate you!

**Comment by Nakilon** [comment]
```bash
gem pristine charlock_holmes
```
