### ISSUE TITLE
About poetry.lock

### ISSUE THREAD

**Issue by retnikt** [github/linguist#4882]
`poetry.lock` files are misclassified.

## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

`poetry.lock` files, which contain dependency-pinning information about dependencies managed using [Poetry](https://python-poetry.org), are misclassified. They are TOML, and are also generated automatically by Poetry so they should be excluded from diffs.

### Expected language:
Generated - TOML

### Detected language:
Plain text

**Comment by lildude** [comment]
Linguist is a community maintained project and we'd welcome a pull request.
