### ISSUE TITLE
Next Linguist deployment?

### ISSUE THREAD

**Issue by nishtahir** [github/linguist#4890]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

As far as I can tell, it looks like the last Linguist deployment was in March with [v7.9.0](https://github.com/github/linguist/releases/tag/v7.9.0). It looks like there have been a lot of changes merged as well as changes to Grammars. It would be nice to get an ETA on the next deployment.

### URL of the affected repository:
N/A

### Last modified on:

N/A

### Expected language:

N/A

### Detected language:

N/A

**Comment by lildude** [comment]
I'm aiming to do it this week. I started last week with the opening of https://github.com/github/linguist/pull/4881 but have hit problems with local testing unrelated to Linguist.

I'm going to close this issue in favour of that PR.
