### ISSUE TITLE
Mustache misclassified as "HTML+Django"

### ISSUE THREAD

**Issue by yourpropertyexpert** [github/linguist#4899]
## Preliminary Steps

Please confirm you have...
- [X] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works)
- [X] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [X] considered implementing an [override](https://github.com/github/linguist#overrides),
- [X] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

`.mustache` templates are classified as "markup / HTML+Django" in `languages.yml`

This seems anomalous, given that related templating language suffixes like `.twig` and `.latte` are classified (correctly) as their own types of markup. 

## Proposed Solution

Create a new template section for Mustache (modelled on `.latte`) and associate the `.mustache` extension with that.

If it's as simple as that, let me know, and I'll do that and create a pull request :-) My understanding of linguist is too poor to let me assume that's it.

**Comment by lildude** [comment]
> If it's as simple as that, let me know, and I'l do that and create a pull request

Yup, that's pretty much it. See the CONTRIBUTING.md for requirements and instructions.

**Comment by yourpropertyexpert** [comment]
> > If it's as simple as that, let me know, and I'l do that and create a pull request
> 
> Yup, that's pretty much it. See the CONTRIBUTING.md for requirements and instructions.

Thanks.

It's on the to-do list. Hopefully this week, but no promises.

**Comment by yourpropertyexpert** [comment]
> > If it's as simple as that, let me know, and I'l do that and create a pull request
> 
> Yup, that's pretty much it. See the CONTRIBUTING.md for requirements and instructions.

OK - that's submitted as a pull request.

The delay was basically to do with the MacOS installation issues logged separately as [https://github.com/github/linguist/issues/4908](issue 4908).

I hope I've marked it up correctly.

The sample files are from a private repo from a company I run, but I'm happy to licence them to linguist under whatever licence makes life easiest for you guys :-) [And, yes, I warrant to you that I have the legal authority to do so.]

**Comment by lildude** [comment]
https://github.com/github/linguist/pull/4915 has been merged. Closing.
