### ISSUE TITLE
Some Perl files are misclassified as Raku

### ISSUE THREAD

**Issue by softmoth** [github/linguist#4902]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Many Perl files are being misidentified as Raku. I don't see any examples where the heuristics patterns for `perl5` and `perl6` apply, so I suspect this is due to the Bayesian training, if I understand Linguist correctly.

One partial fix might be to add a few more terms to the `perl5` heuristic, like
- `/^use constant/`: Raku constants don't have `use`
- `/^package [^;]+;/`: Raku package declaration has the `unit` prefix or an opening `{` brace

### URL of the affected repository:

I checked the first 10 pages of results from this search, and all of them should be Perl instead:
https://github.com/search?q=extension%3A.pm+language%3ARaku+%27use%27+-filename%3AConstant.pm&type=Code

#### Explanation of search terms
- `extension:.pm` is probably the most common one associated with both Raku and Perl
- `use` is just a very common keyword in Perl modules, to satisfy the Github web search tool's requirement for code searching
- `-filename:Constant.pm` is to weed out `*/Archive/Tar/Constant.pm`, which was flooding the search results because it is in so many repositories. It, too, is a Perl file.

### Last modified on:

Not applicable, it is many repositories.

### Expected language:

Perl (perl5)

### Detected language:

Raku (perl6)

**Comment by lildude** [comment]
> One partial fix might be to add a few more terms to the `perl5` heuristic, like
> 
>     * `/^use constant/`: Raku constants don't have `use`
> 
>     * `/^package [^;]+;/`: Raku package declaration has the `unit` prefix or an opening `{` brace

Linguist is a community maintained project, so if you're confident this will help, please feel free to submit a pull request.

**Comment by docwhat** [comment]
I just ran into this with v7.12.2; it is still an issue.

The [given search](https://github.com/search?q=extension%3A.pm+language%3ARaku+%27use%27+-filename%3AConstant.pm&type=Code) is still incorrectly showing Perl scripts as Raku.

**Comment by lildude** [comment]
> I just ran into this with v7.12.2; it is still an issue.

Yes, this is quite possible and likely because repos are only analysed when changes are pushed to them. GitHub does _not_ reanalyse every repo every time we update Linguist as this would be incredibly resource intensive for little return. Any file still showing Raku probably hasn't been touched since the change was deployed on GitHub.

**Comment by merrilymeredith** [comment]
Adding to this that the Raku detection is very... loose?  It looks like it classifies a `.pm` file as Raku if a line begins with `module` or `class` near the top, and that's inclusive of documentation text.  So a lot of Perl files have hard-wrapped pod:

```perl
=head2 DESCRIPTION

The ultimate power tool for your programming needs!  Add this to your
class and all your problems will disappear!

=cut
```

And I think the word "class" causes the file to be classified as Raku.

**Comment by lildude** [comment]
> Adding to this that the Raku detection is very... loose?

@merrilymeredith it certainly is 😁 The heuristics are the next step to distinguishing each language for the `.pm` after the extension itself:

https://github.com/github/linguist/blob/e2f638d17598e84f6f91c2d03c2f3e27f22a2163/lib/linguist/heuristics.yml#L410-L417

https://github.com/github/linguist/blob/e2f638d17598e84f6f91c2d03c2f3e27f22a2163/lib/linguist/heuristics.yml#L651-L652

And they apply to the first bytes of the file:

https://github.com/github/linguist/blob/e2f638d17598e84f6f91c2d03c2f3e27f22a2163/lib/linguist/heuristics.rb#L6

If Linguist still can't determine the language, it falls through to the classifier which makes a guess based on the samples Linguist has.

Please feel free to submit a PR to tighten things up... the heuristic is be the best place to start.

**Comment by merrilymeredith** [comment]
Someone more familiar with Raku should do that, I'm only noting how broad the false positives are and possibly why.  The Mojolicious project [used `.gitattributes` to force their files to Perl](https://github.com/mojolicious/mojo/blob/main/.gitattributes) because this happened so often.

**Comment by softmoth** [comment]
I'd recommend removing Raku entirely, and force the Raku community to deal with this properly if they want Linguist to recognize the language. At the moment it's providing many more false identifications than correct ones, and this has been unaddressed for years.

**Comment by softmoth** [comment]
Besides, the '.pm' extension for Raku has been deprecated now, so it is only old Raku code which would possibly be affected by removing it.
