### ISSUE TITLE
Feedback: New free language colour picker

### ISSUE THREAD

**Issue by lildude** [github/linguist#4903]
For a very long time now, picking a free colour has been a right pain in the 🍑 and I've been mulling various methods of easing this in one form or another.

Comments yesterday in https://github.com/github/linguist/pull/4900 and https://github.com/github/linguist/pull/4894 and a bit of free time on my hands renewed my interest, so I dug into various different methods, and finally came up with a simple HTML web page and a little bit of Javascript (⚠️ my Javascript knowledge is terrible) and built: [GitHub Linguist Free Colour Picker](https://lildude.github.io/linguist-free-colours/).

Use your cursor or enter the hex manually, and it'll highlight the box at the bottom to show you how it'll look and also validate if the colour is free or not.  

For example, `#fdff3c` isn't available:

![Screenshot 2020-06-26 at 17 41 44](https://user-images.githubusercontent.com/627280/85880757-76110c80-b7d4-11ea-8a38-4b7642fb5e92.png)

... but `#ce00cd` is:

![Screenshot 2020-06-26 at 17 41 56](https://user-images.githubusercontent.com/627280/85880769-7dd0b100-b7d4-11ea-96b7-879b55d1c44a.png)

Have a tinker with it, lemme know what you think, and feel free to open issues and submit PRs in the repo https://github.com/lildude/linguist-free-colours

**Comment by pchaigno** [comment]
This is awesome! I love how the blue is completely saturated...

How hard do you think it'd be to grey, make black, or make white areas that are unavailable? I could try and implement that in a couple weeks (when I'll have more time) if it sounds like something that would be possible.

**Comment by lildude** [comment]
> How hard do you think it'd be to grey, make black, or make white areas that are unavailable?

Oh it's possible, just incredibly time consuming as you'd need to iterate over every colour and perform the check in order to determine if the colour is free or not.  This is the approach taken in https://github.com/PMunch/colourfinder and the one I initially started with, albeit in Ruby and in a slightly different form, in this project but found it too time consuming and would require maintenance and some form of state retention and updating as the used colours change.  The current approach relies solely on the `languages.yml` file to remain up-to-date as the colour check happens on the fly.

If you've got an idea of how to do this efficiently, go for it.

**Comment by Alhadis** [comment]
I like how GitHub's designers have managed to redesign the entire website, yet still haven't reached a consensus as to whether or not colour proximity is even relevant anymore... **#priorities**

> Oh it's possible, just incredibly time consuming as you'd need to iterate over every colour and perform the check in order to determine if the colour is free or not

I recommend generating a list of unavailable colours ahead-of-time, and configuring a webhook to regenerate the list each time a change is pushed to Linguist (I'm assuming that's possible using GitHub Actions, or what-have-you 😉). The list needn't be anything fancier than a binary file containing raw RGB values; you'd load it using something like:

~~~js
const unavailableColours = new Set();
fetch("https://lildude.github.io/linguist-free-colours/unavailable")
	.then(response => response.arrayBuffer())
	.then(fileData => {
		fileData = new Uint8Array(fileData);
		for(let i = 0; i < fileData.length;
			unavailableColours.add(
				fileData[i++] << 16 |
				fileData[i++] << 8  |
				fileData[i++]
			));
	});
~~~

**Comment by pchaigno** [comment]
@lildude I think this can be closed?

**Comment by Alhadis** [comment]
Awh, but I was just about to offer feedback. 😭

**Comment by lildude** [comment]
You still can 😁

**Comment by Alhadis** [comment]
My feedback is that the colour proximity requirement needs to leave the hall. 😁
