### ISSUE TITLE
Linguist doesn't accurately count C files vs Python files

### ISSUE THREAD

**Issue by ShivKushwah** [github/linguist#4906]
## Preliminary Steps

Please confirm you have...
- [ ] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [ ] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [ ] considered implementing an [override](https://github.com/github/linguist#overrides),
- [ ] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

Confirmed.

## Problem Description

In my PSec repo, it says that Python makes up 73% of total files. My repo is majority C/C++ files, and this was not an issue previous to me adding 6 new Python files to the repo recently. This bug is especially strange because when I click Python under the Languages tab on the repo, it actually correctly shows that C is the most common language type (30 files) while Python is one of the least common files (7 files). Any ideas about this discrepancy?

### URL of the affected repository:
https://github.com/ShivKushwah/PSec

### Last modified on:
2020-06-26

### Expected language:
C

### Detected language:
Python

**Comment by pchaigno** [comment]
Please read [How Linguist Works](https://github.com/github/linguist#how-linguist-works).

**Comment by ShivKushwah** [comment]
Hi, I have read that documentation before posting and wasn't able to see how that affected my repository as I don't have any explicit language overrides. In addition, the language tab was correctly showing the the language distribution (primarily C/C++) before I committed the Python files. One thing to note is that I was unable to test linguist locally (on MacOS) since I was running into make errors

`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin18/ruby/config.h:365:31: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
#define RUBY_ARCH "universal-"RUBY_PLATFORM_OS`

**Comment by pchaigno** [comment]
> The percentages are calculated based on the bytes of code for each language as reported by the List Languages API.

**Comment by ShivKushwah** [comment]
@pchaigno  I'm still not entirely sure how that applies to me? 
In my repo, I have ~30 C files with thousands of lines of code each while I have ~7 Python files with less than a hundred lines.
Shouldn't the bytes of C code in this case be much more than the bytes of Python code?

<img width="241" alt="Screen Shot 2020-06-27 at 11 46 28 AM" src="https://user-images.githubusercontent.com/13080000/85929736-18300380-b86c-11ea-8b05-a165e50a53c0.png">

<img width="317" alt="Screen Shot 2020-06-27 at 11 48 43 AM" src="https://user-images.githubusercontent.com/13080000/85929749-2ed65a80-b86c-11ea-894e-d166f7b08d55.png">

**Comment by lildude** [comment]
> In my repo, I have ~30 C files with thousands of lines of code each while I have ~7 Python files with less than a hundred lines.
> Shouldn't the bytes of C code in this case be much more than the bytes of Python code?

Indeed you do, but you're looking at two different things. The top image is showing you the search results of your repo. The second is showing the language breakdown. Linguist is only responsible for the latter and has no influence on the former other than to identify the language.

Now note how only two languages are listed there: Python and CMake.  That's because only these files are being counted:

```console
$ github-linguist . --breakdown
80.39%  Python
19.61%  CMake

CMake:
CMakeLists.txt
HelperScripts/CMakeLists.txt
HelperScripts/ConfigSGX.cmake
HelperScripts/FindSGXSDK.cmake
HelperScripts/Init.cmake

Python:
PerformanceMetricsScript/ApplicationLevelPerformanceMetricsParsing.py
PerformanceMetricsScript/ApplicationLevelPerformanceMetricsScript.py
PerformanceMetricsScript/PerformanceMetricParserDistributedHost1.py
PerformanceMetricsScript/PerformanceMetricParserDistributedHost2.py
PerformanceMetricsScript/PerformanceMetricParserDistributedParsing.py
PerformanceMetricsScript/PerformanceMetricParserLocal.py
$
```

The bytes of code of Python is clearly more than those of CMake.

Why are only those files being counted? 

Because they're the only code files that do _not_ exist in the `Samples` directory. 

Why is this a problem? 

Because Linguist considers files under `Samples` as documentation: https://github.com/github/linguist/blob/9c8d6e7df8f50793d27d4adefadc3ec1c9945259/lib/linguist/documentation.yml#L32-L33

And what's the solution?

Implement an override to tell Linguist that everything in `Samples` is _not_ documentation.

With the override in place, you'll get this for the language breakdown:

```console
$ github-linguist .
53.85%  C
29.55%  C++
7.24%   Makefile
5.20%   OpenEdge ABL
2.41%   CMake
1.75%   Python
$
```

**Comment by ShivKushwah** [comment]
@lildude  THANK YOU SO MUCH!
I added "Samples/* linguist-documentation=false" to my .gitattributes file and everything works now.

Thanks again!
