### ISSUE TITLE
Installation script on MacOS fails on Macs with C++17

### ISSUE THREAD

**Issue by yourpropertyexpert** [github/linguist#4908]
## Preliminary Steps

Please confirm you have...
- [X] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [X] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [X] considered implementing an [override](https://github.com/github/linguist#overrides),
- [X] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

On MacOS with (all recent?) versions of xcode, the script/bootstrap fails because Charlock Holmes can't be installed.

This relates to a known issue with Charlock - [https://github.com/brianmario/charlock_holmes/issues/146](https://github.com/brianmario/charlock_holmes/issues/146 ) - namely that it relies on a deprecated setting in C++17.

The bootstrap script attempts to install Charlock 0.7.7 even if it's already there, so fails to get further.

To install Charlock  0.7.7 on a Mac you need to include the following options to the gem build

`--with-icu-dir=/usr/local/opt/icu4c --with-cxxflags='-Wno-reserved-user-defined-literal -std=c++11'`

... and I'm trying to work out how to add that to the bundle options :-)

**Comment by lildude** [comment]
My `~/.bundle/config` file contains:

```console
$ grep CHAR ~/.bundle/config
BUNDLE_BUILD__CHARLOCK_HOLMES: "--with-icu-dir=/usr/local/opt/icu4c --with-cxxflags=-std=c++11"
$
```

... which I would have set a long time ago, but probably used something like:

```
bundle config build.charlock_holmes --with-icu-dir /usr/local/opt/icu4c --with-cxxflags=-std=c++11
```

... so to get your flags, something like this might do the trick:

```
bundle config build.charlock_holmes --with-icu-dir /usr/local/opt/icu4c --with-cxxflags='-Wno-reserved-user-defined-literal -std=c++11'
```

**Comment by Epokhe** [comment]
@lildude trying your suggestion didn't work, here is the output
```
❯ bundler _1.17.3_
Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 13.0.1
Using public_suffix 4.0.5
Using addressable 2.7.0
Using bundler 1.17.3
Using byebug 11.1.3
Fetching charlock_holmes 0.7.7
Installing charlock_holmes 0.7.7 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/Users/epokhe/linguist/vendor/gems/ruby/2.6.0/gems/charlock_holmes-0.7.7/ext/charlock_holmes
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r
./siteconf20200702-75167-t4l8au.rb extconf.rb --with-icu-dir\ /usr/local/opt/icu4c\
--with-cxxflags\=-Wno-reserved-user-defined-literal\ -std\=c\+\+11
checking for -licui18n... yes
checking for unicode/ucnv.h... yes

...

In file included from
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby.h:33:
In file included from
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/ruby.h:24:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin19/ruby/config.h:413:31:
error: invalid suffix on literal; C++11 requires a space between literal and identifier
[-Wreserved-user-defined-literal]
#define RUBY_ARCH "universal-"RUBY_PLATFORM_OS
                              ^

/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin19/ruby/config.h:414:35:
error: invalid suffix on literal; C++11 requires a space between literal and identifier
[-Wreserved-user-defined-literal]
#define RUBY_PLATFORM "universal."RUBY_PLATFORM_CPU"-"RUBY_PLATFORM_OS
                                  ^

/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin19/ruby/config.h:414:55:
error: invalid suffix on literal; C++11 requires a space between literal and identifier
[-Wreserved-user-defined-literal]
#define RUBY_PLATFORM "universal."RUBY_PLATFORM_CPU"-"RUBY_PLATFORM_OS

...

2 warnings and 3 errors generated.
make: *** [transliterator.o] Error 1

make failed, exit code 2

Gem files will remain installed in
/Users/epokhe/linguist/vendor/gems/ruby/2.6.0/gems/charlock_holmes-0.7.7 for inspection.
Results logged to
/Users/epokhe/linguist/vendor/gems/ruby/2.6.0/extensions/universal-darwin-19/2.6.0/charlock_holmes-0.7.7/gem_make.out

An error occurred while installing charlock_holmes (0.7.7), and Bundler cannot continue.
Make sure that `gem install charlock_holmes -v '0.7.7' --source 'https://rubygems.org/'` succeeds
before bundling.

In Gemfile:
  github-linguist was resolved to 7.10.0, which depends on
    charlock_holmes
```

**Comment by lildude** [comment]
You got me stumped. Looks like the args are making it through though. Your best bet is to seek help from the upstream charlock_holmes repo. There seem to be quite a few issues like this.

**Comment by Epokhe** [comment]
I fixed line 414 manually and saved as sudo, that solved the problem 🤷‍♂️

**Comment by yourpropertyexpert** [comment]
> I fixed lines 413-414 in config.h manually and saved as sudo, that solved the problem 🤷‍♂️

I know I'd missing something obvious, but which config.h ?

**Comment by Epokhe** [comment]
Sorry for not being clear @yourpropertyexpert 
The errors I got points to a config.h file and line 413-414. The first one from the snippet above:
```
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin19/ruby/config.h:413:31:
error: invalid suffix on literal; C++11 requires a space between literal and identifier
```

For each line marked by the errors, I went there and put spaces in between literals and identifiers, changing them from this
```
#define RUBY_ARCH"universal-"RUBY_PLATFORM_OS
```

To this
```
#define RUBY_ARCH "universal-" RUBY_PLATFORM_OS
```

Hope that helps

**Comment by yourpropertyexpert** [comment]
It's not your fault... I really appreciate your patience.

I've been programming for 30+ years, but this is my first attempt at Ruby... and I found something like 4 different files called config.h in the repo :-)

**Comment by yourpropertyexpert** [comment]
I've updated the "Contributing" documentation, and made a PR - #4910 

Given it's a problem with an upstream dependency, I don't see a plausible way to fix it in this project (and it has been logged with them.)

But, I thought I could at least try to update the docs.

**Comment by oliviertassinari** [comment]
I did the same to fix the issue:

```diff
#define RUBY_PLATFORM_OS "darwin19"
-#define RUBY_ARCH"universal-"RUBY_PLATFORM_OS
-#define RUBY_PLATFORM"universal."RUBY_PLATFORM_CPU"-"RUBY_PLATFORM_OS
+#define RUBY_ARCH "universal-" RUBY_PLATFORM_OS
+#define RUBY_PLATFORM "universal." RUBY_PLATFORM_CPU "-" RUBY_PLATFORM_OS
#endif /* INCLUDE_RUBY_CONFIG_H */
```

**Comment by smola** [comment]
Bump, since there's an open PR.

**Comment by lildude** [comment]
Closing as we now recommend against using the macOS/XCode supplied version of Ruby in the docs.
