### ISSUE TITLE
Bug report: missidentifying SAGE programming language

### ISSUE THREAD

**Issue by hilder-vitor** [github/linguist#4909]
## Preliminary Steps

Please confirm you have...
- [ x ] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [ x ] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [ x ] considered implementing an [override](https://github.com/github/linguist#overrides),
- [ x ] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Hello,
in my repository named sage_lattice_examples, all the scripts are written in SAGE (https://www.sagemath.org/), which is a programming language that mathematicians and cryptographers use a lot, however, GitHub is reporting that they are written in Python. The menu on the right shows "Languages: Python 100%".

### URL of the affected repository:
https://github.com/hilder-vitor/sage_lattice_examples

### Last modified on:
2020-06-13

### Expected language:
 Sage 

### Detected language:
 Python

**Comment by lildude** [comment]
This is happening because Sage is grouped alongside Python:

https://github.com/github/linguist/blob/b24ff11d9cf60dd996156a718f83024c9436e5ea/lib/linguist/languages.yml#L4939-L4949

This has been the case since support was added for it over 9 years ago in https://github.com/github/linguist/pull/91 and to quote the original PR "Sage uses python for syntax" hence it has been grouped with Python.

**Comment by hilder-vitor** [comment]
Hello,
thank you for answering!

So, is this a design choice and it means that Sage will continue being classified as Python? Or would you be interested in separating them?

**Comment by lildude** [comment]
I know absolutely nothing about Sage, but if there's a good reason to break it out, and there's support for it, I don't see why not. Feel free to add this to the discussion in https://github.com/github/linguist/issues/4291

**Comment by hilder-vitor** [comment]
I have done so. I do not know what would be considered a "good reason", but I have at least talked a bit about the differences between them.  (:

Thank you again!

**Comment by pchaigno** [comment]
Closing in favor of #4291.
