### ISSUE TITLE
Question: How can I add my own stable programming language?

### ISSUE THREAD

**Issue by enty8080** [github/linguist#4917]
**Sorry for ignoring issue form, this is just a question**

@github

I have my own stable programming language named HEY here:
https://enty8080.github.io/hey

You can download it and check, this language stable and works well.

How can I add it to linguist with language_id and highlight?

**Thanks.**

**Comment by Alhadis** [comment]
The answers to your question are in the issue template which you didn't fill out.

**Comment by enty8080** [comment]
@Alhadis I will make a PR with support for my language.

**Comment by Alhadis** [comment]
Before you do so, please make an effort to read our [contribution guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md). In particular, note the part about real-world usage and what we require of new languages before we can support them.
