### ISSUE TITLE
Coding without jekyll

### ISSUE THREAD

**Issue by Insanyngame** [github/linguist#4945]
I just would want to know if there is a way to program without jekyll library.
I'm doing a project and I can't put a title and logo on the website ( https://insanyngame.github.io ) 's page like this image:
![image](https://user-images.githubusercontent.com/66750166/90345494-6d300080-dff7-11ea-88bd-8b351d1e9727.png)
but it gets:
![image](https://user-images.githubusercontent.com/66750166/90345522-a4061680-dff7-11ea-9e64-97ef1f3a8523.png)
 
thx! 
PS: I couldn't find it on google or other issue page, so sorry if this is the second (or more) time you are answering question like this...

**Comment by Alhadis** [comment]
Try asking at http://github.community/.

Closing this issue, as it isn't related to Linguist whatsoever.
