### ISSUE TITLE
TypeScript Declaration files considered vendored

### ISSUE THREAD

**Issue by eps1lon** [github/linguist#4956]
Declaration files that are checked in are usually<sup>1</sup> manually authored and should not be considered vendored.

## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

TypeScript declaration files are considered vendored:

https://github.com/github/linguist/blob/v7.10.0/lib/linguist/vendor.yml#L176-L177

### URL of the affected repository:

https://github.com/mui-org/material-ui

Fixing this manually with https://github.com/mui-org/material-ui/pull/22282

### Last modified on:

N/A

### Expected language:

TypeScript

### Detected language:

vendored

<sup>1</sup> Every repository I worked on manually authors declaration files that are checked in (DefinitelyTyped, jss, `@testing-library/*`, material-ui etc). So there may be selection bias at work.

**Comment by lildude** [comment]
I can't really comment on what the correct behaviour is as I know diddly about TypeScript but what I can say is this behaviour has been in place for over 7 years (intro'd in https://github.com/github/linguist/pull/896) and this is the first time it has come up 😁.

I suspect the original PR was written from the point of view of the consumer and not author of these files.

Is it possible these files will consistently fall into another vendored path (eg always `bower_components` which is already vendored) for consumers of these files that won't be the case for authors? I'm thinking that if this is the case, we could probably remove the line in question and fallback to another vendored path to hide this from consumers.

**Comment by Alhadis** [comment]
I'd tentatively leave it as vendored. I also write TypeScript declarations by hand (except when [brutal abuse of JSDoc](https://github.com/Alhadis/Utils/blob/master/index.d.ts) is more fun), and all my projects are vanilla JavaScript — the `.d.ts` files are more of a courtesy to TypeScript programmers. Therefore, I (and presumably other devs) consider them ancillary at best. In other words, for a repository that's 100% JavaScript, it'd be misleading to report a small percentage of the codebase as written in TypeScript.

Nonetheless, it's a grey area that many will disagree on.... hence why we have overrides. :wink:
