### ISSUE TITLE
Review most popular languages in lib/linguist/popular.yml

### ISSUE THREAD

**Issue by sheerun** [github/linguist#4966]
[This file](https://github.com/github/linguist/blob/master/lib/linguist/popular.yml) haven't been update in at least two years and new languages are now popular https://madnight.github.io/githut/#/pull_requests/2020/2 shows that we are missing among others:

- Rust
- Dart
- Kotlin
- Groovy
- Elixir
- PowerShell
- Emacs Lisp
- OCaml
- Erlang

Also it seems some languages are no longer popular, like:

- ActionScript
- CoffeeScript

**Comment by lildude** [comment]
🤔 I'm not sure that file is even used anymore. I'd need to dig through the GitHub.com source code to be sure.

**Comment by sheerun** [comment]
@lildude For sure in "Written in this language" advanced search option

**Comment by lildude** [comment]
Yup. Looks like it is definitely still used. I'll update the list.
