### ISSUE TITLE
FreeBasic repo misclassified as VBA

### ISSUE THREAD

**Issue by XusinboyBekchanov** [github/linguist#4997]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

If the code contains #include or common or the extension is .bas or .bi (additionally user-defined .inc, .frm) then this language should be defined as FreeBasic.

### URL of the affected repository:
https://github.com/XusinboyBekchanov/VisualFBEditor

### Last modified on:
2020-09-06

### Expected language:
FreeBasic

### Detected language:
VBA

**Comment by smola** [comment]
@XusinboyBekchanov Maybe you can contribute a pull request? See [CONTRIBUTING.md](https://github.com/github/linguist/blob/master/CONTRIBUTING.md). Regular expressions for disambiguations are added to [heuristics.yml](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.yml). [New samples](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language) would probably be needed too.

**Comment by XusinboyBekchanov** [comment]
I added pull request for languages.yml.

**Comment by XusinboyBekchanov** [comment]
https://github.com/github/linguist/pull/4998

**Comment by XusinboyBekchanov** [comment]
If you look at my repository, you can see that: FreeBasic 75.1%, VBA 17.8%, Rich Text Format 6.4%, Makefile 0.7%:
![image](https://user-images.githubusercontent.com/32607344/114654567-e9ecb900-9d03-11eb-89e8-e54b4aef1869.png)
If you click on one of them, this appears:
![image](https://user-images.githubusercontent.com/32607344/114654739-37692600-9d04-11eb-97f8-d77b8e68fe71.png)
Why does it show only Visual Basic.Net, but not FreeBasic and VBA?

**Comment by lildude** [comment]
@XusinboyBekchanov because of the bug in Search (not Linguist) as detailed in https://github.com/github/linguist/issues/5320

It's good to see your repo is now correctly showing FreeBasic so I'm going to close this issue.
