### ISSUE TITLE
Override language grouping in gitattributes

### ISSUE THREAD

**Issue by wopian** [github/linguist#5002]
Related to https://github.com/github/linguist/issues/4245, https://github.com/github/linguist/issues/4506 and https://github.com/github/linguist/issues/4593

## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

### The Known Problem

https://github.com/chrislgarry/Apollo-11 and https://github.com/virtualagc/virtualagc only have one main language in their repositories, Apollo Guidance Computer, which is one of many Assembly dialects and is grouped under Assembly, as it should be.

This unfortunately leads to the language listing on the repositories pointing to a page with zero search results for Assembly, as the files are instead listed under the AGC dialect.

This change in UI on GitHub's side happened over two years ago (prior issues from 2 years ago were closed hoping GitHub would fix this external problem) and languages part of a larger language group are still not included in search results as of mid 2020, so I doubt this will be fixed by GitHub any time soon, if at all.

### The Feature Request 

Would it be possible to offer a new override to manually ungroup a language so that end users can "fix" their "language bar to language search" UX for their own repositories? E,g:

```gitattributes
*.agc linguist-ungroup
*.agc linguist-ungroup-language
```

**Comment by Alhadis** [comment]
> Would it be possible to offer a new override to manually ungroup a language so that end users can "fix" their "language bar to language search" UX for their own repositories?

It's frustrating, I know, but it wouldn't be worth adding a feature to Linguist to solve a problem it has nothing to do with anyway.

> so I doubt this will be fixed by GitHub any time soon, if at all.

I hear ya. Try ~~spamming 'em with support tickets over and over, each year~~ [github.community](http://github.community/), which might grant more visibility to the issue.

Man, just imagine all the problems we could fix with PRs if GitHub was, uh, literally open-source. 😀

**Comment by wopian** [comment]
https://github.community/t/include-child-languages-in-language-search-results/152409
