### ISSUE TITLE
Detected language depends on file length or amount of data?

### ISSUE THREAD

**Issue by ib** [github/linguist#5012]
This seems arbitrary and ridiculous:

`#ifndef FOO_H
#define FOO_H

static const struct foo
{
  int foo1;
  int foo2;
  int foo3;
}
foos[] =
{
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
  { 0x0000, 0x0000, 0 },
};

#endif`

`foo.h: 44 lines (41 sloc)
  type:      Text
  mime type: text/plain
  language:  Objective-C`

and with 1 line of `{ 0x0000, 0x0000, 0 },` less the correct result:

`foo.h: 43 lines (40 sloc)
  type:      Text
  mime type: text/plain
  language:  C`

This should be fixed.

**Comment by smola** [comment]
Yes. Linguist has a set of heuristics to identify a language. When all heuristics fail, it falls back to a Bayesian classifier which performs poorly on short files, and in particular .h files.

There is an open discussion to improve this for C, C++ and Objective-C: https://github.com/github/linguist/issues/1626

**Comment by ib** [comment]
It actually seems to perform worse the longer the file is. The short file is recognized correctly.

I wonder why in case of doubt it is not C that is recognized, especially since there is not a single Objective-C keyword in the file. Why does Objective-C take precedence over C (which is the more likely)?

**Comment by smola** [comment]
@ib That's likely to be a problem with the Bayesian classifier, which is trained with a very small dataset. If Objective-C samples in linguist dataset have more `{` or `}` characters than C samples, that would make it classify as Objective-C if these characters are the majority token in the file. It's just a glitch in how the current classifier estimates probabilities, not an explicit design choice.

That's an area I'm working to improve right now, but there's no easy answer or silver bullet. As a workaround, if you want to fix classifications for your repositories, you can use `.gitattributes`: https://github.com/github/linguist#overrides

**Comment by ib** [comment]
@smola

> That's an area I'm working to improve right now

Any progress?
