### ISSUE TITLE
XML should be counted as a language used in the repo

### ISSUE THREAD

**Issue by mishraaditya595** [github/linguist#5016]
In a repository, under the language section, XML is not considered.

## Problem Description
XML-layout files play a significant role in Android projects. When layout is created in Java or Kotlin, it's counted, and when in XML, it is not considered. Maybe one could open a pull request with Android View XML (that way we could count those XML files only) as a new language to initiate discussion.

### Detected language: Nothing

**Comment by lildude** [comment]
This is expected as XML is and has always been considered data by Linguist. 

> Maybe one could open a pull request with Android View XML (that way we could count those XML files only) as a new language to initiate discussion.

I don't think we need to do this as I believe these files are really just plain old XML.  If you really want them to count in your language stats, you can force this by using the [`linguist-detectable`](https://github.com/github/linguist#detectable) override.
