### ISSUE TITLE
Add support for confuscript

### ISSUE THREAD

**Issue by Floffah** [github/linguist#5017]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
I would like my language [confuscript](https://github.com/floffah/confuscript) to be available for syntax highlighting.
It has grammar written in Nearley if that is helpful. I don't know enough ruby or go to be able to submit a pr for this.

### URL of the affected repository:
https://github.com/floffah/confuscript

### Expected language:

Confuscript
### Detected language:

plaintext

**Comment by lildude** [comment]
As per the CONTRIBUTING.md, we require wide usage of a language before adding support:

>  In most cases we prefer that each new file extension be in use in hundreds of repositories before supporting them in Linguist.

"hundreds or repositories" is accepted as over 200 unique user/repo repositories.

As your language is very new, and from the comment on the repo, appears incomplete, it probably doesn't have wide-enough real-world usage for inclusion right now. Accordingly, I recommend we close this issue and you track usage on GitHub.com by searching for files with your language's extension and keywords. When usage is sufficient for inclusion, you can open a PR to add support (very little, if any Ruby knowledge is required for most additions) or open a new issue.

**Comment by Floffah** [comment]
Oh okay thank you
