### ISSUE TITLE
Go file incorrectly classified as generated

### ISSUE THREAD

**Issue by myitcv** [github/linguist#5026]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

The following file is incorrectly classified as a generated `.go` file:

```
package config

import (
	"flag"
	"os"
	"regexp"

	"github.com/gorilla/securecookie"

	"golang.org/x/oauth2"
)

//go:generate go run github.com/jteeuwen/go-bindata/go-bindata -pkg config -o gen_bindata.go -prefix ../www/ ../www ../www/default ../www/assets ../www/assets/xterm ../www/assets/xterm/addons ../www/assets/xterm/addons/webLinks ../www/assets/xterm/addons/terminado ../www/assets/xterm/addons/fullscreen ../www/assets/xterm/addons/fit ../www/assets/xterm/addons/attach ../www/assets/xterm/addons/zmodem ../www/assets/xterm/addons/search ../www/k8s
//go:generate go run github.com/play-with-docker/play-with-docker/internal/addgenheader gen_bindata.go "Code generated by go-bindata."
//go:generate gofmt -w -s gen_bindata.go
```

This appears to be because the following check is used to detect generated Go files:

https://github.com/github/linguist/blob/8f05b41e03162e06c1b9820f552f0ffc4050ac7e/lib/linguist/generated.rb#L303-L308

Currently, per [this agreed comment](https://golang.org/s/generatedcode), generated Go files are identified by those which contain a line anywhere in the file that matches the following regular expression:

```
^// Code generated .* DO NOT EDIT\.$
```

Note the difference to the implementation in this repository.

For completeness, https://github.com/golang/go/issues/41196 has just been accepted that amends this slightly: 

> Specifically, the comment must appear before the first non-blank line, non-comment text. `/* */` comments before the `// Code generated ...` comment would be allowed.

However I imagine there will be a lag before all code generators update to this standard.

### URL of the affected repository:

https://github.com/play-with-docker/play-with-docker/blob/de3047d573c1e295fcf5d8a4a6b59252c57de508/config/config.go

### Last modified on:

28 Sep 2020 16:24 BST

### Expected language:

Go

### Detected language:

Go

**Comment by lildude** [comment]
If you've got the bandwidth, we'd appreciate a PR that updates the current usage and adds support for the new usage.

**Comment by myitcv** [comment]
> If you've got the bandwidth

Unfortunately not right now.



> adds support for the new usage

I think some judgement call needs to be made as to when to switch over to this new approach. I'd even suggest using some real numbers by scanning GitHub repos to work out how many files/projects etc would be impact by the switch from current implementation to "correct" Go approach, and then "correct" Go approach to "new" Go approach (assuming this is how you would phase it). The numbers might even support jumping straight to the "new" Go approach.

**Comment by smola** [comment]
I think supporting the "old" Go approach is enough. Linguist needs to work on real code, which includes a lot of old code. `^// Code generated .* DO NOT EDIT\.$` would work both for the current and amended version, right?

**Comment by myitcv** [comment]
> would work both for the current and amended version, right?

Correct, it would. 

But at some point we should move to the new definition. Otherwise, "bad" code generators will never get fixed. Fixing "bad" code generators has a derivative benefit for other tools which rely on things be correctly "marked" too.

But I agree, there needs to be an evidence-based judgement call made on when to switch.

**Comment by smola** [comment]
> @myitcv  Otherwise, "bad" code generators will never get fixed.

Linguist supports a lot of historic constructs. Otherwise, it would stop detecting old files. Some users run linguist with all files in git history. Actually that was my first linguist use case: detecting language of all files in all GitHub repositories for every commit. I think there are still a few large-scale users doing exactly this.

**Comment by myitcv** [comment]
> Linguist supports a lot of historic constructs

Then perhaps there needs to be a `-legacy` flag or equivalent? If GitHub detects a file as "generated" but others tools do not (because they have moved to the new definition) then that also raises a question for users.

To give some context, 0.825% is presented in https://github.com/golang/go/issues/41196 as an indication of how many files need to be updated, so we're not talking big problems here.
