### ISSUE TITLE
Files are detected under linguist-detectable=false folder

### ISSUE THREAD

**Issue by nrlquaker** [github/linguist#5031]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

I've set `linguist-detectable=false` to a folder in `.gitattributes`, but I can see files from that folder in the language stats.

### URL of the affected repository:
https://github.com/nrlquaker/winbox-mac/

### Last modified on:
2020-09-04

**Comment by lildude** [comment]
Your override is as follows:

```
Winbox-mac.app/Contents/Resources/wine/* linguist-detectable=false
```

The `*` limits the scope to only files within that directory because (taken from the [.gitignore docs](https://www.git-scm.com/docs/gitignore)):

> An asterisk "*" matches anything except a slash. The character "?" matches any one character except "/".

A little further down you'll see your solution:

> A trailing "/**" matches everything inside. For example, "abc/**" matches all files inside directory "abc", relative to the location of the .gitignore file, with infinite depth.

**Comment by nrlquaker** [comment]
Thanks, @lildude. Tried locally and the problem is fixed.

**Comment by nrlquaker** [comment]
Event its ok when I run `github-linguist --breakdown` locally, on GitHub report still haven't changed. Last commit was 4 days ago.

**Comment by lildude** [comment]
What make you think GitHub isn't acknowledging it?

**Comment by nrlquaker** [comment]
Because when I press on `Shell` languages I see [files](https://github.com/nrlquaker/winbox-mac/search?l=shell) from `linguist-detectable=false` folder.

**Comment by lildude** [comment]
That's expected 😁  What you're looking at are the search results (note the URL). These are completely independent of Linguist and deliberately do _not_ acknowledge the Linguist overrides in `.gitattributes` because if it did, you'd never be able to search for your files.

I can assure you though that Linguist is definitely only counting the files you expect it to, ie it is only counting these three files:

- Winbox-mac.app/Contents/MacOS/winbox-mac
- scripts/bump_version
- scripts/release

**Comment by nrlquaker** [comment]
Oh. I got it. Thanks for clarification.
