### ISSUE TITLE
Multiple language support

### ISSUE THREAD

**Issue by sdegutis** [github/linguist#5032]
I'm coming here from finding out that GitHub comments [use Linguist](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks) both for figuring out what language is used in a code block, and for determining what syntax highlighter to use for it. But I think it would be handy to have a diff that shows both the code and diff highlighting. For example, as you go through [React tutorials](https://reactjs.org/docs/components-and-props.html), you see new lines highlighted. I'd like to "amend" some JS code, but mark up lines as being added/removed with regular diff syntax. To that end, as a simple proposal, I'm suggesting something like:

    ```js,diff
    a = {}
    - a.b = 123
    + a.b = 124
    ```

**Comment by Alhadis** [comment]
Your best bet is to [contact support](http://github.com/support) and submit a feature request, as this isn't something Linguist has any control over.

I recall some other sites supporting fenced diff-blocks using the syntax:

~~~markdown
```diff js
-	deleted();
+	added();
 	unchanged();
```
~~~

Which I'm sure every GitHub user would love to have — myself included. 😉

**Comment by sdegutis** [comment]
Cool thanks 👍
