### ISSUE TITLE
File Type Not Recognized Locally Even After Edit to languages.yml

### ISSUE THREAD

**Issue by dillonledoux** [github/linguist#5033]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

I am trying to add additional file types to the LabVIEW entry in the languages.yml file.  I have made the necessary changes in [my forked repo](https://github.com/dillonledoux/linguist/tree/add_LabVIEW_branch) and have run Linguist locally to test.  However, Linguist will not recognize ".vi" file types at all unless I place an override.  I used [this repo](https://github.com/monoDriveIO/monodrive-labview-client) and [this other repo](https://github.com/MakerHub/LINX) to test this function and the ".vi" file type is simply ignored. 

Can anyone provide further insight into why this may be happening before I submit the pull request to add the extensions? 

### Last modified on:

2020-09-30

### Expected language:

LabVIEW

### Detected language:

None

**Comment by lildude** [comment]
It's because you're attempting to identify/assign a language to a binary file. Linguist deliberately ignores binaries as they're not code and thus not readable with something like a text file viewer or a browser.  Your additions for non-binary files should however work as expected.

**Comment by dillonledoux** [comment]
That's what I was afraid of.  I guess the override will be the solution here.  Thank you for taking a look!
