### ISSUE TITLE
Skylines

### ISSUE THREAD

**Issue by muslim199** [github/linguist#5048]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

**Comment by muslim199** [comment]
Haha

**Comment by muslim199** [comment]
Haha

**Comment by Alhadis** [comment]
Enough with the spam. Keep it up, and you'll be [reported for abuse](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/reporting-abuse-or-spam).
