### ISSUE TITLE
Support for JSON snippets

### ISSUE THREAD

**Issue by konklone** [github/linguist#505]
I'd like to add support for a slight modification of the JSON lexer - that of JSON snippets, where surrounding braces or brackets are allowed to be missing.

This is a pattern I use in @sunlightlabs' API documentation, to document sections of response objects:
http://sunlightlabs.github.io/congress/legislators.html#fields/names

Right now, this is accomplished through a hack - in the original markdown documents, there are surrounding braces, but the content they surround is not indented. After documents are run through the syntax highlighter, any unindented JSON blocks inside braces get their braces removed. Without this hack, simply excluding the braces in the original code means the syntax highlighting for JSON doesn't trigger.

I've been poking through this repository, and @tmm1's pygments.rb, and the underlying pygments library, and I can't figure out how to begin doing the work myself. In what repo would I put this code, and what's the easiest way to go about it? Is there a way to "subclass" the existing JSON lexer and tweak the rules?

**Comment by benatkin** [comment]
The highlighting is apparently the same between JavaScript and JSON now. Way to go! So just use `js` instead of `json` if you don't want JSON validation.
