### ISSUE TITLE
Incorrectly Detecting Shell

### ISSUE THREAD

**Issue by LukeG294** [github/linguist#5057]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Incorrectly detecting 0.9% Shell on the below repo

### Expected language:
100% Python

### Detected language:
0.9% Shell

Thanks for your help, this isn't a huge issue.

**Comment by lildude** [comment]
> Incorrectly detecting 0.9% Shell on the below repo

Not quite 😁 Here's your shell file: https://github.com/brainbotdev/brainbot/blob/master/.env.example

It's a named file specifically assigned to Shell:

https://github.com/github/linguist/blob/65d078bab8a8bafc5c53614be5c3fec42c2897f0/lib/linguist/languages.yml#L5146-L5175

**Comment by LukeG294** [comment]
> > Incorrectly detecting 0.9% Shell on the below repo
> 
> Not quite 😁 Here's your shell file: https://github.com/brainbotdev/brainbot/blob/master/.env.example
> 
> It's a named file specifically assigned to Shell:
> 
> https://github.com/github/linguist/blob/65d078bab8a8bafc5c53614be5c3fec42c2897f0/lib/linguist/languages.yml#L5146-L5175

Wow, didn't even notice that. Thanks!
