### ISSUE TITLE
Bad syntax HL

### ISSUE THREAD

**Issue by Seluj78** [github/linguist#5067]
I could not find the repo of the syntax HL github uses, I know this is most likely the wrong place.

I was looking at this dockerfile and the color is incorrect for half the file

https://github.com/sickcodes/Docker-OSX/blob/8343da16fc3f2c5ebc6e1f79dbf53cdf3639d1f8/Dockerfile#L116-L198

cheers

**Comment by Alhadis** [comment]
> I could not find the repo of the syntax HL github uses

The list of repositories is [linked to in the README file](https://github.com/github/linguist#theres-a-problem-with-the-syntax-highlighting-of-a-file):

> Linguist detects the language of a file but the actual syntax-highlighting is powered by a set of language grammars which are included in this project as a set of submodules as [listed here].

As for the repository that provides Dockerfile highlighting, it's [`asbjornenge/Docker.tmbundle`](https://github.com/asbjornenge/Docker.tmbundle), as listed in [`vendor/README.md`](https://github.com/github/linguist/blob/master/vendor/README.md).

**Comment by Seluj78** [comment]
Thank you for the reply! Have a nice day
