### ISSUE TITLE
C++ with embedded GLSL strings incorrectly labeled as Objective-C

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [github/linguist#5068]
I understand linguist can be told to use attribute files so they are not interpreted or that they are told to be interpreted a certain way, but this would require adding a git-attribute file and listing all of my C++ files because of a simple problem.

## Problem Description
Simply put, my C++ files that contain embedded GLSL are reflected as Objective-C files which is not true. Objective-C isn't even used in my project. It's all C++.

You can see these files show up in the language detection and search filters as "Objective-C" by following this link:
https://github.com/TheMaverickProgrammer/Swoosh/search?l=objective-c

### URL of the affected repository:
https://github.com/TheMaverickProgrammer/Swoosh

### Last modified on:
2020-10-10

### Expected language:
C++

### Detected language:
Objective-C

**Comment by Alhadis** [comment]
> but this would require adding a git-attribute file and listing all of my C++ files

How is that a problem, exactly?

**Comment by TheMaverickProgrammer** [comment]
because there is nothing wrong with my C++ files and they are being mis-interpretted

**Comment by Alhadis** [comment]
Linguist isn't perfect, nor will it ever be. It's ability to distinguish C++ and Objective-C headers is a common issue, which is half the reason we implemented overrides in the first place.

**Comment by TheMaverickProgrammer** [comment]
> Linguist isn't perfect, nor will it ever be.

Not with that attitude

**Comment by Alhadis** [comment]
Yours isn't helping, either.

Now, unless you're willing to submit a PR to make Linguist the shining, immaculate pinnacle of software perfection, I don't think there's anything else to discuss here. You now know what the solution is, it's up to you to help yourself.

**Comment by TheMaverickProgrammer** [comment]
oof bitter
