### ISSUE TITLE
scdoc text files are incorrectly rendered as SuperCollider instead of Markdown

### ISSUE THREAD

**Issue by mvdan** [github/linguist#5072]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

[scdoc](https://sr.ht/~sircmpwn/scdoc/) is a project very similar to [ronn](https://github.com/rtomayko/ronn), with the main difference being that it's written as a small C program instead of Ruby. They both use slight variants of Markdown to write man pages, allowing them to be easy to read and write directly.

Since Ronn is already [detected as Markdown by linguist](https://github.com/github/linguist/blob/143cd81b3e1a70f094f094a34498747211fecfc3/lib/linguist/languages.yml#L3212), those files render well. For example, see [ronn.1.ronn](https://github.com/rtomayko/ronn/blob/master/man/ronn.1.ronn) rendered nicely.

Unfortunately, this is not the case for scdoc files, which have the extension `.scd`, [already taken](https://github.com/github/linguist/blob/143cd81b3e1a70f094f094a34498747211fecfc3/lib/linguist/languages.yml#L5439) by SuperCollider. As such, they render very poorly; for example, see [sway.5.scd](https://github.com/swaywm/sway/blob/master/sway/sway.5.scd).

I realise that the `.scd` extension is already taken or at best ambiguous, so I'm not asking to break that.

I also realise that projects could use gitattributes overrides, and that's better than nothing as a temporary workaround, but I still think it would be nice to support scdoc nicely given that it's extremely similar to ronn.

So here's my suggestion: since scdoc man pages always match the regular expression `[a-z]+\.[0-9]\.scd`, we could simply add the extensions `.1.scd` through `.9.scd` to the [list of extensions](https://github.com/github/linguist/blob/143cd81b3e1a70f094f094a34498747211fecfc3/lib/linguist/languages.yml#L3203-L3213) matching Markdown. This should be doable as long as linguist is smart enough to attempt to match longer extensions before shorter ones, so that `foo.1.scd` matches Markdown and `foo.scd` matches SuperCollider.

### URL of the affected repository:

https://github.com/swaywm/sway/blob/master/sway/sway.5.scd

### Last modified on:

2020-08-03

### Expected language:

Markdown

### Detected language:

SuperCollider

**Comment by mvdan** [comment]
I tried `*.*.scd linguist-language=Markdown` and it kind of works as a temporary workaround, since the syntax highlighting now follows Markdown. But my file is still not being rendered like `.md` and `.ronn` files: https://github.com/mvdan/sh/blob/f1d7185c4d02528db7c2f0290e9356a1c5503683/cmd/shfmt/shfmt.1.scd

**Comment by lildude** [comment]
The rendering of `.md` and `.ronn` files isn't done by Linguist and Linguist doesn't have much influence over that beyond identifying the language. The actual rendering is done by the code in https://github.com/github/markup/.

If you want syntax highlighting, support would need to be added to Linguist - please feel free to submit a PR.

If you want actual rendering, then you'll need to add support to or open an issue in https://github.com/github/markup/, though keep in mind, development in that library has slowed quite considerably over the years.

**Comment by mvdan** [comment]
Thank you, I wasn't aware that language detection and language rendering were separate. Proper rendering is less important than fixing the highlighting I think, so we could fix linguist first and that would already be a big win.

Does my idea above about adding the extensions `.1.scd` through `.9.scd` sound good? Will linguist's extension matcher work with such extensions which should be checked before `.scd`?

**Comment by mvdan** [comment]
I had a quick look at this but I'm afraid that Ruby and the Bayesian classifier steps in CONTRIBUTING.md make this look like a few hours of work rather than a simple PR.

**Comment by Nixinova** [comment]
SCDoc and SuperCollider have very different syntax so Linguist should be able to differentiate them without a heuristic. I'll issue a PR to see if it works properly.

**Comment by Nixinova** [comment]
Added in #5198, can be closed.

**Comment by mvdan** [comment]
Thanks! When would the fix ship to github.com? https://github.com/swaywm/sway/blob/master/sway/sway.5.scd still renders the old way.

**Comment by Nixinova** [comment]
"this week" #5197

**Comment by Nixinova** [comment]
(Requesting closure of this issue)

**Comment by mvdan** [comment]
I'll close this issue when the file above renders properly, if that's okay. If it's been two weeks and the rendering is still wrong, I'll assume that the issue should remain open.

**Comment by Nixinova** [comment]
That file now renders properly with the release of 7.13

**Comment by mvdan** [comment]
It does, thank you!
