### ISSUE TITLE
.plt files recognized as "Gnuplot", but they're also unit test files for Prolog

### ISSUE THREAD

**Issue by atava** [github/linguist#5074]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

As per the title.
 - Prolog is the most used logic programming language
 - SWI-Prolog is the most widespread compiler and framework for Prolog
 - .plt files are unit test files in SWI-Prolog (and maybe other Prolog systems)

I get "Gnuplot" for .plt files. I would like them to be listed as Prolog.
These are the current extensions for Prolog in _languages.yml_:
  - ".pl"
  - ".pro"
  - ".prolog"
  - ".yap"

Reference (point 3): https://www.swi-prolog.org/pldoc/doc_for?object=section(%27packages/plunit.html%27)

### Expected language:

Prolog

### Detected language:

Gnuplot

**Comment by lildude** [comment]
As you've already found, the reason for this is the `.plt` extension is not associated with Prolog and is only associated with Gnuplot, hence your files are being identified as Gnuplot. In order for these files to be identified as Prolog, the extension needs to be added to Prolog too. As there is already a language associated with this extension, we'd also need a heuristic to differentiate the two.

Please review the CONTRIBUTING.md and feel free to submit a pull request adding support.

Until then, you can use an override to force the language to Prolog.

**Comment by atava** [comment]
I've used an override and it is okay with me for now (although I have to set it in every Prolog repo I create).
I'll consider asking for support as you say. Thanks.
