### ISSUE TITLE
Setting syntax only via `.gitattributes`

### ISSUE THREAD

**Issue by silverwind** [github/linguist#5092]
The [linguist-language](https://github.com/github/linguist#using-gitattributes) git attribute currently serves two purposes on GitHub:

1. It sets the syntax highlighting mode for matching files
2. It affects the language stats of the repo for matching files

Now, there are cases where one wants set syntax highlighting differently than the actual language. One example case are [go templates](https://github.com/go-gitea/gitea/blob/0de546009e466486cd88dfa98d07d8775bd3087d/templates/repo/commits_table.tmpl) which GitHub can not highlight at all but they can be made to work reasonably well using the [`Handlebars` syntax](https://github.com/go-gitea/gitea/blob/0de546009e466486cd88dfa98d07d8775bd3087d/.gitattributes#L4), but doing that distorts the language stats.

I'd suggest a new `linguist-syntax` attribute that allows to set syntax explicitly which has precedence over `linguist-language` (which would still be used for language stats).

**Comment by lildude** [comment]
🤔 I'm not sure if this is the right approach or really necessary. It's also not trivial to implement. 

Generally speaking, the language and syntax highlighting grammars are closely tied and very rarely would you have a legitimate reason, other than preference on rare occasions, to use a different grammar from the one for the language in question without changing the identified language.

I can understand your motivation for this request as Go templates are an odd beast in that they're mainly HTML with Handlebar-like syntax and not actually Go, so really shouldn't be identified as Go.

A similar discussion about the syntax highlighting has come up in the VSCode extension too - https://github.com/Microsoft/vscode-go/issues/464 - and it pretty much comes down to it being up to the/a grammar to add support.

https://github.com/microsoft/vscode-go/issues/228 also discusses the topic of highlighting Go template files.

All that said, from a Linguist perspective, a better solution would be to determine how the language should be identified, eg "Go Template" and add it to Linguist, with a supporting grammar. You can see similar things have been implemented this way from the "HTML+<whatever>" or "<whatever> Templates" languages already supported.

**Comment by silverwind** [comment]
Kind of unrelated to the request here, but those template languages are often two or more languages in one, this goes for Jinja, Go Templates and also Handlebars. Some of them do have specific functionality for HTML like escaping but they all have switches to disable the HTML-specific features.

I guess linguist would have to support detecting multiple languages by filename (and also setting multiples via `linguist-language`), like `file.html.tmpl`,`file.yaml.hbs` or even `file.html.hbs.tmpl`. If no second extension is present for template languages, assume HTML. I guess this would be the only surefire way to correctly identify go templates and it would also require the syntax highlighter to be able to handle nested syntaxes, which is probably non-trivial.
