### ISSUE TITLE
Predominantly TSX/TS project is 99% CSS (less than 50 lines of CSS committed though)

### ISSUE THREAD

**Issue by tarikhamilton** [github/linguist#5094]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

My language breakdown hasn't updated in forever and it is very inaccurate.

### URL of the affected repository: 
[https://github.com/tarikhamilton/one-rep-max](https://github.com/tarikhamilton/one-rep-max)

### Expected language:
Should be mostly TypeScript. I do not want to do anything special, just the stock detection settings.

### Detected language:
99% CSS lol

I found a few similar cases, but nothing exactly similar.

[github detects TS repo as CSS](https://github.com/github/linguist/issues/3968) - Theirs had 130KB of CSS, I have like 15 lines. I don't have a lot of TypeScript, but I do have a lot of TSX, which I see is still labelled as TypeScript in the languages.xml.

The one thing that was atypical about my repo is that I created the repo locally on a master branch, but moved things over to the main branch. I have a feeling that that is related, but I do not know how to remedy.

**Comment by lildude** [comment]
> I have like 15 lines.

You have waaaay more than that... like 2.47MB more than that and it alone is so huge that its total bytes of code far exceeds anything else in your repo putting all other languages into the insignificant realm of "other".

You total breakdown by bytes of code is:

CSS 2.47 MB
TypeScript 22.3 KB
HTML 1.82 KB
JavaScript 1.02 KB

The per-file breakdown is:

```console
$ github-linguist one-rep-max/ --breakdown
99.02%  CSS
0.87%   TypeScript
0.07%   HTML
0.04%   JavaScript

JavaScript:
.storybook/main.js
.storybook/preview.js
scripts/set-package-json-homepage.js
tailwind.config.js

HTML:
public/index.html

TypeScript:
src/App.test.tsx
src/App.tsx
src/components/Cell/index.stories.tsx
src/components/Cell/index.tsx
src/components/CircleButton/index.stories.tsx
src/components/CircleButton/index.tsx
src/components/HeaderCell/index.stories.tsx
src/components/HeaderCell/index.tsx
src/components/Inputs/Input.tsx
src/components/Inputs/NumberInput/index.stories.tsx
src/components/Inputs/NumberInput/index.tsx
src/components/Inputs/TextInput/index.stories.tsx
src/components/Inputs/TextInput/index.tsx
src/components/Inputs/index.ts
src/components/SetMaxButtonGroup/index.stories.tsx
src/components/SetMaxButtonGroup/index.tsx
src/components/interfaces/TableCell.interface.ts
src/helpers.tsx
src/index.tsx
src/reducer.ts
src/serviceWorker.ts
src/setupTests.ts

CSS:
src/_tailwind.css
src/index.css
src/tailwind.css   <---- Here's the offender

$
```

That file is 2.47MB which is pretty much _all_ your CSS and almost all the code in your repo.

So if you want you repo to reflect TypeScript you'll need to do one of the following:

1. Remove that file, and maybe update your code to use a CDN-hosted version of it.
2. Use a minified version of the file which Linguist will ignore.
3. Implement an override, but that would go against your desire to use "just the stock detection settings."

**Comment by tarikhamilton** [comment]
Wow, thank you. I thought maybe I created that file within the build process because it did not show up in the Github language search, so I wrote it off as being the cause, though really it could've only been it... https://github.com/tarikhamilton/one-rep-max/search?l=css 

I wonder if this is a bug within Github's search. I will be sure to use github-linguist locally to confirm in the future.
