### ISSUE TITLE
Add Pashmak Programming Language Request

### ISSUE THREAD

**Issue by amirghazi87** [github/linguist#5107]
# New Programming Language
## Pashmak Programming language
the .pashm files is pashmak programming languge
please add it
## The Pashmak Github Ripository
[Pashmak](https://github.com/pashmaklang/pashmak)
Thanks

**Comment by lildude** [comment]
If the language meets the popularity requirement detailed in the CONTRIBUTING.md file, feel free to submit a PR adding support for this language. The requirement is vague at the moment, but we take 200 unique user/repos as a minimum.

**Comment by Nixinova** [comment]
Used in only a handful of repos (to be exact, 4), nowhere near meeting the requirements.

**Comment by parsampsh** [comment]
Hello.
I'm creator of the @pashmaklang
I know count of repositories related to this language should be more than 200.
But about syntax highlighting, we should use which standard?
Currently we have a syntax highlighter for vscode (https://github.com/sami2020pro/vscode-pashmak) and also nano editor(i'm fan of vim ((: ).
What should we do for syntax highlighting? is vscode extension enough?

**Comment by lildude** [comment]
Yes, any TextMate-compatible grammar is fine, so you can use a grammar for TextMate, Atom or VSCode.

**Comment by parsampsh** [comment]
> Yes, any TextMate-compatible grammar is fine, so you can use a grammar for TextMate, Atom or VSCode.

Thanks!

**Comment by parsampsh** [comment]
I sent pull request #5218 for adding Pashmak.
Please close this issue.

**Comment by Nixinova** [comment]
> I know count of repositories related to this language should be more than 200.

Where? Github lists only 77 pashm files. https://github.com/github/linguist/issues/5107#issuecomment-774781832

**Comment by parsampsh** [comment]
> > I know count of repositories related to this language should be more than 200.
> 
> Where? Github lists only 77 pashm files. [#5107 (comment)](https://github.com/github/linguist/issues/5107#issuecomment-774781832)

Yes. not now, new repos will be created soon. I'll re-open the #5218 soon.

**Comment by Nixinova** [comment]
> Yes. not now, new repos will be created soon.

It needs 200 unique repositories to be added, I don't think that would happen 'soon'. I think this issue as well should be closed in the meantime.

**Comment by parsampsh** [comment]
> > Yes. not now, new repos will be created soon.
> 
> It needs 200 unique repositories to be added, I don't think that would happen 'soon'. I think this issue as well should be closed in the meantime.

ok.
