### ISSUE TITLE
Am i missing something? [Repository not updating]

### ISSUE THREAD

**Issue by RaimundoDiaz** [github/linguist#5112]
## Problem Description

I created a repository with a wrong .gitignore file, so at the start, it detected that I had 98% javascript, it was ok because all my node modules were in the repository, once I corrected the .gitignore file I deleted them from the repository, but it did not update. I made a copy of the repository to know if I was missing something but linguist worked perfectly in the new one. So I don't know if I am missing something or what, I tried vendoring code with the .gitattributes file, excluding all the .js files from the repository, and a lot of things I found in the solved issues but nothing worked 😞 
### Last modified on:

< 2020-12-13 >
### Expected language:

I made a copy and created another repository and linguist worked perfectly:
- https://github.com/RaimundoDiaz/test123/tree/master
![expected language](https://i.imgur.com/FfKI33j.png)

### Detected language:

Javascript 100% 😢

**Comment by lildude** [comment]
You'll need to push a change to one of the files that count towards the language stats in order to force a re-analysis as changing or removing the `.gitattributes` alone does _not_ force a re-analysis.

**Comment by RaimundoDiaz** [comment]
> You'll need to push a change to one of the files that count towards the language stats in order to force a re-analysis as changing or removing the `.gitattributes` alone does _not_ force a re-analysis.

Thanks! I deleted everything and uploaded it again and it worked.
