### ISSUE TITLE
Wrong % and languages missing from repo Django project

### ISSUE THREAD

**Issue by davidysoards** [github/linguist#5114]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
Repo languages shows 98.9% CSS and 1.1% other, but clicking on CSS to see the list of the files only finds 2 CSS files out of a total of 65 files.

It also finds 35 Python files, and 20 HTML.

It is a Django project.

I've tried pushing new code, and it does not update the languages.

### URL of the affected repository:
https://github.com/davidysoards/cookup

### Last modified on:
2020-12-16

### Expected languages:
Python, HTML, CSS, JavaScript

### Detected language:
CSS

**Comment by lildude** [comment]
> Expected languages:
>
> Python, HTML, CSS, JavaScript

You mean like this? 😁 

![CleanShot 2020-12-16 at 09 32 46](https://user-images.githubusercontent.com/627280/102330610-ac5c6700-3f81-11eb-9bea-29c35b28752c.png)

> I've tried pushing new code, and it does not update the languages.

Sounds like you didn't give it long enough. From the README:

> How Linguist works on GitHub.com
> 
> When you push changes to a repository on GitHub.com, a low priority background job is enqueued to analyze your repository as explained above. The results of this analysis are cached for the lifetime of your repository and are only updated when the repository is updated. As this analysis is performed by a low priority background job, it can take a while, particularly during busy periods, for your language statistics bar to reflect your changes.

Sounds like you had an out-dated cached analysis and it took a bit of time the re-analysis to be queued and run.

Now it has been run, all looks good to me.

**Comment by davidysoards** [comment]
That's great! I had pushed code last week also and didn't see any change, but all is well now. Thanks for your help.
