### ISSUE TITLE
How to use linguist-vendored in .gitattributes with directories with spaces?

### ISSUE THREAD

**Issue by dan-trewin** [github/linguist#5117]
Github is recognizing my repo as the wrong language due to vendored code.  I've been searching all over for an answer to this issue.

Basically, the directory I want linguist to ignore has a space in it.  Unfortunately, I think this is causing an issue with the pattern matching.

How would I mark `/Assets/TextMesh Pro/*` as vendored code in `.gitattributes`

I've tried all these an none of them have worked:
```
Assets/TextMesh Pro/* linguist-vendored
Assets/TextMesh*Pro/* linguist-vendored
/Assets/TextMesh Pro/* linguist-vendored
```

**Comment by Alhadis** [comment]
This should work:

~~~gitattributes
Assets/TextMesh?Pro/* linguist-vendored
~~~

However, so should `Assets/TextMesh*Pro/*`. Remember, changes to `.gitattributes` files won't immediately take effect until a change to another file is pushed (which forces GitHub to recompute the language stats).

**Comment by dan-trewin** [comment]
Thanks @Alhadis .

I used your suggested pattern: `Assets/TextMesh?Pro/* linguist-vendored` and also changed the README to trigger a new language stats computation.

I also had to wait ~15 hrs for it to recompute. I didn't realize there was a delay for GitHub to recompute the language stats. Good to know!

Closing.

**Comment by mfp0610** [comment]
Assets/TextMesh Pro/** linguist-vendored
You should do so to vendor all the files and directories in the directory
