### ISSUE TITLE
Linguist is not ignoring a file with linguist-generated override 

### ISSUE THREAD

**Issue by susam** [github/linguist#5123]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

[How Linguist Works](https://github.com/github/linguist#how-linguist-works) mentions:

> Linguist starts by going through all the files in a repository and excludes all files that it determines to be binary data, vendored code, generated code, documentation, or are defined as data (e.g. SQL) or prose (e.g. Markdown) languages, whilst taking into account any overrides.

However, I see Linguist is including the files marked as *generated* in the language statistics. For example, https://github.com/susam/10kbclub/blob/master/.gitattributes contains:

```
/index.html linguist-generated
```

But https://github.com/susam/10kbclub/search?l=html shows `/index.html` in the results. As a result of this, the whole repository gets classified as HTML.

### URL of the affected repository:
https://github.com/susam/10kbclub

### Last modified on:
2020-12-28

### Expected language:
JavaScript

### Detected language:
HTML

**Comment by lildude** [comment]
> However, I see Linguist is including the files marked as _generated_ in the language statistics.

It definitely isn't:

```console
$ git clone -q git@github.com:susam/10kbclub.git
$ github-linguist 10kbclub --breakdown
52.73%  HTML
44.71%  JavaScript
2.56%   Makefile

Makefile:
Makefile

JavaScript:
src/checks.js
src/metrics.js
src/refresh.js
src/render.js

HTML:
src/template.html   <---- Only this file counts towards the HTML total

$
```

> But https://github.com/susam/10kbclub/search?l=html shows `/index.html` in the results. As a result of this, the whole repository gets classified as HTML.

This isn't the results of Linguist you're looking at, but the search results (note the `search` in the URL). Linguist doesn't prevent files from being indexed by search else you'd never be able to find files in your own repo if you marked them all to be ignored.

> As a result of this, the whole repository gets classified as HTML.

Nope. Your repo is showing HTML as the primary language because you have more bytes of code of HTML than anything else, and it's all down to one file.

**Comment by susam** [comment]
Thank you, @lildude, for the detailed explanation.
