### ISSUE TITLE
C header file detected as C#

### ISSUE THREAD

**Issue by foggynight** [github/linguist#5128]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [ ] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

One of the C header files in my repo is being detected as C#. There are doxygen comments, but besides that it's all very C.

This is related to #1626 

### URL of the affected repository:
https://github.com/foggynight/ascii-engine

### Last modified on:

2020-01-02

### Expected language:

C

### Detected language:

C#

**Comment by lildude** [comment]
The same thing detailed in https://github.com/github/linguist/issues/1626 applies here. You'll need to implement an override to force your preferred language.

**Comment by foggynight** [comment]
Got it, was hoping for a solution that didn't involve adding any files to the repo, but thank you regardless.
