### ISSUE TITLE
Add Netlify _redirects file

### ISSUE THREAD

**Issue by Nixinova** [github/linguist#5145]
# New filename
@Netlify has special `_redirects` files that when placed in the root directory controls the redirects of the website.

Used in 6K+ repos ([query](https://github.com/search?p=2&q=path%3A%2F+filename%3A"_redirects"+-language%3ACSV&type=Code)).

[Netlify docs](https://docs.netlify.com/routing/redirects/).

## Syntax
*For a tmLanguage to be created (I could probably do it myself later).*

```
# comment
<input_uri> [<query1>] [<query2...>] <output_uri>[<http_status>[!]] [{Country|Language}=<code1>[,<code2...>]]
```

The input may contain a wildcard `*` which is represented in the output by `:splat`. Placeholders are represented using `:<name>` in both input and output. A `!` after the status forces the redirect rule to apply even if the input URI exists.

**Comment by lildude** [comment]
🤔 this might be a little tough to add support for with syntax highlighting as from what I can see this isn't really a new language and I can't think of another language that the filenames could be associated with.

**Comment by Nixinova** [comment]
Are there any other syntaxes that just contain hash comments, URLs, and key=values?

**Comment by lildude** [comment]
I have no idea, you tell me 😉

**Comment by Nixinova** [comment]
Is this out if scope of Linguist as it's not a proper language per se?

**Comment by Nixinova** [comment]
Should this still be added though?

**Comment by Nixinova** [comment]
Created tmLanguage: https://github.com/Nixinova/tmLanguage/blob/a5d2226e9fadf709c661ce760ed81a6a021ea93c/grammars/_redirects.tmLanguage.yaml
