### ISSUE TITLE
Group Liquid under HTML

### ISSUE THREAD

**Issue by Nixinova** [github/linguist#5150]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides) [have done so]
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Description

Currently Linguist classifies Liquid as its own language. However, extremely similar languages like Nunjucks are classified under a subset of HTML (HTML+Django). Therefore Liquid should also be classified as a subset of HTML, as Liquid and Nunjucks are very, very similar in syntax and it makes no sense for them to be classified in two different ways.

**Comment by lildude** [comment]
Sounds reasonable to me. We'd welcome a PR adding the grouping.

**Comment by Alhadis** [comment]
Hold up. This would contradict our changes in #4979, where similar templating languages were removed from the HTML group.

If there's a change to be made, it should be to dissociate Nunjucks from `HTML+Django`.

**Comment by lildude** [comment]
🤦 Good catch @Alhadis; I completely forgot about that.

**Comment by Nixinova** [comment]
Ah, so it should go the other way, with everything being ungrouped from HTML? Will close this issue then.
