### ISSUE TITLE
Pascal: need highlight of hex numbers

### ISSUE THREAD

**Issue by Alexey-T** [github/linguist#5154]
Delphi/FreePascal support HEX numbers:
```
$0
$ABCD
$FF00EE
```

Current site don't highlight these as 1 token
![bug2](https://user-images.githubusercontent.com/4154978/105029633-a6b3de80-5a63-11eb-9d69-415d7d7836d4.png)

@artem3213212

**Comment by lildude** [comment]
Closing as per my comment in your previous issue at https://github.com/github/linguist/issues/5153#issuecomment-762807585
