### ISSUE TITLE
Pascal: highlight special FPC words

### ISSUE THREAD

**Issue by Alexey-T** [github/linguist#5155]
FreePascal supports such special words (not KEYwords but special)

https://github.com/Alexey-T/lexer_tests/blob/master/lexers/Pascal/special%20FPC%20words.pas

file lists them almost all.
in 1st block: not highlighted words: 
```
function
procedure
```
in 2nd block: many are not supported.

@artem3213212

**Comment by lildude** [comment]
Closing as per my comment in your previous issue at https://github.com/github/linguist/issues/5153#issuecomment-762807585
