### ISSUE TITLE
Unable to detect Python Language on repository

### ISSUE THREAD

**Issue by abentgeorge** [github/linguist#5160]
## 
I'm practicing data cleaning via python. However my [repository](https://github.com/abentgeorge/Data_Cleaning---Splitting-Names) is only detecting JupyterNotebook 

I understand why Jupyter notebook is being detected(extra cell code) but couldn't find a workaround

I tried creating the python file on Sublime text and uploading it separately but even then the language is only detecting Jupyter.
 How do I go about this?

**Comment by abentgeorge** [comment]
Apologies if I've used the wrong label, still new to using GitHub

**Comment by abentgeorge** [comment]
So python was detected. Must have not updated after the first refresh. Any workaround for the Jupyternotebook issue?

**Comment by lildude** [comment]
This issue really should have been opened as a Discussion (last option in the list you were presented with when opening this issue). I'd transfer it, but the option isn't coming up and I'm still trying to workout why.

Please can you re-open this as a [discussion](https://github.com/github/linguist/discussions) in the "Language Analysis" category.

**Comment by lildude** [comment]
I've reopened this issue and will transfer it to discussions and answer once moved.
