### ISSUE TITLE
My project isn't showing the language bar i don't know why?

### ISSUE THREAD

**Issue by zalazel** [github/linguist#5179]
this is the link for my project and it is not showing the language bar unlike my other projects!
https://github.com/zalazel/tesla-clone

**Comment by lildude** [comment]
It does now 😄 

Looks like there was an issue with the background jobs when you pushed your changes two weeks ago. I've run the job again so now you see the bar. If you'd pushed again it would have kicked off the jobs again too.

**Comment by zalazel** [comment]
thanks :)
