### ISSUE TITLE
Mikrotik RouterOS files are .rsc and NOT Rascal!

### ISSUE THREAD

**Issue by madman22** [github/linguist#5216]
Mikrotik scripting language is not in the list of languages, and the source code is not highlighting correctly.

.rsc files are Mikrotik RouterOS scripts but github detects them as Rascal.  They are not rascal.

Mikrotik RouterOS predates Rascal by a couple decades.

**Comment by lildude** [comment]
Sounds like you're stating Linguist is missing support for a language (Mikrotik) so this would not be a bug.  

To ensure we've got all the correct information, please open a new issue using the "New language" option and fill in the template as best you can.
