### ISSUE TITLE
Add `linguist-configuration` attribute for configuration files?

### ISSUE THREAD

**Issue by matt17r** [github/linguist#5228]
## Description

I've only just discovered Linguist so I might be missing something obvious but it seems to me that configuration files are currently included in repository statistics. Whilst some of them are generated and could perhaps be assigned the `linguist-generated` attribute, I think a `linguist-configuration` label would make more sense for many of them.

Examples of configuration files in a fairly standard Rails (plus Tailwind) application include:

- app/assets/config/manifest.js
- app/javascript/packs/application.js
- app/javascript/stylesheets/application.scss
- Everything in config/ (for me that's a mixture of 19 `.rb`, 4 `.js`, and 5 `.yml` files)
- .browserslistrc
- .ruby_version
- babel.config.js
- config.ru
- Gemfile
- package.json
- postcss.config.js
- Rakefile
- tailwind.config.js

**Comment by Alhadis** [comment]
The override you're looking for is `linguist-vendored` or `linguist-documentation` (both of which do the exact same thing), which tells Linguist to ignore files when calculating language statistics (but include them in diffs).

**Comment by Nixinova** [comment]
> both of which do the exact same thing

Is there a reason why there isn't just one "linguist-hidden" attribute then?

**Comment by lildude** [comment]
@Nixinova I don't know the full history but I'm guessing probably because that doesn't really help with language classification (Linguist's primary purpose) and adds additional uncertainty about whether the changes to those files are shown in diffs or not and if they're counted or not.

**Comment by Alhadis** [comment]
@lildude Would it be correct to say that `linguist-documentation` is functionally identical to `linguist-vendored`? If so, we could simplify [our overrides docs](https://github.com/github/linguist/blob/02ffab2d4df3034c05fd7b2e8bf0a2fd31c0452d/docs/overrides.md#documentation) by advertising `linguist-documentation` as an alias of `linguist-vendored` (which might be clearer than "_vendored"_ in certain contexts).

**Comment by Alhadis** [comment]
[A test I performed earlier](https://github.com/Cutlery-Drawer/cutlery-drawer.github.io/commit/0baa40398e58fcafa5453c65300e53ef9c18f040) would suggest otherwise.

**Comment by Nixinova** [comment]
> Gimme some time to dig through the GitHub code to see if there's something there. I've not looked at this part of the code in a long time as "it just works"

Any update on that?

**Comment by lildude** [comment]
Whoops. I completely forgot about it. 

> Would it be correct to say that `linguist-documentation` is functionally identical to `linguist-vendored`? If so, we could simplify [our overrides docs](https://github.com/github/linguist/blob/02ffab2d4df3034c05fd7b2e8bf0a2fd31c0452d/docs/overrides.md#documentation) by advertising `linguist-documentation` as an alias of `linguist-vendored` (which might be clearer than "_vendored"_ in certain contexts). Currently, we make it sound like each override is distinct from each other (which adds to confusion/ambiguity…)

Nope, we can't do that. I've done a quick search and there are places within GitHub which do not consider these identical, like the new search where documentation is indexed but [vendored and generated code isn't](https://docs.github.com/en/search-github/github-code-search/about-github-code-search#limitations).

**Comment by Nixinova** [comment]
Makes sense :+1:
