### ISSUE TITLE
Add support for Quova programming language

### ISSUE THREAD

**Issue by FauxKiwi** [github/linguist#5229]
## Language name
Quova

## URL of example repository
https://github.com/FauxKiwi/QuovaExample

## URL of syntax highlighting grammar
https://github.com/FauxKiwi/QuovaLanguage/tree/master/src/main/antlr/quova.antlr

## Most popular extensions
.qv .qvm

**Comment by Nixinova** [comment]
Languages must be used in many (200+) repos, meaning new hobbyist languages are excluded until they are in general use.
