### ISSUE TITLE
Difference between prefixed and suffixed attributes

### ISSUE THREAD

**Issue by mmarti** [github/linguist#5234]
Apologies in advance if I'm just doing something stupid, but spent a bit of time scratching my head on why this wouldn't work. Please let me know if this is expected behavior or a possible bug.

Long story short, I have a repo with a `node_modules` directory that contains actual app code (it's useful to piggyback on node's module resolution logic so we can just `require('my-cool-module')` instead of using relative paths, etc., but that's neither here nor there).  I wanted to include files in that directory in the language stats along with unsuppressing diffs, so I tried the following:

```
# Doesn't work
/src/node_modules/ -linguist-vendored 

# Doesn't work
/src/node_modules/ -linguist-vendored -linguist-generated

# Language stats show but diff still suppressed
/src/node_modules/** -linguist-vendored -linguist-generated

# Works
/src/node_modules/** linguist-vendored=false linguist-generated=false

# Also works
/src/node_modules/** -linguist-vendored linguist-generated=false
```

Is there some weird behavior or difference between using the negation-style prefix versus the false-style suffix?  Any help or explanation would be awesome.  Both `-linguist-vendored` and `linguist-vendored=false` work, but only the false-style suffix works for `linguist-generated`, which seemed really odd on the surface.  On a side note, I did get a working version of it, but it'd be great to know if I was doing something wrong / this is expected or if this is a bug.

**Comment by lildude** [comment]
🤔 the method to process the attributes is the same for all the boolean overrides:

https://github.com/github/linguist/blob/fcda9cfe7295c1d51409c2de5f111b9847ff427b/lib/linguist/lazy_blob.rb#L48-L62

... so I'd expect `-linguist-generated` to work like `-linguist-vendored` does.

In the case of generated, it in turn calls in to https://github.com/github/linguist/blob/fcda9cfe7295c1d51409c2de5f111b9847ff427b/lib/linguist/generated.rb which checks the actual files which doesn't care about the gitattributes.

Could you have maybe made a typo or not given it long enough for the background job to run for the `-linguist-vendored -linguist-generated` setting?

Do you see this problem if you switch the two around?

Do you have a repo in which we can see this in action?

**Comment by mmarti** [comment]
This was actually a private repo in a GitHub Enterprise instance, so unfortunately I don't have a public link I could share.  It's possible the enterprise instance is using an older version or doing something else funky, but I'm not sure.  Regarding the typo / not waiting long enough, I did multiple tests going back and forth and could reproduce it consistently, so I'm fairly confident there is something wrong, but it might be a weird interaction with linguist and not linguist itself.

I appreciate you confirming the expected behavior.  Feel free to close this for now.  If I'm able to get a smaller reproducible example I can share, I can reopen / create a new issue and go from there.  Thanks for the reply.

**Comment by lildude** [comment]
No probs.

If you do manage to come up with an reproduction and it's only reproducible on GitHub Enterprise Server (GHES), I can check the version of Linguist shipped with that version and see if I can reproduce it too. You can determine the version of GHES by hovering your cursor over the Octocat icon at the bottom of any page on your instance. You should get a tooltip showing the version of GHES.

Closing as requested.
