### ISSUE TITLE
Missing and renamed packages for ubuntu in CONTRIBUTING.md

### ISSUE THREAD

**Issue by wader** [github/linguist#5245]
## Describe the bug

Hi while workingon #5233 I was following the steps in `CONTRIBUTING.md` but there were some missing and renamed packages. Here are the steps I eventually used:

```
docker run -ti --rm -v "$PWD:$PWD" -w "$PWD" -v /var/run/docker.sock:/var/run/docker.sock ubuntu
apt-get install cmake pkg-config libicu-dev docker.io ruby ruby-dev libz-dev build-essential libssl-dev
gem install bundler
script/bootstrap
script/add-grammar https://github.com/wader/linguist-language-jq
script/update-ids
bundle exec rake samples
bundle exec rake test
```

**Comment by lildude** [comment]
@wader Do you mind opening a PR to update the docs? Things like this can and do happen so PRs are best to keep things up-to-date quickly. 🙇

**Comment by wader** [comment]
I guess the list of packages we the only thing really if we don't indent of adding instructions for using docker?

**Comment by lildude** [comment]
> if we don't indent of adding instructions for using docker?

I hadn't considered documenting using Docker for dev until you mentioned it. I'll add it to my TODO list.

**Comment by wader** [comment]
Mm i can be quite convenient if you don't want to mess with your host environment too much
