### ISSUE TITLE
Node shebang causes TypeScript files to be classified as JavaScript

### ISSUE THREAD

**Issue by Nixinova** [github/linguist#5251]
## Describe the bug
TypeScript (.ts) files are classified as JavaScript when they contain a Node shebang, as Node is listen as a JS-only interpreter in languages.yml.

TypeScript passes through any shebangs on the file, so when a shebang is needed on the outputted JS the easiest option is to add the Node shebang to the initial .ts file as well. This is necessary when making CLI applications.

### Expected behaviour
TS files should be classified as TS even when containing a JS-env shebang.

### Related discussion

Originally opened and discussed as #5249. Moved here to allow for easier tracking and linking etc.

### Additional notes
Looking at [this search query](https://github.com/search?q=extension%3Ats+language%3Ajs&type=code) I'm not the only one who gets their repo misclassified when you add the Node shebang. Which is valid syntax (https://github.com/Microsoft/TypeScript/issues/2749), and is the only way I can see to get my TS scripts to work in Node when compiled without adding any overhead. It's even [encouraged](https://itnext.io/how-to-create-your-own-typescript-cli-with-node-js-1faf7095ef89), and projects like [this](https://github.com/skovy/typed-scss-modules/blob/f006f40b4ecf7350ac8bf6da341ee20924f4f866/lib/cli.ts) are forced to use the shebang as otherwise the file cannot be run as a CLI.

**Comment by lildude** [comment]
🤔... `node` was deliberately removed from TypeScript by @Alhadis in https://github.com/github/linguist/pull/4470 with the explanation at https://github.com/github/linguist/issues/4469#issuecomment-475488529

**Comment by Nixinova** [comment]
So adding Node causes the opposite issue? How could Node be added as a valid TS interpreter without messing with JS detection?

**Comment by Nixinova** [comment]
#4558 was closed as "use override" but this is too widespread for that to be a valid solution.

**Comment by Alhadis** [comment]
> So adding Node causes the opposite issue?

I'm... really not sure how you reached that conclusion. It was adding [*Deno*](http://deno.land/) that was causing the aforementioned issue.

> #4558 was closed as "use override" but this is too widespread for that to be a valid solution.

It's only widespread because of TypeScript's (current) popularity. This is really an edge-case that Linguist isn't expected or equipped to handle — hashbangs aren't supposed to appear in files that can't be directly executed by an interpreter.

If I were to fix this, it would be on TypeScript's level; i.e., by transpiling stuff like `#!/usr/bin/env tscx` into `#!/usr/bin/env node` when compiled. Here, `tscx` (or `tsx`, _"TypeScript Compile and eXecute"_) is a hypothetical executable that's installed alongside `tsc` which compiles and runs a TypeScript file à la [`ts-node`](https://www.npm.com/package/ts-node).

**Comment by Nixinova** [comment]
> > So adding Node causes the opposite issue?
> 
> I'm... really not sure how you reached that conclusion.

Adding Node *would* cause the opposite issue, I mean.

> This is really an edge-case that Linguist isn't expected or equipped to handle

So is there any way this can be fixed with Linguist, or will I have to open a feature request in the TypeScript repo on including an outputted shebang?

**Comment by Alhadis** [comment]
The latter. When referencing this issue, make it clear that this isn't an issue Linguist **can't** fix — it's something we **shouldn't** fix.

**Comment by hyrious** [comment]
Facing the same. It was my typescript source code: https://github.com/hyrious/esbuild-dev/blob/bb8366775d7003ca2b70fb482b9e76fb349a81db/src/bin.ts. The shebang at the top of file is not indicating this file is written in js. It is just a "comment" to let the compiler print out ([the output file](https://cdn.jsdelivr.net/npm/@hyrious/esbuild-dev@0.4.4/dist/bin.mjs)).

I think this issue **should** be fixed. As I don't understand why people want to use shebang to **override** the language indicated by extname (when extname exists). I mean, files without extname can use shebang to tell the language, but files with extname should ignore shebang.

````
```ruby
#!/usr/bin/env python3
# code in the file is valid python code,
# but the file is ending with .rb, how come?
```
````

One exception is that the extname of the file is part of **executable** name. For example a binary called `a.rb` wants users to use it by `a.rb xxx`. I'm not sure if it's worth.

**Comment by Nixinova** [comment]
> As I don't understand why people want to use shebang to override the language indicated by extname (when extname exists).

Extensions are just a suggestion; shebangs (usually) mean "execute me only with this", which should be a guaranteed language match. TS is forcing misuse of the shebang, so I've opened microsoft/TypeScript#45319.

**Comment by regan-karlewicz** [comment]
@Nixinova 

For what it's worth, you can use a postbuild script to update your file's shebang.

E.g. in your package.json scripts:

```
    "build": "tsc",
    "postbuild": "perl -i -pe 's,#!/usr/bin/env ts-node,#!/usr/bin/env node,g' cli.js",
```

And then when you build...

```
➜ yarn build
yarn run v1.22.18
$ tsc
$ perl -i -pe 's,#!/usr/bin/env ts-node,#!/usr/bin/env node,g' cli.js
✨  Done in 1.46s.
```

And the outputted JS will have the correct shebang.
