### ISSUE TITLE
Add support for robots.txt

### ISSUE THREAD

**Issue by YashTotale** [github/linguist#5256]
## Language name

`robots.txt`

## URL of example repository

https://github.com/jonasjacek/robots.txt/blob/master/robots.txt

## URL of syntax highlighting grammar

[Google's robot.txt parser and matcher](https://github.com/google/robotstxt). This is written in C++, so I'm not sure if it is applicable.

## Most popular extensions

- `robots.txt`

## Detected language

- Text

**Comment by ShubhamPalriwala** [comment]
Hey @YashTotale ,
Can you elaborate a bit more on what we're planning to do here?

**Comment by Nixinova** [comment]
> This is written in C++, so I'm not sure if it is applicable.

Syntax highlighting must be TextMate (tmLanguage) files.

> Can you elaborate a bit more on what we're planning to do here?

Linguist controls the language classification and syntax highlighting of files on GitHub, so if this is implemented robots.txt files would have syntax highlighting applied to them.

**Comment by ShubhamPalriwala** [comment]
Hey @Nixinova ,
Okay so basically whenever a repo has `robots.txt`, we are planning to have it's own linguistic support and syntax highlighting right?

**Comment by Nixinova** [comment]
> Okay so basically whenever a repo has robots.txt, we are planning to have it's own linguistic support and syntax highlighting right?

Yes, exactly.

**Comment by Nixinova** [comment]
I've made a syntax highlighting grammar here: https://gist.github.com/Nixinova/fb1ca5717c3a9a5e35c468af3345da16
