### ISSUE TITLE
Configuring `github-linguist`

### ISSUE THREAD

**Issue by Yash-Singh1** [github/linguist#5283]
## Describe the enhancement

There should be some sort of configuration file that can be present at any directory that allows to whitelist or disable certain languages or select or disable files that should be reported from `github-linguist`. This can be useful in a repository for example where there is a `bin` directory present that someone doesn't want to be reported. Another use case is where you know that all the HTML inside the current directory is generated and don't want `github-linguist` reporting it.

**Comment by lildude** [comment]
Unless I'm misunderstanding your request, there already is a file… the `gitattributes` file which can be used to do exactly what you have described. Please read the documentation linked from the README.

**Comment by Yash-Singh1** [comment]
@lildude Thanks! I did not see that. That means that:

```gitattributes
*.js linguist-vendored
```

Should not report JS files.
