### ISSUE TITLE
Issues with script/add-grammar

### ISSUE THREAD

**Issue by am11** [github/linguist#5291]
Adding / updating grammar source per the docs https://github.com/github/linguist/blob/master/CONTRIBUTING.md is resulting in unclean state since nixinova submodule is introduced (#5261). It looks like it was manually added rather than using the script which docs talk about (`script/add-grammar`)? Currently, running the script for any other language removes Nixinova/tmLangauge submodule.

cc @Nixinova, @Alhadis

**Comment by am11** [comment]
Looks like the fix is two-fold:

1. https://github.com/Nixinova/tmLanguage/compare/main...am11:main - linguist compiler doesn't like numerical keys and doesn't understand `Repository[booleans].punct` key. It also expect YAML grammar files with extension `.yaml-tmLanguage` rather than `.tmLanguage.yaml`. The script which drives the compiler expects that the repo name is `Nixinova-tmLanguage`, but I have updated it so we can provide optional name (see <span>#</span>2a.
2. there are two parts:
  a. Apply this patch to script/add-grammar only: https://github.com/github/linguist/compare/master...am11:feature/submodule/nixinova#diff-6673ed6341634ad54dcf459f17f48029a04eacfeb453245a35d2a86558e7c265
  b. after <span>#</span>1, we can run `script/add-grammar https://github.com/Nixinova/tmLanguage NixniNova-tmLanguage` to get diff similar to https://github.com/github/linguist/compare/master...am11:feature/submodule/nixinova (`Nixninova` instead of `am11`).

**Comment by Nixinova** [comment]
Could you open an issue on https://github.com/Nixinova/tmLanguage with what needs to be changed on my end? Thanks.

**Comment by am11** [comment]
This PR has all the things we need from the downstream repo: https://github.com/Nixinova/tmLanguage/pull/4. If you could rename the repo to Nixinova-tmLanguage, that would be good (but it is not mandatory).

**Comment by Alhadis** [comment]
> linguist compiler doesn't like numerical keys
> […]
> Looks like an indentation error on my end

This is why I hate YAML.

**Comment by Nixinova** [comment]
Merged changes upstream. What is needed on Linguist's side?
