### ISSUE TITLE
Support updated Perl syntax highlighting

### ISSUE THREAD

**Issue by PatrickCronin** [github/linguist#5309]
## Describe the enhancement

The upstream library used by github for Perl(5) syntax highlighting recently merged a few commits that adds [support for intended heredocs](https://github.com/textmate/perl.tmbundle/pull/42) and [improves scoping](https://github.com/textmate/perl.tmbundle/commit/a85927a902d6e5d7805f56a653f324d34dfad53a). It would be great if github could include these recent changes from that library.

**Comment by lildude** [comment]
And it will as we pull in the latest grammars every time we make a new release (this is mentioned in the docs). I'm in the process of testing the next release for release this week. Your changes missed my last sync last week but I'll be doing another to pull in a few other grammar updates which will pick up the Perl changes too.

You can track the release in https://github.com/github/linguist/pull/5305

As this is standard practice, we don't need this issue so I'm closing it.
