### ISSUE TITLE
Search bug: Clicking on a language under the language bar returns no results OR Search results show the wrong language.

### ISSUE THREAD

**Issue by medvednikov** [github/linguist#5320]
## Describe the bug

Each repo has a "languages" section to the right. If the language is V, clicking on it redirects to https://github.com/vlang/v/search?l=v which results in `We couldn’t find any code matching '' in vlang/v
You could try an advanced search.`

(Using the largest V project as an example: https://github.com/vlang/v)

### Expected behaviour

List of files written in this language, like for JS:

https://github.com/vlang/v/search?l=javascript

**Comment by Nixinova** [comment]
GitHub's language search uses an outdated version of Linguist; that's probably the issue.

**Comment by lildude** [comment]
Yes, this is a problem with Search, not Linguist. To quote [modified here] my response at https://github.com/github/linguist/discussions/5249#discussioncomment-428558

> This is the Search behaviour playing up and not Linguist (you should see that it is only the search results showing this). This is the same issue that affects #5052 and [the] previous discussion at #5220
>
> I opened an internal issue off [the] last discussion and I've since learnt the reason for this: the search functionality was written in Go and is using an old fork of https://github.com/src-d/enry taken before it was forked off into the publicly maintained https://github.com/go-enry/go-enry. Our older fork has changes equivalent to Linguist v7.2.0 so is missing a whole lot of the newer languages etc.
>
> Work is underway to get our changes up-streamed and then we'll switch over to using it instead at which point Search will start reflecting what the language bar does. There's no timeline on when this will happen though.

**Comment by lildude** [comment]
As this isn't a bug in Linguist, I'm going to re-title and pin this issue to reduce duplication.

**Comment by lildude** [comment]
For those curious and following along, these are the two PRs in which we're up-streaming our changes:

- https://github.com/go-enry/go-enry/pull/46
- https://github.com/go-enry/go-enry/pull/47

We'll switch to using the public repo once they're merged and a new release has been made.

**Comment by Nixinova** [comment]
Seems to be fixed?

**Comment by medvednikov** [comment]
Yes, works great now!

Great job and thanks a lot.

**Comment by XusinboyBekchanov** [comment]
Still does not show FreeBasic.

**Comment by lildude** [comment]
> Still does not show FreeBasic.

Yup, that's because we just missed getting go-enry updated to include the 7.14.0 changes in. Things will work once they merge https://github.com/go-enry/go-enry/pull/52 and make a new release.

**Comment by XusinboyBekchanov** [comment]
They merged and made a new release, for some reason there is no result yet.

**Comment by XusinboyBekchanov** [comment]
https://github.com/go-enry/go-enry/releases/tag/v2.7.1

**Comment by lildude** [comment]
The Search part of GitHub (completely independent of Linguist) has not updated to that version yet. This is completely out of my or Linguist's control. Please be patient, or if you can't may I suggest you contact GitHub support.
