### ISSUE TITLE
Make Linguist able to detect multiple languages in the same file

### ISSUE THREAD

**Issue by stopmotio** [github/linguist#5326]
## Describe the enhancement
Take a one page/file web-app. The HTML file counts as 100% HTML, when it is most likely ~90% JavaScript, 9% CSS, and just 1% HTML. I'd like to see files that can hold multiple languages properly supported.

**Comment by lildude** [comment]
This is almost certainly never going to happen without a major rewrite of how Linguist works and even then, I think it would be incredibly resource intensive and probably highly unreliable when it comes to attempting to differentiate between the different languages within the same file.

This has been brought up a few times in the past in the discussions around detecting Python in Jupyter files in https://github.com/github/linguist/issues/3316, R in Rmarkdown files in https://github.com/github/linguist/issues/5208, and JavaScript in HTML files in https://github.com/github/linguist/discussions/5248

**Comment by stopmotio** [comment]
I have an improvised solution:
For every <script> in an HTML file, add a certain % of the script as JS.
For every <style>, do the same

Do this for other formats too, html is just one example.

How difficult would this somewhat botched solution be?

**Comment by lildude** [comment]
If you've got an extensible (so it can be used for other languages), performant and relatively accurate working method of doing this, I'd love to see a PR.

**Comment by stopmotio** [comment]
I don't know Ruby but here's the basic loop

For every transitional object (i.e. bit of text that goes from one language to another)
Add 10% or so of that language to the file's total.

**Comment by lildude** [comment]
That's not going to be very performant nor accurate. Arbitrarily adding some figure will most definitely upset a lot of peeps. Case in point: if your one 100 line file repo has only a single line of HTML, I don't think you'd want your language stats to say 10% of the repo's content was HTML. 

Your suggestion also requires iterating over every single line of the file which might be fine on a few repos but it won't scale well to the numbers GitHub hosts.

**Comment by stopmotio** [comment]
It's definitely going to be difficult, no doubt, and it's in accurate, but it's _something._ but if it can't work, I'll close.

**Comment by stopmotio** [comment]
Plus this was only brought to light by that NotepadWeb repo anyway so if it doesn't serve it at all it's a bit too botched
