### ISSUE TITLE
highlight grpc syntax in protobuf

### ISSUE THREAD

**Issue by longkai** [github/linguist#5334]
## Describe the enhancement

Currently, there is no syntax highlight for gRPC in protobuf files. Since gRPC is well used for many projects and many editors has highlight support for it, I suppose Github should add this feature?

![image](https://user-images.githubusercontent.com/1432582/115658201-e217bf00-a36a-11eb-9389-b32c05e95872.png)
![image](https://user-images.githubusercontent.com/1432582/115658228-f22f9e80-a36a-11eb-85f9-c8015f248b75.png)

**Comment by lildude** [comment]
This isn't going to be anything within GitHub's or Linguist's direct control.

Linguist, and thus GitHub, already supports protocol buffer, hence you are seeing partial syntax highlighting. Anything missing from this highlighting is then down to the grammar itself, which in this case is the one from https://github.com/michaeledgar/protobuf-tmbundle 

You will need to ask the maintainer of the grammar to extend support as per our recommendation in the [There's a problem with the syntax highlighting of a file](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#theres-a-problem-with-the-syntax-highlighting-of-a-file) section of the Troubleshooting doc. These updates will then be pulled into Linguist and GitHub on the next release after the grammar gains support.

If the maintainer of the grammar is non-responsive or unwilling to make the change or accept the change if you submit a PR yourself, the only other way of getting this support is to find a new and more actively maintained grammar which does correctly support this and submit a PR to Linguist to change the source.

A quick looks suggests https://github.com/michaeledgar/protobuf-tmbundle isn't particularly active and may no longer be maintained. I have however found that VSCode grammar at https://github.com/zxh0/vscode-proto3 does appear to be actively maintained, and I'm guessing VSCode is where your second screenshot comes from. If so please feel free to read the CONTRIBUTING.md file for details on changing the grammar source and send us a PR.

**Comment by longkai** [comment]
Hi, thank you for your informative reply.

I have followed the steps and send the PR, please give it a review.
