### ISSUE TITLE
Change Vue's language color

### ISSUE THREAD

**Issue by wenfangdu** [github/linguist#5338]
## Describe the enhancement

The current Vue display color is `#2c3e50`, which doesn't feel quite like Vue and kind of hard to see, I suggest changing it to `#41b883`, which is the color taken from below, which feels more Vueish:

![image](https://user-images.githubusercontent.com/28700378/115889741-c9043080-a486-11eb-9d01-afd71f67f002.png)

**Comment by lildude** [comment]
Vue's colour - which looks quite similar to the blue in the logo - has been in place for over six years so changing it now _will_ be noticed and will likely cause a stir. As a result it will not be changed without full community support (to be debated etc on official Vue community forums, not in this or any other Linguist issue). See the [section](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#changing-the-color-associated-with-a-language) dedicated to this topic in the CONTRIBUTING.md for more details.

**Comment by wenfangdu** [comment]
Link this [issue](https://github.com/vuejs/vue-next/issues/3674) for tracking.

**Comment by lildude** [comment]
The comments from https://github.com/github/linguist/pull/2513#issuecomment-123480804 explains why the current colour was chosen. We used to have a requirement that all colours had to be visually distinct from each other but we dropped that requirement in https://github.com/github/linguist/pull/4978

**Comment by yyx990803** [comment]
Author of Vue here.

Good to see the color restrictions being dropped in https://github.com/github/linguist/pull/4978 - in this case I'm in full support for changing the color to the green which is more representative :)
