### ISSUE TITLE
Add support of AsciiDoc

### ISSUE THREAD

**Issue by tamasborbas** [github/linguist#5342]
## Language name

AsciiDoc

## URL of example repository

* https://github.com/asciidoctor/asciidoc-docs
* https://github.com/eclipse/che-docs
* https://github.com/viatra/org.eclipse.viatra

## URL of syntax highlighting grammar

https://github.com/highlightjs/highlight.js/blob/main/src/languages/asciidoc.js

## Most popular extensions

`.adoc`, `.asciidoc`, `.ad`, `.asc`

## Detected language

There is none

**Comment by lildude** [comment]
Linguist already has support for AsciiDoc:

https://github.com/github/linguist/blob/32ec19c013a7f81ffaeead25e6e8f9668c7ed574/lib/linguist/languages.yml#L350-L359

It won't show up in your language statistics by default as it's considered prose and prose is not counted by default. If you want your repo to show AsciiDoc, you'll need to implement the [`linguist-detectable` override](https://github.com/github/linguist/blob/master/docs/overrides.md) in your repos.

**Comment by tamasborbas** [comment]
Oh, thanks and sorry for the irrelevant issue then!
