### ISSUE TITLE
Error running add-grammar

### ISSUE THREAD

**Issue by alerque** [github/linguist#5343]
I'm trying to add a new grammar (#5341) and have experimented with several possible sources. Following the new language contribution guide, one in particular that looks like it might work leads me to this command:

```console
$ ./script/add-grammar https://github.com/macabeus/vscode-fluent
Checking docker is installed and running
$ docker ps
Registering new submodule: vendor/grammars/vscode-fluent
$ git submodule add -f https://github.com/macabeus/vscode-fluent vendor/grammars/vscode-fluent
$ script/grammar-compiler add vendor/grammars/vscode-fluent
Caching grammar license
$ bundle exec licensed cache -c vendor/licenses/config.yml
  > bundler: command not found: licensed
  > Install missing gem executables with `bundle install`
Command failed. Aborting.
```

I've tried installing dependencies as instructed, but it doesn't help:

```console
$ bundle install
...
Fetching licensed 2.15.0
Installing licensed 2.15.0
Bundle complete! 12 Gemfile dependencies, 35 gems now installed.
Bundled gems are installed into `./vendor/bundle`
```

**Comment by lildude** [comment]
It looks like you've skipped over the [Getting Started](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#getting-started) step. All the steps after that point assume you've already bootstrapped which installs all the missing gems.

**Comment by Alhadis** [comment]
@lildude It wouldn't hurt to check for `licensed` (and any other Gem executables) before running commands that modify the working tree. This would at least save hasty users from shooting themselves in the foot…

**Comment by alerque** [comment]
Thanks for the pointers. I wasn't so hasty as to not read the guide –and I did execute those steps– but the first grammar I tried to import did not go well for other unrelated reasons. I then ran a `git clean` that was a bit too aggressive.
