### ISSUE TITLE
Wren language support

### ISSUE THREAD

**Issue by BenStigsen** [github/linguist#5349]
## Language name
Wren

## URL of example repository
https://github.com/wren-lang/wren/

## URL of syntax highlighting grammar
There's a bunch of overlap with Lua, but here's the text editor "lite" syntax highlighting for Wren: https://raw.githubusercontent.com/franko/lite-plugins/master/plugins/language_wren.lua

## Most popular extensions
`.wren`

## Detected language
None

## Some Wren projects:
TIC-80: https://tic80.com/
DOME: https://github.com/domeengine/dome
Luxe: https://luxeengine.com/

**Comment by Nixinova** [comment]
Previous PRs #4088 #5151 were closed due to lack of usage on GitHub, however the extension may now be eligible as it has over [1K files](https://github.com/search?q=extension%3Awren).

**Comment by ruby0x1** [comment]
Note that we're (Wren + community) working on a proper updated language definition and will submit a new PR with that when it's time. This can be closed until then.
