### ISSUE TITLE
Add `RPG Maker MV` to the list.

### ISSUE THREAD

**Issue by wg481** [github/linguist#5403]
## Describe the enhancement
RPG Maker MV (technically MZ as well) should be added to the list.
<br>
I know it's not that big of a platform, but I think it would be nice. I would add it just as `RPG Maker` with the type being `data`. In the lineup, it would place directly after Ruby.

Supported filetypes exclusive to RPG Maker MV/MZ are:
 - RPGMVM (Encrypted Movie File)
 - RPGMVO (Encrypted Sound File)
 - RPGMVP (Encrypted Picture File)
 - RPGPROJECT (The Project file for every RPG Maker game)
 - RPGSAVE (save file)

For adding the RPG Maker tool series as a whole, and not under specific versions, include filetypes like:
 - R3PROJ (RPG Maker 2003 project)
 - RGSS2A (RPG Maker VX RGSS Encrypted Archive)
 - RGSS3A (RPG Maker VX Ace RGSS Encrypted Archive)
 - RGSSAD (RPG Maker VX RGSS Encrypted Archive)
 - LSD (RPG Maker Game Save File)
 - LSW (RPG Maker Saved Game File)
 - RVDATA/RVDATA2 (RPG Maker VX/Ace Data File)
 - LMU (RPG Maker Map File)
 - RVPROJ (RPG Maker VX/Ace Project File)
 - LMU (RPG Maker Map File)
 - LMT (RPG Maker Map File Tree)

It would be helpful for identifying projects rather than using OTHER as in the linguist section.

**Comment by Nixinova** [comment]
They look like binary files; Linguist only covers source (text-based) files and those extensions don't seem to be in use

**Comment by wg481** [comment]
From what languages.yml looks to be, it's a simple structure that detects file extensions.

**Comment by Nixinova** [comment]
It detects *languages*, not file extensions. If any of these are written in an actual language they can be added but if they are binary files (i.e. if you open one it's gibberish) they aelrent covered by this.

**Comment by lildude** [comment]
Linguist would never get to reading the `languages.yml` file thanks to this very early guard:

https://github.com/github/linguist/blob/757b173b34db14bc23c7b53a15252628add4f815/lib/linguist.rb#L22

So even if we added binary extensions, repos would never show a language for them rendering most (all?) of this PR useless.
