### ISSUE TITLE
Request adding Jamplate Preprocessor Language

### ISSUE THREAD

**Issue by LSafer** [github/linguist#5417]
## Language name
Jamplate

## URL of example repository
- repo: https://github.com/jamplate/examples
- webpage (with syntax highlighting): https://jamplate.org/examples.html

## URL of syntax highlighting grammar
Will be added in a future comment.
Here is the guide instead: https://jamplate.org/guide.html

## Most popular extensions

- `.jamplate`
- `.jh`

## Detected language

- `.jamplate` a Jamplate main file.
- `.jh` a Jamplate header file.

**Comment by Nixinova** [comment]
There's only [52 files](https://github.com/search?q=extension%3Ajamplate&type=code) of jamplate; Linguist doesn't add hobbyist languages.

**Comment by LSafer** [comment]
Ok, thank you 🥺💔
