### ISSUE TITLE
samples/C/main.c is not C but C++ file

### ISSUE THREAD

**Issue by e-kwsm** [github/linguist#5426]
## Describe the bug

https://github.com/github/linguist/blob/4184bbf8066d8aa908d437af6a58b46049fc3f8b/samples/C/main.c is not a C file and thus is inappropriate for a C sample; the file is actually a C++ file:
https://github.com/github/linguist/blob/4184bbf8066d8aa908d437af6a58b46049fc3f8b/samples/C/main.c#L17-L18

The file seems to be a previous version of https://github.com/v8/v8/blob/master/src/runtime/runtime-compiler.cc.

### Expected behaviour

samples/C should offer C files.

### Related discussion

The file is added in #2967.

**Comment by e-kwsm** [comment]
Is this intentional? I’m a bit confused.

**Comment by lildude** [comment]
Ooo, good catch. Yes, that appears to be a mistake and not intentional. I'll open a PR to move it.
