### ISSUE TITLE
Split `go.mod` and `go.sum` into their own language(s)

### ISSUE THREAD

**Issue by Nixinova** [github/linguist#5430]
## Description
Golang module source (`go.mod`) and lock (`go.sum`) files are currently registered as `Text` in Linguist (#4340) but this means that they don't get e.g. syntax highlighting.

[Example go.mod](https://github.com/sloppycoder/api-load-gen/blob/93f886500ad351d45ebc9e9812e5930cbbe0f396/go.mod)
[Example go.sum](https://github.com/yhkl-dev/base/blob/1c7b18bdaba3d2127dc600a9b408cd8bfca253a7/go.sum)

## Language name
![image](https://user-images.githubusercontent.com/42429413/128432333-11799213-567b-4218-b073-8e09585e80e8.png)

## URL of syntax highlighting grammar
[go.mod](https://github.com/microsoft/vscode-go/blob/master/syntaxes/go.mod.tmGrammar.json) ([lightshow][gomod])
[go.sum](https://github.com/microsoft/vscode-go/blob/master/syntaxes/go.sum.tmGrammar.json) ([lightshow][gosum])

## Detected language

![image](https://user-images.githubusercontent.com/42429413/122636758-07dcfc80-d13f-11eb-909d-9b4b1d68a55b.png)

  [gosum]: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvscode-go%2Fblob%2Fmaster%2Fsyntaxes%2Fgo.sum.tmGrammar.json&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fyhkl-dev%2Fbase%2Fblob%2F1c7b18bdaba3d2127dc600a9b408cd8bfca253a7%2Fgo.sum&code=

  [gomod]: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvscode-go%2Fblob%2Fmaster%2Fsyntaxes%2Fgo.mod.tmGrammar.json&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fsloppycoder%2Fapi-load-gen%2Fblob%2F93f886500ad351d45ebc9e9812e5930cbbe0f396%2Fgo.mod&code=

**Comment by Zerotask** [comment]
Examples how it looks locally in VS Code, using the official Go extension:

### go.mod
![image](https://user-images.githubusercontent.com/20150243/122644061-74da9d00-d113-11eb-9acf-78b9e443b39a.png)


### go.sum
![image](https://user-images.githubusercontent.com/20150243/122644079-95a2f280-d113-11eb-8693-2ffac04cc1ce.png)
