### ISSUE TITLE
Error in my code or linguist?

### ISSUE THREAD

**Issue by Coder2195Text** [github/linguist#5432]
https://github.com/Coder2195Text/space-chaos

Using gitattributes to remove false reporting node_modules and source, I only want the release to be reported.

However, after trying and failing I couldn't get them to hide node_modules and source in linguist-vendored, whats wrong with my code and/or linguist?

**Comment by lildude** [comment]
You've done nothing wrong and you don't even need an override as Linguist ignores node_modules by default. The only files being counted are those outside of that directory.

It's worth pointing out that Linguist has no control over Search which is what is still showing your files when you click JavaScript in the sidebar. If it did, you wouldn't be able to find any files Linguist ignores.

As this isn't a bug, I'm going to move this to discussions.
