### ISSUE TITLE
gitattributes not working

### ISSUE THREAD

**Issue by flack** [github/linguist#5439]
## Describe the bug

I have the following lines in `.gitattributes`:

https://github.com/flack/openpsa/blob/c19ae95c45782bebb38f6ad4a2113e6f1c4818cf/.gitattributes#L7-L16

unfortunately, linguist ignores them completely, both when I run it locally and on github, too.

### Expected behaviour

The listed folders should be excluded

### Additional notes

I have tried (locally) to remove all lines from `.gitattributes` and just add a single `static/* linguist-vendored`, but even that doesn't work. Clearly, I'm missing something, but I have no idea what, my code looks like all the examples I could find online

**Comment by flack** [comment]
Nevermind, I figured it out: You have to use `**` to actually exclude the subtree. Would be good to mention that in the docs

**Comment by lildude** [comment]
> Would be good to mention that in the docs

It is… in the gitattributes and gitignore docs (as this has nothing to do with Linguist; Linguist just takes advantage of the functionality). This has come up plenty times in the discussions and older issues. I think my comment at https://github.com/github/linguist/discussions/5175#discussioncomment-317382 provides a good overview and reference to all relevant docs and demonstrates how to check the attributes without involving Linguist.

**Comment by flack** [comment]
Yes, I know, it's mostly my problem. I've tried reading that git manual many times, but after a couple of lines my eyes just glaze over. Not sure if it's the layout or just this jargon filled writing style, but for the life of me I can't make sense of that and usually end up copy n pasting stuff from stackoverflow instead..

I do think though that you could reduce the load of confused tickets like mine if the documentation here 

https://github.com/github/linguist/blob/master/docs/overrides.md#documentation

would just use the more common case as an example. Most people probably will want to exclude the entire `project-docs/` tree and not just the files directly in that folder. So if the example would simply be changed to `project-docs/** linguist-documentation` copy n paste would have worked out of the box and I would never have had to bother you guys with this ticket. Also (at least for me), seeing `**` gives me a hint that this is basically working like paths in Grunt e.g., so I would have figured out the rest from there (while only seeing `*` kind of let me to believe it's working like globs on the Linux shell, because for my simple mind, linguist seems more like a tool that would iterate over files)

**Comment by eps1lon** [comment]
> It is… in the gitattributes and gitignore docs (as this has nothing to do with Linguist; Linguist just takes advantage of the functionality). 

@lildude Are you referring to the requirement of adding `**`? Because gitignore does not need that. If I add `src/` then every file in `src` will be ignored e.g. `src/module/index.js` will be ignored as well as `src/index.js`.
