### ISSUE TITLE
Update MATLAB-Language-grammar submodule

### ISSUE THREAD

**Issue by 4086606** [github/linguist#5465]
## Describe the enhancement

I overhauled the grammar @   mathworks/MATLAB-Language-grammar#38. Could someone sync the submodule here with my changes?

**Comment by lildude** [comment]
This happens automatically with every release. These is no point updating it any sooner as it won't be reflected on GitHub until then. I have seen your other comments and will update the grammar when I make the next release which I'm hoping to find time for some time this week.

Please be patient, there's only one of me and maintaining Linguist is not my primary role at GitHub.

Closing as there's nothing to do here.

**Comment by 4086606** [comment]
It's all right, thanks for your time and clarifying how this repository actually works
