### ISSUE TITLE
Language not being detected by linguist

### ISSUE THREAD

**Issue by jit-hin** [github/linguist#5470]
### Discussed in https://github.com/github/linguist/discussions/5467

<div type='discussions-op-text'>

<sup>Originally posted by **jit-hin** July 18, 2021</sup>
Consider my repo which is not yet completed: [username-generator](https://github.com/jit-hin/username-generator/).

The language used is *not detected* by linguist. I know that it will take time but after so many weeks also my old repo which was identical to the new one, it's language wasn't detected. 

I wanted to know if I am using minified JavaScript as I have read the conditions of linguist. Please do help me.

*Thanks!*</div>

**Comment by lildude** [comment]
Closing in favour of the discussion you opened yesterday. In future, please be patient and wait for a response rather than unnecessarily opening an issue.

**Comment by jit-hin** [comment]
Can you say what the problem is?
