### ISSUE TITLE
Heuristic to upgrade JSON to JSONC automatically

### ISSUE THREAD

**Issue by 4086606** [github/linguist#5478]
## Describe the enhancement

If there's a `// comment` in a JSON file, it should be automatically assumed that it's a Microsoft JSONC file.

**Comment by Alhadis** [comment]
No, that would render the distinction between JSON and JSONC completely useless.

**Comment by 4086606** [comment]
Ah I see. Alright will rely on `.gitattributes` instead.

`.gitattributes` example for posterity: https://github.com/microsoft/vscode/pull/129206/commits/9e0857e916632b306d047ad7324980bfa5b48fea
