### ISSUE TITLE
Add support for the smart contract language Clarity

### ISSUE THREAD

**Issue by 0xAsteria** [github/linguist#5486]
## Language name

Clarity

## URL of example repository

[syvita/sypool/miningpool](https://github.com/syvita/sypool/tree/main/packages/miningpool/contracts)
[friedger/clarity-friedger-pool](https://github.com/friedger/clarity-friedger-pool/tree/main/contracts)
[syvita/sypool/oracle](https://github.com/syvita/sypool/blob/main/packages/oracle/contracts/oracle.clar)
[psq/swapr](https://github.com/psq/swapr)
[arkadiko-dao/arkadiko](https://github.com/arkadiko-dao/arkadiko/tree/master/clarity/contracts)

## URL of syntax highlighting grammar

https://github.com/hirosystems/clarity-lsp

## Most popular extensions

`.clar`

## Detected language

None

**Comment by lildude** [comment]
Support was added in https://github.com/github/linguist/pull/5665
