### ISSUE TITLE
Bulk download of TextMate grammars

### ISSUE THREAD

**Issue by fabiospampinato** [github/linguist#5509]
## Describe the enhancement

There's an awesome list of TextMate grammars [here](https://github.com/github/linguist/tree/master/vendor), and I assume at some point the actual `*.tmLanguage` files need to be downloaded from those in order to make Linguist do its job at syntax highlighting, but I'm not being able to find a script for downloading all those in bulk, is there one already that I can't find? If there isn't one, wouldn't it be a nice improvement to add one?

**Comment by fabiospampinato** [comment]
Unpacking the github-linguist gem works well enough for me!

**Comment by lildude** [comment]
We convert the grammars into JSON for use by our syntax highlighting engines. A tarball is added to each release.
