### ISSUE TITLE
Unable to install on macOS Big Sur

### ISSUE THREAD

**Issue by schissmantics** [github/linguist#5549]
I'm getting a wrong classification in my [repo](https://github.com/schissmantics/xagents) 80% jupyter 20% python which is totally wrong, so I tried installation ...

## Describe the bug
I'm expecting this to install

    gem install github-linguist

For some reason, it complains about permissions:

    ERROR:  While executing gem ... (Gem::FilePermissionError)
        You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.
    user@user-MacBook-Pro ~ % 

So, I use sudo

    Password:
    Building native extensions. This could take a while...
    ERROR:  Error installing github-linguist:
	    ERROR: Failed to build gem native extension.
    
        current directory: /Library/Ruby/Gems/2.6.0/gems/charlock_holmes-0.7.7/ext/charlock_holmes
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20210902-2523-gsr8x4.rb extconf.rb
    checking for -licui18n... yes
    checking for unicode/ucnv.h... yes
    checking for -lz... yes
    checking for -licuuc... yes
    checking for -licudata... yes
    creating Makefile
    
    current directory: /Library/Ruby/Gems/2.6.0/gems/charlock_holmes-0.7.7/ext/charlock_holmes
    make "DESTDIR=" clean
    
    current directory: /Library/Ruby/Gems/2.6.0/gems/charlock_holmes-0.7.7/ext/charlock_holmes
    make "DESTDIR="
    compiling converter.c
    compiling encoding_detector.c
    compiling ext.c
    compiling transliterator.cpp
    In file included from transliterator.cpp:1:
    In file included from ./common.h:9:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby.h:33:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/ruby.h:24:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin20/ruby/config.h:415:31: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
    #define RUBY_ARCH "universal-"RUBY_PLATFORM_OS
                                  ^
                                   
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin20/ruby/config.h:416:35: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
    #define RUBY_PLATFORM "universal."RUBY_PLATFORM_CPU"-"RUBY_PLATFORM_OS
                                      ^
                                       
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin20/ruby/config.h:416:55: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
    #define RUBY_PLATFORM "universal."RUBY_PLATFORM_CPU"-"RUBY_PLATFORM_OS
                                                          ^
                                                           
    In file included from transliterator.cpp:1:
    In file included from ./common.h:9:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby.h:33:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/ruby.h:2111:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/intern.h:56:19: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
    void rb_mem_clear(register VALUE*, register long);
                      ^~~~~~~~~
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/intern.h:56:36: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
    void rb_mem_clear(register VALUE*, register long);
                                       ^~~~~~~~~
    2 warnings and 3 errors generated.
    make: *** [transliterator.o] Error 1
    
    make failed, exit code 2
    
    Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/charlock_holmes-0.7.7 for inspection.
    Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-20/2.6.0/charlock_holmes-0.7.7/gem_make.out

### Expected behaviour

Installation should work

**Comment by Nixinova** [comment]
> which is totally wrong

The ipynb file is a megabyte, which drowns out the python file count.

**Comment by schissmantics** [comment]
I'll close the issue because it seems irrelevant.

**Comment by Alhadis** [comment]
@schissmantics You can use an [override](https://github.com/github/linguist/blob/master/docs/overrides.md) to exclude `.ipynb` files from language statistics. Add this to a `.gitattributes` file (preferably located in the root of your project):

~~~gitattributes
*.ipynb linguist-vendored
~~~

See [_“Overrides”_](https://github.com/github/linguist/blob/master/docs/overrides.md#summary) for other useful overrides.
