### ISSUE TITLE
Incomplete syntax highlighting for the programming language Squirrel (.nut)

### ISSUE THREAD

**Issue by TheWitheredStriker** [github/linguist#5554]
Hello. I'm a novice GitHub user, and I apologize if this is in the wrong area or if I mislabeled it, but I didn't know where else to post this.

I saw that the syntax highlighting for the Squirrel programming language (file extension `.nut`) appears to be incomplete. 

For example, let's [take this file](https://github.com/MathyFurret/th155-decomp/blob/v1.10d/src/data/script/graphics.nut).

While keywords like `if`, `else` and `return` are highlighted fine, others, like `function` and `local`, are not.

While I'm not fully sure why this happens (I'm a novice coder after all), I _presume_ that this is because the highlighter for Squirrel appears to base itself off C or C++; not only is Squirrel interwoven with these languages in many of its implementations, but the keywords that __are__ highlighted are also found in C(++) whereas the ones that aren't are not found in those languages.

Of course, I can very well be mistaken, this is simply an observation I made. Either way, it does put me off, and I'd appreciate it if someone could look into this. Thanks in adance!

**Comment by Alhadis** [comment]
> I _presume_ that this is because the highlighter for Squirrel appears to base itself off C or C++; not only is Squirrel interwoven with these languages in many of its implementations, but the keywords that **are** highlighted are also found in C(++) whereas the ones that aren't are not found in those languages.

🤔 That code looks nothing like C. If I were to guess, I'd say there wasn't a better grammar for highlighting Squirrel source code at the time when support for it was added to Linguist.

So, your observation is correct—the grammar we're using for Squirrel isn't adequate, and a dedicated one is needed. Do you know of any? We can use any highlighting supported by VS Code, Atom, Sublime Text, or TextMate (technically, they're the same format).

**Comment by TheWitheredStriker** [comment]
After some searching, I found [the repository of a Squirrel TextMate file.](https://github.com/robmerrell/squirrel-tmbundle) Is this what we need, or do we need a different file?

**Comment by Alhadis** [comment]
We need a different file: I can't see a license in that repository, and we require grammars to be permissively-licensed (i.e., MIT, ISC, Apache, etc). The repository also appears to be unmaintained (it was last updated in 2011). This might be the reason it was never added to Linguist in the first place.

[There's this](https://github.com/mathewmariani/squirrel-language) though, which [solves your highlighting issue](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fgithub.com%2Fmathewmariani%2Fsquirrel-language%2Fblob%2Fmaster%2Fgrammars%2Fsquirrel.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2FMathyFurret%2Fth155-decomp%2Fv1.10d%2Fsrc%2Fdata%2Fscript%2Fgraphics.nut&code=) and has a [compatible license](https://github.com/mathewmariani/squirrel-language/blob/f6c254905951ceedb4622dd9e70f4eecb2388e15/LICENSE). Do you want to submit a pull-request, or should I?

**Comment by TheWitheredStriker** [comment]
Looks great! I'd prefer if you were to make the pull request, as I'm still a novice to GitHub (I'm advancing, though!) and am mostly unfamiliar with the inner workings of Linguist.

**Comment by Alhadis** [comment]
Okay, this is interesting... it appears that highlighting was already added in #3791, but the submitter of that PR forgot to update the `tm_scope` of Squirrel's language entry. As such, the `squirrel-language` grammar has been sitting unused in [`vendor/grammars/`](https://github.com/github/linguist/tree/master/vendor/grammars) for the past 4 years.

**Comment by TheWitheredStriker** [comment]
Oh damn. Hope it'll be addressed soon.

**Comment by TheWitheredStriker** [comment]
Would like to append a new discovery of mine; apparently [Squirrel files can also have the `.gnut` expression](https://github.com/Syampuuh/Titanfall2/blob/master/scripts/vscripts/gamemodes/cl_capture_point.gnut). They have no syntax highlighting. Is this something we can address, or does GitHub first need to be able to recognize this file extension?

**Comment by lildude** [comment]
> Oh damn. Hope it'll be addressed soon.

It'll be addressed when the next release is made. I don't have a date for this yet as it depends on my workload.

> Would like to append a new discovery of mine; apparently [Squirrel files can also have the `.gnut` expression](https://github.com/Syampuuh/Titanfall2/blob/master/scripts/vscripts/gamemodes/cl_capture_point.gnut). They have no syntax highlighting. Is this something we can address, or does GitHub first need to be able to recognize this file extension?

If usage meets our minimum requirements, support can be added for the extension (see CONTRIBUTING.md). Until then, you'll need to use an override.

**Comment by TheWitheredStriker** [comment]
Alright.

Several keywords like `function` and `local` are still not highlighted for me. Is this normal?

**Comment by lildude** [comment]
> Several keywords like `function` and `local` are still not highlighted for me. Is this normal?

I wouldn't think so as GitHub is still using the C++ grammar as https://github.com/github/linguist/pull/5556 hasn't been merged yet let alone deployed to GitHub.com. 

If we use the file you mentioned before, it'll look like [this](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fmathewmariani%2Fsquirrel-language%2Fblob%2Fmaster%2Fgrammars%2Fsquirrel.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2FSyampuuh%2FTitanfall2%2Fblob%2Fmaster%2Fscripts%2Fvscripts%2Fgamemodes%2Fcl_capture_point.gnut&code=) once #5556 has been merged and deployed to GitHub.com. It doesn't look quite right so you'd need to take up any further syntax highlighting issues with the grammar maintainer or find a better grammar and submit a PR to switch to the better grammar.

**Comment by TheWitheredStriker** [comment]
Alright. Noted.

**Comment by TheWitheredStriker** [comment]
So just to be sure: [is this the grammar we're using now?](https://github.com/mathewmariani/squirrel-language)

**Comment by Alhadis** [comment]
@TheWitheredStriker Yes. You can find the complete list at [`vendor/README.md`](https://github.com/github/linguist/blob/master/vendor/README.md).

**Comment by TheWitheredStriker** [comment]
Hm, odd. I find it bizarre that it highlights `local` and `function` correctly in the preview you linked, but not on the actual repository after the approval of the PR.

**Comment by lildude** [comment]
Why is it bizarre? I've explained this in my [comment above](https://github.com/github/linguist/issues/5554#issuecomment-913782365) - now with added emphasis:

> I wouldn't think so as **GitHub is still using the C++ grammar** as #5556 hasn't been merged yet let alone **deployed to GitHub.com.**
> 
> If we use the file you mentioned before, it'll look like [this](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fmathewmariani%2Fsquirrel-language%2Fblob%2Fmaster%2Fgrammars%2Fsquirrel.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2FSyampuuh%2FTitanfall2%2Fblob%2Fmaster%2Fscripts%2Fvscripts%2Fgamemodes%2Fcl_capture_point.gnut&code=) once #5556 has been merged and **deployed to GitHub.com**.

The PR has been merged but not yet deployed to GitHub.com. Changes only appear on GitHub.com when I make a new Linguist [release](https://github.com/github/linguist/releases) and as you can see, I've not made one since 4 Aug so any PRs merged since then, including #5556, will **not** affect what you see on GitHub.com.

I don't know when I'll be making the next release as it depends on my primary workload.

**Comment by TheWitheredStriker** [comment]
Oooh. Woops, my bad  😅   apologies for that
