### ISSUE TITLE
Proposal: Add `.code-snippets`

### ISSUE THREAD

**Issue by Yash-Singh1** [github/linguist#5574]
## Describe the enhancement

`.code-snippets` files are just JSONC and are used by vscode to have custom autocompletion to snippets. There are almost 17K results on GitHub for this file extension: https://github.com/search?q=extension%3Acode-snippets.

**Comment by Nixinova** [comment]
Seems like it should be JSON<ins>C</ins> https://github.com/sjydevildaum/TIS20210905/blob/7d348c96d9ecebb7cf9e6a130f07ab837a3a9e8b/.vscode/react.code-snippets
