### ISSUE TITLE
Add language: Mermaid Diagram Support

### ISSUE THREAD

**Issue by Yash-Singh1** [github/linguist#5578]
## Language name

MermaidJS

## URL of example repository

https://github.com/lotusnprod/lotus-processor/blob/f46c20768fa80e8fe6c438424323734f547f6163/docs/flowchart.mmd

## URL of syntax highlighting grammar

WIP

## Most popular extensions

`.mmd`

## Detected language

N/A

## Popularity

https://github.com/search?p=1&q=extension%3Ammd&type=Code (6K Results)

**Comment by lildude** [comment]
Please note, Linguist can only add support for syntax highlighting of the files (I'm not sure how useful that would be) assuming a grammar can be found. Rendering to show the images would need to be implemented elsewhere.

**Comment by Yash-Singh1** [comment]
> assuming a grammar can be found

I am currently working on a text mate grammar, so I’ll create a PR after I am done with that.

**Comment by lildude** [comment]
I think https://github.com/bpruitt-goddard/vscode-mermaid-syntax-highlight should do the trick for syntax highlighting

**Comment by Alhadis** [comment]
I've never seen [this syntax](https://github.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/blob/7d71f36b01d62fd26610b32eab1e104971b9cbed/syntaxes/mermaid.tmLanguage.yaml#L6-L9) before. Is `!!import/deep` a YAML thing?

~~~yaml
repository:
  mermaid:
    patterns: !!import/deep
      - diagrams/
~~~

Doesn't look like a valid TextMate-compatible grammar to me. It might rely on a build-step or something…

**Comment by Alhadis** [comment]
Want me to write one? I'm already halfway through taking apart Mermaid's own Monaco-based highlighter to see how it works. I've reduced it to a list of keywords and patterns, so smashing something together shouldn't be too difficult.

**Comment by lildude** [comment]
> Want me to write one?
> [...]
> **EDIT:** Wait, Mermaid is, like, _10_ different syntaxes hiding under a trench-coat pretending to be a single language. I can write a grammar for it, but I probably won't be done in time for the next Linguist release. 😅

Go for it if you want the challenge and no rush. I thought it would be a quick addition when I found the grammar.

> All I ask in return is that GitHub support [Pikchr](https://pikchr.org/home/doc/trunk/homepage.md) so we can use [pic(1)](https://github.com/github/linguist/blob/e78ef71af3600f96b9a40a06511ebbe3797e7401/lib/linguist/languages.yml#L4795-L4805) on GitHub. 😁

Ask in the Product Feedback section of https://github.com/orgs/community/discussions/ and you never know, your wish may come true one day 😁

**Comment by Alhadis** [comment]
Track progress here: https://github.com/Alhadis/language-mermaid

I'll submit a PR once I've finished splattering mermaids.
