### ISSUE TITLE
Available language colors

### ISSUE THREAD

**Issue by timo-cmd2** [github/linguist#5583]
## Get available colors for new languages 

Hello, is there a more efficient solution for getting available language colors than just manually crawling the colors tool by @lildude ?

And, how will the management go over, when there are more languages than color codes? Will languages have same colors?

Thanks and best regards

Timo Sarkar

**Comment by lildude** [comment]
There is no longer a restriction in colour choice, so pick whatever colour is best suited, though we recommend sticking to official branding colours to reduce unnecessary churn or unhappy users. Yes, languages will share colours but it's rare for two languages used together to have the same colour.

**Comment by Alhadis** [comment]
As @lildude pointed out:

> There is no longer a restriction in colour choice,

This restriction was abolished in #4978, so the set of "available" colours is logically equivalent to the universal set.

Closing this as there isn't really anything to do here.
