### ISSUE TITLE
Proposal: Procfile language

### ISSUE THREAD

**Issue by Yash-Singh1** [github/linguist#5593]
## Language name

Procfile

## URL of example repository

https://github.com/heroku/typescript-getting-started

## URL of syntax highlighting grammar

https://github.com/benspaulding/vscode-procfile/blob/main/syntaxes/procfile.tmLanguage.json

## Most popular extensions

N/A

## Detected language

None

## More information

https://devcenter.heroku.com/articles/procfile

Procfiles define data on commands to run when a process is initialized and is used by a few hosting platforms.

Results: 653K (https://github.com/search?q=filename%3AProcfile)

**Comment by CertifiedRice** [comment]
I added it to the linguist file [PR](https://github.com/github/linguist/pull/5762)
