### ISSUE TITLE
No syntax highlighting in rust when a # is found.

### ISSUE THREAD

**Issue by RpxdYTX** [github/linguist#5624]
## Describe the bug

In Rust there are attribute like macros that start with `#` and raw strings, chars and keyword escaping that use the `r#` characters, but  when using them, they are not highlighted correctly, such as:

```rust
#[allow (dead_code)]
//or
#![allow (dead_code)] //for the parent
```
Or:
```rust
pub fn r#async (&self) {...}
```

Are just white (the exceptions are raw strings).

### Expected behaviour

The right syntax highlighting, like, for attributes, the colors for macros could be used, and for escaped keywords the actual context should be used (in that example it would be the function highlighting).

### Related discussion

None, sorry for not opening a discussion before this issue.

### Additional notes

Also none.

**Comment by lildude** [comment]
Please take this up with the grammar maintainers as advised in the [troubleshooting doc](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#theres-a-problem-with-the-syntax-highlighting-of-a-file).

Closing as this is not a problem with Linguist but rather with the external grammar.
