### ISSUE TITLE
Word diff

### ISSUE THREAD

**Issue by rxaviers** [github/linguist#5639]
Hi all, my assumption is that [syntax highlighting](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) we find on GitHub comments use this repo as render engine. Sorry if it isn't the right place to post this sort of issue/request or if I am missing something.

## Describe the enhancement

Today, it's possible to show diff syntax highlight.

````
```diff
- A
+ B
```
````

```diff
- A
+ B
```

But, it's not possible to show a (it's missing a) per-word or per-character diff syntax highlight.

````
```diffperch
- recieve
+ receive
```
````

Expected:

![Screen Shot 2021-11-08 at 14 14 37](https://user-images.githubusercontent.com/967155/140787579-d88c360c-2065-4e86-80b5-801576b87cbd.png)

**Comment by lildude** [comment]
> Hi all, my assumption is that syntax highlighting we find on GitHub comments use this repo as render engine.

Unfortunately not. Linguist only provides the grammars used by the syntax highlighting. The actual rendering is performed by https://github.com/github/markup and it would need to be enhanced to perform the per-character diff rendering.

**Comment by rxaviers** [comment]
Thank you
