### ISSUE TITLE
.mlx not classified as MATLAB code

### ISSUE THREAD

**Issue by LCRuth** [github/linguist#5644]
Hi!  It looks like MATLAB LiveScript files (.mlx) are not classified as MATLAB.  Only .m and .matlab are classified as MATLAB, as shown here in languages.yml: 
https://github.com/github/linguist/blob/e2f638d17598e84f6f91c2d03c2f3e27f22a2163/lib/linguist/languages.yml
**Could you add .mlx to list of extensions classified by linguist as MATLAB code?**

Example projects classified as 100% MATLAB, where the classification only comes from the .m file, not the .mlx file (apparent after clicking on "MATLAB 100%" at the bottom right):  
https://github.com/gh-BumsooKim/DeepLearning-MATLAB
https://github.com/cuixing158/yoloX-yoloV5-onnx-matlab

My project, which is primarily MATLAB LiveScript (.mlx); but MATLAB is not included in the code classification, only TeX, since linguist doesn't recognize .mlx: https://github.com/LCRuth/4noteGuitarChordModulationExercise

Thank you!  (I'm a n00b here, let me know if I should be going about this differently!)

**Comment by Nixinova** [comment]
MLX files don't seem to be plaintext. Is that right? Only text-based languages get support in Linguist as GitHub ignores non-text files when applying language statistics.

**Comment by lildude** [comment]
Yup, they're identified as "Microsoft OOXML" which means they're technically zipped XML files:

```console
$ file FourNoteGuitarModulationExercise.mlx
FourNoteGuitarModulationExercise.mlx: Microsoft OOXML
$ unzip -c FourNoteGuitarModulationExercise.mlx | head -1
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default ContentType="application/vnd.openxmlformats-package.relationships+xml" Extension="rels"/><Default ContentType="application/vnd.mathworks.matlab.code.document+xml" Extension="xml"/><Override ContentType="text/xml" PartName="/matlab/output.xml"/><Override ContentType="application/vnd.openxmlformats-package.core-properties+xml" PartName="/metadata/coreProperties.xml"/><Override ContentType="application/vnd.mathworks.package.coreProperties+xml" PartName="/metadata/mwcoreProperties.xml"/><Override ContentType="application/vnd.mathworks.package.corePropertiesExtension+xml" PartName="/metadata/mwcorePropertiesExtension.xml"/><Override ContentType="application/vnd.mathworks.package.corePropertiesReleaseInfo+xml" PartName="/metadata/mwcorePropertiesReleaseInfo.xml"/></Types><?xml version="1.0" encoding="UTF-8" standalone="yes" ?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Target="matlab/document.xml" Type="http://schemas.mathworks.com/matlab/code/2013/relationships/document"/><Relationship Id="rId2" Target="matlab/output.xml" Type="http://schemas.mathworks.com/matlab/code/2013/relationships/output"/><Relationship Id="rId3" Target="metadata/mwcoreProperties.xml" Type="http://schemas.mathworks.com/package/2012/relationships/coreProperties"/><Relationship Id="rId4" Target="metadata/mwcorePropertiesExtension.xml" Type="http://schemas.mathworks.com/package/2014/relationships/corePropertiesExtension"/><Relationship Id="rId5" Target="metadata/mwcorePropertiesReleaseInfo.xml" Type="http://schemas.mathworks.com/package/2019/relationships/corePropertiesReleaseInfo"/><Relationship Id="rId6" Target="metadata/coreProperties.xml" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties"/></Relationships><?xml version="1.0" encoding="UTF-8"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:pPr><w:pStyle w:val="text"/><w:jc w:val="left"/></w:pPr><w:r><w:t>Put M, m, hm, hM into matrix. Find 4-note chords, printing intervals, key, mode, scale, and notes.</w:t></w:r></w:p><w:p><w:pPr><w:pStyle w:val="code"/></w:pPr><w:r><w:t><![CDATA[M=[2 2 1 2 2 2 1];  %Major
$
```

More deets on the format at https://uk.mathworks.com/help/releases/R2016a/matlab/matlab_prog/live-script-file-format.html

Zip can't be read as-is so are treated as binaries are so are ignored when it comes to to analysing for languages. We can't change this, as such I'm closing this issue.
