### ISSUE TITLE
React js and React typescript 

### ISSUE THREAD

**Issue by codewithpom** [github/linguist#5655]
## Describe the enhancement

So I was thinking that instead of reporting tsx  and jsx files as Typescript and Javascript I wish if they could be like Javascript react or Javascript Typescript.
Thanks

**Comment by Alhadis** [comment]
[React and JSX aren't the same thing](https://betterprogramming.pub/how-to-use-jsx-without-react-21d23346e5dc). Moreover, this would require us to discriminate between JavaScript and JSX, something which has been notoriously unreliable in the past (see #3677).
