### ISSUE TITLE
Switch to maintained PHP syntax highlighter

### ISSUE THREAD

**Issue by ondrejmirtes** [github/linguist#5668]
## Describe the enhancement

It seems like Linguist is using this repository https://github.com/textmate/php.tmbundle for its PHP syntax highlighting.

There has been a pull request open for highlighting PHP 8.0 features for more than a year: https://github.com/textmate/php.tmbundle/pull/88

Are the maintainers of Linguist interested in switching to a fork of that repository which would be more actively maintained? PHP 8.1 is now out with even more keywords to be highlighted, and it'd be great to be up-to-date.

I could create the fork and maintain it. Thanks.

**Comment by lildude** [comment]
> Are the maintainers of Linguist interested in switching to a fork of that repository which would be more actively maintained?

Definitely! Go for it and send us a PR to change there source we use.

**Comment by ondrejmirtes** [comment]
My PR has been merged, thank you :)
