### ISSUE TITLE
Better instructions for how to run a local version of linguist

### ISSUE THREAD

**Issue by tobega** [github/linguist#5675]
I would like to run a locally enhanced version of linguist for our in-house adventofcode event, using some languages that are not popular enough to add to the main version.

I cannot understand from the contributing instructions how to run the local version on any other directory than the linguist directory.

**Comment by lildude** [comment]
Whoops, no idea how I've missed this until now. Sorry.

it's probably a bit late now, but Linguist takes an optional file or directory as an argument:

https://github.com/github/linguist/blob/4ffcdbcbb60a74cbfbd37656bcc3fcea4eca8e26/bin/github-linguist#L12-L18

… which means you can run locally from the cloned repo to check another repo:

```
bundle exec bin/github-linguist /path/to/a/git/repo
```
