### ISSUE TITLE
HTTP parser doesn't parse responses correctly

### ISSUE THREAD

**Issue by dorianmariefr** [github/linguist#5699]
## Describe the bug

If I do `curl -I https://www.google.com` for instance, it starts with

```http
HTTP/2 200 
content-type: text/html; charset=ISO-8859-1
...
```

You can see I used the `http` language here and it's marking red the first line.

### Expected behaviour

It syntax highlight the HTTP response correctly

### Additional notes

Found via those tweets https://twitter.com/jankomarohnic/status/1473547382143045632

**Comment by lildude** [comment]
As per the specific section in the [troubleshooting doc](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#theres-a-problem-with-the-syntax-highlighting-of-a-file), please report this in the upstream grammar repo.

Closing as this is an issue with the upstream grammar and not Linguist.

**Comment by dorianmariefr** [comment]
oops, opening the issue there
