### ISSUE TITLE
Change the color of mcfunction.

### ISSUE THREAD

**Issue by ClientCrash** [github/linguist#5703]
The current color has nothing to do with minecraft or the command functionality.
I suggest changing it so something more fitting like #1DB53C (the color of the creeper face logo often used by mojang, it also looks very similar to the grass texture color).

**Comment by ClientCrash** [comment]
Since I don't think the mcfunction files or commands have a logo or even a color, it is appropriate to change them to a color that is even remotely related to the purpose and use cases of the language.

**Comment by Nixinova** [comment]
Linguist doesnt change colours (even bad colours) without consensus from that language's community, so if you want it changed you'd need to post a poll or something somewhere visible to mcfunction creators.

**Comment by Nixinova** [comment]
this and #5705 should be closed
