### ISSUE TITLE
[bug][PHP]: uppercase namespace parts are highlighted differently in preview

### ISSUE THREAD

**Issue by azjezz** [github/linguist#5707]
## Describe the bug

the last part of the namespace in use statements in PHP are highlighted different if they only contain uppercase letters:

( In https://github.com/azjezz/hack-php-async-io/blob/3b44c06a2a486733cd9796289f01bf00dccd8655/src/main.php )
![image](https://user-images.githubusercontent.com/29315886/147367851-eaebf8b7-beea-4b59-b308-a0169480d272.png)

This behavior is also present when using the namespace:

( In https://github.com/azjezz/hack-php-async-io/blob/3b44c06a2a486733cd9796289f01bf00dccd8655/src/main.php#L15 )
![image](https://user-images.githubusercontent.com/29315886/147367874-cf43b7a3-c492-4ea6-99d0-30ab779ae9f4.png)

The weird thing is that this doesn't happen when editing the file, but only when viewing it:

![image](https://user-images.githubusercontent.com/29315886/147367915-941fa23f-ce95-4afc-92e0-fe2837404bca.png)

### Expected behaviour

The last part of the namespace should be highlighted in the same color regardless if it contains only uppercase letters, or a mix of uppercase, lowercase, underscore, and numbers.

### Related discussion

N/A

### Additional notes

N/A

**Comment by Iphone530** [comment]
message TEKSignatureList {
  signatures: [
    TEKSignature {
      signature_info:
        SignatureInfo {
          verification_key_id: "310"
          verification_key_version: "v1"
          signature_algorithm: "1.2.840.10045.4.3.2"
        }
      signature: [...] // signature byte contents using key version 1
    },
  ]
}

**Comment by Alhadis** [comment]
From [the troubleshooting docs](https://github.com/github/linguist/blob/e4599a93152a29a650b1e48722e5d2ba465acb0d/docs/troubleshooting.md#theres-a-problem-with-the-syntax-highlighting-of-a-file):

> Linguist detects the language of a file but the actual syntax-highlighting is powered by […] a set of submodules [as listed here](https://github.com/github/linguist/blob/master/vendor/README.md). […] If you experience an issue with the syntax-highlighting on GitHub, **please report the issue to the upstream grammar repository, not here.**

For PHP highlighting, Linguist uses @ondrejmirtes's [fork of `textmate/php.tmbundle`](https://github.com/ondrejmirtes/php.tmbundle). This was switched quite recently to fix another issue (see #5677). Now, normally I'd recommend filing an issue upstream, but @ondrejmirtes hasn't enabled the Issues tab on his fork. Hence we'll have to wait for his response to this thread.

**Comment by ondrejmirtes** [comment]
Hello, I'm heavily invested in PHP's future and awesomeness and good highlighting on GitHub is definitely part of that. The reason why I turned off issues on my php.tmbundle fork is that I'm really busy with my current projects (mostly PHPStan and related libraries like Roave/BetterReflection).

I promise I'll be responsive with reviewing and testing any incoming PRs, much more than the owners of the original repo were, but I can't fix these bugs myself. Thank you for understanding.

**Comment by lildude** [comment]
@ondrejmirtes so how are you going to take feedback and issues like this? Issues like this don't belong in the Linguist repo as it's not an issue with Linguist.

**Comment by ondrejmirtes** [comment]
@lildude I'll gladly test and accept any PRs with fixes, otherwise I'm not really interested in bug reports. The person reporting the bug can and should look into fixing it instead.

I can modify the README to reflect this.

**Comment by lildude** [comment]
🤔 that seems at odds with your "I'm heavily invested in PHP's future and awesomeness and good highlighting on GitHub is definitely part of that." comment, but that's your choice.

Over to you @azjezz.

Closing this issue as it's not a Linguist issue.
