### ISSUE TITLE
Broken TypeScript syntax highlighting with generics inside template literal types

### ISSUE THREAD

**Issue by KnorpelSenf** [github/linguist#5737]
## Describe the bug

At https://github.com/grammyjs/grammY/blob/f4cfb5563c6ac1e8a160d79ce5490013cd1895dc/src/filter.ts#L323, you can see that the syntax highlighting stops working in the middle of a source file. It looks like all highlighting works until a type with type parameters is encountered inside a template literal string.

A few hundred lines of the file are highlighted in the same colour. Sometimes, the highlighting comes back eventually, such as in the file linked above.

In other case, it does not, as a very old version of the same file illustrates: https://github.com/grammyjs/grammY/blob/fedd181bf0f5ac898a7e8d2e56e81778b3bd0694/deno/src/filter.ts

### Expected behaviour

I expect that all typescript syntax can be highlighted correctly.

### Related discussion

N/A

### Additional notes

I am not entirely sure if this is the right place to report that the site's syntax highlighting is broken. Feel free to enlighten me about where else to report this issue.

**Comment by lildude** [comment]
As per the section dedicated to this in the [troubleshooting docs](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#theres-a-problem-with-the-syntax-highlighting-of-a-file), this is a problem with the grammar and not Linguist. Please report this with the upstream grammar.

Closing as this is not a problem with Linguist.
