### ISSUE TITLE
Add systemd

### ISSUE THREAD

**Issue by sebdanielsson** [github/linguist#5750]
## Language name
systemd

## URL of example repository
https://github.com/slackhq/nebula/blob/master/examples/service_scripts/nebula.service

## URL of syntax highlighting grammar
https://www.freedesktop.org/software/systemd/man/systemd.syntax.html

## Most popular extensions
.service

### Full list of systemd unit files:
systemd.unit(5), systemd.service(5), systemd.socket(5), systemd.device(5), systemd.mount(5), systemd.automount(5), systemd.swap(5), systemd.target(5), systemd.path(5), systemd.timer(5), systemd.slice(5), systemd.scope(5), systemd.nspawn(5)

## Detected language
None

**Comment by papapathe** [comment]
Hey, i would like to work on this. Where should i start ?

**Comment by CertifiedRice** [comment]
@papapathe you can add it [here](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml)

**Comment by lildude** [comment]
@papapathe all the details you need for adding support are in the [CONTRIBUTING.md file](https://github.com/github/linguist/blob/master/CONTRIBUTING.md)

**Comment by CertifiedRice** [comment]
I have added support in #5767 , Please review it 😄
