### ISSUE TITLE
TypeScript grammar does not properly highlight template literal types

### ISSUE THREAD

**Issue by sam-goodwin** [github/linguist#5794]
## Describe the bug
Sorry if this is the wrong place, I couldn't find a more relevant repository.

GitHub syntax highlighting is incorrectly handling template literal types:
<img width="375" alt="image" src="https://user-images.githubusercontent.com/38672686/154825214-ea72288e-2e2f-425d-8fc6-8de2db6e77f8.png">

### Expected behaviour
It should render the same as VS Code does:
<img width="437" alt="image" src="https://user-images.githubusercontent.com/38672686/154825241-bdf1d38e-d1d3-464b-ad98-2713bcb8dd21.png">

### Additional Notes

It looks like the grammar is displaying all content after the backtick as a String.

**Comment by Alhadis** [comment]
To quote [our troubleshooting docs](https://github.com/github/linguist/blob/e4599a93152a29a650b1e48722e5d2ba465acb0d/docs/troubleshooting.md#theres-a-problem-with-the-syntax-highlighting-of-a-file):

> Linguist detects the language of a file but the actual syntax-highlighting is powered by a set of language grammars which are included in this project as a set of submodules [as listed here](https://github.com/github/linguist/blob/e4599a93152a29a650b1e48722e5d2ba465acb0d/vendor/README.md).
>
> If you experience an issue with the syntax-highlighting on GitHub, **please report the issue to the upstream grammar repository, not here.** Grammars are updated every time we build the Linguist gem so upstream bug fixes are automatically incorporated as they are fixed.

For TypeScript, Linguist is using [`tree-sitter/tree-sitter-typescript`](https://github.com/tree-sitter/tree-sitter-typescript) for highlighting. I recommend filing this issue there.

Closing this as it's unrelated to Linguist.
