### ISSUE TITLE
How to convert from textmate to tree sitter

### ISSUE THREAD

**Issue by lpil** [github/linguist#5805]
Hello!

Gleam has a tree sitter grammar that's of a higher quality than the existing textmate one. Is there a process for upgrading to use the tree-sitter grammar?

Thanks,
Louis

**Comment by lpil** [comment]
Thank you

**Comment by asymmetric** [comment]
@lpil has the switch happened? Asking because I'm interested in doing the same for Nix (assuming GitHub doesn't already use the [tree-sitter-based grammar](https://github.com/cstrahan/tree-sitter-nix/)).

**Comment by lpil** [comment]
It has, someone at GitHub got in touch and helped us out here.

**Comment by sambacha** [comment]
> @lpil has the switch happened? Asking because I'm interested in doing the same for Nix (assuming GitHub doesn't already use the [tree-sitter-based grammar](https://github.com/cstrahan/tree-sitter-nix/)).

FYI @asymmetric tree-sitter grammar is used for nix as well!
