### ISSUE TITLE
Add support for Internet shortcuts

### ISSUE THREAD

**Issue by DaCuteRaccoon** [github/linguist#5836]
## Language name
URL

## URL of example repository
[DaCuteRaccoon/languages](https://github.com/DaCuteRaccoon/languages/blob/main/langs/URLS.url)

## URL of syntax highlighting grammar
It's similar to TOML and the same as INI. My editor is Notepad++, and they just use "MS ini file" as their syntax highlighting. **So just use *the syntax highlighting of ini*.**

## Most popular extensions
```.url```
I'm not aware of any other extensions other than url.

## Detected language
I don't know what you mean by "detected language," but I'm assuming you mean the type of language (as of [languages.yml](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml)). It's data.

**Comment by Alhadis** [comment]
> I don't know what you mean by "detected language," but I'm assuming you mean the type of language (as of [languages.yml](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml)). It's data.

We use the term _"language"_ to apply to any textual file-format recognised by GitHub: markup languages, scripts, source code, plain-text databases, config files, etc.

**Comment by Nixinova** [comment]
> I don't know what you mean by "detected language,"

This is asking what language the files are currently detected as. Which is null right now.
