### ISSUE TITLE
C++ highlighting fails to highlight certain comma/modulo-heavy code

### ISSUE THREAD

**Issue by Qix-** [github/linguist#5841]
Sorry for the cruddy title, I don't really know the root cause so I made a best effort guess. Feel free to edit it.

## Describe the bug
The following valid C++ code completely breaks highlighting, namely for the strings:

```c++
auto cli = (
	option("--help").set(show_help)
		% "Show this help message",
	(option("-J", "--threads") & value("num_threads", num_threads))
		% "The number of threads to use (default 0, meaning 'auto')",
	value("db_dir").set(dbdir).required(true).blocking(true)
		% "The database directory location",
	any_other(invalid_params)
);
```

### Expected behaviour
Strings are highlighted correctly, the other `option` calls highlight purple, etc.

### Related discussion
None.

### Additional notes
None.

**Comment by Nixinova** [comment]
Linguist doesn't handle highlighting directly; this is done by external repos as listed in the [vendor/readme.md](https://github.com/github/linguist/tree/master/vendor#readme) file. For C++ the repo is https://github.com/textmate/c.tmbundle. Repost this issue there.
