### ISSUE TITLE
.ts files tracked as js by github search

### ISSUE THREAD

**Issue by StringManolo** [github/linguist#5842]
.ts files shown as javascript in search results

https://github.com/StringManolo/gclb.ts/search?l=JavaScript

I have a .gitattribute file that works fine for the repo stats, but not for the search.
```bash
*.ts linguist-language=TypeScript
```

They are being tracked as js because they have a node shebang.

**Comment by Nixinova** [comment]
See #5251 for why the shebang makes it JavaScript.
For the search classification, classifications are cached so any changes to gitattributes aren't loaded until the file in question is edited. *(Search is also screwy in many ways and is currently in beta for an overhaul.)*

**Comment by regan-karlewicz** [comment]
You can replace the shebang at build time to solve this issue with no special config:  https://github.com/github/linguist/issues/5251#issuecomment-1138955138
