### ISSUE TITLE
Add support for Overpass QL language

### ISSUE THREAD

**Issue by FloEdelmann** [github/linguist#5890]
## Language name

"Overpass QL" or "Overpass Query Language"
https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL

## URL of example repository

* https://github.com/KDE/syntax-highlighting/blob/42a061b04c507de11b0fb240808fc65a7528d946/autotests/input/highlight.overpassql
* https://github.com/Teiron/OverpassQL.tmLanguage/tree/4429a1e84a93407cd8355178e02f96d6b1000ca3/overpass/tests

## URL of syntax highlighting grammar

* https://github.com/KDE/syntax-highlighting/blob/42a061b04c507de11b0fb240808fc65a7528d946/data/syntax/overpassql.xml
* https://github.com/tqdv/vscodium-overpassql-syntax
* https://github.com/Teiron/OverpassQL.tmLanguage

## Most popular extensions

* `*.overpassql`
* `*.overpass`

## Detected language

Currently detected as plain text.

---

**EDIT:** I now keep track of all repos using `*.overpassql` and those where I suggested renaming in a GitHub project: [github.com/users/FloEdelmann/projects/2/views/2](https://github.com/users/FloEdelmann/projects/2/views/2)

**Comment by Nixinova** [comment]
There's only [6](https://github.com/search?q=extension%3Aoverpassql&type=code) .overpassql files and [26](https://github.com/search?q=extension%3Aoverpass&type=code) .overpass files. That's not enough for inclusion if those are the only filenames used by this lang.

**Comment by FloEdelmann** [comment]
It looks like the following file extensions are also used, but they are also used for other file types:

* [104k](https://github.com/search?q=extension%3Aosm&type=Code) `*.osm` files (currently detected as XML), but most seem to be [OSM XML files](https://wiki.openstreetmap.org/wiki/OSM_XML).
  <details>
  <summary>At least 74 examples where it's used as Overpass QL</summary>

  - https://github.com/ldodds/osm-queries/search?q=extension%3Aosm (45 files)
  - https://github.com/herver1971/AreasNaturales/tree/master/Consultas (16 files)
  - https://github.com/wireguy/SouthofMadagascarDrought/search?q=extension%3Aosm (5 files)
  - https://github.com/ldodds/overpass-doc/search?q=extension%3Aosm (2 files)
  - https://github.com/XuluniX/javaMaps/search?q=extension%3Aosm (2 files)
  - https://github.com/wireguy/overpass (2 files)
  - https://github.com/makatony/mapMapping/blob/master/query.osm (1 file)
  - https://github.com/cb-cities/sf_abm/blob/master/0_network/data/sf/query.osm (1 file)

  </details>

* [139k](https://github.com/search?q=extension%3Aql) `*.ql` files (currently detected as CodeQL), but most seem to be CodeQL files.
  <details>
  <summary>At least 145 examples where it's used as Overpass QL</summary>

  - https://github.com/drolbr/Overpass-API/search?q=extension%3Aql (49 files)
  - https://github.com/ThomasG77/30DayMapChallenge/search?q=extension%3Aql (21 files)
  - https://github.com/GISdevio/OSM-Accessibility-Data/search?q=extension%3Aql (13 files)
  - https://github.com/elgaard/OpenStreetmapTools/search?q=extension%3Aql (11 files)
  - https://github.com/simboli/Cookbook-Open-Street-Map/search?q=extension%3Aql (9 files)
  - https://github.com/wodo/alpine-explorer/search?q=extension%3Aql (9 files)
  - https://github.com/jstratman/jstratman.github.io/search?q=extension%3Aql (7 files)
  - https://github.com/TestBigOrg/overpass-queries/search?q=extension%3Aql (6 files)
  - https://github.com/Devops555/ikhaat/search?q=extension%3Aql (3 files)
  - https://github.com/openstreetmap-polska/vip/search?q=extension%3Aql (2 files)
  - https://github.com/ripsawridge/trips/search?q=extension%3Aql (2 files)
  - https://github.com/meyermarcel/overpass-api-examples/search?q=extension%3Aql (2 files)
  - https://github.com/MarcelloPerathoner/hikemap/blob/master/scripts/overpass.ql (1 file)
  - https://github.com/Kacperos155/Mapa-Lini-Kolejowych/blob/master/Mapa%20lini%20kolejowych/Overpass%20data/Overpass%20query.ql (1 file)
  - https://github.com/mapbox/wikimama/blob/master/query.ql (1 file)
  - https://github.com/open-austin/austin-park-equity/blob/master/data/scripts/osm-parks.ql (1 file)
  - https://github.com/oaksandspokes/bikeOsmExport/blob/master/bikeInfraQuery.ql (1 file)
  - https://github.com/maksimbark/knowledge-management/blob/master/practice4/query.ql (1 file)
  - https://github.com/open-austin/atx-citysdk-js/blob/master/data/scripts/osm-parks.ql (1 file)
  - https://github.com/numpde/optimum/blob/main/code/data/20210610-Manhattan/manhattan.ql (1 file)
  - https://github.com/juliepanda/shortest/blob/master/main.ql (1 file)
  - https://github.com/kolesar-andras/site-download/blob/master/overpass.ql (1 file)
  - https://github.com/numpde/transport/blob/master/pt2pt/20191021-NYCTLC/data_preparation/data/osm/manhattan/manhattan.ql (1 file)

  </details>

**Comment by Nixinova** [comment]
Thanks for running the file analysis. The requirements say that each extension must be used in at least 200 repos, so this still doesn't seem enough for inclusion.

**Comment by jerrychong25** [comment]
Thanks @FloEdelmann for the request on adding Overpass QL Language support!

**Comment by LaoshuBaby** [comment]
Thank @FloEdelmann for promotion of OverpassQL, I want to know whether usage in markdown's code part will help in counting repository, like this:

```overpassql
[out:xml][timeout:25];nwr[name="foo"];out body;>;out skel qt;
```

![markdown_sample](https://user-images.githubusercontent.com/42690037/194721670-b5fbca6e-4d36-4933-9251-ffd6085f298c.png)

**Comment by FloEdelmann** [comment]
I don't know whether the languages in Markdown code blocks count towards the limit of 200 repos. But as soon as GitHub's syntax highlighting engine supports `*.overpassql` files, Markdown code blocks with ` ```overpassql ` should also automatically be highlighted. So it would make sense to change those, too :)

**Comment by Alhadis** [comment]
> I don't know whether the languages in Markdown code blocks count towards the limit of 200 repos.

No, they're not. Linguist performs no language analysis of code-blocks, since all names/aliases are unique per language. But your assumption about about `` ```overpassql `` blocks being automatically highlighted is correct. 👍

**Comment by FloEdelmann** [comment]
There are now more than 200 repositories using the `*.overpassql` file extension! :tada: 
See https://github.com/users/FloEdelmann/projects/2/views/4

To keep the discussion clean, I've created a follow-up issue (#6311) and close this one.
