### ISSUE TITLE
Please add detection for the REXX  programming language

### ISSUE THREAD

**Issue by lbdyck** [github/linguist#5914]

**Comment by Alhadis** [comment]
Linguist [already supports REXX](https://github.com/github/linguist/blob/5ece44ec7edad9930a76184f767f88932252e1e7/lib/linguist/languages.yml#L5125-L5139). Whereabouts are you seeing a problem?

If you filled out the issue template (which we kind of require 😉) we'd be able to help you better.

**Comment by lbdyck** [comment]
I'm using GitLab 14.? on a local server (not a paid license)

**Comment by lildude** [comment]
You're asking the wrong peeps then 😁 You want the peeps with the purple header and orange fox-like logo 😉 (Git**Hub** != Git**Lab**) more specifically, you want the https://gitlab.com/gitlab-org/gitaly repo as that's what pulls in Linguist and it's currently a loooooong way behind on v7.12.1.

Closing as this isn't a GitHub Linguist issue.
