### ISSUE TITLE
JSON boolean/null as the last value of an object marked red

### ISSUE THREAD

**Issue by notEthan** [github/linguist#5943]
## Describe the bug

In JSON, a `true`/`false`/`null` value is normally blue. But as the last value in an object, when it's directly adjacent to its closing `}`, it is red.

```json
{"blue bool": true, "blue null": null, "red bool": false}
{"nested": {"red bool": true}, "nested too": {"red null": null}}
{"blue null": null, "blue with a space before bracket": true }
{"blue bool": false, "blue with trailing comma though not valid json": null,}
["arrays are not similarly affected", true]
```

I don't think it used to do this.

A screenshot of what I see (on dark default theme), in case it renders differently elsewhere:
<img width="752" alt="Screen Shot 2022-06-18 at 1 28 37" src="https://user-images.githubusercontent.com/133719/174429782-e1ff625d-33a0-49ee-83e0-0a7e3f1bfd6c.png">

### Expected behaviour

I expect none of these to be highlighted red (except possibly the one with the invalid trailing comma, but that's not the issue)

**Comment by notEthan** [comment]
Reading a little more, I understand Linguist does not do syntax highlighting. Should I file this with https://github.com/tree-sitter/tree-sitter-json instead?

**Comment by Alhadis** [comment]
The latter: please file an issue at @Nixinova's repository.

> I understand Linguist does not do syntax highlighting

Yup, correct. Ergo, I'm closing this as unrelated.

**Comment by Alhadis** [comment]
@notEthan Actually, never mind. I've already submitted a fix. See Nixinova/NovaGrammars#9.

**Comment by notEthan** [comment]
thank you, @Alhadis
