### ISSUE TITLE
Add markdown as language

### ISSUE THREAD

**Issue by kaffarell** [github/linguist#5951]
## Language name
markdown

## Most popular extensions
.md

Is there a reason why markdown isn't included as a language?
It really sucks, cause I have a big repository with a lot of markdown files as documentation, and a single js file. The repository thus shows 100% percent js  usage, and now 99% of all the programming languages used on my github account is javascript.

**Comment by Nixinova** [comment]
Markdown is already a language, it is just not included in the repository statistics because it is not code.

> Linguist starts by going through all the files in a repository and excludes all files that it determines to be binary data, vendored code, generated code, documentation, or are defined as data (e.g. SQL) or prose (**e.g. Markdown**) languages, whilst taking into account any overrides.
– ["How Linguist works"](https://github.com/github/linguist/blob/master/docs/how-linguist-works.md)

If you want Markdown to be included in the repository statistics you need to use [an override](https://github.com/github/linguist/blob/master/docs/overrides.md#using-gitattributes):

```gitattributes
*.md linguist-detectable
```

**Comment by kaffarell** [comment]
Perfect, thank you!

**Comment by Suman373** [comment]
> Markdown is already a language, it is just not included in the repository statistics because it is not code.
> 
> > Linguist starts by going through all the files in a repository and excludes all files that it determines to be binary data, vendored code, generated code, documentation, or are defined as data (e.g. SQL) or prose (**e.g. Markdown**) languages, whilst taking into account any overrides.
> > – ["How Linguist works"](https://github.com/github/linguist/blob/master/docs/how-linguist-works.md)
> 
> If you want Markdown to be included in the repository statistics you need to use [an override](https://github.com/github/linguist/blob/master/docs/overrides.md#using-gitattributes) in your `/.gitattributes` file:
> 
> ```gitattributes
> *.md linguist-detectable
> ```
> 
> Then Markdown will be included in the results the next time GitHub refreshes your repo's language stats.

Thanks for the nice explanation!!
