### ISSUE TITLE
Wrong PostScript syntax highlighting

### ISSUE THREAD

**Issue by zzo38** [github/linguist#5959]
## Describe the bug
See the issue: https://github.com/multiformats/multicodec/issues/278 It is supposed to be a PostScript code but there are some unusual things with the syntax highlighting.

### Expected behaviour
The comment that says `% discard header line` should be same colours of other comments, and words such as `pop` and `if` should not have different colours in different parts of the program; they should be consistent.

**Comment by zzo38** [comment]
I am guessing that it might be confused by the use of the `currentfile` operator. However, in this case the `currentfile` is inside of a `{}` block, and therefore is not executed right away and does not access the data inside of the `{}` block.

**Comment by Nixinova** [comment]
Linguist doesn't directly control syntax highlighting. As listed in https://github.com/github/linguist/tree/master/vendor the PostScript grammar is taken from https://github.com/Alhadis/Atom-PostScript. You should take this issue there.

**Comment by zzo38** [comment]
OK, I will post the issue on Alhadis/Atom-PostScript instead. Thank you for telling me that; somehow I had forgotten about that list, but now I know better.
