### ISSUE TITLE
Language percentage distribution is wrong in my repository

### ISSUE THREAD

**Issue by izcoser** [github/linguist#5962]
Hi.

I have [this](https://github.com/izcoser/etherbets) repo and it reports 55% CSS and 19% JS.
If you click on JS it'll accurately show 30 files and only 2 small files if you click CSS. Despite that, it's still not calculating the percentages correctly.

Any idea why this is happening?

**Comment by Nixinova** [comment]
That's because Linguist uses file size, not file count
<img width="290" alt="image" src="https://user-images.githubusercontent.com/42429413/177229736-f279abd7-340a-48e9-ad13-486007c35d5a.png">

**Comment by Nixinova** [comment]
Linguist classifies react files that have no dots in them as vendored, and are excluded from the results:
https://github.com/github/linguist/blob/b2a1105d6dee84e8a097b368b2b80669dc969f9b/lib/linguist/vendor.yml#L226-L227
So these are the only files that get looked at:
<img width="379" alt="image" src="https://user-images.githubusercontent.com/42429413/177230019-3fa1e6a5-e758-491d-b8a3-77f9e7989520.png">
And creates the output based on those file sizes:
<img width="277" alt="image" src="https://user-images.githubusercontent.com/42429413/177230051-696539af-9e57-41a7-ba51-7cdfe4648c59.png">

**Comment by izcoser** [comment]
Thank you! I did look at vendor.yml but that rule went unnoticed. How can I tell Linguist to stop ignoring these files, as they are my own code?

**Comment by Nixinova** [comment]
Add e.g. `*.js linguist-vendored=false` to your `.gitattributes` and they'll be included in the next time that GitHub refreshes the stats.

**Comment by izcoser** [comment]
Thank you very much! Closing this.
