### ISSUE TITLE
Language used is not detected

### ISSUE THREAD

**Issue by raikiran07** [github/linguist#5984]
## Describe the bug

I have created many repositories which consist mostly of javascript, it is more than 3 months since I uploaded but almost all my repository's languages are not detected, I don't have any prior knowledge to fix it. Can anyone help me with this?

**Comment by Alhadis** [comment]
Is there a reason you neglected to fill out the issue template?

**Comment by raikiran07** [comment]
sorry, I didn't find the issue template so I directly created an issue regarding my problem. Is there any particular template that I need to follow?

**Comment by Alhadis** [comment]
@raikiran07 I've updated the OP with the template's fields.

**Comment by raikiran07** [comment]
thanks for your help, I got the solution

**Comment by lildude** [comment]
This is the option you really wanted 😉 

![CleanShot 2022-07-21 at 12 37 04](https://user-images.githubusercontent.com/627280/180204679-6777f966-2541-49e5-b298-7e2c19e9250f.png)
