### ISSUE TITLE
Change Rust color for type names, and `self` keyword

### ISSUE THREAD

**Issue by antoninhrlt** [github/linguist#5985]
As you can see on this screen (from my profile README) :
![New color](https://user-images.githubusercontent.com/66388237/180088116-8f1f2432-583e-4c11-a4c5-dab81e29b88c.png)

Type names `Anto`, `Programmer` and `Language` as well as `self` are all gray.

But I remember the type names were colored (maybe blue or violet, I don't remember exactly). And `self` was blue as well as `&` is.

From my memories, `Language` was gray, even if it's a type name.

I also saw a color changement on the attributes : 
![New color](https://user-images.githubusercontent.com/66388237/180089248-9c4e5e65-69f6-4788-acef-2cae4ecd2437.png)
That's ok. But it should not remove the color on the type names.

Well, I would like to see back the pretty colors instead of this sad gray. Thanks for reading me

Regards.

**Comment by antoninhrlt** [comment]
Just saw #5973, is it the source of the problem ?

**Comment by TheWitheredStriker** [comment]
I believe so, as Rust's grammar file was changed. The old one was a public archive with some issues starting to pile up.

**Comment by lildude** [comment]
Yup, @TheWitheredStriker is spot on.

That said, we have an update in the pipeline to pull in the changes from https://github.com/tree-sitter/tree-sitter-rust/pull/150 so things might improve in the next few days.

If not, you'll need to report any problems to the upstream repo at https://github.com/tree-sitter/tree-sitter-rust.

Closing as this has nothing to do with Linguist.

**Comment by antoninhrlt** [comment]
Yes I see thanks.

> Closing as this has nothing to do with Linguist.

Colors changed because Linguist use another syntax hilighter now, so...
Well, I will create another issue on the appropriated repository
