### ISSUE TITLE
Vue syntax highlighting bugs when TS's optional chaining opreator is used within the template

### ISSUE THREAD

**Issue by ringeringeraja** [github/linguist#6001]
## Describe the bug

All syntax will become buggy if something like "something?.prop" is within double bracks inside the <template> tag, though the code will compile fine.
Example:

```vue
<template>
  <div class="greeting">Hello, {{ user?.name }}!</div>
  <div class="summary">You have {{ user?.amount }} coins.</div>
</template>

<script setup lang="ts">
import user from './store'
</script>
```

### Expected behaviour

The syntax highligting is expected to recognise "object?.prop" as a valid object property and proceed to parse the next token instead of bugging everything following it.

**Comment by Alhadis** [comment]
From the [troubleshooting docs](https://github.com/github/linguist/blob/e4599a93152a29a650b1e48722e5d2ba465acb0d/docs/troubleshooting.md#theres-a-problem-with-the-syntax-highlighting-of-a-file):

> If you experience an issue with the syntax-highlighting on GitHub, <strong><em><ins>please report the issue to the upstream grammar repository, not here</ins></em></strong>. Grammars are updated every time we build the Linguist gem so upstream bug fixes are automatically incorporated as they are fixed.

In the case of Vue, syntax highlighting is provided by [`vuejs/vue-syntax-highlight`](https://github.com/vuejs/vue-syntax-highlight). I recommend filing an issue upstream, if it hasn't been reported already.

Closing this as it isn't an issue related to Linguist.

**Comment by wopian** [comment]
There has been no action in the [vuejs/vue-syntax-highlight](https://github.com/vuejs/vue-syntax-highlight) repository for 3+ years in the branch Linguist uses for Vue's syntax highlighting unfortunately. 

See my issue from almost a year ago: https://github.com/vuejs/vue-syntax-highlight/issues/217 highlighting the issue (that's now grown to 2+ Stage 4 syntaxes (`?.` and `??`)

**Comment by lildude** [comment]
I guess the only option is find another grammar (maybe a VSCode grammar?) that doesn't experience the issues and submit a PR to replace the grammar. You can find details on how to do this in the [CONTRIBUTING.md](https://github.com/github-linguist/linguist/blob/master/CONTRIBUTING.md) file.

**Comment by eensander** [comment]
Are there any developments on this? I don't see why this issue was closed, since I have noticed this incorrect representation in our as well as many repositories from other organizations on GitHub that use Vue+TS. And as correctly expressed by @kaiarrowood [here](https://github.com/vuejs/vue-syntax-highlight/issues/217#issuecomment-1488923844): 
> Vue 3 is pushing heavily towards typescript so instances of this are just going to get more and more common

If, as @wopian says, "there doesn't seem to be any interest from the maintainers to fix this either", would then @lildude's proposed solution be achievable instead?

Thanks

**Comment by lildude** [comment]
No developments from a Linguist perspective as this is closed as a problem with the upstream grammar. If the maintainers of the current grammar don't want to make changes then yes, the only option is to find a new grammar. We rely on the community to provide these kinds of updates as you're more likely in the know, so if you know of a Textmate/VSCode-compatible grammar that is suitably licensed, feel free to open a PR to change grammars.

No rush as you've just missed the latest release. The next release is scheduled to be in about three month's time.

**Comment by sevenc-nanashi** [comment]
The one in vuejs/language-tools (https://github.com/vuejs/language-tools/blob/master/extensions/vscode/syntaxes/vue.tmLanguage.json) looks good for me.
