### ISSUE TITLE
Support linguist on github enterprise server

### ISSUE THREAD

**Issue by philipcraig** [github/linguist#6005]
## Describe the enhancement

Support linguist on github enterprise server, so that PR reviews there can suppress diffs using `linguist-generated` in `.gitattributes`

(Using GitHub Enterprise Server 3.1.19)

**Comment by lildude** [comment]
This will already be in place. Support for `linguist-generated` has been in Linguist for well over 10 years so will be available in every release of GitHub Enterprise Server. 

If you're not seeing the behaviour you're expecting, you've either made a mistake in your `.gitattributes` (typos or forgetting about recursion—`*` does not recurse, but `**` does—are the normal causes) or something else unrelated to Linguist is at play.

**Comment by philipcraig** [comment]
happy to close, it was indeed `**` that was the problem. Thank you
