### ISSUE TITLE
Add support for Cairo 0.10.0

### ISSUE THREAD

**Issue by Bernardstanislas** [github/linguist#6079]
## Language name

Cairo-lang

## URL of example repository

https://github.com/starkware-libs/cairo-lang

## URL of syntax highlighting grammar

https://github.com/starkware-libs/cairo-lang

## Update the support

Linguist detects Cairo files for version < 0.10.0, syntax has changed a lot and syntax highlighting no longer works.

**Comment by lildude** [comment]
This needs to be addressed by the upstream grammar. See https://github.com/github/linguist/pull/6070#issuecomment-1247919604

Closing.
