### ISSUE TITLE
Add languages OASv2 OASv3

### ISSUE THREAD

**Issue by whuji** [github/linguist#6115]
## Language name

OASv2, OASv3

## URL of example repository

https://github.com/Azure/azure-rest-api-specs
https://github.com/github/rest-api-description
https://github.com/42Crunch/vscode-openapi

## URL of syntax highlighting grammar

No new grammar needed (JSON and YAML format), just heuristics disambiguation.

## Most popular extensions

.json
.yaml
.yml

## Detected language

currently JSON / YAML
could be disambiguated as OASv2, OASv3

---

Swagger and OpenAPI files are being very common and could be represented on GitHub as languages as there are used to generate server and client code and infrastructure automation code.

**Comment by lildude** [comment]
Shipped in https://github.com/github/linguist/pull/6116
