### ISSUE TITLE
Please add `mindmap` rendering from Mermaidjs v9.2.2+

### ISSUE THREAD

**Issue by vhrichfernandez** [github/linguist#6168]
## Describe the enhancement
I'm seeing rendering issues for the latest version of Mermaid linguist here:
https://github.com/mermaid-js/mermaid/blob/develop/docs/syntax/mindmap.md

Here's an example of how they _should_ look:
https://mermaid-js.github.io/mermaid/#/mindmap

Thank you!

**Comment by lildude** [comment]
Linguist is not responsible for rendering Mermaid diagrams. It's only responsible for the syntax highlighting of the raw code.

Please contact GitHub support using the Contact GitHub link on a page showing the issue or open a new discussion at https://github.com/orgs/community/discussions
