### ISSUE TITLE
Svelte highlighting seems to be not working

### ISSUE THREAD

**Issue by stevepopovich** [github/linguist#6180]
## Describe the bug

Hi folks, hubber here from the mobile team. Svelte highlighting seems to be broken and has been for months. I am trying to get to the bottom of what is going on and need some direction, hoping y'all can help.

Highlighting in this https://github.com/Lleweraf/supachat/blob/latest/src/components/ChatInput.svelte is broken, both on dotcom and on mobile.

### Expected behaviour

We should see svelte code highlighted properly 

### Related discussion

[This](https://github.com/github/mobile/issues/3068) is the original issue we are tracking on mobile.

**Comment by lildude** [comment]
@stevepopovich I recently got to the bottom of this in https://github.com/github/linguist/discussions/6164

In short, the grammar is using regex matches in the scope names but GitHub's very old syntax highlighter doesn't expand these so subsequent rules aren't found.

The old highlighter isn't going to be fixed so the options are:

- update the grammar to take this limitation into account, or
- confirm the tree-sitter grammar is at least as complete as the Textmate-based grammar and renders correctly and then I can lobby to have that added to the new highlighter instead.

**Comment by lildude** [comment]
I've done some quick testing in dev using the tree-sitter grammar and it looks promising and much better than the Textmate grammar:

![CleanShot 2022-11-22 at 09 45 37](https://user-images.githubusercontent.com/627280/203281409-8d8a2cd2-8dd5-4e32-b6ee-3771953e69b8.png)

I'm going to submit a PR proposing to add the Svelte tree-sitter grammar. We'll see how it goes.

**Comment by stevepopovich** [comment]
Amazing! Thank you. Sorry I was in the wrong spot, things have gotten confusing for me trying to figure out who owns the problem.

**Comment by lildude** [comment]
So it turns out my local dev env was not actually pulling in the treesitter grammar when testing. It was actually pulling in the TextMate grammar from Linguist v7.20.0 which means the TextMate grammar was working properly then and started failing after that.

More deets in my response at https://github.com/github/linguist/discussions/6164#discussioncomment-4215301

**Comment by stevepopovich** [comment]
So once https://github.com/github/github/pull/248502 is deployed, this is expected to be fixed?

**Comment by lildude** [comment]
Yup.

**Comment by lildude** [comment]
And we're back to working Svelte syntax highlighting (below should look like the screenshot above):

```svelte
<script>
  const notWorking = 'I am not highlighted';
</script>

{#each something as s}
  <p on:click={doSomething}>
    Our tags are highlighted correctly
  </p>
{/each}

<style>
  .not-highlighted {
    color: 'black'; // because it isn't highlighted bar
  }
</style>

<template>
  {#each something as s}
    <p on:click={doSomething}>
      Now we aren't working.
    </p>
  {/each}
</template>
```
