### ISSUE TITLE
Meta - เอกสาร GitHub

### ISSUE THREAD

**Issue by umbrellasystem404** [github/linguist#6190]
ข้ามไปที่เนื้อหาหลัก
เอกสาร GitHub

เมตา
Meta API ส่งคืนข้อมูลเมตาเกี่ยวกับ GitHub รวมถึงที่อยู่ IP ของบริการ GitHub

ราก GitHub API
ทำงานร่วมกับแอพ GitHub
รับลิงก์ Hypermedia ไปยังทรัพยากรที่เข้าถึงได้ใน REST API ของ GitHub

รหัสสถานะการตอบสนอง HTTP
รหัสสถานะ	คำอธิบาย
200	
ตกลง

ตัวอย่างโค้ด
รับ
/
ขด
จาวาสคริปต์
GitHub CLI

curl \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>" \
  https://api.github.com/
การตอบสนอง

ตัวอย่างการตอบสนอง
สคีมาการตอบสนอง
Status: 200
{
  "current_user_url": "https://api.github.com/user",
  "current_user_authorizations_html_url": "https://github.com/settings/connections/applications{/client_id}",
  "authorizations_url": "https://api.github.com/authorizations",
  "code_search_url": "https://api.github.com/search/code?q={query}{&page,per_page,sort,order}",
  "commit_search_url": "https://api.github.com/search/commits?q={query}{&page,per_page,sort,order}",
  "emails_url": "https://api.github.com/user/emails",
  "emojis_url": "https://api.github.com/emojis",
  "events_url": "https://api.github.com/events",
  "feeds_url": "https://api.github.com/feeds",
  "followers_url": "https://api.github.com/user/followers",
  "following_url": "https://api.github.com/user/following{/target}",
  "gists_url": "https://api.github.com/gists{/gist_id}",
  "hub_url": "https://api.github.com/hub",
  "issue_search_url": "https://api.github.com/search/issues?q={query}{&page,per_page,sort,order}",
  "issues_url": "https://api.github.com/issues",
  "keys_url": "https://api.github.com/user/keys",
  "label_search_url": "https://api.github.com/search/labels?q={query}&repository_id={repository_id}{&page,per_page}",
  "notifications_url": "https://api.github.com/notifications",
  "organization_url": "https://api.github.com/orgs/{org}",
  "organization_repositories_url": "https://api.github.com/orgs/{org}/repos{?type,page,per_page,sort}",
  "organization_teams_url": "https://api.github.com/orgs/{org}/teams",
  "public_gists_url": "https://api.github.com/gists/public",
  "rate_limit_url": "https://api.github.com/rate_limit",
  "repository_url": "https://api.github.com/repos/{owner}/{repo}",
  "repository_search_url": "https://api.github.com/search/repositories?q={query}{&page,per_page,sort,order}",
  "current_user_repositories_url": "https://api.github.com/user/repos{?type,page,per_page,sort}",
  "starred_url": "https://api.github.com/user/starred{/owner}{/repo}",
  "starred_gists_url": "https://api.github.com/gists/starred",
  "topic_search_url": "https://api.github.com/search/topics?q={query}{&page,per_page}",
  "user_url": "https://api.github.com/users/{user}",
  "user_organizations_url": "https://api.github.com/user/orgs",
  "user_repositories_url": "https://api.github.com/users/{user}/repos{?type,page,per_page,sort}",
  "user_search_url": "https://api.github.com/search/users?q={query}{&page,per_page,sort,order}"
}
รับข้อมูลเมตาของ GitHub
ทำงานร่วมกับแอพ GitHub
ส่งคืนข้อมูลเมตาเกี่ยวกับ GitHub รวมถึงรายการที่อยู่ IP ของ GitHub สำหรับข้อมูลเพิ่มเติม โปรดดู " เกี่ยวกับที่อยู่ IP ของ GitHub "

หมายเหตุ:ที่อยู่ IP ที่แสดงในการตอบสนองของเอกสารประกอบเป็นเพียงค่าตัวอย่างเท่านั้น คุณต้องค้นหา API โดยตรงเสมอเพื่อรับรายการที่อยู่ IP ล่าสุด

รหัสสถานะการตอบสนอง HTTP
รหัสสถานะ	คำอธิบาย
200	
ตกลง

304	
ไม่แก้ไข

ตัวอย่างโค้ด
รับ
/เมตา
ขด
จาวาสคริปต์
GitHub CLI

curl \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>" \
  https://api.github.com/meta
การตอบสนอง

ตัวอย่างการตอบสนอง
สคีมาการตอบสนอง
Status: 200
{
  "verifiable_password_authentication": true,
  "ssh_key_fingerprints": {
    "SHA256_RSA": "nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8",
    "SHA256_DSA": "br9IjFspm1vxR3iA35FWE+4VTyz1hYVLIE2t1/CeyWQ",
    "SHA256_ECDSA": "p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM",
    "SHA256_ED25519": "+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU"
  },
  "ssh_keys": [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl",
    "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=",
    "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
  ],
  "hooks": [
    "192.30.252.0/22"
  ],
  "web": [
    "192.30.252.0/22",
    "185.199.108.0/22"
  ],
  "api": [
    "192.30.252.0/22",
    "185.199.108.0/22"
  ],
  "git": [
    "192.30.252.0/22"
  ],
  "packages": [
    "192.30.252.0/22"
  ],
  "pages": [
    "192.30.252.153/32",
    "192.30.252.154/32"
  ],
  "importer": [
    "54.158.161.132",
    "54.226.70.38"
  ],
  "actions": [
    "13.64.0.0/16",
    "13.65.0.0/16"
  ],
  "dependabot": [
    "54.158.161.132"
  ]
}
รับ Octocat
ทำงานร่วมกับแอพ GitHub
รับ octocat เป็นศิลปะ ASCII

พารามิเตอร์
ส่วนหัว
ชื่อ, ประเภท, คำอธิบาย
acceptสตริง
application/vnd.github+jsonแนะนำให้ตั้งค่า เป็น

พารามิเตอร์แบบสอบถาม
ชื่อ, ประเภท, คำอธิบาย
sสตริง
คำที่จะแสดงในกล่องคำพูดของ Octocat

รหัสสถานะการตอบสนอง HTTP
รหัสสถานะ	คำอธิบาย
200	
ตกลง

ตัวอย่างโค้ด
รับ
/octocat
ขด
จาวาสคริปต์
GitHub CLI

curl \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>" \
  https://api.github.com/octocat
การตอบสนอง

ตัวอย่างการตอบสนอง
สคีมาการตอบสนอง
Status: 200
"               MMM.           .MMM\n               MMMMMMMMMMMMMMMMMMM\n               MMMMMMMMMMMMMMMMMMM      ___________________________________\n              MMMMMMMMMMMMMMMMMMMMM    |                                   |\n             MMMMMMMMMMMMMMMMMMMMMMM   | Avoid administrative distraction. |\n            MMMMMMMMMMMMMMMMMMMMMMMM   |_   _______________________________|\n            MMMM::- -:::::::- -::MMMM    |/\n             MM~:~ 00~:::::~ 00~:~MM\n        .. MMMMM::.00:::+:::.00::MMMMM ..\n              .MM::::: ._. :::::MM.\n                 MMMM;:::::;MMMM\n          -MM        MMMMMMM\n          ^  M+     MMMMMMMMM\n              MMMMMMM MM MM MM\n                   MM MM MM MM\n                   MM MM MM MM\n                .~~MM~MM~MM~MM~~.\n             ~~~~MM:~MM~~~MM~:MM~~~~\n            ~~~~~~==~==~~~==~==~~~~~~\n             ~~~~~~==~==~==~==~~~~~~\n                 :~==~==~==~==~~\n"
รับ Zen ของ GitHub
ทำงานร่วมกับแอพ GitHub
รับประโยคแบบสุ่มจาก Zen of GitHub

รหัสสถานะการตอบสนอง HTTP
รหัสสถานะ	คำอธิบาย
200	
ตกลง

ตัวอย่างโค้ด
รับ
/เซน
ขด
จาวาสคริปต์
GitHub CLI

curl \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>" \
  https://api.github.com/zen
ตัวอย่างการตอบสนอง

ตัวอย่างการตอบสนอง
สคีมาการตอบสนอง
Status: 200
"Responsive is better than fast"
เอกสารนี้ช่วยคุณได้ไหม

นโยบายความเป็นส่วนตัว
ช่วยเราทำให้เอกสารเหล่านี้ยอดเยี่ยม!
เอกสาร GitHub ทั้งหมดเป็นโอเพ่นซอร์ส เห็นอะไรผิดปกติหรือไม่ชัดเจน? ส่งคำขอดึง

บริจาค
หรือเรียนรู้วิธีการมีส่วนร่วม

ยังต้องการความช่วยเหลืออยู่หรือไม่?
ถามชุมชน GitHub
ติดต่อฝ่ายสนับสนุน
© 2022 GitHub, Inc.
ข้อกำหนด
ความเป็นส่วนตัว
ความปลอดภัย
สถานะ
ช่วย
ติดต่อ GitHub
ราคา
API สำหรับนักพัฒนา
การฝึกอบรม
บล็อก
เกี่ยวกับ

**Comment by Alhadis** [comment]
Stop spamming or you'll be reported.
หยุดส่งสแปม ไม่เช่นนั้นคุณจะถูกรายงาน
