### ISSUE TITLE
Promela language repo is gone

### ISSUE THREAD

**Issue by nk9** [github/linguist#6223]
## Describe the bug
The [Promela repo](https://github.com/corbanmailloux/sublime-promela-spin), as linked from [the vendor list](https://github.com/github/linguist/blob/master/vendor/README.md), is gone.

**Comment by lildude** [comment]
No it's not:

![CleanShot 2023-01-01 at 16 20 04](https://user-images.githubusercontent.com/627280/210177713-c2e577ee-df85-4f7d-b697-28f261c51461.png)

```console
$ curl -sLI https://github.com/corbanmailloux/sublime-promela-spin | head -1
HTTP/2 200
$
```

Closing.

**Comment by jack2107** [comment]
нд, 1 січ. 2023, 18:21 користувач Colin Seymour ***@***.***>
пише:

**Comment by jack2107** [comment]
нд, 1 січ. 2023, 18:21 користувач Джек Рiзник ***@***.***> пише:

**Comment by nk9** [comment]
Very strange, it was 404 when I filed this! Anyway, I agree, it's there now. 👍
