### ISSUE TITLE
Support Python 3.10 `match` and `case` keywords

### ISSUE THREAD

**Issue by showierdata9978** [github/linguist#6288]
## Describe the enhancement

Add support for `match` and `case` as it was added in 3.10, and python has stable released 3.11

**Comment by TurnrDev** [comment]
I'd like to reopen this as the upstream grammer for python has added support over a year ago and it seems it's still not pulled into linguist? https://github.com/tree-sitter/tree-sitter-python/commit/ed0fe62e55dc617ed9dec8817ebf771aa7cf3c42

**Comment by TurnrDev** [comment]
Sounds like Tree Sitter need to get on it then. This is a fairly confusing system, are we sure it's the best way to do things? 😅

**Comment by lildude** [comment]
> I'll give them a nudge though.

Turned this into do-it-myself 😁. We're now running the latest tagged version of the grammar (v0.20.0):

Look how boootiful it is now 😻 

```python
match command.split():
    case ["quit"]:
        print("Goodbye!")
        quit_game()
    case ["look"]:
        current_room.describe()
    case ["get", obj]:
        character.get(obj, current_room)
    case ["go", direction]:
        current_room = current_room.neighbor(direction)
    # The rest of your commands go here
```

**Comment by TurnrDev** [comment]
I guess this issue can be reclosed as completed now! Thank you, you are a legend
