### ISSUE TITLE
Change color of language in card

### ISSUE THREAD

**Issue by tranghane** [github/linguist#6292]
![image](https://user-images.githubusercontent.com/106038718/219450592-67972d81-3816-470b-8808-0efaec4fec60.png)
Hi, as you can see, the colour (for Jupyter Notebook and HTML) is kinda hard to see, and it's even harder for those color-blind. I wonder how we can change that

**Comment by lildude** [comment]
That image is coming from your profile README.md which is being generated by https://github-readme-stats.vercel.app/, not Linguist or GitHub. It may however be getting the colours from GitHub which we will only change if agreed upon by the wider community for that language. See the CONTRIBUTING.md file [here](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#changing-the-color-associated-with-a-language).

It's worth pointing out that Linguist and GitHub is only responsible for the language bar you see in the sidebar of a repo, and we already cater for possible legibility issues by putting spacing between each of the language colours:

![CleanShot 2023-02-16 at 18 23 55](https://user-images.githubusercontent.com/627280/219454364-74083113-8525-44e0-ac26-9bb03b1cf49a.png)

As this is not a Linguist issue, I'm going to close this issue. You will need to contact the author of https://github-readme-stats.vercel.app/ if you want improvements to their rendered image.
