### ISSUE TITLE
better syntax highlighting for console snippets

### ISSUE THREAD

**Issue by mcandre** [github/linguist#6293]
## Describe the enhancement

The current console language highlighter has really strange tokenization, for example when used inside of a README.md (GitHub flavored Markdown) document.

The highlighter really seems to highlight text at random. It's so strange and distracting, that even no colorization would be easier to read.

### New tokenization scheme

* 99% of text: A boring, consistent foreground color.
* Standard prompts: A bare dollar (`$`) or greater than (`>`) prompt leading the line. We could extend this very slightly to handle UNIX and NTFS file paths preceding these characters. But beyond that complexity, anything else in a snippet prompt is likely going to be wasteful, distracting text for the human reader, and difficult to establish a performant parser ROC curve. We can color the prompt classic green, and dim the luminosity, in order to emphasize that the user is not expected to literally type out the prompt when following console snippets.
* Standard line comments: A sharp (`#`) or a double colon (`::`) leading the line. Any obscure comment syntax, or multiline comment syntax, is better suited to placing above or below a snippet (in the case of a documentation), or highlighted with a more specific parser, for script files. Color in the area of brown. Like the prompt, dim to denote its parenthetical nature.

And that's it. Do not attempt to highlight other tokens specially, because they're very likely to be arbitrary output from unknowable programs.

### Don't highlight built-in shell commands like cd

Don't try to highlight shell built-ins specially. Given that built-in commands and other executables will be interleaved in console snippets, all that does is make a distracting, unpredictable view.

And which exact built-ins would we even support exactly? Because ls is a built-in for POSIX sh and PowerShell but not for Command Prompt. where may be a built-in on some systems but not others. find is a built-in for Command Prompt and PowerShell but not UNIX sh. ll may be a distribution-provided alias for ls with certain flags enabled, though not technically a shell built-in, in for troubleshooting purposes.

curl/wget are built-ins for PowerShell but not for Command Prompt or UNIX sh. which is a built-in for UNIX sh but not for Command Prompt. Most things are built-ins in OS distributions based on Busybox/Toybox sh.

Such applies not only to UNIX sh implementations, but note that there are also non-POSIX shells like csh, tcsh, fish, ...

pushd/popd are built-ins for bash and zsh but not for ksh. Some distributions shim pushd/popd on behalf of ksh, mimicking a built-in. For troubleshooting reasons, should we treat these commands as built-ins or non-built-ins? You can see what a headache highlighting built-ins becomes.

The highlighter cannot be expected to know the exact console implementation, especially for very short snippets. To hazard a guess is to produce very many incorrectly highlighted snippets, and so it should not attempt to guess, but simply apply the least common denominator.

### Short term patch

Recommend disabling any and all colors and luminances for the existing highlighter implementation on console language snippets, as a quick patch while we improve highlighting long term.

**Comment by Alhadis** [comment]
> Short term patch
> -----------------
> Recommend disabling any and all colors and luminances for the existing highlighter implementation on console language snippets, as a quick patch while we improve highlighting long term.

Long term patch
---------------
Stop tagging code-blocks as `console` output if the highlighting is problematic. You can easily use ordinary shell highlighting (`` ```sh ``), ordinary PowerShell highlighting (`` ```powershell ``) and ordinary Batchfile/CMD.exe highlighting (`` ```batch ``) instead.

**Comment by lildude** [comment]
This isn't really anything within Linguist's direct control and would need to be addressed by the [grammar](https://github.com/atom/language-shellscript). This has been discussed before too in https://github.com/github/linguist/issues/5682

**Comment by mcandre** [comment]
> Stop tagging code-blocks as console output if the highlighting is problematic. You can easily use ordinary shell highlighting (```sh), ordinary PowerShell highlighting (```powershell) and ordinary Batchfile/CMD.exe highlighting (```batch) instead.

That's not what I'm asking for. I don't post PowerShell or MS-DOS Batch or POSIX sh or csh or fish command snippets. I post generic, cross-platform snippets. We should fix the console parser to stop assuming so much, so that the console highlighter works better by default.

**Comment by lildude** [comment]
> I post generic, cross-platform snippets. We should fix the console parser to stop assuming so much, so that the console highlighter works better by default.
 
I think we need to take a few steps back here and clarify a few things...

1. There is no such thing as a "console parser". All [fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) are rendered by the https://github.com/github/markup library which looks at the optional language attribute to determine the syntax highlighting that should be applied to that codeblock and uses the corresponding grammar from Linguist. If no language is specified, no syntax highlighting it applied.
2. If you set the codeblock language to `console`, you are explicitly asking markup to use the "Shell session" syntax highlighting as defined here: https://github.com/github/linguist/blob/89f4df5824fb3da8bd6fa37075dd36aeb7d18442/lib/linguist/languages.yml#L6378-L6389 as this is the only language entry which is called "console" or has an alias of "console".
3. As a result of this, you get the, admittedly far from perfect even for shell sessions, syntax highlighting as defined in [this grammar](https://github.com/atom/language-shellscript) (previously mentioned). This is very *nix shell centric as that is how it was written. If there is anything that could be considered the "console parser" it would be this grammar. 

So with that in mind, the "console parser" is not assuming anything. You are. You are explicitly telling markup that you want "Shell session" syntax highlighting applied to the codeblocks you add `console` but are assuming it is a lot more generic than it really is.

If the *nix shell-centric syntax highlighting doesn't suit your purposes, there are two solutions:

1. Specify another language in your codeblock which gives you the syntax highlighting you want, eg `pycon` or `python console` if you want [Python Console highlighting](https://github.com/github/linguist/blob/89f4df5824fb3da8bd6fa37075dd36aeb7d18442/lib/linguist/languages.yml#L5407-L5415).
2. Create a custom, generic `console` grammar which will apply a generic and consistant "console" highlighting as you want, across all languages, console shells, and use-cases you are thinking of, without prompting and without making the current highlighting any worse. Once such a grammar exists, we can certainly entertain the idea of adding it to Linguist, either as a generic standalone "language" or by swapping it with the current "Shell session" grammar.

Either way, this is out of Linguist's control so nothing is going to happen within Linguist.

**Comment by Alhadis** [comment]
> I post generic, cross-platform snippets.

So in other words, you post a subset of shell syntax that happens to be functionally identical when parsed as batch or PowerShell. I'm assuming that's what you mean, because there's no such thing as a truly "cross-platform" console syntax (unless the simplest, most minimal use-cases are all you care about).

In any case, this falls outside Linguist's scope of responsibilities (as @lildude explained for you), and the subpar console/shell highlighting is a known issue that (should) be resolved eventually.

In the meantime, I'm closing this, since there's nothing we can do to address the issue on our end. Please consider opening a [discussion](https://github.com/github/linguist/discussions/new/choose) if you need to discuss this further.

**Comment by Alhadis** [comment]
Whoops, I meant to close this as "not planned", instead of of "completed.

@lildude, is it possible to update the reason for closing an issue after it's already been, well, closed?

**Comment by lildude** [comment]
Yup. You might not have the access for it as a repo contributor, but I can:

![CleanShot 2023-03-13 at 09 44 16](https://user-images.githubusercontent.com/627280/224664934-85034743-d981-495c-b44a-685e1c71c005.png)

Done.

**Comment by NuckChorris** [comment]
@lildude you said this:

> Create a custom, generic console grammar which will apply a generic and consistant "console" highlighting as you want, across all languages, console shells, and use-cases you are thinking of, without prompting and without making the current highlighting any worse. Once such a grammar exists, we can certainly entertain the idea of adding it to Linguist, either as a generic standalone "language" or by swapping it with the current "Shell session" grammar.

But if you look at the [grammar definition](https://github.com/atom/language-shellscript/blob/master/grammars/shell-session.cson) this _is_ what the `text.shell-session` or `console` grammar is, just... kinda poorly, because it requires the `:~` in the command prefix, which is misaligned with the defacto syntax it is attempting to describe, and attempts to delegate (poorly, in confusing places) to `source.shell`. The syntax used across much of github, described in this issue, but also enforced by [markdownlint MD014](https://github.com/DavidAnson/markdownlint/blob/main/doc/md014.md) and [generated by bundler](https://github.com/rubygems/rubygems/blob/master/bundler/lib/bundler/templates/newgem/README.md.tt#L11-L18) is much simpler:

```console
# Run command
$ cat file.test
Output goes here
```

vs the supported syntax:

```console
# Run command
foo:~ $ cat file.test
Output goes here
```

Also of note is the lack of comment support. All Unix shells support `#` as a line comment, as does PowerShell, so I think that would be a reasonable addition to the grammar (could also add `::` or `rem` support for Batch)

Is it outside Linguist's scope to fix the grammars it contains, or would a PR to this grammar be acceptable?

**Comment by lildude** [comment]
> Is it outside Linguist's scope to fix the grammars it contains, or would a PR to this grammar be acceptable?

Both 😁 If you want to change the source of a grammar, you do it here. If you want to change the grammar itself, you do it in the grammar repo and we'll pick it up with the next release.

**Comment by adelton** [comment]
The problem with the grammar repo is that it has been archived, so not accepting contributions. Basically, https://github.com/atom/language-shellscript falls into the https://github.com/github-linguist/linguist/issues/6251 / https://github.com/github-linguist/linguist/discussions/6327 category.
