### ISSUE TITLE
Highlighting leak in OCaml

### ISSUE THREAD

**Issue by Alizter** [github/linguist#6318]
## Describe the bug

The following OCaml code causes a highlighting leak:
```ocaml
 let man =
    [ `S "DESCRIPTION"
    ; `P
        {|$(b,dune fmt) runs the formatter on the source code. The formatter is automatically selected. ocamlformat is used to format OCaml source code (*.ml and *.mli files) and refmt is used to format Reason source code (*.re and *.rei files).|}
    ; `Blocks Common.help_secs
    ]
```
![image](https://user-images.githubusercontent.com/8614547/224764332-0c06e35a-673d-4db0-87cd-7e9c78ad3565.png)

### Expected behaviour

The string escape characters `{| |}` shouldn't be interfered by a following `$`.

**Comment by lildude** [comment]
Closing as this is an upstream bug which I see you've now opened an issue for (you should transpose all the content from this issue to that issue to save peeps the extra unnecessary click). If and when that is fixed, it'll be pulled into Linguist on the next release.

**Comment by Alizter** [comment]
Thanks, sorry for the misunderstanding.
