### ISSUE TITLE
Setting `*.md.liquid linguist-language=Markdown` doesn't enable Markdown rendering with "Rich Diff" in GH pull request

### ISSUE THREAD

**Issue by JLLeitschuh** [github/linguist#6331]
## Describe the bug

Configuring `*.md.liquid linguist-language=Markdown` on a branch in `.gitattributes` should allow those files to be rendered on GitHub as markdown, supporting all features that markdown files have, including supporting rich diffing in pull requests.

### Expected behaviour

I would expect setting `*.md.liquid linguist-language=Markdown` in `.gitattributes` would allow files with the `*.md.liquid` to support the rich diff view in pull requests.

### Additional notes

Example pull request: https://github.com/ossf/omega-moderne-client/pull/7

**Comment by lildude** [comment]
Linguist isn't responsible for the rendering of markup languages. That is controlled by the [markup](https://github.com/github/markup) library which does not honour the Linguist overrides when it comes to rendering files which do not use one of [these](https://github.com/github/markup#markups) extensions. 

This request has already been made twice in the markup repo: https://github.com/github/markup/issues/1102 and https://github.com/github/markup/issues/1069

Closing as this is not a Linguist issue.
