### ISSUE TITLE
*snip*

### ISSUE THREAD

**Issue by mylene611** [github/linguist#6346]
According to [this line of code in heuristics.yml](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.yml#L719), in order for a .tsx file to be classified as language TSX (=> TypeScript), it has to have a line that imports the react module.

However, according to [this blog post that introduced React 17](https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#whats-a-jsx-transform), `With the new transform, you can use JSX without importing React`.

Also, [a JSX (or TSX) file does not have to be a React file](https://betterprogramming.pub/how-to-use-jsx-without-react-21d23346e5dc). I think we should not use the React import statement to identify TSX files.

Moreoever, when developing in next.js, there is even less chance that we need to import the React components, but the files are still TSX files.

Maybe in the .tsx section in the heuristics.yml file, we should put XML before TSX, and remove the pattern for TSX so that it can do a "catch-all" for all .tsx files that do not match the XML pattern?

_Originally posted by @chibiricky in https://github.com/github/linguist/discussions/6340_

**Comment by Alhadis** [comment]
Please stop.
