### ISSUE TITLE
Incorrect YAML syntax highlighting

### ISSUE THREAD

**Issue by uhthomas** [github/linguist#6350]
## Describe the bug

The YAML syntax highlighter breaks on this line:

https://github.com/grafana/agent/blob/ecaf5ea16046a543e1835c6f17cea67d33172aab/cmd/grafana-agent-operator/agent-example-config.yaml#L155

![image](https://user-images.githubusercontent.com/9749173/228687544-f6621e45-d51c-445b-9c89-8ab518a5e266.png)

### Expected behaviour

The syntax highlighter should not break.

**Comment by lildude** [comment]
As per the [troubleshooting doc](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#theres-a-problem-with-the-syntax-highlighting-of-a-file) and [Fixing syntax highlighting](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#fixing-syntax-highlighting) this is a problem with the upstream grammar and so an issue or PR should be opened there. However, we use an old, and now archived, Atom grammar so the only option is to find a maintained grammar that does not experience this issue and submit a PR to [switch grammar sources](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#changing-the-source-of-a-syntax-highlighting-grammar).

Closing as this is not a Linguist bug. Feel free to submit a PR to switch grammars.
