### ISSUE TITLE
Bug in `ttl` highlighting.

### ISSUE THREAD

**Issue by jeswr** [github/linguist#6352]
## Describe the bug

The syntax highlighter supports the `a` abbreviation in Turtle; this works well in examples like

```ttl
ex:jesse a ex:thing
```

However, it also matches against cases it shouldn't, for instance when the letter `a` is the suffix of a prefixed URI such as in the example below

```ttl
ex:a ex:b ex:c
```

### Expected behaviour

The `a` in `ex:a` should not be highlighted in the second example above.

**Comment by lildude** [comment]
As per the [troubleshooting doc](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#theres-a-problem-with-the-syntax-highlighting-of-a-file) and [Fixing syntax highlighting](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#fixing-syntax-highlighting) this is a problem with the upstream grammar and so an issue or PR should be opened there.

Closing as this is not a Linguist bug.

**Comment by jeswr** [comment]
Opened issue upstream
