### ISSUE TITLE
TypoScript incorrectly recognized as TypeScript

### ISSUE THREAD

**Issue by ghost** [github/linguist#638]
It looks like my TypoScript files (.ts) are being incorrectly recognized as TypeScript.

http://en.wikipedia.org/wiki/TYPO3#TypoScript

http://docs.typo3.org/typo3cms/TyposcriptReference/

**Comment by dr2okevin** [comment]
Why was this Closed? More than 3 Years later TypoScript is still missing.

**Comment by J5lx** [comment]
Becaus no one made a PR:

> These will be misidentified without TypoScript added to https://github.com/github/linguist/blob/master/lib/linguist/languages.yml. Closing this, but we'll take a look at PR adding the language.

**Comment by pchaigno** [comment]
Please see the [guidelines to add support for a new language to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). If TypoScript meets the requirement on in-the-wild usage, don't hesitate to open a pull request.

**Comment by dr2okevin** [comment]
I don't understand what in need to do on step 2

**Comment by pchaigno** [comment]
You need to add a grammar for syntax highlighting if you know one, with the command indicated.

**Comment by dr2okevin** [comment]
but what is this grammar? Where can i get one, or how can i create one?

**Comment by pchaigno** [comment]
For grammars, you can use TextMate bundles or Sublime Text/Atom packages. Please see the respective editor's documentation for more information.
