### ISSUE TITLE
Astro syntax highlighting is broken

### ISSUE THREAD

**Issue by zadeviggers** [github/linguist#6381]
## Describe the bug
The syntax highlighting in `.astro` files only highlights the HTML section, but not the frontmatter, style tag contents, and script tag contents.
This only affects the file view and code blocks in issues. The code blocks in issues manage to highlight the frontmatter, but still can't highlight the contents of style and script tags.

An example of the issue can be seen in this file, shown in the screenshots below:
https://github.com/zadeviggers/zade.viggers.net/blob/05689e3133cfd77fc698f5d437464eade3282755/src/components/HowManyYearsAgo.astro

File view:
<img width="624" alt="image" src="https://github.com/github/linguist/assets/74938858/c542dc99-0a53-42ba-bf41-2cc5855d65c9">
</details>

Issue code block:
<img width="639" alt="image" src="https://github.com/github/linguist/assets/74938858/ae7bdca2-057c-4c66-b3ea-e3b67df549da">

### Expected behaviour
Here are the contents of the above file, being highligted correctly in vscode:
<img width="659" alt="image" src="https://github.com/github/linguist/assets/74938858/fa5cd57a-ad8d-4596-9978-b860c656c174">

### Additional notes

The issue could be with the grammar, but I think it's unlikely, given that syntax highlighting works in vscode and behaves differently across the file view and issue code blocks.  

@Princesseuh is in charge of the [language-tools repo](https://github.com/withastro/language-tools), which is used as a submodule here.

**Comment by lildude** [comment]
> @Princesseuh is in charge of the [language-tools repo](https://github.com/withastro/language-tools), which is used as a submodule here.

And that's precisely where you should be logging this issue as this is a problem with the grammar, not Linguist.

See https://github.com/github/linguist/blob/master/docs/troubleshooting.md#theres-a-problem-with-the-syntax-highlighting-of-a-file

**Comment by lildude** [comment]
Actually, now I think about it, this has nothing to do with either Linguist or the grammar. This will be a problem with the various view components, possibly caused by the syntax highlighter. Gists are highlighting differently too.

Please contact GitHub support using the "Contact GitHub" link at the bottom of an affected page.
