### ISSUE TITLE
Dynamically suppress files/folders

### ISSUE THREAD

**Issue by frans-k** [github/linguist#714]
I think files in node_modules/ should be suppressed in diffs, or at least the option for it should exist.

I recently added a module to package.json and ended up with 300 new files and 46k additions in node_modules/, and then made a pull request. That comparison took a while to load.

Related but not exactly the same: https://github.com/github/linguist/issues/137

**Comment by carnesen** [comment]
@tnm Re "Is there any time you wouldn't make `node_modules` ignored?" Here's a use case. When you do `require("module-x")` in Node.js it searches upwards from the file containing the statement until it finds a subdirectory named `node_modules/module-x`. So if I have a bunch of interdependent source-code-controlled modules in a single repository I can make them accessible to each other by simply putting them into a directory named `node_modules`. After git clone and npm install, our repo looks like this:

- monorepo
  - node_modules (Shared 3rd party dependencies. gitignored)
  - src
    - node_modules (our JavaScript modules. Committed to git)
      - module-x
        - node_modules (module_x-specific 3rd party dependencies. gitignored)
      - module-y
        - node_modules (module_y-specific 3rd party dependencies. gitignored)

**Comment by dbkaplun** [comment]
+1. I think a good solution would be to add a URL param like `?exclude="node_modules/*"`. This would match the interface for the existing `?w=` param which toggles whitespace diffing.
