### ISSUE TITLE
Add Liquid super-filter

### ISSUE THREAD

**Issue by parkr** [github/linguist#767]
I write a lot of GitHub Pages websites. It has been wonderful to have the metadata view (though it needs some design work) on markdown files and the like. However, it would be very useful to have a general `liquid` lexer of sorts that would sit above another lexer (like `json` or `markdown`) in order to highlight the liquid bits.

I have found @tpope's [vim-liquid](https://github.com/tpope/vim-liquid) especially useful, as it applies this principle to my vim syntax highlighting.

Thoughts on adding this?

**Comment by arfon** [comment]
> Liquid can be used in any language and may not have the `.liquid` file extension. It may just be unconscionable.

I afraid we just don't have a good way to address this right now. :crying_cat_face:
