### ISSUE TITLE
Shell script not detected

### ISSUE THREAD

**Issue by frm** [github/linguist#802]
I have a repo that currently contains a shell script and it doesn't detect any language. https://github.com/perry23/dsme
But I have another repo that also has a shell script but it is detected: https://github.com/perry23/unix

**Comment by JazzMaster** [comment]
shell scripts by themselves are being reported as C. bash syntax is hardly C.

**Comment by JazzMaster** [comment]
additionally .gitattributes is being ignored.

**Comment by pchaigno** [comment]
@JazzMaster That doesn't look like the same issue. Please open a new issue with required details.
