### ISSUE TITLE
Language identifier

### ISSUE THREAD

**Issue by ghost** [github/linguist#875]
> In your fenced block, add an optional language identifier and
> we'll run it through syntax highlighting.

[&sect; Syntax highlighting](http://help.github.com/articles/github-flavored-markdown#syntax-highlighting)

So, with fenced code blocks we can explicitly state the desired language for highlighting. I feel that this should be applied to files as well. For files with no/unknown extension, no shebang, you could override them if they are misidentified

``` rb
# language: ruby
# the previous line will set the highlighting
def foo
  puts 'foo'
end
```

This would be a boon to all users at GitHub; instead of waiting for a fix in the detection code, you can just add the identifier, then remove it if the auto detect code is fixed.

**Comment by svnpenn** [comment]
For dummies, this can now be done with:

    # -*- mode: sh -*-
