### ISSUE TITLE
Server-side comments in ASPX (C# and VB) not highlighted as comments

### ISSUE THREAD

**Issue by abitgone** [github/linguist#895]
ASP.NET web forms – .aspx files, etc – can use [server-side comments][msdn] that are similar in syntax to HTML comments:
```aspx
<%-- This is a server-side comment --%>
```
Linguist doesn't appear to be picking these up correctly.

[msdn]: http://msdn.microsoft.com/en-us/library/4acf8afk(v=vs.100).aspx

**Comment by arfon** [comment]
@abitgone - what are your thoughts on @pchaigno's last comment. This is an issue with the highlighting grammar https://github.com/textmate/asp.tmbundle/ - could you open an issue here to report the bug?

**Comment by abitgone** [comment]
@arfon: Couldn't agree more. I've submitted a pull request with a patch for the .tmbundle – you can see that [my version highlights the server-side comments correctly now](https://lightshow.githubapp.com/?utf8=✓&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Ftextmate%2Fasp.tmbundle%2Fmaster%2FSyntaxes%2FHTML-ASP.plist&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fabitgone%2Flinguist-aspx-comments%2Fmaster%2Ftest.aspx&code=). 

Thanks for your help.

**Comment by infininight** [comment]
@arfon I've accepted the pull request from @abitgone, ready to be pulled upstream.

**Comment by arfon** [comment]
> @arfon I've accepted the pull request from @abitgone, ready to be pulled upstream.

Great! We should be updating the Linguist gem tomorrow.
