### ISSUE TITLE
NetCDF4 data file is interpreted as netC file

### ISSUE THREAD

**Issue by jessebikman** [github/linguist#958]
I've noticed an issue that affects myself and others; NetCDF4 files in our repos are being falsely interpreted as nesC files due to their .nc file extension. 

NetCDF4 files tend to be large files, but are necessary in repositories for their utility as example NetCDF4 files for oceanographic applications, and thus cannot have their file extensions altered or removed. Is there an exception that could be made so that large files (i.e. > 10 MB) with extension .nc are not parsed as nesC files? This mis-categorization diminishes the SEO utility of Github in an open science development context because the data files are confused with programmatic elements (python code, MATLAB code, etc.). 

Here are some example repositories (mine first):

https://github.com/jessebikman/netCDF4-python-ADCIRC-shapefile

https://github.com/pyugrid/pyugrid

https://github.com/asascience-open/sci-wms

https://github.com/nctoolbox/nctoolbox

**Comment by arfon** [comment]
I've just run through these examples and it appears this issue is now fixed.
